-- upgrade_v2_0_entity_class.sql
-- DeityDB v2.0.0 — schema epoch: controlled entity_class over free-text entity_type.
-- Adds entity_class lookup (19 classes) + entity_type_class_map, fills the 57 blank
-- entity_types from category, adds entities.entity_class (FK + index), backfills, and
-- verifies fail-closed. Idempotent. Apply with: psql -v ON_ERROR_STOP=1 -f this file.

BEGIN;

-- 1. controlled vocabulary
CREATE TABLE IF NOT EXISTS entity_class (
  class_id    text PRIMARY KEY,
  label       text NOT NULL,
  description text,
  sort_order  integer NOT NULL DEFAULT 0
);
INSERT INTO entity_class (class_id,label,description,sort_order) VALUES
  ('deity','Deity','Gods, goddesses, and powers worshipped as divine (incl. primordials, Titans, river & nature gods, deified divine animals).',1),
  ('angel','Angel','Angelic beings of all ranks: archangels, angelic princes, Shem angels, planetary & zodiacal angels, Mandaean uthras.',2),
  ('demon','Demon','Demons, devils, fallen angels, and Goetic spirits of every rank.',3),
  ('aeon','Aeon','Gnostic aeons, archons, and structured emanations of the pleroma.',4),
  ('sefirah','Sefirah','Kabbalistic sefirot and ordered emanation-configurations (partzufim).',5),
  ('spirit','Spirit','Lesser and intermediary spirits: nature spirits (nymphs, nereids, oceanids), daimones, jinn, folkloric and light-world beings.',6),
  ('monster','Monster','Monstrous and chaos beings: dragons, serpents, jotnar, the Echidna/Typhon brood, sea-monsters, mythic beasts.',7),
  ('hero','Hero','Heroes, deified mortals, legendary and saga figures, knights, and cult heroes.',8),
  ('ruler','Ruler','Kings, queens, and rulers as human or legendary figures.',9),
  ('prophet','Prophet','Prophets, messengers, and revealers of divine teaching.',10),
  ('sage','Sage','Religious founders, teachers, theologians, mystics, sages, and clergy.',11),
  ('saint','Saint','Canonized or venerated saints, blesseds, martyrs, and holy ascetics.',12),
  ('scriptural-figure','Scriptural figure','Narrative persons of scripture (patriarchs, matriarchs, biblical and apostolic figures).',13),
  ('abstraction','Abstraction','Personified abstractions, abstract powers and categories, principles, doctrines, and concepts.',14),
  ('collective','Collective','Collectives, groups, orders, movements, and institutional bodies of beings.',15),
  ('realm','Realm','Cosmological places, realms, worlds, and cosmic structures.',16),
  ('ritual','Ritual','Ritual and practice categories, initiatory grades, and ritual abstractions.',17),
  ('title','Title','Devotional titles and apparitions treated as entities (e.g. Marian titles).',18),
  ('object','Object','Sacred objects, relics, betyls, cult images, constructs, and sacred texts.',19)
ON CONFLICT (class_id) DO UPDATE SET
  label=EXCLUDED.label, description=EXCLUDED.description, sort_order=EXCLUDED.sort_order;

-- 2. free-text entity_type -> controlled class map
CREATE TABLE IF NOT EXISTS entity_type_class_map (
  entity_type  text PRIMARY KEY,
  entity_class text NOT NULL REFERENCES entity_class(class_id)
);
INSERT INTO entity_type_class_map (entity_type,entity_class) VALUES
  ('Abbess/saint','saint'),
  ('Abbot/bishop/craftsman saint','saint'),
  ('Abbot/saint','saint'),
  ('Abstract power/category','abstraction'),
  ('Abstract/cosmological category','abstraction'),
  ('Abstract/luminary category','abstraction'),
  ('Abstract/social category','abstraction'),
  ('Abyssal/adversarial being','demon'),
  ('Acts figure','scriptural-figure'),
  ('Adversarial archon','aeon'),
  ('Adversarial being','demon'),
  ('Adversarial collective','collective'),
  ('Adversarial emanation','aeon'),
  ('Adversarial ruler','demon'),
  ('Adversarial/fallen angel','demon'),
  ('Adversarial/female spirit','spirit'),
  ('Aeon / Divine Will','aeon'),
  ('Aeon / Only-begotten','aeon'),
  ('Aeon / personified Faith','aeon'),
  ('Aeon / personified Love','aeon'),
  ('Aeon/cosmic realm','realm'),
  ('Aeon/first thought','aeon'),
  ('Aeon/intellect','aeon'),
  ('Aeon/intellect principle','aeon'),
  ('Aeon/personification','aeon'),
  ('Aeon/personified passion','aeon'),
  ('Aeon/personified thought','aeon'),
  ('Aeon/primordial human','aeon'),
  ('Aeon/principle','aeon'),
  ('Aeon/sub-aeon of Barbelo','aeon'),
  ('Aeonic collective','collective'),
  ('Aeonic collective / second tier of Pleroma','collective'),
  ('Aeonic collective / third tier of Pleroma','collective'),
  ('Afterlife realm','realm'),
  ('Agent/aeon','aeon'),
  ('Agrarian goddess','deity'),
  ('Agrarian/time god','deity'),
  ('Ambivalent deity','deity'),
  ('Anatolian lunar god','deity'),
  ('Anatolian mother goddess','deity'),
  ('Ancestor deity','spirit'),
  ('Ancestor figure','spirit'),
  ('Ancestral collective','collective'),
  ('Angel','angel'),
  ('Angel collective','collective'),
  ('Angel/prince','angel'),
  ('Angelic being','angel'),
  ('Angelic collective','collective'),
  ('Angelic hierarchy','angel'),
  ('Angelic king','angel'),
  ('Angelic order','angel'),
  ('Angelic order/rank','angel'),
  ('Angelic pair','angel'),
  ('Angelic prince','angel'),
  ('Angelic triad','collective'),
  ('Antagonist figure','hero'),
  ('Anthropological category','abstraction'),
  ('Anthropological collective','collective'),
  ('Apocalyptic collective','collective'),
  ('Apocalyptic figure','scriptural-figure'),
  ('Apocalyptic monster','monster'),
  ('Apophatic mystery','abstraction'),
  ('Apostle','sage'),
  ('Apostle and Evangelist','angel'),
  ('Apostle/saint','saint'),
  ('Apostolic Father','sage'),
  ('Apostolic Father / Pope','sage'),
  ('Apostolic figure','scriptural-figure'),
  ('Apostolic/revealer figure','scriptural-figure'),
  ('Apotropaic deity','deity'),
  ('Arcadian goddess','deity'),
  ('Arch-demon','demon'),
  ('Archangel','angel'),
  ('Archangel/exalted being','angel'),
  ('Archangel/prince','angel'),
  ('Archangel/saint','angel'),
  ('Archon','aeon'),
  ('Archon/converted ruler','aeon'),
  ('Archon/gate-guardian','aeon'),
  ('Archon/planetary ruler','aeon'),
  ('Archontic collective','collective'),
  ('Ascended master','sage'),
  ('Ascetic/saint','saint'),
  ('Aspect of deity','deity'),
  ('Assessor of Maat','deity'),
  ('Astral collective','collective'),
  ('Astral deity','spirit'),
  ('Astral deity/personification','spirit'),
  ('Astral ruler collective','collective'),
  ('Astronomical collective','collective'),
  ('Authoritative interpreter/exemplar','sage'),
  ('Biblical figure','scriptural-figure'),
  ('Birth goddess / Fate deity','deity'),
  ('Bishop/craftsman saint','saint'),
  ('Bishop/martyr/saint','saint'),
  ('Bishop/saint','saint'),
  ('Boundary principle','abstraction'),
  ('Boundary/cross principle','abstraction'),
  ('Caliph','ruler'),
  ('Celestial prototype','aeon'),
  ('Celestial sovereign goddess','deity'),
  ('Celestial sphere','collective'),
  ('Chaos bird / Storm monster','monster'),
  ('Chaos monster','monster'),
  ('Chaos serpent','monster'),
  ('Chief deity','deity'),
  ('Chief deity / Moon god','deity'),
  ('Child deity','deity'),
  ('Child-harming spirit','spirit'),
  ('Chthonic cult form','deity'),
  ('Chthonic deity','deity'),
  ('Chthonic deity / deity of vital abundance','deity'),
  ('Chthonic god','deity'),
  ('Chthonic god/title','deity'),
  ('Chthonic goddess','deity'),
  ('Chthonic monster/being','monster'),
  ('Chthonic serpent','monster'),
  ('Chthonic/liminal goddess','deity'),
  ('Chthonic/mystery goddess','deity'),
  ('Church Father','sage'),
  ('Church Father / Cappadocian','sage'),
  ('Church Father / Doctor','sage'),
  ('Church Father / Doctor / Pope','sage'),
  ('Church Father / apologist','sage'),
  ('Church Father / theologian','sage'),
  ('City god','deity'),
  ('Civic god','deity'),
  ('Clergy order','sage'),
  ('Cobra goddess','deity'),
  ('Collective','collective'),
  ('Collective / grouping','collective'),
  ('Collective / hub','collective'),
  ('Collective category','collective'),
  ('Collective/disciple body','collective'),
  ('Collective/divine category','collective'),
  ('Companion','hero'),
  ('Companion spirit','spirit'),
  ('Concept','abstraction'),
  ('Connective power collective','collective'),
  ('Construct','object'),
  ('Cosmic being','spirit'),
  ('Cosmic being/order','spirit'),
  ('Cosmic builder','deity'),
  ('Cosmic deity','deity'),
  ('Cosmic god collective','collective'),
  ('Cosmic mechanism/category','abstraction'),
  ('Cosmic power','abstraction'),
  ('Cosmic realm','realm'),
  ('Cosmic realm/category','realm'),
  ('Cosmic ruler/archon','aeon'),
  ('Cosmic soul','abstraction'),
  ('Cosmic structure','realm'),
  ('Cosmogonic principle','abstraction'),
  ('Cosmogonic process','abstraction'),
  ('Cosmological category','abstraction'),
  ('Cosmological concept','abstraction'),
  ('Cosmological place/category','realm'),
  ('Cosmological principle','abstraction'),
  ('Cosmological process','abstraction'),
  ('Cosmological realm','realm'),
  ('Cosmological structure','realm'),
  ('Craft being collective','collective'),
  ('Craft category','abstraction'),
  ('Craft god','deity'),
  ('Creator deity','deity'),
  ('Creator/ruler figure','deity'),
  ('Cryptid','monster'),
  ('Cult figure/title','title'),
  ('Cult object','object'),
  ('Cult title/aspect','title'),
  ('Cult title/deity type','deity'),
  ('Cultural number-devotion','abstraction'),
  ('Culture hero/inventor','hero'),
  ('Curete/guardian','deity'),
  ('Daimon','spirit'),
  ('Daimon collective','collective'),
  ('Daimon collective/craftsmen','collective'),
  ('Daimon/ghost','spirit'),
  ('Daimon/giant craftsmen collective','collective'),
  ('Daimon/god','spirit'),
  ('Daimon/goddess','spirit'),
  ('Daimon/monster','monster'),
  ('Daimon/personification','spirit'),
  ('Deacon','scriptural-figure'),
  ('Dead/ancestral collective','collective'),
  ('Death angel','angel'),
  ('Death god','deity'),
  ('Death spirits collective','collective'),
  ('Decan power','abstraction'),
  ('Deified emperor','deity'),
  ('Deified figure','hero'),
  ('Deified figure/divine claimant','deity'),
  ('Deified human','hero'),
  ('Deified mortal','hero'),
  ('Deified mortal/goddess','hero'),
  ('Deified mortal/sea goddess','hero'),
  ('Deity','deity'),
  ('Deity (as believed)','deity'),
  ('Deity collective','collective'),
  ('Deity/deified figure','deity'),
  ('Demiurge/world-maker','deity'),
  ('Demiurgic archon','aeon'),
  ('Demiurgic archon/name','aeon'),
  ('Demiurgic intellect','aeon'),
  ('Demiurgic/adversarial name','demon'),
  ('Demiurgic/lightworld being','spirit'),
  ('Demon','demon'),
  ('Demon class','demon'),
  ('Demon collective','collective'),
  ('Demoness','demon'),
  ('Demonic collective','collective'),
  ('Demonic power','demon'),
  ('Demonic realm','realm'),
  ('Demonic/adversarial being','demon'),
  ('Desert deity','deity'),
  ('Disciple','sage'),
  ('Disciple/saint','saint'),
  ('Disease demon','demon'),
  ('Divinatory practice','ritual'),
  ('Divinatory system','deity'),
  ('Divine attribute / Manifestation','deity'),
  ('Divine being','deity'),
  ('Divine collective','collective'),
  ('Divine feminine/aeon','aeon'),
  ('Divine hero','hero'),
  ('Divine lord','deity'),
  ('Divine manifestation','deity'),
  ('Divine mind','deity'),
  ('Divine mother / Cow goddess','deity'),
  ('Divine name/principle','abstraction'),
  ('Divine names','deity'),
  ('Divine person','deity'),
  ('Divine personification','abstraction'),
  ('Divine power','abstraction'),
  ('Divine power/principle','abstraction'),
  ('Divine presence','deity'),
  ('Divine principle/person','abstraction'),
  ('Divine title/form','deity'),
  ('Divine tribunal','deity'),
  ('Divine units','deity'),
  ('Divine word/reason','deity'),
  ('Divine/heroic figure','hero'),
  ('Doctrine','abstraction'),
  ('Dragon','monster'),
  ('Dragon demon','monster'),
  ('Dragon/serpent','monster'),
  ('Dream daimon','spirit'),
  ('Duat region','realm'),
  ('Dwarf','spirit'),
  ('Dying/fertility god','deity'),
  ('Dynastic god','deity'),
  ('Earth/creator deity','deity'),
  ('Earth/netherworld deity','deity'),
  ('Ecclesial/social category','abstraction'),
  ('Egregore','spirit'),
  ('Elect collective','collective'),
  ('Elect collective/category','collective'),
  ('Elemental power/category','spirit'),
  ('Elemental/place category','realm'),
  ('Elemental/weather category','spirit'),
  ('Elemental/weather power/category','spirit'),
  ('Eleusinian figure','hero'),
  ('Eleusinian hero','hero'),
  ('Eloquence/war god','deity'),
  ('Enchanter','hero'),
  ('Enchantress','hero'),
  ('Enochian king','angel'),
  ('Enochian prince','angel'),
  ('Equestrian god','deity'),
  ('Eschatological adversary','demon'),
  ('Eschatological being','spirit'),
  ('Eschatological category','abstraction'),
  ('Eschatological collective','collective'),
  ('Eschatological figure','scriptural-figure'),
  ('Esoteric correspondence system','abstraction'),
  ('Evangelist','angel'),
  ('Fallen aeon/penitent','aeon'),
  ('Fallen angel','demon'),
  ('Fallen angel/desert power','demon'),
  ('Fate collective','collective'),
  ('Fate deity/personification','abstraction'),
  ('Fate goddess','deity'),
  ('Female spirit collective','collective'),
  ('Fertility deity','deity'),
  ('Fertility god','deity'),
  ('Fertility/sky goddess','deity'),
  ('Fire giant','monster'),
  ('Fire/craft god','deity'),
  ('First aeon/mother principle','aeon'),
  ('First human / Patriarch','scriptural-figure'),
  ('Flood survivor / Immortal mortal','hero'),
  ('Flower goddess / divine creation','deity'),
  ('Folk saint','saint'),
  ('Folkloric being','spirit'),
  ('Fomorian','monster'),
  ('Foreign king','ruler'),
  ('Founder/saint','saint'),
  ('Friar/saint','saint'),
  ('Frog goddess','deity'),
  ('Frontier deity','deity'),
  ('Functional deity','deity'),
  ('Funerary deity','deity'),
  ('Funerary deity collective','collective'),
  ('Giant','monster'),
  ('Giant divine king','deity'),
  ('Giant/adversarial collective','collective'),
  ('God','deity'),
  ('God of the dead','deity'),
  ('God-king','deity'),
  ('God/personification','abstraction'),
  ('Goddess','deity'),
  ('Goddess / Early Theban deity','deity'),
  ('Goddess / Feminine form of Zeus','deity'),
  ('Goddess / Queen of Heaven','deity'),
  ('Goddess collective','collective'),
  ('Goddess/cult aspect','deity'),
  ('Goddess/daimon','spirit'),
  ('Goddess/epithet','deity'),
  ('Goddess/maiden','deity'),
  ('Goddess/personification','abstraction'),
  ('Goddess/saint bridge','saint'),
  ('Godhead/principle','abstraction'),
  ('Goetic Duke','demon'),
  ('Goetic Duke and Earl','demon'),
  ('Goetic Earl','demon'),
  ('Goetic Earl and President','demon'),
  ('Goetic Earl and Prince','demon'),
  ('Goetic King','demon'),
  ('Goetic King and Earl','demon'),
  ('Goetic King and President','demon'),
  ('Goetic Knight','demon'),
  ('Goetic Marquis','demon'),
  ('Goetic Marquis and Earl','demon'),
  ('Goetic President','demon'),
  ('Goetic President and Earl','demon'),
  ('Goetic Prince','demon'),
  ('Gorgon/monster','monster'),
  ('Gospel figure','scriptural-figure'),
  ('Grace goddess','deity'),
  ('Grain/sky deity','deity'),
  ('Great goddess (mystery cult)','deity'),
  ('Great goddess / Divine mistress','deity'),
  ('Guardian daimon','spirit'),
  ('Guardian spirit','spirit'),
  ('Guardian uthra','angel'),
  ('Guardian/authoritative interpreter','sage'),
  ('Hadith narrator','sage'),
  ('Hammer god','deity'),
  ('Harvest/fate goddess','deity'),
  ('Healing daimon/deity','spirit'),
  ('Healing god','deity'),
  ('Healing god/deified mortal','hero'),
  ('Healing goddess','deity'),
  ('Healing goddess/personification','abstraction'),
  ('Healing hero','hero'),
  ('Hearth goddess','deity'),
  ('Heavenly human','spirit'),
  ('Heavenly redeemer','deity'),
  ('Helper-saint','saint'),
  ('Hermit/saint','saint'),
  ('Hero','hero'),
  ('Hero / Leader','hero'),
  ('Hero / Semi-divine king','hero'),
  ('Hero-daimon','spirit'),
  ('Hero-god','hero'),
  ('Hero-gods collective','collective'),
  ('Hero/deified mortal/cult figure','hero'),
  ('Heroic spirit collective','collective'),
  ('Heroine','hero'),
  ('Hesperid','spirit'),
  ('Hidden Imam/eschatological figure','sage'),
  ('Hidden form of Ra','deity'),
  ('Hidden saint collective','collective'),
  ('Hidden saint office','saint'),
  ('High god','deity'),
  ('High priest','sage'),
  ('Higher cosmic realm/category','realm'),
  ('Hippopotamus goddess','deity'),
  ('Holy collective','collective'),
  ('Holy figure','saint'),
  ('Holy figure/saint','saint'),
  ('Hora/seasonal goddess','deity'),
  ('Horned god','deity'),
  ('Horse goddess','deity'),
  ('Horus form','deity'),
  ('Household cult form','deity'),
  ('Household deity collective','collective'),
  ('Household spirit collective','collective'),
  ('Human collective','collective'),
  ('Hymnographer/saint','saint'),
  ('Imam','sage'),
  ('Imam/holy figure','sage'),
  ('Imam/martyr','saint'),
  ('Immortalized mortal','hero'),
  ('Infernal officer','demon'),
  ('Infernal prince','demon'),
  ('Initiate order','collective'),
  ('Initiatory power collective','collective'),
  ('Institution','collective'),
  ('Institution/office','collective'),
  ('Inundation deity','deity'),
  ('Jackal deity','deity'),
  ('Jinn subtype','spirit'),
  ('Judge','scriptural-figure'),
  ('Judgment symbol/category','abstraction'),
  ('Judgment/lightworld being','spirit'),
  ('Jurist-founder','sage'),
  ('Jötunn','monster'),
  ('Keeper of winds','deity'),
  ('King','ruler'),
  ('King / Wisdom figure','ruler'),
  ('King/saint','saint'),
  ('King/war god','deity'),
  ('Knight','hero'),
  ('Knowledge category','abstraction'),
  ('Legal/eschatological category','abstraction'),
  ('Legendary figure','hero'),
  ('Light collective','collective'),
  ('Light judge/savior figure','aeon'),
  ('Light-overseer/First Man','deity'),
  ('Light-purifier/receiver','aeon'),
  ('Lightworld being','spirit'),
  ('Lightworld collective','collective'),
  ('Lightworld savior','deity'),
  ('Lightworld savior/warrior','deity'),
  ('Lightworld warrior','deity'),
  ('Lioness goddess','deity'),
  ('Lioness goddess / Hunter','deity'),
  ('Litany collective','collective'),
  ('Literary human figure','scriptural-figure'),
  ('Local deity','deity'),
  ('Local goddess','deity'),
  ('Local serpent god','deity'),
  ('Lord of Heaven / sky and storm deity','deity'),
  ('Lotus deity','deity'),
  ('Love/fertility goddess','deity'),
  ('Love/war goddess','deity'),
  ('Love/youth god','deity'),
  ('Lower Sophia','aeon'),
  ('Luminary/aeon','aeon'),
  ('Lunar deity','deity'),
  ('Lunar deity / Tribal deity','deity'),
  ('Lusitanian deity / oath and settlement goddess','deity'),
  ('Magical deity','deity'),
  ('Magical order','collective'),
  ('Magician-king','ruler'),
  ('Maintaining power collective','collective'),
  ('Major deity','deity'),
  ('Major goddess','deity'),
  ('Manifestation/Prophet-founder','prophet'),
  ('Marian apparition','title'),
  ('Marian title/apparition','title'),
  ('Marian veneration','title'),
  ('Martyr/saint','saint'),
  ('Matriarch','scriptural-figure'),
  ('Melian nymph','spirit'),
  ('Meroitic deity / syncretized with Anhur-Shu','deity'),
  ('Meroitic goddess / consort of Apedemak','deity'),
  ('Messenger (rasul)','prophet'),
  ('Messenger/trade god','deity'),
  ('Messiah/incarnate Logos','deity'),
  ('Military commander','hero'),
  ('Military/storm god','deity'),
  ('Mistress/Potnia','deity'),
  ('Monk/abbot/saint','saint'),
  ('Monk/saint','saint'),
  ('Monk/theologian','saint'),
  ('Monster','monster'),
  ('Monster category','monster'),
  ('Monster/giant','monster'),
  ('Monster/serpent','monster'),
  ('Moon deity','deity'),
  ('Moon deity / State god','deity'),
  ('Moon god','deity'),
  ('Moon goddess / Divine consort','deity'),
  ('Moral abstraction','abstraction'),
  ('Mother goddess','deity'),
  ('Mother goddess / Divine consort','deity'),
  ('Mother goddess collective','collective'),
  ('Mother of the Believers','scriptural-figure'),
  ('Movement','collective'),
  ('Muse','deity'),
  ('Musical figure','hero'),
  ('Musical hero','hero'),
  ('Mystery cult deity','deity'),
  ('Mystery god/daimon','spirit'),
  ('Mystery gods collective','collective'),
  ('Mystic','sage'),
  ('Mystic/saint','saint'),
  ('Mystical archetype/category','sage'),
  ('Mystical doctrine/category','sage'),
  ('Mystical knowledge/category','sage'),
  ('Mystical love/category','sage'),
  ('Mystical path/category','sage'),
  ('Mystical process/category','sage'),
  ('Mythic adversarial collective','collective'),
  ('Mythic process/category','abstraction'),
  ('Mythical animal','monster'),
  ('Naiad','spirit'),
  ('Naiad/nymph','spirit'),
  ('National deity','deity'),
  ('Nature category','abstraction'),
  ('Nereid','spirit'),
  ('Nereid/sea queen','spirit'),
  ('Netherworld being','spirit'),
  ('Netherworld/place power','abstraction'),
  ('Norn','deity'),
  ('Number-hermeneutic practice','ritual'),
  ('Nun/saint','saint'),
  ('Nymph','spirit'),
  ('Nymph collective','collective'),
  ('Nymph/goat nurse','spirit'),
  ('Nymph/goddess collective','collective'),
  ('Nymph/worshipper collective','collective'),
  ('Nymph?','spirit'),
  ('Oceanid','spirit'),
  ('Oceanid/Titaness','deity'),
  ('Oceanid/nymph','spirit'),
  ('Oceanid/personification','spirit'),
  ('Oceanid/river goddess','spirit'),
  ('Oceanid/sea goddess','spirit'),
  ('Office / Lineage','collective'),
  ('Olympian god','deity'),
  ('Olympian goddess','deity'),
  ('Olympian/mystery god','deity'),
  ('Olympic spirit','spirit'),
  ('Operative angel','angel'),
  ('Oread','spirit'),
  ('Orphic goddess','deity'),
  ('Orphic primordial deity','deity'),
  ('Orphic/Dionysian god','deity'),
  ('Otherworld craftsman god','deity'),
  ('Otherworld king','deity'),
  ('Otherworld realm','realm'),
  ('Otherworld-adjacent king','deity'),
  ('Paradise beings','spirit'),
  ('Partzuf','sefirah'),
  ('Patriarch','scriptural-figure'),
  ('Patriarch / Flood hero','hero'),
  ('Patriarch/visionary figure','scriptural-figure'),
  ('Peacemaker figure','hero'),
  ('Personal/divine spirit','spirit'),
  ('Personified abstraction','abstraction'),
  ('Personified fate','abstraction'),
  ('Personified passion','aeon'),
  ('Personified power','abstraction'),
  ('Personified virtue','abstraction'),
  ('Personified wisdom','abstraction'),
  ('Physician martyrs/saints','saint'),
  ('Pilgrim/saint','saint'),
  ('Place/environment category','realm'),
  ('Place/liminal category','realm'),
  ('Plague/war deity','deity'),
  ('Planetary angel','angel'),
  ('Planetary intelligence','spirit'),
  ('Planetary power/category','abstraction'),
  ('Planetary ruler collective','collective'),
  ('Planetary spirit','spirit'),
  ('Planetary/luminary power/category','abstraction'),
  ('Pleiad nymph','spirit'),
  ('Possessing spirit','spirit'),
  ('Praeterhuman intelligence','spirit'),
  ('Priest','sage'),
  ('Priest / Ancestor','spirit'),
  ('Primordial being','deity'),
  ('Primordial deity','deity'),
  ('Primordial deity collective','collective'),
  ('Primordial giant','monster'),
  ('Primordial goddess','deity'),
  ('Primordial high god','deity'),
  ('Primordial human','deity'),
  ('Primordial king','ruler'),
  ('Primordial rebel god','deity'),
  ('Primordial sea being','deity'),
  ('Primordial sea goddess','deity'),
  ('Prophet','prophet'),
  ('Prophet / Fiery prophet','prophet'),
  ('Prophet / Lawgiver','prophet'),
  ('Prophet/messenger','prophet'),
  ('Prophet/revealer','prophet'),
  ('Prophet/saint','saint'),
  ('Prophet/teacher','prophet'),
  ('Prophetic figure/type','prophet'),
  ('Protective deity','deity'),
  ('Protective goddess','deity'),
  ('Protective household deity','deity'),
  ('Protogenos/Primordial','deity'),
  ('Providential category','abstraction'),
  ('Queen','ruler'),
  ('Queen of Heaven','deity'),
  ('Ram deity','deity'),
  ('Recording angel collective','collective'),
  ('Reformer / Leader','sage'),
  ('Relic','object'),
  ('Religious movement / collective','collective'),
  ('Revealed art','ritual'),
  ('Revealer','prophet'),
  ('Revealer symbol/being','spirit'),
  ('Revealer/ancestral figure','prophet'),
  ('Revealer/angelic figure','angel'),
  ('Revealer/daimon','spirit'),
  ('Revealer/life figure','aeon'),
  ('Revealer/savior','deity'),
  ('Revealer/savior figure','prophet'),
  ('Revelatory category','abstraction'),
  ('Ritual','ritual'),
  ('Ritual category','ritual'),
  ('Ritual daimon collective','collective'),
  ('Ritual mechanism/category','ritual'),
  ('Ritual river/category','ritual'),
  ('Ritual/cosmological process','ritual'),
  ('Ritual/devotional category','ritual'),
  ('Ritual/medical abstraction','ritual'),
  ('Ritual/medical category','ritual'),
  ('Ritual/social category','ritual'),
  ('Ritual/symbolic category','ritual'),
  ('River god/Potamos','deity'),
  ('River goddess','deity'),
  ('Roman official','scriptural-figure'),
  ('Royal martyr/saint','saint'),
  ('Royal saint','saint'),
  ('Ruler','ruler'),
  ('Ruler collective','collective'),
  ('Rustic daimon/deity','spirit'),
  ('Rustic fertility god','deity'),
  ('Rustic god','deity'),
  ('Rustic god/deified mortal','hero'),
  ('Sacramental hierarchy','ritual'),
  ('Sacred Place','realm'),
  ('Sacred betyl','object'),
  ('Sacred bull','deity'),
  ('Sacred object','object'),
  ('Sacred place','realm'),
  ('Sacred power','abstraction'),
  ('Sacred text','object'),
  ('Sacred text/principle','abstraction'),
  ('Sacred vehicle/category','abstraction'),
  ('Sacred-number doctrine','abstraction'),
  ('Sage','sage'),
  ('Sage collective','collective'),
  ('Saint','saint'),
  ('Saint collective','collective'),
  ('Saint/disciple','saint'),
  ('Savior aeon','aeon'),
  ('Savior aspect','deity'),
  ('Savior figure','prophet'),
  ('Scripture','object'),
  ('Scripture/concept','abstraction'),
  ('Sea god','deity'),
  ('Sea god/deified child','deity'),
  ('Sea god/deified mortal','hero'),
  ('Sea goddess','deity'),
  ('Sea goddess/deified mortal','hero'),
  ('Sea monster','monster'),
  ('Sea monster/daimon','monster'),
  ('Sea/otherworld god','deity'),
  ('Sea/prosperity god','deity'),
  ('Seer/healer hero','hero'),
  ('Seer/prophetic hero','hero'),
  ('Seer/prophetic heroine','hero'),
  ('Sefirah','sefirah'),
  ('Self-generated aeon','aeon'),
  ('Sephirah','sefirah'),
  ('Serpent deity','deity'),
  ('Serpent/netherworld being','monster'),
  ('Shem angel','angel'),
  ('Skill/sovereignty god','deity'),
  ('Smith god','deity'),
  ('Solar barque crew','deity'),
  ('Solar deity','deity'),
  ('Solar form','deity'),
  ('Solar god (imperial cult)','deity'),
  ('Solar goddess','deity'),
  ('Solar hero','hero'),
  ('Solar justice god','deity'),
  ('Solar/falcon deity','deity'),
  ('Solar/storm god','deity'),
  ('Sorcerer','hero'),
  ('Soteriological process/category','abstraction'),
  ('Soteriological realm/category','realm'),
  ('Soteriological substance/category','abstraction'),
  ('Soteriological/devotional category','abstraction'),
  ('Soul collective','collective'),
  ('Sovereignty goddess','deity'),
  ('Spirit','spirit'),
  ('Spirit collective','collective'),
  ('Spirit/demon class','demon'),
  ('Spirit/personified power','spirit'),
  ('Spirit/wind power','spirit'),
  ('Spiritual authority/category','abstraction'),
  ('Spiritual office','abstraction'),
  ('Spiritual type/category','abstraction'),
  ('Spiritual/social category','abstraction'),
  ('Spring deity','deity'),
  ('Star goddess / destiny figure','deity'),
  ('State god','deity'),
  ('State god / dying deity','deity'),
  ('Stellar god','deity'),
  ('Stellar goddess','deity'),
  ('Storm deity','deity'),
  ('Storm god','deity'),
  ('Sublunar daimon collective','collective'),
  ('Succession deity','deity'),
  ('Suffering savior','deity'),
  ('Sufi ascetic/saint','saint'),
  ('Sufi martyr','saint'),
  ('Sufi master/author','sage'),
  ('Sufi metaphysician','sage'),
  ('Sufi philosopher','sage'),
  ('Sufi poet','sage'),
  ('Sufi saint','saint'),
  ('Sufi saint/order founder','saint'),
  ('Sufi theologian','sage'),
  ('Sun deity','deity'),
  ('Sun goddess','deity'),
  ('Supernatural collective category','collective'),
  ('Supreme deity','deity'),
  ('Supreme god','deity'),
  ('Supreme principle','abstraction'),
  ('Supreme principle/aeon','aeon'),
  ('Supreme principle/savior','abstraction'),
  ('Symbolic category','abstraction'),
  ('Symbolic figure / archetype','abstraction'),
  ('Symbolic figure / venerated being','spirit'),
  ('Symbolic identity category','abstraction'),
  ('Symbolic/cosmological category','abstraction'),
  ('Symbolic/ritual category','ritual'),
  ('Syncretic deity','deity'),
  ('Thelemic deity','deity'),
  ('Theologian','sage'),
  ('Theological category','sage'),
  ('Theological concept','sage'),
  ('Thoughtform','spirit'),
  ('Thracian goddess','deity'),
  ('Thracian sky deity','deity'),
  ('Thracian sky-thunder god','deity'),
  ('Threshold god','deity'),
  ('Thunder god','deity'),
  ('Titan','deity'),
  ('Titan/Titaness','deity'),
  ('Titaness/cult aspect','deity'),
  ('Tragic queen/goddess','deity'),
  ('Transcendent god collective','collective'),
  ('Tribal god','deity'),
  ('Trickster magician','hero'),
  ('Trickster/adversarial being','spirit'),
  ('Tutelary collective','collective'),
  ('Tutelary deity','deity'),
  ('Tutelary figure','deity'),
  ('Underworld collective','collective'),
  ('Underworld daimon','spirit'),
  ('Underworld daimon collective','collective'),
  ('Underworld deity','deity'),
  ('Underworld god','deity'),
  ('Underworld goddess','deity'),
  ('Underworld judge','deity'),
  ('Underworld king','deity'),
  ('Underworld monster/guardian','monster'),
  ('Underworld nymph','spirit'),
  ('Underworld nymph collective','collective'),
  ('Underworld queen','deity'),
  ('Underworld river god','deity'),
  ('Underworld river goddess','deity'),
  ('Underworld ruler','deity'),
  ('Underworld serpent','monster'),
  ('Underworld serpent guardian','monster'),
  ('Underworld/fertility goddess','deity'),
  ('Underworld/place power','abstraction'),
  ('Underworld/war god','deity'),
  ('Vanir being','deity'),
  ('Vegetation deity','deity'),
  ('Vegetation heroine','hero'),
  ('Vegetation/fertility deity','deity'),
  ('Venus / morning star goddess','deity'),
  ('Venus deity / War deity','deity'),
  ('Villain','scriptural-figure'),
  ('Virgin martyr/saint','saint'),
  ('Virgin mother/aeon','aeon'),
  ('Virgin-martyr/saint','saint'),
  ('Virgin/saint','saint'),
  ('Virtue/category','abstraction'),
  ('Vulture goddess','deity'),
  ('War deity','deity'),
  ('War god','deity'),
  ('War goddess','deity'),
  ('War/agriculture god','deity'),
  ('War/fertility goddess','deity'),
  ('War/law god','deity'),
  ('War/sovereignty goddess','deity'),
  ('Warrior figure/divine name','hero'),
  ('Watcher leader','angel'),
  ('Wild man / Hero companion','hero'),
  ('Wind demon','demon'),
  ('Wind god','deity'),
  ('Wind gods collective','collective'),
  ('Wind spirit','spirit'),
  ('Wine/ecstatic god','deity'),
  ('Wisdom being','spirit'),
  ('Wisdom/creator god','deity'),
  ('Wise elder goddess','deity'),
  ('Wolf monster','monster'),
  ('World serpent','monster'),
  ('World teacher','sage'),
  ('World tree','realm'),
  ('Writing/grain goddess','deity'),
  ('Writing/wisdom god','deity'),
  ('Yazata','deity'),
  ('Youthful/messenger god','deity'),
  ('air spirit / water mother / cosmogonic deity','spirit'),
  ('ancestral deity','deity'),
  ('archangel of resurrection and souls of the dead','angel'),
  ('archangel of vengeance and divine justice','angel'),
  ('archangel over spirits who transgress','angel'),
  ('ascended master','sage'),
  ('being','spirit'),
  ('binding deity / protective war god','deity'),
  ('chief deity of the Nabataeans / sky and mountain god','deity'),
  ('chief god / sky sovereign','deity'),
  ('chthonic goddess / regeneration deity','deity'),
  ('city god of Susa / lord of the dead','deity'),
  ('city goddess / enthroned queen','deity'),
  ('collective','collective'),
  ('collective / cult grouping','collective'),
  ('concept','abstraction'),
  ('creator deity / lord of Musawwarat','deity'),
  ('deity','deity'),
  ('deity / Sabine goddess of abundance and harvest','deity'),
  ('deity / deified revealer figure','deity'),
  ('deity / goddess of flowering plants and spring','deity'),
  ('deity / guardian of forests and boundaries','deity'),
  ('deity / prophetic goddess and patroness of childbirth','deity'),
  ('deity / prophetic wild nature god','deity'),
  ('deity / prophetic woodpecker deity','deity'),
  ('divine principle','abstraction'),
  ('doctrine','abstraction'),
  ('earth goddess','deity'),
  ('figure','sage'),
  ('fire deity','deity'),
  ('folk spirit','spirit'),
  ('folklore_being','spirit'),
  ('forest deity','deity'),
  ('forest goddess / patroness of bears','deity'),
  ('giant hybrid offspring of Watchers and human women','angel'),
  ('god of writing, wisdom, and dreams','deity'),
  ('goddess / consort of Khaldi','deity'),
  ('goddess of fate and death','deity'),
  ('goddess of fertility, love, and war','deity'),
  ('goddess of love and water','deity'),
  ('goddess of war and motherhood','deity'),
  ('great Syrian goddess / fish goddess','deity'),
  ('great god / water deity','deity'),
  ('great goddess / mother goddess','deity'),
  ('guardian deity','deity'),
  ('healing / oracular deity','deity'),
  ('hero','hero'),
  ('heroine','hero'),
  ('human','hero'),
  ('hypostasis','aeon'),
  ('initiatory_grade','ritual'),
  ('legendary_figure','hero'),
  ('lion war god / royal deity','deity'),
  ('lord of the forest / hunting deity','deity'),
  ('monster','monster'),
  ('movement','collective'),
  ('narrative_cycle','abstraction'),
  ('ogre','monster'),
  ('order','collective'),
  ('person','sage'),
  ('place','realm'),
  ('ritual','ritual'),
  ('river and mountain goddess','deity'),
  ('sanctified human','saint'),
  ('sea deity / lord of the waters','deity'),
  ('serpent','monster'),
  ('shaman-bard / culture hero / primordial sage','sage'),
  ('shamanistic mistress of Pohjola','hero'),
  ('sky / fire deity','deity'),
  ('sky god','deity'),
  ('solar deity / lord of the Abaton','deity'),
  ('spirit','spirit'),
  ('spirit / witch figure','spirit'),
  ('storm deity / national god of Aram-Damascus','deity'),
  ('storm god / thunder deity','deity'),
  ('sun and fertility goddess','deity'),
  ('supreme deity / sky father','deity'),
  ('supreme deity / war god','deity'),
  ('syncretic deity / warrior form','hero'),
  ('text','object'),
  ('thunder god / sky father','deity'),
  ('tradition_hub','collective'),
  ('vegetation deity / dying-and-rising consort','deity'),
  ('war deity / dragon-slayer','deity'),
  ('witch','spirit'),
  ('world-tree','realm')
ON CONFLICT (entity_type) DO UPDATE SET entity_class=EXCLUDED.entity_class;

-- 3. fill the 57 blank entity_types from their category (normalized)
UPDATE entities SET entity_type='Disease demon' WHERE (entity_type IS NULL OR btrim(entity_type)='') AND btrim(category)='Disease Demon';
UPDATE entities SET entity_type='Demon' WHERE (entity_type IS NULL OR btrim(entity_type)='') AND btrim(category)='Demon';
UPDATE entities SET entity_type='Angelic being' WHERE (entity_type IS NULL OR btrim(entity_type)='') AND btrim(category)='Angelic Being';
UPDATE entities SET entity_type='Dragon demon' WHERE (entity_type IS NULL OR btrim(entity_type)='') AND btrim(category)='Dragon Demon';
UPDATE entities SET entity_type='Sea monster' WHERE (entity_type IS NULL OR btrim(entity_type)='') AND btrim(category)='Sea Monster';
UPDATE entities SET entity_type='Ritual category' WHERE (entity_type IS NULL OR btrim(entity_type)='') AND btrim(category)='Ritual Category';
UPDATE entities SET entity_type='Child-harming spirit' WHERE (entity_type IS NULL OR btrim(entity_type)='') AND btrim(category)='Child-Harming Spirit';
UPDATE entities SET entity_type='Wind demon' WHERE (entity_type IS NULL OR btrim(entity_type)='') AND btrim(category)='Wind Demon';
UPDATE entities SET entity_type='Wind spirit' WHERE (entity_type IS NULL OR btrim(entity_type)='') AND btrim(category)='Wind Spirit';

-- 4. add the column and backfill from the map
ALTER TABLE entities ADD COLUMN IF NOT EXISTS entity_class text;
UPDATE entities e SET entity_class = m.entity_class
  FROM entity_type_class_map m WHERE e.entity_type = m.entity_type;

-- 5. constraints + index
CREATE INDEX IF NOT EXISTS idx_entities_class ON entities(entity_class);
ALTER TABLE entities DROP CONSTRAINT IF EXISTS entities_entity_class_fkey;
ALTER TABLE entities ADD CONSTRAINT entities_entity_class_fkey
  FOREIGN KEY (entity_class) REFERENCES entity_class(class_id);

-- 6. fail-closed verification
DO $$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM entities WHERE entity_type IS NULL OR btrim(entity_type)='';
  IF n<>0 THEN RAISE EXCEPTION 'v2.0 gate: % blank entity_type remain', n; END IF;
  SELECT count(*) INTO n FROM entities WHERE entity_class IS NULL;
  IF n<>0 THEN RAISE EXCEPTION 'v2.0 gate: % entities with NULL entity_class', n; END IF;
  SELECT count(DISTINCT e.entity_type) INTO n FROM entities e
    LEFT JOIN entity_type_class_map m ON e.entity_type=m.entity_type WHERE m.entity_type IS NULL;
  IF n<>0 THEN RAISE EXCEPTION 'v2.0 gate: % entity_types not in the class map', n; END IF;
END $$;

COMMIT;

-- post-commit report
SELECT ec.sort_order, e.entity_class, ec.label, count(*) AS entities
  FROM entities e JOIN entity_class ec ON e.entity_class=ec.class_id
  GROUP BY 1,2,3 ORDER BY 1;
