-- scripts/add_zoroastrian_yazatas.sql
-- Rebalancing pass: Zoroastrian yazatas, Fravashis, and the final Saoshyant from
-- the Yashts (Darmesteter SBE / avesta.org). Verbatim, substring-gated. No AI prose.
-- (Bundahishn creatures Gaokerena/Gopatshah/Gavaevodata/Hadhayans and Kavi Vishtaspa
-- deferred: not cleanly in the fetched Yasht text.)

BEGIN;

INSERT INTO entities
  (entity_id, canonical_name, tradition, entity_type, category, primary_domains, cult_scope, primary_period, evidence_confidence, review_status, inclusion_basis, earth_association_score, chthonic_flag, serpent_flag, short_note, entity_class)
VALUES
('ENT_ZOR_SATAVAESA','Satavaesa','Zoroastrian','Yazata','Astral Deity','Satavaesa; yazata; Zoroastrian worship','Zoroastrian','Avestan period','A','candidate_verified_name','Avesta (Yasht) primary attestation',1,false,false,'Astral yazata, the star to whom the waters belong, shed between the earth and the sky (Tir Yasht).','deity'),
('ENT_ZOR_HAPTOIRINGA','Haptoiringa','Zoroastrian','Yazata','Astral Deity','Haptoiringa; yazata; Zoroastrian worship','Zoroastrian','Avestan period','A','candidate_verified_name','Avesta (Yasht) primary attestation',1,false,false,'Astral yazata, the seven stars (Ursa Major) invoked to oppose the Yatus and Pairikas (Tir Yasht).','deity'),
('ENT_ZOR_VANANT','Vanant','Zoroastrian','Yazata','Astral Deity','Vanant; yazata; Zoroastrian worship','Zoroastrian','Avestan period','A','candidate_verified_name','Avesta (Yasht) primary attestation',1,false,false,'Astral yazata, the star made by Mazda, invoked for strength and victory (Tir Yasht).','deity'),
('ENT_ZOR_PARENDI','Parendi','Zoroastrian','Yazata','Yazata','Parendi; yazata; Zoroastrian worship','Zoroastrian','Avestan period','A','candidate_verified_name','Avesta (Yasht) primary attestation',1,false,false,'Yazata of abundance and good fortune, of the swift chariot.','deity'),
('ENT_ZOR_ARSHTAT','Arshtat','Zoroastrian','Yazata','Yazata','Arshtat; yazata; Zoroastrian worship','Zoroastrian','Avestan period','A','candidate_verified_name','Avesta (Yasht) primary attestation',1,false,false,'Yazata of rectitude and justice, who makes the world grow.','deity'),
('ENT_ZOR_SAENA','Saena','Zoroastrian','Fravashi','Revered soul','Saena; yazata; Zoroastrian worship','Zoroastrian','Avestan period','A','candidate_verified_name','Avesta (Yasht) primary attestation',1,false,false,'The Fravashi of the holy Saena, son of Ahum-stut, who first appeared on earth with a hundred disciples (Farvardin Yasht).','spirit'),
('ENT_ZOR_FRASHAOSHTRA','Frashaoshtra','Zoroastrian','Fravashi','Revered soul','Frashaoshtra; yazata; Zoroastrian worship','Zoroastrian','Avestan period','A','candidate_verified_name','Avesta (Yasht) primary attestation',1,false,false,'Fravashi of Frashaoshtra, son of Hvova, a foremost disciple of Zoroaster (Farvardin Yasht).','spirit'),
('ENT_ZOR_JAMASPA','Jamaspa','Zoroastrian','Fravashi','Revered soul','Jamaspa; yazata; Zoroastrian worship','Zoroastrian','Avestan period','A','candidate_verified_name','Avesta (Yasht) primary attestation',1,false,false,'Fravashi of Jamaspa, sage counsellor of Kavi Vishtaspa and disciple of Zoroaster (Farvardin Yasht).','spirit'),
('ENT_ZOR_ASTVATERETA','Astvat-ereta','Zoroastrian','Saoshyant','Savior figure','Astvat-ereta; yazata; Zoroastrian worship','Zoroastrian','Avestan period','A','candidate_verified_name','Avesta (Yasht) primary attestation',1,false,false,'The final Saoshyant (world-renovating savior), Astvat-ereta, foretold in the Farvardin Yasht.','deity')
ON CONFLICT (entity_id) DO NOTHING;

INSERT INTO entity_citations
  (citation_id,entity_id,source_id,work_title,locus,quote,translator,translation_year,source_url,original_text_url,evidence_grade,evidence_note,needs_review,review_reason,verified_on,verify_method,display_order)
VALUES
('CIT_SATAVAESA_AV','ENT_ZOR_SATAVAESA','SRC_AVESTA','The Zend-Avesta (Darmesteter, SBE)','Avesta (Yasht)','They shed Satavaesa between the earth and the sky, him to whom the waters belong, who listens to appeals and makes the waters flow and the plants grow up, to nourish animals and men, to nourish the Aryan nations, to nourish the five kinds of animals and to help the faithful.','James Darmesteter',1883,'https://www.avesta.org/ka/yt13sbe.htm',NULL,'primary-verbatim',NULL,true,'Located by name in the Yasht (Darmesteter SBE); verify the exact Yasht and stanza.',DATE '2026-06-26','name + substring gate against Darmesteter Avesta (avesta.org)',1),
('CIT_HAPTOIRINGA_AV','ENT_ZOR_HAPTOIRINGA','SRC_AVESTA','The Zend-Avesta (Darmesteter, SBE)','Avesta (Yasht)','I will sacrifice unto the stars Haptoiringa, to oppose the Yatus and Pairikas. ''We sacrifice unto Vanant, the star made by Mazda; for the well-shapen strength, for the Victory, made by Ahura, for the crushing Ascendant, for the destruction of what distresses us, for the destruction of what persecutes us. ''We sacrifice unto Tishtrya, whose eye-sight is sound.','James Darmesteter',1883,'https://www.avesta.org/ka/yt13sbe.htm',NULL,'primary-verbatim',NULL,true,'Located by name in the Yasht (Darmesteter SBE); verify the exact Yasht and stanza.',DATE '2026-06-26','name + substring gate against Darmesteter Avesta (avesta.org)',1),
('CIT_VANANT_AV','ENT_ZOR_VANANT','SRC_AVESTA','The Zend-Avesta (Darmesteter, SBE)','Avesta (Yasht)','We sacrifice unto Vanant, the star made by Mazda; for the well-shapen strength, for the Victory, made by Ahura, for the crushing Ascendant, for the destruction of what distresses us, for the destruction of what persecutes us. ''We sacrifice unto Tishtrya, whose eye-sight is sound.','James Darmesteter',1883,'https://www.avesta.org/ka/yt13sbe.htm',NULL,'primary-verbatim',NULL,true,'Located by name in the Yasht (Darmesteter SBE); verify the exact Yasht and stanza.',DATE '2026-06-26','name + substring gate against Darmesteter Avesta (avesta.org)',1),
('CIT_PARENDI_AV','ENT_ZOR_PARENDI','SRC_AVESTA','The Zend-Avesta (Darmesteter, SBE)','Avesta (Yasht)','Ahura Mazda gave him assistance, and the Amesha-Spentas and Mithra, the lord of wide pastures, pointed him the way: behind him went the tall Ashish Vanguhi and Parendi on her light chariot: always till, in his course, he reached Mount Hvanvant on the shining waters. ''For his brightness and glory, I will offer him a sacrifice worth being heard.... X.','James Darmesteter',1883,'https://www.avesta.org/ka/yt13sbe.htm',NULL,'primary-verbatim',NULL,true,'Located by name in the Yasht (Darmesteter SBE); verify the exact Yasht and stanza.',DATE '2026-06-26','name + substring gate against Darmesteter Avesta (avesta.org)',1),
('CIT_ARSHTAT_AV','ENT_ZOR_ARSHTAT','SRC_AVESTA','The Zend-Avesta (Darmesteter, SBE)','Avesta (Yasht)','any man of you become, who shall treat Mithra well, the lord of wide pastures, and Arshtat, who makes the world grow, who makes the world increase. 19. ''Thus do I proclaim unto thee, O pure Spitama! the vigour and strength, the glory, the help, and the joy that are in the Fravashis of the faithful, the awful and overpowering Fravashis; and how they come to help me, how they bring assistance unto me, the awful Fravashis of the faithful.'' II.','James Darmesteter',1883,'https://www.avesta.org/ka/yt13sbe.htm',NULL,'primary-verbatim',NULL,true,'Located by name in the Yasht (Darmesteter SBE); verify the exact Yasht and stanza.',DATE '2026-06-26','name + substring gate against Darmesteter Avesta (avesta.org)',1),
('CIT_SAENA_AV','ENT_ZOR_SAENA','SRC_AVESTA','The Zend-Avesta (Darmesteter, SBE)','Avesta (Yasht)','We worship the Fravashi of the holy Saena, the son of Ahum-stut, who first appeared upon this earth with a hundred pupils. We worship the Fravashi of the holy Fradhidaya. We worship the Fravashi of the holy Usmanara, the son of Paeshata. We worship the Fravashi of the holy Vohu-raochah, the son of Franya; We worship the Fravashi of the holy Asho-raochah, the son of Franya; We worship the Fravashi of the holy Varesmo-raochah, the son of Franya.','James Darmesteter',1883,'https://www.avesta.org/ka/yt13sbe.htm',NULL,'primary-verbatim',NULL,true,'Located by name in the Yasht (Darmesteter SBE); verify the exact Yasht and stanza.',DATE '2026-06-26','name + substring gate against Darmesteter Avesta (avesta.org)',1),
('CIT_FRASHAOSHTRA_AV','ENT_ZOR_FRASHAOSHTRA','SRC_AVESTA','The Zend-Avesta (Darmesteter, SBE)','Avesta (Yasht)','We worship the Fravashi of the holy Frashaoshtra, the son of Hvova; We worship the Fravashi of the holy Jamaspa, the son of Hvova; We worship the Fravashi of the holy Avaraoshtri. 104. We worship the Fravashi of the holy Hushkyaothna, the son of Frashaoshtra;','James Darmesteter',1883,'https://www.avesta.org/ka/yt13sbe.htm',NULL,'primary-verbatim',NULL,true,'Located by name in the Yasht (Darmesteter SBE); verify the exact Yasht and stanza.',DATE '2026-06-26','name + substring gate against Darmesteter Avesta (avesta.org)',1),
('CIT_JAMASPA_AV','ENT_ZOR_JAMASPA','SRC_AVESTA','The Zend-Avesta (Darmesteter, SBE)','Avesta (Yasht)','We worship the Fravashi of the holy Frashaoshtra, the son of Hvova; We worship the Fravashi of the holy Jamaspa, the son of Hvova; We worship the Fravashi of the holy Avaraoshtri. 104. We worship the Fravashi of the holy Hushkyaothna, the son of Frashaoshtra;','James Darmesteter',1883,'https://www.avesta.org/ka/yt13sbe.htm',NULL,'primary-verbatim',NULL,true,'Located by name in the Yasht (Darmesteter SBE); verify the exact Yasht and stanza.',DATE '2026-06-26','name + substring gate against Darmesteter Avesta (avesta.org)',1),
('CIT_ASTVATERETA_AV','ENT_ZOR_ASTVATERETA','SRC_AVESTA','The Zend-Avesta (Darmesteter, SBE)','Avesta (Yasht)','Whose name will be the victorious SAOSHYANT and whose name will be Astvat-ereta. He will be SAOSHYANT (the Beneficent One), because he will benefit the whole bodily world; he will be ASTVAT-ERETA (he who makes the bodily creatures rise up), because as a bodily creature and as a living creature he will stand against the destruction of the bodily creatures, to withstand the Druj of the two-footed brood, to withstand the evil done by the faithful. XXIX.','James Darmesteter',1883,'https://www.avesta.org/ka/yt13sbe.htm',NULL,'primary-verbatim',NULL,true,'Located by name in the Yasht (Darmesteter SBE); verify the exact Yasht and stanza.',DATE '2026-06-26','name + substring gate against Darmesteter Avesta (avesta.org)',1)
ON CONFLICT (citation_id) DO UPDATE SET quote=EXCLUDED.quote;

COMMIT;
