-- scripts/add_potamoi.sql
-- Greek river-gods (Potamoi), sons of Oceanus, from the river catalogue of Hesiod
-- Theogony 337-345 (Evelyn-White). One shared catalogue quote per river; held names skipped.

BEGIN;

INSERT INTO entities
  (entity_id, canonical_name, tradition, entity_type, category, primary_domains, cult_scope, primary_period, evidence_confidence, review_status, inclusion_basis, earth_association_score, chthonic_flag, serpent_flag, short_note, entity_class)
VALUES
('ENT_NILUS','Nilus','Greek','River-god (Potamos)','River Deity','river-god; Potamoi; the rivers','Greek','archaic Greek','A','candidate_verified_name','Hesiod Theogony primary attestation (river catalogue)',3,false,false,'One of the river-gods (Potamoi), sons of Oceanus and Tethys, named in the river catalogue of Hesiod Theogony.','deity'),
('ENT_ISTER','Ister','Greek','River-god (Potamos)','River Deity','river-god; Potamoi; the rivers','Greek','archaic Greek','A','candidate_verified_name','Hesiod Theogony primary attestation (river catalogue)',3,false,false,'One of the river-gods (Potamoi), sons of Oceanus and Tethys, named in the river catalogue of Hesiod Theogony.','deity'),
('ENT_RHESUS','Rhesus','Greek','River-god (Potamos)','River Deity','river-god; Potamoi; the rivers','Greek','archaic Greek','A','candidate_verified_name','Hesiod Theogony primary attestation (river catalogue)',3,false,false,'One of the river-gods (Potamoi), sons of Oceanus and Tethys, named in the river catalogue of Hesiod Theogony.','deity'),
('ENT_ACHELOUS','Achelous','Greek','River-god (Potamos)','River Deity','river-god; Potamoi; the rivers','Greek','archaic Greek','A','candidate_verified_name','Hesiod Theogony primary attestation (river catalogue)',3,false,false,'One of the river-gods (Potamoi), sons of Oceanus and Tethys, named in the river catalogue of Hesiod Theogony.','deity'),
('ENT_RHODIUS','Rhodius','Greek','River-god (Potamos)','River Deity','river-god; Potamoi; the rivers','Greek','archaic Greek','A','candidate_verified_name','Hesiod Theogony primary attestation (river catalogue)',3,false,false,'One of the river-gods (Potamoi), sons of Oceanus and Tethys, named in the river catalogue of Hesiod Theogony.','deity'),
('ENT_HALIACMON','Haliacmon','Greek','River-god (Potamos)','River Deity','river-god; Potamoi; the rivers','Greek','archaic Greek','A','candidate_verified_name','Hesiod Theogony primary attestation (river catalogue)',3,false,false,'One of the river-gods (Potamoi), sons of Oceanus and Tethys, named in the river catalogue of Hesiod Theogony.','deity'),
('ENT_HEPTAPORUS','Heptaporus','Greek','River-god (Potamos)','River Deity','river-god; Potamoi; the rivers','Greek','archaic Greek','A','candidate_verified_name','Hesiod Theogony primary attestation (river catalogue)',3,false,false,'One of the river-gods (Potamoi), sons of Oceanus and Tethys, named in the river catalogue of Hesiod Theogony.','deity'),
('ENT_SIMOIS','Simois','Greek','River-god (Potamos)','River Deity','river-god; Potamoi; the rivers','Greek','archaic Greek','A','candidate_verified_name','Hesiod Theogony primary attestation (river catalogue)',3,false,false,'One of the river-gods (Potamoi), sons of Oceanus and Tethys, named in the river catalogue of Hesiod Theogony.','deity'),
('ENT_HERMUS','Hermus','Greek','River-god (Potamos)','River Deity','river-god; Potamoi; the rivers','Greek','archaic Greek','A','candidate_verified_name','Hesiod Theogony primary attestation (river catalogue)',3,false,false,'One of the river-gods (Potamoi), sons of Oceanus and Tethys, named in the river catalogue of Hesiod Theogony.','deity'),
('ENT_ARDESCUS','Ardescus','Greek','River-god (Potamos)','River Deity','river-god; Potamoi; the rivers','Greek','archaic Greek','A','candidate_verified_name','Hesiod Theogony primary attestation (river catalogue)',3,false,false,'One of the river-gods (Potamoi), sons of Oceanus and Tethys, named in the river catalogue of Hesiod Theogony.','deity')
ON CONFLICT (entity_id) DO NOTHING;

INSERT INTO entity_citations
  (citation_id,entity_id,source_id,work_title,locus,quote,translator,translation_year,source_url,original_text_url,evidence_grade,evidence_note,needs_review,review_reason,verified_on,verify_method,display_order)
VALUES
('CIT_NILUS_THEOG','ENT_NILUS','SRC_HESIOD_THEOGONY','Hesiod, Theogony','Theogony 337-345','And Tethys bare to Ocean eddying rivers, Nilus, and Alpheus, and deep-swirling Eridanus, Strymon, and Meander, and the fair stream of Ister, and Phasis, and Rhesus, and the silver eddies of Achelous, Nessus, and Rhodius, Haliacmon, and Heptaporus, Granicus, and Aesepus, and holy Simois, and Peneus, and Hermus, and Caicus fair stream, and great Sangarius, Ladon, Parthenius, Euenus, Ardescus, and divine Scamander.','Hugh G. Evelyn-White',1914,'https://www.gutenberg.org/ebooks/348',NULL,'primary-verbatim',NULL,true,'Named in the river catalogue of the Theogony (Evelyn-White); verify line.',DATE '2026-06-26','name + substring gate against Evelyn-White Theogony (#348)',1),
('CIT_ISTER_THEOG','ENT_ISTER','SRC_HESIOD_THEOGONY','Hesiod, Theogony','Theogony 337-345','And Tethys bare to Ocean eddying rivers, Nilus, and Alpheus, and deep-swirling Eridanus, Strymon, and Meander, and the fair stream of Ister, and Phasis, and Rhesus, and the silver eddies of Achelous, Nessus, and Rhodius, Haliacmon, and Heptaporus, Granicus, and Aesepus, and holy Simois, and Peneus, and Hermus, and Caicus fair stream, and great Sangarius, Ladon, Parthenius, Euenus, Ardescus, and divine Scamander.','Hugh G. Evelyn-White',1914,'https://www.gutenberg.org/ebooks/348',NULL,'primary-verbatim',NULL,true,'Named in the river catalogue of the Theogony (Evelyn-White); verify line.',DATE '2026-06-26','name + substring gate against Evelyn-White Theogony (#348)',1),
('CIT_RHESUS_THEOG','ENT_RHESUS','SRC_HESIOD_THEOGONY','Hesiod, Theogony','Theogony 337-345','And Tethys bare to Ocean eddying rivers, Nilus, and Alpheus, and deep-swirling Eridanus, Strymon, and Meander, and the fair stream of Ister, and Phasis, and Rhesus, and the silver eddies of Achelous, Nessus, and Rhodius, Haliacmon, and Heptaporus, Granicus, and Aesepus, and holy Simois, and Peneus, and Hermus, and Caicus fair stream, and great Sangarius, Ladon, Parthenius, Euenus, Ardescus, and divine Scamander.','Hugh G. Evelyn-White',1914,'https://www.gutenberg.org/ebooks/348',NULL,'primary-verbatim',NULL,true,'Named in the river catalogue of the Theogony (Evelyn-White); verify line.',DATE '2026-06-26','name + substring gate against Evelyn-White Theogony (#348)',1),
('CIT_ACHELOUS_THEOG','ENT_ACHELOUS','SRC_HESIOD_THEOGONY','Hesiod, Theogony','Theogony 337-345','And Tethys bare to Ocean eddying rivers, Nilus, and Alpheus, and deep-swirling Eridanus, Strymon, and Meander, and the fair stream of Ister, and Phasis, and Rhesus, and the silver eddies of Achelous, Nessus, and Rhodius, Haliacmon, and Heptaporus, Granicus, and Aesepus, and holy Simois, and Peneus, and Hermus, and Caicus fair stream, and great Sangarius, Ladon, Parthenius, Euenus, Ardescus, and divine Scamander.','Hugh G. Evelyn-White',1914,'https://www.gutenberg.org/ebooks/348',NULL,'primary-verbatim',NULL,true,'Named in the river catalogue of the Theogony (Evelyn-White); verify line.',DATE '2026-06-26','name + substring gate against Evelyn-White Theogony (#348)',1),
('CIT_RHODIUS_THEOG','ENT_RHODIUS','SRC_HESIOD_THEOGONY','Hesiod, Theogony','Theogony 337-345','And Tethys bare to Ocean eddying rivers, Nilus, and Alpheus, and deep-swirling Eridanus, Strymon, and Meander, and the fair stream of Ister, and Phasis, and Rhesus, and the silver eddies of Achelous, Nessus, and Rhodius, Haliacmon, and Heptaporus, Granicus, and Aesepus, and holy Simois, and Peneus, and Hermus, and Caicus fair stream, and great Sangarius, Ladon, Parthenius, Euenus, Ardescus, and divine Scamander.','Hugh G. Evelyn-White',1914,'https://www.gutenberg.org/ebooks/348',NULL,'primary-verbatim',NULL,true,'Named in the river catalogue of the Theogony (Evelyn-White); verify line.',DATE '2026-06-26','name + substring gate against Evelyn-White Theogony (#348)',1),
('CIT_HALIACMON_THEOG','ENT_HALIACMON','SRC_HESIOD_THEOGONY','Hesiod, Theogony','Theogony 337-345','And Tethys bare to Ocean eddying rivers, Nilus, and Alpheus, and deep-swirling Eridanus, Strymon, and Meander, and the fair stream of Ister, and Phasis, and Rhesus, and the silver eddies of Achelous, Nessus, and Rhodius, Haliacmon, and Heptaporus, Granicus, and Aesepus, and holy Simois, and Peneus, and Hermus, and Caicus fair stream, and great Sangarius, Ladon, Parthenius, Euenus, Ardescus, and divine Scamander.','Hugh G. Evelyn-White',1914,'https://www.gutenberg.org/ebooks/348',NULL,'primary-verbatim',NULL,true,'Named in the river catalogue of the Theogony (Evelyn-White); verify line.',DATE '2026-06-26','name + substring gate against Evelyn-White Theogony (#348)',1),
('CIT_HEPTAPORUS_THEOG','ENT_HEPTAPORUS','SRC_HESIOD_THEOGONY','Hesiod, Theogony','Theogony 337-345','And Tethys bare to Ocean eddying rivers, Nilus, and Alpheus, and deep-swirling Eridanus, Strymon, and Meander, and the fair stream of Ister, and Phasis, and Rhesus, and the silver eddies of Achelous, Nessus, and Rhodius, Haliacmon, and Heptaporus, Granicus, and Aesepus, and holy Simois, and Peneus, and Hermus, and Caicus fair stream, and great Sangarius, Ladon, Parthenius, Euenus, Ardescus, and divine Scamander.','Hugh G. Evelyn-White',1914,'https://www.gutenberg.org/ebooks/348',NULL,'primary-verbatim',NULL,true,'Named in the river catalogue of the Theogony (Evelyn-White); verify line.',DATE '2026-06-26','name + substring gate against Evelyn-White Theogony (#348)',1),
('CIT_SIMOIS_THEOG','ENT_SIMOIS','SRC_HESIOD_THEOGONY','Hesiod, Theogony','Theogony 337-345','And Tethys bare to Ocean eddying rivers, Nilus, and Alpheus, and deep-swirling Eridanus, Strymon, and Meander, and the fair stream of Ister, and Phasis, and Rhesus, and the silver eddies of Achelous, Nessus, and Rhodius, Haliacmon, and Heptaporus, Granicus, and Aesepus, and holy Simois, and Peneus, and Hermus, and Caicus fair stream, and great Sangarius, Ladon, Parthenius, Euenus, Ardescus, and divine Scamander.','Hugh G. Evelyn-White',1914,'https://www.gutenberg.org/ebooks/348',NULL,'primary-verbatim',NULL,true,'Named in the river catalogue of the Theogony (Evelyn-White); verify line.',DATE '2026-06-26','name + substring gate against Evelyn-White Theogony (#348)',1),
('CIT_HERMUS_THEOG','ENT_HERMUS','SRC_HESIOD_THEOGONY','Hesiod, Theogony','Theogony 337-345','And Tethys bare to Ocean eddying rivers, Nilus, and Alpheus, and deep-swirling Eridanus, Strymon, and Meander, and the fair stream of Ister, and Phasis, and Rhesus, and the silver eddies of Achelous, Nessus, and Rhodius, Haliacmon, and Heptaporus, Granicus, and Aesepus, and holy Simois, and Peneus, and Hermus, and Caicus fair stream, and great Sangarius, Ladon, Parthenius, Euenus, Ardescus, and divine Scamander.','Hugh G. Evelyn-White',1914,'https://www.gutenberg.org/ebooks/348',NULL,'primary-verbatim',NULL,true,'Named in the river catalogue of the Theogony (Evelyn-White); verify line.',DATE '2026-06-26','name + substring gate against Evelyn-White Theogony (#348)',1),
('CIT_ARDESCUS_THEOG','ENT_ARDESCUS','SRC_HESIOD_THEOGONY','Hesiod, Theogony','Theogony 337-345','And Tethys bare to Ocean eddying rivers, Nilus, and Alpheus, and deep-swirling Eridanus, Strymon, and Meander, and the fair stream of Ister, and Phasis, and Rhesus, and the silver eddies of Achelous, Nessus, and Rhodius, Haliacmon, and Heptaporus, Granicus, and Aesepus, and holy Simois, and Peneus, and Hermus, and Caicus fair stream, and great Sangarius, Ladon, Parthenius, Euenus, Ardescus, and divine Scamander.','Hugh G. Evelyn-White',1914,'https://www.gutenberg.org/ebooks/348',NULL,'primary-verbatim',NULL,true,'Named in the river catalogue of the Theogony (Evelyn-White); verify line.',DATE '2026-06-26','name + substring gate against Evelyn-White Theogony (#348)',1)
ON CONFLICT (citation_id) DO UPDATE SET quote=EXCLUDED.quote;

COMMIT;
