-- scripts/add_enoch_watchers.sql
-- Mainstream-traditions pass: the missing chiefs of tens among the fallen
-- Watchers of 1 Enoch (Book of Watchers, 6:7 / 8:3), Second Temple Jewish/Christian
-- angelology. Verbatim, substring-gated against R. H. Charles's translation
-- (Wikisource). 10 cite the 6:7 leaders-list; Araqiel/Ezeqeel/Armaros cite their
-- 8:3 teaching. Variant spellings (Asael, Baraqijal, Samsapeel, Semjaza, Samiazaz,
-- Arakiba) added as aliases to existing entities, not duplicated. No AI prose.

BEGIN;

INSERT INTO entities
  (entity_id, canonical_name, tradition, entity_type, category, primary_domains, cult_scope, primary_period, evidence_confidence, review_status, inclusion_basis, earth_association_score, chthonic_flag, serpent_flag, short_note, entity_class)
VALUES
('ENT_ISR_RAMEEL','Rameel','Israelite/Second Temple','Fallen angel','Watcher-chief','fallen angel; Watcher; chief of tens','Israelite/Second Temple','3rd-2nd c. BCE','A','candidate_verified_name','1 Enoch primary attestation (1 Enoch 6:7)',2,false,false,'One of the twenty chiefs of tens among the fallen Watchers who descended on Mount Hermon (1 Enoch 6:7).','demon'),
('ENT_ISR_TAMIEL','Tamiel','Israelite/Second Temple','Fallen angel','Watcher-chief','fallen angel; Watcher; chief of tens','Israelite/Second Temple','3rd-2nd c. BCE','A','candidate_verified_name','1 Enoch primary attestation (1 Enoch 6:7)',2,false,false,'One of the twenty chiefs of tens among the fallen Watchers who descended on Mount Hermon (1 Enoch 6:7).','demon'),
('ENT_ISR_RAMIEL','Ramiel','Israelite/Second Temple','Fallen angel','Watcher-chief','fallen angel; Watcher; chief of tens','Israelite/Second Temple','3rd-2nd c. BCE','A','candidate_verified_name','1 Enoch primary attestation (1 Enoch 6:7)',2,false,false,'One of the twenty chiefs of tens among the fallen Watchers who descended on Mount Hermon (1 Enoch 6:7).','demon'),
('ENT_ISR_DANEL','Danel','Israelite/Second Temple','Fallen angel','Watcher-chief','fallen angel; Watcher; chief of tens','Israelite/Second Temple','3rd-2nd c. BCE','A','candidate_verified_name','1 Enoch primary attestation (1 Enoch 6:7)',2,false,false,'One of the twenty chiefs of tens among the fallen Watchers who descended on Mount Hermon (1 Enoch 6:7).','demon'),
('ENT_ISR_BATAREL','Batarel','Israelite/Second Temple','Fallen angel','Watcher-chief','fallen angel; Watcher; chief of tens','Israelite/Second Temple','3rd-2nd c. BCE','A','candidate_verified_name','1 Enoch primary attestation (1 Enoch 6:7)',2,false,false,'One of the twenty chiefs of tens among the fallen Watchers who descended on Mount Hermon (1 Enoch 6:7).','demon'),
('ENT_ISR_ANANEL','Ananel','Israelite/Second Temple','Fallen angel','Watcher-chief','fallen angel; Watcher; chief of tens','Israelite/Second Temple','3rd-2nd c. BCE','A','candidate_verified_name','1 Enoch primary attestation (1 Enoch 6:7)',2,false,false,'One of the twenty chiefs of tens among the fallen Watchers who descended on Mount Hermon (1 Enoch 6:7).','demon'),
('ENT_ISR_ZAQIEL','Zaqiel','Israelite/Second Temple','Fallen angel','Watcher-chief','fallen angel; Watcher; chief of tens','Israelite/Second Temple','3rd-2nd c. BCE','A','candidate_verified_name','1 Enoch primary attestation (1 Enoch 6:7)',2,false,false,'One of the twenty chiefs of tens among the fallen Watchers who descended on Mount Hermon (1 Enoch 6:7).','demon'),
('ENT_ISR_SATAREL','Satarel','Israelite/Second Temple','Fallen angel','Watcher-chief','fallen angel; Watcher; chief of tens','Israelite/Second Temple','3rd-2nd c. BCE','A','candidate_verified_name','1 Enoch primary attestation (1 Enoch 6:7)',2,false,false,'One of the twenty chiefs of tens among the fallen Watchers who descended on Mount Hermon (1 Enoch 6:7).','demon'),
('ENT_ISR_TUREL','Turel','Israelite/Second Temple','Fallen angel','Watcher-chief','fallen angel; Watcher; chief of tens','Israelite/Second Temple','3rd-2nd c. BCE','A','candidate_verified_name','1 Enoch primary attestation (1 Enoch 6:7)',2,false,false,'One of the twenty chiefs of tens among the fallen Watchers who descended on Mount Hermon (1 Enoch 6:7).','demon'),
('ENT_ISR_JOMJAEL','Jomjael','Israelite/Second Temple','Fallen angel','Watcher-chief','fallen angel; Watcher; chief of tens','Israelite/Second Temple','3rd-2nd c. BCE','A','candidate_verified_name','1 Enoch primary attestation (1 Enoch 6:7)',2,false,false,'One of the twenty chiefs of tens among the fallen Watchers who descended on Mount Hermon (1 Enoch 6:7).','demon'),
('ENT_ISR_ARAQIEL','Araqiel','Israelite/Second Temple','Fallen angel','Watcher-chief','fallen angel; Watcher; signs of the earth','Israelite/Second Temple','3rd-2nd c. BCE','A','candidate_verified_name','1 Enoch primary attestation (1 Enoch 8:3)',2,false,false,'Fallen Watcher who taught humankind the signs of the earth (1 Enoch 8:3); a chief of tens among the Watchers (1 Enoch 6:7).','demon'),
('ENT_ISR_EZEQEEL','Ezeqeel','Israelite/Second Temple','Fallen angel','Watcher-chief','fallen angel; Watcher; knowledge of the clouds','Israelite/Second Temple','3rd-2nd c. BCE','A','candidate_verified_name','1 Enoch primary attestation (1 Enoch 8:3)',2,false,false,'Fallen Watcher who taught humankind the knowledge of the clouds (1 Enoch 8:3); a chief of tens among the Watchers (1 Enoch 6:7).','demon'),
('ENT_ISR_ARMAROS','Armaros','Israelite/Second Temple','Fallen angel','Watcher-chief','fallen angel; Watcher; resolving of enchantments','Israelite/Second Temple','3rd-2nd c. BCE','A','candidate_verified_name','1 Enoch primary attestation (1 Enoch 8:3)',2,false,false,'Fallen Watcher who taught humankind the resolving of enchantments (1 Enoch 8:3); a chief of tens among the Watchers (1 Enoch 6:7).','demon')
ON CONFLICT (entity_id) DO NOTHING;

INSERT INTO entity_aliases
  (entity_id, alias_name, alias_type, language, source_id, confidence, review_status, notes)
SELECT 'ENT_ISR_AZAZEL','Asael','variant','en','SRC_1_ENOCH','high','candidate_verified_name','Variant spelling of this Watcher in 1 Enoch (Charles).' WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_ISR_AZAZEL' AND alias_name='Asael')
UNION ALL
SELECT 'ENT_ISR_BARAQIEL','Baraqijal','variant','en','SRC_1_ENOCH','high','candidate_verified_name','Variant spelling of this Watcher in 1 Enoch (Charles).' WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_ISR_BARAQIEL' AND alias_name='Baraqijal')
UNION ALL
SELECT 'ENT_JM_SHAMSHIEL','Samsapeel','variant','en','SRC_1_ENOCH','high','candidate_verified_name','Variant spelling of this Watcher in 1 Enoch (Charles).' WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_JM_SHAMSHIEL' AND alias_name='Samsapeel')
UNION ALL
SELECT 'ENT_ISR_SHEMIHAZAH','Semjaza','variant','en','SRC_1_ENOCH','high','candidate_verified_name','Variant spelling of this Watcher in 1 Enoch (Charles).' WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_ISR_SHEMIHAZAH' AND alias_name='Semjaza')
UNION ALL
SELECT 'ENT_ISR_SHEMIHAZAH','Samiazaz','variant','en','SRC_1_ENOCH','high','candidate_verified_name','Variant spelling of this Watcher in 1 Enoch (Charles).' WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_ISR_SHEMIHAZAH' AND alias_name='Samiazaz')
UNION ALL
SELECT 'ENT_ISR_ARAQIEL','Arakiba','variant','en','SRC_1_ENOCH','high','candidate_verified_name','Variant spelling of this Watcher in 1 Enoch (Charles).' WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_ISR_ARAQIEL' AND alias_name='Arakiba');

INSERT INTO entity_citations
  (citation_id,entity_id,source_id,work_title,locus,quote,translator,translation_year,source_url,original_text_url,evidence_grade,evidence_note,needs_review,review_reason,verified_on,verify_method,display_order)
VALUES
('CIT_ISR_RAMEEL_ENOCH','ENT_ISR_RAMEEL','SRC_1_ENOCH','The Book of Enoch (1 Enoch)','1 Enoch 6:7','And these are the names of their leaders: Samiazaz, their leader, Arakiba, Rameel, Kokabiel, Tamiel, Ramiel, Danel, Ezeqeel, Baraqijal, Asael, Armaros, Batarel, Ananel, Zaqiel, Samsapeel, Satarel, Turel, Jomjael, Sariel.','R. H. Charles',1912,'https://en.wikisource.org/wiki/The_Book_of_Enoch_(Charles)/Chapter_06',NULL,'primary-verbatim',NULL,true,'Located by name in 1 Enoch (Charles); verify chapter.verse.',DATE '2026-06-25','name-anchored + substring gate against Charles 1 Enoch (Wikisource); diacritics/editorial brackets normalized',1),
('CIT_ISR_TAMIEL_ENOCH','ENT_ISR_TAMIEL','SRC_1_ENOCH','The Book of Enoch (1 Enoch)','1 Enoch 6:7','And these are the names of their leaders: Samiazaz, their leader, Arakiba, Rameel, Kokabiel, Tamiel, Ramiel, Danel, Ezeqeel, Baraqijal, Asael, Armaros, Batarel, Ananel, Zaqiel, Samsapeel, Satarel, Turel, Jomjael, Sariel.','R. H. Charles',1912,'https://en.wikisource.org/wiki/The_Book_of_Enoch_(Charles)/Chapter_06',NULL,'primary-verbatim',NULL,true,'Located by name in 1 Enoch (Charles); verify chapter.verse.',DATE '2026-06-25','name-anchored + substring gate against Charles 1 Enoch (Wikisource); diacritics/editorial brackets normalized',1),
('CIT_ISR_RAMIEL_ENOCH','ENT_ISR_RAMIEL','SRC_1_ENOCH','The Book of Enoch (1 Enoch)','1 Enoch 6:7','And these are the names of their leaders: Samiazaz, their leader, Arakiba, Rameel, Kokabiel, Tamiel, Ramiel, Danel, Ezeqeel, Baraqijal, Asael, Armaros, Batarel, Ananel, Zaqiel, Samsapeel, Satarel, Turel, Jomjael, Sariel.','R. H. Charles',1912,'https://en.wikisource.org/wiki/The_Book_of_Enoch_(Charles)/Chapter_06',NULL,'primary-verbatim',NULL,true,'Located by name in 1 Enoch (Charles); verify chapter.verse.',DATE '2026-06-25','name-anchored + substring gate against Charles 1 Enoch (Wikisource); diacritics/editorial brackets normalized',1),
('CIT_ISR_DANEL_ENOCH','ENT_ISR_DANEL','SRC_1_ENOCH','The Book of Enoch (1 Enoch)','1 Enoch 6:7','And these are the names of their leaders: Samiazaz, their leader, Arakiba, Rameel, Kokabiel, Tamiel, Ramiel, Danel, Ezeqeel, Baraqijal, Asael, Armaros, Batarel, Ananel, Zaqiel, Samsapeel, Satarel, Turel, Jomjael, Sariel.','R. H. Charles',1912,'https://en.wikisource.org/wiki/The_Book_of_Enoch_(Charles)/Chapter_06',NULL,'primary-verbatim',NULL,true,'Located by name in 1 Enoch (Charles); verify chapter.verse.',DATE '2026-06-25','name-anchored + substring gate against Charles 1 Enoch (Wikisource); diacritics/editorial brackets normalized',1),
('CIT_ISR_BATAREL_ENOCH','ENT_ISR_BATAREL','SRC_1_ENOCH','The Book of Enoch (1 Enoch)','1 Enoch 6:7','And these are the names of their leaders: Samiazaz, their leader, Arakiba, Rameel, Kokabiel, Tamiel, Ramiel, Danel, Ezeqeel, Baraqijal, Asael, Armaros, Batarel, Ananel, Zaqiel, Samsapeel, Satarel, Turel, Jomjael, Sariel.','R. H. Charles',1912,'https://en.wikisource.org/wiki/The_Book_of_Enoch_(Charles)/Chapter_06',NULL,'primary-verbatim',NULL,true,'Located by name in 1 Enoch (Charles); verify chapter.verse.',DATE '2026-06-25','name-anchored + substring gate against Charles 1 Enoch (Wikisource); diacritics/editorial brackets normalized',1),
('CIT_ISR_ANANEL_ENOCH','ENT_ISR_ANANEL','SRC_1_ENOCH','The Book of Enoch (1 Enoch)','1 Enoch 6:7','And these are the names of their leaders: Samiazaz, their leader, Arakiba, Rameel, Kokabiel, Tamiel, Ramiel, Danel, Ezeqeel, Baraqijal, Asael, Armaros, Batarel, Ananel, Zaqiel, Samsapeel, Satarel, Turel, Jomjael, Sariel.','R. H. Charles',1912,'https://en.wikisource.org/wiki/The_Book_of_Enoch_(Charles)/Chapter_06',NULL,'primary-verbatim',NULL,true,'Located by name in 1 Enoch (Charles); verify chapter.verse.',DATE '2026-06-25','name-anchored + substring gate against Charles 1 Enoch (Wikisource); diacritics/editorial brackets normalized',1),
('CIT_ISR_ZAQIEL_ENOCH','ENT_ISR_ZAQIEL','SRC_1_ENOCH','The Book of Enoch (1 Enoch)','1 Enoch 6:7','And these are the names of their leaders: Samiazaz, their leader, Arakiba, Rameel, Kokabiel, Tamiel, Ramiel, Danel, Ezeqeel, Baraqijal, Asael, Armaros, Batarel, Ananel, Zaqiel, Samsapeel, Satarel, Turel, Jomjael, Sariel.','R. H. Charles',1912,'https://en.wikisource.org/wiki/The_Book_of_Enoch_(Charles)/Chapter_06',NULL,'primary-verbatim',NULL,true,'Located by name in 1 Enoch (Charles); verify chapter.verse.',DATE '2026-06-25','name-anchored + substring gate against Charles 1 Enoch (Wikisource); diacritics/editorial brackets normalized',1),
('CIT_ISR_SATAREL_ENOCH','ENT_ISR_SATAREL','SRC_1_ENOCH','The Book of Enoch (1 Enoch)','1 Enoch 6:7','And these are the names of their leaders: Samiazaz, their leader, Arakiba, Rameel, Kokabiel, Tamiel, Ramiel, Danel, Ezeqeel, Baraqijal, Asael, Armaros, Batarel, Ananel, Zaqiel, Samsapeel, Satarel, Turel, Jomjael, Sariel.','R. H. Charles',1912,'https://en.wikisource.org/wiki/The_Book_of_Enoch_(Charles)/Chapter_06',NULL,'primary-verbatim',NULL,true,'Located by name in 1 Enoch (Charles); verify chapter.verse.',DATE '2026-06-25','name-anchored + substring gate against Charles 1 Enoch (Wikisource); diacritics/editorial brackets normalized',1),
('CIT_ISR_TUREL_ENOCH','ENT_ISR_TUREL','SRC_1_ENOCH','The Book of Enoch (1 Enoch)','1 Enoch 6:7','And these are the names of their leaders: Samiazaz, their leader, Arakiba, Rameel, Kokabiel, Tamiel, Ramiel, Danel, Ezeqeel, Baraqijal, Asael, Armaros, Batarel, Ananel, Zaqiel, Samsapeel, Satarel, Turel, Jomjael, Sariel.','R. H. Charles',1912,'https://en.wikisource.org/wiki/The_Book_of_Enoch_(Charles)/Chapter_06',NULL,'primary-verbatim',NULL,true,'Located by name in 1 Enoch (Charles); verify chapter.verse.',DATE '2026-06-25','name-anchored + substring gate against Charles 1 Enoch (Wikisource); diacritics/editorial brackets normalized',1),
('CIT_ISR_JOMJAEL_ENOCH','ENT_ISR_JOMJAEL','SRC_1_ENOCH','The Book of Enoch (1 Enoch)','1 Enoch 6:7','And these are the names of their leaders: Samiazaz, their leader, Arakiba, Rameel, Kokabiel, Tamiel, Ramiel, Danel, Ezeqeel, Baraqijal, Asael, Armaros, Batarel, Ananel, Zaqiel, Samsapeel, Satarel, Turel, Jomjael, Sariel.','R. H. Charles',1912,'https://en.wikisource.org/wiki/The_Book_of_Enoch_(Charles)/Chapter_06',NULL,'primary-verbatim',NULL,true,'Located by name in 1 Enoch (Charles); verify chapter.verse.',DATE '2026-06-25','name-anchored + substring gate against Charles 1 Enoch (Wikisource); diacritics/editorial brackets normalized',1),
('CIT_ISR_ARAQIEL_ENOCH','ENT_ISR_ARAQIEL','SRC_1_ENOCH','The Book of Enoch (1 Enoch)','1 Enoch 8:3','Semjaza taught enchantments, and root-cuttings, Armaros the resolving of enchantments, Baraqijal (taught) astrology, Kokabel the constellations, Ezeqeel the knowledge of the clouds, Araqiel the signs of the earth, Shamsiel the signs of the sun, and Sariel the course of the moon.','R. H. Charles',1912,'https://en.wikisource.org/wiki/The_Book_of_Enoch_(Charles)/Chapter_08',NULL,'primary-verbatim',NULL,true,'Located by name in 1 Enoch (Charles); verify chapter.verse.',DATE '2026-06-25','name-anchored + substring gate against Charles 1 Enoch (Wikisource); diacritics/editorial brackets normalized',1),
('CIT_ISR_EZEQEEL_ENOCH','ENT_ISR_EZEQEEL','SRC_1_ENOCH','The Book of Enoch (1 Enoch)','1 Enoch 8:3','Semjaza taught enchantments, and root-cuttings, Armaros the resolving of enchantments, Baraqijal (taught) astrology, Kokabel the constellations, Ezeqeel the knowledge of the clouds, Araqiel the signs of the earth, Shamsiel the signs of the sun, and Sariel the course of the moon.','R. H. Charles',1912,'https://en.wikisource.org/wiki/The_Book_of_Enoch_(Charles)/Chapter_08',NULL,'primary-verbatim',NULL,true,'Located by name in 1 Enoch (Charles); verify chapter.verse.',DATE '2026-06-25','name-anchored + substring gate against Charles 1 Enoch (Wikisource); diacritics/editorial brackets normalized',1),
('CIT_ISR_ARMAROS_ENOCH','ENT_ISR_ARMAROS','SRC_1_ENOCH','The Book of Enoch (1 Enoch)','1 Enoch 8:3','Semjaza taught enchantments, and root-cuttings, Armaros the resolving of enchantments, Baraqijal (taught) astrology, Kokabel the constellations, Ezeqeel the knowledge of the clouds, Araqiel the signs of the earth, Shamsiel the signs of the sun, and Sariel the course of the moon.','R. H. Charles',1912,'https://en.wikisource.org/wiki/The_Book_of_Enoch_(Charles)/Chapter_08',NULL,'primary-verbatim',NULL,true,'Located by name in 1 Enoch (Charles); verify chapter.verse.',DATE '2026-06-25','name-anchored + substring gate against Charles 1 Enoch (Wikisource); diacritics/editorial brackets normalized',1)
ON CONFLICT (citation_id) DO UPDATE SET quote=EXCLUDED.quote, locus=EXCLUDED.locus, source_url=EXCLUDED.source_url;

COMMIT;
