-- scripts/add_mainstream_demons_dwarves.sql
-- Mainstream pass (2): Testament of Solomon disease-demons (3 missing decans) and
-- Voluspa Dvergatal dwarves (Poetic Edda). Verbatim, substring-gated against
-- Conybeare 1898 / Thorpe 1866. No AI prose.

BEGIN;

INSERT INTO entities
  (entity_id, canonical_name, tradition, entity_type, category, primary_domains, cult_scope, primary_period, evidence_confidence, review_status, inclusion_basis, earth_association_score, chthonic_flag, serpent_flag, short_note, entity_class)
VALUES
('ENT_LAT_BARSAFAEL','Barsafael','Late Antique Ritual','Disease demon','Disease Demon','disease demon; affliction; the pain of migraine','Late Antique Ritual','1st-3rd c. CE','A','candidate_verified_name','Testament of Solomon primary attestation',2,false,false,'Disease-demon (decan) of the Testament of Solomon who causes the pain of migraine.','demon'),
('ENT_LAT_METATHIAX','Metathiax','Late Antique Ritual','Disease demon','Disease Demon','disease demon; affliction; the reins to ache','Late Antique Ritual','1st-3rd c. CE','A','candidate_verified_name','Testament of Solomon primary attestation',2,false,false,'Disease-demon (decan) of the Testament of Solomon who causes the reins to ache.','demon'),
('ENT_LAT_HEPHESIMIRETH','Hephesimireth','Late Antique Ritual','Disease demon','Disease Demon','disease demon; affliction; lingering disease','Late Antique Ritual','1st-3rd c. CE','A','candidate_verified_name','Testament of Solomon primary attestation',2,false,false,'Disease-demon (decan) of the Testament of Solomon who causes lingering disease.','demon'),
('ENT_NOR_NORDRI','Nordri','Germanic/Norse','Dwarf','Dwarves','dwarf; Dvergatal; dwarf-catalogue','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Poetic Edda primary attestation (Voluspa Dvergatal)',1,false,false,'One of the dwarfs named in the Dvergatal (dwarf-catalogue) of the Voluspa.','spirit'),
('ENT_NOR_SUDRI','Sudri','Germanic/Norse','Dwarf','Dwarves','dwarf; Dvergatal; dwarf-catalogue','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Poetic Edda primary attestation (Voluspa Dvergatal)',1,false,false,'One of the dwarfs named in the Dvergatal (dwarf-catalogue) of the Voluspa.','spirit'),
('ENT_NOR_AUSTRI','Austri','Germanic/Norse','Dwarf','Dwarves','dwarf; Dvergatal; dwarf-catalogue','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Poetic Edda primary attestation (Voluspa Dvergatal)',1,false,false,'One of the dwarfs named in the Dvergatal (dwarf-catalogue) of the Voluspa.','spirit'),
('ENT_NOR_VESTRI','Vestri','Germanic/Norse','Dwarf','Dwarves','dwarf; Dvergatal; dwarf-catalogue','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Poetic Edda primary attestation (Voluspa Dvergatal)',1,false,false,'One of the dwarfs named in the Dvergatal (dwarf-catalogue) of the Voluspa.','spirit'),
('ENT_NOR_BIVOR','Bivor','Germanic/Norse','Dwarf','Dwarves','dwarf; Dvergatal; dwarf-catalogue','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Poetic Edda primary attestation (Voluspa Dvergatal)',1,false,false,'One of the dwarfs named in the Dvergatal (dwarf-catalogue) of the Voluspa.','spirit'),
('ENT_NOR_BOMBUR','Bombur','Germanic/Norse','Dwarf','Dwarves','dwarf; Dvergatal; dwarf-catalogue','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Poetic Edda primary attestation (Voluspa Dvergatal)',1,false,false,'One of the dwarfs named in the Dvergatal (dwarf-catalogue) of the Voluspa.','spirit'),
('ENT_NOR_GANDALF','Gandalf','Germanic/Norse','Dwarf','Dwarves','dwarf; Dvergatal; dwarf-catalogue','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Poetic Edda primary attestation (Voluspa Dvergatal)',1,false,false,'One of the dwarfs named in the Dvergatal (dwarf-catalogue) of the Voluspa.','spirit'),
('ENT_NOR_VINDALF','Vindalf','Germanic/Norse','Dwarf','Dwarves','dwarf; Dvergatal; dwarf-catalogue','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Poetic Edda primary attestation (Voluspa Dvergatal)',1,false,false,'One of the dwarfs named in the Dvergatal (dwarf-catalogue) of the Voluspa.','spirit'),
('ENT_NOR_THRAIN','Thrain','Germanic/Norse','Dwarf','Dwarves','dwarf; Dvergatal; dwarf-catalogue','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Poetic Edda primary attestation (Voluspa Dvergatal)',1,false,false,'One of the dwarfs named in the Dvergatal (dwarf-catalogue) of the Voluspa.','spirit'),
('ENT_NOR_THEKK','Thekk','Germanic/Norse','Dwarf','Dwarves','dwarf; Dvergatal; dwarf-catalogue','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Poetic Edda primary attestation (Voluspa Dvergatal)',1,false,false,'One of the dwarfs named in the Dvergatal (dwarf-catalogue) of the Voluspa.','spirit'),
('ENT_NOR_FUNDIN','Fundin','Germanic/Norse','Dwarf','Dwarves','dwarf; Dvergatal; dwarf-catalogue','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Poetic Edda primary attestation (Voluspa Dvergatal)',1,false,false,'One of the dwarfs named in the Dvergatal (dwarf-catalogue) of the Voluspa.','spirit'),
('ENT_NOR_HORNBORI','Hornbori','Germanic/Norse','Dwarf','Dwarves','dwarf; Dvergatal; dwarf-catalogue','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Poetic Edda primary attestation (Voluspa Dvergatal)',1,false,false,'One of the dwarfs named in the Dvergatal (dwarf-catalogue) of the Voluspa.','spirit'),
('ENT_NOR_AURVANG','Aurvang','Germanic/Norse','Dwarf','Dwarves','dwarf; Dvergatal; dwarf-catalogue','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Poetic Edda primary attestation (Voluspa Dvergatal)',1,false,false,'One of the dwarfs named in the Dvergatal (dwarf-catalogue) of the Voluspa.','spirit')
ON CONFLICT (entity_id) DO NOTHING;

INSERT INTO entity_citations
  (citation_id,entity_id,source_id,work_title,locus,quote,translator,translation_year,source_url,original_text_url,evidence_grade,evidence_note,needs_review,review_reason,verified_on,verify_method,display_order)
VALUES
('CIT_LAT_BARSAFAEL_TSOL','ENT_LAT_BARSAFAEL','SRC_TESTAMENT_SOLOMON','The Testament of Solomon','Testament of Solomon','And the second said: "I am called Barsafael, and I cause those who are subject to my hour to feel the pain of migraine. If only I hear the words, ''Gabriel, imprison Barsafael,'' at once I retreat." 75. The third said: "I am called Arotosael. I do harm to eyes, and grievously injure them. Only let me hear the words, ''Uriel, imprison Aratosael'' (sic), at once I retreat . . . . . 1 " 1. There seems to be a lacuna here.','F. C. Conybeare',1898,'https://www.esotericarchives.com/solomon/testamen.htm',NULL,'primary-verbatim',NULL,true,'Located by name in the Testament of Solomon (Conybeare); verify the section.',DATE '2026-06-25','name-anchored + substring gate against Conybeare 1898 text',1),
('CIT_LAT_METATHIAX_TSOL','ENT_LAT_METATHIAX','SRC_TESTAMENT_SOLOMON','The Testament of Solomon','Testament of Solomon','The tenth said: "I am called Metathiax. I cause the reins to ache. If I hear the words, ''Adonael, imprison Metathiax,'' I at once retreat." 82. The eleventh said: "I am called Katanikotael.','F. C. Conybeare',1898,'https://www.esotericarchives.com/solomon/testamen.htm',NULL,'primary-verbatim',NULL,true,'Located by name in the Testament of Solomon (Conybeare); verify the section.',DATE '2026-06-25','name-anchored + substring gate against Conybeare 1898 text',1),
('CIT_LAT_HEPHESIMIRETH_TSOL','ENT_LAT_HEPHESIMIRETH','SRC_TESTAMENT_SOLOMON','The Testament of Solomon','Testament of Solomon','The thirty-first said: "I am called Hephesimireth, and cause lingering disease. If you throw salt, rubbed in the hand, into oil and smear it on the patient, saying: ''Seraphim, Cherubim, help me!'' I at once retire." 102. The thirty-second said: "I am called Ichthion. I paralyze muscles and contuse them. If I hear ''Adonaeth, help!'' I at once retire." 103. The thirty-third said: "I am called Agchonion.','F. C. Conybeare',1898,'https://www.esotericarchives.com/solomon/testamen.htm',NULL,'primary-verbatim',NULL,true,'Located by name in the Testament of Solomon (Conybeare); verify the section.',DATE '2026-06-25','name-anchored + substring gate against Conybeare 1898 text',1),
('CIT_NORDRI_PEDDA','ENT_NOR_NORDRI','SRC_POETIC_EDDA','The Poetic Edda (Voluspa)','Voluspa (Dvergatal)','Nyi and Nidi, Nordri and Sudri, Austri and Vestri, Althiof, Dvalin Nar and Nain, Niping, Dain, Bivor, Bavor, Bombur, Nori, An and Anar, Ai, Miodvitnir, 12. Veig and Gandalf, Vindalf, Thrain, Thekk and Thorin, Thror, Vitr, and Litr, Nur and Nyrad, Regin and Radsvid. Now of the dwarfs I have rightly told. 13. Fili, Kili, Fundin, Nali, Hepti, Vili, Hanar, Svior, Billing, Bruni, Bild, Buri, Frar, Hornbori, Fraeg and Loni, Aurvang, Iari, Eikinskialdi.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Located by name in the Dvergatal of the Voluspa (Thorpe); verify the stanza.',DATE '2026-06-25','name-anchored + substring gate against Thorpe Poetic Edda (Gutenberg #14726)',1),
('CIT_SUDRI_PEDDA','ENT_NOR_SUDRI','SRC_POETIC_EDDA','The Poetic Edda (Voluspa)','Voluspa (Dvergatal)','Nyi and Nidi, Nordri and Sudri, Austri and Vestri, Althiof, Dvalin Nar and Nain, Niping, Dain, Bivor, Bavor, Bombur, Nori, An and Anar, Ai, Miodvitnir, 12. Veig and Gandalf, Vindalf, Thrain, Thekk and Thorin, Thror, Vitr, and Litr, Nur and Nyrad, Regin and Radsvid. Now of the dwarfs I have rightly told. 13. Fili, Kili, Fundin, Nali, Hepti, Vili, Hanar, Svior, Billing, Bruni, Bild, Buri, Frar, Hornbori, Fraeg and Loni, Aurvang, Iari, Eikinskialdi.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Located by name in the Dvergatal of the Voluspa (Thorpe); verify the stanza.',DATE '2026-06-25','name-anchored + substring gate against Thorpe Poetic Edda (Gutenberg #14726)',1),
('CIT_AUSTRI_PEDDA','ENT_NOR_AUSTRI','SRC_POETIC_EDDA','The Poetic Edda (Voluspa)','Voluspa (Dvergatal)','Nyi and Nidi, Nordri and Sudri, Austri and Vestri, Althiof, Dvalin Nar and Nain, Niping, Dain, Bivor, Bavor, Bombur, Nori, An and Anar, Ai, Miodvitnir, 12. Veig and Gandalf, Vindalf, Thrain, Thekk and Thorin, Thror, Vitr, and Litr, Nur and Nyrad, Regin and Radsvid. Now of the dwarfs I have rightly told. 13. Fili, Kili, Fundin, Nali, Hepti, Vili, Hanar, Svior, Billing, Bruni, Bild, Buri, Frar, Hornbori, Fraeg and Loni, Aurvang, Iari, Eikinskialdi.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Located by name in the Dvergatal of the Voluspa (Thorpe); verify the stanza.',DATE '2026-06-25','name-anchored + substring gate against Thorpe Poetic Edda (Gutenberg #14726)',1),
('CIT_VESTRI_PEDDA','ENT_NOR_VESTRI','SRC_POETIC_EDDA','The Poetic Edda (Voluspa)','Voluspa (Dvergatal)','Nyi and Nidi, Nordri and Sudri, Austri and Vestri, Althiof, Dvalin Nar and Nain, Niping, Dain, Bivor, Bavor, Bombur, Nori, An and Anar, Ai, Miodvitnir, 12. Veig and Gandalf, Vindalf, Thrain, Thekk and Thorin, Thror, Vitr, and Litr, Nur and Nyrad, Regin and Radsvid. Now of the dwarfs I have rightly told. 13. Fili, Kili, Fundin, Nali, Hepti, Vili, Hanar, Svior, Billing, Bruni, Bild, Buri, Frar, Hornbori, Fraeg and Loni, Aurvang, Iari, Eikinskialdi.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Located by name in the Dvergatal of the Voluspa (Thorpe); verify the stanza.',DATE '2026-06-25','name-anchored + substring gate against Thorpe Poetic Edda (Gutenberg #14726)',1),
('CIT_BIVOR_PEDDA','ENT_NOR_BIVOR','SRC_POETIC_EDDA','The Poetic Edda (Voluspa)','Voluspa (Dvergatal)','Nyi and Nidi, Nordri and Sudri, Austri and Vestri, Althiof, Dvalin Nar and Nain, Niping, Dain, Bivor, Bavor, Bombur, Nori, An and Anar, Ai, Miodvitnir, 12. Veig and Gandalf, Vindalf, Thrain, Thekk and Thorin, Thror, Vitr, and Litr, Nur and Nyrad, Regin and Radsvid. Now of the dwarfs I have rightly told. 13. Fili, Kili, Fundin, Nali, Hepti, Vili, Hanar, Svior, Billing, Bruni, Bild, Buri, Frar, Hornbori, Fraeg and Loni, Aurvang, Iari, Eikinskialdi.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Located by name in the Dvergatal of the Voluspa (Thorpe); verify the stanza.',DATE '2026-06-25','name-anchored + substring gate against Thorpe Poetic Edda (Gutenberg #14726)',1),
('CIT_BOMBUR_PEDDA','ENT_NOR_BOMBUR','SRC_POETIC_EDDA','The Poetic Edda (Voluspa)','Voluspa (Dvergatal)','Nyi and Nidi, Nordri and Sudri, Austri and Vestri, Althiof, Dvalin Nar and Nain, Niping, Dain, Bivor, Bavor, Bombur, Nori, An and Anar, Ai, Miodvitnir, 12. Veig and Gandalf, Vindalf, Thrain, Thekk and Thorin, Thror, Vitr, and Litr, Nur and Nyrad, Regin and Radsvid. Now of the dwarfs I have rightly told. 13. Fili, Kili, Fundin, Nali, Hepti, Vili, Hanar, Svior, Billing, Bruni, Bild, Buri, Frar, Hornbori, Fraeg and Loni, Aurvang, Iari, Eikinskialdi.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Located by name in the Dvergatal of the Voluspa (Thorpe); verify the stanza.',DATE '2026-06-25','name-anchored + substring gate against Thorpe Poetic Edda (Gutenberg #14726)',1),
('CIT_GANDALF_PEDDA','ENT_NOR_GANDALF','SRC_POETIC_EDDA','The Poetic Edda (Voluspa)','Voluspa (Dvergatal)','Veig and Gandalf, Vindalf, Thrain, Thekk and Thorin, Thror, Vitr, and Litr, Nur and Nyrad, Regin and Radsvid. Now of the dwarfs I have rightly told. 13. Fili, Kili, Fundin, Nali, Hepti, Vili, Hanar, Svior, Billing, Bruni, Bild, Buri, Frar, Hornbori, Fraeg and Loni, Aurvang, Iari, Eikinskialdi.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Located by name in the Dvergatal of the Voluspa (Thorpe); verify the stanza.',DATE '2026-06-25','name-anchored + substring gate against Thorpe Poetic Edda (Gutenberg #14726)',1),
('CIT_VINDALF_PEDDA','ENT_NOR_VINDALF','SRC_POETIC_EDDA','The Poetic Edda (Voluspa)','Voluspa (Dvergatal)','Veig and Gandalf, Vindalf, Thrain, Thekk and Thorin, Thror, Vitr, and Litr, Nur and Nyrad, Regin and Radsvid. Now of the dwarfs I have rightly told. 13. Fili, Kili, Fundin, Nali, Hepti, Vili, Hanar, Svior, Billing, Bruni, Bild, Buri, Frar, Hornbori, Fraeg and Loni, Aurvang, Iari, Eikinskialdi.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Located by name in the Dvergatal of the Voluspa (Thorpe); verify the stanza.',DATE '2026-06-25','name-anchored + substring gate against Thorpe Poetic Edda (Gutenberg #14726)',1),
('CIT_THRAIN_PEDDA','ENT_NOR_THRAIN','SRC_POETIC_EDDA','The Poetic Edda (Voluspa)','Voluspa (Dvergatal)','Veig and Gandalf, Vindalf, Thrain, Thekk and Thorin, Thror, Vitr, and Litr, Nur and Nyrad, Regin and Radsvid. Now of the dwarfs I have rightly told. 13. Fili, Kili, Fundin, Nali, Hepti, Vili, Hanar, Svior, Billing, Bruni, Bild, Buri, Frar, Hornbori, Fraeg and Loni, Aurvang, Iari, Eikinskialdi.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Located by name in the Dvergatal of the Voluspa (Thorpe); verify the stanza.',DATE '2026-06-25','name-anchored + substring gate against Thorpe Poetic Edda (Gutenberg #14726)',1),
('CIT_THEKK_PEDDA','ENT_NOR_THEKK','SRC_POETIC_EDDA','The Poetic Edda (Voluspa)','Voluspa (Dvergatal)','Veig and Gandalf, Vindalf, Thrain, Thekk and Thorin, Thror, Vitr, and Litr, Nur and Nyrad, Regin and Radsvid. Now of the dwarfs I have rightly told. 13. Fili, Kili, Fundin, Nali, Hepti, Vili, Hanar, Svior, Billing, Bruni, Bild, Buri, Frar, Hornbori, Fraeg and Loni, Aurvang, Iari, Eikinskialdi.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Located by name in the Dvergatal of the Voluspa (Thorpe); verify the stanza.',DATE '2026-06-25','name-anchored + substring gate against Thorpe Poetic Edda (Gutenberg #14726)',1),
('CIT_FUNDIN_PEDDA','ENT_NOR_FUNDIN','SRC_POETIC_EDDA','The Poetic Edda (Voluspa)','Voluspa (Dvergatal)','Fili, Kili, Fundin, Nali, Hepti, Vili, Hanar, Svior, Billing, Bruni, Bild, Buri, Frar, Hornbori, Fraeg and Loni, Aurvang, Iari, Eikinskialdi. 14. Time ''tis of the dwarfs in Dvalin''s band, to the sons of men, to Lofar up to reckon, those who came forth from the world''s rock, earth''s foundation, to Iora''s plains. 15.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Located by name in the Dvergatal of the Voluspa (Thorpe); verify the stanza.',DATE '2026-06-25','name-anchored + substring gate against Thorpe Poetic Edda (Gutenberg #14726)',1),
('CIT_HORNBORI_PEDDA','ENT_NOR_HORNBORI','SRC_POETIC_EDDA','The Poetic Edda (Voluspa)','Voluspa (Dvergatal)','Fili, Kili, Fundin, Nali, Hepti, Vili, Hanar, Svior, Billing, Bruni, Bild, Buri, Frar, Hornbori, Fraeg and Loni, Aurvang, Iari, Eikinskialdi. 14. Time ''tis of the dwarfs in Dvalin''s band, to the sons of men, to Lofar up to reckon, those who came forth from the world''s rock, earth''s foundation, to Iora''s plains. 15.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Located by name in the Dvergatal of the Voluspa (Thorpe); verify the stanza.',DATE '2026-06-25','name-anchored + substring gate against Thorpe Poetic Edda (Gutenberg #14726)',1),
('CIT_AURVANG_PEDDA','ENT_NOR_AURVANG','SRC_POETIC_EDDA','The Poetic Edda (Voluspa)','Voluspa (Dvergatal)','Fili, Kili, Fundin, Nali, Hepti, Vili, Hanar, Svior, Billing, Bruni, Bild, Buri, Frar, Hornbori, Fraeg and Loni, Aurvang, Iari, Eikinskialdi. 14. Time ''tis of the dwarfs in Dvalin''s band, to the sons of men, to Lofar up to reckon, those who came forth from the world''s rock, earth''s foundation, to Iora''s plains. 15.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Located by name in the Dvergatal of the Voluspa (Thorpe); verify the stanza.',DATE '2026-06-25','name-anchored + substring gate against Thorpe Poetic Edda (Gutenberg #14726)',1)
ON CONFLICT (citation_id) DO UPDATE SET quote=EXCLUDED.quote, locus=EXCLUDED.locus;

COMMIT;
