-- scripts/add_norse_goddesses_valkyries.sql
-- Norse Asynjur (goddesses, Snorri Gylfaginning, per-goddess clauses) + valkyries
-- (Grimnismal 36 stanza). Verbatim, substring-gated; held names skipped.

BEGIN;

INSERT INTO entities
  (entity_id, canonical_name, tradition, entity_type, category, primary_domains, cult_scope, primary_period, evidence_confidence, review_status, inclusion_basis, earth_association_score, chthonic_flag, serpent_flag, short_note, entity_class)
VALUES
('ENT_NOR_SAGA','Saga','Germanic/Norse','Goddess (Asynja)','Goddess','asynja; goddess; love/poetry','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Gylfaginning)',1,false,false,'One of the Asynjur (goddesses) of the Aesir, described in Snorri Gylfaginning.','deity'),
('ENT_NOR_GEFJUN','Gefjun','Germanic/Norse','Goddess (Asynja)','Goddess','asynja; goddess; maidens','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Gylfaginning)',1,false,false,'One of the Asynjur (goddesses) of the Aesir, described in Snorri Gylfaginning.','deity'),
('ENT_NOR_SJOFN','Sjofn','Germanic/Norse','Goddess (Asynja)','Goddess','asynja; goddess; love','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Gylfaginning)',1,false,false,'One of the Asynjur (goddesses) of the Aesir, described in Snorri Gylfaginning.','deity'),
('ENT_NOR_LOFN','Lofn','Germanic/Norse','Goddess (Asynja)','Goddess','asynja; goddess; love-union','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Gylfaginning)',1,false,false,'One of the Asynjur (goddesses) of the Aesir, described in Snorri Gylfaginning.','deity'),
('ENT_NOR_VAR','Var','Germanic/Norse','Goddess (Asynja)','Goddess','asynja; goddess; oaths','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Gylfaginning)',1,false,false,'One of the Asynjur (goddesses) of the Aesir, described in Snorri Gylfaginning.','deity'),
('ENT_NOR_VOR','Vor','Germanic/Norse','Goddess (Asynja)','Goddess','asynja; goddess; wisdom','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Gylfaginning)',1,false,false,'One of the Asynjur (goddesses) of the Aesir, described in Snorri Gylfaginning.','deity'),
('ENT_NOR_SYN','Syn','Germanic/Norse','Goddess (Asynja)','Goddess','asynja; goddess; refusal/defence','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Gylfaginning)',1,false,false,'One of the Asynjur (goddesses) of the Aesir, described in Snorri Gylfaginning.','deity'),
('ENT_NOR_HLIN','Hlin','Germanic/Norse','Goddess (Asynja)','Goddess','asynja; goddess; protection','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Gylfaginning)',1,false,false,'One of the Asynjur (goddesses) of the Aesir, described in Snorri Gylfaginning.','deity'),
('ENT_NOR_SNOTRA','Snotra','Germanic/Norse','Goddess (Asynja)','Goddess','asynja; goddess; prudence','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Gylfaginning)',1,false,false,'One of the Asynjur (goddesses) of the Aesir, described in Snorri Gylfaginning.','deity'),
('ENT_NOR_GNA','Gna','Germanic/Norse','Goddess (Asynja)','Goddess','asynja; goddess; errands','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Gylfaginning)',1,false,false,'One of the Asynjur (goddesses) of the Aesir, described in Snorri Gylfaginning.','deity'),
('ENT_NOR_VK_HRIST','Hrist','Germanic/Norse','Valkyrie','Valkyrie','valkyrie; chooser of the slain; serves in Valhalla','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Grimnismal 36)',1,false,false,'One of the valkyries who bear ale to the Einherjar in Valhalla, named in Grimnismal 36.','spirit'),
('ENT_NOR_VK_MIST','Mist','Germanic/Norse','Valkyrie','Valkyrie','valkyrie; chooser of the slain; serves in Valhalla','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Grimnismal 36)',1,false,false,'One of the valkyries who bear ale to the Einherjar in Valhalla, named in Grimnismal 36.','spirit'),
('ENT_NOR_VK_SKEGGOLD','Skeggold','Germanic/Norse','Valkyrie','Valkyrie','valkyrie; chooser of the slain; serves in Valhalla','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Grimnismal 36)',1,false,false,'One of the valkyries who bear ale to the Einherjar in Valhalla, named in Grimnismal 36.','spirit'),
('ENT_NOR_VK_SKOGUL','Skogul','Germanic/Norse','Valkyrie','Valkyrie','valkyrie; chooser of the slain; serves in Valhalla','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Grimnismal 36)',1,false,false,'One of the valkyries who bear ale to the Einherjar in Valhalla, named in Grimnismal 36.','spirit'),
('ENT_NOR_VK_HLOKK','Hlokk','Germanic/Norse','Valkyrie','Valkyrie','valkyrie; chooser of the slain; serves in Valhalla','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Grimnismal 36)',1,false,false,'One of the valkyries who bear ale to the Einherjar in Valhalla, named in Grimnismal 36.','spirit'),
('ENT_NOR_VK_HERFIOTUR','Herfiotur','Germanic/Norse','Valkyrie','Valkyrie','valkyrie; chooser of the slain; serves in Valhalla','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Grimnismal 36)',1,false,false,'One of the valkyries who bear ale to the Einherjar in Valhalla, named in Grimnismal 36.','spirit'),
('ENT_NOR_VK_HILD','Hild','Germanic/Norse','Valkyrie','Valkyrie','valkyrie; chooser of the slain; serves in Valhalla','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Grimnismal 36)',1,false,false,'One of the valkyries who bear ale to the Einherjar in Valhalla, named in Grimnismal 36.','spirit'),
('ENT_NOR_VK_THRUD','Thrud','Germanic/Norse','Valkyrie','Valkyrie','valkyrie; chooser of the slain; serves in Valhalla','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Grimnismal 36)',1,false,false,'One of the valkyries who bear ale to the Einherjar in Valhalla, named in Grimnismal 36.','spirit'),
('ENT_NOR_VK_GOLL','Goll','Germanic/Norse','Valkyrie','Valkyrie','valkyrie; chooser of the slain; serves in Valhalla','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Grimnismal 36)',1,false,false,'One of the valkyries who bear ale to the Einherjar in Valhalla, named in Grimnismal 36.','spirit'),
('ENT_NOR_VK_GEIROLUL','Geirolul','Germanic/Norse','Valkyrie','Valkyrie','valkyrie; chooser of the slain; serves in Valhalla','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Grimnismal 36)',1,false,false,'One of the valkyries who bear ale to the Einherjar in Valhalla, named in Grimnismal 36.','spirit'),
('ENT_NOR_VK_RANDGRID','Randgrid','Germanic/Norse','Valkyrie','Valkyrie','valkyrie; chooser of the slain; serves in Valhalla','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Grimnismal 36)',1,false,false,'One of the valkyries who bear ale to the Einherjar in Valhalla, named in Grimnismal 36.','spirit'),
('ENT_NOR_VK_RADGRID','Radgrid','Germanic/Norse','Valkyrie','Valkyrie','valkyrie; chooser of the slain; serves in Valhalla','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Grimnismal 36)',1,false,false,'One of the valkyries who bear ale to the Einherjar in Valhalla, named in Grimnismal 36.','spirit'),
('ENT_NOR_VK_REGINLEIF','Reginleif','Germanic/Norse','Valkyrie','Valkyrie','valkyrie; chooser of the slain; serves in Valhalla','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Grimnismal 36)',1,false,false,'One of the valkyries who bear ale to the Einherjar in Valhalla, named in Grimnismal 36.','spirit')
ON CONFLICT (entity_id) DO NOTHING;

INSERT INTO entity_citations
  (citation_id,entity_id,source_id,work_title,locus,quote,translator,translation_year,source_url,original_text_url,evidence_grade,evidence_note,needs_review,review_reason,verified_on,verify_method,display_order)
VALUES
('CIT_NOR_SAGA_EDDA','ENT_NOR_SAGA','SRC_PROSE_EDDA','Snorri Sturluson, Prose Edda (Gylfaginning)','Gylfaginning','The goddess is Saga, who dwells in Sokvabek, and this is a large dwelling.','Rasmus B. Anderson',1880,'https://www.gutenberg.org/ebooks/18947',NULL,'primary-verbatim',NULL,true,'Named in Snorri Sturluson, Prose Edda (Gylfaginning); verify.',DATE '2026-06-26','name + substring gate against Snorri Sturluson, Prose Edda (Gylfaginning)',1),
('CIT_NOR_GEFJUN_EDDA','ENT_NOR_GEFJUN','SRC_PROSE_EDDA','Snorri Sturluson, Prose Edda (Gylfaginning)','Gylfaginning','The goddess is Gefjun, who is a may, and those who die maids become her hand-maidens.','Rasmus B. Anderson',1880,'https://www.gutenberg.org/ebooks/18947',NULL,'primary-verbatim',NULL,true,'Named in Snorri Sturluson, Prose Edda (Gylfaginning); verify.',DATE '2026-06-26','name + substring gate against Snorri Sturluson, Prose Edda (Gylfaginning)',1),
('CIT_NOR_SJOFN_EDDA','ENT_NOR_SJOFN','SRC_PROSE_EDDA','Snorri Sturluson, Prose Edda (Gylfaginning)','Gylfaginning','The goddess is Sjofn, who is fond of turning men’s and women’s hearts to love, and it is from her name that love is called Sjafne.','Rasmus B. Anderson',1880,'https://www.gutenberg.org/ebooks/18947',NULL,'primary-verbatim',NULL,true,'Named in Snorri Sturluson, Prose Edda (Gylfaginning); verify.',DATE '2026-06-26','name + substring gate against Snorri Sturluson, Prose Edda (Gylfaginning)',1),
('CIT_NOR_LOFN_EDDA','ENT_NOR_LOFN','SRC_PROSE_EDDA','Snorri Sturluson, Prose Edda (Gylfaginning)','Gylfaginning','The goddess is Lofn, who is kind and good to those who call upon her, and she has permission from Alfather or Frigg to bring together men and women, no matter what difficulties may stand in the way; therefore “love” is so called from her name, and also that which is much loved by men.','Rasmus B. Anderson',1880,'https://www.gutenberg.org/ebooks/18947',NULL,'primary-verbatim',NULL,true,'Named in Snorri Sturluson, Prose Edda (Gylfaginning); verify.',DATE '2026-06-26','name + substring gate against Snorri Sturluson, Prose Edda (Gylfaginning)',1),
('CIT_NOR_VAR_EDDA','ENT_NOR_VAR','SRC_PROSE_EDDA','Snorri Sturluson, Prose Edda (Gylfaginning)','Gylfaginning','The goddess is Var.','Rasmus B. Anderson',1880,'https://www.gutenberg.org/ebooks/18947',NULL,'primary-verbatim',NULL,true,'Named in Snorri Sturluson, Prose Edda (Gylfaginning); verify.',DATE '2026-06-26','name + substring gate against Snorri Sturluson, Prose Edda (Gylfaginning)',1),
('CIT_NOR_VOR_EDDA','ENT_NOR_VOR','SRC_PROSE_EDDA','Snorri Sturluson, Prose Edda (Gylfaginning)','Gylfaginning','The goddess is Vor, who is so wise and searching that nothing can be concealed from her.','Rasmus B. Anderson',1880,'https://www.gutenberg.org/ebooks/18947',NULL,'primary-verbatim',NULL,true,'Named in Snorri Sturluson, Prose Edda (Gylfaginning); verify.',DATE '2026-06-26','name + substring gate against Snorri Sturluson, Prose Edda (Gylfaginning)',1),
('CIT_NOR_SYN_EDDA','ENT_NOR_SYN','SRC_PROSE_EDDA','Snorri Sturluson, Prose Edda (Gylfaginning)','Gylfaginning','The goddess is Syn, who guards the door of the hall, and closes it against those who are not to enter.','Rasmus B. Anderson',1880,'https://www.gutenberg.org/ebooks/18947',NULL,'primary-verbatim',NULL,true,'Named in Snorri Sturluson, Prose Edda (Gylfaginning); verify.',DATE '2026-06-26','name + substring gate against Snorri Sturluson, Prose Edda (Gylfaginning)',1),
('CIT_NOR_HLIN_EDDA','ENT_NOR_HLIN','SRC_PROSE_EDDA','Snorri Sturluson, Prose Edda (Gylfaginning)','Gylfaginning','The goddess is Hlin, who guards those men whom Frigg wants to protect from any danger.','Rasmus B. Anderson',1880,'https://www.gutenberg.org/ebooks/18947',NULL,'primary-verbatim',NULL,true,'Named in Snorri Sturluson, Prose Edda (Gylfaginning); verify.',DATE '2026-06-26','name + substring gate against Snorri Sturluson, Prose Edda (Gylfaginning)',1),
('CIT_NOR_SNOTRA_EDDA','ENT_NOR_SNOTRA','SRC_PROSE_EDDA','Snorri Sturluson, Prose Edda (Gylfaginning)','Gylfaginning','The goddess is Snotra, who is wise and courtly.','Rasmus B. Anderson',1880,'https://www.gutenberg.org/ebooks/18947',NULL,'primary-verbatim',NULL,true,'Named in Snorri Sturluson, Prose Edda (Gylfaginning); verify.',DATE '2026-06-26','name + substring gate against Snorri Sturluson, Prose Edda (Gylfaginning)',1),
('CIT_NOR_GNA_EDDA','ENT_NOR_GNA','SRC_PROSE_EDDA','Snorri Sturluson, Prose Edda (Gylfaginning)','Gylfaginning','The goddess is Gna, whom Frigg sends on her errands into various worlds.','Rasmus B. Anderson',1880,'https://www.gutenberg.org/ebooks/18947',NULL,'primary-verbatim',NULL,true,'Named in Snorri Sturluson, Prose Edda (Gylfaginning); verify.',DATE '2026-06-26','name + substring gate against Snorri Sturluson, Prose Edda (Gylfaginning)',1),
('CIT_NOR_VK_HRIST_EDDA','ENT_NOR_VK_HRIST','SRC_POETIC_EDDA','The Poetic Edda (Grimnismal)','Grimnismal 36','Hrist and Mist the horn shall bear me Skeggold and Skogul, Hlokk and Herfiotur, Hildi and Thrudi, Goll and Geirolul, Randgrid and Radgrid, and Reginleif, these bear beer to the Einheriar.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Named in The Poetic Edda (Grimnismal); verify.',DATE '2026-06-26','name + substring gate against The Poetic Edda (Grimnismal)',1),
('CIT_NOR_VK_MIST_EDDA','ENT_NOR_VK_MIST','SRC_POETIC_EDDA','The Poetic Edda (Grimnismal)','Grimnismal 36','Hrist and Mist the horn shall bear me Skeggold and Skogul, Hlokk and Herfiotur, Hildi and Thrudi, Goll and Geirolul, Randgrid and Radgrid, and Reginleif, these bear beer to the Einheriar.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Named in The Poetic Edda (Grimnismal); verify.',DATE '2026-06-26','name + substring gate against The Poetic Edda (Grimnismal)',1),
('CIT_NOR_VK_SKEGGOLD_EDDA','ENT_NOR_VK_SKEGGOLD','SRC_POETIC_EDDA','The Poetic Edda (Grimnismal)','Grimnismal 36','Hrist and Mist the horn shall bear me Skeggold and Skogul, Hlokk and Herfiotur, Hildi and Thrudi, Goll and Geirolul, Randgrid and Radgrid, and Reginleif, these bear beer to the Einheriar.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Named in The Poetic Edda (Grimnismal); verify.',DATE '2026-06-26','name + substring gate against The Poetic Edda (Grimnismal)',1),
('CIT_NOR_VK_SKOGUL_EDDA','ENT_NOR_VK_SKOGUL','SRC_POETIC_EDDA','The Poetic Edda (Grimnismal)','Grimnismal 36','Hrist and Mist the horn shall bear me Skeggold and Skogul, Hlokk and Herfiotur, Hildi and Thrudi, Goll and Geirolul, Randgrid and Radgrid, and Reginleif, these bear beer to the Einheriar.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Named in The Poetic Edda (Grimnismal); verify.',DATE '2026-06-26','name + substring gate against The Poetic Edda (Grimnismal)',1),
('CIT_NOR_VK_HLOKK_EDDA','ENT_NOR_VK_HLOKK','SRC_POETIC_EDDA','The Poetic Edda (Grimnismal)','Grimnismal 36','Hrist and Mist the horn shall bear me Skeggold and Skogul, Hlokk and Herfiotur, Hildi and Thrudi, Goll and Geirolul, Randgrid and Radgrid, and Reginleif, these bear beer to the Einheriar.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Named in The Poetic Edda (Grimnismal); verify.',DATE '2026-06-26','name + substring gate against The Poetic Edda (Grimnismal)',1),
('CIT_NOR_VK_HERFIOTUR_EDDA','ENT_NOR_VK_HERFIOTUR','SRC_POETIC_EDDA','The Poetic Edda (Grimnismal)','Grimnismal 36','Hrist and Mist the horn shall bear me Skeggold and Skogul, Hlokk and Herfiotur, Hildi and Thrudi, Goll and Geirolul, Randgrid and Radgrid, and Reginleif, these bear beer to the Einheriar.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Named in The Poetic Edda (Grimnismal); verify.',DATE '2026-06-26','name + substring gate against The Poetic Edda (Grimnismal)',1),
('CIT_NOR_VK_HILD_EDDA','ENT_NOR_VK_HILD','SRC_POETIC_EDDA','The Poetic Edda (Grimnismal)','Grimnismal 36','Hrist and Mist the horn shall bear me Skeggold and Skogul, Hlokk and Herfiotur, Hildi and Thrudi, Goll and Geirolul, Randgrid and Radgrid, and Reginleif, these bear beer to the Einheriar.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Named in The Poetic Edda (Grimnismal); verify.',DATE '2026-06-26','name + substring gate against The Poetic Edda (Grimnismal)',1),
('CIT_NOR_VK_THRUD_EDDA','ENT_NOR_VK_THRUD','SRC_POETIC_EDDA','The Poetic Edda (Grimnismal)','Grimnismal 36','Hrist and Mist the horn shall bear me Skeggold and Skogul, Hlokk and Herfiotur, Hildi and Thrudi, Goll and Geirolul, Randgrid and Radgrid, and Reginleif, these bear beer to the Einheriar.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Named in The Poetic Edda (Grimnismal); verify.',DATE '2026-06-26','name + substring gate against The Poetic Edda (Grimnismal)',1),
('CIT_NOR_VK_GOLL_EDDA','ENT_NOR_VK_GOLL','SRC_POETIC_EDDA','The Poetic Edda (Grimnismal)','Grimnismal 36','Hrist and Mist the horn shall bear me Skeggold and Skogul, Hlokk and Herfiotur, Hildi and Thrudi, Goll and Geirolul, Randgrid and Radgrid, and Reginleif, these bear beer to the Einheriar.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Named in The Poetic Edda (Grimnismal); verify.',DATE '2026-06-26','name + substring gate against The Poetic Edda (Grimnismal)',1),
('CIT_NOR_VK_GEIROLUL_EDDA','ENT_NOR_VK_GEIROLUL','SRC_POETIC_EDDA','The Poetic Edda (Grimnismal)','Grimnismal 36','Hrist and Mist the horn shall bear me Skeggold and Skogul, Hlokk and Herfiotur, Hildi and Thrudi, Goll and Geirolul, Randgrid and Radgrid, and Reginleif, these bear beer to the Einheriar.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Named in The Poetic Edda (Grimnismal); verify.',DATE '2026-06-26','name + substring gate against The Poetic Edda (Grimnismal)',1),
('CIT_NOR_VK_RANDGRID_EDDA','ENT_NOR_VK_RANDGRID','SRC_POETIC_EDDA','The Poetic Edda (Grimnismal)','Grimnismal 36','Hrist and Mist the horn shall bear me Skeggold and Skogul, Hlokk and Herfiotur, Hildi and Thrudi, Goll and Geirolul, Randgrid and Radgrid, and Reginleif, these bear beer to the Einheriar.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Named in The Poetic Edda (Grimnismal); verify.',DATE '2026-06-26','name + substring gate against The Poetic Edda (Grimnismal)',1),
('CIT_NOR_VK_RADGRID_EDDA','ENT_NOR_VK_RADGRID','SRC_POETIC_EDDA','The Poetic Edda (Grimnismal)','Grimnismal 36','Hrist and Mist the horn shall bear me Skeggold and Skogul, Hlokk and Herfiotur, Hildi and Thrudi, Goll and Geirolul, Randgrid and Radgrid, and Reginleif, these bear beer to the Einheriar.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Named in The Poetic Edda (Grimnismal); verify.',DATE '2026-06-26','name + substring gate against The Poetic Edda (Grimnismal)',1),
('CIT_NOR_VK_REGINLEIF_EDDA','ENT_NOR_VK_REGINLEIF','SRC_POETIC_EDDA','The Poetic Edda (Grimnismal)','Grimnismal 36','Hrist and Mist the horn shall bear me Skeggold and Skogul, Hlokk and Herfiotur, Hildi and Thrudi, Goll and Geirolul, Randgrid and Radgrid, and Reginleif, these bear beer to the Einheriar.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Named in The Poetic Edda (Grimnismal); verify.',DATE '2026-06-26','name + substring gate against The Poetic Edda (Grimnismal)',1)
ON CONFLICT (citation_id) DO UPDATE SET quote=EXCLUDED.quote;

COMMIT;
