-- scripts/add_greek_monster_groups.sql
-- Named members of Greek monster-groups (Cyclopes, Hekatoncheires, Gorgons, Harpies,
-- Graeae) from Hesiod Theogony (Evelyn-White). Verbatim, substring-gated; held/colliding names skipped.

BEGIN;

INSERT INTO entities
  (entity_id, canonical_name, tradition, entity_type, category, primary_domains, cult_scope, primary_period, evidence_confidence, review_status, inclusion_basis, earth_association_score, chthonic_flag, serpent_flag, short_note, entity_class)
VALUES
('ENT_BRONTES','Brontes','Greek','Cyclops','Giant','Cyclops; thunder','Greek','archaic Greek','A','candidate_verified_name','Primary attestation (Theogony 139-141)',2,false,false,'One of the three Cyclopes (with Steropes and Arges) who forged the thunderbolt of Zeus.','monster'),
('ENT_STEROPES','Steropes','Greek','Cyclops','Giant','Cyclops; lightning','Greek','archaic Greek','A','candidate_verified_name','Primary attestation (Theogony 139-141)',2,false,false,'One of the three Cyclopes (with Brontes and Arges) who forged the thunderbolt of Zeus.','monster'),
('ENT_ARGES','Arges','Greek','Cyclops','Giant','Cyclops; brightness','Greek','archaic Greek','A','candidate_verified_name','Primary attestation (Theogony 139-141)',2,false,false,'One of the three Cyclopes (with Brontes and Steropes) who forged the thunderbolt of Zeus.','monster'),
('ENT_COTTUS','Cottus','Greek','Hundred-Hander','Giant','hundred-hander; storm','Greek','archaic Greek','A','candidate_verified_name','Primary attestation (Theogony 147-153)',2,false,false,'One of the three Hekatoncheires (Hundred-Handers), hundred-armed sons of Ouranos and Gaia.','monster'),
('ENT_BRIAREUS','Briareus','Greek','Hundred-Hander','Giant','hundred-hander; sea','Greek','archaic Greek','A','candidate_verified_name','Primary attestation (Theogony 147-153)',2,false,false,'One of the three Hekatoncheires (Hundred-Handers), hundred-armed sons of Ouranos and Gaia.','monster'),
('ENT_GYES','Gyes','Greek','Hundred-Hander','Giant','hundred-hander','Greek','archaic Greek','A','candidate_verified_name','Primary attestation (Theogony 147-153)',2,false,false,'One of the three Hekatoncheires (Hundred-Handers), hundred-armed sons of Ouranos and Gaia.','monster'),
('ENT_EURYALE','Euryale','Greek','Gorgon','Monster','Gorgon','Greek','archaic Greek','A','candidate_verified_name','Primary attestation (Theogony 270-276)',2,false,false,'One of the three Gorgons (with Stheno and Medusa), daughters of Phorcys and Ceto.','monster'),
('ENT_AELLO','Aello','Greek','Harpy','Monster','Harpy; storm-wind','Greek','archaic Greek','A','candidate_verified_name','Primary attestation (Theogony 265-269)',2,false,false,'One of the Harpies (with Ocypete), winged storm-spirits, daughters of Thaumas.','monster'),
('ENT_PEMPHREDO','Pemphredo','Greek','Graea','Monster','Graea','Greek','archaic Greek','A','candidate_verified_name','Primary attestation (Theogony 270-273)',2,false,false,'One of the Graeae (the Grey Sisters, with Enyo), daughters of Phorcys and Ceto.','spirit')
ON CONFLICT (entity_id) DO NOTHING;

INSERT INTO entity_citations
  (citation_id,entity_id,source_id,work_title,locus,quote,translator,translation_year,source_url,original_text_url,evidence_grade,evidence_note,needs_review,review_reason,verified_on,verify_method,display_order)
VALUES
('CIT_BRONTES_THEOG','ENT_BRONTES','SRC_HESIOD_THEOGONY','Hesiod, Theogony','Theogony 139-141','139-146) And again, she bare the Cyclopes, overbearing in spirit, Brontes, and Steropes and stubborn-hearted Arges 1606, who gave Zeus the thunder and made the thunderbolt: in all else they were like the gods, but one eye only was set in th','Hugh G. Evelyn-White',1914,'https://www.gutenberg.org/ebooks/348',NULL,'primary-verbatim',NULL,true,'Named in Hesiod Theogony (Evelyn-White); verify line.',DATE '2026-06-26','name + substring gate against Evelyn-White Theogony (#348)',1),
('CIT_STEROPES_THEOG','ENT_STEROPES','SRC_HESIOD_THEOGONY','Hesiod, Theogony','Theogony 139-141','139-146) And again, she bare the Cyclopes, overbearing in spirit, Brontes, and Steropes and stubborn-hearted Arges 1606, who gave Zeus the thunder and made the thunderbolt: in all else they were like the gods, but one eye only was set in th','Hugh G. Evelyn-White',1914,'https://www.gutenberg.org/ebooks/348',NULL,'primary-verbatim',NULL,true,'Named in Hesiod Theogony (Evelyn-White); verify line.',DATE '2026-06-26','name + substring gate against Evelyn-White Theogony (#348)',1),
('CIT_ARGES_THEOG','ENT_ARGES','SRC_HESIOD_THEOGONY','Hesiod, Theogony','Theogony 139-141','139-146) And again, she bare the Cyclopes, overbearing in spirit, Brontes, and Steropes and stubborn-hearted Arges 1606, who gave Zeus the thunder and made the thunderbolt: in all else they were like the gods, but one eye only was set in th','Hugh G. Evelyn-White',1914,'https://www.gutenberg.org/ebooks/348',NULL,'primary-verbatim',NULL,true,'Named in Hesiod Theogony (Evelyn-White); verify line.',DATE '2026-06-26','name + substring gate against Evelyn-White Theogony (#348)',1),
('CIT_COTTUS_THEOG','ENT_COTTUS','SRC_HESIOD_THEOGONY','Hesiod, Theogony','Theogony 147-153','147-163) And again, three other sons were born of Earth and Heaven, great and doughty beyond telling, Cottus and Briareos and Gyes, presumptuous children.','Hugh G. Evelyn-White',1914,'https://www.gutenberg.org/ebooks/348',NULL,'primary-verbatim',NULL,true,'Named in Hesiod Theogony (Evelyn-White); verify line.',DATE '2026-06-26','name + substring gate against Evelyn-White Theogony (#348)',1),
('CIT_BRIAREUS_THEOG','ENT_BRIAREUS','SRC_HESIOD_THEOGONY','Hesiod, Theogony','Theogony 147-153','147-163) And again, three other sons were born of Earth and Heaven, great and doughty beyond telling, Cottus and Briareos and Gyes, presumptuous children.','Hugh G. Evelyn-White',1914,'https://www.gutenberg.org/ebooks/348',NULL,'primary-verbatim',NULL,true,'Named in Hesiod Theogony (Evelyn-White); verify line.',DATE '2026-06-26','name + substring gate against Evelyn-White Theogony (#348)',1),
('CIT_GYES_THEOG','ENT_GYES','SRC_HESIOD_THEOGONY','Hesiod, Theogony','Theogony 147-153','147-163) And again, three other sons were born of Earth and Heaven, great and doughty beyond telling, Cottus and Briareos and Gyes, presumptuous children.','Hugh G. Evelyn-White',1914,'https://www.gutenberg.org/ebooks/348',NULL,'primary-verbatim',NULL,true,'Named in Hesiod Theogony (Evelyn-White); verify line.',DATE '2026-06-26','name + substring gate against Evelyn-White Theogony (#348)',1),
('CIT_EURYALE_THEOG','ENT_EURYALE','SRC_HESIOD_THEOGONY','Hesiod, Theogony','Theogony 270-276','xxxii: Orion.]—Hesiod says that he was the son of Euryale, the daughter of Minos, and of Poseidon, and that there was given him as a gift the power of walking upon the waves as though upon land.','Hugh G. Evelyn-White',1914,'https://www.gutenberg.org/ebooks/348',NULL,'primary-verbatim',NULL,true,'Named in Hesiod Theogony (Evelyn-White); verify line.',DATE '2026-06-26','name + substring gate against Evelyn-White Theogony (#348)',1),
('CIT_AELLO_THEOG','ENT_AELLO','SRC_HESIOD_THEOGONY','Hesiod, Theogony','Theogony 265-269','265-269) And Thaumas wedded Electra the daughter of deep-flowing Ocean, and she bare him swift Iris and the long-haired Harpies, Aello (Storm-swift) and Ocypetes (Swift-flier) who on their swift wings keep pace with the blasts of the winds','Hugh G. Evelyn-White',1914,'https://www.gutenberg.org/ebooks/348',NULL,'primary-verbatim',NULL,true,'Named in Hesiod Theogony (Evelyn-White); verify line.',DATE '2026-06-26','name + substring gate against Evelyn-White Theogony (#348)',1),
('CIT_PEMPHREDO_THEOG','ENT_PEMPHREDO','SRC_HESIOD_THEOGONY','Hesiod, Theogony','Theogony 270-273','(ll 270-294) And again, Ceto bare to Phorcys the fair-cheeked Graiae, sisters grey from their birth: and both deathless gods and men who walk on earth call them Graiae, Pemphredo well-clad, and saffron-robed Enyo, and the Gorgons who dwell','Hugh G. Evelyn-White',1914,'https://www.gutenberg.org/ebooks/348',NULL,'primary-verbatim',NULL,true,'Named in Hesiod Theogony (Evelyn-White); verify line.',DATE '2026-06-26','name + substring gate against Evelyn-White Theogony (#348)',1)
ON CONFLICT (citation_id) DO UPDATE SET quote=EXCLUDED.quote;


-- quote fixes (strip Gutenberg line-markers; Euryale → Gorgon passage):
UPDATE entity_citations SET quote='And again, she bare the Cyclopes, overbearing in spirit, Brontes, and Steropes and stubborn-hearted Arges 1606, who gave Zeus the thunder and made the thunderbolt: in all else they were like the gods, but one eye only was se' WHERE citation_id='CIT_BRONTES_THEOG';
UPDATE entity_citations SET quote='And again, she bare the Cyclopes, overbearing in spirit, Brontes, and Steropes and stubborn-hearted Arges 1606, who gave Zeus the thunder and made the thunderbolt: in all else they were like the gods, but one eye only was set in the midst' WHERE citation_id='CIT_STEROPES_THEOG';
UPDATE entity_citations SET quote='And again, she bare the Cyclopes, overbearing in spirit, Brontes, and Steropes and stubborn-hearted Arges 1606, who gave Zeus the thunder and made the thunderbolt: in all else they were like the gods, but one eye only was set in the midst of their fore-heads.' WHERE citation_id='CIT_ARGES_THEOG';
UPDATE entity_citations SET quote='And again, three other sons were born of Earth and Heaven, great and doughty beyond telling, Cottus and Briareos and Gyes, presumptuous children.' WHERE citation_id='CIT_COTTUS_THEOG';
UPDATE entity_citations SET quote='And again, three other sons were born of Earth and Heaven, great and doughty beyond telling, Cottus and Briareos and Gyes, presumptuous children.' WHERE citation_id='CIT_BRIAREUS_THEOG';
UPDATE entity_citations SET quote='And again, three other sons were born of Earth and Heaven, great and doughty beyond telling, Cottus and Briareos and Gyes, presumptuous children.' WHERE citation_id='CIT_GYES_THEOG';
UPDATE entity_citations SET quote='an in the frontier land towards Night where are the clear-voiced Hesperides, Sthenno, and Euryale, and Medusa who suffered a woeful fate: she was mortal, but the two were undying and grew not old.' WHERE citation_id='CIT_EURYALE_THEOG';
UPDATE entity_citations SET quote='And Thaumas wedded Electra the daughter of deep-flowing Ocean, and she bare him swift Iris and the long-haired Harpies, Aello (Storm-swift) and Ocypetes (Swift-flier) who on their swift wings keep pace with the blasts of the winds and the birds; for quick as time they dart along.' WHERE citation_id='CIT_AELLO_THEOG';
UPDATE entity_citations SET quote='And again, Ceto bare to Phorcys the fair-cheeked Graiae, sisters grey from their birth: and both deathless gods and men who walk on earth call them Graiae, Pemphredo well-clad, and saffron-robed Enyo, and the Gorgons who dwell beyond glorious Ocean in the frontier land towards Night where are the clear-voiced Hesperides, St' WHERE citation_id='CIT_PEMPHREDO_THEOG';
COMMIT;
