-- scripts/add_nag_hammadi_clusters.sql
-- Nag Hammadi verify-and-add pass, batches 2-4 (Gospel of the Egyptians NHC III,2;
-- Apocryphon of John NHC II,1; Paraphrase of Shem NHC VII,1). Same method as
-- add_nag_hammadi_sethian.sql: real verbatim excerpts substring-gated against the
-- Robinson NHL text (gnosis.org), extracted via cite_anchor.py, trimmed to a
-- clause/sentence boundary. Flagged needs_review. No AI-written descriptions.

BEGIN;

INSERT INTO entities
  (entity_id, canonical_name, tradition, entity_type, category, primary_domains, cult_scope, primary_period, evidence_confidence, review_status, inclusion_basis, earth_association_score, chthonic_flag, serpent_flag, short_note, entity_class)
VALUES
('ENT_SET_SAMBLO','Samblo','Sethian','Angelic minister','Angelic Being','Samblo; ministry of the four luminaries','Sethian','2nd-3rd c. CE','A','candidate_verified_name','Nag Hammadi primary attestation (NHC III,2)',1,false,false,'One of the four ministers of the four luminaries (with Gamaliel, Gabriel, Abrasax) in the Gospel of the Egyptians (NHC III,2).','angel'),
('ENT_SET_ESEPHECH','Esephech','Sethian','Divine child','Aeon','Esephech; the child of the child; glory','Sethian','2nd-3rd c. CE','A','candidate_verified_name','Nag Hammadi primary attestation (NHC III,2)',1,false,false,'Sethian divine child, ''the holder of glory, the child of the child,'' in the Gospel of the Egyptians (NHC III,2).','aeon'),
('ENT_SET_MICHEUS','Micheus','Sethian','Baptismal power','Angelic Being','baptism; living water; spring of truth','Sethian','2nd-3rd c. CE','A','candidate_verified_name','Nag Hammadi primary attestation (NHC III,2)',1,false,false,'Sethian baptismal power over the holy baptism and living water (paired with Michar) in the Gospel of the Egyptians (NHC III,2).','spirit'),
('ENT_SET_MICHAR','Michar','Sethian','Baptismal power','Angelic Being','baptism; living water; spring of truth','Sethian','2nd-3rd c. CE','A','candidate_verified_name','Nag Hammadi primary attestation (NHC III,2)',1,false,false,'Sethian baptismal power over the holy baptism and living water (paired with Micheus) in the Gospel of the Egyptians (NHC III,2).','spirit'),
('ENT_SET_MNESINOUS','Mnesinous','Sethian','Baptismal power','Angelic Being','baptism; living water; spring of truth','Sethian','2nd-3rd c. CE','A','candidate_verified_name','Nag Hammadi primary attestation (NHC III,2)',1,false,false,'Sethian baptismal power over the spring of truth and living water in the Gospel of the Egyptians (NHC III,2).','spirit'),
('ENT_SET_SESENGENPHARANGES','Sesengenpharanges','Sethian','Baptismal power','Angelic Being','baptism of the living; purification','Sethian','2nd-3rd c. CE','A','candidate_verified_name','Nag Hammadi primary attestation (NHC III,2)',1,false,false,'Sethian baptismal power over the baptism of the living and the purifiers in the Gospel of the Egyptians (NHC III,2).','spirit'),
('ENT_SET_ATHOTH','Athoth','Sethian','Archon','Archon','archon; rulership','Sethian','2nd-3rd c. CE','A','candidate_verified_name','Nag Hammadi primary attestation (NHC II,1)',1,false,false,'First of the twelve rulers under Yaldabaoth, ''whom the generations call the reaper,'' in the Apocryphon of John (NHC II,1).','demon'),
('ENT_SET_HARMAS','Harmas','Sethian','Archon','Archon','archon; rulership','Sethian','2nd-3rd c. CE','A','candidate_verified_name','Nag Hammadi primary attestation (NHC II,1)',1,false,false,'Second of the twelve rulers under Yaldabaoth, ''the eye of envy,'' in the Apocryphon of John (NHC II,1).','demon'),
('ENT_SET_YABEL','Yabel','Sethian','Archon','Archon','archon; rulership','Sethian','2nd-3rd c. CE','A','candidate_verified_name','Nag Hammadi primary attestation (NHC II,1)',1,false,false,'Fourth of the twelve rulers under Yaldabaoth in the Apocryphon of John (NHC II,1).','demon'),
('ENT_GNO_DERDEKEAS','Derdekeas','Gnostic','Revealer/savior figure','Revealer Figure','Derdekeas; revelation; salvation; the infinite Light','Gnostic','2nd-3rd c. CE','A','candidate_verified_name','Nag Hammadi primary attestation (NHC VII,1)',1,false,false,'Savior-revealer, ''son of the incorruptible, infinite Light,'' in the Paraphrase of Shem (NHC VII,1).','prophet')
ON CONFLICT (entity_id) DO NOTHING;

INSERT INTO entity_aliases
  (entity_id, alias_name, alias_type, language, source_id, confidence, review_status, notes)
SELECT 'ENT_SET_HARMAS','Armas','variant','en','SRC_NAG_HAMMADI_SCRIPTURES','high','candidate_verified_name','Variant spelling attested in the same tractate.' WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_SET_HARMAS' AND alias_name='Armas');

INSERT INTO entity_citations
  (citation_id,entity_id,source_id,work_title,locus,quote,translator,translation_year,source_url,original_text_url,evidence_grade,evidence_note,needs_review,review_reason,verified_on,verify_method,display_order)
VALUES
('CIT_SET_SAMBLO_NHC','ENT_SET_SAMBLO','SRC_NAG_HAMMADI_SCRIPTURES','The Nag Hammadi Library (Robinson, ed.)','Gospel of the Egyptians, NHC III,2','Seth, the ministers of the four lights, the great Gamaliel, the great Gabriel, the great Samblo, and the great Abrasax, and they who preside over the sun, its rising, Olses and Hypneus and Heurumaious, and they who preside over the entrance into the rest of eternal life, the rulers Mixanther and Michanor, and they who guard the souls of the elect, Akramas and Strempsouchos, and the great power Heli Heli Machar Machar Seth, and the great invisible','J. M. Robinson et al.',1990,'http://gnosis.org/naghamm/goseqypt.html',NULL,'primary-verbatim',NULL,true,'In-copyright modern translation - brief excerpt for scholarly identification, located by name; verify against the published edition.',DATE '2026-06-25','name-anchored + substring gate against gnosis.org Robinson NHL text; trimmed to clause/sentence boundary',1),
('CIT_SET_ESEPHECH_NHC','ENT_SET_ESEPHECH','SRC_NAG_HAMMADI_SCRIPTURES','The Nag Hammadi Library (Robinson, ed.)','Gospel of the Egyptians, NHC III,2','He gave praise to the great, invisible, incomprehensible, virginal Spirit, and the male virgin, and the thrice-male child, and the male virgin Youel, and Esephech, the holder of glory, the child of the child and the crown of his glory, and the great Doxomedon-aeon, and the thrones which are in him, and the powers which surround him, the glories and the incorruptions, and their whole pleroma which I mentioned before, and the ethereal earth','J. M. Robinson et al.',1990,'http://gnosis.org/naghamm/goseqypt.html',NULL,'primary-verbatim',NULL,true,'In-copyright modern translation - brief excerpt for scholarly identification, located by name; verify against the published edition.',DATE '2026-06-25','name-anchored + substring gate against gnosis.org Robinson NHL text; trimmed to clause/sentence boundary',1),
('CIT_SET_MICHEUS_NHC','ENT_SET_MICHEUS','SRC_NAG_HAMMADI_SCRIPTURES','The Nag Hammadi Library (Robinson, ed.)','Gospel of the Egyptians, NHC III,2','the great and Theopemptos and Isaouel, and they who preside over the spring of truth, Micheus and Michar and Mnesinous, and he who presides over the baptism of the living, and the purifiers, and Sesengenpharanges, and they who preside over the gates of the waters, Micheus and Michar, and they who preside over the mountain, Seldao and Elainos, and the receivers of the great race, the incorruptible, mighty men <of> the great Seth','J. M. Robinson et al.',1990,'http://gnosis.org/naghamm/goseqypt.html',NULL,'primary-verbatim',NULL,true,'In-copyright modern translation - brief excerpt for scholarly identification, located by name; verify against the published edition.',DATE '2026-06-25','name-anchored + substring gate against gnosis.org Robinson NHL text; trimmed to clause/sentence boundary',1),
('CIT_SET_MICHAR_NHC','ENT_SET_MICHAR','SRC_NAG_HAMMADI_SCRIPTURES','The Nag Hammadi Library (Robinson, ed.)','Gospel of the Egyptians, NHC III,2','and Theopemptos and Isaouel, and they who preside over the spring of truth, Micheus and Michar and Mnesinous, and he who presides over the baptism of the living, and the purifiers, and Sesengenpharanges, and they who preside over the gates of the waters, Micheus and Michar, and they who preside over the mountain, Seldao and Elainos, and the receivers of the great race, the incorruptible, mighty men <of> the great Seth, the ministers of the four lights','J. M. Robinson et al.',1990,'http://gnosis.org/naghamm/goseqypt.html',NULL,'primary-verbatim',NULL,true,'In-copyright modern translation - brief excerpt for scholarly identification, located by name; verify against the published edition.',DATE '2026-06-25','name-anchored + substring gate against gnosis.org Robinson NHL text; trimmed to clause/sentence boundary',1),
('CIT_SET_MNESINOUS_NHC','ENT_SET_MNESINOUS','SRC_NAG_HAMMADI_SCRIPTURES','The Nag Hammadi Library (Robinson, ed.)','Gospel of the Egyptians, NHC III,2','and Isaouel, and they who preside over the spring of truth, Micheus and Michar and Mnesinous, and he who presides over the baptism of the living, and the purifiers, and Sesengenpharanges, and they who preside over the gates of the waters, Micheus and Michar, and they who preside over the mountain, Seldao and Elainos, and the receivers of the great race, the incorruptible, mighty men <of> the great Seth, the ministers of the four lights','J. M. Robinson et al.',1990,'http://gnosis.org/naghamm/goseqypt.html',NULL,'primary-verbatim',NULL,true,'In-copyright modern translation - brief excerpt for scholarly identification, located by name; verify against the published edition.',DATE '2026-06-25','name-anchored + substring gate against gnosis.org Robinson NHL text; trimmed to clause/sentence boundary',1),
('CIT_SET_SESENGENPHARANGES_NHC','ENT_SET_SESENGENPHARANGES','SRC_NAG_HAMMADI_SCRIPTURES','The Nag Hammadi Library (Robinson, ed.)','Gospel of the Egyptians, NHC III,2','Mnesinous, and he who presides over the baptism of the living, and the purifiers, and Sesengenpharanges, and they who preside over the gates of the waters, Micheus and Michar, and they who preside over the mountain, Seldao and Elainos, and the receivers of the great race, the incorruptible, mighty men <of> the great Seth, the ministers of the four lights, the great Gamaliel, the great Gabriel, the great Samblo, and the great Abrasax','J. M. Robinson et al.',1990,'http://gnosis.org/naghamm/goseqypt.html',NULL,'primary-verbatim',NULL,true,'In-copyright modern translation - brief excerpt for scholarly identification, located by name; verify against the published edition.',DATE '2026-06-25','name-anchored + substring gate against gnosis.org Robinson NHL text; trimmed to clause/sentence boundary',1),
('CIT_SET_ATHOTH_NHC','ENT_SET_ATHOTH','SRC_NAG_HAMMADI_SCRIPTURES','The Nag Hammadi Library (Robinson, ed.)','Apocryphon of John, NHC II,1','The name of the first one is Athoth, whom the generations call the reaper. The second one is Harmas, who is the eye of envy. The third one is Kalila-Oumbri. The fourth one is Yabel. The fifth one is Adonaiou, who is called Sabaoth. The sixth one is Cain, whom the generations of men call the sun. The seventh is Abel. The eighth is Abrisene. The ninth is Yobel. The tenth is Armoupieel.','J. M. Robinson et al.',1990,'http://gnosis.org/naghamm/apocjn.html',NULL,'primary-verbatim',NULL,true,'In-copyright modern translation - brief excerpt for scholarly identification, located by name; verify against the published edition.',DATE '2026-06-25','name-anchored + substring gate against gnosis.org Robinson NHL text; trimmed to clause/sentence boundary',1),
('CIT_SET_HARMAS_NHC','ENT_SET_HARMAS','SRC_NAG_HAMMADI_SCRIPTURES','The Nag Hammadi Library (Robinson, ed.)','Apocryphon of John, NHC II,1','The second one is Harmas, who is the eye of envy. The third one is Kalila-Oumbri. The fourth one is Yabel. The fifth one is Adonaiou, who is called Sabaoth. The sixth one is Cain, whom the generations of men call the sun. The seventh is Abel. The eighth is Abrisene. The ninth is Yobel. The tenth is Armoupieel. The eleventh is Melceir-Adonein.','J. M. Robinson et al.',1990,'http://gnosis.org/naghamm/apocjn.html',NULL,'primary-verbatim',NULL,true,'In-copyright modern translation - brief excerpt for scholarly identification, located by name; verify against the published edition.',DATE '2026-06-25','name-anchored + substring gate against gnosis.org Robinson NHL text; trimmed to clause/sentence boundary',1),
('CIT_SET_YABEL_NHC','ENT_SET_YABEL','SRC_NAG_HAMMADI_SCRIPTURES','The Nag Hammadi Library (Robinson, ed.)','Apocryphon of John, NHC II,1','The fourth one is Yabel. The fifth one is Adonaiou, who is called Sabaoth. The sixth one is Cain, whom the generations of men call the sun. The seventh is Abel. The eighth is Abrisene. The ninth is Yobel. The tenth is Armoupieel. The eleventh is Melceir-Adonein.','J. M. Robinson et al.',1990,'http://gnosis.org/naghamm/apocjn.html',NULL,'primary-verbatim',NULL,true,'In-copyright modern translation - brief excerpt for scholarly identification, located by name; verify against the published edition.',DATE '2026-06-25','name-anchored + substring gate against gnosis.org Robinson NHL text; trimmed to clause/sentence boundary',1),
('CIT_GNO_DERDEKEAS_NHC','ENT_GNO_DERDEKEAS','SRC_NAG_HAMMADI_SCRIPTURES','The Nag Hammadi Library (Robinson, ed.)','Paraphrase of Shem, NHC VII,1','I am Derdekeas, the son of the incorruptible, infinite Light." The light of the infinite Spirit came down to a feeble nature for a short time until all the impurity of nature became void, and in order that the darkness of Nature might be blamed. I put on my garment which is the garment of the light of the Majesty which I am.','J. M. Robinson et al.',1990,'http://gnosis.org/naghamm/para_shem.html',NULL,'primary-verbatim',NULL,true,'In-copyright modern translation - brief excerpt for scholarly identification, located by name; verify against the published edition.',DATE '2026-06-25','name-anchored + substring gate against gnosis.org Robinson NHL text; trimmed to clause/sentence boundary',1)
ON CONFLICT (citation_id) DO UPDATE SET quote=EXCLUDED.quote, locus=EXCLUDED.locus, source_url=EXCLUDED.source_url, verify_method=EXCLUDED.verify_method;

COMMIT;
