-- scripts/add_roman_indigitamenta.sql
-- Rebalancing pass: Roman indigitamenta (functional minor deities) named by
-- Augustine, City of God (Dods), from Varro. Verbatim, substring-gated. The
-- citations are a hostile-witness attestation (Augustine mocks them) but name and
-- describe each god. No AI prose.

BEGIN;

INSERT INTO entities
  (entity_id, canonical_name, tradition, entity_type, category, primary_domains, cult_scope, primary_period, evidence_confidence, review_status, inclusion_basis, earth_association_score, chthonic_flag, serpent_flag, short_note, entity_class)
VALUES
('ENT_ROM_CLOACINA','Cloacina','Roman','Functional deity','Indigitamentum','Cloacina; indigitamenta; Roman functional deity','Roman','Roman Republic/Empire','A','candidate_verified_name','Augustine City of God primary attestation (from Varro)',1,false,false,'Roman functional minor deity (indigitamentum) presiding over the sewers and drains, named by Augustine from Varro.','deity'),
('ENT_ROM_VATICANUS','Vaticanus','Roman','Functional deity','Indigitamentum','Vaticanus; indigitamenta; Roman functional deity','Roman','Roman Republic/Empire','A','candidate_verified_name','Augustine City of God primary attestation (from Varro)',1,false,false,'Roman functional minor deity (indigitamentum) presiding over the first cry of newborn infants, named by Augustine from Varro.','deity'),
('ENT_ROM_EDUCA','Educa','Roman','Functional deity','Indigitamentum','Educa; indigitamenta; Roman functional deity','Roman','Roman Republic/Empire','A','candidate_verified_name','Augustine City of God primary attestation (from Varro)',1,false,false,'Roman functional minor deity (indigitamentum) presiding over teaching children to eat, named by Augustine from Varro.','deity'),
('ENT_ROM_ABEONA','Abeona','Roman','Functional deity','Indigitamentum','Abeona; indigitamenta; Roman functional deity','Roman','Roman Republic/Empire','A','candidate_verified_name','Augustine City of God primary attestation (from Varro)',1,false,false,'Roman functional minor deity (indigitamentum) presiding over children departing and going away, named by Augustine from Varro.','deity'),
('ENT_ROM_ADEONA','Adeona','Roman','Functional deity','Indigitamentum','Adeona; indigitamenta; Roman functional deity','Roman','Roman Republic/Empire','A','candidate_verified_name','Augustine City of God primary attestation (from Varro)',1,false,false,'Roman functional minor deity (indigitamentum) presiding over children approaching and coming, named by Augustine from Varro.','deity'),
('ENT_ROM_MELLONA','Mellona','Roman','Functional deity','Indigitamentum','Mellona; indigitamenta; Roman functional deity','Roman','Roman Republic/Empire','A','candidate_verified_name','Augustine City of God primary attestation (from Varro)',1,false,false,'Roman functional minor deity (indigitamentum) presiding over bees and honey, named by Augustine from Varro.','deity'),
('ENT_ROM_BUBONA','Bubona','Roman','Functional deity','Indigitamentum','Bubona; indigitamenta; Roman functional deity','Roman','Roman Republic/Empire','A','candidate_verified_name','Augustine City of God primary attestation (from Varro)',1,false,false,'Roman functional minor deity (indigitamentum) presiding over oxen and cattle, named by Augustine from Varro.','deity'),
('ENT_ROM_JUGATINUS','Jugatinus','Roman','Functional deity','Indigitamentum','Jugatinus; indigitamenta; Roman functional deity','Roman','Roman Republic/Empire','A','candidate_verified_name','Augustine City of God primary attestation (from Varro)',1,false,false,'Roman functional minor deity (indigitamentum) presiding over the joining of spouses in marriage, named by Augustine from Varro.','deity'),
('ENT_ROM_DOMIDUCUS','Domiducus','Roman','Functional deity','Indigitamentum','Domiducus; indigitamenta; Roman functional deity','Roman','Roman Republic/Empire','A','candidate_verified_name','Augustine City of God primary attestation (from Varro)',1,false,false,'Roman functional minor deity (indigitamentum) presiding over leading the bride to her home, named by Augustine from Varro.','deity'),
('ENT_ROM_PERTUNDA','Pertunda','Roman','Functional deity','Indigitamentum','Pertunda; indigitamenta; Roman functional deity','Roman','Roman Republic/Empire','A','candidate_verified_name','Augustine City of God primary attestation (from Varro)',1,false,false,'Roman functional minor deity (indigitamentum) presiding over the consummation of marriage, named by Augustine from Varro.','deity'),
('ENT_ROM_MUTUNUS','Mutunus','Roman','Functional deity','Indigitamentum','Mutunus; indigitamenta; Roman functional deity','Roman','Roman Republic/Empire','A','candidate_verified_name','Augustine City of God primary attestation (from Varro)',1,false,false,'Roman functional minor deity (indigitamentum) presiding over marriage and fertility (with Tutunus), named by Augustine from Varro.','deity'),
('ENT_ROM_VOLUPIA','Volupia','Roman','Functional deity','Indigitamentum','Volupia; indigitamenta; Roman functional deity','Roman','Roman Republic/Empire','A','candidate_verified_name','Augustine City of God primary attestation (from Varro)',1,false,false,'Roman functional minor deity (indigitamentum) presiding over pleasure and voluptuousness, named by Augustine from Varro.','deity'),
('ENT_ROM_AGENORIA','Agenoria','Roman','Functional deity','Indigitamentum','Agenoria; indigitamenta; Roman functional deity','Roman','Roman Republic/Empire','A','candidate_verified_name','Augustine City of God primary attestation (from Varro)',1,false,false,'Roman functional minor deity (indigitamentum) presiding over action and industry, named by Augustine from Varro.','deity'),
('ENT_ROM_STIMULA','Stimula','Roman','Functional deity','Indigitamentum','Stimula; indigitamenta; Roman functional deity','Roman','Roman Republic/Empire','A','candidate_verified_name','Augustine City of God primary attestation (from Varro)',1,false,false,'Roman functional minor deity (indigitamentum) presiding over the goad to vigorous action, named by Augustine from Varro.','deity'),
('ENT_ROM_NUMERIA','Numeria','Roman','Functional deity','Indigitamentum','Numeria; indigitamenta; Roman functional deity','Roman','Roman Republic/Empire','A','candidate_verified_name','Augustine City of God primary attestation (from Varro)',1,false,false,'Roman functional minor deity (indigitamentum) presiding over the ability to count and number, named by Augustine from Varro.','deity'),
('ENT_ROM_PELLONIA','Pellonia','Roman','Functional deity','Indigitamentum','Pellonia; indigitamenta; Roman functional deity','Roman','Roman Republic/Empire','A','candidate_verified_name','Augustine City of God primary attestation (from Varro)',1,false,false,'Roman functional minor deity (indigitamentum) presiding over driving away enemies, named by Augustine from Varro.','deity'),
('ENT_ROM_RUNCINA','Runcina','Roman','Functional deity','Indigitamentum','Runcina; indigitamenta; Roman functional deity','Roman','Roman Republic/Empire','A','candidate_verified_name','Augustine City of God primary attestation (from Varro)',1,false,false,'Roman functional minor deity (indigitamentum) presiding over the weeding of crops, named by Augustine from Varro.','deity'),
('ENT_ROM_SPINIENSIS','Spiniensis','Roman','Functional deity','Indigitamentum','Spiniensis; indigitamenta; Roman functional deity','Roman','Roman Republic/Empire','A','candidate_verified_name','Augustine City of God primary attestation (from Varro)',1,false,false,'Roman functional minor deity (indigitamentum) presiding over the clearing of thorns, named by Augustine from Varro.','deity'),
('ENT_ROM_FESSONIA','Fessonia','Roman','Functional deity','Indigitamentum','Fessonia; indigitamenta; Roman functional deity','Roman','Roman Republic/Empire','A','candidate_verified_name','Augustine City of God primary attestation (from Varro)',1,false,false,'Roman functional minor deity (indigitamentum) presiding over relief from weariness, named by Augustine from Varro.','deity')
ON CONFLICT (entity_id) DO NOTHING;

INSERT INTO entity_citations
  (citation_id,entity_id,source_id,work_title,locus,quote,translator,translation_year,source_url,original_text_url,evidence_grade,evidence_note,needs_review,review_reason,verified_on,verify_method,display_order)
VALUES
('CIT_ROM_CLOACINA_AUG','ENT_ROM_CLOACINA','SRC_AUGUSTINE_CITY_OF_GOD','Augustine, City of God','City of God','Now, surely of this work, which is so excellent and so very full of the highest dignity, they dare not ascribe any part to the goddess Cloacina; or to Volupia, who has her appellation from voluptuousness; or to Libentina, who has her name from lust; or to Vaticanus, who presides over the screaming of infants;','Marcus Dods',1871,'https://www.gutenberg.org/ebooks/45304',NULL,'primary-verbatim',NULL,true,'Named by Augustine (from Varro); verify the book/chapter. Hostile-witness attestation.',DATE '2026-06-26','name + substring gate against Dods City of God (Gutenberg #45304)',1),
('CIT_ROM_VATICANUS_AUG','ENT_ROM_VATICANUS','SRC_AUGUSTINE_CITY_OF_GOD','Augustine, City of God','City of God','her appellation from voluptuousness; or to Libentina, who has her name from lust; or to Vaticanus, who presides over the screaming of infants;','Marcus Dods',1871,'https://www.gutenberg.org/ebooks/45304',NULL,'primary-verbatim',NULL,true,'Named by Augustine (from Varro); verify the book/chapter. Hostile-witness attestation.',DATE '2026-06-26','name + substring gate against Dods City of God (Gutenberg #45304)',1),
('CIT_ROM_EDUCA_AUG','ENT_ROM_EDUCA','SRC_AUGUSTINE_CITY_OF_GOD','Augustine, City of God','City of God','the breast _ruma_: in the goddess Potina, let him administer drink: in the goddess Educa, let him supply food: from the terror of infants, let him be styled Paventia: from the hope which comes, Venilia; from voluptuousness, Volupia; from action, Agenor: from the stimulants by which man is spurred on to much action, let him be named the goddess Stimula: let him be the goddess Strenia, for making strenuous; Numeria, who teaches to number;','Marcus Dods',1871,'https://www.gutenberg.org/ebooks/45304',NULL,'primary-verbatim',NULL,true,'Named by Augustine (from Varro); verify the book/chapter. Hostile-witness attestation.',DATE '2026-06-26','name + substring gate against Dods City of God (Gutenberg #45304)',1),
('CIT_ROM_ABEONA_AUG','ENT_ROM_ABEONA','SRC_AUGUSTINE_CITY_OF_GOD','Augustine, City of God','City of God','sucking; to the god Statilinus when standing; to the goddess Adeona when coming; to Abeona when going away; to the goddess Mens that they might have a good mind; to the god Volumnus, and the goddess Volumna, that they might wish for good things; to the nuptial gods, that they might make good matches; to the rural gods, and chiefly to the goddess Fructesca herself, that they might receive the most abundant fruits;','Marcus Dods',1871,'https://www.gutenberg.org/ebooks/45304',NULL,'primary-verbatim',NULL,true,'Named by Augustine (from Varro); verify the book/chapter. Hostile-witness attestation.',DATE '2026-06-26','name + substring gate against Dods City of God (Gutenberg #45304)',1),
('CIT_ROM_ADEONA_AUG','ENT_ROM_ADEONA','SRC_AUGUSTINE_CITY_OF_GOD','Augustine, City of God','City of God','to the goddess Rumina when sucking; to the god Statilinus when standing; to the goddess Adeona when coming; to Abeona when going away; to the goddess Mens that they might have a good mind; to the god Volumnus, and the goddess Volumna, that they might wish for good things; to the nuptial gods, that they might make good matches; to the rural gods, and chiefly to the goddess Fructesca herself, that they might receive the most abundant fruits;','Marcus Dods',1871,'https://www.gutenberg.org/ebooks/45304',NULL,'primary-verbatim',NULL,true,'Named by Augustine (from Varro); verify the book/chapter. Hostile-witness attestation.',DATE '2026-06-26','name + substring gate against Dods City of God (Gutenberg #45304)',1),
('CIT_ROM_MELLONA_AUG','ENT_ROM_MELLONA','SRC_AUGUSTINE_CITY_OF_GOD','Augustine, City of God','City of God','Without Segetia they had harvests; without Bubona, oxen; honey without Mellona; apples without Pomona: and, in a word, everything for which the Romans thought they must supplicate so great a crowd of false gods, they received much more happily from the one true God.','Marcus Dods',1871,'https://www.gutenberg.org/ebooks/45304',NULL,'primary-verbatim',NULL,true,'Named by Augustine (from Varro); verify the book/chapter. Hostile-witness attestation.',DATE '2026-06-26','name + substring gate against Dods City of God (Gutenberg #45304)',1),
('CIT_ROM_BUBONA_AUG','ENT_ROM_BUBONA','SRC_AUGUSTINE_CITY_OF_GOD','Augustine, City of God','City of God','from standing corn, Segetia, not _seges_; from apples, Pomona, not _pomum_; from oxen, Bubona, not _bos_. Sometimes, again, with no alteration of the word, just as the things themselves are named, so that the goddess who gives money is called Pecunia, and money is not thought to be itself a goddess: so of Virtus, who gives virtue; Honor, who gives honour; Concordia, who gives concord;','Marcus Dods',1871,'https://www.gutenberg.org/ebooks/45304',NULL,'primary-verbatim',NULL,true,'Named by Augustine (from Varro); verify the book/chapter. Hostile-witness attestation.',DATE '2026-06-26','name + substring gate against Dods City of God (Gutenberg #45304)',1),
('CIT_ROM_JUGATINUS_AUG','ENT_ROM_JUGATINUS','SRC_AUGUSTINE_CITY_OF_GOD','Augustine, City of God','City of God','or, certainly, not Fortuna, but because he has beards, Fortunius: let him, in the god Jugatinus, yoke couples in marriage;','Marcus Dods',1871,'https://www.gutenberg.org/ebooks/45304',NULL,'primary-verbatim',NULL,true,'Named by Augustine (from Varro); verify the book/chapter. Hostile-witness attestation.',DATE '2026-06-26','name + substring gate against Dods City of God (Gutenberg #45304)',1),
('CIT_ROM_DOMIDUCUS_AUG','ENT_ROM_DOMIDUCUS','SRC_AUGUSTINE_CITY_OF_GOD','Augustine, City of God','City of God','But the married woman must be brought home: the god Domiducus also is invoked. That she may be in the house, the god Domitius is introduced. That she may remain with her husband, the goddess Manturnae is used. What more is required? Let human modesty be spared.','Marcus Dods',1871,'https://www.gutenberg.org/ebooks/45304',NULL,'primary-verbatim',NULL,true,'Named by Augustine (from Varro); verify the book/chapter. Hostile-witness attestation.',DATE '2026-06-26','name + substring gate against Dods City of God (Gutenberg #45304)',1),
('CIT_ROM_PERTUNDA_AUG','ENT_ROM_PERTUNDA','SRC_AUGUSTINE_CITY_OF_GOD','Augustine, City of God','City of God','For there are the goddess Virginiensis, and the god-father Subigus, and the goddess-mother Prema, and the goddess Pertunda, and Venus, and Priapus.','Marcus Dods',1871,'https://www.gutenberg.org/ebooks/45304',NULL,'primary-verbatim',NULL,true,'Named by Augustine (from Varro); verify the book/chapter. Hostile-witness attestation.',DATE '2026-06-26','name + substring gate against Dods City of God (Gutenberg #45304)',1),
('CIT_ROM_MUTUNUS_AUG','ENT_ROM_MUTUNUS','SRC_AUGUSTINE_CITY_OF_GOD','Augustine, City of God','City of God','the virgin wife is loosed, let him be invoked as the goddess Virginiensis: let him be Mutunus or Tuternus, who, among the Greeks, is called Priapus.','Marcus Dods',1871,'https://www.gutenberg.org/ebooks/45304',NULL,'primary-verbatim',NULL,true,'Named by Augustine (from Varro); verify the book/chapter. Hostile-witness attestation.',DATE '2026-06-26','name + substring gate against Dods City of God (Gutenberg #45304)',1),
('CIT_ROM_VOLUPIA_AUG','ENT_ROM_VOLUPIA','SRC_AUGUSTINE_CITY_OF_GOD','Augustine, City of God','City of God','Now, surely of this work, which is so excellent and so very full of the highest dignity, they dare not ascribe any part to the goddess Cloacina; or to Volupia, who has her appellation from voluptuousness; or to Libentina, who has her name from lust; or to Vaticanus, who presides over the screaming of infants;','Marcus Dods',1871,'https://www.gutenberg.org/ebooks/45304',NULL,'primary-verbatim',NULL,true,'Named by Augustine (from Varro); verify the book/chapter. Hostile-witness attestation.',DATE '2026-06-26','name + substring gate against Dods City of God (Gutenberg #45304)',1),
('CIT_ROM_AGENORIA_AUG','ENT_ROM_AGENORIA','SRC_AUGUSTINE_CITY_OF_GOD','Augustine, City of God','City of God','things, and (well nigh) all movements of the mind; that while they invoked the goddess Agenoria, who should excite to action; the goddess Stimula, who should stimulate to unusual action; the goddess Murcia, who should not move men beyond measure, but make them, as Pomponius says, _murcid_--that is, too slothful and inactive; the goddess Strenua, who should make them strenuous;','Marcus Dods',1871,'https://www.gutenberg.org/ebooks/45304',NULL,'primary-verbatim',NULL,true,'Named by Augustine (from Varro); verify the book/chapter. Hostile-witness attestation.',DATE '2026-06-26','name + substring gate against Dods City of God (Gutenberg #45304)',1),
('CIT_ROM_STIMULA_AUG','ENT_ROM_STIMULA','SRC_AUGUSTINE_CITY_OF_GOD','Augustine, City of God','City of God','that while they invoked the goddess Agenoria, who should excite to action; the goddess Stimula, who should stimulate to unusual action; the goddess Murcia, who should not move men beyond measure, but make them, as Pomponius says, _murcid_--that is, too slothful and inactive; the goddess Strenua, who should make them strenuous;','Marcus Dods',1871,'https://www.gutenberg.org/ebooks/45304',NULL,'primary-verbatim',NULL,true,'Named by Augustine (from Varro); verify the book/chapter. Hostile-witness attestation.',DATE '2026-06-26','name + substring gate against Dods City of God (Gutenberg #45304)',1),
('CIT_ROM_NUMERIA_AUG','ENT_ROM_NUMERIA','SRC_AUGUSTINE_CITY_OF_GOD','Augustine, City of God','City of God','him be named the goddess Stimula: let him be the goddess Strenia, for making strenuous; Numeria, who teaches to number;','Marcus Dods',1871,'https://www.gutenberg.org/ebooks/45304',NULL,'primary-verbatim',NULL,true,'Named by Augustine (from Varro); verify the book/chapter. Hostile-witness attestation.',DATE '2026-06-26','name + substring gate against Dods City of God (Gutenberg #45304)',1),
('CIT_ROM_PELLONIA_AUG','ENT_ROM_PELLONIA','SRC_AUGUSTINE_CITY_OF_GOD','Augustine, City of God','City of God','For why should they invoke the goddess Fessonia for the weary; for driving away enemies, the goddess Pellonia; for the sick, as a physician, either Apollo or Aesculapius, or both together if there should be great danger? Neither should the god Spiniensis be entreated that he might root out the thorns from the fields;','Marcus Dods',1871,'https://www.gutenberg.org/ebooks/45304',NULL,'primary-verbatim',NULL,true,'Named by Augustine (from Varro); verify the book/chapter. Hostile-witness attestation.',DATE '2026-06-26','name + substring gate against Dods City of God (Gutenberg #45304)',1),
('CIT_ROM_RUNCINA_AUG','ENT_ROM_RUNCINA','SRC_AUGUSTINE_CITY_OF_GOD','Augustine, City of God','City of God','Matuta; when the crop was runcated,--that is, removed from the soil,--to the goddess Runcina. Nor do I yet recount them all, for I am sick of all this, though it gives them no shame.','Marcus Dods',1871,'https://www.gutenberg.org/ebooks/45304',NULL,'primary-verbatim',NULL,true,'Named by Augustine (from Varro); verify the book/chapter. Hostile-witness attestation.',DATE '2026-06-26','name + substring gate against Dods City of God (Gutenberg #45304)',1),
('CIT_ROM_SPINIENSIS_AUG','ENT_ROM_SPINIENSIS','SRC_AUGUSTINE_CITY_OF_GOD','Augustine, City of God','City of God','Aesculapius, or both together if there should be great danger? Neither should the god Spiniensis be entreated that he might root out the thorns from the fields;','Marcus Dods',1871,'https://www.gutenberg.org/ebooks/45304',NULL,'primary-verbatim',NULL,true,'Named by Augustine (from Varro); verify the book/chapter. Hostile-witness attestation.',DATE '2026-06-26','name + substring gate against Dods City of God (Gutenberg #45304)',1),
('CIT_ROM_FESSONIA_AUG','ENT_ROM_FESSONIA','SRC_AUGUSTINE_CITY_OF_GOD','Augustine, City of God','City of God','For why should they invoke the goddess Fessonia for the weary; for driving away enemies, the goddess Pellonia; for the sick, as a physician, either Apollo or Aesculapius, or both together if there should be great danger? Neither should the god Spiniensis be entreated that he might root out the thorns from the fields;','Marcus Dods',1871,'https://www.gutenberg.org/ebooks/45304',NULL,'primary-verbatim',NULL,true,'Named by Augustine (from Varro); verify the book/chapter. Hostile-witness attestation.',DATE '2026-06-26','name + substring gate against Dods City of God (Gutenberg #45304)',1)
ON CONFLICT (citation_id) DO UPDATE SET quote=EXCLUDED.quote;

COMMIT;
