-- scripts/add_norse_jotnar_aesir.sql
-- Named jotnar (giants) + missing Aesir from the Eddas. Verbatim, substring-gated.

BEGIN;

INSERT INTO entities
  (entity_id, canonical_name, tradition, entity_type, category, primary_domains, cult_scope, primary_period, evidence_confidence, review_status, inclusion_basis, earth_association_score, chthonic_flag, serpent_flag, short_note, entity_class)
VALUES
('ENT_NOR_VAFTHRUDNIR','Vafthrudnir','Germanic/Norse','Giant (Jotun)','Giant','jotun; wisdom','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Vafthrudnismal)',1,false,false,'The all-wise giant who contends in lore with Odin in Vafthrudnismal.','spirit'),
('ENT_NOR_BERGELMIR','Bergelmir','Germanic/Norse','Giant (Jotun)','Giant','jotun; primeval','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Vafthrudnismal 35)',1,false,false,'Primeval frost-giant who alone survived the flood of Ymir blood (Vafthrudnismal 35).','spirit'),
('ENT_NOR_GYMIR','Gymir','Germanic/Norse','Giant (Jotun)','Giant','jotun; father of Gerd','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Skirnismal)',1,false,false,'Frost-giant, father of Gerd, whom Freyr wooed (Skirnismal).','spirit'),
('ENT_NOR_BAUGI','Baugi','Germanic/Norse','Giant (Jotun)','Giant','jotun; the mead of poetry','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Havamal)',1,false,false,'Giant, brother of Suttung, in whose service Odin won the mead of poetry (Havamal).','spirit'),
('ENT_NOR_HRAESVELG','Hraesvelg','Germanic/Norse','Giant (Jotun)','Giant','jotun; wind; eagle','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Vafthrudnismal 37)',1,false,false,'Giant in eagle form at the edge of heaven from whose wings the winds arise (Vafthrudnismal 37).','spirit'),
('ENT_NOR_FORNJOT','Fornjot','Germanic/Norse','Giant (Jotun)','Giant','jotun; primeval','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Prose Edda)',1,false,false,'Primeval giant, ancestor of the personified sea, fire and wind.','spirit'),
('ENT_NOR_HOENIR','Hoenir','Germanic/Norse','God (As)','High Deity','Aesir; sense/spirit','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Voluspa)',1,false,false,'One of the three gods (with Odin and Lodur) who gave the first humans soul/sense (Voluspa).','deity'),
('ENT_NOR_LODUR','Lodur','Germanic/Norse','God (As)','High Deity','Aesir; blood/colour','Germanic/Norse','13th c. (recorded)','A','candidate_verified_name','Primary attestation (Voluspa)',1,false,false,'One of the three gods (with Odin and Hoenir) who gave the first humans blood and colour (Voluspa).','deity')
ON CONFLICT (entity_id) DO NOTHING;

INSERT INTO entity_citations
  (citation_id,entity_id,source_id,work_title,locus,quote,translator,translation_year,source_url,original_text_url,evidence_grade,evidence_note,needs_review,review_reason,verified_on,verify_method,display_order)
VALUES
('CIT_NOR_VAFTHRUDNIR_EDDA','ENT_NOR_VAFTHRUDNIR','SRC_POETIC_EDDA','The Poetic Edda','Vafthrudnismal','Odin visits the Giant (Jotun) Vafthrudnir, for the purpose of proving his knowledge.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Named in the Edda; verify.',DATE '2026-06-26','name + substring gate against the cited Edda',1),
('CIT_NOR_BERGELMIR_EDDA','ENT_NOR_BERGELMIR','SRC_POETIC_EDDA','The Poetic Edda','Vafthrudnismal 35','He is called by the giants Bergelmir. He escaped by going on board his bark, and with him went his wife, and from them are descended the Frost-giants." 8.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Named in the Edda; verify.',DATE '2026-06-26','name + substring gate against the cited Edda',1),
('CIT_NOR_GYMIR_EDDA','ENT_NOR_GYMIR','SRC_POETIC_EDDA','The Poetic Edda','Skirnismal','In Gymir''s courts I saw walking a maid for whom I long. Her arms gave forth light wherewith shone all air and water. 7.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Named in the Edda; verify.',DATE '2026-06-26','name + substring gate against the cited Edda',1),
('CIT_NOR_BAUGI_EDDA','ENT_NOR_BAUGI','SRC_POETIC_EDDA','The Poetic Edda','Havamal','Odin took up his night''s lodging at the house of Suttung''s brother, Baugi, who told him that he was sadly at a loss for labourers, his nine thralls having slain each other.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Named in the Edda; verify.',DATE '2026-06-26','name + substring gate against the cited Edda',1),
('CIT_NOR_HRAESVELG_EDDA','ENT_NOR_HRAESVELG','SRC_POETIC_EDDA','The Poetic Edda','Vafthrudnismal 37','Hraesvelg he is called, who at the end of heaven sits, a Jotun in an eagle''s plumage: from his wings comes, it is said, the wind, that over all men passes. _Gagnrad_. 38.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Named in the Edda; verify.',DATE '2026-06-26','name + substring gate against the cited Edda',1),
('CIT_NOR_FORNJOT_EDDA','ENT_NOR_FORNJOT','SRC_PROSE_EDDA','Snorri Sturluson, Prose Edda','Prose Edda','Thus we have in the prehistoric sagas of Iceland an account of the finding of Norway, wherein it is related that Fornjot,[134] in Jotland, which is also called Finland or Quenland, east of the Gulf of Bothnia, had three sons: Hler, also called Æger, Loge and Kare.[135] Of Loge it is relate','Rasmus B. Anderson',1880,'https://www.gutenberg.org/ebooks/18947',NULL,'primary-verbatim',NULL,true,'Named in the Edda; verify.',DATE '2026-06-26','name + substring gate against the cited Edda',1),
('CIT_NOR_HOENIR_EDDA','ENT_NOR_HOENIR','SRC_POETIC_EDDA','The Poetic Edda','Voluspa','Spirit gave Odin, sense gave Hoenir, blood gave Lodur, and goodly colour. 19.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Named in the Edda; verify.',DATE '2026-06-26','name + substring gate against the cited Edda',1),
('CIT_NOR_LODUR_EDDA','ENT_NOR_LODUR','SRC_POETIC_EDDA','The Poetic Edda','Voluspa','Spirit gave Odin, sense gave Hoenir, blood gave Lodur, and goodly colour. 19.','Benjamin Thorpe',1866,'https://www.gutenberg.org/ebooks/14726',NULL,'primary-verbatim',NULL,true,'Named in the Edda; verify.',DATE '2026-06-26','name + substring gate against the cited Edda',1)
ON CONFLICT (citation_id) DO UPDATE SET quote=EXCLUDED.quote;

COMMIT;
