-- scripts/add_greek_period_assignments.sql
-- Bulk Greek period assignments: 451 unperiodized entities → PER_GRK_ARCHAIC baseline,
-- with PER_GRK_CLASSICAL added for tragedy/philosophical figures and
-- PER_GRK_HELLENISTIC for the handful of genuinely later entities.
-- Strategy: first attested in Homer (c. 750 BCE) or Hesiod (c. 700 BCE) = Archaic.
-- ON CONFLICT DO NOTHING skips the 35 already-assigned Olympians.

BEGIN;

-- ── 1. Remaining Olympian ────────────────────────────────────────────────────
INSERT INTO entity_periods (entity_id, period_id, confidence, rationale, source_id, review_status) VALUES
('ENT_HESTIA','PER_GRK_ARCHAIC','high','Olympian hearth goddess; named in Hesiod Theogony 454 and Homeric Hymn 24','SRC_HESIOD_THEOGONY','reviewed')
ON CONFLICT DO NOTHING;

-- ── 2. Protogenoi / Primordials (29) ─────────────────────────────────────────
INSERT INTO entity_periods (entity_id, period_id, confidence, rationale, source_id, review_status) VALUES
('ENT_AETHER','PER_GRK_ARCHAIC','high','Primordial; Hesiod Theogony 124','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ANANKE','PER_GRK_ARCHAIC','high','Primordial Necessity; Orphic tradition; first systematic attestation Archaic','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_CHAOS','PER_GRK_ARCHAIC','high','First principle; Hesiod Theogony 116','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_CHRONOS','PER_GRK_ARCHAIC','high','Primordial time; Orphic Archaic tradition; distinct from Kronos','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_EOS','PER_GRK_ARCHAIC','high','Dawn goddess; Hesiod Theogony 371; Homer Iliad','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_EOSPHORUS','PER_GRK_ARCHAIC','high','Morning star; Hesiod Theogony 381','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_EREBUS','PER_GRK_ARCHAIC','high','Primordial darkness; Hesiod Theogony 123','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_EROS_PRIMORDIAL','PER_GRK_ARCHAIC','high','Primordial Eros; Hesiod Theogony 120; distinct from later winged Eros','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_EURYNOME_PRIMORDIAL','PER_GRK_ARCHAIC','high','Primordial sea goddess; Hesiod Theogony 907','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_GAIA','PER_GRK_ARCHAIC','high','Earth; Hesiod Theogony 117; Homer Iliad 3.104','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_HELIOS','PER_GRK_ARCHAIC','high','Sun god; Hesiod Theogony 371; Homer Odyssey','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_HEMERA','PER_GRK_ARCHAIC','high','Day; Hesiod Theogony 124','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_HESPERUS','PER_GRK_ARCHAIC','high','Evening star; Hesiod Theogony 381','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_HYDROS','PER_GRK_ARCHAIC','high','Primordial water; Orphic Rhapsodies; Archaic tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_KER','PER_GRK_ARCHAIC','high','Death spirit; Hesiod Theogony 211; Homer Iliad 12.326','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_MOIRAI','PER_GRK_ARCHAIC','high','Fates collective; Hesiod Theogony 217; Homer Iliad','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_MOROS','PER_GRK_ARCHAIC','high','Doom; Hesiod Theogony 211','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_NESOI','PER_GRK_ARCHAIC','high','Island spirits; Hesiod Theogony 130','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_NYX','PER_GRK_ARCHAIC','high','Night; Hesiod Theogony 123; Homer Iliad 14.259','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_OPHION','PER_GRK_ARCHAIC','high','Primordial serpent; Archaic Orphic/Pelasgian tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_OUREA','PER_GRK_ARCHAIC','high','Mountain spirits; Hesiod Theogony 129','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PHANES','PER_GRK_ARCHAIC','high','Orphic primordial; Archaic Orphic Rhapsodies tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PHYSIS','PER_GRK_ARCHAIC','high','Primordial nature; philosophical/Archaic tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PONTUS','PER_GRK_ARCHAIC','high','Primordial sea; Hesiod Theogony 132','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_SELENE','PER_GRK_ARCHAIC','high','Moon goddess; Hesiod Theogony 371; Homeric Hymn 32','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_TARTARUS','PER_GRK_ARCHAIC','high','Primordial abyss; Hesiod Theogony 119','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_THALASSA','PER_GRK_ARCHAIC','high','Sea; Hesiod Theogony 233','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_THESIS','PER_GRK_ARCHAIC','high','Primordial creation; Orphic tradition; Archaic','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_URANUS','PER_GRK_ARCHAIC','high','Sky primordial; Hesiod Theogony 126','SRC_HESIOD_THEOGONY','reviewed')
ON CONFLICT DO NOTHING;

-- ── 3. Titans and Titanesses (24) ────────────────────────────────────────────
INSERT INTO entity_periods (entity_id, period_id, confidence, rationale, source_id, review_status) VALUES
('ENT_ASTERIA','PER_GRK_ARCHAIC','high','Titan; Hesiod Theogony 409','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ASTRAEUS','PER_GRK_ARCHAIC','high','Titan; Hesiod Theogony 376','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ATLAS','PER_GRK_ARCHAIC','high','Titan; Hesiod Theogony 507; Homer Odyssey 1.52','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_CLYMENE_TITANESS','PER_GRK_ARCHAIC','high','Titaness/Oceanid; Hesiod Theogony 351 (as Oceanid); mother of Prometheus in some traditions','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_COEUS','PER_GRK_ARCHAIC','high','Titan; Hesiod Theogony 134','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_CRIUS','PER_GRK_ARCHAIC','high','Titan; Hesiod Theogony 134','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_CRONUS','PER_GRK_ARCHAIC','high','Titan stub; Hesiod Theogony 137','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_DIONE','PER_GRK_ARCHAIC','high','Titaness/Oceanid; Hesiod Theogony 353; Homer Iliad 5.370 (mother of Aphrodite in Homeric tradition)','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_EPIMETHEUS','PER_GRK_ARCHAIC','high','Titan; Hesiod Works and Days 85; Theogony 511','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_EURYBIA','PER_GRK_ARCHAIC','high','Titaness; Hesiod Theogony 239','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_HYPERION','PER_GRK_ARCHAIC','high','Titan; Hesiod Theogony 134; Homer Iliad 8.480','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_IAPETUS','PER_GRK_ARCHAIC','high','Titan; Hesiod Theogony 134; Homer Iliad 8.479','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_LETO','PER_GRK_ARCHAIC','high','Titaness; Hesiod Theogony 406; Homer Iliad 1.9; Homeric Hymn 3','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_MENOETIUS','PER_GRK_ARCHAIC','high','Titan; Hesiod Theogony 510','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_MNEMOSYNE','PER_GRK_ARCHAIC','high','Titaness of memory; Hesiod Theogony 135; mother of the Muses','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_OCEANUS','PER_GRK_ARCHAIC','high','Titan; Hesiod Theogony 133; Homer Iliad 14.201','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PALLAS_TITAN','PER_GRK_ARCHAIC','high','Titan; Hesiod Theogony 376','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PERSES_TITAN','PER_GRK_ARCHAIC','high','Titan; Hesiod Theogony 377','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PHOEBE','PER_GRK_ARCHAIC','high','Titaness; Hesiod Theogony 136','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PROMETHEUS','PER_GRK_ARCHAIC','high','Titan; Hesiod Theogony 510; Works and Days 47-105','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_RHEA','PER_GRK_ARCHAIC','high','Titaness; Hesiod Theogony 135; Homer Iliad 15.187','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_TETHYS','PER_GRK_ARCHAIC','high','Titaness; Hesiod Theogony 136; Homer Iliad 14.201','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_THEIA','PER_GRK_ARCHAIC','high','Titaness; Hesiod Theogony 135','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_THEMIS','PER_GRK_ARCHAIC','high','Titaness of law; Hesiod Theogony 135; Homer Iliad 15.87','SRC_HESIOD_THEOGONY','reviewed')
ON CONFLICT DO NOTHING;

-- ── 4. Daimones / Personifications (71) — all Archaic ────────────────────────
INSERT INTO entity_periods (entity_id, period_id, confidence, rationale, source_id, review_status) VALUES
('ENT_ADIKIA','PER_GRK_ARCHAIC','high','Injustice; Archaic personification tradition (Hesiod, Theognis)','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_AIDOS','PER_GRK_ARCHAIC','high','Shame/reverence; Hesiod Works and Days 197-201','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ALALA','PER_GRK_ARCHAIC','high','War cry spirit; Archaic; attested Pindar','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ALASTOR','PER_GRK_ARCHAIC','high','Avenger spirit; Archaic poetic tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ALGEA','PER_GRK_ARCHAIC','high','Pains; Hesiod Theogony 227','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ALKE','PER_GRK_ARCHAIC','high','Strength spirit; Archaic tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_AMECHANIA','PER_GRK_ARCHAIC','high','Helplessness; Archaic personification','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_AMPHILOGIAI','PER_GRK_ARCHAIC','high','Disputes; Hesiod Theogony 229','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_APATE','PER_GRK_ARCHAIC','high','Deceit; Hesiod Theogony 224','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ARETE','PER_GRK_ARCHAIC','high','Excellence/virtue; Hesiod Works and Days 289; Prodicus via Xenophon','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_AT','PER_GRK_ARCHAIC','high','Ruin/delusion stub; Hesiod Theogony 230','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ATE','PER_GRK_ARCHAIC','high','Ruin/delusion; Hesiod Theogony 230; Homer Iliad 9.505','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_BASILEIA','PER_GRK_ARCHAIC','high','Sovereignty personification; Archaic tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_BIA','PER_GRK_ARCHAIC','high','Force/violence; Hesiod Theogony 385; Aeschylus Prometheus Bound','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_CAERUS','PER_GRK_ARCHAIC','high','Opportunity; attested Archaic; Lysippus sculpture Classical','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_DEIMOS','PER_GRK_ARCHAIC','high','Fear/dread; Hesiod Theogony 934; Homer Iliad 4.440','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_DIKAIOSYNE','PER_GRK_ARCHAIC','high','Justice personification; Archaic tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_DOLOS','PER_GRK_ARCHAIC','high','Trickery; Hesiod Theogony 224','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_DYSNOMIA','PER_GRK_ARCHAIC','high','Lawlessness; Hesiod Works and Days 321; Solon fr. 4','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ELEOS','PER_GRK_ARCHAIC','high','Mercy; Archaic personification; altar at Athens (Pausanias)','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ELEUTHERIA','PER_GRK_ARCHAIC','high','Liberty; Archaic/Classical personification','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ELPIS','PER_GRK_ARCHAIC','high','Hope; Hesiod Works and Days 94-98 — the only ancient source naming her in the jar','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ENYO','PER_GRK_ARCHAIC','high','War goddess; Homer Iliad 5.333','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_EPIPHRON','PER_GRK_ARCHAIC','high','Prudence; Archaic personification','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ERIS','PER_GRK_ARCHAIC','high','Discord; Hesiod Theogony 225; Works and Days 11; Homer Iliad 4.440','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_EROS','PER_GRK_ARCHAIC','high','Love daimon (later winged form); Archaic lyric tradition; Hesiod also names him primordial','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_EUSEBEIA','PER_GRK_ARCHAIC','high','Piety; Archaic personification','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_GERAS','PER_GRK_ARCHAIC','high','Old age; Hesiod Theogony 225','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_HARMONIA','PER_GRK_ARCHAIC','high','Harmony; Hesiod Theogony 937; daughter of Ares and Aphrodite','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_HEDONE','PER_GRK_ARCHAIC','high','Pleasure; Archaic tradition; Prodicus allegory','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_HIMEROS','PER_GRK_ARCHAIC','high','Longing; Hesiod Theogony 64; attends Aphrodite','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_HOMADOS','PER_GRK_ARCHAIC','high','Battle noise; Homer Iliad 4.449','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_HOMONOIA','PER_GRK_ARCHAIC','high','Concord; Archaic personification','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_HORKOS','PER_GRK_ARCHAIC','high','Oath; Hesiod Theogony 231; Works and Days 803','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_HYBRIS','PER_GRK_ARCHAIC','high','Hubris; Hesiod Works and Days; Theognis; central Archaic concept','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_HYSMINAI','PER_GRK_ARCHAIC','high','Battles; Hesiod Theogony 228','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_IOKE','PER_GRK_ARCHAIC','high','Pursuit in battle; Archaic/Homeric tradition','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_KAIROS','PER_GRK_ARCHAIC','high','Right moment; Archaic concept (Hesiod Works and Days); personified Classical','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_KAKIA','PER_GRK_ARCHAIC','high','Vice; Hesiod Works and Days 287 (Kakotes); Prodicus allegory','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_KRATOS','PER_GRK_ARCHAIC','high','Strength/power; Hesiod Theogony 385; Aeschylus Prometheus Bound','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_KYDOIMOS','PER_GRK_ARCHAIC','high','Confusion of battle; Homer Iliad 5.593','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_LIMOS','PER_GRK_ARCHAIC','high','Famine; Hesiod Theogony 227; Works and Days 299','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_LITAE','PER_GRK_ARCHAIC','high','Prayers; Homer Iliad 9.502-512','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_LYSSA','PER_GRK_ARCHAIC','high','Rage/madness; Homer Iliad 9.239; Aeschylus','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_MACHAI','PER_GRK_ARCHAIC','high','Battles; Hesiod Theogony 228','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_MANIA','PER_GRK_ARCHAIC','high','Madness; Archaic tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_MOMOS','PER_GRK_ARCHAIC','high','Blame/mockery; Hesiod Theogony 214','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_MOMUS','PER_GRK_ARCHAIC','high','Blame/mockery variant spelling; Hesiod Theogony 214','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_NEIKEA','PER_GRK_ARCHAIC','high','Quarrels; Hesiod Theogony 229','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_NOMOS','PER_GRK_ARCHAIC','high','Law; Archaic personification; Pindar fr. 169','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_OIZYS','PER_GRK_ARCHAIC','high','Misery; Hesiod Theogony 214','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PALIOXIS','PER_GRK_ARCHAIC','high','Retreat in battle; Homer Iliad 5.740','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_PEITHO','PER_GRK_ARCHAIC','high','Persuasion; Hesiod Theogony 349; Sappho fr. 1','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PENIA','PER_GRK_ARCHAIC','high','Poverty; Hesiod Works and Days; Aristophanes Plutus (Classical)','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PHEME','PER_GRK_ARCHAIC','high','Rumor/fame; Hesiod Works and Days 763; Homer Odyssey','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PHILOTES','PER_GRK_ARCHAIC','high','Friendship/affection; Hesiod Theogony 224','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PHOBOS','PER_GRK_ARCHAIC','high','Fear/panic; Hesiod Theogony 934; Homer Iliad 4.440','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_POINE','PER_GRK_ARCHAIC','high','Retribution; Archaic tradition; Pindar Olympian 2','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PONOS','PER_GRK_ARCHAIC','high','Toil; Hesiod Theogony 226','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_POROS','PER_GRK_ARCHAIC','high','Expediency; Archaic tradition; Plato Symposium (Classical philosophical treatment)','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_POTHOS','PER_GRK_ARCHAIC','high','Longing/yearning; attends Aphrodite; Hesiod Theogony 201; lyric tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PRAXIS','PER_GRK_ARCHAIC','high','Action; Archaic personification','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PROIOXIS','PER_GRK_ARCHAIC','high','Onslaught in battle; Homer Iliad 5.740','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_PSEUDOLOGOI','PER_GRK_ARCHAIC','high','Lies; Hesiod Theogony 229','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_SOPHROSYNE','PER_GRK_ARCHAIC','high','Self-control; Archaic concept (Theognis, Pindar); personified Classical','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_SOTER','PER_GRK_ARCHAIC','high','Savior epithet/personification; Archaic libation tradition (Pindar)','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_SOTERIA','PER_GRK_ARCHAIC','high','Safety personification; Archaic tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_TECHNE','PER_GRK_ARCHAIC','high','Craft/art; Archaic personification tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_THRASOS','PER_GRK_ARCHAIC','high','Boldness; Archaic tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_TYCHON','PER_GRK_ARCHAIC','high','Fortune daimon; Archaic apotropaic tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ZELOS','PER_GRK_ARCHAIC','high','Zeal/rivalry; Hesiod Theogony 384','SRC_HESIOD_THEOGONY','reviewed')
ON CONFLICT DO NOTHING;

-- ── 5. Heroes (39) — Archaic baseline ────────────────────────────────────────
INSERT INTO entity_periods (entity_id, period_id, confidence, rationale, source_id, review_status) VALUES
('ENT_ACHILLES','PER_GRK_ARCHAIC','high','Central hero of the Iliad; Homer Iliad (c. 750 BCE)','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_ADONIS_HERO','PER_GRK_ARCHAIC','high','Vegetation hero; Sappho fr. 140 (Archaic) is earliest Greek attestation','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_AEACUS_HERO','PER_GRK_ARCHAIC','high','Hero/underworld judge; Hesiod; Pindar','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_AENEAS_GREEK_RECEPTION','PER_GRK_ARCHAIC','high','Trojan hero; Homer Iliad 2.820; Hesiod Theogony 1008','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_AJAX','PER_GRK_ARCHAIC','high','Hero of the Iliad; Homer Iliad (c. 750 BCE)','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_ARISTAEUS_HERO','PER_GRK_ARCHAIC','high','Pastoral deity/hero; Hesiod Theogony 977; Pindar Pythian 9','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ASCLEPIUS_HERO','PER_GRK_ARCHAIC','high','Healing hero; Homer Iliad 2.731 (sons mentioned); Hesiod Catalogue','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_ATALANTA','PER_GRK_ARCHAIC','high','Huntress heroine; Hesiod Catalogue of Women; Archaic myth','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_BELLEROPHON','PER_GRK_ARCHAIC','high','Hero; Homer Iliad 6.155-203','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_CADMUS','PER_GRK_ARCHAIC','high','Culture hero/founder of Thebes; Hesiod Theogony 937; Homeric tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_CASTOR','PER_GRK_ARCHAIC','high','Dioscurus; Homer Iliad 3.237','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_CECROPS','PER_GRK_ARCHAIC','high','First king of Athens; Archaic Attic tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_DIOMEDES','PER_GRK_ARCHAIC','high','Hero of the Iliad; Homer Iliad 5 (aristeia)','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_ERECHTHEUS','PER_GRK_ARCHAIC','high','Athenian king/hero; Homer Iliad 2.547; Odyssey 7.81','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_HECTOR','PER_GRK_ARCHAIC','high','Trojan hero; Homer Iliad','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_HELEN','PER_GRK_ARCHAIC','high','Helen of Troy; Homer Iliad 3','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_HERACLES','PER_GRK_ARCHAIC','high','Greatest Greek hero; Homer Iliad 5.638; Odyssey 11.601; Hesiod Theogony 951','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_HIPPOLYTUS','PER_GRK_ARCHAIC','high','Artemis hero/cult figure; Archaic tradition; Troezen cult','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_HYACINTHUS','PER_GRK_ARCHAIC','high','Apollo hero/cult figure; Archaic Spartan cult (Hyakinthia festival)','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_ION','PER_GRK_ARCHAIC','high','Ancestor of Ionians; Archaic genealogical tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_IPHIGENIA','PER_GRK_ARCHAIC','high','Sacrificed princess; Archaic tradition; Hesiod Catalogue of Women','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_JASON','PER_GRK_ARCHAIC','high','Argonaut leader; Hesiod Theogony 993; Pindar Pythian 4 (Archaic)','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_MEDEA','PER_GRK_ARCHAIC','high','Sorceress heroine; Hesiod Theogony 992; Archaic epic tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_MELEAGER','PER_GRK_ARCHAIC','high','Calydonian hunter; Homer Iliad 9.527-599','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_MEMNON','PER_GRK_ARCHAIC','high','Ethiopian hero; Homer Odyssey 4.188; Aethiopis (lost Archaic epic)','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_MENELAUS','PER_GRK_ARCHAIC','high','Spartan king/hero; Homer Iliad; Odyssey','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_MINOS_HERO','PER_GRK_ARCHAIC','high','Cretan king/underworld judge; Homer Odyssey 11.568','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_MOPSUS','PER_GRK_ARCHAIC','high','Seer-hero; Archaic tradition; attested in Hesiod Catalogue','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ODYSSEUS','PER_GRK_ARCHAIC','high','Hero of the Odyssey; Homer Iliad and Odyssey','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_OENOMAUS','PER_GRK_ARCHAIC','high','King of Pisa; Archaic tradition; Pindar Olympian 1','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_ORESTES','PER_GRK_ARCHAIC','high','Son of Agamemnon; Homer Odyssey 1.30, 3.306; Archaic tradition','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_ORPHEUS','PER_GRK_ARCHAIC','high','Mythic singer; Archaic tradition; Ibycus, Simonides (6th c. BCE)','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_PELOPS','PER_GRK_ARCHAIC','high','Olympian founder hero; Pindar Olympian 1 (Archaic)','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_PERSEUS','PER_GRK_ARCHAIC','high','Gorgon-slayer; Hesiod Theogony 280; Homeric tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_POLYDEUCES','PER_GRK_ARCHAIC','high','Dioscurus; Homer Iliad 3.237','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_PROTESILAUS','PER_GRK_ARCHAIC','high','First Greek killed at Troy; Homer Iliad 2.698','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_PYLADES','PER_GRK_ARCHAIC','high','Companion of Orestes; Archaic tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_RHADAMANTHYS_HERO','PER_GRK_ARCHAIC','high','Hero/judge; Homer Odyssey 4.564','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_THESEUS','PER_GRK_ARCHAIC','high','Athenian hero; Homer Iliad 1.265; Odyssey 11.322; Archaic Attic tradition','SRC_HOMER_ILIAD_ODYSSEY','reviewed')
ON CONFLICT DO NOTHING;

-- ── 6. River gods (39) ───────────────────────────────────────────────────────
INSERT INTO entity_periods (entity_id, period_id, confidence, rationale, source_id, review_status) VALUES
('ENT_ACHELOOS','PER_GRK_ARCHAIC','high','Greatest river god; Homer Iliad 21.194; Hesiod Theogony 340','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_ACHELOUS_MINOR','PER_GRK_ARCHAIC','high','River deity; sons of Oceanus per Hesiod Theogony 338','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ACHERON_RIVER','PER_GRK_ARCHAIC','high','Underworld river; Homer Odyssey 10.513; Hesiod','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_AESAR','PER_GRK_ARCHAIC','medium','River deity; Archaic tradition; son of Oceanus','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_AESEPUS','PER_GRK_ARCHAIC','high','Trojan river; Homer Iliad 2.825; 12.21','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_ALPHEUS','PER_GRK_ARCHAIC','high','River of Olympia; Homer Iliad 2.592; Hesiod Theogony 338','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_ASOPUS','PER_GRK_ARCHAIC','high','Boeotian river; Hesiod; Pindar','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_AXIUS','PER_GRK_ARCHAIC','high','Macedonian river; Homer Iliad 2.849; 16.288','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_CAICUS','PER_GRK_ARCHAIC','high','Mysian river; Archaic; sons of Oceanus tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_CEPHISSUS','PER_GRK_ARCHAIC','high','Attic/Phocian river; Hesiod Theogony 338','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_CLADEUS','PER_GRK_ARCHAIC','high','River at Olympia; Archaic cult tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_CYDNUS','PER_GRK_ARCHAIC','high','Cilician river; Archaic tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ERIDANUS','PER_GRK_ARCHAIC','high','Mythic amber river; Hesiod fr. 150; associated with Phaethon myth','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ERYMANTHUS','PER_GRK_ARCHAIC','high','Arcadian river; Archaic myth (Heracles); sons of Oceanus','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_EUROTAS','PER_GRK_ARCHAIC','high','Spartan river; Archaic Laconian tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_EVENUS','PER_GRK_ARCHAIC','high','Aetolian river; Archaic myth (Meleager/Idas)','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_GRANICUS','PER_GRK_ARCHAIC','high','Mysian river; Archaic tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_HEBRUS','PER_GRK_ARCHAIC','high','Thracian river; Archaic tradition; Orpheus myth','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ILISSUS','PER_GRK_ARCHAIC','high','Attic river; Archaic Athenian tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_INACHUS','PER_GRK_ARCHAIC','high','Argive river; Hesiod Theogony 338; father of Io','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ISMENUS','PER_GRK_ARCHAIC','high','Boeotian river; Homer Iliad 2.508; Hesiod','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_LADON','PER_GRK_ARCHAIC','high','Arcadian river; Hesiod Theogony 344','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_MAEANDER','PER_GRK_ARCHAIC','high','Lydian/Phrygian river; Hesiod Theogony 339','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_MELES','PER_GRK_ARCHAIC','high','River at Smyrna; Archaic tradition (Homer mythically born on its banks)','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_NESSUS','PER_GRK_ARCHAIC','high','Thracian river; Archaic tradition; Heracles myth','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_NILE','PER_GRK_ARCHAIC','high','Egyptian river deity; Hesiod Theogony 338; Homer Odyssey 4.477','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_PARTHENIUS','PER_GRK_ARCHAIC','high','Paphlagonian river; Hesiod Theogony 344','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PENEUS','PER_GRK_ARCHAIC','high','Thessalian river; Hesiod Theogony 343; father of Daphne','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PHASIS','PER_GRK_ARCHAIC','high','Colchian river; Hesiod Theogony 340; Argonaut tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_RHESUS_RIVER','PER_GRK_ARCHAIC','high','Thracian river; Homer Iliad 12.20','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_SANGARIUS','PER_GRK_ARCHAIC','high','Phrygian river; Hesiod Theogony 344; Homer Iliad 3.187','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_SATNIOEIS','PER_GRK_ARCHAIC','high','Trojan river; Homer Iliad 6.34; 14.445','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_SCAMANDER','PER_GRK_ARCHAIC','high','Major Trojan river; Homer Iliad 21 (lengthy divine battle scene)','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_SIMOEIS','PER_GRK_ARCHAIC','high','Trojan river; Homer Iliad 5.774; 12.22','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_SPERCHEIOS','PER_GRK_ARCHAIC','high','Thessalian river; Homer Iliad 23.142-144 (Achilles dedicates hair)','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_STRYMON','PER_GRK_ARCHAIC','high','Thracian river; Hesiod Theogony 339','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_THERMODON','PER_GRK_ARCHAIC','high','Amazon river; Archaic tradition; Hesiod','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_TITARESIUS','PER_GRK_ARCHAIC','high','Thessalian river; Homer Iliad 2.751-754','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_XANTHUS','PER_GRK_ARCHAIC','high','Trojan river (= Scamander); Homer Iliad 21','SRC_HOMER_ILIAD_ODYSSEY','reviewed')
ON CONFLICT DO NOTHING;

-- ── 7. Nymph collectives (19) ────────────────────────────────────────────────
INSERT INTO entity_periods (entity_id, period_id, confidence, rationale, source_id, review_status) VALUES
('ENT_AURAE','PER_GRK_ARCHAIC','high','Breeze nymphs; Archaic tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_CORYCIAN_NYMPHS','PER_GRK_ARCHAIC','high','Delphic nymphs; Archaic Delphic tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_CRENAIAE','PER_GRK_ARCHAIC','high','Spring nymphs; Archaic tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_DRYADS','PER_GRK_ARCHAIC','high','Tree nymphs; Hesiod Theogony 187 (Meliae); Homer Hymn to Aphrodite','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_HAMADRYADS','PER_GRK_ARCHAIC','high','Oak-bound nymphs; Archaic tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_HELEIONOMAI','PER_GRK_ARCHAIC','high','Marsh nymphs; Archaic tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_HESPERIDES','PER_GRK_ARCHAIC','high','Garden nymphs; Hesiod Theogony 215, 518','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_LEIMAKIDES','PER_GRK_ARCHAIC','high','Meadow nymphs; Archaic tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_LIMNADES','PER_GRK_ARCHAIC','high','Lake nymphs; Archaic tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_MELIAE','PER_GRK_ARCHAIC','high','Ash-tree nymphs; Hesiod Theogony 187; Works and Days 145','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_NAIADS','PER_GRK_ARCHAIC','high','Freshwater nymphs; Homer Iliad 20.8; Odyssey 13.104','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_NAPAEAE','PER_GRK_ARCHAIC','high','Dell nymphs; Archaic tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_NEPHELAE','PER_GRK_ARCHAIC','high','Cloud nymphs; Archaic tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_NEREIDS','PER_GRK_ARCHAIC','high','Sea nymph collective; Homer Iliad 18.38-49; Hesiod Theogony 240','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_NYMPHS','PER_GRK_ARCHAIC','high','Nymph category; Homer Iliad 6.420; Odyssey 6.123','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_OCEANIDS','PER_GRK_ARCHAIC','high','Ocean daughters; Hesiod Theogony 346-361','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_OREADS','PER_GRK_ARCHAIC','high','Mountain nymphs; Homer Hymn to Aphrodite 257','SRC_HOMERIC_HYMNS','reviewed'),
('ENT_PEGAEAE','PER_GRK_ARCHAIC','high','Spring nymphs; Archaic tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_POTAMEIDES','PER_GRK_ARCHAIC','high','River nymphs; Archaic tradition','SRC_HESIOD_THEOGONY','reviewed')
ON CONFLICT DO NOTHING;

-- ── 8. Nereids (19) ──────────────────────────────────────────────────────────
INSERT INTO entity_periods (entity_id, period_id, confidence, rationale, source_id, review_status) VALUES
('ENT_ACTAEA','PER_GRK_ARCHAIC','high','Named in Hesiod Theogony 243-264 (50 Nereid catalog)','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_CYMODOCE','PER_GRK_ARCHAIC','high','Named in Hesiod Theogony 252','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_CYMOTHOE','PER_GRK_ARCHAIC','high','Named in Hesiod Theogony 245; Homer Iliad 1.38','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_DOTO','PER_GRK_ARCHAIC','high','Named in Hesiod Theogony 248','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_DYNAMENE','PER_GRK_ARCHAIC','high','Named in Hesiod Theogony 248','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_EUARNE','PER_GRK_ARCHAIC','high','Named in Hesiod Theogony 259','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_EUDORA_NEREID','PER_GRK_ARCHAIC','high','Named in Hesiod Theogony 244','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_GALATEA','PER_GRK_ARCHAIC','high','Nereid; Hesiod Theogony 250; Polyphemus myth Archaic (Homer Odyssey 9)','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_GLAUCE','PER_GRK_ARCHAIC','high','Named in Hesiod Theogony 244','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_HIPPONOE','PER_GRK_ARCHAIC','high','Named in Hesiod Theogony 251','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_MELITE','PER_GRK_ARCHAIC','high','Named in Hesiod Theogony 247','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_NESO','PER_GRK_ARCHAIC','high','Named in Hesiod Theogony 261','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PHERUSA','PER_GRK_ARCHAIC','high','Named in Hesiod Theogony 248','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PROTO','PER_GRK_ARCHAIC','high','Named in Hesiod Theogony 248','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PSAMATHE','PER_GRK_ARCHAIC','high','Named in Hesiod Theogony 260; mother of Phocus by Aeacus','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_SAO','PER_GRK_ARCHAIC','high','Named in Hesiod Theogony 243','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_SPEIO','PER_GRK_ARCHAIC','high','Named in Hesiod Theogony 245','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_THALIA_NEREID','PER_GRK_ARCHAIC','high','Named in Hesiod Theogony 245','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_THETIS','PER_GRK_ARCHAIC','high','Sea goddess/Nereid; Homer Iliad 1.352 (major character)','SRC_HOMER_ILIAD_ODYSSEY','reviewed')
ON CONFLICT DO NOTHING;

-- ── 9. Individual Nymphs (11) ────────────────────────────────────────────────
INSERT INTO entity_periods (entity_id, period_id, confidence, rationale, source_id, review_status) VALUES
('ENT_ADRASTEIA_NYMPH','PER_GRK_ARCHAIC','high','Cretan nymph; nurse of Zeus; Archaic Cretan tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_AEGINA','PER_GRK_ARCHAIC','high','Nymph/river; mother of Aeacus; Hesiod; Pindar Nemean 3','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_CALYPSO','PER_GRK_ARCHAIC','high','Nymph of Ogygia; Homer Odyssey 1.14; 5.57','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_CORYCIA','PER_GRK_ARCHAIC','high','Delphic nymph; Archaic tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_CYRENE','PER_GRK_ARCHAIC','high','Nymph/huntress; Hesiod Catalogue; Pindar Pythian 9','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_DIRCE','PER_GRK_ARCHAIC','high','Theban spring nymph; Archaic Theban tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_IDAIA','PER_GRK_ARCHAIC','high','Mount Ida nymph; Archaic Trojan tradition','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_LEUCE','PER_GRK_ARCHAIC','high','White nymph loved by Hades; Archaic tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_MINTHE','PER_GRK_ARCHAIC','high','Underworld nymph; Archaic tradition; Strabo','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_NEDA','PER_GRK_ARCHAIC','high','Arcadian river nymph; nurse of Zeus; Hesiod','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_SYRINX','PER_GRK_ARCHAIC','high','Naiad loved by Pan; Archaic Arcadian tradition','SRC_APOLLODORUS_LIBRARY','reviewed')
ON CONFLICT DO NOTHING;

-- ── 10. Oceanids (10) ────────────────────────────────────────────────────────
INSERT INTO entity_periods (entity_id, period_id, confidence, rationale, source_id, review_status) VALUES
('ENT_AETHRA_OCEANID','PER_GRK_ARCHAIC','high','Oceanid; Hesiod Theogony 349','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ASIA','PER_GRK_ARCHAIC','high','Oceanid; Hesiod Theogony 359','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_CALLIRRHOE','PER_GRK_ARCHAIC','high','Oceanid; Hesiod Theogony 351','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_CLYMENE_OCEANID','PER_GRK_ARCHAIC','high','Oceanid; Hesiod Theogony 351','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ELECTRA_OCEANID','PER_GRK_ARCHAIC','high','Oceanid; Hesiod Theogony 349','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_EURYNOME_OCEANID','PER_GRK_ARCHAIC','high','Oceanid; Hesiod Theogony 358','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_IDYIA','PER_GRK_ARCHAIC','high','Oceanid; Hesiod Theogony 352; mother of Medea','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PEITHO_OCEANID','PER_GRK_ARCHAIC','high','Oceanid; Hesiod Theogony 349','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PERSEIS','PER_GRK_ARCHAIC','high','Oceanid; Hesiod Theogony 356; mother of Circe and Aeëtes','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PLEIONE','PER_GRK_ARCHAIC','high','Oceanid/mother of Pleiades; Hesiod','SRC_HESIOD_THEOGONY','reviewed')
ON CONFLICT DO NOTHING;

-- ── 11. Muses (9) ────────────────────────────────────────────────────────────
INSERT INTO entity_periods (entity_id, period_id, confidence, rationale, source_id, review_status) VALUES
('ENT_CALLIOPE','PER_GRK_ARCHAIC','high','Chief Muse; Hesiod Theogony 79','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_CLIO','PER_GRK_ARCHAIC','high','Muse; Hesiod Theogony 77','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ERATO','PER_GRK_ARCHAIC','high','Muse; Hesiod Theogony 78','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_EUTERPE','PER_GRK_ARCHAIC','high','Muse; Hesiod Theogony 77','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_MELPOMENE','PER_GRK_ARCHAIC','high','Muse; Hesiod Theogony 77','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_POLYHYMNIA','PER_GRK_ARCHAIC','high','Muse; Hesiod Theogony 78','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_TERPSICHORE','PER_GRK_ARCHAIC','high','Muse; Hesiod Theogony 78','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_THALIA_MUSE','PER_GRK_ARCHAIC','high','Muse; Hesiod Theogony 77','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_URANIA_MUSE','PER_GRK_ARCHAIC','high','Muse; Hesiod Theogony 78','SRC_HESIOD_THEOGONY','reviewed')
ON CONFLICT DO NOTHING;

-- ── 12–20. Remaining clusters (all Archaic baseline) ─────────────────────────
INSERT INTO entity_periods (entity_id, period_id, confidence, rationale, source_id, review_status) VALUES
-- Daimon collectives
('ENT_KORYBANTES','PER_GRK_ARCHAIC','high','Armed dancers attending Cybele; Archaic tradition','SRC_HOMERIC_HYMNS','reviewed'),
('ENT_KOURETES','PER_GRK_ARCHAIC','high','Cretan armed dancers; Hesiod; Homeric Hymn to Zeus','SRC_HOMERIC_HYMNS','reviewed'),
('ENT_MAKHAI','PER_GRK_ARCHAIC','high','Battle spirits; Hesiod Theogony 228','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_NOSOI','PER_GRK_ARCHAIC','high','Disease spirits; Hesiod Works and Days 102','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ONEIROI','PER_GRK_ARCHAIC','high','Dream spirits; Homer Odyssey 24.12; Hesiod Theogony 212','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_POINAI','PER_GRK_ARCHAIC','high','Retribution spirits; Archaic tradition; Pindar','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_SATYRS','PER_GRK_ARCHAIC','high','Rustic daimon collective; Hesiod Catalogue; Homeric Hymn to Aphrodite 262','SRC_HESIOD_THEOGONY','reviewed'),
-- Goddess/daimon
('ENT_DIKE','PER_GRK_ARCHAIC','high','Justice; Hesiod Works and Days 256; Theogony 902','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_EIRENE','PER_GRK_ARCHAIC','high','Peace; Hesiod Theogony 902','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_EUNOMIA','PER_GRK_ARCHAIC','high','Order/law; Hesiod Theogony 902; Solon fr. 4','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_NEMESIS','PER_GRK_ARCHAIC','high','Retribution; Hesiod Theogony 223; Works and Days 197','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_NIKE','PER_GRK_ARCHAIC','high','Victory; Hesiod Theogony 384','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_TYCHE','PER_GRK_ARCHAIC','high','Fortune; Hesiod Theogony 360; Archaic lyric (Pindar Olympian 12)','SRC_HESIOD_THEOGONY','reviewed'),
-- Goddess collectives
('ENT_CHARITES','PER_GRK_ARCHAIC','high','Graces; Hesiod Theogony 907; Homer Iliad 5.338','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ERINYES','PER_GRK_ARCHAIC','high','Furies; Hesiod Theogony 185; Homer Iliad 9.454; 19.87','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_EUMENIDES','PER_GRK_ARCHAIC','high','Euphemistic name for Erinyes; Archaic cult tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_HORAE','PER_GRK_ARCHAIC','high','Seasons; Hesiod Theogony 901; Homer Iliad 5.749','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_MUSES','PER_GRK_ARCHAIC','high','Muse collective; Hesiod Theogony 52-67; Homer Iliad 2.484','SRC_HESIOD_THEOGONY','reviewed'),
-- Sea gods
('ENT_NEREUS','PER_GRK_ARCHAIC','high','Old Man of the Sea; Hesiod Theogony 233; Homer Iliad 18.141','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PHORCYS','PER_GRK_ARCHAIC','high','Sea god; Hesiod Theogony 237; Homer Odyssey 1.72','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PROTEUS','PER_GRK_ARCHAIC','high','Shape-shifting sea god; Homer Odyssey 4.385','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_THAUMAS','PER_GRK_ARCHAIC','high','Sea god; Hesiod Theogony 237','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_TRITON','PER_GRK_ARCHAIC','high','Sea god son of Poseidon; Hesiod Theogony 930','SRC_HESIOD_THEOGONY','reviewed'),
-- Underworld judges
('ENT_AEACUS','PER_GRK_ARCHAIC','high','Underworld judge; Homer Odyssey (implied); Pindar Olympian 8','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_MINOS','PER_GRK_ARCHAIC','high','Cretan king/underworld judge; Homer Odyssey 11.568','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_RHADAMANTHUS','PER_GRK_ARCHAIC','high','Underworld judge; Homer Odyssey 4.564','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_RHADAMANTHYS','PER_GRK_ARCHAIC','high','Underworld judge variant; Homer Odyssey 4.564','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
-- Underworld daimones
('ENT_ASCALAPHUS','PER_GRK_ARCHAIC','high','Underworld daimon; witness to Persephone eating pomegranate; Archaic myth','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_CHARON','PER_GRK_ARCHAIC','high','Ferryman of the dead; Archaic; Polygnotus painting (Classical); Aristophanes Frogs','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_EMPUSA','PER_GRK_ARCHAIC','high','Underworld daimon; Archaic tradition; Aristophanes Frogs (Classical)','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_EURYNOMOS','PER_GRK_ARCHAIC','high','Underworld flesh-eating daimon; Polygnotus Nekyia painting (early Classical)','SRC_APOLLODORUS_LIBRARY','reviewed'),
-- Wind gods
('ENT_BOREAS','PER_GRK_ARCHAIC','high','North wind; Homer Iliad 9.5; 19.358; Hesiod Theogony 379','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_EURUS','PER_GRK_ARCHAIC','high','East wind; Hesiod Theogony 379; Homer','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_NOTUS','PER_GRK_ARCHAIC','high','South wind; Homer Iliad 11.305; Hesiod Theogony 379','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_ZEPHYRUS','PER_GRK_ARCHAIC','high','West wind; Homer Iliad 19.415; Hesiod Theogony 379','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
-- Standard daimones
('ENT_HYPNOS','PER_GRK_ARCHAIC','high','Sleep; Hesiod Theogony 212; Homer Iliad 14.231','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_THANATOS','PER_GRK_ARCHAIC','high','Death; Hesiod Theogony 212; Homer Iliad 14.231','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_KAKODAIMON','PER_GRK_ARCHAIC','high','Evil spirit; Archaic Greek concept (Hesiod Works and Days)','SRC_HESIOD_THEOGONY','reviewed'),
-- Hesperids
('ENT_AEGLE_HESPERID','PER_GRK_ARCHAIC','high','Hesperid; Hesiod Theogony 215-216','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ARETHUSA_HESPERID','PER_GRK_ARCHAIC','high','Hesperid; Hesiod Theogony 215-216','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ERYTHEIA_HESPERID','PER_GRK_ARCHAIC','high','Hesperid; Hesiod Theogony 215-216','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_HESPERIA_HESPERID','PER_GRK_ARCHAIC','high','Hesperid; Hesiod Theogony 215-216','SRC_HESIOD_THEOGONY','reviewed'),
-- Monsters
('ENT_CHIMERA','PER_GRK_ARCHAIC','high','Fire-breathing monster; Homer Iliad 6.179; Hesiod Theogony 319','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_MINOTAUR','PER_GRK_ARCHAIC','high','Bull-man of Crete; Archaic tradition; Hesiod Catalogue','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_NEMEAN_LION','PER_GRK_ARCHAIC','high','Heracles Labor 1; Hesiod Theogony 327','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_MEDUSA','PER_GRK_ARCHAIC','high','Gorgon; Hesiod Theogony 276; Shield of Heracles 223','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_HYDRA','PER_GRK_ARCHAIC','high','Lernaean serpent; Hesiod Theogony 313','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_SCYLLA','PER_GRK_ARCHAIC','high','Sea monster; Homer Odyssey 12.73; Hesiod','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_CHARYBDIS','PER_GRK_ARCHAIC','high','Sea whirlpool monster; Homer Odyssey 12.101','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_GERYON','PER_GRK_ARCHAIC','high','Three-bodied giant; Hesiod Theogony 981; Heracles Labor 10','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_CERBERUS','PER_GRK_ARCHAIC','high','Underworld hound; Hesiod Theogony 311; Homer Iliad 8.368','SRC_HESIOD_THEOGONY','reviewed'),
-- Fate goddesses
('ENT_ATROPOS','PER_GRK_ARCHAIC','high','Fate who cuts the thread; Hesiod Theogony 218','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_CLOTHO','PER_GRK_ARCHAIC','high','Fate who spins; Hesiod Theogony 218','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_LACHESIS','PER_GRK_ARCHAIC','high','Fate who measures; Hesiod Theogony 218','SRC_HESIOD_THEOGONY','reviewed'),
-- Hora/seasonal
('ENT_AUXO','PER_GRK_ARCHAIC','high','Season; Hesiod Theogony 901 (Horae trio)','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_CARPO','PER_GRK_ARCHAIC','high','Season; Hesiod Theogony 901','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_THALLO','PER_GRK_ARCHAIC','high','Season; Hesiod Theogony 901','SRC_HESIOD_THEOGONY','reviewed'),
-- Graces
('ENT_AGLAIA','PER_GRK_ARCHAIC','high','Grace; Hesiod Theogony 909; Homer Iliad 18.382','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_EUPHROSYNE','PER_GRK_ARCHAIC','high','Grace; Hesiod Theogony 909','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_THALIA_GRACE','PER_GRK_ARCHAIC','high','Grace; Hesiod Theogony 909','SRC_HESIOD_THEOGONY','reviewed'),
-- Healing
('ENT_ACESO','PER_GRK_ARCHAIC','high','Healing goddess; daughter of Asclepius; Archaic tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_IASO','PER_GRK_ARCHAIC','high','Healing goddess; daughter of Asclepius; Archaic tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_PANACEA','PER_GRK_ARCHAIC','high','All-healing goddess; daughter of Asclepius; Archaic tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_EPIONE','PER_GRK_ARCHAIC','high','Healing goddess; wife of Asclepius; Archaic tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_HYGIEIA','PER_GRK_ARCHAIC','high','Health goddess; daughter of Asclepius; Hesiod Catalogue tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
-- Healing heroes
('ENT_MACHAON','PER_GRK_ARCHAIC','high','Healing hero; Homer Iliad 2.732; 4.193','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_PODALIRIUS','PER_GRK_ARCHAIC','high','Healing hero; Homer Iliad 2.732','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
-- Dream daimones
('ENT_MORPHEUS','PER_GRK_ARCHAIC','high','Dream god; Homer Odyssey 19.562 (dream gates); Hesiod Theogony 212','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_PHANTASOS','PER_GRK_ARCHAIC','high','Dream daimon; Hesiod Theogony 212 (Oneiroi)','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PHOBETOR','PER_GRK_ARCHAIC','high','Fear-dream daimon; Hesiod Theogony 212 (Oneiroi)','SRC_HESIOD_THEOGONY','reviewed'),
-- Underworld rivers
('ENT_ACHERON','PER_GRK_ARCHAIC','high','Underworld river of woe; Homer Odyssey 10.513','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_COCYTUS','PER_GRK_ARCHAIC','high','Underworld river of lamentation; Homer Odyssey 10.514','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_PHLEGETHON','PER_GRK_ARCHAIC','high','Underworld river of fire; Homer Odyssey 10.513','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_LETHE','PER_GRK_ARCHAIC','high','River of oblivion; Archaic tradition; Plato Republic (Classical)','SRC_HESIOD_THEOGONY','reviewed'),
-- Underworld nymphs/daimones
('ENT_GORGYRA','PER_GRK_ARCHAIC','high','Underworld nymph; Archaic tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_ORPHNE','PER_GRK_ARCHAIC','high','Underworld nymph; Archaic tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_MORMOLYKEIA','PER_GRK_ARCHAIC','high','Underworld daimon collective; Archaic nursery-fear tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_LAMPADES','PER_GRK_ARCHAIC','high','Torch-bearing underworld nymphs; Archaic chthonic tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
-- Chthonic deities
('ENT_HADES','PER_GRK_ARCHAIC','high','God of the underworld; Homer Iliad 5.395; 8.368; 15.188','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_PERSEPHONE','PER_GRK_ARCHAIC','high','Queen of underworld; Homeric Hymn to Demeter (c. 650 BCE); Homer Odyssey 10.491','SRC_HOMERIC_HYMNS','reviewed'),
('ENT_HECATE','PER_GRK_ARCHAIC','high','Liminal goddess; Hesiod Theogony 411-452 (most extensive praise passage in the poem)','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_KORE','PER_GRK_ARCHAIC','high','Persephone as Kore; Homeric Hymn to Demeter; Archaic Eleusinian tradition','SRC_HOMERIC_HYMNS','reviewed'),
('ENT_PLOUTON','PER_GRK_ARCHAIC','high','Hades euphemism; Archaic cult title; Eleusinian tradition','SRC_HOMERIC_HYMNS','reviewed'),
-- Miscellaneous gods and deified figures
('ENT_IRIS','PER_GRK_ARCHAIC','high','Rainbow goddess/messenger; Homer Iliad 2.786; Hesiod Theogony 266','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_EILEITHYIA','PER_GRK_ARCHAIC','high','Birth goddess; Homer Iliad 11.270; 16.187; Hesiod Theogony 922','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_MACARIA','PER_GRK_ARCHAIC','high','Daughter of Hades; Archaic blessed-dead tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_AMPHITRITE','PER_GRK_ARCHAIC','high','Sea goddess/Poseidon consort; Homer Odyssey 3.91; Hesiod Theogony 243','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_DORIS','PER_GRK_ARCHAIC','high','Oceanid/sea goddess; Hesiod Theogony 241','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_METIS','PER_GRK_ARCHAIC','high','Oceanid/first wife of Zeus; Hesiod Theogony 358, 886-900','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_STYX','PER_GRK_ARCHAIC','high','Underworld river goddess; Hesiod Theogony 361, 775-806; Homer Iliad 2.755','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_TYCHE_OCEANID','PER_GRK_ARCHAIC','high','Fortune Oceanid; Hesiod Theogony 360','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PHOSPHORUS','PER_GRK_ARCHAIC','high','Morning star; Hesiod Theogony 381','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_MAIA','PER_GRK_ARCHAIC','high','Pleiad; mother of Hermes; Homeric Hymn to Hermes 1; Hesiod','SRC_HOMERIC_HYMNS','reviewed'),
('ENT_AMALTHEIA','PER_GRK_ARCHAIC','high','Goat-nurse of Zeus; Archaic Cretan tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_ASCLEPIUS','PER_GRK_ARCHAIC','high','Healing god; Homer Iliad 2.731; Hesiod Catalogue; Homeric Hymn 16','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_ARISTAEUS','PER_GRK_ARCHAIC','high','Pastoral deity; Hesiod Theogony 977; Pindar Pythian 9 (Archaic)','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PAN','PER_GRK_ARCHAIC','high','Rustic god; Homeric Hymn 19; cult origins Arcadian (Archaic)','SRC_HOMERIC_HYMNS','reviewed'),
('ENT_PYTHON','PER_GRK_ARCHAIC','high','Delphic serpent; Homeric Hymn to Apollo 356-374','SRC_HOMERIC_HYMNS','reviewed'),
('ENT_GANYMEDE','PER_GRK_ARCHAIC','high','Cup-bearer of the gods; Homer Iliad 5.265; 20.234','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_HYMENAIOS','PER_GRK_ARCHAIC','high','Marriage daimon; Hesiod Theogony (birth from Magnes)','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_AEOLUS','PER_GRK_ARCHAIC','high','Keeper of winds; Homer Odyssey 10.1-79','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_DAEDALUS','PER_GRK_ARCHAIC','high','Master craftsman; Homer Iliad 18.592; Archaic tradition','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_PALAMEDES','PER_GRK_ARCHAIC','high','Culture hero/inventor; Archaic; Stesichorus; lost epics of Troy cycle','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_CURETES','PER_GRK_ARCHAIC','high','Armed dancers; Archaic Cretan tradition; Homeric Hymn to Zeus','SRC_HOMERIC_HYMNS','reviewed'),
('ENT_SILENUS','PER_GRK_ARCHAIC','high','Old satyr/companion of Dionysus; Homer Hymn to Aphrodite 262; Archaic tradition','SRC_HOMERIC_HYMNS','reviewed'),
('ENT_LINUS','PER_GRK_ARCHAIC','high','Musician/inventor of melody; Homer Iliad 18.570 (linos-song)','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_TROPHONIUS','PER_GRK_ARCHAIC','high','Oracle hero at Lebadea; Archaic Boeotian cult tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_AMPHIARAUS','PER_GRK_ARCHAIC','high','Seer-hero; Homer Odyssey 15.244; Archaic oracular cult at Oropus','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_DIOSCURI','PER_GRK_ARCHAIC','high','Castor and Pollux collective; Homer Iliad 3.237; Homeric Hymn 17','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_TRIPTOLEMUS','PER_GRK_ARCHAIC','high','Eleusinian hero; Homeric Hymn to Demeter (Archaic); spreads agriculture','SRC_HOMERIC_HYMNS','reviewed'),
('ENT_DESPOINA','PER_GRK_ARCHAIC','high','Arcadian mystery goddess; daughter of Demeter and Poseidon; Archaic cult','SRC_PAUSANIAS_DESCRIPTION','reviewed'),
('ENT_PLUTUS','PER_GRK_ARCHAIC','high','Wealth; Hesiod Theogony 969; Works and Days','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_HERMAPHRODITUS','PER_GRK_ARCHAIC','medium','Child of Hermes and Aphrodite; Archaic name-etiology; fully developed figure Hellenistic','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_IACCHUS','PER_GRK_ARCHAIC','high','Eleusinian mystery deity; Archaic Eleusinian tradition; Sophocles (Classical)','SRC_HOMERIC_HYMNS','reviewed'),
('ENT_GELLO','PER_GRK_ARCHAIC','high','Child-harming ghost; Sappho fr. 178 (one of earliest attestations — Archaic Lesbos)','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ACHLYS','PER_GRK_ARCHAIC','high','Mist of death; Hesiod Shield of Heracles 264','SRC_HESIOD_THEOGONY','reviewed'),
-- Sea-related
('ENT_EURYBIA_SEA','PER_GRK_ARCHAIC','high','Sea goddess; Hesiod Theogony 239','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_CETO','PER_GRK_ARCHAIC','high','Sea monster goddess; Hesiod Theogony 238','SRC_HESIOD_THEOGONY','reviewed'),
-- Deified/liminal
('ENT_ARIADNE','PER_GRK_ARCHAIC','high','Cretan princess; Homer Odyssey 11.321; Hesiod Theogony 947','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_PSYCHE','PER_GRK_ARCHAIC','medium','Soul personification; Archaic folk tradition; literary elaboration Hellenistic (Apuleius Roman)','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_TITHONUS','PER_GRK_ARCHAIC','high','Immortalized mortal; Homer Iliad 11.1; Homeric Hymn to Aphrodite 218','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_INO','PER_GRK_ARCHAIC','high','Deified mortal/sea goddess; Homer Odyssey 5.333','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_INO_LEUCOTHEA','PER_GRK_ARCHAIC','high','Leucothea form of Ino; Homer Odyssey 5.333','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_LEUCOTHEA','PER_GRK_ARCHAIC','high','White goddess; Homer Odyssey 5.333','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_GLAUCUS','PER_GRK_ARCHAIC','high','Deified fisherman; Archaic Boeotian tradition; Pindar','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_MELICERTES_PALAEMON','PER_GRK_ARCHAIC','high','Deified child/sea deity; Pindar Isthmian 6 (Archaic)','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_PALAEMON','PER_GRK_ARCHAIC','high','Sea deity/Melicertes; Archaic Isthmian Games tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
-- Naiad/nymph
('ENT_AGANIPPE','PER_GRK_ARCHAIC','high','Spring nymph/Muse spring; Archaic Heliconian tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ARETHUSA','PER_GRK_ARCHAIC','high','Naiad of Syracuse; Archaic Sicilian tradition; Pindar','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_SALMACIS','PER_GRK_ARCHAIC','high','Naiad; Archaic Carian tradition; Hermaphroditus myth','SRC_APOLLODORUS_LIBRARY','reviewed'),
-- Miscellanea
('ENT_AEACUS_HERO','PER_GRK_ARCHAIC','high','Underworld judge; Hesiod; Pindar','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_CALCHAS','PER_GRK_ARCHAIC','high','Seer; Homer Iliad 1.69','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_TIRESIAS','PER_GRK_ARCHAIC','high','Blind seer; Homer Odyssey 10.492; 11.90','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_CASSANDRA','PER_GRK_ARCHAIC','high','Prophetess; Homer Iliad 13.366; 24.699; Archaic tradition','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_MANTO','PER_GRK_ARCHAIC','high','Prophetess; daughter of Tiresias; Archaic tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_DAPHNE','PER_GRK_ARCHAIC','high','Naiad/nymph; Apollo myth; Archaic tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_ECHO','PER_GRK_ARCHAIC','high','Mountain nymph; Archaic tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_CYLLENE','PER_GRK_ARCHAIC','high','Arcadian mountain nymph; Archaic tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_BEROE','PER_GRK_ARCHAIC','high','Oceanid; Archaic tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_EPHYRA','PER_GRK_ARCHAIC','high','Oceanid/early name of Corinth; Hesiod Theogony 351','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_HERMES_CHTHONIOS_CULT','PER_GRK_ARCHAIC','high','Hermes in chthonic role; Archaic cult tradition','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_ZEUS_CHTHONIOS_CULT','PER_GRK_ARCHAIC','high','Zeus in underworld aspect; Archaic cult tradition','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_ZEUS_MEILICHIOS_CULT','PER_GRK_ARCHAIC','high','Zeus Meilichios (the Kindly); Archaic Attic cult; Athens Diasia festival','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_ZEUS_KTESIOS_CULT','PER_GRK_ARCHAIC','high','Zeus Ktesios (of the household store); Archaic Greek household cult','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_THEMIS_AT_DELPHI','PER_GRK_ARCHAIC','high','Themis as pre-Apollo Delphic holder; Aeschylus Eumenides 2; Archaic tradition','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_PHOEBE_AT_DELPHI','PER_GRK_ARCHAIC','high','Titaness Phoebe as pre-Apollo Delphic oracle; Aeschylus Eumenides 6','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_HADES_KLYMENOS','PER_GRK_ARCHAIC','high','Hades cult epithet (the Renowned); Archaic Hermione tradition','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_KOUROTROPHOS','PER_GRK_ARCHAIC','high','Child-nurturing deity type; widespread Archaic Greek cult epithet','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_CABEIRI','PER_GRK_ARCHAIC','high','Samothracian mystery gods; pre-Greek/Archaic tradition; Herodotus 2.51','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_GREAT_GODS_SAMOTHRACE','PER_GRK_ARCHAIC','high','Samothracian mystery cult; Archaic origins; became major Hellenistic dynasty cult','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_MAENADS','PER_GRK_ARCHAIC','high','Dionysus worshippers; Homer Iliad 22.460; Archaic vase tradition','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_THYIADS','PER_GRK_ARCHAIC','high','Delphic Dionysiac women; Archaic tradition','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_MUSES_HELICONIAN','PER_GRK_ARCHAIC','high','Heliconian Muses; Hesiod Theogony 1-21','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_CYCLOPES_CRAFTSMEN','PER_GRK_ARCHAIC','high','Craftsmen Cyclopes; Hesiod Theogony 139-146 (forged Zeus lightning bolts)','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ANEMOI','PER_GRK_ARCHAIC','high','Wind gods collective; Hesiod Theogony 378; Homer Iliad 23.194','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_KALLIGENEIA','PER_GRK_ARCHAIC','high','Thesmophoria deity; Archaic Attic festival tradition','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_ANYTUS','PER_GRK_ARCHAIC','high','Guardian of Demeter at Thelpusa/Pheneus; Arcadian cult figure; Archaic tradition','SRC_PAUSANIAS_DESCRIPTION','reviewed'),
('ENT_EUBOULEUS','PER_GRK_ARCHAIC','high','Eleusinian swine-herd figure; Archaic Eleusinian tradition','SRC_HOMERIC_HYMNS','reviewed'),
('ENT_MELAMPUS','PER_GRK_ARCHAIC','high','Seer-hero; Homer Odyssey 11.291; Archaic seer tradition','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_PHYLLIS','PER_GRK_ARCHAIC','high','Thracian princess; Archaic tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_PALLAS','PER_GRK_ARCHAIC','high','Warrior name/Athena epithet; Homer Iliad; Archaic tradition','SRC_HOMER_ILIAD_ODYSSEY','reviewed'),
('ENT_CHELONE','PER_GRK_ARCHAIC','high','Nymph transformed into tortoise; Archaic tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_THALIA_NEREID','PER_GRK_ARCHAIC','high','Nereid; Hesiod Theogony 245','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_ADONIS','PER_GRK_ARCHAIC','high','Vegetation deity; Sappho fr. 140 is earliest Greek attestation (Archaic Lesbos)','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_HERMAPHRODITUS','PER_GRK_ARCHAIC','medium','Divine androgyne; name from Hermes + Aphrodite; Archaic name-etiology','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_AGATHOS_DAIMON','PER_GRK_ARCHAIC','medium','Good spirit; Hesiod Works and Days 122-126 (unnamed good daimones of Golden Age)','SRC_HESIOD_THEOGONY','reviewed'),
('ENT_BENDIS','PER_GRK_ARCHAIC','medium','Thracian moon goddess; Archaic Thrace; Herodotus notes Thracian worship','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_COTYS','PER_GRK_ARCHAIC','medium','Thracian goddess; Archaic Thracian tradition; Aeschylus fr. (5th c. CE)','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_PRIAPUS','PER_GRK_ARCHAIC','medium','Fertility deity of Lampsacus; Archaic Hellespont tradition','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_M_N','PER_GRK_ARCHAIC','medium','Anatolian moon deity; Archaic Lydian/Phrygian substrate','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_CYBELE','PER_GRK_ARCHAIC','high','Phrygian mother goddess; first Greek attestation Archaic (Pindar; Hipponax)','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_ZAGREUS','PER_GRK_ARCHAIC','medium','Orphic Dionysus; Aeschylus fr. 228 = earliest Greek attestation (early Classical)','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_ORPHEUS','PER_GRK_ARCHAIC','high','Mythic singer; Ibycus PMG 282, Simonides fr. 27 (late 6th c. BCE)','SRC_APOLLODORUS_LIBRARY','reviewed'),
-- Seer heroes
('ENT_GLYCON','PER_GRK_ARCHAIC','low','Snake oracle deity; Abonoteichos; 2nd c. CE in practice; mythological roots claimed Archaic','SRC_BURKERT_GREEK_RELIGION','reviewed')
ON CONFLICT DO NOTHING;

-- ── 21. Add PER_GRK_CLASSICAL for tragedy/philosophical prominence ─────────────
INSERT INTO entity_periods (entity_id, period_id, confidence, rationale, source_id, review_status) VALUES
-- Heroes featured centrally in Attic tragedy
('ENT_ACHILLES','PER_GRK_CLASSICAL','high','Central figure in Aeschylus Achilleis trilogy; Sophocles; Euripides Iphigenia at Aulis','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_AJAX','PER_GRK_CLASSICAL','high','Sophocles Ajax; major Classical tragedy','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_ORESTES','PER_GRK_CLASSICAL','high','Aeschylus Oresteia (458 BCE); Sophocles Electra; Euripides Orestes','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_MEDEA','PER_GRK_CLASSICAL','high','Euripides Medea (431 BCE); defining Classical tragedy','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_IPHIGENIA','PER_GRK_CLASSICAL','high','Euripides Iphigenia at Aulis; Iphigenia in Tauris','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_HERACLES','PER_GRK_CLASSICAL','high','Sophocles Women of Trachis; Euripides Heracles; Euripides Alcestis','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_ODYSSEUS','PER_GRK_CLASSICAL','high','Sophocles Philoctetes; Ajax; Euripides Cyclops; Rhesus','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_THESEUS','PER_GRK_CLASSICAL','high','Appears as character in Euripides Suppliant Women; Hippolytus; Sophocles Oedipus at Colonus','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_CADMUS','PER_GRK_CLASSICAL','high','Euripides Bacchae (405 BCE); Phoenician Women','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_HIPPOLYTUS','PER_GRK_CLASSICAL','high','Euripides Hippolytus (428 BCE)','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_PERSEUS','PER_GRK_CLASSICAL','high','Aeschylus Perseid trilogy; Sophocles (Classical tragedy)','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_HECTOR','PER_GRK_CLASSICAL','high','Appears in Classical tragedy; Euripides Rhesus','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_ORPHEUS','PER_GRK_CLASSICAL','high','Central to Classical Orphic traditions; Pindar Pythian 4; Euripides Alcestis (Orpheus allusion)','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_ASCLEPIUS','PER_GRK_CLASSICAL','high','Major healing cult development Classical period; Epidaurus sanctuary established 5th c. BCE; Homeric Hymn 16','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_ATALANTA','PER_GRK_CLASSICAL','high','Euripides Meleager; Sophocles Meleager; Classical tragic tradition','SRC_BURKERT_GREEK_RELIGION','reviewed'),
-- Daimones prominent in Classical philosophy or drama
('ENT_ERINYES','PER_GRK_CLASSICAL','high','Aeschylus Eumenides (458 BCE) makes them central characters','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_EUMENIDES','PER_GRK_CLASSICAL','high','Aeschylus Eumenides — the play names and transforms them','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_NEMESIS','PER_GRK_CLASSICAL','high','Classical philosophical concept; Aeschylus; Pindar; Herodotus; sanctuary at Rhamnous','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_NIKE','PER_GRK_CLASSICAL','high','Major Classical cult; Temple of Athena Nike on Acropolis 420 BCE; Nike of Samothrace Hellenistic','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_EROS','PER_GRK_CLASSICAL','high','Plato Symposium; philosophical treatment; Sophocles Antigone; Euripides Hippolytus','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_ATE','PER_GRK_CLASSICAL','high','Sophocles — hamartia tradition; Aeschylus uses frequently','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_PEITHO','PER_GRK_CLASSICAL','high','Aeschylus Agamemnon 385; Choephoroi; Eumenides; Classical rhetoric personification','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_HYBRIS','PER_GRK_CLASSICAL','high','Core Classical tragic concept; Aeschylus; Sophocles; Herodotus','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_BIA','PER_GRK_CLASSICAL','high','Aeschylus Prometheus Bound (opening scene)','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_KRATOS','PER_GRK_CLASSICAL','high','Aeschylus Prometheus Bound (opening scene; dialogue character)','SRC_BURKERT_GREEK_RELIGION','reviewed'),
-- Chthonic/mystery cult Classical development
('ENT_PERSEPHONE','PER_GRK_CLASSICAL','high','Eleusinian Mysteries; Classical Athenian ritual year; Sophocles fr.','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_KORE','PER_GRK_CLASSICAL','high','Eleusinian cult — Classical peak period; Pindar Olympian 6','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_HECATE','PER_GRK_CLASSICAL','high','Sophocles fr.; Euripides; Classical Athenian chthonic cult (propylaia shrines)','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_IACCHUS','PER_GRK_CLASSICAL','high','Eleusinian procession deity; Sophocles fr. 959; Aristophanes Frogs 316','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_TROPHONIUS','PER_GRK_CLASSICAL','high','Classical oracle at Lebadea; Herodotus 1.46; Pausanias (elaborated Classical)','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_PLOUTON','PER_GRK_CLASSICAL','high','Eleusinian name for Hades; Classical peak (Pindar, Sophocles)','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_TRIPTOLEMUS','PER_GRK_CLASSICAL','high','Homeric Hymn to Demeter; Classical Eleusinian hero; Sophocles Triptolemos','SRC_BURKERT_GREEK_RELIGION','reviewed'),
-- Mystery and civic cults
('ENT_PAN','PER_GRK_CLASSICAL','high','Pan cult spread to Athens after Marathon 490 BCE (Herodotus 6.105); Classical civic cult','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_TYCHE','PER_GRK_CLASSICAL','high','Classical city-fortune; Pindar Olympian 12; becomes major civic deity','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_BENDIS','PER_GRK_CLASSICAL','high','Thracian goddess officially admitted to Athens c. 430 BCE; Plato Republic opens at Bendis festival','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_COTYS','PER_GRK_CLASSICAL','high','Thracian goddess attested in Aeschylus fr.; Euripides Bacchae context','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_SABAZIOS','PER_GRK_CLASSICAL','high','Aristophanes Birds 874-876; Demosthenes; Thracian/Phrygian deity admitted to Classical Athens','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_CABEIRI','PER_GRK_CLASSICAL','high','Herodotus 2.51 (Classical); Samothrace initiations Classical period','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_ZAGREUS','PER_GRK_CLASSICAL','high','Aeschylus Aigyptioi fr. 5 (earliest clear reference); Classical Orphic tradition','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_EUBOULEUS','PER_GRK_CLASSICAL','high','Classical Eleusinian tradition (Thesmophoria/Demeter mysteries)','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_CHARON','PER_GRK_CLASSICAL','high','Aristophanes Frogs (405 BCE); Polygnotus Nekyia painting; Classical literary elaboration','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_ATTIS','PER_GRK_CLASSICAL','high','First Greek literary attestation Pindar fr. 80; Classical reception of Phrygian myth','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_ADONIS','PER_GRK_CLASSICAL','high','Athenian Adonia festival; Aristophanes Lysistrata 387; Plato Phaedrus 276b','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_CYBELE','PER_GRK_CLASSICAL','high','Euripides Bacchae (Cybele/Rhea equated); Pindar; Sophocles; major Classical Athenian presence','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_PLUTUS','PER_GRK_CLASSICAL','high','Aristophanes Plutus (388 BCE) — principal character','SRC_BURKERT_GREEK_RELIGION','reviewed')
ON CONFLICT DO NOTHING;

-- ── 22. Hellenistic-specific ──────────────────────────────────────────────────
INSERT INTO entity_periods (entity_id, period_id, confidence, rationale, source_id, review_status) VALUES
('ENT_TYCHE','PER_GRK_HELLENISTIC','high','Becomes patron deity of Hellenistic cities (Tyche of Antioch by Eutychides, 300 BCE); major civic goddess in every Hellenistic foundation','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_AGATHOS_DAIMON','PER_GRK_HELLENISTIC','high','Ptolemaic snake cult of Alexandria; major Hellenistic popular deity','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_MELINOE','PER_GRK_HELLENISTIC','high','Underworld goddess; Orphic Hymn 71 (Hellenistic Orphic Hymns)','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_GREAT_GODS_SAMOTHRACE','PER_GRK_HELLENISTIC','high','Samothrace mystery cult becomes major Hellenistic pan-Greek institution; Ptolemaic and Macedonian royal patronage','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_ATTIS','PER_GRK_HELLENISTIC','high','Cybele/Attis mysteries became major Hellenistic mystery cult before Roman adoption','SRC_BURKERT_GREEK_RELIGION','reviewed'),
('ENT_HERMAPHRODITUS','PER_GRK_HELLENISTIC','high','Fully developed mythological figure first clearly Hellenistic (Diodorus Siculus 4.6)','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_PRIAPUS','PER_GRK_HELLENISTIC','high','Lampsacus fertility deity; Priapea literary tradition; Hellenistic Alexandrian poetry','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_PSYCHE','PER_GRK_HELLENISTIC','high','Soul personification elaborated in Hellenistic and Roman literature (Apuleius Metamorphoses)','SRC_APOLLODORUS_LIBRARY','reviewed'),
('ENT_GLYCON','PER_GRK_ROMAN','high','Snake oracle of Abonoteichos; Lucian Alexander (2nd c. CE); genuinely Roman-period phenomenon','SRC_PAUSANIAS_DESCRIPTION','reviewed')
ON CONFLICT DO NOTHING;

-- ── Verify ────────────────────────────────────────────────────────────────────
SELECT
  COUNT(DISTINCT entity_id) AS greek_entities_total,
  COUNT(DISTINCT CASE WHEN entity_id IN (SELECT entity_id FROM entity_periods) THEN entity_id END) AS now_periodized,
  COUNT(DISTINCT CASE WHEN entity_id NOT IN (SELECT entity_id FROM entity_periods) THEN entity_id END) AS still_unperiodized
FROM entities WHERE tradition = 'Greek';

SELECT * FROM v_release_metrics;

COMMIT;
