-- scripts/add_gigantes.sql
-- Greek Gigantes (Giants of the Gigantomachy), Apollodorus Library 1.6.1-2 (Frazer).
-- Verbatim death-clauses, substring-gated. Homonym-colliding giants (Pallas/Ephialtes/
-- Eurytus/Clytius/Hippolytus) skipped to avoid duplicate entity_ids. No AI prose.

BEGIN;

INSERT INTO entities
  (entity_id, canonical_name, tradition, entity_type, category, primary_domains, cult_scope, primary_period, evidence_confidence, review_status, inclusion_basis, earth_association_score, chthonic_flag, serpent_flag, short_note, entity_class)
VALUES
('ENT_ALCYONEUS','Alcyoneus','Greek','Giant (Gigas)','Giant','giant; Gigantomachy; immortal in his homeland','Greek','archaic Greek','A','candidate_verified_name','Apollodorus Library primary attestation (1.6)',2,false,false,'Giant slain by Heracles (revived when touching his native earth until dragged from it) in the Gigantomachy.','spirit'),
('ENT_PORPHYRION','Porphyrion','Greek','Giant (Gigas)','Giant','giant; Gigantomachy; king of the Giants','Greek','archaic Greek','A','candidate_verified_name','Apollodorus Library primary attestation (1.6)',2,false,false,'Giant, leader of the Gigantes, who assailed Hera and was slain by Zeus thunderbolt and Heracles arrow.','spirit'),
('ENT_MIMAS','Mimas','Greek','Giant (Gigas)','Giant','giant; Gigantomachy','Greek','archaic Greek','A','candidate_verified_name','Apollodorus Library primary attestation (1.6)',2,false,false,'Giant slain by Hephaestus with missiles of red-hot metal in the Gigantomachy.','spirit'),
('ENT_ENCELADUS','Enceladus','Greek','Giant (Gigas)','Giant','giant; Gigantomachy; buried under Sicily','Greek','archaic Greek','A','candidate_verified_name','Apollodorus Library primary attestation (1.6)',2,false,false,'Giant who fled the Gigantomachy and was buried by Athena under the island of Sicily.','spirit'),
('ENT_POLYBOTES','Polybotes','Greek','Giant (Gigas)','Giant','giant; Gigantomachy; buried under Nisyros','Greek','archaic Greek','A','candidate_verified_name','Apollodorus Library primary attestation (1.6)',2,false,false,'Giant chased by Poseidon and crushed under the island of Nisyrus in the Gigantomachy.','spirit'),
('ENT_GRATION','Gration','Greek','Giant (Gigas)','Giant','giant; Gigantomachy','Greek','archaic Greek','A','candidate_verified_name','Apollodorus Library primary attestation (1.6)',2,false,false,'Giant slain by Artemis in the Gigantomachy.','spirit'),
('ENT_AGRIUS','Agrius','Greek','Giant (Gigas)','Giant','giant; Gigantomachy','Greek','archaic Greek','A','candidate_verified_name','Apollodorus Library primary attestation (1.6)',2,false,false,'Giant slain (with Thoas) by the Fates wielding brazen clubs in the Gigantomachy.','spirit'),
('ENT_THOAS','Thoas','Greek','Giant (Gigas)','Giant','giant; Gigantomachy','Greek','archaic Greek','A','candidate_verified_name','Apollodorus Library primary attestation (1.6)',2,false,false,'Giant slain (with Agrius) by the Fates wielding brazen clubs in the Gigantomachy.','spirit')
ON CONFLICT (entity_id) DO NOTHING;

INSERT INTO entity_citations
  (citation_id,entity_id,source_id,work_title,locus,quote,translator,translation_year,source_url,original_text_url,evidence_grade,evidence_note,needs_review,review_reason,verified_on,verify_method,display_order)
VALUES
('CIT_ALCYONEUS_APOLLOD','ENT_ALCYONEUS','SRC_APOLLODORUS_LIBRARY','Pseudo-Apollodorus, Library','Library 1.6.1-2','Hercules first shot Alcyoneus with an arrow, but when the giant fell on the ground he somewhat revived. However, at Athena''s advice Hercules dragged him outside Pallene, and so the giant died.','J. G. Frazer',1921,'https://www.theoi.com/Text/Apollodorus1.html',NULL,'primary-verbatim',NULL,true,'Named in the Gigantomachy of Apollodorus 1.6 (Frazer); verify section.',DATE '2026-06-26','name + substring gate against Frazer Apollodorus',1),
('CIT_PORPHYRION_APOLLOD','ENT_PORPHYRION','SRC_APOLLODORUS_LIBRARY','Pseudo-Apollodorus, Library','Library 1.6.1-2','But in the battle Porphyrion attacked Hercules and Hera. Nevertheless Zeus inspired him with lust for Hera, and when he tore her robes and would have forced her, she called for help, and Zeus smote him with a thunderbolt, and Hercules shot him dead with an arrow.','J. G. Frazer',1921,'https://www.theoi.com/Text/Apollodorus1.html',NULL,'primary-verbatim',NULL,true,'Named in the Gigantomachy of Apollodorus 1.6 (Frazer); verify section.',DATE '2026-06-26','name + substring gate against Frazer Apollodorus',1),
('CIT_MIMAS_APOLLOD','ENT_MIMAS','SRC_APOLLODORUS_LIBRARY','Pseudo-Apollodorus, Library','Library 1.6.1-2','Mimas by Hephaestus with missiles of red-hot metal.','J. G. Frazer',1921,'https://www.theoi.com/Text/Apollodorus1.html',NULL,'primary-verbatim',NULL,true,'Named in the Gigantomachy of Apollodorus 1.6 (Frazer); verify section.',DATE '2026-06-26','name + substring gate against Frazer Apollodorus',1),
('CIT_ENCELADUS_APOLLOD','ENT_ENCELADUS','SRC_APOLLODORUS_LIBRARY','Pseudo-Apollodorus, Library','Library 1.6.1-2','Enceladus fled, but Athena threw on him in his flight the island of Sicily','J. G. Frazer',1921,'https://www.theoi.com/Text/Apollodorus1.html',NULL,'primary-verbatim',NULL,true,'Named in the Gigantomachy of Apollodorus 1.6 (Frazer); verify section.',DATE '2026-06-26','name + substring gate against Frazer Apollodorus',1),
('CIT_POLYBOTES_APOLLOD','ENT_POLYBOTES','SRC_APOLLODORUS_LIBRARY','Pseudo-Apollodorus, Library','Library 1.6.1-2','Polybotes was chased through the sea by Poseidon and came to Cos; and Poseidon, breaking off that piece of the island which is called Nisyrum, threw it on him.','J. G. Frazer',1921,'https://www.theoi.com/Text/Apollodorus1.html',NULL,'primary-verbatim',NULL,true,'Named in the Gigantomachy of Apollodorus 1.6 (Frazer); verify section.',DATE '2026-06-26','name + substring gate against Frazer Apollodorus',1),
('CIT_GRATION_APOLLOD','ENT_GRATION','SRC_APOLLODORUS_LIBRARY','Pseudo-Apollodorus, Library','Library 1.6.1-2','Artemis slew Gration.','J. G. Frazer',1921,'https://www.theoi.com/Text/Apollodorus1.html',NULL,'primary-verbatim',NULL,true,'Named in the Gigantomachy of Apollodorus 1.6 (Frazer); verify section.',DATE '2026-06-26','name + substring gate against Frazer Apollodorus',1),
('CIT_AGRIUS_APOLLOD','ENT_AGRIUS','SRC_APOLLODORUS_LIBRARY','Pseudo-Apollodorus, Library','Library 1.6.1-2','And the Fates, fighting with brazer clubs, killed Agrius and Thoas','J. G. Frazer',1921,'https://www.theoi.com/Text/Apollodorus1.html',NULL,'primary-verbatim',NULL,true,'Named in the Gigantomachy of Apollodorus 1.6 (Frazer); verify section.',DATE '2026-06-26','name + substring gate against Frazer Apollodorus',1),
('CIT_THOAS_APOLLOD','ENT_THOAS','SRC_APOLLODORUS_LIBRARY','Pseudo-Apollodorus, Library','Library 1.6.1-2','And the Fates, fighting with brazer clubs, killed Agrius and Thoas','J. G. Frazer',1921,'https://www.theoi.com/Text/Apollodorus1.html',NULL,'primary-verbatim',NULL,true,'Named in the Gigantomachy of Apollodorus 1.6 (Frazer); verify section.',DATE '2026-06-26','name + substring gate against Frazer Apollodorus',1)
ON CONFLICT (citation_id) DO UPDATE SET quote=EXCLUDED.quote;

COMMIT;
