-- build_occult_revival.sql  (GENERATED by gen_occult_revival.py) — v1.74.0
-- Modern Occult Revival aligned to existing traditions: Thelema (ENT_THL_), Theosophy (ENT_THE_,
-- reusing ENT_REC_MAHATMAS), and the Golden Dawn (ENT_MOD_).
-- 19 new entities, 38 edges. Idempotent + self-validating.
BEGIN;

INSERT INTO periods (period_id, period_name, start_year, end_year) VALUES
 ('PER_MODERN_OCCULT','Modern Occult Revival',1850,1950)
ON CONFLICT (period_id) DO NOTHING;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_GOLDEN_DAWN','primary text','The Hermetic Order of the Golden Dawn corpus (cipher manuscripts; Regardie, The Golden Dawn)','Modern Occult')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,trad text,etype text,cat text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_THL_PANTHEON','The Thelemic Pantheon','Thelemic','Collective','Collective','Thelema; the deities of Liber AL; the new aeon','B','The collective of deities and praeterhuman intelligences central to Aleister Crowley''s Thelema as set out in Liber AL vel Legis (1904) and its surrounding corpus.'),
 ('ENT_THL_HOOR_PAAR_KRAAT','Hoor-paar-kraat','Thelemic','Thelemic deity','Deity','silence; the inmost; passivity; secrecy','B','The silent passive twin of Ra-Hoor-Khuit, the god of silence; a Thelemic adaptation of Harpocrates forming a polarity with the active conquering child.'),
 ('ENT_THL_BABALON','Babalon','Thelemic','Thelemic deity','Deity','the Great Mother; ecstasy; the Scarlet Woman; liberation; the Abyss','B','The Thelemic Great Mother and sacred-whore goddess riding the Beast, developed by Crowley (notably in The Vision and the Voice) as a redemptive reframing of the biblical Whore of Babylon.'),
 ('ENT_THL_THERION','Therion (The Beast 666)','Thelemic','Thelemic deity','Deity','force; the magical self; prophecy; consort of Babalon','B','To Mega Therion, ''The Great Beast 666,'' Crowley''s prophetic magical office and consort of Babalon; an affirmative reclamation of the apocalyptic Beast of Revelation.'),
 ('ENT_THL_CHORONZON','Choronzon','Thelemic','Praeterhuman intelligence','Demon','the Abyss; dispersion; chaos; dissolution of the ego','B','The demon and ''dweller in the Abyss'' encountered in the 10th Aethyr; first named in John Dee''s Enochian records and greatly developed by Crowley into the Thelemic embodiment of dispersion.'),
 ('ENT_THL_HGA','The Holy Guardian Angel','Thelemic','Concept','Concept','the true self; tutelary spirit; attainment; knowledge and conversation','B','The Thelemic/Abramelin concept of the individual''s tutelary genius or true higher self, whose ''Knowledge and Conversation'' is the central attainment; adopted from the Book of Abramelin and recast by Crowley, who identified Aiwass as his own HGA.'),
 ('ENT_THL_AEON_HORUS','The Aeon of Horus','Thelemic','Concept','Concept','the present age; the crowned and conquering child; self-realization','B','The current cosmic age inaugurated in 1904 according to Thelema, succeeding the Aeons of Isis and Osiris and governed by Ra-Hoor-Khuit; modeled as an era rather than a being.'),
 ('ENT_THE_HIERARCHY','The Theosophical Spiritual Hierarchy','Theosophical','Collective','Collective','the spiritual hierarchy of beings governing planetary and cosmic evolution','B','The graded hierarchy of spiritual beings — the Masters, the Lord of the World, the Logoi, and the Lords of Karma — said in Theosophy to oversee human and planetary evolution.'),
 ('ENT_THE_MORYA','Morya (Master M.)','Theosophical','Ascended master','Spirit','hidden wisdom; spiritual guidance; the first ray of will','B','Master Morya, one of the Mahatmas said to stand behind the Theosophical Society and to have corresponded with Blavatsky; a being original to the modern Theosophical movement.'),
 ('ENT_THE_KOOT_HOOMI','Koot Hoomi (Master K.H.)','Theosophical','Ascended master','Spirit','hidden wisdom; spiritual guidance; the second ray of love-wisdom','B','Master Koot Hoomi (Kuthumi), one of the principal Mahatmas of Theosophy and chief author of the Mahatma Letters; a being original to the modern Theosophical movement.'),
 ('ENT_THE_DJWAL_KHUL','Djwal Khul (The Tibetan)','Theosophical','Ascended master','Spirit','hidden wisdom; esoteric teaching; transmission','B','Master Djwal Khul, ''the Tibetan,'' a Mahatma later said to have telepathically dictated the books written through Alice Bailey; a being of the modern Theosophical tradition.'),
 ('ENT_THE_MAHA_CHOHAN','The Maha Chohan','Theosophical','Ascended master','Spirit','hidden wisdom; spiritual administration; the third ray','B','The ''Great Lord,'' chief of the third ray and head of the Masters'' hierarchy of civilization in Theosophical teaching; a being original to the modern Theosophical movement.'),
 ('ENT_THE_SANAT_KUMARA','Sanat Kumara','Theosophical','Cosmic being','Deity','the Lord of the World; Shamballa; planetary governance; the Ancient of Days','B','The ''Lord of the World'' and ''Ancient of Days'' said to dwell at Shamballa and govern Earth''s spiritual evolution; a Theosophical adaptation of the Hindu Kumara name into a modern cosmic office.'),
 ('ENT_THE_SOLAR_LOGOS','The Solar Logos','Theosophical','Cosmic being','Deity','the solar system; cosmic consciousness; the divine animating logos','B','The Theosophical conception of the divine intelligence ensouling and governing the entire solar system, developed within the modern revival from the Greek philosophical Logos.'),
 ('ENT_THE_PLANETARY_LOGOS','The Planetary Logos','Theosophical','Cosmic being','Deity','planetary governance; the Earth-chain; cosmic consciousness','B','The Theosophical divine intelligence ensouling a single planet, subordinate to the Solar Logos; a modern-revival cosmological office.'),
 ('ENT_THE_LIPIKA','The Lords of Karma (The Lipika)','Theosophical','Cosmic being','Collective','karma; the cosmic record; the law of cause and effect; the akashic record','B','The Lipika, the ''recorders'' or Lords of Karma described in Blavatsky''s The Secret Doctrine who register every act and administer the law of karma; a collective being of modern Theosophical cosmology.'),
 ('ENT_THE_ROOT_RACES','The Root Races','Theosophical','Cosmic being','Collective','human evolution; cosmic cycles; the seven humanities','B','The series of seven successive cosmological humanities (Lemurian, Atlantean, Aryan, ...) through which spirit evolves in The Secret Doctrine; modeled as a single collective rather than seven entities.'),
 ('ENT_MOD_GOLDEN_DAWN','The Hermetic Order of the Golden Dawn','Modern Occult','Magical order','Collective','ceremonial magic; initiation; the Western esoteric synthesis','B','The influential English initiatory magical order founded in 1888 that synthesized Qabalah, Enochian, Egyptian, and Tarot systems; a synthesizing framework rather than a source of new beings.'),
 ('ENT_MOD_SECRET_CHIEFS','The Secret Chiefs','Modern Occult','Praeterhuman intelligence','Collective','hidden authority; initiation; direction of the Order','B','The hidden Third-Order adepts said to direct the Hermetic Order of the Golden Dawn through its leaders (notably claimed by Mathers); a concept paralleling and influenced by the Theosophical Masters.');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'literary',conf,'candidate_verified_name','Modern occult revival (v1.74.0)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,note text,etype text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_THL_PANTHEON','SRC_CROWLEY_BOOK_OF_LAW','The collective of deities and praeterhuman intelligences central to Aleister Crowley''s Thelema as set out in Liber AL vel Legis (1904) and its surrounding corpus.','primary text attestation'),
 ('ENT_THL_HOOR_PAAR_KRAAT','SRC_CROWLEY_BOOK_OF_LAW','The silent passive twin of Ra-Hoor-Khuit, the god of silence; a Thelemic adaptation of Harpocrates forming a polarity with the active conquering child.','primary text attestation'),
 ('ENT_THL_BABALON','SRC_CROWLEY_BOOK_OF_LAW','The Thelemic Great Mother and sacred-whore goddess riding the Beast, developed by Crowley (notably in The Vision and the Voice) as a redemptive reframing of the biblical Whore of Babylon.','primary text attestation'),
 ('ENT_THL_THERION','SRC_CROWLEY_BOOK_OF_LAW','To Mega Therion, ''The Great Beast 666,'' Crowley''s prophetic magical office and consort of Babalon; an affirmative reclamation of the apocalyptic Beast of Revelation.','primary text attestation'),
 ('ENT_THL_CHORONZON','SRC_CROWLEY_BOOK_OF_LAW','The demon and ''dweller in the Abyss'' encountered in the 10th Aethyr; first named in John Dee''s Enochian records and greatly developed by Crowley into the Thelemic embodiment of dispersion.','primary text attestation'),
 ('ENT_THL_HGA','SRC_CROWLEY_BOOK_OF_LAW','The Thelemic/Abramelin concept of the individual''s tutelary genius or true higher self, whose ''Knowledge and Conversation'' is the central attainment; adopted from the Book of Abramelin and recast by Crowley, who identified Aiwass as his own HGA.','primary text attestation'),
 ('ENT_THL_AEON_HORUS','SRC_CROWLEY_BOOK_OF_LAW','The current cosmic age inaugurated in 1904 according to Thelema, succeeding the Aeons of Isis and Osiris and governed by Ra-Hoor-Khuit; modeled as an era rather than a being.','primary text attestation'),
 ('ENT_THE_HIERARCHY','SRC_BLAVATSKY_SECRET_DOCTRINE','The graded hierarchy of spiritual beings — the Masters, the Lord of the World, the Logoi, and the Lords of Karma — said in Theosophy to oversee human and planetary evolution.','primary text attestation'),
 ('ENT_THE_MORYA','SRC_BLAVATSKY_SECRET_DOCTRINE','Master Morya, one of the Mahatmas said to stand behind the Theosophical Society and to have corresponded with Blavatsky; a being original to the modern Theosophical movement.','primary text attestation'),
 ('ENT_THE_KOOT_HOOMI','SRC_BLAVATSKY_SECRET_DOCTRINE','Master Koot Hoomi (Kuthumi), one of the principal Mahatmas of Theosophy and chief author of the Mahatma Letters; a being original to the modern Theosophical movement.','primary text attestation'),
 ('ENT_THE_DJWAL_KHUL','SRC_BLAVATSKY_SECRET_DOCTRINE','Master Djwal Khul, ''the Tibetan,'' a Mahatma later said to have telepathically dictated the books written through Alice Bailey; a being of the modern Theosophical tradition.','primary text attestation'),
 ('ENT_THE_MAHA_CHOHAN','SRC_BLAVATSKY_SECRET_DOCTRINE','The ''Great Lord,'' chief of the third ray and head of the Masters'' hierarchy of civilization in Theosophical teaching; a being original to the modern Theosophical movement.','primary text attestation'),
 ('ENT_THE_SANAT_KUMARA','SRC_BLAVATSKY_SECRET_DOCTRINE','The ''Lord of the World'' and ''Ancient of Days'' said to dwell at Shamballa and govern Earth''s spiritual evolution; a Theosophical adaptation of the Hindu Kumara name into a modern cosmic office.','primary text attestation'),
 ('ENT_THE_SOLAR_LOGOS','SRC_BLAVATSKY_SECRET_DOCTRINE','The Theosophical conception of the divine intelligence ensouling and governing the entire solar system, developed within the modern revival from the Greek philosophical Logos.','primary text attestation'),
 ('ENT_THE_PLANETARY_LOGOS','SRC_BLAVATSKY_SECRET_DOCTRINE','The Theosophical divine intelligence ensouling a single planet, subordinate to the Solar Logos; a modern-revival cosmological office.','primary text attestation'),
 ('ENT_THE_LIPIKA','SRC_BLAVATSKY_SECRET_DOCTRINE','The Lipika, the ''recorders'' or Lords of Karma described in Blavatsky''s The Secret Doctrine who register every act and administer the law of karma; a collective being of modern Theosophical cosmology.','primary text attestation'),
 ('ENT_THE_ROOT_RACES','SRC_BLAVATSKY_SECRET_DOCTRINE','The series of seven successive cosmological humanities (Lemurian, Atlantean, Aryan, ...) through which spirit evolves in The Secret Doctrine; modeled as a single collective rather than seven entities.','primary text attestation'),
 ('ENT_MOD_GOLDEN_DAWN','SRC_GOLDEN_DAWN','The influential English initiatory magical order founded in 1888 that synthesized Qabalah, Enochian, Egyptian, and Tarot systems; a synthesizing framework rather than a source of new beings.','primary text attestation'),
 ('ENT_MOD_SECRET_CHIEFS','SRC_GOLDEN_DAWN','The hidden Third-Order adepts said to direct the Hermetic Order of the Golden Dawn through its leaders (notably claimed by Mathers); a concept paralleling and influenced by the Theosophical Masters.','primary text attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_THL_PANTHEON','PER_MODERN_OCCULT','The collective of deities and praeterhuman intelligences central to Aleister Crowley''s Thelema as set out in Liber AL vel Legis (1904) and its surrounding corpus.'),
 ('ENT_THL_HOOR_PAAR_KRAAT','PER_MODERN_OCCULT','The silent passive twin of Ra-Hoor-Khuit, the god of silence; a Thelemic adaptation of Harpocrates forming a polarity with the active conquering child.'),
 ('ENT_THL_BABALON','PER_MODERN_OCCULT','The Thelemic Great Mother and sacred-whore goddess riding the Beast, developed by Crowley (notably in The Vision and the Voice) as a redemptive reframing of the biblical Whore of Babylon.'),
 ('ENT_THL_THERION','PER_MODERN_OCCULT','To Mega Therion, ''The Great Beast 666,'' Crowley''s prophetic magical office and consort of Babalon; an affirmative reclamation of the apocalyptic Beast of Revelation.'),
 ('ENT_THL_CHORONZON','PER_MODERN_OCCULT','The demon and ''dweller in the Abyss'' encountered in the 10th Aethyr; first named in John Dee''s Enochian records and greatly developed by Crowley into the Thelemic embodiment of dispersion.'),
 ('ENT_THL_HGA','PER_MODERN_OCCULT','The Thelemic/Abramelin concept of the individual''s tutelary genius or true higher self, whose ''Knowledge and Conversation'' is the central attainment; adopted from the Book of Abramelin and recast by Crowley, who identified Aiwass as his own HGA.'),
 ('ENT_THL_AEON_HORUS','PER_MODERN_OCCULT','The current cosmic age inaugurated in 1904 according to Thelema, succeeding the Aeons of Isis and Osiris and governed by Ra-Hoor-Khuit; modeled as an era rather than a being.'),
 ('ENT_THE_HIERARCHY','PER_MODERN_OCCULT','The graded hierarchy of spiritual beings — the Masters, the Lord of the World, the Logoi, and the Lords of Karma — said in Theosophy to oversee human and planetary evolution.'),
 ('ENT_THE_MORYA','PER_MODERN_OCCULT','Master Morya, one of the Mahatmas said to stand behind the Theosophical Society and to have corresponded with Blavatsky; a being original to the modern Theosophical movement.'),
 ('ENT_THE_KOOT_HOOMI','PER_MODERN_OCCULT','Master Koot Hoomi (Kuthumi), one of the principal Mahatmas of Theosophy and chief author of the Mahatma Letters; a being original to the modern Theosophical movement.'),
 ('ENT_THE_DJWAL_KHUL','PER_MODERN_OCCULT','Master Djwal Khul, ''the Tibetan,'' a Mahatma later said to have telepathically dictated the books written through Alice Bailey; a being of the modern Theosophical tradition.'),
 ('ENT_THE_MAHA_CHOHAN','PER_MODERN_OCCULT','The ''Great Lord,'' chief of the third ray and head of the Masters'' hierarchy of civilization in Theosophical teaching; a being original to the modern Theosophical movement.'),
 ('ENT_THE_SANAT_KUMARA','PER_MODERN_OCCULT','The ''Lord of the World'' and ''Ancient of Days'' said to dwell at Shamballa and govern Earth''s spiritual evolution; a Theosophical adaptation of the Hindu Kumara name into a modern cosmic office.'),
 ('ENT_THE_SOLAR_LOGOS','PER_MODERN_OCCULT','The Theosophical conception of the divine intelligence ensouling and governing the entire solar system, developed within the modern revival from the Greek philosophical Logos.'),
 ('ENT_THE_PLANETARY_LOGOS','PER_MODERN_OCCULT','The Theosophical divine intelligence ensouling a single planet, subordinate to the Solar Logos; a modern-revival cosmological office.'),
 ('ENT_THE_LIPIKA','PER_MODERN_OCCULT','The Lipika, the ''recorders'' or Lords of Karma described in Blavatsky''s The Secret Doctrine who register every act and administer the law of karma; a collective being of modern Theosophical cosmology.'),
 ('ENT_THE_ROOT_RACES','PER_MODERN_OCCULT','The series of seven successive cosmological humanities (Lemurian, Atlantean, Aryan, ...) through which spirit evolves in The Secret Doctrine; modeled as a single collective rather than seven entities.'),
 ('ENT_MOD_GOLDEN_DAWN','PER_MODERN_OCCULT','The influential English initiatory magical order founded in 1888 that synthesized Qabalah, Enochian, Egyptian, and Tarot systems; a synthesizing framework rather than a source of new beings.'),
 ('ENT_MOD_SECRET_CHIEFS','PER_MODERN_OCCULT','The hidden Third-Order adepts said to direct the Hermetic Order of the Golden Dawn through its leaders (notably claimed by Mathers); a concept paralleling and influenced by the Theosophical Masters.');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_THL_NUIT','member_of','ENT_THL_PANTHEON','high','Nuit is one of the principal deities of Liber AL vel Legis.'),
 ('ENT_THL_HADIT','member_of','ENT_THL_PANTHEON','high','Hadit is one of the principal deities of Liber AL vel Legis.'),
 ('ENT_THL_RA_HOOR_KHUIT','member_of','ENT_THL_PANTHEON','high','Ra-Hoor-Khuit is one of the principal deities of Liber AL vel Legis.'),
 ('ENT_THL_AIWASS','member_of','ENT_THL_PANTHEON','high','Aiwass, the intelligence who dictated Liber AL, is central to the Thelemic pantheon.'),
 ('ENT_THL_HOOR_PAAR_KRAAT','member_of','ENT_THL_PANTHEON','high','Hoor-paar-kraat is the silent twin within the Thelemic godhead.'),
 ('ENT_THL_BABALON','member_of','ENT_THL_PANTHEON','high','Babalon is a central deity of the Thelemic corpus.'),
 ('ENT_THL_THERION','member_of','ENT_THL_PANTHEON','high','Therion/The Beast 666 is a central figure of the Thelemic corpus.'),
 ('ENT_THL_CHORONZON','member_of','ENT_THL_PANTHEON','high','Choronzon is the Thelemic demon of the Abyss within the system.'),
 ('ENT_THL_HOOR_PAAR_KRAAT','reception_of','ENT_SYN_HARPOCRATES','high','Hoor-paar-kraat is the Thelemic form of the Greco-Egyptian Harpocrates.'),
 ('ENT_THL_BABALON','reception_of','ENT_CHR_WHORE_BABYLON','high','Babalon is Crowley''s reframing of the biblical Whore of Babylon.'),
 ('ENT_THL_THERION','reception_of','ENT_CHR_BEAST','high','Therion/The Beast 666 is Crowley''s reclamation of the apocalyptic Beast of Revelation.'),
 ('ENT_THL_CHORONZON','reception_of','ENT_REN_ENOCHIAN','high','Choronzon was first named in John Dee''s Enochian records and later developed by Crowley.'),
 ('ENT_THL_BABALON','consort_of','ENT_THL_THERION','high','Babalon and Therion (the Beast) are the paired feminine and masculine principles of the new aeon.'),
 ('ENT_THL_HOOR_PAAR_KRAAT','paired_with','ENT_THL_RA_HOOR_KHUIT','high','Hoor-paar-kraat is the silent passive twin of the active Ra-Hoor-Khuit, two aspects of Heru-ra-ha.'),
 ('ENT_THL_RA_HOOR_KHUIT','presides_over','ENT_WAR','high','Ra-Hoor-Khuit is the warlike crowned-and-conquering lord of force and vengeance.'),
 ('ENT_THL_THERION','presides_over','ENT_MAGIC','medium','Therion is Crowley''s prophetic magical office central to the practice of magick.'),
 ('ENT_THL_CHORONZON','presides_over','ENT_DESTRUCTION','medium','Choronzon is the power of dispersion and dissolution at the Abyss.'),
 ('ENT_THL_AIWASS','presides_over','ENT_REVELATION','high','Aiwass is the intelligence who delivered the revelation of Liber AL.'),
 ('ENT_THL_AIWASS','aligned_with','ENT_THL_HGA','medium','Crowley identified Aiwass as his own Holy Guardian Angel.'),
 ('ENT_THL_RA_HOOR_KHUIT','rules','ENT_THL_AEON_HORUS','high','Ra-Hoor-Khuit is the lord governing the Aeon of Horus.'),
 ('ENT_THE_MORYA','member_of','ENT_REC_MAHATMAS','high','Morya is one of the Mahatmas (Theosophical Masters of Wisdom).'),
 ('ENT_THE_KOOT_HOOMI','member_of','ENT_REC_MAHATMAS','high','Koot Hoomi is one of the Mahatmas.'),
 ('ENT_THE_DJWAL_KHUL','member_of','ENT_REC_MAHATMAS','high','Djwal Khul is one of the Mahatmas.'),
 ('ENT_THE_MAHA_CHOHAN','member_of','ENT_REC_MAHATMAS','high','The Maha Chohan heads a department within the Mahatmas'' hierarchy.'),
 ('ENT_REC_MAHATMAS','member_of','ENT_THE_HIERARCHY','high','The Mahatmas form the human-adept tier of the Theosophical Spiritual Hierarchy.'),
 ('ENT_THE_SANAT_KUMARA','member_of','ENT_THE_HIERARCHY','high','Sanat Kumara, the Lord of the World, heads the Theosophical Spiritual Hierarchy.'),
 ('ENT_THE_SOLAR_LOGOS','member_of','ENT_THE_HIERARCHY','high','The Solar Logos stands at the cosmic apex of the Theosophical hierarchy.'),
 ('ENT_THE_PLANETARY_LOGOS','member_of','ENT_THE_HIERARCHY','high','The Planetary Logos governs Earth within the hierarchy, subordinate to the Solar Logos.'),
 ('ENT_THE_LIPIKA','member_of','ENT_THE_HIERARCHY','high','The Lords of Karma administer the law of karma within the cosmic hierarchy.'),
 ('ENT_THE_ROOT_RACES','member_of','ENT_THE_HIERARCHY','medium','The Root Races are the evolving humanities overseen by the Spiritual Hierarchy.'),
 ('ENT_THE_SANAT_KUMARA','presides_over','ENT_HIDDEN_KNOWLEDGE','medium','As Lord of the World at Shamballa, Sanat Kumara governs the spiritual evolution overseen by the hidden hierarchy.'),
 ('ENT_REC_MAHATMAS','presides_over','ENT_HIDDEN_KNOWLEDGE','high','The Masters of the Ancient Wisdom are the custodians of hidden wisdom in Theosophy.'),
 ('ENT_THE_LIPIKA','presides_over','ENT_DEATH','low','The Lords of Karma administer the cycle of death and rebirth, though their domain is karma broadly.'),
 ('ENT_MOD_SECRET_CHIEFS','member_of','ENT_MOD_GOLDEN_DAWN','high','The Secret Chiefs are the hidden Third Order said to direct the Golden Dawn.'),
 ('ENT_MOD_GOLDEN_DAWN','presides_over','ENT_MAGIC','high','The Golden Dawn was the foremost order of ceremonial magic in the modern revival.'),
 ('ENT_MOD_SECRET_CHIEFS','presides_over','ENT_HIDDEN_KNOWLEDGE','medium','The Secret Chiefs are the hidden source of authority and knowledge directing the Golden Dawn.'),
 ('ENT_MOD_GOLDEN_DAWN','reception_of','ENT_REN_ENOCHIAN','high','The Golden Dawn incorporated John Dee''s Enochian system into its synthesis.'),
 ('ENT_MOD_SECRET_CHIEFS','aligned_with','ENT_REC_MAHATMAS','medium','The Secret Chiefs parallel and were influenced by the Theosophical Masters.');

\echo '--- REJECTED edges (bad id/type/source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
