-- v2.1.86  Grimal, Concise Dictionary of Classical Mythology (1990): SECONDARY headword excerpts/pointers for under-sourced Greek/Roman entities
-- In-copyright dictionary: brief attributed opening-definition excerpts (Renard precedent) or NULL pointers; each excerpt gated as a
-- contiguous substring of the extraction; soft-hyphen/column-bleed/page-number spans rejected. INSERT only; existing citations PRESERVED.
BEGIN;

INSERT INTO sources (source_id, title, url, source_type, scope) VALUES ('SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', '', 'secondary scholarship (dictionary)', 'NEW - concise headword dictionary of Greek and Roman mythology; brief headword excerpts/pointers for under-sourced Greek/Roman entities') ON CONFLICT (source_id) DO NOTHING;

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_HYBRIS_GRIMAL', 'ENT_HYBRIS', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Hybris"', NULL, 'secondary', 'Grimal''s entry on the personification Hybris (''the personification of lack of restraint and of insolence''); the opening sentence has a soft-hyphen line break in the extraction, so pointer only.', DATE '2026-09-18', 'headword entry confirmed in the pdftotext extraction but its text is column-bled/OCR-broken; NO text reproduced - pointer only', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_HYBRIS_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_POINE_GRIMAL', 'ENT_POINE', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Poine"', 'Poine (Ποινή) The personification of Vengeance or Punishment;', 'secondary', 'Grimal''s entry on Poine.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_POINE_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_POLYDEUCES_GRIMAL', 'ENT_POLYDEUCES', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Polydeuces"', 'Polydeuces (Πολυδεύκης) The Greek form of Pollux, one of the DIOSCURI.', 'secondary', 'Grimal''s entry on Polydeuces.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_POLYDEUCES_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_POTHOS_GRIMAL', 'ENT_POTHOS', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Pothos"', 'He appears in Aphrodite''s retinue beside Eros and Himerus. He was said to be a son of Aphrodite.', 'secondary', 'Grimal''s entry on Pothos (the personification of desire).', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_POTHOS_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ROM_ANNA_PERENNA_GRIMAL', 'ENT_ROM_ANNA_PERENNA', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Anna Perenna"', 'Anna Perenna A Roman goddess worshipped in a sacred wood on the Via Flaminia.', 'secondary', 'Grimal''s entry on Anna Perenna.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ROM_ANNA_PERENNA_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ROM_FIDES_GRIMAL', 'ENT_ROM_FIDES', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Fides"', 'Fides The Roman personification of Good Faith.', 'secondary', 'Grimal''s entry on Fides.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ROM_FIDES_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ROM_LARES_GRIMAL', 'ENT_ROM_LARES', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Lares"', NULL, 'secondary', 'Grimal''s entry on the Lares (opening sentence has soft-hyphen breaks in the extraction).', DATE '2026-09-18', 'headword entry confirmed in the pdftotext extraction but its text is column-bled/OCR-broken; NO text reproduced - pointer only', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ROM_LARES_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ROM_PAX_GRIMAL', 'ENT_ROM_PAX', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Pax"', 'Pax The personification of Peace at Rome.', 'secondary', 'Grimal''s entry on Pax.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ROM_PAX_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ROM_PIETAS_GRIMAL', 'ENT_ROM_PIETAS', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Pietas"', 'Pietas The personification of feelings of duty towards the gods, the state and one''s family.', 'secondary', 'Grimal''s entry on Pietas.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ROM_PIETAS_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ROM_ROBIGUS_GRIMAL', 'ENT_ROM_ROBIGUS', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Robigo"', 'Robigo and Robigus were two divinities, the first feminine, the second masculine, which watched over the growing wheat and averted blight (robigo in Latin).', 'secondary', 'Grimal''s entry (under Robigo) on Robigus/Robigo.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ROM_ROBIGUS_GRIMAL');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_ROM_ROBIGUS', 'Robigo', 'spelling variant (Grimal)', 'SRC_GRIMAL_CONCISE', 'high', 'needs_review', 'Grimal, Concise Dictionary of Classical Mythology'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_ROM_ROBIGUS' AND alias_name='Robigo');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ROM_SALUS_GRIMAL', 'ENT_ROM_SALUS', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Salus"', 'Salus In Rome the personification of health and preservation in general. She had a temple on the Quirinal.', 'secondary', 'Grimal''s entry on Salus.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ROM_SALUS_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ROM_SUMMANUS_GRIMAL', 'ENT_ROM_SUMMANUS', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Summanus"', 'he was the god of the nocturnal heaven. A statue of Summanus existed on the temple of Jupiter on the Capitol', 'secondary', 'Grimal''s entry on Summanus.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ROM_SUMMANUS_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ROM_TELLUS_GRIMAL', 'ENT_ROM_TELLUS', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Tellus"', 'Tellus The personification of the productive power of the earth in Rome.', 'secondary', 'Grimal''s entry on Tellus.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ROM_TELLUS_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ROM_VACUNA_GRIMAL', 'ENT_ROM_VACUNA', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Vacuna"', 'Vacuna An ancient Sabine goddess who had a sanctuary near Horace''s villa.', 'secondary', 'Grimal''s entry on Vacuna.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ROM_VACUNA_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ROM_VEIOVIS_GRIMAL', 'ENT_ROM_VEIOVIS', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Veiovis"', 'Veiovis A Roman god, identified with Apollo, who had an ancient shrine on the Capitol and another on the Insula Tiberina.', 'secondary', 'Grimal''s entry on Veiovis.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ROM_VEIOVIS_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ROM_VERTUMNUS_GRIMAL', 'ENT_ROM_VERTUMNUS', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Vertumnus"', 'Vertumnus A god who had a statue in Rome in the Etruscan district at the entrance to the Forum.', 'secondary', 'Grimal''s entry on Vertumnus.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ROM_VERTUMNUS_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_CERBERUS_GRIMAL', 'ENT_CERBERUS', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Cerberus"', 'Cerberus (Κέρβερος) The dog of Hades. He watched over the realm of the dead and forbade living people to enter it, and prevented the dead from leaving it.', 'secondary', 'Grimal''s entry on Cerberus.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_CERBERUS_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_MON_ECHIDNA_GRIMAL', 'ENT_MON_ECHIDNA', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Echidna"', 'A monster with the torso of a woman and a serpent''s tail instead of legs.', 'secondary', 'Grimal''s entry on Echidna (Greek headword OCR-garbled; definition quoted).', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_MON_ECHIDNA_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_MON_GRAEAE_GRIMAL', 'ENT_MON_GRAEAE', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Graeae"', 'Graeae (Γραΐαι) The ''Old Women'', who had never been young, and were born old.', 'secondary', 'Grimal''s entry on the Graeae.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_MON_GRAEAE_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_MON_HARPIES_GRIMAL', 'ENT_MON_HARPIES', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Harpies"', 'The Harpies (''the Snatchers'') were winged demons,', 'secondary', 'Grimal''s entry on the Harpies (continuation has a soft-hyphen break).', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_MON_HARPIES_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_CABEIRI_GRIMAL', 'ENT_CABEIRI', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Cabiri"', 'Cabiri (Κάβειροι) Divinities whose main shrine was at Samothrace.', 'secondary', 'Grimal''s entry on the Cabiri.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_CABEIRI_GRIMAL');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_CABEIRI', 'Cabiri', 'spelling variant (Grimal)', 'SRC_GRIMAL_CONCISE', 'high', 'needs_review', 'Grimal, Concise Dictionary of Classical Mythology'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_CABEIRI' AND alias_name='Cabiri');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_GREAT_GODS_SAMOTHRACE_GRIMAL', 'ENT_GREAT_GODS_SAMOTHRACE', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Cabiri"', 'Cabiri (Κάβειροι) Divinities whose main shrine was at Samothrace.', 'secondary', 'Grimal treats the Great Gods of Samothrace under the headword Cabiri.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_GREAT_GODS_SAMOTHRACE_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_LAMIA_GRIMAL', 'ENT_LAMIA', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Lamia (2)"', 'A female monster who was said to steal children and was a terror to nurses.', 'secondary', 'Grimal''s entry Lamia (2), the child-stealing monster (Lamia (1) is the mother of the Libyan Sibyl).', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_LAMIA_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_HYMENAIOS_GRIMAL', 'ENT_HYMENAIOS', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Hymenaeus"', 'Hymenaeus (Ύμέναιος) The god who led the wedding procession.', 'secondary', 'Grimal''s entry on Hymenaeus.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_HYMENAIOS_GRIMAL');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_HYMENAIOS', 'Hymenaeus', 'spelling variant (Grimal)', 'SRC_GRIMAL_CONCISE', 'high', 'needs_review', 'Grimal, Concise Dictionary of Classical Mythology'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_HYMENAIOS' AND alias_name='Hymenaeus');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_IASO_GRIMAL', 'ENT_IASO', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Iaso"', 'Iaso (Ίασώ) The healer, said to be a daughter of Asclepius and a sister of Hygieia. Her sanctuary was at Oropus.', 'secondary', 'Grimal''s entry on Iaso.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_IASO_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_DAEDALUS_GRIMAL', 'ENT_DAEDALUS', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Daedalus"', 'Daedalus (Δαίδαλος) An Athenian descended from Cecrops. Daedalus was a skilled artist, architect, sculptor and inventor.', 'secondary', 'Grimal''s entry on Daedalus.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_DAEDALUS_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ARISTAEUS_GRIMAL', 'ENT_ARISTAEUS', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Aristaeus"', 'he saw the Nymph Cyrene and transported her to Libya where she bore him a son named Aristaeus.', 'secondary', 'Grimal''s entry on Aristaeus.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ARISTAEUS_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_NOTUS_GRIMAL', 'ENT_NOTUS', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Notus"', 'Notus (Νότος) The god of the South Wind, a warm and very moist wind. He was the son of Eos and Astraeus.', 'secondary', 'Grimal''s entry on Notus.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_NOTUS_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_EUMENIDES_GRIMAL', 'ENT_EUMENIDES', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Eumenides"', NULL, 'secondary', 'Grimal''s entry on the Eumenides (''the gracious goddesses, a euphemism for the ERINYES''); opening has a soft-hyphen break and garbled Greek, so pointer only.', DATE '2026-09-18', 'headword entry confirmed in the pdftotext extraction but its text is column-bled/OCR-broken; NO text reproduced - pointer only', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_EUMENIDES_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ROM_SEMO_SANCUS_GRIMAL', 'ENT_ROM_SEMO_SANCUS', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Sancus"', 'Sancus His full name was Semo Sancus, a divinity of the earliest Roman religion.', 'secondary', 'Grimal''s entry on Semo Sancus.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ROM_SEMO_SANCUS_GRIMAL');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_ROM_SEMO_SANCUS', 'Sancus', 'spelling variant (Grimal)', 'SRC_GRIMAL_CONCISE', 'high', 'needs_review', 'Grimal, Concise Dictionary of Classical Mythology'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_ROM_SEMO_SANCUS' AND alias_name='Sancus');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ROM_JUNO_GRIMAL', 'ENT_ROM_JUNO', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Juno"', 'Juno The Roman equivalent of HERA. Originally she was one of the three divinities honoured on the Quirinal and then on the Capitol, namely Jupiter, Juno and Minerva.', 'secondary', 'Grimal''s entry on Juno.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ROM_JUNO_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ROM_VULCAN_GRIMAL', 'ENT_ROM_VULCAN', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Vulcan"', 'He was said to have been introduced to Rome by Titus Tatius, but there was a tradition which attributes the construction of his first shrine to Romulus.', 'secondary', 'Grimal''s entry on Vulcan (opening sentence has an inline page number in the extraction and was rejected).', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ROM_VULCAN_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ROM_PENATES_GRIMAL', 'ENT_ROM_PENATES', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Penates"', 'Penates Roman deities who guarded hearth and home. They were often associated with Vesta, but they remained distinct from the LARES.', 'secondary', 'Grimal''s entry on the Penates.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ROM_PENATES_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ROM_POMONA_GRIMAL', 'ENT_ROM_POMONA', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Pomona"', 'Pomona The Roman Nymph of fruit. She had a sacred wood, the Pomonal, on the road from Rome to Ostia.', 'secondary', 'Grimal''s entry on Pomona.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ROM_POMONA_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ROM_CONCORDIA_GRIMAL', 'ENT_ROM_CONCORDIA', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Homonoia"', 'she had an altar at Olympia. In Rome she was called Concordia.', 'secondary', 'Grimal treats Concordia under Homonoia.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ROM_CONCORDIA_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_HOMONOIA_GRIMAL', 'ENT_HOMONOIA', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Homonoia"', 'she had an altar at Olympia. In Rome she was called Concordia.', 'secondary', 'Grimal''s entry on Homonoia (opening has a soft-hyphen break).', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_HOMONOIA_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_AMALTHEIA_GRIMAL', 'ENT_AMALTHEIA', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Amalthea"', 'The nurse who brought up Zeus in secrecy on Mount Ida in Crete when Cronus wanted to eat him.', 'secondary', 'Grimal''s entry on Amalthea.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_AMALTHEIA_GRIMAL');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_AMALTHEIA', 'Amalthea', 'spelling variant (Grimal)', 'SRC_GRIMAL_CONCISE', 'high', 'needs_review', 'Grimal, Concise Dictionary of Classical Mythology'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_AMALTHEIA' AND alias_name='Amalthea');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_OPHION_GRIMAL', 'ENT_OPHION', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Ophion"', 'Ophion and his female companion, Eurynome, reigned over the Titans', 'secondary', 'Grimal''s entry on Ophion.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_OPHION_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_EURYNOME_PRIMORDIAL_GRIMAL', 'ENT_EURYNOME_PRIMORDIAL', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Ophion"', 'Ophion and his female companion, Eurynome, reigned over the Titans', 'secondary', 'Grimal names the primordial Eurynome, consort of Ophion, in the Ophion entry (the Eurynome headword itself is column-bled).', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_EURYNOME_PRIMORDIAL_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_MON_ORTHRUS_GRIMAL', 'ENT_MON_ORTHRUS', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Orthrus"', 'He was the offspring of Typhon and Echidna and therefore brother of Cerberus. By mating with Echidna, he fathered the Theban Sphinx.', 'secondary', 'Grimal''s entry on Orthrus.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_MON_ORTHRUS_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_MON_GIGANTES_GRIMAL', 'ENT_MON_GIGANTES', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Giants"', 'Giants (Γίγαντες) The children of GAIA, born from the blood of her husband Uranus', 'secondary', 'Grimal''s entry on the Giants.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located at line start and read to confirm the referent is THIS figure; brief attributed excerpt of the entry''s opening definition (in-copyright dictionary); spans containing soft-hyphen line breaks, column bleed or inline page numbers were rejected; contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_MON_GIGANTES_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_MON_HECATONCHEIRES_GRIMAL', 'ENT_MON_HECATONCHEIRES', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Hecatoncheires"', NULL, 'secondary', 'Grimal''s entry on the Hecatoncheires; column-bled in the scan, pointer only.', DATE '2026-09-18', 'headword entry confirmed in the pdftotext extraction but its text is column-bled/OCR-broken; NO text reproduced - pointer only', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_MON_HECATONCHEIRES_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_CECROPS_GRIMAL', 'ENT_CECROPS', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Cecrops (1)"', NULL, 'secondary', 'Grimal''s entry Cecrops (1), the mythical first king of Attica; column-bled, pointer only.', DATE '2026-09-18', 'headword entry confirmed in the pdftotext extraction but its text is column-bled/OCR-broken; NO text reproduced - pointer only', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_CECROPS_GRIMAL');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ION_GRIMAL', 'ENT_ION', 'SRC_GRIMAL_CONCISE', 'Pierre Grimal, The Concise Dictionary of Classical Mythology, ed. Stephen Kershaw, trans. A. R. Maxwell-Hyslop (Oxford: Blackwell, 1990)', 's.v. "Ion"', NULL, 'secondary', 'Grimal''s entry on Ion, eponym of the Ionians; column-bled, pointer only.', DATE '2026-09-18', 'headword entry confirmed in the pdftotext extraction but its text is column-bled/OCR-broken; NO text reproduced - pointer only', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Grimal', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ION_GRIMAL');

COMMIT;
