-- build_p4_continental_germanic.sql  (GENERATED by gen_roster.py p4_continental_germanic) — v1.80.0
-- 14 entities, 21 edges, 1 new periods, 1 new sources. Idempotent + self-validating.
BEGIN;

INSERT INTO periods (period_id, period_name, start_year, end_year) VALUES
 ('PER_CONTINENTAL_GERMANIC','Continental (Romano-)Germanic',-100,400)
ON CONFLICT (period_id) DO NOTHING;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_SIMEK_NORTHERN','secondary scholarship','Rudolf Simek, Dictionary of Northern Mythology (trans. A. Hall, D. S. Brewer, 1993)','Reuse: standard reference for the Matronae and Continental Germanic deities.')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,trad text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_CGE_PANTHEON','Continental Germanic Pantheon','collective','collective','Continental Germanic','pantheon','B','Hub collective for the Romano-Germanic deities of the Rhineland and Low Countries attested in votive inscriptions; modeling construct.'),
 ('ENT_CGE_MATRONAE','Matronae','collective','collective','Continental Germanic','motherhood, fertility, protection','B','The triple mother-goddesses of the Rhineland, attested on >1,000 votive stones (1st-4th c. CE), typically depicted as three seated women; named in numerous cult-epithet groups.'),
 ('ENT_CGE_MATRONAE_AUFANIAE','Matronae Aufaniae','deity','deity','Continental Germanic','motherhood, protection','B','Among the most-attested Matronae groups, centered on Bonn and Nettersheim; numerous inscriptions, esp. 2nd-3rd c. CE.'),
 ('ENT_CGE_MATRONAE_VACALLINEHAE','Matronae Vacallinehae','deity','deity','Continental Germanic','motherhood, protection','B','Matronae group worshipped chiefly at the large sanctuary of Pesch in the Eifel; ~150 inscriptions there.'),
 ('ENT_CGE_MATRONAE_GABIAE','Matronae Gabiae','deity','deity','Continental Germanic','motherhood, giving, abundance','B','Matronae group whose name relates to Germanic *geban ''to give''; cf. the Norse Gefjon/Gefn; attested in the Rhineland.'),
 ('ENT_CGE_MATRONAE_SULEVIAE','Matronae Suleviae / Suleviae','deity','deity','Continental Germanic','motherhood, household, protection','C','Mother/protective goddesses (Suleviae) attested across the Roman provinces incl. the Germanic Rhineland; ambiguously Celtic-Germanic, often grouped with the Matronae.'),
 ('ENT_CGE_NEHALENNIA','Nehalennia','deity','deity','Continental Germanic','seafaring, trade, protection, fertility','B','Goddess of seafarers and traders attested by ~160 votive altars at Domburg and Colijnsplaat (Zeeland), shown with dog, basket of fruit, and ship''s prow; 2nd-3rd c. CE.'),
 ('ENT_CGE_HERCULES_MAGUSANUS','Hercules Magusanus','deity','deity','Continental Germanic','strength, protection, war','B','Romano-Germanic god of the Batavians, an interpretatio Romana equating a native (Donar-like) hero with Hercules; widely attested in Lower Germany, 1st-3rd c. CE.'),
 ('ENT_CGE_BADUHENNA','Baduhenna','deity','deity','Continental Germanic','war, battle','C','Frisian goddess named by Tacitus (Annals IV.73) in connection with a sacred grove (lucus Baduhennae) where Roman soldiers were slain in 28 CE; name linked to *badwa ''battle''.'),
 ('ENT_CGE_TANFANA','Tanfana','deity','deity','Continental Germanic','fertility, cult-place','C','Goddess of the Marsi whose temple Germanicus destroyed (Tacitus, Annals I.51, 14 CE); a votive inscription also attests her; otherwise obscure.'),
 ('ENT_CGE_HLUDANA','Hludana','deity','deity','Continental Germanic','fertility, protection','C','Goddess attested by five inscriptions from the Lower Rhine/Frisian region; name often linked etymologically to Norse Hlodyn (an epithet of Jord, Thor''s mother).'),
 ('ENT_CGE_SANDRAUDIGA','Sandraudiga','deity','deity','Continental Germanic','fertility, abundance','C','Goddess known from a single votive altar at Zundert (North Brabant); name interpreted as ''she who gives wealth/red sand''; otherwise unknown.'),
 ('ENT_CGE_VAGDAVERCUSTIS','Vagdavercustis','deity','deity','Continental Germanic','war, virtue, protection','C','Germanic goddess attested on altars from the Lower Rhine (notably Cologne-Deutz, dedicated by a Praetorian prefect); name possibly meaning ''martial excellence''.'),
 ('ENT_CGE_REQUALIVAHANUS','Requalivahanus','deity','deity','Continental Germanic','protection (obscure)','C','Male Germanic god attested by votive inscriptions at Pesch in the Eifel; function unknown, name obscure.');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'devotional',conf,'candidate_verified_name','Roster build via gen_roster.py (see CHANGELOG/git for release)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,etype text,note text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_CGE_PANTHEON','SRC_SIMEK_NORTHERN','scholarly attestation','attestation'),
 ('ENT_CGE_MATRONAE','SRC_SIMEK_NORTHERN','scholarly attestation','attestation'),
 ('ENT_CGE_MATRONAE_AUFANIAE','SRC_SIMEK_NORTHERN','scholarly attestation','attestation'),
 ('ENT_CGE_MATRONAE_VACALLINEHAE','SRC_SIMEK_NORTHERN','scholarly attestation','attestation'),
 ('ENT_CGE_MATRONAE_GABIAE','SRC_SIMEK_NORTHERN','scholarly attestation','attestation'),
 ('ENT_CGE_MATRONAE_SULEVIAE','SRC_SIMEK_NORTHERN','scholarly attestation','attestation'),
 ('ENT_CGE_NEHALENNIA','SRC_SIMEK_NORTHERN','scholarly attestation','attestation'),
 ('ENT_CGE_HERCULES_MAGUSANUS','SRC_SIMEK_NORTHERN','scholarly attestation','attestation'),
 ('ENT_CGE_BADUHENNA','SRC_SIMEK_NORTHERN','scholarly attestation','attestation'),
 ('ENT_CGE_TANFANA','SRC_SIMEK_NORTHERN','scholarly attestation','attestation'),
 ('ENT_CGE_HLUDANA','SRC_SIMEK_NORTHERN','scholarly attestation','attestation'),
 ('ENT_CGE_SANDRAUDIGA','SRC_SIMEK_NORTHERN','scholarly attestation','attestation'),
 ('ENT_CGE_VAGDAVERCUSTIS','SRC_SIMEK_NORTHERN','scholarly attestation','attestation'),
 ('ENT_CGE_REQUALIVAHANUS','SRC_SIMEK_NORTHERN','scholarly attestation','attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_CGE_PANTHEON','PER_CONTINENTAL_GERMANIC','Hub collective for the Romano-Germanic deities of the Rhineland and Low Countries attested in votive inscriptions; modeling construct.'),
 ('ENT_CGE_MATRONAE','PER_CONTINENTAL_GERMANIC','The triple mother-goddesses of the Rhineland, attested on >1,000 votive stones (1st-4th c. CE), typically depicted as three seated women; named in numerous cult-epithet groups.'),
 ('ENT_CGE_MATRONAE_AUFANIAE','PER_CONTINENTAL_GERMANIC','Among the most-attested Matronae groups, centered on Bonn and Nettersheim; numerous inscriptions, esp. 2nd-3rd c. CE.'),
 ('ENT_CGE_MATRONAE_VACALLINEHAE','PER_CONTINENTAL_GERMANIC','Matronae group worshipped chiefly at the large sanctuary of Pesch in the Eifel; ~150 inscriptions there.'),
 ('ENT_CGE_MATRONAE_GABIAE','PER_CONTINENTAL_GERMANIC','Matronae group whose name relates to Germanic *geban ''to give''; cf. the Norse Gefjon/Gefn; attested in the Rhineland.'),
 ('ENT_CGE_MATRONAE_SULEVIAE','PER_CONTINENTAL_GERMANIC','Mother/protective goddesses (Suleviae) attested across the Roman provinces incl. the Germanic Rhineland; ambiguously Celtic-Germanic, often grouped with the Matronae.'),
 ('ENT_CGE_NEHALENNIA','PER_CONTINENTAL_GERMANIC','Goddess of seafarers and traders attested by ~160 votive altars at Domburg and Colijnsplaat (Zeeland), shown with dog, basket of fruit, and ship''s prow; 2nd-3rd c. CE.'),
 ('ENT_CGE_HERCULES_MAGUSANUS','PER_CONTINENTAL_GERMANIC','Romano-Germanic god of the Batavians, an interpretatio Romana equating a native (Donar-like) hero with Hercules; widely attested in Lower Germany, 1st-3rd c. CE.'),
 ('ENT_CGE_BADUHENNA','PER_CONTINENTAL_GERMANIC','Frisian goddess named by Tacitus (Annals IV.73) in connection with a sacred grove (lucus Baduhennae) where Roman soldiers were slain in 28 CE; name linked to *badwa ''battle''.'),
 ('ENT_CGE_TANFANA','PER_CONTINENTAL_GERMANIC','Goddess of the Marsi whose temple Germanicus destroyed (Tacitus, Annals I.51, 14 CE); a votive inscription also attests her; otherwise obscure.'),
 ('ENT_CGE_HLUDANA','PER_CONTINENTAL_GERMANIC','Goddess attested by five inscriptions from the Lower Rhine/Frisian region; name often linked etymologically to Norse Hlodyn (an epithet of Jord, Thor''s mother).'),
 ('ENT_CGE_SANDRAUDIGA','PER_CONTINENTAL_GERMANIC','Goddess known from a single votive altar at Zundert (North Brabant); name interpreted as ''she who gives wealth/red sand''; otherwise unknown.'),
 ('ENT_CGE_VAGDAVERCUSTIS','PER_CONTINENTAL_GERMANIC','Germanic goddess attested on altars from the Lower Rhine (notably Cologne-Deutz, dedicated by a Praetorian prefect); name possibly meaning ''martial excellence''.'),
 ('ENT_CGE_REQUALIVAHANUS','PER_CONTINENTAL_GERMANIC','Male Germanic god attested by votive inscriptions at Pesch in the Eifel; function unknown, name obscure.');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_CGE_MATRONAE','member_of','ENT_CGE_PANTHEON','high','The Matronae collective belongs to the Continental Germanic religious sphere.'),
 ('ENT_CGE_NEHALENNIA','member_of','ENT_CGE_PANTHEON','high','Nehalennia is a Continental Germanic deity attested in the Low Countries.'),
 ('ENT_CGE_HERCULES_MAGUSANUS','member_of','ENT_CGE_PANTHEON','high','Hercules Magusanus is a Romano-Germanic Batavian deity.'),
 ('ENT_CGE_BADUHENNA','member_of','ENT_CGE_PANTHEON','high','Baduhenna is a Frisian (Continental Germanic) goddess.'),
 ('ENT_CGE_TANFANA','member_of','ENT_CGE_PANTHEON','high','Tanfana is a Continental Germanic goddess of the Marsi.'),
 ('ENT_CGE_HLUDANA','member_of','ENT_CGE_PANTHEON','high','Hludana is a Lower Rhine/Frisian Germanic goddess.'),
 ('ENT_CGE_SANDRAUDIGA','member_of','ENT_CGE_PANTHEON','high','Sandraudiga is a Continental Germanic goddess from Brabant.'),
 ('ENT_CGE_VAGDAVERCUSTIS','member_of','ENT_CGE_PANTHEON','high','Vagdavercustis is a Lower Rhine Germanic goddess.'),
 ('ENT_CGE_REQUALIVAHANUS','member_of','ENT_CGE_PANTHEON','high','Requalivahanus is a Continental Germanic god attested at Pesch.'),
 ('ENT_CGE_MATRONAE_AUFANIAE','member_of','ENT_CGE_MATRONAE','high','The Aufaniae are a named cult-group of the Matronae.'),
 ('ENT_CGE_MATRONAE_VACALLINEHAE','member_of','ENT_CGE_MATRONAE','high','The Vacallinehae are a named cult-group of the Matronae centered at Pesch.'),
 ('ENT_CGE_MATRONAE_GABIAE','member_of','ENT_CGE_MATRONAE','high','The Gabiae are a named cult-group of the Matronae.'),
 ('ENT_CGE_MATRONAE_SULEVIAE','member_of','ENT_CGE_MATRONAE','medium','The Suleviae are mother-goddesses frequently grouped with the Matronae in the Rhineland.'),
 ('ENT_CGE_REQUALIVAHANUS','associated_with','ENT_CGE_MATRONAE_VACALLINEHAE','medium','Requalivahanus and the Matronae Vacallinehae share the sanctuary cult-site of Pesch in the Eifel.'),
 ('ENT_CGE_MATRONAE','aligned_with','ENT_CEL_MATRES','high','The Germanic Matronae and the Celtic/Gaulish Matres/Matrones are the same triple-mother-goddess cult phenomenon across the Romano-provincial frontier (functional cognate).'),
 ('ENT_CGE_HERCULES_MAGUSANUS','equated_with','ENT_HERACLES','high','Hercules Magusanus is an interpretatio Romana that explicitly equates a native Germanic hero-god with the Greco-Roman Heracles/Hercules.'),
 ('ENT_CGE_HERCULES_MAGUSANUS','aligned_with','ENT_NOR_THOR','medium','Scholars connect the native god behind Hercules Magusanus with the thunder/strength god Donar, cognate of Norse Thor (Tacitus equated Germanic ''Hercules'' with the thunderer).'),
 ('ENT_CGE_HLUDANA','aligned_with','ENT_NOR_NERTHUS','low','Hludana is an earth/fertility goddess of the Germanic North Sea coast, broadly comparable to the earth-mother Nerthus; her name is also linked to the Norse earth-goddess epithet Hlodyn.'),
 ('ENT_CGE_MATRONAE_GABIAE','aligned_with','ENT_NOR_FRIGG','low','The Gabiae (''giving ones'') belong to the Germanic giving/fertility mother-goddess complex broadly aligned with Frigg and the Norse Gefjon (ENT_NOR_GEFJON).'),
 ('ENT_CGE_BADUHENNA','aligned_with','ENT_NOR_TYR','low','Baduhenna is a war/battle deity of the Frisii, sharing the Germanic martial-divinity sphere associated with Tiw/Tyr.'),
 ('ENT_CGE_NEHALENNIA','aligned_with','ENT_NOR_NERTHUS','low','Nehalennia is a coastal fertility/protective goddess of the Low Countries, broadly within the Germanic fertility-goddess sphere alongside Nerthus.');

\echo '--- REJECTED edges (bad id/type, or subject lacks a source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
