-- build_lds.sql  (GENERATED by gen_roster.py lds) — v1.80.0
-- 17 entities, 30 edges, 1 new periods, 3 new sources. Idempotent + self-validating.
BEGIN;

INSERT INTO periods (period_id, period_name, start_year, end_year) VALUES
 ('PER_LDS','Latter-day Saint / Restoration Era',1820,2025)
ON CONFLICT (period_id) DO NOTHING;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_GIVENS_WRESTLING','secondary scholarship','Terryl L. Givens, Wrestling the Angel: The Foundations of Mormon Thought — Cosmos, God, Humanity (Oxford University Press, 2015)','Standard scholarly synthesis of LDS theology: premortal existence, Godhead, Heavenly Father/Mother, exaltation/theosis, council in heaven, three degrees of glory.'),
 ('SRC_PEARL_GREAT_PRICE','primary text','The Pearl of Great Price (LDS canonical scripture: Book of Moses, Book of Abraham, Joseph Smith—History, Articles of Faith)','Primary source for Kolob, the council in heaven, the premortal council, Michael=Adam, the creation account, and Moroni''s appearances (Joseph Smith—History).'),
 ('SRC_LDS_DC','primary text','Doctrine and Covenants (LDS canonical scripture, 1835–)','Primary source for the three degrees of glory (Celestial/Terrestrial/Telestial, D&C 76 and 131), exaltation, and the identification of Michael as Adam (D&C 27, 107, 116).')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,trad text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_LDS_GODHEAD','The Godhead (LDS)','Divine collective','Godhead/principle','Latter-day Saint','supreme divinity; tritheistic unity of purpose','B','Canonical (Articles of Faith 1; D&C 130:22): three distinct personages — Father, Son, Holy Ghost — one in purpose, not one substance. Cohort hub.'),
 ('ENT_LDS_ELOHIM','Heavenly Father (Elohim)','Supreme deity','Creator deity','Latter-day Saint','exalted embodied Father of spirits; supreme God','B','Attested in LDS scripture and temple usage; an exalted, embodied, anthropomorphic God who was once a man (Givens, Wrestling the Angel). Distinct LDS conception, not the classical Trinity''s Father.'),
 ('ENT_LDS_HEAVENLY_MOTHER','Heavenly Mother','Mother goddess','Mother goddess','Latter-day Saint','divine feminine; mother of spirits; consort of Heavenly Father','B','Officially affirmed (Gospel Topics essay ''Mother in Heaven''; Eliza R. Snow hymn ''O My Father''); divine consort and co-parent of premortal spirits (Givens, Wrestling the Angel).'),
 ('ENT_LDS_JEHOVAH_CHRIST','Jehovah / Jesus Christ (LDS)','Messiah/incarnate Logos','Savior figure','Latter-day Saint','premortal Jehovah, creator under the Father, incarnate Redeemer','B','LDS framing identifies the premortal Jehovah of the Old Testament with Jesus Christ, the Firstborn spirit and Son who created the worlds under the Father (Givens; Bible Dictionary, ''Jehovah''). Cross-links to existing ENT_JESUS_CHRIST as the LDS reception.'),
 ('ENT_LDS_HOLY_GHOST','Holy Ghost (LDS)','Divine person','Divine person','Latter-day Saint','third member of the Godhead; personage of spirit; witness/revelator','B','Canonical (D&C 130:22): a personage of spirit without a body of flesh, distinct from the Father and Son. LDS reception of the Christian Holy Spirit.'),
 ('ENT_LDS_PREMORTAL_SPIRITS','Premortal Spirit Existence (Pre-existence)','Cosmological category','Cosmological realm','Latter-day Saint','premortal life of spirits as God''s children before birth','B','Doctrine of premortal existence: all humans lived as spirit children of Heavenly Parents before mortal birth (Givens; Book of Abraham 3; D&C 93:29).'),
 ('ENT_LDS_COUNCIL_HEAVEN','Council in Heaven','Cosmological process','Mythic process/category','Latter-day Saint','premortal divine council on the plan of salvation','B','Premortal council where the Father presented the plan of salvation; Jesus and Lucifer offered competing roles, leading to the War in Heaven (Book of Abraham 3; Book of Moses 4; Givens).'),
 ('ENT_LDS_MICHAEL_ADAM','Michael / Adam (LDS)','Archangel/exalted being','First human / Patriarch','Latter-day Saint','archangel Michael who became Adam, the first man and Ancient of Days','B','Canonical identification (D&C 27:11; 107:54; 116): the archangel Michael is Adam, the first man, the ''Ancient of Days'' who presides over his posterity. Cross-links to existing Adam and Michael anchors as LDS reception.'),
 ('ENT_LDS_MORONI','Moroni (Angel)','Revealer/angelic figure','Revealer','Latter-day Saint','resurrected Nephite prophet; angelic revealer of the golden plates','B','Joseph Smith—History (Pearl of Great Price): last Nephite prophet-historian, resurrected as the angel who revealed and delivered the golden plates from which the Book of Mormon was translated.'),
 ('ENT_LDS_LUCIFER','Lucifer / Perdition (LDS)','Adversarial being','Adversarial being','Latter-day Saint','premortal Son of the Morning who rebelled and became Satan','B','Book of Moses 4 and D&C 76:25–27: a spirit son of God in the premortal council who sought to supplant the plan and was cast out, becoming the devil and the sons of perdition.'),
 ('ENT_LDS_KOLOB','Kolob','Stellar god','Celestial sphere','Latter-day Saint','the star/realm nearest to the throne of God','B','Book of Abraham 3 and Facsimile 2: the great star/governing body nearest to where God resides, governing in time and order; a realm in LDS cosmology.'),
 ('ENT_LDS_DEGREES_GLORY','Three Degrees of Glory','Soteriological realm/category','Afterlife realm','Latter-day Saint','the tripartite kingdoms of eternal reward','B','D&C 76: the three postmortal kingdoms (Celestial, Terrestrial, Telestial) into which resurrected souls are assigned by glory; parent category of the three kingdoms.'),
 ('ENT_LDS_CELESTIAL_KINGDOM','Celestial Kingdom','Afterlife realm','Afterlife realm','Latter-day Saint','highest degree of glory; dwelling of God and the exalted','B','D&C 76:50–70, 131: the highest kingdom, where God and Christ dwell and where the exalted may attain godhood; likened to the glory of the sun.'),
 ('ENT_LDS_TERRESTRIAL_KINGDOM','Terrestrial Kingdom','Afterlife realm','Afterlife realm','Latter-day Saint','middle degree of glory','B','D&C 76:71–80: the middle kingdom for honorable people who did not receive the fulness of the gospel; likened to the glory of the moon.'),
 ('ENT_LDS_TELESTIAL_KINGDOM','Telestial Kingdom','Afterlife realm','Afterlife realm','Latter-day Saint','lowest degree of glory','B','D&C 76:81–90: the lowest of the three kingdoms of glory; likened to the glory of the stars.'),
 ('ENT_LDS_EXALTATION','Exaltation (Theosis)','Soteriological process/category','Soteriological process/category','Latter-day Saint','becoming gods; eternal increase in the Celestial Kingdom','B','Doctrine of exaltation/divinization: faithful Saints may attain godhood and eternal family increase (Lorenzo Snow couplet; D&C 132; Givens, Wrestling the Angel). LDS form of theosis.'),
 ('ENT_LDS_PLAN_SALVATION','Plan of Salvation','Doctrine','Soteriological/devotional category','Latter-day Saint','the divine plan of premortal, mortal, and postmortal progression','B','The overarching LDS doctrinal framework presented at the Council in Heaven, encompassing premortal life, mortality, and the degrees of glory (Givens; Book of Abraham 3).');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'devotional',conf,'candidate_verified_name','Roster build via gen_roster.py (see CHANGELOG/git for release)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,etype text,note text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_LDS_GODHEAD','SRC_GIVENS_WRESTLING','scholarly attestation','attestation'),
 ('ENT_LDS_ELOHIM','SRC_GIVENS_WRESTLING','scholarly attestation','attestation'),
 ('ENT_LDS_HEAVENLY_MOTHER','SRC_GIVENS_WRESTLING','scholarly attestation','attestation'),
 ('ENT_LDS_JEHOVAH_CHRIST','SRC_GIVENS_WRESTLING','scholarly attestation','attestation'),
 ('ENT_LDS_HOLY_GHOST','SRC_LDS_DC','primary text attestation','attestation'),
 ('ENT_LDS_PREMORTAL_SPIRITS','SRC_GIVENS_WRESTLING','scholarly attestation','attestation'),
 ('ENT_LDS_COUNCIL_HEAVEN','SRC_PEARL_GREAT_PRICE','primary text attestation','attestation'),
 ('ENT_LDS_MICHAEL_ADAM','SRC_LDS_DC','primary text attestation','attestation'),
 ('ENT_LDS_MORONI','SRC_PEARL_GREAT_PRICE','primary text attestation','attestation'),
 ('ENT_LDS_LUCIFER','SRC_PEARL_GREAT_PRICE','primary text attestation','attestation'),
 ('ENT_LDS_KOLOB','SRC_PEARL_GREAT_PRICE','primary text attestation','attestation'),
 ('ENT_LDS_DEGREES_GLORY','SRC_LDS_DC','primary text attestation','attestation'),
 ('ENT_LDS_CELESTIAL_KINGDOM','SRC_LDS_DC','primary text attestation','attestation'),
 ('ENT_LDS_TERRESTRIAL_KINGDOM','SRC_LDS_DC','primary text attestation','attestation'),
 ('ENT_LDS_TELESTIAL_KINGDOM','SRC_LDS_DC','primary text attestation','attestation'),
 ('ENT_LDS_EXALTATION','SRC_GIVENS_WRESTLING','scholarly attestation','attestation'),
 ('ENT_LDS_PLAN_SALVATION','SRC_GIVENS_WRESTLING','scholarly attestation','attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_LDS_GODHEAD','PER_LDS','Canonical (Articles of Faith 1; D&C 130:22): three distinct personages — Father, Son, Holy Ghost — one in purpose, not one substance. Cohort hub.'),
 ('ENT_LDS_ELOHIM','PER_LDS','Attested in LDS scripture and temple usage; an exalted, embodied, anthropomorphic God who was once a man (Givens, Wrestling the Angel). Distinct LDS conception, not the classical Trinity''s Father.'),
 ('ENT_LDS_HEAVENLY_MOTHER','PER_LDS','Officially affirmed (Gospel Topics essay ''Mother in Heaven''; Eliza R. Snow hymn ''O My Father''); divine consort and co-parent of premortal spirits (Givens, Wrestling the Angel).'),
 ('ENT_LDS_JEHOVAH_CHRIST','PER_LDS','LDS framing identifies the premortal Jehovah of the Old Testament with Jesus Christ, the Firstborn spirit and Son who created the worlds under the Father (Givens; Bible Dictionary, ''Jehovah''). Cross-links to existing ENT_JESUS_CHRIST as the LDS reception.'),
 ('ENT_LDS_HOLY_GHOST','PER_LDS','Canonical (D&C 130:22): a personage of spirit without a body of flesh, distinct from the Father and Son. LDS reception of the Christian Holy Spirit.'),
 ('ENT_LDS_PREMORTAL_SPIRITS','PER_LDS','Doctrine of premortal existence: all humans lived as spirit children of Heavenly Parents before mortal birth (Givens; Book of Abraham 3; D&C 93:29).'),
 ('ENT_LDS_COUNCIL_HEAVEN','PER_LDS','Premortal council where the Father presented the plan of salvation; Jesus and Lucifer offered competing roles, leading to the War in Heaven (Book of Abraham 3; Book of Moses 4; Givens).'),
 ('ENT_LDS_MICHAEL_ADAM','PER_LDS','Canonical identification (D&C 27:11; 107:54; 116): the archangel Michael is Adam, the first man, the ''Ancient of Days'' who presides over his posterity. Cross-links to existing Adam and Michael anchors as LDS reception.'),
 ('ENT_LDS_MORONI','PER_LDS','Joseph Smith—History (Pearl of Great Price): last Nephite prophet-historian, resurrected as the angel who revealed and delivered the golden plates from which the Book of Mormon was translated.'),
 ('ENT_LDS_LUCIFER','PER_LDS','Book of Moses 4 and D&C 76:25–27: a spirit son of God in the premortal council who sought to supplant the plan and was cast out, becoming the devil and the sons of perdition.'),
 ('ENT_LDS_KOLOB','PER_LDS','Book of Abraham 3 and Facsimile 2: the great star/governing body nearest to where God resides, governing in time and order; a realm in LDS cosmology.'),
 ('ENT_LDS_DEGREES_GLORY','PER_LDS','D&C 76: the three postmortal kingdoms (Celestial, Terrestrial, Telestial) into which resurrected souls are assigned by glory; parent category of the three kingdoms.'),
 ('ENT_LDS_CELESTIAL_KINGDOM','PER_LDS','D&C 76:50–70, 131: the highest kingdom, where God and Christ dwell and where the exalted may attain godhood; likened to the glory of the sun.'),
 ('ENT_LDS_TERRESTRIAL_KINGDOM','PER_LDS','D&C 76:71–80: the middle kingdom for honorable people who did not receive the fulness of the gospel; likened to the glory of the moon.'),
 ('ENT_LDS_TELESTIAL_KINGDOM','PER_LDS','D&C 76:81–90: the lowest of the three kingdoms of glory; likened to the glory of the stars.'),
 ('ENT_LDS_EXALTATION','PER_LDS','Doctrine of exaltation/divinization: faithful Saints may attain godhood and eternal family increase (Lorenzo Snow couplet; D&C 132; Givens, Wrestling the Angel). LDS form of theosis.'),
 ('ENT_LDS_PLAN_SALVATION','PER_LDS','The overarching LDS doctrinal framework presented at the Council in Heaven, encompassing premortal life, mortality, and the degrees of glory (Givens; Book of Abraham 3).');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_LDS_ELOHIM','member_of','ENT_LDS_GODHEAD','high','Heavenly Father (Elohim) is the first member of the LDS Godhead (Articles of Faith 1).'),
 ('ENT_LDS_JEHOVAH_CHRIST','member_of','ENT_LDS_GODHEAD','high','Jehovah/Jesus Christ is the second member of the LDS Godhead (D&C 130:22).'),
 ('ENT_LDS_HOLY_GHOST','member_of','ENT_LDS_GODHEAD','high','The Holy Ghost is the third member of the LDS Godhead (D&C 130:22).'),
 ('ENT_LDS_HEAVENLY_MOTHER','consort_of','ENT_LDS_ELOHIM','high','Heavenly Mother is the divine consort of Heavenly Father and co-parent of premortal spirits (Givens; Gospel Topics ''Mother in Heaven'').'),
 ('ENT_LDS_JEHOVAH_CHRIST','child_of','ENT_LDS_ELOHIM','high','Jesus Christ is the Firstborn spirit child and literal Son of Heavenly Father in LDS theology (Givens).'),
 ('ENT_LDS_JEHOVAH_CHRIST','child_of','ENT_LDS_HEAVENLY_MOTHER','medium','As all premortal spirits are children of Heavenly Parents, Jesus is the firstborn spirit child of the Heavenly Mother as well (Givens).'),
 ('ENT_LDS_LUCIFER','child_of','ENT_LDS_ELOHIM','high','Lucifer is a premortal spirit son of God who rebelled in the Council in Heaven (Book of Moses 4:1–4).'),
 ('ENT_LDS_LUCIFER','opposes','ENT_LDS_JEHOVAH_CHRIST','high','Lucifer offered a rival plan opposing Christ''s at the Council in Heaven and was cast out (Book of Moses 4; D&C 76:25–28).'),
 ('ENT_LDS_JEHOVAH_CHRIST','participates_in_creation','ENT_LDS_KOLOB','medium','Under the Father, the premortal Jehovah/Christ is the creator of the worlds; Kolob governs in the LDS cosmological order created in this framework (Book of Abraham 3–4).'),
 ('ENT_LDS_COUNCIL_HEAVEN','presided_over_by','ENT_LDS_ELOHIM','high','Heavenly Father presided over the premortal Council in Heaven where the plan of salvation was presented (Book of Abraham 3; Givens).'),
 ('ENT_LDS_PREMORTAL_SPIRITS','child_of','ENT_LDS_ELOHIM','high','All premortal spirits are the spirit children of Heavenly Father (Book of Abraham 3; D&C 93:29; Givens).'),
 ('ENT_LDS_PREMORTAL_SPIRITS','child_of','ENT_LDS_HEAVENLY_MOTHER','high','Premortal spirits are co-parented by the Heavenly Mother (Givens; hymn ''O My Father'').'),
 ('ENT_LDS_PREMORTAL_SPIRITS','participates_in_creation','ENT_LDS_COUNCIL_HEAVEN','medium','The premortal spirits, including the ''noble and great ones,'' participated in the Council in Heaven (Book of Abraham 3:22–28).'),
 ('ENT_LDS_COUNCIL_HEAVEN','member_of','ENT_LDS_PLAN_SALVATION','medium','The Council in Heaven is the premortal episode within the overarching Plan of Salvation where that plan was presented (Givens).'),
 ('ENT_LDS_PREMORTAL_SPIRITS','member_of','ENT_LDS_PLAN_SALVATION','medium','Premortal spirit existence is the first stage of the LDS Plan of Salvation (Givens).'),
 ('ENT_LDS_DEGREES_GLORY','member_of','ENT_LDS_PLAN_SALVATION','medium','The three degrees of glory are the postmortal reward stage of the Plan of Salvation (D&C 76; Givens).'),
 ('ENT_LDS_CELESTIAL_KINGDOM','member_of','ENT_LDS_DEGREES_GLORY','high','The Celestial Kingdom is the highest of the three degrees of glory (D&C 76).'),
 ('ENT_LDS_TERRESTRIAL_KINGDOM','member_of','ENT_LDS_DEGREES_GLORY','high','The Terrestrial Kingdom is the middle of the three degrees of glory (D&C 76).'),
 ('ENT_LDS_TELESTIAL_KINGDOM','member_of','ENT_LDS_DEGREES_GLORY','high','The Telestial Kingdom is the lowest of the three degrees of glory (D&C 76).'),
 ('ENT_LDS_ELOHIM','dwells_in','ENT_LDS_CELESTIAL_KINGDOM','high','God dwells in the Celestial Kingdom, the highest degree of glory (D&C 76:62, 92).'),
 ('ENT_LDS_KOLOB','dwelling_of','ENT_LDS_ELOHIM','medium','Kolob is the great governing star ''nearest unto the throne of God,'' i.e. the celestial body nearest God''s dwelling (Book of Abraham 3:2–3, 9; Facsimile 2). [QA FIX: replaced invalid ''member_of Godhead'' edge — Kolob is a realm, not a personage of the Godhead.]'),
 ('ENT_LDS_EXALTATION','member_of','ENT_LDS_PLAN_SALVATION','medium','Exaltation (godhood) is the culminating goal of the Plan of Salvation within the Celestial Kingdom (D&C 132; Givens).'),
 ('ENT_LDS_EXALTATION','belongs_to_realm','ENT_LDS_CELESTIAL_KINGDOM','high','Exaltation is attained only in the highest degree of the Celestial Kingdom (D&C 131:1–4).'),
 ('ENT_LDS_MICHAEL_ADAM','member_of','ENT_LDS_PREMORTAL_SPIRITS','medium','Michael/Adam was among the noble and great premortal spirits before becoming the first man (D&C 107:54; Book of Abraham 3).'),
 ('ENT_LDS_MORONI','member_of','ENT_LDS_PREMORTAL_SPIRITS','medium','Moroni, as a resurrected human prophet, was (like all humans) a premortal spirit child of Heavenly Parents before mortal birth (Givens; Book of Abraham 3). [QA FIX: replaced stretched ''reveals Godhead'' edge — Moroni revealed the golden plates, not ''the Godhead'' as an object.]'),
 ('ENT_LDS_ELOHIM','reception_of','ENT_CHR_GOD_FATHER','high','The LDS Heavenly Father (Elohim) is the Restorationist reception/reconception of the Christian God the Father — embodied and exalted rather than the classical Trinity (Givens).'),
 ('ENT_LDS_JEHOVAH_CHRIST','reception_of','ENT_JESUS_CHRIST','high','The LDS Jehovah/Jesus Christ is the Restorationist reception of the Christian Jesus, identifying him with the premortal Old Testament Jehovah (Bible Dictionary; Givens).'),
 ('ENT_LDS_HOLY_GHOST','reception_of','ENT_CHR_HOLY_SPIRIT','high','The LDS Holy Ghost is the Restorationist reception of the Christian Holy Spirit, reconceived as a distinct personage of spirit (D&C 130:22).'),
 ('ENT_LDS_MICHAEL_ADAM','reception_of','ENT_ISR_ADAM','high','LDS doctrine receives the biblical Adam and identifies him with the archangel Michael (D&C 27:11; 107:54).'),
 ('ENT_LDS_MICHAEL_ADAM','equated_with','ENT_SAINT_MICHAEL_CHR','high','LDS scripture explicitly equates the archangel Michael with Adam (D&C 116; 107:54); links to the Christian archangel Michael as the equated figure.');

\echo '--- REJECTED edges (bad id/type, or subject lacks a source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
