-- build_p3_carian.sql  (GENERATED by gen_roster.py p3_carian) — v1.80.0
-- 6 entities, 10 edges, 1 new periods, 1 new sources. Idempotent + self-validating.
BEGIN;

INSERT INTO periods (period_id, period_name, start_year, end_year) VALUES
 ('PER_CARIAN','Carian Civic Polytheism (Hekatomnid–Hellenistic Caria)',-600,-31)
ON CONFLICT (period_id) DO NOTHING;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_LAUMONIER_CARIE','secondary scholarship','Alfred Laumonier, Les cultes indigènes en Carie (Bibliothèque des Écoles françaises d''Athènes et de Rome 188, Paris, 1958)','Foundational monograph on the indigenous and civic cults of Caria: Zeus Labraundos, Zeus Osogo/Zenoposeidon, Zeus of Panamara/Stratios, Hecate of Lagina, the god of Sinuri.')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,trad text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_CAR_PANTHEON','Carian Pantheon','collective','pantheon','Carian','regional polytheism;Anatolian civic cult','B','Hub collective for the indigenous civic deities of Caria attested at the major rural sanctuaries (Labranda, Lagina, Mylasa, Panamara, Sinuri); Laumonier 1958.'),
 ('ENT_CAR_ZEUS_LABRAUNDOS','Zeus Labraundos','deity','sky god','Carian','sky;sovereignty;war;double-axe (labrys)','B','The double-axe-wielding Zeus of the great sanctuary at Labranda near Mylasa, indigenous Carian storm/war god interpreted as Zeus; epigraphically Zeus Labraundos/Labrayndos, his priest the Hekatomnids'' dynastic cult (Mausolus, Idrieus). Laumonier 1958, pp. 37-101.'),
 ('ENT_CAR_ZEUS_OSOGO','Zeus Osogo (Zenoposeidon)','deity','sky god','Carian','sky;sea;fresh water','B','Carian god of Mylasa worshipped as Zeus Osogo / Osogoa, also called Zenoposeidon (Zeus-Poseidon); his temple held a saltwater spring and the trident appeared with the eagle, fusing Zeus and Poseidon. Laumonier 1958, pp. 102-145.'),
 ('ENT_CAR_ZEUS_PANAMAROS','Zeus Panamaros (Zeus Stratios)','deity','sky god','Carian','sky;war;civic protection','B','Zeus of the federal sanctuary at Panamara near Stratonikeia, also titled Zeus Stratios (''of the army''); patron of the Panamareia festival and famed epiphany that repelled a siege. Laumonier 1958, pp. 221-343.'),
 ('ENT_CAR_HECATE_LAGINA','Hecate of Lagina','deity','goddess;chthonic','Carian','liminality;mysteries;civic protection;sovereignty','B','The great Carian Hecate venerated at the sanctuary of Lagina near Stratonikeia, with her annual Kleidos Pompe (procession of the key) and mysteries; a major civic cult equating the indigenous goddess with Greek Hecate. Laumonier 1958, pp. 344-425.'),
 ('ENT_CAR_SINURI','God of Sinuri','deity','local god','Carian','local tutelary;oath;sanctuary protection','C','Indigenous Carian deity (Theos Sinuri) of the rural sanctuary of Sinuri near Mylasa, known from the Hekatomnid-era archive and Carian inscriptions; an autochthonous god retaining his native name rather than a Greek interpretatio. Laumonier 1958, pp. 198-220; Sinuri sanctuary archive.');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'devotional',conf,'candidate_verified_name','Roster build via gen_roster.py (see CHANGELOG/git for release)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,etype text,note text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_CAR_PANTHEON','SRC_LAUMONIER_CARIE','scholarly attestation','attestation'),
 ('ENT_CAR_ZEUS_LABRAUNDOS','SRC_LAUMONIER_CARIE','scholarly attestation','attestation'),
 ('ENT_CAR_ZEUS_OSOGO','SRC_LAUMONIER_CARIE','scholarly attestation','attestation'),
 ('ENT_CAR_ZEUS_PANAMAROS','SRC_LAUMONIER_CARIE','scholarly attestation','attestation'),
 ('ENT_CAR_HECATE_LAGINA','SRC_LAUMONIER_CARIE','scholarly attestation','attestation'),
 ('ENT_CAR_SINURI','SRC_LAUMONIER_CARIE','scholarly attestation','attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_CAR_PANTHEON','PER_CARIAN','Hub collective for the indigenous civic deities of Caria attested at the major rural sanctuaries (Labranda, Lagina, Mylasa, Panamara, Sinuri); Laumonier 1958.'),
 ('ENT_CAR_ZEUS_LABRAUNDOS','PER_CARIAN','The double-axe-wielding Zeus of the great sanctuary at Labranda near Mylasa, indigenous Carian storm/war god interpreted as Zeus; epigraphically Zeus Labraundos/Labrayndos, his priest the Hekatomnids'' dynastic cult (Mausolus, Idrieus). Laumonier 1958, pp. 37-101.'),
 ('ENT_CAR_ZEUS_OSOGO','PER_CARIAN','Carian god of Mylasa worshipped as Zeus Osogo / Osogoa, also called Zenoposeidon (Zeus-Poseidon); his temple held a saltwater spring and the trident appeared with the eagle, fusing Zeus and Poseidon. Laumonier 1958, pp. 102-145.'),
 ('ENT_CAR_ZEUS_PANAMAROS','PER_CARIAN','Zeus of the federal sanctuary at Panamara near Stratonikeia, also titled Zeus Stratios (''of the army''); patron of the Panamareia festival and famed epiphany that repelled a siege. Laumonier 1958, pp. 221-343.'),
 ('ENT_CAR_HECATE_LAGINA','PER_CARIAN','The great Carian Hecate venerated at the sanctuary of Lagina near Stratonikeia, with her annual Kleidos Pompe (procession of the key) and mysteries; a major civic cult equating the indigenous goddess with Greek Hecate. Laumonier 1958, pp. 344-425.'),
 ('ENT_CAR_SINURI','PER_CARIAN','Indigenous Carian deity (Theos Sinuri) of the rural sanctuary of Sinuri near Mylasa, known from the Hekatomnid-era archive and Carian inscriptions; an autochthonous god retaining his native name rather than a Greek interpretatio. Laumonier 1958, pp. 198-220; Sinuri sanctuary archive.');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_CAR_ZEUS_LABRAUNDOS','member_of','ENT_CAR_PANTHEON','high','Zeus Labraundos of Labranda is a core deity of the Carian civic pantheon (Laumonier 1958).'),
 ('ENT_CAR_ZEUS_OSOGO','member_of','ENT_CAR_PANTHEON','high','Zeus Osogo/Zenoposeidon of Mylasa belongs to the Carian pantheon (Laumonier 1958).'),
 ('ENT_CAR_ZEUS_PANAMAROS','member_of','ENT_CAR_PANTHEON','high','Zeus Panamaros/Stratios of the Panamara sanctuary belongs to the Carian pantheon (Laumonier 1958).'),
 ('ENT_CAR_HECATE_LAGINA','member_of','ENT_CAR_PANTHEON','high','Hecate of Lagina is the leading goddess of the Carian civic pantheon (Laumonier 1958).'),
 ('ENT_CAR_SINURI','member_of','ENT_CAR_PANTHEON','high','The god of the Sinuri sanctuary is an indigenous member of the Carian pantheon (Laumonier 1958).'),
 ('ENT_CAR_ZEUS_LABRAUNDOS','cult_form_of','ENT_ZEUS','high','Zeus Labraundos is the Carian cult-form/local epithet of Zeus, the indigenous double-axe god interpreted as Zeus at Labranda.'),
 ('ENT_CAR_ZEUS_OSOGO','cult_form_of','ENT_ZEUS','high','Zeus Osogo of Mylasa is a Carian cult-form of Zeus (the indigenous god worshipped under the name Zeus Osogo).'),
 ('ENT_CAR_ZEUS_PANAMAROS','cult_form_of','ENT_ZEUS','high','Zeus Panamaros/Stratios is the Carian cult-form of Zeus at the Panamara sanctuary.'),
 ('ENT_CAR_HECATE_LAGINA','cult_form_of','ENT_HECATE','high','Hecate of Lagina is the great Carian cult-form of the Greek Hecate, the indigenous goddess venerated as Hecate at Lagina.'),
 ('ENT_CAR_ZEUS_OSOGO','equated_with','ENT_POSEIDON','high','Zeus Osogo bore the title Zenoposeidon and combined attributes (trident with eagle, saltwater spring) of Poseidon, an ancient interpretatio fusing Zeus and Poseidon.');

\echo '--- REJECTED edges (bad id/type, or subject lacks a source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
