-- v2.1.84  Public-domain PRIMARY verbatim upgrades from the 2026-09 library expansion (955 new vols)
-- Dee's Five Books (Heptarchic angels), Arbatel (Latin 1575), Crowley Liber AL / Vision & Voice / Chanokh,
-- Weyer Pseudomonarchia (Latin/Scot 1584), Ars Notoria (Turner 1657), Bundahishn (West 1897), Jastrow 1903, Wilder's Iamblichus 1911.
-- Every quote is gated as a contiguous substring of the extracted text (whitespace-normalized); UPDATEs only touch
-- primary-uncited rows with NULL quote; INSERTs are guarded by citation_id. Existing citations otherwise PRESERVED.
BEGIN;

INSERT INTO sources (source_id, title, url, source_type, scope) VALUES ('SRC_ARS_NOTORIA_TURNER', 'Ars Notoria: The Notory Art of Solomon, trans. Robert Turner (London, 1657); reprinted in J. H. Peterson (ed.), The Lesser Key of Solomon (York Beach: Weiser, 2001), Part V', '', 'primary text (early modern translation)', 'NEW - public-domain 1657 English of the Ars Notoria; used for verbatim attestation of the Notoria angels and notae') ON CONFLICT (source_id) DO NOTHING;
INSERT INTO sources (source_id, title, url, source_type, scope) VALUES ('SRC_JASTROW_DICT', 'Marcus Jastrow, A Dictionary of the Targumim, the Talmud Babli and Yerushalmi, and the Midrashic Literature, 2 vols. (London: Luzac / New York: Putnam, 1903)', '', 'reference (lexicon)', 'NEW - public-domain rabbinic lexicon; Latin-letter glosses only (Hebrew headwords OCR-garbled)') ON CONFLICT (source_id) DO NOTHING;

UPDATE entity_citations SET quote='King BOBOGEL appeared in a blak veluet coat, and his hose close, rownd hose with veluet upperstocks: ouerlayde with gold lace: On his hed a veluet hatcap, with a blak feather in it: with a Cape hanging on one of his sholders, his purse hanging abowt his neck and so put under his gyrdell at which hong a gylt rapier, his berd was long: he had pantofells and pynsons.', evidence_grade='primary-verbatim', work_title='John Dee, Mysteriorum Libri Quinque (Sloane MS 3188, 1581-1583); transcribed in Joseph H. Peterson (ed.), John Dee''s Five Books of Mystery (Boston: Weiser, 2003)', locus='Libri Mysteriorum (Nov. 1582 actions), passim', evidence_note='Primary attestation in Dee''s Heptarchic diaries (Nov. 1582 actions), in Dee''s own words.', verify_method='full-text extraction (EPUB) of Peterson''s transcription; quote is Dee''s own 1582 diary text (public domain), located by word-boundary search, context read to confirm the speaker/referent, and gated as a contiguous substring of the extraction (line breaks collapsed to single spaces); Peterson''s editorial summaries and footnotes were excluded', review_reason='primary verbatim from a modern transcription; confirm against Sloane MS 3188 / Peterson''s page', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_REN_BOBOGEL_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='Prince BORNOGO appeared in a red Robe, with a Gold Cerclet on his hed: he shewed his Seale, and sayde, This it is.', evidence_grade='primary-verbatim', work_title='John Dee, Mysteriorum Libri Quinque (Sloane MS 3188, 1581-1583); transcribed in Joseph H. Peterson (ed.), John Dee''s Five Books of Mystery (Boston: Weiser, 2003)', locus='Libri Mysteriorum (Nov. 1582 actions), passim', evidence_note='Primary attestation in Dee''s Heptarchic diaries (Nov. 1582 actions), in Dee''s own words.', verify_method='full-text extraction (EPUB) of Peterson''s transcription; quote is Dee''s own 1582 diary text (public domain), located by word-boundary search, context read to confirm the speaker/referent, and gated as a contiguous substring of the extraction (line breaks collapsed to single spaces); Peterson''s editorial summaries and footnotes were excluded', review_reason='primary verbatim from a modern transcription; confirm against Sloane MS 3188 / Peterson''s page', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_REN_BORNOGO_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='Prince BEFAFES appeared in a long red robe, with a cerclet of Gold on his hed.', evidence_grade='primary-verbatim', work_title='John Dee, Mysteriorum Libri Quinque (Sloane MS 3188, 1581-1583); transcribed in Joseph H. Peterson (ed.), John Dee''s Five Books of Mystery (Boston: Weiser, 2003)', locus='Libri Mysteriorum (Nov. 1582 actions), passim', evidence_note='Primary attestation in Dee''s Heptarchic diaries (Nov. 1582 actions), in Dee''s own words.', verify_method='full-text extraction (EPUB) of Peterson''s transcription; quote is Dee''s own 1582 diary text (public domain), located by word-boundary search, context read to confirm the speaker/referent, and gated as a contiguous substring of the extraction (line breaks collapsed to single spaces); Peterson''s editorial summaries and footnotes were excluded', review_reason='primary verbatim from a modern transcription; confirm against Sloane MS 3188 / Peterson''s page', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_REN_BEFAFES_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='Prince BUTMONO appeared in a red Robe, with a golden Cerclet on his hed:', evidence_grade='primary-verbatim', work_title='John Dee, Mysteriorum Libri Quinque (Sloane MS 3188, 1581-1583); transcribed in Joseph H. Peterson (ed.), John Dee''s Five Books of Mystery (Boston: Weiser, 2003)', locus='Libri Mysteriorum (Nov. 1582 actions), passim', evidence_note='Primary attestation in Dee''s Heptarchic diaries (Nov. 1582 actions), in Dee''s own words.', verify_method='full-text extraction (EPUB) of Peterson''s transcription; quote is Dee''s own 1582 diary text (public domain), located by word-boundary search, context read to confirm the speaker/referent, and gated as a contiguous substring of the extraction (line breaks collapsed to single spaces); Peterson''s editorial summaries and footnotes were excluded', review_reason='primary verbatim from a modern transcription; confirm against Sloane MS 3188 / Peterson''s page', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_REN_BUTMONO_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='Prince BLISDON appeared in a Robe of many Cullours: and on his hed a Cerclet of Gold.', evidence_grade='primary-verbatim', work_title='John Dee, Mysteriorum Libri Quinque (Sloane MS 3188, 1581-1583); transcribed in Joseph H. Peterson (ed.), John Dee''s Five Books of Mystery (Boston: Weiser, 2003)', locus='Libri Mysteriorum (Nov. 1582 actions), passim', evidence_note='Primary attestation in Dee''s Heptarchic diaries (Nov. 1582 actions), in Dee''s own words.', verify_method='full-text extraction (EPUB) of Peterson''s transcription; quote is Dee''s own 1582 diary text (public domain), located by word-boundary search, context read to confirm the speaker/referent, and gated as a contiguous substring of the extraction (line breaks collapsed to single spaces); Peterson''s editorial summaries and footnotes were excluded', review_reason='primary verbatim from a modern transcription; confirm against Sloane MS 3188 / Peterson''s page', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_REN_BLISDON_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='Prince BRALGES appeared in a red Robe with a Cerclet on his hed.', evidence_grade='primary-verbatim', work_title='John Dee, Mysteriorum Libri Quinque (Sloane MS 3188, 1581-1583); transcribed in Joseph H. Peterson (ed.), John Dee''s Five Books of Mystery (Boston: Weiser, 2003)', locus='Libri Mysteriorum (Nov. 1582 actions), passim', evidence_note='Primary attestation in Dee''s Heptarchic diaries (Nov. 1582 actions), in Dee''s own words.', verify_method='full-text extraction (EPUB) of Peterson''s transcription; quote is Dee''s own 1582 diary text (public domain), located by word-boundary search, context read to confirm the speaker/referent, and gated as a contiguous substring of the extraction (line breaks collapsed to single spaces); Peterson''s editorial summaries and footnotes were excluded', review_reason='primary verbatim from a modern transcription; confirm against Sloane MS 3188 / Peterson''s page', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_REN_BRALGES_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='Prince Butmono sayd this: but the office is under king Bnaspol, whose prince is Blisdon.', evidence_grade='primary-verbatim', work_title='John Dee, Mysteriorum Libri Quinque (Sloane MS 3188, 1581-1583); transcribed in Joseph H. Peterson (ed.), John Dee''s Five Books of Mystery (Boston: Weiser, 2003)', locus='Libri Mysteriorum (Nov. 1582 actions), passim', evidence_note='Primary attestation in Dee''s Heptarchic diaries (Nov. 1582 actions), in Dee''s own words.', verify_method='full-text extraction (EPUB) of Peterson''s transcription; quote is Dee''s own 1582 diary text (public domain), located by word-boundary search, context read to confirm the speaker/referent, and gated as a contiguous substring of the extraction (line breaks collapsed to single spaces); Peterson''s editorial summaries and footnotes were excluded', review_reason='primary verbatim from a modern transcription; confirm against Sloane MS 3188 / Peterson''s page', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_REN_BNASPOL_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='Whether is the King his Name Bnaspen, or Bnapsen?', evidence_grade='primary-verbatim', work_title='John Dee, Mysteriorum Libri Quinque (Sloane MS 3188, 1581-1583); transcribed in Joseph H. Peterson (ed.), John Dee''s Five Books of Mystery (Boston: Weiser, 2003)', locus='Libri Mysteriorum (Nov. 1582 actions), passim', evidence_note='Primary attestation in Dee''s Heptarchic diaries (Nov. 1582 actions), in Dee''s own words. Dee''s own query on the spelling of this king''s name.', verify_method='full-text extraction (EPUB) of Peterson''s transcription; quote is Dee''s own 1582 diary text (public domain), located by word-boundary search, context read to confirm the speaker/referent, and gated as a contiguous substring of the extraction (line breaks collapsed to single spaces); Peterson''s editorial summaries and footnotes were excluded', review_reason='primary verbatim from a modern transcription; confirm against Sloane MS 3188 / Peterson''s page', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_REN_BNAPSEN_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='The King had written in his forhed, BABALEL.', evidence_grade='primary-verbatim', work_title='John Dee, Mysteriorum Libri Quinque (Sloane MS 3188, 1581-1583); transcribed in Joseph H. Peterson (ed.), John Dee''s Five Books of Mystery (Boston: Weiser, 2003)', locus='Libri Mysteriorum (Nov. 1582 actions), passim', evidence_note='Primary attestation in Dee''s Heptarchic diaries (Nov. 1582 actions), in Dee''s own words.', verify_method='full-text extraction (EPUB) of Peterson''s transcription; quote is Dee''s own 1582 diary text (public domain), located by word-boundary search, context read to confirm the speaker/referent, and gated as a contiguous substring of the extraction (line breaks collapsed to single spaces); Peterson''s editorial summaries and footnotes were excluded', review_reason='primary verbatim from a modern transcription; confirm against Sloane MS 3188 / Peterson''s page', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_REN_BABALEL_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='The first Name is BALIGON.', evidence_grade='primary-verbatim', work_title='John Dee, Mysteriorum Libri Quinque (Sloane MS 3188, 1581-1583); transcribed in Joseph H. Peterson (ed.), John Dee''s Five Books of Mystery (Boston: Weiser, 2003)', locus='Libri Mysteriorum (Nov. 1582 actions), passim', evidence_note='Primary attestation in Dee''s Heptarchic diaries (Nov. 1582 actions), in Dee''s own words.', verify_method='full-text extraction (EPUB) of Peterson''s transcription; quote is Dee''s own 1582 diary text (public domain), located by word-boundary search, context read to confirm the speaker/referent, and gated as a contiguous substring of the extraction (line breaks collapsed to single spaces); Peterson''s editorial summaries and footnotes were excluded', review_reason='primary verbatim from a modern transcription; confirm against Sloane MS 3188 / Peterson''s page', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_REN_BALIGON_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='and in the fowrth septenarie, the first of septenarie is Bynepor, and so accownted the fowrth', evidence_grade='primary-verbatim', work_title='John Dee, Mysteriorum Libri Quinque (Sloane MS 3188, 1581-1583); transcribed in Joseph H. Peterson (ed.), John Dee''s Five Books of Mystery (Boston: Weiser, 2003)', locus='Libri Mysteriorum (Nov. 1582 actions), passim', evidence_note='Primary attestation in Dee''s Heptarchic diaries (Nov. 1582 actions), in Dee''s own words.', verify_method='full-text extraction (EPUB) of Peterson''s transcription; quote is Dee''s own 1582 diary text (public domain), located by word-boundary search, context read to confirm the speaker/referent, and gated as a contiguous substring of the extraction (line breaks collapsed to single spaces); Peterson''s editorial summaries and footnotes were excluded', review_reason='primary verbatim from a modern transcription; confirm against Sloane MS 3188 / Peterson''s page', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_REN_BYNEPOR_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='One, to haue Bobogel and Bornogo in the first row: and other to haue Baligon and Bagenol (his prince) in the first row', evidence_grade='primary-verbatim', work_title='John Dee, Mysteriorum Libri Quinque (Sloane MS 3188, 1581-1583); transcribed in Joseph H. Peterson (ed.), John Dee''s Five Books of Mystery (Boston: Weiser, 2003)', locus='Libri Mysteriorum (Nov. 1582 actions), passim', evidence_note='Primary attestation in Dee''s Heptarchic diaries (Nov. 1582 actions), in Dee''s own words.', verify_method='full-text extraction (EPUB) of Peterson''s transcription; quote is Dee''s own 1582 diary text (public domain), located by word-boundary search, context read to confirm the speaker/referent, and gated as a contiguous substring of the extraction (line breaks collapsed to single spaces); Peterson''s editorial summaries and footnotes were excluded', review_reason='primary verbatim from a modern transcription; confirm against Sloane MS 3188 / Peterson''s page', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_REN_BAGENOL_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='I am called MARMARA: but otherwise CARMARA : but that letter M, shall not be expressed, &c.', evidence_grade='primary-verbatim', work_title='John Dee, Mysteriorum Libri Quinque (Sloane MS 3188, 1581-1583); transcribed in Joseph H. Peterson (ed.), John Dee''s Five Books of Mystery (Boston: Weiser, 2003)', locus='Libri Mysteriorum (Nov. 1582 actions), passim', evidence_note='Primary attestation in Dee''s Heptarchic diaries (Nov. 1582 actions), in Dee''s own words.', verify_method='full-text extraction (EPUB) of Peterson''s transcription; quote is Dee''s own 1582 diary text (public domain), located by word-boundary search, context read to confirm the speaker/referent, and gated as a contiguous substring of the extraction (line breaks collapsed to single spaces); Peterson''s editorial summaries and footnotes were excluded', review_reason='primary verbatim from a modern transcription; confirm against Sloane MS 3188 / Peterson''s page', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_REN_CARMARA_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='I am HAGONEL, and govern HAGONEL. There is Hagonel the first, Hagonel the second, and Hagonel the third, I am the first that gouern the three.', evidence_grade='primary-verbatim', work_title='John Dee, Mysteriorum Libri Quinque (Sloane MS 3188, 1581-1583); transcribed in Joseph H. Peterson (ed.), John Dee''s Five Books of Mystery (Boston: Weiser, 2003)', locus='Libri Mysteriorum (Nov. 1582 actions), passim', evidence_note='Primary attestation in Dee''s Heptarchic diaries (Nov. 1582 actions), in Dee''s own words.', verify_method='full-text extraction (EPUB) of Peterson''s transcription; quote is Dee''s own 1582 diary text (public domain), located by word-boundary search, context read to confirm the speaker/referent, and gated as a contiguous substring of the extraction (line breaks collapsed to single spaces); Peterson''s editorial summaries and footnotes were excluded', review_reason='primary verbatim from a modern transcription; confirm against Sloane MS 3188 / Peterson''s page', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_REN_HAGONEL_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='Visibilia autem eorum Astra sunt ARATRON, BETHOR, PHALEG, OCH, HAGITH, OPHIEL, PHVL.', evidence_grade='primary-verbatim', work_title='Arbatel de magia veterum (Basel: Pietro Perna, 1575); Latin text as printed in Joseph H. Peterson (ed./trans.), Arbatel: Concerning the Magic of the Ancients (Lake Worth: Ibis, 2009)', locus='Aphorism 16 (cf. Aphorism 17)', evidence_note='Primary attestation: the Arbatel names this Olympic Spirit among the seven visible "stars" (Aphorism 16) and treats it in its own aphorism.', verify_method='full-text extraction (pdftotext) of Peterson''s parallel edition; the LATIN 1575 text (public domain) is quoted, not Peterson''s copyrighted translation; only OCR-clean Latin sentences were accepted (passages with ae->''re'' OCR corruption rejected); contiguous-substring gate passed', review_reason='Latin primary verbatim; confirm aphorism number against the 1575 edition', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_REN_ARATRON_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='Visibilia autem eorum Astra sunt ARATRON, BETHOR, PHALEG, OCH, HAGITH, OPHIEL, PHVL.', evidence_grade='primary-verbatim', work_title='Arbatel de magia veterum (Basel: Pietro Perna, 1575); Latin text as printed in Joseph H. Peterson (ed./trans.), Arbatel: Concerning the Magic of the Ancients (Lake Worth: Ibis, 2009)', locus='Aphorism 16 (cf. Aphorism 18)', evidence_note='Primary attestation: the Arbatel names this Olympic Spirit among the seven visible "stars" (Aphorism 16) and treats it in its own aphorism.', verify_method='full-text extraction (pdftotext) of Peterson''s parallel edition; the LATIN 1575 text (public domain) is quoted, not Peterson''s copyrighted translation; only OCR-clean Latin sentences were accepted (passages with ae->''re'' OCR corruption rejected); contiguous-substring gate passed', review_reason='Latin primary verbatim; confirm aphorism number against the 1575 edition', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_REN_BETHOR_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='Visibilia autem eorum Astra sunt ARATRON, BETHOR, PHALEG, OCH, HAGITH, OPHIEL, PHVL.', evidence_grade='primary-verbatim', work_title='Arbatel de magia veterum (Basel: Pietro Perna, 1575); Latin text as printed in Joseph H. Peterson (ed./trans.), Arbatel: Concerning the Magic of the Ancients (Lake Worth: Ibis, 2009)', locus='Aphorism 16 (cf. Aphorism 19)', evidence_note='Primary attestation: the Arbatel names this Olympic Spirit among the seven visible "stars" (Aphorism 16) and treats it in its own aphorism.', verify_method='full-text extraction (pdftotext) of Peterson''s parallel edition; the LATIN 1575 text (public domain) is quoted, not Peterson''s copyrighted translation; only OCR-clean Latin sentences were accepted (passages with ae->''re'' OCR corruption rejected); contiguous-substring gate passed', review_reason='Latin primary verbatim; confirm aphorism number against the 1575 edition', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_REN_PHALEG_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='Visibilia autem eorum Astra sunt ARATRON, BETHOR, PHALEG, OCH, HAGITH, OPHIEL, PHVL.', evidence_grade='primary-verbatim', work_title='Arbatel de magia veterum (Basel: Pietro Perna, 1575); Latin text as printed in Joseph H. Peterson (ed./trans.), Arbatel: Concerning the Magic of the Ancients (Lake Worth: Ibis, 2009)', locus='Aphorism 16 (cf. Aphorism 20)', evidence_note='Primary attestation: the Arbatel names this Olympic Spirit among the seven visible "stars" (Aphorism 16) and treats it in its own aphorism.', verify_method='full-text extraction (pdftotext) of Peterson''s parallel edition; the LATIN 1575 text (public domain) is quoted, not Peterson''s copyrighted translation; only OCR-clean Latin sentences were accepted (passages with ae->''re'' OCR corruption rejected); contiguous-substring gate passed', review_reason='Latin primary verbatim; confirm aphorism number against the 1575 edition', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_REN_OCH_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='HAGITH gubernat Venerea, quem suo dignatur charactere formosissimum facit, & ornatum omni decore.', evidence_grade='primary-verbatim', work_title='Arbatel de magia veterum (Basel: Pietro Perna, 1575); Latin text as printed in Joseph H. Peterson (ed./trans.), Arbatel: Concerning the Magic of the Ancients (Lake Worth: Ibis, 2009)', locus='Aphorism 21', evidence_note='Primary attestation: the Arbatel names this Olympic Spirit among the seven visible "stars" (Aphorism 16) and treats it in its own aphorism.', verify_method='full-text extraction (pdftotext) of Peterson''s parallel edition; the LATIN 1575 text (public domain) is quoted, not Peterson''s copyrighted translation; only OCR-clean Latin sentences were accepted (passages with ae->''re'' OCR corruption rejected); contiguous-substring gate passed', review_reason='Latin primary verbatim; confirm aphorism number against the 1575 edition', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_REN_HAGITH_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='Visibilia autem eorum Astra sunt ARATRON, BETHOR, PHALEG, OCH, HAGITH, OPHIEL, PHVL.', evidence_grade='primary-verbatim', work_title='Arbatel de magia veterum (Basel: Pietro Perna, 1575); Latin text as printed in Joseph H. Peterson (ed./trans.), Arbatel: Concerning the Magic of the Ancients (Lake Worth: Ibis, 2009)', locus='Aphorism 16 (cf. Aphorism 22)', evidence_note='Primary attestation: the Arbatel names this Olympic Spirit among the seven visible "stars" (Aphorism 16) and treats it in its own aphorism.', verify_method='full-text extraction (pdftotext) of Peterson''s parallel edition; the LATIN 1575 text (public domain) is quoted, not Peterson''s copyrighted translation; only OCR-clean Latin sentences were accepted (passages with ae->''re'' OCR corruption rejected); contiguous-substring gate passed', review_reason='Latin primary verbatim; confirm aphorism number against the 1575 edition', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_REN_OPHIEL_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='Visibilia autem eorum Astra sunt ARATRON, BETHOR, PHALEG, OCH, HAGITH, OPHIEL, PHVL.', evidence_grade='primary-verbatim', work_title='Arbatel de magia veterum (Basel: Pietro Perna, 1575); Latin text as printed in Joseph H. Peterson (ed./trans.), Arbatel: Concerning the Magic of the Ancients (Lake Worth: Ibis, 2009)', locus='Aphorism 16 (cf. Aphorism 23)', evidence_note='Primary attestation: the Arbatel names this Olympic Spirit among the seven visible "stars" (Aphorism 16) and treats it in its own aphorism.', verify_method='full-text extraction (pdftotext) of Peterson''s parallel edition; the LATIN 1575 text (public domain) is quoted, not Peterson''s copyrighted translation; only OCR-clean Latin sentences were accepted (passages with ae->''re'' OCR corruption rejected); contiguous-substring gate passed', review_reason='Latin primary verbatim; confirm aphorism number against the 1575 edition', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_REN_PHUL_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='Visibilia autem eorum Astra sunt ARATRON, BETHOR, PHALEG, OCH, HAGITH, OPHIEL, PHVL.', evidence_grade='primary-verbatim', work_title='Arbatel de magia veterum (Basel: Pietro Perna, 1575); Latin text as printed in Joseph H. Peterson (ed./trans.), Arbatel: Concerning the Magic of the Ancients (Lake Worth: Ibis, 2009)', locus='Aphorism 16', evidence_note='Primary attestation: the Arbatel names this Olympic Spirit among the seven visible "stars" (Aphorism 16) and treats it in its own aphorism.', verify_method='full-text extraction (pdftotext) of Peterson''s parallel edition; the LATIN 1575 text (public domain) is quoted, not Peterson''s copyrighted translation; only OCR-clean Latin sentences were accepted (passages with ae->''re'' OCR corruption rejected); contiguous-substring gate passed', review_reason='Latin primary verbatim; confirm aphorism number against the 1575 edition', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_REN_OLYMPIC_SPIRITS_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='I am Heaven, and there is no other God than me, and my lord Hadit.', evidence_grade='primary-verbatim', work_title='Aleister Crowley, Liber AL vel Legis (The Book of the Law), 1904; first published in The Equinox I:7 (1912) / Thelema (1909)', locus='I:21', evidence_note='Nuit speaking; primary attestation in the Book of the Law.', verify_method='full-text extraction (EPUB); quote taken from the verse text of Liber AL itself (public domain: pre-1929 publication; author d. 1947), NOT from the 1938 introduction; chapter:verse read off the numbered verse in the extraction; contiguous-substring gate passed', review_reason='primary verbatim; confirm verse number against a printed edition', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_THL_NUIT_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='Be thou Hadit, my secret centre, my heart & my tongue!', evidence_grade='primary-verbatim', work_title='Aleister Crowley, Liber AL vel Legis (The Book of the Law), 1904; first published in The Equinox I:7 (1912) / Thelema (1909)', locus='I:6', evidence_note='Nuit addressing Hadit; primary attestation in the Book of the Law.', verify_method='full-text extraction (EPUB); quote taken from the verse text of Liber AL itself (public domain: pre-1929 publication; author d. 1947), NOT from the 1938 introduction; chapter:verse read off the numbered verse in the extraction; contiguous-substring gate passed', review_reason='primary verbatim; confirm verse number against a printed edition', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_THL_HADIT_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='Ra-Hoor-Khuit hath taken his seat in the East at the Equinox of the Gods; and let Asar be with Isa, who also are one.', evidence_grade='primary-verbatim', work_title='Aleister Crowley, Liber AL vel Legis (The Book of the Law), 1904; first published in The Equinox I:7 (1912) / Thelema (1909)', locus='I:49', evidence_note='Primary attestation in the Book of the Law.', verify_method='full-text extraction (EPUB); quote taken from the verse text of Liber AL itself (public domain: pre-1929 publication; author d. 1947), NOT from the 1938 introduction; chapter:verse read off the numbered verse in the extraction; contiguous-substring gate passed', review_reason='primary verbatim; confirm verse number against a printed edition', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_THL_RA_HOOR_KHUIT_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='Behold! it is revealed by Aiwass the minister of Hoor-paar-kraat.', evidence_grade='primary-verbatim', work_title='Aleister Crowley, Liber AL vel Legis (The Book of the Law), 1904; first published in The Equinox I:7 (1912) / Thelema (1909)', locus='I:7', evidence_note='Primary attestation in the Book of the Law.', verify_method='full-text extraction (EPUB); quote taken from the verse text of Liber AL itself (public domain: pre-1929 publication; author d. 1947), NOT from the 1938 introduction; chapter:verse read off the numbered verse in the extraction; contiguous-substring gate passed', review_reason='primary verbatim; confirm verse number against a printed edition', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_THL_HOOR_PAAR_KRAAT_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='Behold! it is revealed by Aiwass the minister of Hoor-paar-kraat.', evidence_grade='primary-verbatim', work_title='Aleister Crowley, Liber AL vel Legis (The Book of the Law), 1904; first published in The Equinox I:7 (1912) / Thelema (1909)', locus='I:7', evidence_note='Primary attestation in the Book of the Law: Aiwass named as the communicating intelligence.', verify_method='full-text extraction (EPUB); quote taken from the verse text of Liber AL itself (public domain: pre-1929 publication; author d. 1947), NOT from the 1938 introduction; chapter:verse read off the numbered verse in the extraction; contiguous-substring gate passed', review_reason='primary verbatim; confirm verse number against a printed edition', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_THL_AIWASS_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='Now ye shall know that the chosen priest & apostle of infinite space is the prince-priest the Beast; and in his woman called the Scarlet Woman is all power given.', evidence_grade='primary-verbatim', work_title='Aleister Crowley, Liber AL vel Legis (The Book of the Law), 1904; first published in The Equinox I:7 (1912) / Thelema (1909)', locus='I:15', evidence_note='Primary attestation: ''the Beast'' (Therion) in the Book of the Law.', verify_method='full-text extraction (EPUB); quote taken from the verse text of Liber AL itself (public domain: pre-1929 publication; author d. 1947), NOT from the 1938 introduction; chapter:verse read off the numbered verse in the extraction; contiguous-substring gate passed', review_reason='primary verbatim; confirm verse number against a printed edition', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_THL_THERION_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='Nuit! Hadit! Ra-Hoor-Khuit! The Sun, Strength & Sight, Light; these are for the servants of the Star & the Snake.', evidence_grade='primary-verbatim', work_title='Aleister Crowley, Liber AL vel Legis (The Book of the Law), 1904; first published in The Equinox I:7 (1912) / Thelema (1909)', locus='II:21', evidence_note='Primary attestation: the three principal Thelemic deities named together.', verify_method='full-text extraction (EPUB); quote taken from the verse text of Liber AL itself (public domain: pre-1929 publication; author d. 1947), NOT from the 1938 introduction; chapter:verse read off the numbered verse in the extraction; contiguous-substring gate passed', review_reason='primary verbatim; confirm verse number against a printed edition', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_THL_PANTHEON_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='Ra-Hoor-Khuit hath taken his seat in the East at the Equinox of the Gods; and let Asar be with Isa, who also are one.', evidence_grade='primary-verbatim', work_title='Aleister Crowley, Liber AL vel Legis (The Book of the Law), 1904; first published in The Equinox I:7 (1912) / Thelema (1909)', locus='I:49', evidence_note='Primary attestation: the verse proclaiming the Equinox of the Gods, i.e. the inauguration of the Aeon of Horus (the phrase ''Aeon of Horus'' itself occurs only in Crowley''s 1938 introduction, not in the verse text).', verify_method='full-text extraction (EPUB); quote taken from the verse text of Liber AL itself (public domain: pre-1929 publication; author d. 1947), NOT from the 1938 introduction; chapter:verse read off the numbered verse in the extraction; contiguous-substring gate passed', review_reason='primary verbatim; confirm verse number against a printed edition', verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_THL_AEON_HORUS_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_THL_CHORONZON_VV', 'ENT_THL_CHORONZON', 'SRC_CROWLEY_VISION_VOICE', 'Aleister Crowley, The Vision and the Voice (Liber XXX Aerum vel Saeculi sub figura CDXVIII), The Equinox I:5 (1911)', 'The Cry of the 10th Aethyr (ZAX)', 'Yet must he that understandeth go forth unto the outermost Abyss, and there must he speak with him that is set above the four-fold terror, the Princes of Evil, even with Choronzon, the mighty devil that inhabiteth the outermost Abyss.', 'primary-verbatim', 'Primary attestation of Choronzon in the 10th Aethyr; the entity''s existing pointer to Liber AL is left in place but Liber AL does not name Choronzon.', DATE '2026-09-18', 'full-text extraction (pdftotext) of a modern reprint; quote is from Crowley''s 1909 visionary text (public domain, published 1911); located by word-boundary search, aethyr heading read to fix the locus; contiguous-substring gate passed', 1, TRUE, 'primary verbatim; confirm aethyr attribution', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_THL_CHORONZON_VV');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_THL_BABALON_VV', 'ENT_THL_BABALON', 'SRC_CROWLEY_VISION_VOICE', 'Aleister Crowley, The Vision and the Voice (Liber XXX Aerum vel Saeculi sub figura CDXVIII), The Equinox I:5 (1911)', 'The Cry of the 12th Aethyr (LOE)', 'Glory unto the Scarlet Woman, Babalon the Mother of Abominations, that rideth upon the Beast, for she hath spilt their blood in every corner of the earth', 'primary-verbatim', 'Primary attestation of Babalon; the entity''s existing pointer to Liber AL is left in place but Liber AL does not spell the name Babalon.', DATE '2026-09-18', 'full-text extraction (pdftotext) of a modern reprint; quote is from Crowley''s 1909 visionary text (public domain, published 1911); located by word-boundary search, aethyr heading read to fix the locus; contiguous-substring gate passed', 1, TRUE, 'primary verbatim; confirm aethyr attribution', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_THL_BABALON_VV');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_REN_AETHYR_LIL_VV', 'ENT_REN_AETHYR_LIL', 'SRC_CROWLEY_VISION_VOICE', 'Aleister Crowley, The Vision and the Voice (Liber XXX Aerum vel Saeculi sub figura CDXVIII), The Equinox I:5 (1911)', 'The Cry of the 1st Aethyr (LIL), close', 'with that the voice of LIL, that is the Lamp of the Invisible Light, is ended.', 'primary-verbatim', 'Crowley''s 1909 vision of the 1st Aethyr LIL (the Dee/Kelley aethyr name); complements the Dee-diaries pointer.', DATE '2026-09-18', 'full-text extraction (pdftotext) of a modern reprint; quote is from Crowley''s 1909 visionary text (public domain, published 1911); located by word-boundary search, aethyr heading read to fix the locus; contiguous-substring gate passed', 1, TRUE, 'primary verbatim from the Thelemic reception of the Dee aethyrs', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_REN_AETHYR_LIL_VV');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_REN_AETHYR_TEX_VV', 'ENT_REN_AETHYR_TEX', 'SRC_CROWLEY_VISION_VOICE', 'Aleister Crowley, The Vision and the Voice (Liber XXX Aerum vel Saeculi sub figura CDXVIII), The Equinox I:5 (1911)', 'The Cry of the 30th Aethyr (TEX), close', 'Thus far is the voice of TEX and no more.', 'primary-verbatim', 'Crowley''s 1900 vision of the 30th Aethyr TEX (the Dee/Kelley aethyr name); complements the Dee-diaries pointer.', DATE '2026-09-18', 'full-text extraction (pdftotext) of a modern reprint; quote is from Crowley''s 1909 visionary text (public domain, published 1911); located by word-boundary search, aethyr heading read to fix the locus; contiguous-substring gate passed', 1, TRUE, 'primary verbatim from the Thelemic reception of the Dee aethyrs', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_REN_AETHYR_TEX_VV');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_REN_WATCHTOWERS_CHANOKH', 'ENT_REN_WATCHTOWERS', 'SRC_CROWLEY_LIBER_CHANOKH', 'Aleister Crowley, Liber LXXXIV vel Chanokh, The Equinox I:7-8 (1912)', 'Part I, introductory description of the Great Table', 'The sides of the square are the four great watch-towers (Plates IV.-VII.) which are attributed to the elements.', 'primary-verbatim', 'Crowley''s abstract of Dee''s Great Table; names the four Watchtowers as the sides of the Table.', DATE '2026-09-18', 'full-text extraction (pdftotext); quote located by word-boundary search in Crowley''s own text (public domain, 1912), editorial apparatus of the reprint excluded; contiguous-substring gate passed', 1, TRUE, 'primary verbatim from the Thelemic redaction of Dee; confirm against Equinox I:7', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_REN_WATCHTOWERS_CHANOKH');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_GOE_BUNE_WEYER', 'ENT_GOE_BUNE', 'SRC_WEYER_PSEUDOMONARCHIA', 'Johann Weyer, Pseudomonarchia Daemonum (1577), Latin text as reprinted in J. H. Peterson (ed.), The Lesser Key of Solomon (Weiser, 2001), Appendix 2', '§ 24', 'Bune Dux magnus & fortis, apparet ut draco, tribus capitibus, tertium vero assimilatur homini.', 'primary-verbatim', 'Weyer''s catalogue entry for Bune (the source of the Goetia''s 26th spirit).', DATE '2026-09-18', 'full-text extraction (pdftotext) of Peterson''s reprint of Weyer''s Latin (public domain); OCR-clean Latin sentence only; contiguous-substring gate passed', 1, TRUE, 'Latin primary verbatim; confirm section number', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_GOE_BUNE_WEYER');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_GOE_RONOVE_WEYER', 'ENT_GOE_RONOVE', 'SRC_WEYER_PSEUDOMONARCHIA', 'Johann Weyer, Pseudomonarchia Daemonum (1577), Latin text as reprinted in J. H. Peterson (ed.), The Lesser Key of Solomon (Weiser, 2001), Appendix 2', '§ 26', 'Roneve Marchio & Comes, assimilatur monstro.', 'primary-verbatim', 'Weyer''s catalogue entry (spelled Roneve) for the Goetia''s 27th spirit Ronove.', DATE '2026-09-18', 'full-text extraction (pdftotext) of Peterson''s reprint of Weyer''s Latin (public domain); OCR-clean Latin sentence only; contiguous-substring gate passed', 1, TRUE, 'Latin primary verbatim; confirm section number', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_GOE_RONOVE_WEYER');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_GOE_RONOVE', 'Roneve', 'variant spelling (Weyer 1577)', 'SRC_WEYER_PSEUDOMONARCHIA', 'high', 'needs_review', 'Weyer, Pseudomonarchia § 26'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_GOE_RONOVE' AND alias_name='Roneve');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_GOE_RAUM_WEYER', 'ENT_GOE_RAUM', 'SRC_WEYER_PSEUDOMONARCHIA', 'Johann Weyer, Pseudomonarchia Daemonum (1577), Latin text as reprinted in J. H. Peterson (ed.), The Lesser Key of Solomon (Weiser, 2001), Appendix 2', '§ 41', 'Raum vel Raym Comes est magnus: Ut corvus visitur: Sed cum assumit humanam faciem, si ab exorcista jussus fuerit, mire ex regis domo vel alia suffuratur, & ad locum sibi designatum transfert.', 'primary-verbatim', 'Weyer''s catalogue entry for Raum (the Goetia''s 40th spirit).', DATE '2026-09-18', 'full-text extraction (pdftotext) of Peterson''s reprint of Weyer''s Latin (public domain); OCR-clean Latin sentences only; contiguous-substring gate passed', 1, TRUE, 'Latin primary verbatim; confirm section number', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_GOE_RAUM_WEYER');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_GOE_RAUM', 'Raym', 'variant spelling (Weyer 1577)', 'SRC_WEYER_PSEUDOMONARCHIA', 'high', 'needs_review', 'Weyer, Pseudomonarchia § 41'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_GOE_RAUM' AND alias_name='Raym');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_GOE_VINE_WEYER', 'ENT_GOE_VINE', 'SRC_WEYER_PSEUDOMONARCHIA', 'Johann Weyer, Pseudomonarchia Daemonum (1577), Latin text as reprinted in J. H. Peterson (ed.), The Lesser Key of Solomon (Weiser, 2001), Appendix 2', '§ 44', 'Vine magnus Rex & Comes: se ostentat ut leo in equo nigro insidens, portansque viperam in manu.', 'primary-verbatim', 'Weyer''s catalogue entry for Vine (the Goetia''s 45th spirit). The name is a homonym trap (''vine'') in English texts; the Latin entry is unambiguous.', DATE '2026-09-18', 'full-text extraction (pdftotext) of Peterson''s reprint of Weyer''s Latin (public domain); OCR-clean Latin sentence only; contiguous-substring gate passed', 1, TRUE, 'Latin primary verbatim; confirm section number', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_GOE_VINE_WEYER');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_GOE_GAAP_WEYER', 'ENT_GOE_GAAP', 'SRC_WEYER_PSEUDOMONARCHIA', 'Johann Weyer, Pseudomonarchia Daemonum (1577), in Reginald Scot''s English (The Discoverie of Witchcraft, 1584), as reprinted in J. H. Peterson (ed.), The Lesser Key of Solomon (Weiser, 2001), Appendix 2', '§ 36', 'Gaap, alias Tap, a great president and a prince, he appeareth in a meridionall signe, and when he taketh humane shape he is the guide of the foure principall kings, as mightie as Bileth.', 'primary-verbatim', 'Weyer''s catalogue entry for Gaap (the Goetia''s 33rd spirit), in Scot''s 1584 translation (the Latin extraction of this entry is OCR-corrupt and was rejected).', DATE '2026-09-18', 'full-text extraction (pdftotext) of Peterson''s reprint; Scot''s 1584 English (public domain) quoted; contiguous-substring gate passed', 1, TRUE, 'primary verbatim (Scot 1584); confirm section number', 'Reginald Scot', 1584, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_GOE_GAAP_WEYER');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_GOE_GAAP', 'Tap', 'alias given by Weyer/Scot', 'SRC_WEYER_PSEUDOMONARCHIA', 'high', 'needs_review', 'Weyer, Pseudomonarchia § 36'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_GOE_GAAP' AND alias_name='Tap');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_SOL_ARS_NOTORIA_ANGELS_TURNER', 'ENT_SOL_ARS_NOTORIA_ANGELS', 'SRC_ARS_NOTORIA_TURNER', 'Ars Notoria: The Notory Art of Solomon, trans. Robert Turner (London, 1657); as reprinted in J. H. Peterson (ed.), The Lesser Key of Solomon (Weiser, 2001), Part V', 'Part V, passim (section on the Notes of Grammar)', 'Here Solomon sheweth, how the Angel told him distinctly, wherefore the Grammar hath three Figures.', 'primary-verbatim', 'The Ars Notoria''s framing of its figures as delivered to Solomon by an angel.', DATE '2026-09-18', 'full-text extraction (pdftotext); quote from Turner''s 1657 translation (public domain) as reprinted; located by word-boundary search, context read; contiguous-substring gate passed', 1, TRUE, 'primary verbatim (Turner 1657); Veronese critical edition pointer retained', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_SOL_ARS_NOTORIA_ANGELS_TURNER');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_SOL_ARS_NOTORIA_NOTAE_TURNER', 'ENT_SOL_ARS_NOTORIA_NOTAE', 'SRC_ARS_NOTORIA_TURNER', 'Ars Notoria: The Notory Art of Solomon, trans. Robert Turner (London, 1657); as reprinted in J. H. Peterson (ed.), The Lesser Key of Solomon (Weiser, 2001), Part V', 'Part V, opening exposition', 'Therefore there are certain Notes of the Notary Art, which are manifest to us; the Vertue whereof Human Reason cannot comprehend.', 'primary-verbatim', 'The Ars Notoria''s own statement of its notae (Notes).', DATE '2026-09-18', 'full-text extraction (pdftotext); quote from Turner''s 1657 translation (public domain) as reprinted; located by word-boundary search, context read; contiguous-substring gate passed', 1, TRUE, 'primary verbatim (Turner 1657); Veronese critical edition pointer retained', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_SOL_ARS_NOTORIA_NOTAE_TURNER');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ZOR_VIZARESH_BUND', 'ENT_ZOR_VIZARESH', 'SRC_BUNDAHISHN', 'Bundahishn (Indian recension), trans. E. W. West, Sacred Books of the East vol. 5: Pahlavi Texts Part 1 (Oxford, 1897); ed. J. H. Peterson, avesta.org (CC-BY 4.0), with modernized name spellings', 'ch. 28', 'The demon Vizaresh is he who struggles with the souls of men which have departed, those days and nights when they remain in the world; he carries them on, terror-stricken, and sits at the gate of hell.', 'primary-verbatim', 'Bundahishn''s description of the demon Vizaresh.', DATE '2026-09-18', 'full-text extraction (pdftotext) of the avesta.org edition of West''s 1897 translation (public domain); name form in this edition differs from Avestan (alias recorded); chapter fixed from the chapter heading preceding the passage; contiguous-substring gate passed', 2, TRUE, 'primary verbatim (West 1897 via avesta.org); confirm the Pahlavi name = this Avestan entity and the chapter/section', 'E. W. West', 1897, 'https://www.avesta.org/mp/bundahis.html'
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ZOR_VIZARESH_BUND');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ZOR_JEH_BUND', 'ENT_ZOR_JEH', 'SRC_BUNDAHISHN', 'Bundahishn (Indian recension), trans. E. W. West, Sacred Books of the East vol. 5: Pahlavi Texts Part 1 (Oxford, 1897); ed. J. H. Peterson, avesta.org (CC-BY 4.0), with modernized name spellings', 'ch. 3', 'he kissed Jeh upon the head, and the pollution which they call menstruation became apparent in Jeh.', 'primary-verbatim', 'Bundahishn''s account of the demoness Jeh (Jahi).', DATE '2026-09-18', 'full-text extraction (pdftotext) of the avesta.org edition of West''s 1897 translation (public domain); name form in this edition differs from Avestan (alias recorded); chapter fixed from the chapter heading preceding the passage; contiguous-substring gate passed', 2, TRUE, 'primary verbatim (West 1897 via avesta.org); confirm the Pahlavi name = this Avestan entity and the chapter/section', 'E. W. West', 1897, 'https://www.avesta.org/mp/bundahis.html'
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ZOR_JEH_BUND');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ZOR_AKA_MANAH_BUND', 'ENT_ZOR_AKA_MANAH', 'SRC_BUNDAHISHN', 'Bundahishn (Indian recension), trans. E. W. West, Sacred Books of the East vol. 5: Pahlavi Texts Part 1 (Oxford, 1897); ed. J. H. Peterson, avesta.org (CC-BY 4.0), with modernized name spellings', 'ch. 28', 'The business of Akoman is this, that he gave vile thoughts and discord to the creatures.', 'primary-verbatim', 'Akoman is the Pahlavi form of Aka Manah (''evil thought'').', DATE '2026-09-18', 'full-text extraction (pdftotext) of the avesta.org edition of West''s 1897 translation (public domain); name form in this edition differs from Avestan (alias recorded); chapter fixed from the chapter heading preceding the passage; contiguous-substring gate passed', 2, TRUE, 'primary verbatim (West 1897 via avesta.org); confirm the Pahlavi name = this Avestan entity and the chapter/section', 'E. W. West', 1897, 'https://www.avesta.org/mp/bundahis.html'
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ZOR_AKA_MANAH_BUND');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_ZOR_AKA_MANAH', 'Akoman', 'Pahlavi form (West/Peterson spelling)', 'SRC_BUNDAHISHN', 'high', 'needs_review', 'Bundahishn, West trans.'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_ZOR_AKA_MANAH' AND alias_name='Akoman');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ZOR_INDRA_DAEVA_BUND', 'ENT_ZOR_INDRA_DAEVA', 'SRC_BUNDAHISHN', 'Bundahishn (Indian recension), trans. E. W. West, Sacred Books of the East vol. 5: Pahlavi Texts Part 1 (Oxford, 1897); ed. J. H. Peterson, avesta.org (CC-BY 4.0), with modernized name spellings', 'ch. 28', 'The business of the demon Andar is this, that he constrains the thoughts of the creatures from deeds of virtue, just like a leader who has well-constrained (sardar-i khup afsardo); and he casts this into the thoughts of men, that it is not necessary to have the sacred shirt [sudre] and thread-girdle [kusti].', 'primary-verbatim', 'Andar is the Pahlavi form of the daeva Indra.', DATE '2026-09-18', 'full-text extraction (pdftotext) of the avesta.org edition of West''s 1897 translation (public domain); name form in this edition differs from Avestan (alias recorded); chapter fixed from the chapter heading preceding the passage; contiguous-substring gate passed', 2, TRUE, 'primary verbatim (West 1897 via avesta.org); confirm the Pahlavi name = this Avestan entity and the chapter/section', 'E. W. West', 1897, 'https://www.avesta.org/mp/bundahis.html'
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ZOR_INDRA_DAEVA_BUND');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_ZOR_INDRA_DAEVA', 'Andar', 'Pahlavi form (West/Peterson spelling)', 'SRC_BUNDAHISHN', 'high', 'needs_review', 'Bundahishn, West trans.'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_ZOR_INDRA_DAEVA' AND alias_name='Andar');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ZOR_SAURVA_BUND', 'ENT_ZOR_SAURVA', 'SRC_BUNDAHISHN', 'Bundahishn (Indian recension), trans. E. W. West, Sacred Books of the East vol. 5: Pahlavi Texts Part 1 (Oxford, 1897); ed. J. H. Peterson, avesta.org (CC-BY 4.0), with modernized name spellings', 'ch. 28', 'The business of the demon Savar, that is a leader of the demons, is this, that is, misgovernment, oppressive anarchy, and drunkenness.', 'primary-verbatim', 'Savar/Sovar is the Pahlavi form of the daeva Saurva.', DATE '2026-09-18', 'full-text extraction (pdftotext) of the avesta.org edition of West''s 1897 translation (public domain); name form in this edition differs from Avestan (alias recorded); chapter fixed from the chapter heading preceding the passage; contiguous-substring gate passed', 2, TRUE, 'primary verbatim (West 1897 via avesta.org); confirm the Pahlavi name = this Avestan entity and the chapter/section', 'E. W. West', 1897, 'https://www.avesta.org/mp/bundahis.html'
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ZOR_SAURVA_BUND');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_ZOR_SAURVA', 'Savar', 'Pahlavi form (West/Peterson spelling)', 'SRC_BUNDAHISHN', 'high', 'needs_review', 'Bundahishn, West trans.'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_ZOR_SAURVA' AND alias_name='Savar');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_ZOR_SAURVA', 'Sovar', 'Pahlavi form (West/Peterson spelling)', 'SRC_BUNDAHISHN', 'high', 'needs_review', 'Bundahishn, West trans.'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_ZOR_SAURVA' AND alias_name='Sovar');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ZOR_NANGHAITHYA_BUND', 'ENT_ZOR_NANGHAITHYA', 'SRC_BUNDAHISHN', 'Bundahishn (Indian recension), trans. E. W. West, Sacred Books of the East vol. 5: Pahlavi Texts Part 1 (Oxford, 1897); ed. J. H. Peterson, avesta.org (CC-BY 4.0), with modernized name spellings', 'ch. 1', 'From the dark world of Ahriman were Akoman and Andar, and then Sovar, and then Nakahed, and then Tairev and Zairik.', 'primary-verbatim', 'Nakahed (Naikiyas) is the Pahlavi form of the daeva Nanghaithya (West''s identification).', DATE '2026-09-18', 'full-text extraction (pdftotext) of the avesta.org edition of West''s 1897 translation (public domain); name form in this edition differs from Avestan (alias recorded); chapter fixed from the chapter heading preceding the passage; contiguous-substring gate passed', 2, TRUE, 'primary verbatim (West 1897 via avesta.org); confirm the Pahlavi name = this Avestan entity and the chapter/section', 'E. W. West', 1897, 'https://www.avesta.org/mp/bundahis.html'
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ZOR_NANGHAITHYA_BUND');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_ZOR_NANGHAITHYA', 'Nakahed', 'Pahlavi form (West/Peterson spelling)', 'SRC_BUNDAHISHN', 'high', 'needs_review', 'Bundahishn, West trans.'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_ZOR_NANGHAITHYA' AND alias_name='Nakahed');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_ZOR_NANGHAITHYA', 'Naikiyas', 'Pahlavi form (West/Peterson spelling)', 'SRC_BUNDAHISHN', 'high', 'needs_review', 'Bundahishn, West trans.'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_ZOR_NANGHAITHYA' AND alias_name='Naikiyas');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ZOR_VOHU_MANAH_BUND', 'ENT_ZOR_VOHU_MANAH', 'SRC_BUNDAHISHN', 'Bundahishn (Indian recension), trans. E. W. West, Sacred Books of the East vol. 5: Pahlavi Texts Part 1 (Oxford, 1897); ed. J. H. Peterson, avesta.org (CC-BY 4.0), with modernized name spellings', 'ch. 1', 'Ohrmazd created his creatures in the confusion of Ahriman; first he produced Vohuman (“good thought”), by whom the progress of the creatures of Ohrmazd was advanced.', 'primary-verbatim', 'Vohuman is the Pahlavi form of Vohu Manah.', DATE '2026-09-18', 'full-text extraction (pdftotext) of the avesta.org edition of West''s 1897 translation (public domain); name form in this edition differs from Avestan (alias recorded); chapter fixed from the chapter heading preceding the passage; contiguous-substring gate passed', 2, TRUE, 'primary verbatim (West 1897 via avesta.org); confirm the Pahlavi name = this Avestan entity and the chapter/section', 'E. W. West', 1897, 'https://www.avesta.org/mp/bundahis.html'
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ZOR_VOHU_MANAH_BUND');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_ZOR_VOHU_MANAH', 'Vohuman', 'Pahlavi form (West/Peterson spelling)', 'SRC_BUNDAHISHN', 'high', 'needs_review', 'Bundahishn, West trans.'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_ZOR_VOHU_MANAH' AND alias_name='Vohuman');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ZOR_ASHA_VAHISHTA_BUND', 'ENT_ZOR_ASHA_VAHISHTA', 'SRC_BUNDAHISHN', 'Bundahishn (Indian recension), trans. E. W. West, Sacred Books of the East vol. 5: Pahlavi Texts Part 1 (Oxford, 1897); ed. J. H. Peterson, avesta.org (CC-BY 4.0), with modernized name spellings', 'ch. 1', 'Afterwards arose Ardwahisht, and then Shahrewar, and then Spandarmad, and then Hordad, and then Amurdad.', 'primary-verbatim', 'Ardwahisht is the Pahlavi form of Asha Vahishta.', DATE '2026-09-18', 'full-text extraction (pdftotext) of the avesta.org edition of West''s 1897 translation (public domain); name form in this edition differs from Avestan (alias recorded); chapter fixed from the chapter heading preceding the passage; contiguous-substring gate passed', 2, TRUE, 'primary verbatim (West 1897 via avesta.org); confirm the Pahlavi name = this Avestan entity and the chapter/section', 'E. W. West', 1897, 'https://www.avesta.org/mp/bundahis.html'
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ZOR_ASHA_VAHISHTA_BUND');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_ZOR_ASHA_VAHISHTA', 'Ardwahisht', 'Pahlavi form (West/Peterson spelling)', 'SRC_BUNDAHISHN', 'high', 'needs_review', 'Bundahishn, West trans.'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_ZOR_ASHA_VAHISHTA' AND alias_name='Ardwahisht');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ZOR_HAURVATAT_BUND', 'ENT_ZOR_HAURVATAT', 'SRC_BUNDAHISHN', 'Bundahishn (Indian recension), trans. E. W. West, Sacred Books of the East vol. 5: Pahlavi Texts Part 1 (Oxford, 1897); ed. J. H. Peterson, avesta.org (CC-BY 4.0), with modernized name spellings', 'ch. 1', 'Afterwards arose Ardwahisht, and then Shahrewar, and then Spandarmad, and then Hordad, and then Amurdad.', 'primary-verbatim', 'Hordad is the Pahlavi form of Haurvatat.', DATE '2026-09-18', 'full-text extraction (pdftotext) of the avesta.org edition of West''s 1897 translation (public domain); name form in this edition differs from Avestan (alias recorded); chapter fixed from the chapter heading preceding the passage; contiguous-substring gate passed', 2, TRUE, 'primary verbatim (West 1897 via avesta.org); confirm the Pahlavi name = this Avestan entity and the chapter/section', 'E. W. West', 1897, 'https://www.avesta.org/mp/bundahis.html'
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ZOR_HAURVATAT_BUND');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_ZOR_HAURVATAT', 'Hordad', 'Pahlavi form (West/Peterson spelling)', 'SRC_BUNDAHISHN', 'high', 'needs_review', 'Bundahishn, West trans.'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_ZOR_HAURVATAT' AND alias_name='Hordad');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ZOR_AMERETAT_BUND', 'ENT_ZOR_AMERETAT', 'SRC_BUNDAHISHN', 'Bundahishn (Indian recension), trans. E. W. West, Sacred Books of the East vol. 5: Pahlavi Texts Part 1 (Oxford, 1897); ed. J. H. Peterson, avesta.org (CC-BY 4.0), with modernized name spellings', 'ch. 9', 'Amerodad the archangel, as the vegetation was his own, pounded the plants small, and mixed them up with the water which Tishtar seized, and Tishtar made that water rain down upon the whole earth.', 'primary-verbatim', 'Amerodad/Amurdad is the Pahlavi form of Ameretat.', DATE '2026-09-18', 'full-text extraction (pdftotext) of the avesta.org edition of West''s 1897 translation (public domain); name form in this edition differs from Avestan (alias recorded); chapter fixed from the chapter heading preceding the passage; contiguous-substring gate passed', 2, TRUE, 'primary verbatim (West 1897 via avesta.org); confirm the Pahlavi name = this Avestan entity and the chapter/section', 'E. W. West', 1897, 'https://www.avesta.org/mp/bundahis.html'
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ZOR_AMERETAT_BUND');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_ZOR_AMERETAT', 'Amerodad', 'Pahlavi form (West/Peterson spelling)', 'SRC_BUNDAHISHN', 'high', 'needs_review', 'Bundahishn, West trans.'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_ZOR_AMERETAT' AND alias_name='Amerodad');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ZOR_YIMA_BUND', 'ENT_ZOR_YIMA', 'SRC_BUNDAHISHN', 'Bundahishn (Indian recension), trans. E. W. West, Sacred Books of the East vol. 5: Pahlavi Texts Part 1 (Oxford, 1897); ed. J. H. Peterson, avesta.org (CC-BY 4.0), with modernized name spellings', 'ch. 12', 'in the days of Yim a myriad towns and cities were erected on its pleasant and prosperous territory.', 'primary-verbatim', 'Yim is the Pahlavi form of Yima (Jamshed).', DATE '2026-09-18', 'full-text extraction (pdftotext) of the avesta.org edition of West''s 1897 translation (public domain); name form in this edition differs from Avestan (alias recorded); chapter fixed from the chapter heading preceding the passage; contiguous-substring gate passed', 2, TRUE, 'primary verbatim (West 1897 via avesta.org); confirm the Pahlavi name = this Avestan entity and the chapter/section', 'E. W. West', 1897, 'https://www.avesta.org/mp/bundahis.html'
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ZOR_YIMA_BUND');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_ZOR_YIMA', 'Yim', 'Pahlavi form (West/Peterson spelling)', 'SRC_BUNDAHISHN', 'high', 'needs_review', 'Bundahishn, West trans.'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_ZOR_YIMA' AND alias_name='Yim');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ZOR_NAIRYOSANGHA_BUND', 'ENT_ZOR_NAIRYOSANGHA', 'SRC_BUNDAHISHN', 'Bundahishn (Indian recension), trans. E. W. West, Sacred Books of the East vol. 5: Pahlavi Texts Part 1 (Oxford, 1897); ed. J. H. Peterson, avesta.org (CC-BY 4.0), with modernized name spellings', 'ch. 32', 'the angel Neryosang received the brilliance and strength of that seed, delivered it with care to the angel Anahid, and in time will blend it with a mother.', 'primary-verbatim', 'Neryosang is the Pahlavi form of Nairyosangha.', DATE '2026-09-18', 'full-text extraction (pdftotext) of the avesta.org edition of West''s 1897 translation (public domain); name form in this edition differs from Avestan (alias recorded); chapter fixed from the chapter heading preceding the passage; contiguous-substring gate passed', 2, TRUE, 'primary verbatim (West 1897 via avesta.org); confirm the Pahlavi name = this Avestan entity and the chapter/section', 'E. W. West', 1897, 'https://www.avesta.org/mp/bundahis.html'
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ZOR_NAIRYOSANGHA_BUND');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_ZOR_NAIRYOSANGHA', 'Neryosang', 'Pahlavi form (West/Peterson spelling)', 'SRC_BUNDAHISHN', 'high', 'needs_review', 'Bundahishn, West trans.'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_ZOR_NAIRYOSANGHA' AND alias_name='Neryosang');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ZOR_ASTOVIDATU_BUND', 'ENT_ZOR_ASTOVIDATU', 'SRC_BUNDAHISHN', 'Bundahishn (Indian recension), trans. E. W. West, Sacred Books of the East vol. 5: Pahlavi Texts Part 1 (Oxford, 1897); ed. J. H. Peterson, avesta.org (CC-BY 4.0), with modernized name spellings', 'ch. 28', 'Astwihad is the evil flyer (vae-i saritar) who seizes the life; as it says that, when his hand strokes a man it is lethargy, when he casts it on the sick one it is fever, when he looks in his eyes he drives away the life, and they call it death.', 'primary-verbatim', 'Astwihad is the Pahlavi form of Astovidatu.', DATE '2026-09-18', 'full-text extraction (pdftotext) of the avesta.org edition of West''s 1897 translation (public domain); name form in this edition differs from Avestan (alias recorded); chapter fixed from the chapter heading preceding the passage; contiguous-substring gate passed', 2, TRUE, 'primary verbatim (West 1897 via avesta.org); confirm the Pahlavi name = this Avestan entity and the chapter/section', 'E. W. West', 1897, 'https://www.avesta.org/mp/bundahis.html'
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ZOR_ASTOVIDATU_BUND');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_ZOR_ASTOVIDATU', 'Astwihad', 'Pahlavi form (West/Peterson spelling)', 'SRC_BUNDAHISHN', 'high', 'needs_review', 'Bundahishn, West trans.'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_ZOR_ASTOVIDATU' AND alias_name='Astwihad');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ZOR_AZ_BUND', 'ENT_ZOR_AZ', 'SRC_BUNDAHISHN', 'Bundahishn (Indian recension), trans. E. W. West, Sacred Books of the East vol. 5: Pahlavi Texts Part 1 (Oxford, 1897); ed. J. H. Peterson, avesta.org (CC-BY 4.0), with modernized name spellings', 'ch. 28', 'The demon Az (“greediness”) is he who swallows everything, and when, through destitution, nothing has come he eats himself; he is that fiendishness which, although the whole wealth of the world be given up to it, does not fill up and is not satisfied', 'primary-verbatim', 'Bundahishn''s description of the demon Az.', DATE '2026-09-18', 'full-text extraction (pdftotext) of the avesta.org edition of West''s 1897 translation (public domain); name form in this edition differs from Avestan (alias recorded); chapter fixed from the chapter heading preceding the passage; contiguous-substring gate passed', 2, TRUE, 'primary verbatim (West 1897 via avesta.org); confirm the Pahlavi name = this Avestan entity and the chapter/section', 'E. W. West', 1897, 'https://www.avesta.org/mp/bundahis.html'
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ZOR_AZ_BUND');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ZOR_NASU_BUND', 'ENT_ZOR_NASU', 'SRC_BUNDAHISHN', 'Bundahishn (Indian recension), trans. E. W. West, Sacred Books of the East vol. 5: Pahlavi Texts Part 1 (Oxford, 1897); ed. J. H. Peterson, avesta.org (CC-BY 4.0), with modernized name spellings', 'ch. 28', 'The demon Nas is he who causes the pollution and contamination (nisrushtih), which they call nasai (“dead matter”).', 'primary-verbatim', 'Nas is the Pahlavi form of Nasu.', DATE '2026-09-18', 'full-text extraction (pdftotext) of the avesta.org edition of West''s 1897 translation (public domain); name form in this edition differs from Avestan (alias recorded); chapter fixed from the chapter heading preceding the passage; contiguous-substring gate passed', 2, TRUE, 'primary verbatim (West 1897 via avesta.org); confirm the Pahlavi name = this Avestan entity and the chapter/section', 'E. W. West', 1897, 'https://www.avesta.org/mp/bundahis.html'
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ZOR_NASU_BUND');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_ZOR_NASU', 'Nas', 'Pahlavi form (West/Peterson spelling)', 'SRC_BUNDAHISHN', 'high', 'needs_review', 'Bundahishn, West trans.'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_ZOR_NASU' AND alias_name='Nas');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_RLMX_GAROTHMAN_BUND', 'ENT_RLMX_GAROTHMAN', 'SRC_BUNDAHISHN', 'Bundahishn (Indian recension), trans. E. W. West, Sacred Books of the East vol. 5: Pahlavi Texts Part 1 (Oxford, 1897); ed. J. H. Peterson, avesta.org (CC-BY 4.0), with modernized name spellings', 'ch. 30', 'Afterwards, they set the righteous man apart from the wicked; and then the righteous is for heaven (garothman), and they cast the wicked back to hell.', 'primary-verbatim', 'Garothman (Garodman) as the heaven of the righteous at the renovation.', DATE '2026-09-18', 'full-text extraction (pdftotext) of the avesta.org edition of West''s 1897 translation (public domain); name form in this edition differs from Avestan (alias recorded); chapter fixed from the chapter heading preceding the passage; contiguous-substring gate passed', 2, TRUE, 'primary verbatim (West 1897 via avesta.org); confirm the Pahlavi name = this Avestan entity and the chapter/section', 'E. W. West', 1897, 'https://www.avesta.org/mp/bundahis.html'
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_RLMX_GAROTHMAN_BUND');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ZOR_DRUJ_BUND', 'ENT_ZOR_DRUJ', 'SRC_BUNDAHISHN', 'Bundahishn (Indian recension), trans. E. W. West, Sacred Books of the East vol. 5: Pahlavi Texts Part 1 (Oxford, 1897); ed. J. H. Peterson, avesta.org (CC-BY 4.0), with modernized name spellings', 'ch. 2', 'that you shall contend in a bodily form with the fiend (druj), and the fiend shall perish, and in the end I shall have you prepared again perfect and immortal', 'primary-verbatim', 'The druj as the fiend against whom the guardian spirits are sent into the world.', DATE '2026-09-18', 'full-text extraction (pdftotext) of the avesta.org edition of West''s 1897 translation (public domain); name form in this edition differs from Avestan (alias recorded); chapter fixed from the chapter heading preceding the passage; contiguous-substring gate passed', 2, TRUE, 'primary verbatim (West 1897 via avesta.org); confirm the Pahlavi name = this Avestan entity and the chapter/section', 'E. W. West', 1897, 'https://www.avesta.org/mp/bundahis.html'
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ZOR_DRUJ_BUND');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ZOR_DAEVAS_BUND', 'ENT_ZOR_DAEVAS', 'SRC_BUNDAHISHN', 'Bundahishn (Indian recension), trans. E. W. West, Sacred Books of the East vol. 5: Pahlavi Texts Part 1 (Oxford, 1897); ed. J. H. Peterson, avesta.org (CC-BY 4.0), with modernized name spellings', 'ch. 1', 'so he fled back to the gloomy darkness, and formed many demons and fiends; and the creatures of the destroyer arose for violence.', 'primary-verbatim', 'Ahriman''s formation of the demons (dev = daeva) at the first assault.', DATE '2026-09-18', 'full-text extraction (pdftotext) of the avesta.org edition of West''s 1897 translation (public domain); name form in this edition differs from Avestan (alias recorded); chapter fixed from the chapter heading preceding the passage; contiguous-substring gate passed', 2, TRUE, 'primary verbatim (West 1897 via avesta.org); confirm the Pahlavi name = this Avestan entity and the chapter/section', 'E. W. West', 1897, 'https://www.avesta.org/mp/bundahis.html'
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ZOR_DAEVAS_BUND');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ZOR_VERETHRAGNA_BUND', 'ENT_ZOR_VERETHRAGNA', 'SRC_BUNDAHISHN', 'Bundahishn (Indian recension), trans. E. W. West, Sacred Books of the East vol. 5: Pahlavi Texts Part 1 (Oxford, 1897); ed. J. H. Peterson, avesta.org (CC-BY 4.0), with modernized name spellings', 'ch. 17', 'the fire Spenisht, the fire which they keep in use in the world, likewise the fire of Warharan.', 'primary-verbatim', 'Warharan is the Pahlavi form of Verethragna (the Bahram fire).', DATE '2026-09-18', 'full-text extraction (pdftotext) of the avesta.org edition of West''s 1897 translation (public domain); name form in this edition differs from Avestan (alias recorded); chapter fixed from the chapter heading preceding the passage; contiguous-substring gate passed', 2, TRUE, 'primary verbatim (West 1897 via avesta.org); confirm the Pahlavi name = this Avestan entity and the chapter/section', 'E. W. West', 1897, 'https://www.avesta.org/mp/bundahis.html'
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ZOR_VERETHRAGNA_BUND');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_ZOR_VERETHRAGNA', 'Warharan', 'Pahlavi form (West/Peterson spelling)', 'SRC_BUNDAHISHN', 'high', 'needs_review', 'Bundahishn, West trans.'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_ZOR_VERETHRAGNA' AND alias_name='Warharan');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ZOR_ATAR_BUND', 'ENT_ZOR_ATAR', 'SRC_BUNDAHISHN', 'Bundahishn (Indian recension), trans. E. W. West, Sacred Books of the East vol. 5: Pahlavi Texts Part 1 (Oxford, 1897); ed. J. H. Peterson, avesta.org (CC-BY 4.0), with modernized name spellings', 'ch. 27', 'Adar has the marigold (adargun), the water-lily is Aban’s, the white marv is Khwarshed’s, the ranges is Mah’s', 'primary-verbatim', 'Adar (the yazata of fire) in the list of flowers proper to each divinity; the same clause also names Mah.', DATE '2026-09-18', 'full-text extraction (pdftotext) of the avesta.org edition of West''s 1897 translation (public domain); name form in this edition differs from Avestan (alias recorded); chapter fixed from the chapter heading preceding the passage; contiguous-substring gate passed', 2, TRUE, 'primary verbatim (West 1897 via avesta.org); confirm the Pahlavi name = this Avestan entity and the chapter/section', 'E. W. West', 1897, 'https://www.avesta.org/mp/bundahis.html'
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ZOR_ATAR_BUND');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_ZOR_ATAR', 'Adar', 'Pahlavi form (West/Peterson spelling)', 'SRC_BUNDAHISHN', 'high', 'needs_review', 'Bundahishn, West trans.'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_ZOR_ATAR' AND alias_name='Adar');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ZOR_MAH_BUND', 'ENT_ZOR_MAH', 'SRC_BUNDAHISHN', 'Bundahishn (Indian recension), trans. E. W. West, Sacred Books of the East vol. 5: Pahlavi Texts Part 1 (Oxford, 1897); ed. J. H. Peterson, avesta.org (CC-BY 4.0), with modernized name spellings', 'ch. 27', 'Adar has the marigold (adargun), the water-lily is Aban’s, the white marv is Khwarshed’s, the ranges is Mah’s', 'primary-verbatim', 'Mah (the Moon yazata) in the list of flowers proper to each divinity.', DATE '2026-09-18', 'full-text extraction (pdftotext) of the avesta.org edition of West''s 1897 translation (public domain); name form in this edition differs from Avestan (alias recorded); chapter fixed from the chapter heading preceding the passage; contiguous-substring gate passed', 2, TRUE, 'primary verbatim (West 1897 via avesta.org); confirm the Pahlavi name = this Avestan entity and the chapter/section', 'E. W. West', 1897, 'https://www.avesta.org/mp/bundahis.html'
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ZOR_MAH_BUND');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_JM_KETEV_MERIRI_JASTROW', 'ENT_JM_KETEV_MERIRI', 'SRC_JASTROW_DICT', 'Marcus Jastrow, A Dictionary of the Targumim, the Talmud Babli and Yerushalmi, and the Midrashic Literature (London/New York, 1903)', 'vol. 2, s.v. קטב (qeteb)', 'Keteb (M''riri), name of a demon.', 'reference', 'Jastrow''s lexical entry identifying Keteb Meriri as a demon, with Midrashic references (Num. R. 12; Lam. R. to I,3; Midr. Till. Ps. 91:6).', DATE '2026-09-18', 'full-text extraction (pdftotext) of the 1903 dictionary (public domain); Hebrew headwords are OCR-garbled, so only entries whose Latin-letter gloss names the entity were accepted; contiguous-substring gate passed on the English gloss', 1, TRUE, 'reference-grade lexical attestation; confirm entry and page in the printed Jastrow', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_JM_KETEV_MERIRI_JASTROW');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_JM_DUMAH_JASTROW', 'ENT_JM_DUMAH', 'SRC_JASTROW_DICT', 'Marcus Jastrow, A Dictionary of the Targumim, the Talmud Babli and Yerushalmi, and the Midrashic Literature (London/New York, 1903)', 'vol. 1, s.v. דומה II', 'Dumah, the guardian angel of the deceased.', 'reference', 'Jastrow''s lexical entry for Dumah with Talmudic references (Ber. 18b; Hag. 5a).', DATE '2026-09-18', 'full-text extraction (pdftotext) of the 1903 dictionary (public domain); Hebrew headwords are OCR-garbled, so only entries whose Latin-letter gloss names the entity were accepted; contiguous-substring gate passed on the English gloss', 1, TRUE, 'reference-grade lexical attestation; confirm entry and page in the printed Jastrow', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_JM_DUMAH_JASTROW');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_JM_LILIN_JASTROW', 'ENT_JM_LILIN', 'SRC_JASTROW_DICT', 'Marcus Jastrow, A Dictionary of the Targumim, the Talmud Babli and Yerushalmi, and the Midrashic Literature (London/New York, 1903)', 'vol. 2, s.v. לילין (pl.), glossed "night-demons"', NULL, 'reference', 'Jastrow glosses the plural headword as ''night-demons'' with Targumic references (Targ. Y. Num. 6:24; Deut. 32:24; Targ. Is. 34:14); pointer only because the Hebrew headword is OCR-lost in the extraction.', DATE '2026-09-18', 'entry located by its English gloss and Targumic references in the pdftotext extraction; headword not machine-legible, so NO text reproduced - pointer only', 1, TRUE, 'reference pointer; verify the headword in the printed Jastrow', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_JM_LILIN_JASTROW');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISR_ZIZ_JASTROW', 'ENT_ISR_ZIZ', 'SRC_JASTROW_DICT', 'Marcus Jastrow, A Dictionary of the Targumim, the Talmud Babli and Yerushalmi, and the Midrashic Literature (London/New York, 1903)', 'vol. 1, s.v. זיז (2), "name of a fabulous bird"', NULL, 'reference', 'Jastrow''s entry (2) glosses the word as the name of a fabulous bird with reference to Ps. 50:11, Lev. R. 22 and B. Bath. 73b; pointer only because the extraction of the entry is OCR-garbled.', DATE '2026-09-18', 'entry located by its English gloss in the pdftotext extraction; entry text garbled, so NO text reproduced - pointer only', 1, TRUE, 'reference pointer; verify the entry in the printed Jastrow', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISR_ZIZ_JASTROW');

UPDATE entity_citations SET quote='I mean the dæmons, heroes, and uncontaminate souls.', evidence_grade='primary-verbatim', work_title='Iamblichus, Theurgia, or The Egyptian Mysteries (De Mysteriis), trans. Alexander Wilder (New York, 1911)', locus='Part I (the superior races after the gods)', evidence_note='Iamblichus names the heroes among the superior races (gods, daemons, heroes, souls).', verify_method='full-text extraction (pdftotext) of the 1911 Wilder translation (public domain, previously extracted corpus); quote located by word-boundary search in the translation body (not the editorial introduction); contiguous-substring gate passed', review_reason='primary verbatim from Wilder 1911; confirm section (De Myst. I.3-4)', translator='Alexander Wilder', translation_year=1911, verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_LAT_HEROES_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

UPDATE entity_citations SET quote='I mean the dæmons, heroes, and uncontaminate souls.', evidence_grade='primary-verbatim', work_title='Iamblichus, Theurgia, or The Egyptian Mysteries (De Mysteriis), trans. Alexander Wilder (New York, 1911)', locus='Part I (the superior races after the gods)', evidence_note='Wilder renders the class of pure/purified souls as ''uncontaminate souls''; listed by Iamblichus among the superior races.', verify_method='full-text extraction (pdftotext) of the 1911 Wilder translation (public domain, previously extracted corpus); quote located by word-boundary search in the translation body; contiguous-substring gate passed', review_reason='primary verbatim from Wilder 1911; confirm that Wilder''s "uncontaminate souls" is this entity (achrantoi psychai)', translator='Alexander Wilder', translation_year=1911, verified_on=DATE '2026-09-18', needs_review=TRUE
WHERE citation_id='CIT_LAT_PURIFIED_SOULS_SEC' AND evidence_grade='primary-uncited' AND quote IS NULL;

COMMIT;
