-- build_enochian.sql  (GENERATED by gen_enochian.py) — v1.71.0
-- The Enochian system of John Dee: Heptarchia kings/princes, the Four Watchtowers, the Thirty Aethyrs.
-- 19 new entities, 22 edges. Idempotent + self-validating.
BEGIN;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_DEE_ENOCHIAN','primary text','John Dee & Edward Kelley, the Enochian diaries (Heptarchia Mystica; Liber Loagaeth; Liber Scientiae / the Aethyrs), Sloane MSS','Renaissance Esoteric')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_REN_ENOCHIAN','The Enochian System of John Dee','Collective','Enochian system','angelic revelation; the divine (Enochian) language; theurgic cosmology','B','The integrated angelic-magical system received by John Dee and Edward Kelley 1581-1587 across the Heptarchia Mystica, Liber Loagaeth, and Liber Scientiae (the Aethyrs and Great Table); its component structures are well documented even where individual angel names vary between manuscripts.'),
 ('ENT_REN_CARMARA','Carmara','Enochian king','Enochian angel','chief governance of the Heptarchic kings; presidency of the heptarchic order','B','The overarching/chief king coordinating the seven in the Heptarchia; Dee''s records suggest Carmara and Baligon may be two names/aspects of the same governing king (flagged as a manuscript ambiguity).'),
 ('ENT_REN_BALIGON','Baligon','Enochian king','Enochian angel','government of the air; closely identified with Carmara''s office','C','A Heptarchic king frequently equated with Carmara in Dee''s diaries; the relationship between the names Baligon and Carmara is genuinely ambiguous in the records.'),
 ('ENT_REN_BOBOGEL','Bobogel','Enochian king','Enochian angel','government of his day; commonly associated with wisdom/Mercury','B','One of the seven Heptarchic kings; the Wednesday/Mercury correspondence follows the common reading, but planetary-day assignments vary between reconstructions of Dee''s tables.'),
 ('ENT_REN_BABALEL','Babalel','Enochian king','Enochian angel','government of his day; the waters and martial force (Mars)','B','One of the seven Heptarchic kings, linked to Mars and to dominion over the seas in Dee''s notes; precise planetary-day mapping is subject to manuscript variation.'),
 ('ENT_REN_BNASPOL','Bnaspol','Enochian king','Enochian angel','government of his day; the earth and its riches (Saturn)','B','One of the seven Heptarchic kings, linked to dominion over the earth; the Saturn correspondence follows the standard reading but day/planet assignments are not uniformly fixed.'),
 ('ENT_REN_BYNEPOR','Bynepor','Enochian king','Enochian angel','government of his day; life and the estate of nature (Jupiter)','B','One of the seven Heptarchic kings, associated with life and the universal preservation of nature; the Jupiter correspondence is the common reading and varies between reconstructions.'),
 ('ENT_REN_BNAPSEN','Bnapsen','Enochian king','Enochian angel','government of his day; countering evil spirits','C','One of the seven Heptarchic kings; its day/planet assignment (often given as Friday) is among the least stable in the records and is flagged as uncertain.'),
 ('ENT_REN_HAGONEL','Hagonel','Enochian prince','Enochian angel','princely ministry serving the chief king; mediation of his authority','B','The prince attached to the chief king (Carmara/Baligon) and the most prominent of the seven princes in Dee''s diaries.'),
 ('ENT_REN_BORNOGO','Bornogo','Enochian prince','Enochian angel','princely ministry serving his governing king','C','Listed among the seven Heptarchic princes in Dee''s tables; the exact spelling and the king served vary between manuscript readings (flagged uncertain).'),
 ('ENT_REN_BEFAFES','Befafes','Enochian prince','Enochian angel','princely ministry serving his governing king; associated in some readings with the waters','C','Listed among the seven Heptarchic princes; pairing to a specific king and spelling vary across Dee''s tables (flagged uncertain).'),
 ('ENT_REN_BUTMONO','Butmono','Enochian prince','Enochian angel','princely ministry serving his governing king','C','Listed among the seven Heptarchic princes; the spelling and king served are subject to manuscript variation (flagged uncertain).'),
 ('ENT_REN_BLISDON','Blisdon','Enochian prince','Enochian angel','princely ministry serving his governing king','C','Listed among the seven Heptarchic princes; spelling and king-assignment vary across readings of Dee''s tables (flagged uncertain).'),
 ('ENT_REN_BRALGES','Bralges','Enochian prince','Enochian angel','princely ministry serving his governing king','C','Listed among the seven Heptarchic princes; the spelling and king served vary in the manuscripts (flagged uncertain).'),
 ('ENT_REN_BAGENOL','Bagenol','Enochian prince','Enochian angel','princely ministry serving his governing king','C','Listed among the seven Heptarchic princes; spelling and king-pairing are uncertain across Dee''s tables (flagged uncertain).'),
 ('ENT_REN_WATCHTOWERS','The Four Enochian Watchtowers (Great Table)','Collective','Enochian realm','elemental governance of the four quarters (Air/East, Water/West, Earth/North, Fire/South)','B','The four great elemental tablets of the Great Table received by Dee and Kelley, each governing one element and quarter; the individual square-angels and elemental Great Kings are deliberately not enumerated to avoid invention.'),
 ('ENT_REN_AETHYRS','The Thirty Aethyrs (Aires) of the Enochian System','Collective','Enochian realm','thirty graded spiritual spheres enclosing creation, from lowest to highest heaven','B','Thirty concentric Aethyrs recorded in Liber Scientiae, ascending from TEX (the 30th, lowest) to LIL (the 1st, highest); only the firmly attested example aethyrs are listed individually.'),
 ('ENT_REN_AETHYR_LIL','LIL','cosmological realm','Enochian realm','the first and highest Aethyr, nearest the divine','B','Named in Liber Scientiae as the first (highest) of the thirty Aethyrs; firmly attested in Dee''s records.'),
 ('ENT_REN_AETHYR_TEX','TEX','cosmological realm','Enochian realm','the thirtieth and lowest Aethyr, nearest the material world','B','Named in Liber Scientiae as the thirtieth (lowest) of the thirty Aethyrs; firmly attested in Dee''s records.');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,'Renaissance Esoteric',etype,cat,dom,'literary',conf,'candidate_verified_name','Enochian system of John Dee (v1.71.0)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,note text,etype text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_REN_ENOCHIAN','SRC_DEE_ENOCHIAN','The integrated angelic-magical system received by John Dee and Edward Kelley 1581-1587 across the Heptarchia Mystica, Liber Loagaeth, and Liber Scientiae (the Aethyrs and Great Table); its component structures are well documented even where individual angel names vary between manuscripts.','primary text attestation'),
 ('ENT_REN_CARMARA','SRC_DEE_ENOCHIAN','The overarching/chief king coordinating the seven in the Heptarchia; Dee''s records suggest Carmara and Baligon may be two names/aspects of the same governing king (flagged as a manuscript ambiguity).','primary text attestation'),
 ('ENT_REN_BALIGON','SRC_DEE_ENOCHIAN','A Heptarchic king frequently equated with Carmara in Dee''s diaries; the relationship between the names Baligon and Carmara is genuinely ambiguous in the records.','primary text attestation'),
 ('ENT_REN_BOBOGEL','SRC_DEE_ENOCHIAN','One of the seven Heptarchic kings; the Wednesday/Mercury correspondence follows the common reading, but planetary-day assignments vary between reconstructions of Dee''s tables.','primary text attestation'),
 ('ENT_REN_BABALEL','SRC_DEE_ENOCHIAN','One of the seven Heptarchic kings, linked to Mars and to dominion over the seas in Dee''s notes; precise planetary-day mapping is subject to manuscript variation.','primary text attestation'),
 ('ENT_REN_BNASPOL','SRC_DEE_ENOCHIAN','One of the seven Heptarchic kings, linked to dominion over the earth; the Saturn correspondence follows the standard reading but day/planet assignments are not uniformly fixed.','primary text attestation'),
 ('ENT_REN_BYNEPOR','SRC_DEE_ENOCHIAN','One of the seven Heptarchic kings, associated with life and the universal preservation of nature; the Jupiter correspondence is the common reading and varies between reconstructions.','primary text attestation'),
 ('ENT_REN_BNAPSEN','SRC_DEE_ENOCHIAN','One of the seven Heptarchic kings; its day/planet assignment (often given as Friday) is among the least stable in the records and is flagged as uncertain.','primary text attestation'),
 ('ENT_REN_HAGONEL','SRC_DEE_ENOCHIAN','The prince attached to the chief king (Carmara/Baligon) and the most prominent of the seven princes in Dee''s diaries.','primary text attestation'),
 ('ENT_REN_BORNOGO','SRC_DEE_ENOCHIAN','Listed among the seven Heptarchic princes in Dee''s tables; the exact spelling and the king served vary between manuscript readings (flagged uncertain).','primary text attestation'),
 ('ENT_REN_BEFAFES','SRC_DEE_ENOCHIAN','Listed among the seven Heptarchic princes; pairing to a specific king and spelling vary across Dee''s tables (flagged uncertain).','primary text attestation'),
 ('ENT_REN_BUTMONO','SRC_DEE_ENOCHIAN','Listed among the seven Heptarchic princes; the spelling and king served are subject to manuscript variation (flagged uncertain).','primary text attestation'),
 ('ENT_REN_BLISDON','SRC_DEE_ENOCHIAN','Listed among the seven Heptarchic princes; spelling and king-assignment vary across readings of Dee''s tables (flagged uncertain).','primary text attestation'),
 ('ENT_REN_BRALGES','SRC_DEE_ENOCHIAN','Listed among the seven Heptarchic princes; the spelling and king served vary in the manuscripts (flagged uncertain).','primary text attestation'),
 ('ENT_REN_BAGENOL','SRC_DEE_ENOCHIAN','Listed among the seven Heptarchic princes; spelling and king-pairing are uncertain across Dee''s tables (flagged uncertain).','primary text attestation'),
 ('ENT_REN_WATCHTOWERS','SRC_DEE_ENOCHIAN','The four great elemental tablets of the Great Table received by Dee and Kelley, each governing one element and quarter; the individual square-angels and elemental Great Kings are deliberately not enumerated to avoid invention.','primary text attestation'),
 ('ENT_REN_AETHYRS','SRC_DEE_ENOCHIAN','Thirty concentric Aethyrs recorded in Liber Scientiae, ascending from TEX (the 30th, lowest) to LIL (the 1st, highest); only the firmly attested example aethyrs are listed individually.','primary text attestation'),
 ('ENT_REN_AETHYR_LIL','SRC_DEE_ENOCHIAN','Named in Liber Scientiae as the first (highest) of the thirty Aethyrs; firmly attested in Dee''s records.','primary text attestation'),
 ('ENT_REN_AETHYR_TEX','SRC_DEE_ENOCHIAN','Named in Liber Scientiae as the thirtieth (lowest) of the thirty Aethyrs; firmly attested in Dee''s records.','primary text attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_REN_ENOCHIAN','PER_EARLY_MODERN_OCCULT','The integrated angelic-magical system received by John Dee and Edward Kelley 1581-1587 across the Heptarchia Mystica, Liber Loagaeth, and Liber Scientiae (the Aethyrs and Great Table); its component structures are well documented even where individual angel names vary between manuscripts.'),
 ('ENT_REN_CARMARA','PER_EARLY_MODERN_OCCULT','The overarching/chief king coordinating the seven in the Heptarchia; Dee''s records suggest Carmara and Baligon may be two names/aspects of the same governing king (flagged as a manuscript ambiguity).'),
 ('ENT_REN_BALIGON','PER_EARLY_MODERN_OCCULT','A Heptarchic king frequently equated with Carmara in Dee''s diaries; the relationship between the names Baligon and Carmara is genuinely ambiguous in the records.'),
 ('ENT_REN_BOBOGEL','PER_EARLY_MODERN_OCCULT','One of the seven Heptarchic kings; the Wednesday/Mercury correspondence follows the common reading, but planetary-day assignments vary between reconstructions of Dee''s tables.'),
 ('ENT_REN_BABALEL','PER_EARLY_MODERN_OCCULT','One of the seven Heptarchic kings, linked to Mars and to dominion over the seas in Dee''s notes; precise planetary-day mapping is subject to manuscript variation.'),
 ('ENT_REN_BNASPOL','PER_EARLY_MODERN_OCCULT','One of the seven Heptarchic kings, linked to dominion over the earth; the Saturn correspondence follows the standard reading but day/planet assignments are not uniformly fixed.'),
 ('ENT_REN_BYNEPOR','PER_EARLY_MODERN_OCCULT','One of the seven Heptarchic kings, associated with life and the universal preservation of nature; the Jupiter correspondence is the common reading and varies between reconstructions.'),
 ('ENT_REN_BNAPSEN','PER_EARLY_MODERN_OCCULT','One of the seven Heptarchic kings; its day/planet assignment (often given as Friday) is among the least stable in the records and is flagged as uncertain.'),
 ('ENT_REN_HAGONEL','PER_EARLY_MODERN_OCCULT','The prince attached to the chief king (Carmara/Baligon) and the most prominent of the seven princes in Dee''s diaries.'),
 ('ENT_REN_BORNOGO','PER_EARLY_MODERN_OCCULT','Listed among the seven Heptarchic princes in Dee''s tables; the exact spelling and the king served vary between manuscript readings (flagged uncertain).'),
 ('ENT_REN_BEFAFES','PER_EARLY_MODERN_OCCULT','Listed among the seven Heptarchic princes; pairing to a specific king and spelling vary across Dee''s tables (flagged uncertain).'),
 ('ENT_REN_BUTMONO','PER_EARLY_MODERN_OCCULT','Listed among the seven Heptarchic princes; the spelling and king served are subject to manuscript variation (flagged uncertain).'),
 ('ENT_REN_BLISDON','PER_EARLY_MODERN_OCCULT','Listed among the seven Heptarchic princes; spelling and king-assignment vary across readings of Dee''s tables (flagged uncertain).'),
 ('ENT_REN_BRALGES','PER_EARLY_MODERN_OCCULT','Listed among the seven Heptarchic princes; the spelling and king served vary in the manuscripts (flagged uncertain).'),
 ('ENT_REN_BAGENOL','PER_EARLY_MODERN_OCCULT','Listed among the seven Heptarchic princes; spelling and king-pairing are uncertain across Dee''s tables (flagged uncertain).'),
 ('ENT_REN_WATCHTOWERS','PER_EARLY_MODERN_OCCULT','The four great elemental tablets of the Great Table received by Dee and Kelley, each governing one element and quarter; the individual square-angels and elemental Great Kings are deliberately not enumerated to avoid invention.'),
 ('ENT_REN_AETHYRS','PER_EARLY_MODERN_OCCULT','Thirty concentric Aethyrs recorded in Liber Scientiae, ascending from TEX (the 30th, lowest) to LIL (the 1st, highest); only the firmly attested example aethyrs are listed individually.'),
 ('ENT_REN_AETHYR_LIL','PER_EARLY_MODERN_OCCULT','Named in Liber Scientiae as the first (highest) of the thirty Aethyrs; firmly attested in Dee''s records.'),
 ('ENT_REN_AETHYR_TEX','PER_EARLY_MODERN_OCCULT','Named in Liber Scientiae as the thirtieth (lowest) of the thirty Aethyrs; firmly attested in Dee''s records.');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_REN_CARMARA','member_of','ENT_REN_ENOCHIAN','high','Carmara is the chief Heptarchic king of the system.'),
 ('ENT_REN_BALIGON','member_of','ENT_REN_ENOCHIAN','medium','Baligon is a Heptarchic king, frequently identified with the Carmara office.'),
 ('ENT_REN_BOBOGEL','member_of','ENT_REN_ENOCHIAN','high','One of the seven Heptarchic kings.'),
 ('ENT_REN_BABALEL','member_of','ENT_REN_ENOCHIAN','high','One of the seven Heptarchic kings.'),
 ('ENT_REN_BNASPOL','member_of','ENT_REN_ENOCHIAN','high','One of the seven Heptarchic kings.'),
 ('ENT_REN_BYNEPOR','member_of','ENT_REN_ENOCHIAN','high','One of the seven Heptarchic kings.'),
 ('ENT_REN_BNAPSEN','member_of','ENT_REN_ENOCHIAN','high','One of the seven Heptarchic kings.'),
 ('ENT_REN_HAGONEL','member_of','ENT_REN_ENOCHIAN','high','Hagonel is a Heptarchic prince of the system.'),
 ('ENT_REN_BORNOGO','member_of','ENT_REN_ENOCHIAN','medium','Listed among the seven Heptarchic princes.'),
 ('ENT_REN_BEFAFES','member_of','ENT_REN_ENOCHIAN','medium','Listed among the seven Heptarchic princes.'),
 ('ENT_REN_BUTMONO','member_of','ENT_REN_ENOCHIAN','medium','Listed among the seven Heptarchic princes.'),
 ('ENT_REN_BLISDON','member_of','ENT_REN_ENOCHIAN','medium','Listed among the seven Heptarchic princes.'),
 ('ENT_REN_BRALGES','member_of','ENT_REN_ENOCHIAN','medium','Listed among the seven Heptarchic princes.'),
 ('ENT_REN_BAGENOL','member_of','ENT_REN_ENOCHIAN','medium','Listed among the seven Heptarchic princes.'),
 ('ENT_REN_HAGONEL','mediated_by','ENT_REN_CARMARA','medium','Hagonel serves and mediates the authority of the chief king Carmara (the Carmara/Baligon office).'),
 ('ENT_REN_WATCHTOWERS','member_of','ENT_REN_ENOCHIAN','high','The Four Watchtowers (Great Table) are a core structure of the Enochian system.'),
 ('ENT_REN_AETHYRS','member_of','ENT_REN_ENOCHIAN','high','The Thirty Aethyrs are a core structure of the Enochian system.'),
 ('ENT_REN_AETHYR_LIL','member_of','ENT_REN_AETHYRS','high','LIL is the first of the thirty Aethyrs.'),
 ('ENT_REN_AETHYR_TEX','member_of','ENT_REN_AETHYRS','high','TEX is the thirtieth of the thirty Aethyrs.'),
 ('ENT_REN_ENOCHIAN','transmits','ENT_REVELATION','high','The Enochian system was received as an angelic revelation and is fundamentally a vehicle of divine disclosure.'),
 ('ENT_REN_ENOCHIAN','presides_over','ENT_HIDDEN_KNOWLEDGE','medium','The system governs access to a hidden angelic language and secret cosmological knowledge.'),
 ('ENT_REN_BABALEL','presides_over','ENT_WAR','medium','Babalel is associated with Mars and martial force in Dee''s records.');

\echo '--- REJECTED edges (bad id/type/source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
