-- build_druze.sql  (GENERATED by gen_roster.py druze) — v1.80.0
-- 16 entities, 26 edges, 1 new periods, 3 new sources. Idempotent + self-validating.
BEGIN;

INSERT INTO periods (period_id, period_name, start_year, end_year) VALUES
 ('PER_DRUZE','Druze Tradition (Fatimid origins to present)',1017,2025)
ON CONFLICT (period_id) DO NOTHING;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_ABU_IZZEDDIN_DRUZES','secondary scholarship','Nejla M. Abu-Izzeddin, The Druzes: A New Study of Their History, Faith and Society (Brill, 1984)','Druze history, doctrine of tawhid, the hudud, al-Hakim, al-Darazi, Hamza, transmigration'),
 ('SRC_FIRRO_DRUZES','secondary scholarship','Kais M. Firro, A History of the Druzes (Brill, 1992)','Druze social and political history; community formation in the Levant'),
 ('SRC_DAFTARY_ISMAILIS','secondary scholarship','Farhad Daftary, The Ismailis: Their History and Doctrines, 2nd ed. (Cambridge UP, 2007)','Fatimid Ismaili background; al-Hakim''s reign; the Druze schism')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,trad text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_DRZ_HUDUD','Al-Hudud al-Khamsa (The Five Cosmic Luminaries)','collective','emanation hierarchy','Druze','cosmology','B','Collective hub: the five cosmic ranks (al-hudud al-ulwiyya) through which the divine unity is mediated in Druze cosmology; attested in Abu-Izzeddin and standard scholarship.'),
 ('ENT_DRZ_AL_AQL','Al-Aql al-Kulli (the Universal Intellect)','hypostasis','luminary','Druze','cosmology','B','First and highest of the five luminaries, the Universal Intellect; held to be manifested in Hamza ibn Ali. Attested doctrine.'),
 ('ENT_DRZ_AL_NAFS','Al-Nafs al-Kulliyya (the Universal Soul)','hypostasis','luminary','Druze','cosmology','B','Second luminary, the Universal Soul, emanating from the Intellect; associated with Abu Ibrahim Isma''il al-Tamimi.'),
 ('ENT_DRZ_AL_KALIMA','Al-Kalima (the Word)','hypostasis','luminary','Druze','cosmology','B','Third luminary, the Word/Logos; associated with Muhammad ibn Wahb al-Tamimi. Attested.'),
 ('ENT_DRZ_AL_SABIQ','Al-Sabiq (the Preceder / Right Wing)','hypostasis','luminary','Druze','cosmology','B','Fourth luminary, the Preceder (also ''the Right Wing''); associated with Salama ibn Abd al-Wahhab. Attested.'),
 ('ENT_DRZ_AL_TALI','Al-Tali (the Follower / Left Wing)','hypostasis','luminary','Druze','cosmology','B','Fifth luminary, the Follower (also ''the Left Wing''); associated with Baha al-Din al-Muqtana. Attested.'),
 ('ENT_DRZ_HAMZA','Hamza ibn Ali ibn Ahmad','person','luminary-incarnation','Druze','founder','B','Persian founder-theologian of the Druze daʿwa (fl. 1017-21); chief organizer, held as the human manifestation of al-Aql (Universal Intellect). Historically attested. HOMONYM: distinct from ENT_ISL_HAMZA (Hamza ibn Abd al-Muttalib, uncle of the Prophet Muhammad).'),
 ('ENT_DRZ_ABU_IBRAHIM','Abu Ibrahim Isma''il al-Tamimi','person','luminary-incarnation','Druze','founder','C','Early Druze daʿi associated with the rank of al-Nafs (Universal Soul). Attested in Druze epistolary tradition.'),
 ('ENT_DRZ_AL_TAMIMI','Muhammad ibn Wahb al-Qurashi al-Tamimi','person','luminary-incarnation','Druze','founder','C','Early Druze daʿi associated with the rank of al-Kalima (the Word). HOMONYM: distinct from the Prophet Muhammad (ENT_ISL_MUHAMMAD).'),
 ('ENT_DRZ_SALAMA','Salama ibn Abd al-Wahhab','person','luminary-incarnation','Druze','founder','C','Early Druze daʿi associated with the rank of al-Sabiq (the Preceder). Attested.'),
 ('ENT_DRZ_MUQTANA','Baha al-Din al-Muqtana al-Samuqi','person','luminary-incarnation','Druze','founder','B','Druze daʿi (fl. 1027-43) who compiled much of the Rasaʾil al-Hikma (Epistles of Wisdom) and sealed the daʿwa; held as the manifestation of al-Tali (the Follower). Attested.'),
 ('ENT_DRZ_AL_HAKIM','Al-Hakim bi-Amr Allah','person','divine-manifestation','Druze','theophany','B','Sixth Fatimid caliph-imam (r.996-1021); in Druze belief the manifestation (mazhar/tajalli) of the divine unity. Historically attested Fatimid ruler; his divinity is a confessional Druze claim, modeled descriptively.'),
 ('ENT_DRZ_AL_DARAZI','Muhammad al-Darazi (Nashtakin al-Darazi)','person','heresiarch','Druze','founder','B','Early daʿi (d. c.1018) whose extremist preaching gave the community its exonym ''Druze''; later repudiated by Hamza as a heretic. Historically attested.'),
 ('ENT_DRZ_TAQAMMUS','Taqammus (transmigration of souls)','concept','doctrine','Druze','soteriology','B','Druze doctrine that the fixed number of souls transmigrate immediately from body to body (taqammus); a defining publicly attested tenet.'),
 ('ENT_DRZ_TAWHID','Tawhid (the Druze doctrine of divine unity)','concept','doctrine','Druze','theology','B','The unitarian core from which the Druze self-designation Muwahhidun (''Unitarians'') derives; God beyond attributes, mediated through the hudud. Attested.'),
 ('ENT_DRZ_RASAIL','Rasaʾil al-Hikma (Epistles of Wisdom)','text','canon','Druze','scripture','B','The 111-epistle Druze sacred canon, largely by Hamza and al-Muqtana; foundational closed scripture. Existence and authorship attested in scholarship.');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'devotional',conf,'candidate_verified_name','Roster build via gen_roster.py (see CHANGELOG/git for release)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,etype text,note text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_DRZ_HUDUD','SRC_ABU_IZZEDDIN_DRUZES','scholarly attestation','attestation'),
 ('ENT_DRZ_AL_AQL','SRC_ABU_IZZEDDIN_DRUZES','scholarly attestation','attestation'),
 ('ENT_DRZ_AL_NAFS','SRC_ABU_IZZEDDIN_DRUZES','scholarly attestation','attestation'),
 ('ENT_DRZ_AL_KALIMA','SRC_ABU_IZZEDDIN_DRUZES','scholarly attestation','attestation'),
 ('ENT_DRZ_AL_SABIQ','SRC_ABU_IZZEDDIN_DRUZES','scholarly attestation','attestation'),
 ('ENT_DRZ_AL_TALI','SRC_ABU_IZZEDDIN_DRUZES','scholarly attestation','attestation'),
 ('ENT_DRZ_HAMZA','SRC_ABU_IZZEDDIN_DRUZES','scholarly attestation','attestation'),
 ('ENT_DRZ_ABU_IBRAHIM','SRC_ABU_IZZEDDIN_DRUZES','scholarly attestation','attestation'),
 ('ENT_DRZ_AL_TAMIMI','SRC_ABU_IZZEDDIN_DRUZES','scholarly attestation','attestation'),
 ('ENT_DRZ_SALAMA','SRC_ABU_IZZEDDIN_DRUZES','scholarly attestation','attestation'),
 ('ENT_DRZ_MUQTANA','SRC_FIRRO_DRUZES','scholarly attestation','attestation'),
 ('ENT_DRZ_AL_HAKIM','SRC_DAFTARY_ISMAILIS','scholarly attestation','attestation'),
 ('ENT_DRZ_AL_DARAZI','SRC_ABU_IZZEDDIN_DRUZES','scholarly attestation','attestation'),
 ('ENT_DRZ_TAQAMMUS','SRC_FIRRO_DRUZES','scholarly attestation','attestation'),
 ('ENT_DRZ_TAWHID','SRC_ABU_IZZEDDIN_DRUZES','scholarly attestation','attestation'),
 ('ENT_DRZ_RASAIL','SRC_ABU_IZZEDDIN_DRUZES','scholarly attestation','attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_DRZ_HUDUD','PER_DRUZE','Collective hub: the five cosmic ranks (al-hudud al-ulwiyya) through which the divine unity is mediated in Druze cosmology; attested in Abu-Izzeddin and standard scholarship.'),
 ('ENT_DRZ_AL_AQL','PER_DRUZE','First and highest of the five luminaries, the Universal Intellect; held to be manifested in Hamza ibn Ali. Attested doctrine.'),
 ('ENT_DRZ_AL_NAFS','PER_DRUZE','Second luminary, the Universal Soul, emanating from the Intellect; associated with Abu Ibrahim Isma''il al-Tamimi.'),
 ('ENT_DRZ_AL_KALIMA','PER_DRUZE','Third luminary, the Word/Logos; associated with Muhammad ibn Wahb al-Tamimi. Attested.'),
 ('ENT_DRZ_AL_SABIQ','PER_DRUZE','Fourth luminary, the Preceder (also ''the Right Wing''); associated with Salama ibn Abd al-Wahhab. Attested.'),
 ('ENT_DRZ_AL_TALI','PER_DRUZE','Fifth luminary, the Follower (also ''the Left Wing''); associated with Baha al-Din al-Muqtana. Attested.'),
 ('ENT_DRZ_HAMZA','PER_DRUZE','Persian founder-theologian of the Druze daʿwa (fl. 1017-21); chief organizer, held as the human manifestation of al-Aql (Universal Intellect). Historically attested. HOMONYM: distinct from ENT_ISL_HAMZA (Hamza ibn Abd al-Muttalib, uncle of the Prophet Muhammad).'),
 ('ENT_DRZ_ABU_IBRAHIM','PER_DRUZE','Early Druze daʿi associated with the rank of al-Nafs (Universal Soul). Attested in Druze epistolary tradition.'),
 ('ENT_DRZ_AL_TAMIMI','PER_DRUZE','Early Druze daʿi associated with the rank of al-Kalima (the Word). HOMONYM: distinct from the Prophet Muhammad (ENT_ISL_MUHAMMAD).'),
 ('ENT_DRZ_SALAMA','PER_DRUZE','Early Druze daʿi associated with the rank of al-Sabiq (the Preceder). Attested.'),
 ('ENT_DRZ_MUQTANA','PER_DRUZE','Druze daʿi (fl. 1027-43) who compiled much of the Rasaʾil al-Hikma (Epistles of Wisdom) and sealed the daʿwa; held as the manifestation of al-Tali (the Follower). Attested.'),
 ('ENT_DRZ_AL_HAKIM','PER_DRUZE','Sixth Fatimid caliph-imam (r.996-1021); in Druze belief the manifestation (mazhar/tajalli) of the divine unity. Historically attested Fatimid ruler; his divinity is a confessional Druze claim, modeled descriptively.'),
 ('ENT_DRZ_AL_DARAZI','PER_DRUZE','Early daʿi (d. c.1018) whose extremist preaching gave the community its exonym ''Druze''; later repudiated by Hamza as a heretic. Historically attested.'),
 ('ENT_DRZ_TAQAMMUS','PER_DRUZE','Druze doctrine that the fixed number of souls transmigrate immediately from body to body (taqammus); a defining publicly attested tenet.'),
 ('ENT_DRZ_TAWHID','PER_DRUZE','The unitarian core from which the Druze self-designation Muwahhidun (''Unitarians'') derives; God beyond attributes, mediated through the hudud. Attested.'),
 ('ENT_DRZ_RASAIL','PER_DRUZE','The 111-epistle Druze sacred canon, largely by Hamza and al-Muqtana; foundational closed scripture. Existence and authorship attested in scholarship.');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_DRZ_AL_AQL','member_of','ENT_DRZ_HUDUD','high','Al-Aql is the first of the five cosmic luminaries (al-hudud).'),
 ('ENT_DRZ_AL_NAFS','member_of','ENT_DRZ_HUDUD','high','Al-Nafs is the second of the five luminaries.'),
 ('ENT_DRZ_AL_KALIMA','member_of','ENT_DRZ_HUDUD','high','Al-Kalima is the third of the five luminaries.'),
 ('ENT_DRZ_AL_SABIQ','member_of','ENT_DRZ_HUDUD','high','Al-Sabiq is the fourth of the five luminaries.'),
 ('ENT_DRZ_AL_TALI','member_of','ENT_DRZ_HUDUD','high','Al-Tali is the fifth of the five luminaries.'),
 ('ENT_DRZ_AL_NAFS','emanates_from','ENT_DRZ_AL_AQL','high','In Druze cosmology the Universal Soul emanates from the Universal Intellect.'),
 ('ENT_DRZ_AL_KALIMA','emanates_from','ENT_DRZ_AL_NAFS','high','The Word emanates from the Universal Soul in the descending hierarchy of luminaries.'),
 ('ENT_DRZ_AL_SABIQ','emanates_from','ENT_DRZ_AL_KALIMA','high','The Preceder emanates from the Word.'),
 ('ENT_DRZ_AL_TALI','emanates_from','ENT_DRZ_AL_SABIQ','high','The Follower emanates from the Preceder, completing the five ranks.'),
 ('ENT_DRZ_HAMZA','embodies','ENT_DRZ_AL_AQL','high','Hamza ibn Ali is held to be the human manifestation of al-Aql, the Universal Intellect.'),
 ('ENT_DRZ_ABU_IBRAHIM','embodies','ENT_DRZ_AL_NAFS','medium','Abu Ibrahim al-Tamimi is associated with the rank of al-Nafs.'),
 ('ENT_DRZ_AL_TAMIMI','embodies','ENT_DRZ_AL_KALIMA','medium','Muhammad ibn Wahb al-Tamimi is associated with the rank of al-Kalima.'),
 ('ENT_DRZ_SALAMA','embodies','ENT_DRZ_AL_SABIQ','medium','Salama ibn Abd al-Wahhab is associated with the rank of al-Sabiq.'),
 ('ENT_DRZ_MUQTANA','embodies','ENT_DRZ_AL_TALI','high','Baha al-Din al-Muqtana is held to be the manifestation of al-Tali, the Follower.'),
 ('ENT_DRZ_HAMZA','member_of','ENT_DRZ_HUDUD','high','As manifestation of al-Aql, Hamza is the human head of the five luminaries.'),
 ('ENT_DRZ_MUQTANA','member_of','ENT_DRZ_HUDUD','high','As manifestation of al-Tali, al-Muqtana belongs to the five luminaries.'),
 ('ENT_DRZ_AL_HAKIM','presides_over','ENT_DRZ_HUDUD','high','In Druze belief al-Hakim, as divine manifestation, stands above and is served by the five cosmic luminaries.'),
 ('ENT_DRZ_HAMZA','transmits','ENT_DRZ_RASAIL','medium','Hamza authored/transmitted a major portion of the epistles collected in the Rasaʾil al-Hikma.'),
 ('ENT_DRZ_MUQTANA','transmits','ENT_DRZ_RASAIL','medium','Al-Muqtana compiled and transmitted many of the epistles of the Rasaʾil al-Hikma.'),
 ('ENT_DRZ_HAMZA','reveals','ENT_DRZ_TAWHID','high','Hamza systematized and proclaimed the Druze doctrine of tawhid.'),
 ('ENT_DRZ_TAQAMMUS','member_of','ENT_DRZ_TAWHID','medium','Taqammus is an integral doctrine within the Druze tawhid worldview.'),
 ('ENT_DRZ_AL_DARAZI','opposes','ENT_DRZ_HAMZA','high','Al-Darazi''s extremist claims were repudiated by Hamza, who declared him a heretic; the two were rivals in the early daʿwa.'),
 ('ENT_DRZ_TAWHID','reception_of','ENT_ISL_ALLAH','high','Druze tawhid develops the Islamic affirmation of God''s absolute unity (Allah) in a distinctive transcendent direction.'),
 ('ENT_DRZ_AL_HAKIM','reception_of','ENT_ISL_IMAMAH','high','Druze veneration of al-Hakim derives from the Fatimid Ismaili doctrine of the imamate (imamah), radicalized into a claim of divine manifestation.'),
 ('ENT_DRZ_HAMZA','reception_of','ENT_OCCULTATION','medium','Druze expectation of the return of al-Hakim and Hamza adapts the Shia doctrine of occultation (ghayba) and awaited return.'),
 ('ENT_DRZ_AL_AQL','aligned_with','ENT_GNO_NOUS','medium','The Druze Universal Intellect (al-Aql al-Kulli) is functionally cognate to the Neoplatonic/Gnostic Nous as first emanation, a comparison drawn in scholarship on Ismaili-Druze cosmology.');

\echo '--- REJECTED edges (bad id/type, or subject lacks a source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
