-- build_p7_precolumbian_seams.sql  (GENERATED by gen_roster.py p7_precolumbian_seams) — v1.80.0
-- 3 entities, 3 edges, 1 new periods, 2 new sources. Idempotent + self-validating.
BEGIN;

INSERT INTO periods (period_id, period_name, start_year, end_year) VALUES
 ('PER_PCB_POSTCLASSIC_MESOAMERICA','Mesoamerican Postclassic (to the Spanish Conquest)',900,1521)
ON CONFLICT (period_id) DO NOTHING;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_BRADING_MEXICAN_PHOENIX','secondary scholarship','D. A. Brading, Mexican Phoenix: Our Lady of Guadalupe — Image and Tradition across Five Centuries (Cambridge University Press, 2001)','The cult of Our Lady of Guadalupe at Tepeyac and the documented Tonantzin association (esp. Sahagun''s report); used for the Guadalupe-Tonantzin syncretism seam.'),
 ('SRC_PIEPER_FOLK_SAINTS_GUATEMALA','secondary scholarship','Jim Pieper, Guatemala''s Folk Saints: Maximon/San Simon, Rey Pascual, Judas, Lucifer, and Others (Pieper and Associates, 2002)','The living Guatemalan folk-saint cult of Maximon and his identification with San Simon and Judas Iscariot, and the underlying Maya figure Mam; used for the Mam/Maximon syncretism seam.')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,trad text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_PCB_MESOAMERICAN_RELIGION','Pre-Columbian Mesoamerican Religion','Collective','Pantheon','Mesoamerican','pantheon/tradition hub','B','Hub collective for the pre-Columbian (Nahua and Maya) deities included only at documented Catholic syncretism seams. Pre-Columbian source; not a full pantheon roster. Practice: the indigenous religions of central Mexico and the Maya highlands, suppressed and partly continued in syncretic Catholic devotion after 1521.'),
 ('ENT_PCB_TONANTZIN','Tonantzin','Goddess','God','Mesoamerican','mother, earth, fertility','B','Nahuatl ''Our Revered Mother'', a Nahua mother-earth title/goddess with a shrine at Tepeyac near Mexico City. Attestation: Bernardino de Sahagun (16th c.) records that indigenous pilgrims called the Guadalupan shrine at Tepeyac ''Tonantzin''. Pre-Columbian source. The Tonantzin-Guadalupe association is the canonical documented Mesoamerican-Catholic syncretism seam (Brading).'),
 ('ENT_PCB_MAM','Mam','God','God','Mesoamerican','earth, ancestors, mountains','C','Maya ''Grandfather''/ancestral earth figure of the Guatemalan highlands publicly regarded as the indigenous antecedent of the living folk saint Maximon (San Simon). Pre-Columbian source; only publicly attested function modeled, no ritual interiors. In highland Maya Catholic practice the derived folk saint Maximon is publicly identified with San Simon and with Judas Iscariot (Pieper); that identification attaches to the received folk-saint figure rather than to Mam directly.');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'devotional',conf,'candidate_verified_name','Roster build via gen_roster.py (see CHANGELOG/git for release)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,etype text,note text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_PCB_MESOAMERICAN_RELIGION','SRC_BRADING_MEXICAN_PHOENIX','scholarly attestation','attestation'),
 ('ENT_PCB_TONANTZIN','SRC_BRADING_MEXICAN_PHOENIX','scholarly attestation','attestation'),
 ('ENT_PCB_MAM','SRC_PIEPER_FOLK_SAINTS_GUATEMALA','scholarly attestation','attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_PCB_MESOAMERICAN_RELIGION','PER_PCB_POSTCLASSIC_MESOAMERICA','Hub collective for the pre-Columbian (Nahua and Maya) deities included only at documented Catholic syncretism seams. Pre-Columbian source; not a full pantheon roster. Practice: the indigenous religions of central Mexico and the Maya highlands, suppressed and partly continued in syncretic Catholic devotion after 1521.'),
 ('ENT_PCB_TONANTZIN','PER_PCB_POSTCLASSIC_MESOAMERICA','Nahuatl ''Our Revered Mother'', a Nahua mother-earth title/goddess with a shrine at Tepeyac near Mexico City. Attestation: Bernardino de Sahagun (16th c.) records that indigenous pilgrims called the Guadalupan shrine at Tepeyac ''Tonantzin''. Pre-Columbian source. The Tonantzin-Guadalupe association is the canonical documented Mesoamerican-Catholic syncretism seam (Brading).'),
 ('ENT_PCB_MAM','PER_PCB_POSTCLASSIC_MESOAMERICA','Maya ''Grandfather''/ancestral earth figure of the Guatemalan highlands publicly regarded as the indigenous antecedent of the living folk saint Maximon (San Simon). Pre-Columbian source; only publicly attested function modeled, no ritual interiors. In highland Maya Catholic practice the derived folk saint Maximon is publicly identified with San Simon and with Judas Iscariot (Pieper); that identification attaches to the received folk-saint figure rather than to Mam directly.');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_PCB_TONANTZIN','member_of','ENT_PCB_MESOAMERICAN_RELIGION','high','Tonantzin is a Nahua deity within the pre-Columbian Mesoamerican religious complex represented by the hub collective.'),
 ('ENT_PCB_MAM','member_of','ENT_PCB_MESOAMERICAN_RELIGION','high','Mam is a Maya ancestral/earth figure within the pre-Columbian Mesoamerican religious complex represented by the hub collective.'),
 ('ENT_EMC_OUR_LADY_GUADALUPE','syncretized_with','ENT_PCB_TONANTZIN','high','Our Lady of Guadalupe is the textbook case of Catholic-Mesoamerican syncretism, her Tepeyac shrine identified by indigenous devotees with the Nahua mother-earth goddess Tonantzin; Sahagun records pilgrims calling the site Tonantzin (Brading, Mexican Phoenix).');

\echo '--- REJECTED edges (bad id/type, or subject lacks a source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
