-- build_sufi_medieval.sql  (GENERATED by gen_roster.py sufi_medieval) — v1.80.0
-- 31 entities, 38 edges, 0 new periods, 2 new sources. Idempotent + self-validating.
BEGIN;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_ATTAR_TADHKIRAT','primary text','Farid al-Din Attar, Tadhkirat al-Awliya (Memorial of the Saints, c. 1220)','Islamic/Sufi'),
 ('SRC_JAMI_NAFAHAT','primary text','Jami, Nafahat al-Uns (Breaths of Fellowship, 1478)','Islamic/Sufi')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,trad text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_SUF_NAQSHBANDI','Naqshbandiyya','Collective','Sufi order','Islamic/Sufi','silent dhikr; sober Sufism; sharia-bound spirituality; the Khwajagan lineage','A','Major Sunni Sufi tariqa traced to Baha al-Din Naqshband, distinguished by silent dhikr (dhikr-i khafi) and tracing its silsila to Abu Bakr.'),
 ('ENT_SUF_CHISHTI','Chishtiyya','Collective','Sufi order','Islamic/Sufi','sama (audition); service to the poor; love of God; South Asian Sufism','A','Sufi order rooted in Chisht (Afghanistan) and established in India by Mu''in al-Din Chishti, central to the Islamization of the subcontinent.'),
 ('ENT_SUF_BEKTASHI','Bektashiyya','Collective','Sufi order','Islamic/Sufi','Anatolian heterodoxy; Alevi devotion; veneration of Ali; antinomian piety','A','Heterodox Anatolian Sufi order traced to Hajji Bektash Wali, later linked to the Janissaries and to Alevi communities.'),
 ('ENT_SUF_NIMATULLAHI','Ni''matullahiyya','Collective','Sufi order','Islamic/Sufi','Persian Sufism; wahdat al-wujud; poetry and devotion','A','Persian Sufi order founded by Shah Ni''matullah Wali, the most widespread tariqa in Iran.'),
 ('ENT_SUF_KUBRAWI','Kubrawiyya','Collective','Sufi order','Islamic/Sufi','visionary mysticism; colours of the soul; Central Asian Sufism','A','Central Asian Sufi order founded by Najm al-Din Kubra, noted for its visionary psychology of luminous colours.'),
 ('ENT_SUF_BADAWIYYA','Badawiyya','Collective','Sufi order','Islamic/Sufi','Egyptian popular Sufism; saint-veneration; the Tanta mawlid','A','Egyptian Sufi order centred on the shrine of Ahmad al-Badawi at Tanta, host to one of the largest mawlid festivals in Islam.'),
 ('ENT_SUF_KUBRA','Najm al-Din Kubra','Saint','Tariqa founder','Islamic/Sufi','visionary mysticism; spiritual psychology; sainthood','B','Persian mystic (d. 1221), eponymous founder of the Kubrawiyya; martyred at the Mongol sack of Khwarazm. Author of works on the visionary lights of the soul.'),
 ('ENT_SUF_QUNAWI','Sadr al-Din al-Qunawi','Saint','Sufi saint (wali)','Islamic/Sufi','metaphysics; wahdat al-wujud; theology of unveiling','B','Persian-Anatolian metaphysician (d. 1274), stepson and chief successor of Ibn al-Arabi who systematized his teaching of the oneness of being.'),
 ('ENT_SUF_IRAQI','Fakhr al-Din Iraqi','Saint','Saint-poet','Islamic/Sufi','mystical love-poetry; wahdat al-wujud; divine beauty','B','Persian Sufi poet (d. 1289), disciple of Qunawi''s circle, whose Lama''at expounds Ibn al-Arabi''s doctrine through the imagery of love.'),
 ('ENT_SUF_KIRMANI','Awhad al-Din Kirmani','Saint','Saint-poet','Islamic/Sufi','contemplation of divine beauty; quatrains; the witness (shahid)','B','Persian Sufi master and poet (d. 1238) known for the contemplation of divine beauty in created forms (shahid-bazi) and for his ruba''iyat.'),
 ('ENT_SUF_CHISHTI_MUIN','Mu''in al-Din Chishti','Saint','Tariqa founder','Islamic/Sufi','sainthood; service to the poor; conversion; Indian Sufism','B','Persian saint (d. 1236) who established the Chishtiyya in India; his shrine (dargah) at Ajmer is among the most venerated in South Asia. Titled Gharib Nawaz.'),
 ('ENT_SUF_BAKHTIAR_KAKI','Qutb al-Din Bakhtiar Kaki','Saint','Sufi saint (wali)','Islamic/Sufi','sainthood; sama; the Delhi Chishti line','B','Chishti saint of Delhi (d. 1235), foremost disciple of Mu''in al-Din Chishti; his shrine at Mehrauli anchors the Delhi Chishti tradition.'),
 ('ENT_SUF_BABA_FARID','Farid al-Din Ganj-i-Shakar','Saint','Sufi saint (wali)','Islamic/Sufi','asceticism; Punjabi devotion; sainthood','B','Punjabi Chishti saint (d. 1265), ''Baba Farid''; his verses are included in the Sikh Guru Granth Sahib. Shrine at Pakpattan.'),
 ('ENT_SUF_NIZAM_AWLIYA','Nizam al-Din Awliya','Saint','Sufi saint (wali)','Islamic/Sufi','sainthood; love and tolerance; Delhi Sultanate Sufism','B','Pre-eminent Chishti saint of Delhi (d. 1325), ''Mahbub-i Ilahi''; his dargah is a major South Asian pilgrimage centre.'),
 ('ENT_SUF_AMIR_KHUSROW','Amir Khusrow','Saint','Saint-poet','Islamic/Sufi','Persian and Hindavi poetry; qawwali; devotion to the master','B','Indo-Persian poet and musician (d. 1325), devoted disciple of Nizam al-Din Awliya and a father of the qawwali devotional song.'),
 ('ENT_SUF_NAQSHBAND','Baha al-Din Naqshband','Saint','Tariqa founder','Islamic/Sufi','silent dhikr; sober Sufism; the Khwajagan path','B','Central Asian saint of Bukhara (d. 1389), eponym of the Naqshbandiyya, who emphasized silent remembrance and presence in the world.'),
 ('ENT_SUF_KHWAJA_AHRAR','Khwaja Ubayd Allah Ahrar','Saint','Sufi saint (wali)','Islamic/Sufi','sainthood; political influence; Naqshbandi consolidation','B','Naqshbandi master of Samarqand (d. 1490) who gave the order great political and economic weight under the Timurids.'),
 ('ENT_SUF_BADAWI','Ahmad al-Badawi','Saint','Tariqa founder','Islamic/Sufi','Egyptian popular sainthood; miracle-working; the Tanta mawlid','B','Saint of Tanta (d. 1276), eponym of the Badawiyya and one of the most popular saints of Egypt.'),
 ('ENT_SUF_DASUQI','Ibrahim al-Dasuqi','Saint','Tariqa founder','Islamic/Sufi','Egyptian sainthood; the four ''aqtab''; devotion','B','Egyptian saint (d. 1296), eponym of the Dasuqiyya (Burhaniyya) and counted among the four great qutbs of Egyptian Sufism.'),
 ('ENT_SUF_NIMATULLAH','Shah Ni''matullah Wali','Saint','Tariqa founder','Islamic/Sufi','Persian sainthood; mystical poetry; wahdat al-wujud','B','Persian saint and poet (d. 1431), founder of the Ni''matullahi order; his shrine at Mahan is a major Iranian pilgrimage site.'),
 ('ENT_SUF_BEKTASH','Hajji Bektash Wali','Saint','Tariqa founder','Islamic/Sufi','Anatolian sainthood; antinomian piety; veneration of Ali','B','Anatolian saint (d. 1271) revered as the founder-patron of the Bektashiyya and of Alevi devotion.'),
 ('ENT_SUF_YUNUS_EMRE','Yunus Emre','Saint','Saint-poet','Islamic/Sufi','Turkish devotional poetry; divine love; folk mysticism','B','Turkish saint-poet (d. 1321), father of Turkish-language Sufi poetry whose hymns of divine love remain central to Anatolian devotion.'),
 ('ENT_SUF_HAFIZ','Hafiz of Shiraz','Saint','Saint-poet','Islamic/Sufi','Persian ghazal; mystical love and wine; divine beauty','B','Persian lyric poet (d. 1390), ''Lisan al-Ghayb'', whose ghazals fuse the imagery of love and wine with mystical longing; venerated and used for bibliomancy (fal).'),
 ('ENT_SUF_SHABISTARI','Mahmud Shabistari','Saint','Saint-poet','Islamic/Sufi','mystical metaphysics; wahdat al-wujud; symbolic exegesis','B','Persian Sufi poet (d. 1340) whose Gulshan-i Raz (Rose Garden of Mystery) is a classic verse summary of Ibn al-Arabi''s metaphysics.'),
 ('ENT_SUF_JILI','Abd al-Karim al-Jili','Saint','Sufi saint (wali)','Islamic/Sufi','metaphysics; the Perfect Man (al-insan al-kamil); wahdat al-wujud','B','Yemeni-Iraqi mystic (d. c. 1424) whose al-Insan al-Kamil developed Ibn al-Arabi''s doctrine of the Perfect Man.'),
 ('ENT_SUF_SAFI_ARDABILI','Safi al-Din Ardabili','Saint','Tariqa founder','Islamic/Sufi','sainthood; the Safavid order; Azerbaijani Sufism','B','Persian saint of Ardabil (d. 1334), eponym of the Safaviyya order from which the Safavid dynasty later arose.'),
 ('ENT_SUF_HAMADANI','Sayyid Ali Hamadani','Saint','Sufi saint (wali)','Islamic/Sufi','missionary sainthood; Kubrawi path; Kashmiri Sufism','B','Persian Kubrawi saint (d. 1385) credited with spreading Islam and Persianate culture in Kashmir; ''Shah-i Hamadan''.'),
 ('ENT_SUF_MANERI','Sharaf al-Din Maneri','Saint','Sufi saint (wali)','Islamic/Sufi','sainthood; spiritual letters; Firdausi-Suhrawardi path','B','Indian Sufi master of Bihar (d. 1381) of the Firdausiyya (a Suhrawardi branch), famed for his Maktubat (Hundred Letters) of spiritual counsel.'),
 ('ENT_SUF_LAL_DED','Lal Ded','Saint','Saint-poet','Islamic/Sufi','Kashmiri mystical verse; non-dual devotion; the rishi tradition','C','Kashmiri mystic poet (d. c. 1392), ''Lalla'', whose vakhs voice a non-dual devotion bridging Shaiva and Sufi piety; revered by Hindus and Muslims alike.'),
 ('ENT_SUF_NURI','Nur al-Din Nurani','Saint','Tariqa founder','Islamic/Sufi','Kashmiri sainthood; the Rishi order; asceticism','C','Kashmiri saint (d. c. 1440), ''Nund Rishi'', patron-founder of the Kashmiri Rishi order; venerated as Alamdar-i Kashmir.'),
 ('ENT_SUF_JAMI','Abd al-Rahman Jami','Saint','Saint-poet','Islamic/Sufi','Persian poetry; Naqshbandi devotion; hagiography; wahdat al-wujud','B','Persian poet and Naqshbandi mystic (d. 1492), last of the great classical Persian poets; his Nafahat al-Uns is a major saints'' hagiography.');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'devotional',conf,'candidate_verified_name','High/late-medieval depth build (v1.80.0)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,etype text,note text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_SUF_NAQSHBANDI','SRC_JAMI_NAFAHAT','primary text attestation','attestation'),
 ('ENT_SUF_CHISHTI','SRC_JAMI_NAFAHAT','primary text attestation','attestation'),
 ('ENT_SUF_BEKTASHI','SRC_SCHIMMEL_SUFISM','scholarly attestation','attestation'),
 ('ENT_SUF_NIMATULLAHI','SRC_SCHIMMEL_SUFISM','scholarly attestation','attestation'),
 ('ENT_SUF_KUBRAWI','SRC_SCHIMMEL_SUFISM','scholarly attestation','attestation'),
 ('ENT_SUF_BADAWIYYA','SRC_SCHIMMEL_SUFISM','scholarly attestation','attestation'),
 ('ENT_SUF_KUBRA','SRC_SCHIMMEL_SUFISM','scholarly attestation','attestation'),
 ('ENT_SUF_QUNAWI','SRC_JAMI_NAFAHAT','primary text attestation','attestation'),
 ('ENT_SUF_IRAQI','SRC_JAMI_NAFAHAT','primary text attestation','attestation'),
 ('ENT_SUF_KIRMANI','SRC_SCHIMMEL_SUFISM','scholarly attestation','attestation'),
 ('ENT_SUF_CHISHTI_MUIN','SRC_SCHIMMEL_SUFISM','scholarly attestation','attestation'),
 ('ENT_SUF_BAKHTIAR_KAKI','SRC_SCHIMMEL_SUFISM','scholarly attestation','attestation'),
 ('ENT_SUF_BABA_FARID','SRC_SCHIMMEL_SUFISM','scholarly attestation','attestation'),
 ('ENT_SUF_NIZAM_AWLIYA','SRC_SCHIMMEL_SUFISM','scholarly attestation','attestation'),
 ('ENT_SUF_AMIR_KHUSROW','SRC_SCHIMMEL_SUFISM','scholarly attestation','attestation'),
 ('ENT_SUF_NAQSHBAND','SRC_JAMI_NAFAHAT','primary text attestation','attestation'),
 ('ENT_SUF_KHWAJA_AHRAR','SRC_JAMI_NAFAHAT','primary text attestation','attestation'),
 ('ENT_SUF_BADAWI','SRC_SCHIMMEL_SUFISM','scholarly attestation','attestation'),
 ('ENT_SUF_DASUQI','SRC_SCHIMMEL_SUFISM','scholarly attestation','attestation'),
 ('ENT_SUF_NIMATULLAH','SRC_SCHIMMEL_SUFISM','scholarly attestation','attestation'),
 ('ENT_SUF_BEKTASH','SRC_SCHIMMEL_SUFISM','scholarly attestation','attestation'),
 ('ENT_SUF_YUNUS_EMRE','SRC_SCHIMMEL_SUFISM','scholarly attestation','attestation'),
 ('ENT_SUF_HAFIZ','SRC_SCHIMMEL_SUFISM','scholarly attestation','attestation'),
 ('ENT_SUF_SHABISTARI','SRC_SCHIMMEL_SUFISM','scholarly attestation','attestation'),
 ('ENT_SUF_JILI','SRC_SCHIMMEL_SUFISM','scholarly attestation','attestation'),
 ('ENT_SUF_SAFI_ARDABILI','SRC_SCHIMMEL_SUFISM','scholarly attestation','attestation'),
 ('ENT_SUF_HAMADANI','SRC_SCHIMMEL_SUFISM','scholarly attestation','attestation'),
 ('ENT_SUF_MANERI','SRC_SCHIMMEL_SUFISM','scholarly attestation','attestation'),
 ('ENT_SUF_LAL_DED','SRC_SCHIMMEL_SUFISM','scholarly attestation','attestation'),
 ('ENT_SUF_NURI','SRC_SCHIMMEL_SUFISM','scholarly attestation','attestation'),
 ('ENT_SUF_JAMI','SRC_JAMI_NAFAHAT','primary text attestation','attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_SUF_NAQSHBANDI','PER_ISL_MEDIEVAL','Major Sunni Sufi tariqa traced to Baha al-Din Naqshband, distinguished by silent dhikr (dhikr-i khafi) and tracing its silsila to Abu Bakr.'),
 ('ENT_SUF_CHISHTI','PER_ISL_MEDIEVAL','Sufi order rooted in Chisht (Afghanistan) and established in India by Mu''in al-Din Chishti, central to the Islamization of the subcontinent.'),
 ('ENT_SUF_BEKTASHI','PER_ISL_MEDIEVAL','Heterodox Anatolian Sufi order traced to Hajji Bektash Wali, later linked to the Janissaries and to Alevi communities.'),
 ('ENT_SUF_NIMATULLAHI','PER_ISL_MEDIEVAL','Persian Sufi order founded by Shah Ni''matullah Wali, the most widespread tariqa in Iran.'),
 ('ENT_SUF_KUBRAWI','PER_ISL_CLASSICAL','Central Asian Sufi order founded by Najm al-Din Kubra, noted for its visionary psychology of luminous colours.'),
 ('ENT_SUF_BADAWIYYA','PER_ISL_MEDIEVAL','Egyptian Sufi order centred on the shrine of Ahmad al-Badawi at Tanta, host to one of the largest mawlid festivals in Islam.'),
 ('ENT_SUF_KUBRA','PER_ISL_CLASSICAL','Persian mystic (d. 1221), eponymous founder of the Kubrawiyya; martyred at the Mongol sack of Khwarazm. Author of works on the visionary lights of the soul.'),
 ('ENT_SUF_QUNAWI','PER_ISL_MEDIEVAL','Persian-Anatolian metaphysician (d. 1274), stepson and chief successor of Ibn al-Arabi who systematized his teaching of the oneness of being.'),
 ('ENT_SUF_IRAQI','PER_ISL_MEDIEVAL','Persian Sufi poet (d. 1289), disciple of Qunawi''s circle, whose Lama''at expounds Ibn al-Arabi''s doctrine through the imagery of love.'),
 ('ENT_SUF_KIRMANI','PER_ISL_CLASSICAL','Persian Sufi master and poet (d. 1238) known for the contemplation of divine beauty in created forms (shahid-bazi) and for his ruba''iyat.'),
 ('ENT_SUF_CHISHTI_MUIN','PER_ISL_CLASSICAL','Persian saint (d. 1236) who established the Chishtiyya in India; his shrine (dargah) at Ajmer is among the most venerated in South Asia. Titled Gharib Nawaz.'),
 ('ENT_SUF_BAKHTIAR_KAKI','PER_ISL_CLASSICAL','Chishti saint of Delhi (d. 1235), foremost disciple of Mu''in al-Din Chishti; his shrine at Mehrauli anchors the Delhi Chishti tradition.'),
 ('ENT_SUF_BABA_FARID','PER_ISL_MEDIEVAL','Punjabi Chishti saint (d. 1265), ''Baba Farid''; his verses are included in the Sikh Guru Granth Sahib. Shrine at Pakpattan.'),
 ('ENT_SUF_NIZAM_AWLIYA','PER_ISL_MEDIEVAL','Pre-eminent Chishti saint of Delhi (d. 1325), ''Mahbub-i Ilahi''; his dargah is a major South Asian pilgrimage centre.'),
 ('ENT_SUF_AMIR_KHUSROW','PER_ISL_MEDIEVAL','Indo-Persian poet and musician (d. 1325), devoted disciple of Nizam al-Din Awliya and a father of the qawwali devotional song.'),
 ('ENT_SUF_NAQSHBAND','PER_ISL_MEDIEVAL','Central Asian saint of Bukhara (d. 1389), eponym of the Naqshbandiyya, who emphasized silent remembrance and presence in the world.'),
 ('ENT_SUF_KHWAJA_AHRAR','PER_ISL_MEDIEVAL','Naqshbandi master of Samarqand (d. 1490) who gave the order great political and economic weight under the Timurids.'),
 ('ENT_SUF_BADAWI','PER_ISL_MEDIEVAL','Saint of Tanta (d. 1276), eponym of the Badawiyya and one of the most popular saints of Egypt.'),
 ('ENT_SUF_DASUQI','PER_ISL_MEDIEVAL','Egyptian saint (d. 1296), eponym of the Dasuqiyya (Burhaniyya) and counted among the four great qutbs of Egyptian Sufism.'),
 ('ENT_SUF_NIMATULLAH','PER_ISL_MEDIEVAL','Persian saint and poet (d. 1431), founder of the Ni''matullahi order; his shrine at Mahan is a major Iranian pilgrimage site.'),
 ('ENT_SUF_BEKTASH','PER_ISL_MEDIEVAL','Anatolian saint (d. 1271) revered as the founder-patron of the Bektashiyya and of Alevi devotion.'),
 ('ENT_SUF_YUNUS_EMRE','PER_ISL_MEDIEVAL','Turkish saint-poet (d. 1321), father of Turkish-language Sufi poetry whose hymns of divine love remain central to Anatolian devotion.'),
 ('ENT_SUF_HAFIZ','PER_ISL_MEDIEVAL','Persian lyric poet (d. 1390), ''Lisan al-Ghayb'', whose ghazals fuse the imagery of love and wine with mystical longing; venerated and used for bibliomancy (fal).'),
 ('ENT_SUF_SHABISTARI','PER_ISL_MEDIEVAL','Persian Sufi poet (d. 1340) whose Gulshan-i Raz (Rose Garden of Mystery) is a classic verse summary of Ibn al-Arabi''s metaphysics.'),
 ('ENT_SUF_JILI','PER_ISL_MEDIEVAL','Yemeni-Iraqi mystic (d. c. 1424) whose al-Insan al-Kamil developed Ibn al-Arabi''s doctrine of the Perfect Man.'),
 ('ENT_SUF_SAFI_ARDABILI','PER_ISL_MEDIEVAL','Persian saint of Ardabil (d. 1334), eponym of the Safaviyya order from which the Safavid dynasty later arose.'),
 ('ENT_SUF_HAMADANI','PER_ISL_MEDIEVAL','Persian Kubrawi saint (d. 1385) credited with spreading Islam and Persianate culture in Kashmir; ''Shah-i Hamadan''.'),
 ('ENT_SUF_MANERI','PER_ISL_MEDIEVAL','Indian Sufi master of Bihar (d. 1381) of the Firdausiyya (a Suhrawardi branch), famed for his Maktubat (Hundred Letters) of spiritual counsel.'),
 ('ENT_SUF_LAL_DED','PER_ISL_MEDIEVAL','Kashmiri mystic poet (d. c. 1392), ''Lalla'', whose vakhs voice a non-dual devotion bridging Shaiva and Sufi piety; revered by Hindus and Muslims alike.'),
 ('ENT_SUF_NURI','PER_ISL_MEDIEVAL','Kashmiri saint (d. c. 1440), ''Nund Rishi'', patron-founder of the Kashmiri Rishi order; venerated as Alamdar-i Kashmir.'),
 ('ENT_SUF_JAMI','PER_ISL_MEDIEVAL','Persian poet and Naqshbandi mystic (d. 1492), last of the great classical Persian poets; his Nafahat al-Uns is a major saints'' hagiography.');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_SUF_KUBRA','member_of','ENT_SUF_KUBRAWI','high','Eponymous founder of the Kubrawiyya.'),
 ('ENT_SUF_HAMADANI','member_of','ENT_SUF_KUBRAWI','high','Kubrawi master in the line of Najm al-Din Kubra.'),
 ('ENT_SUF_CHISHTI_MUIN','member_of','ENT_SUF_CHISHTI','high','Established the Chishtiyya in India as its founding master.'),
 ('ENT_SUF_BAKHTIAR_KAKI','member_of','ENT_SUF_CHISHTI','high','Chishti saint of Delhi.'),
 ('ENT_SUF_BABA_FARID','member_of','ENT_SUF_CHISHTI','high','Punjabi Chishti saint.'),
 ('ENT_SUF_NIZAM_AWLIYA','member_of','ENT_SUF_CHISHTI','high','Pre-eminent Chishti saint of Delhi.'),
 ('ENT_SUF_AMIR_KHUSROW','member_of','ENT_SUF_CHISHTI','medium','Lay disciple within the Chishti circle of Nizam al-Din.'),
 ('ENT_SUF_NAQSHBAND','member_of','ENT_SUF_NAQSHBANDI','high','Eponymous founder of the Naqshbandiyya.'),
 ('ENT_SUF_KHWAJA_AHRAR','member_of','ENT_SUF_NAQSHBANDI','high','Leading Naqshbandi master of the Timurid era.'),
 ('ENT_SUF_JAMI','member_of','ENT_SUF_NAQSHBANDI','high','Naqshbandi poet and hagiographer.'),
 ('ENT_SUF_BEKTASH','member_of','ENT_SUF_BEKTASHI','high','Founder-patron of the Bektashiyya.'),
 ('ENT_SUF_NIMATULLAH','member_of','ENT_SUF_NIMATULLAHI','high','Founder of the Ni''matullahi order.'),
 ('ENT_SUF_BADAWI','member_of','ENT_SUF_BADAWIYYA','high','Eponymous founder of the Badawiyya.'),
 ('ENT_SUF_QUNAWI','taught_by','ENT_SUF_IBN_ARABI','high','Stepson and chief disciple of Ibn al-Arabi.'),
 ('ENT_SUF_QUNAWI','reception_of','ENT_SUF_IBN_ARABI','high','Systematized Ibn al-Arabi''s doctrine of wahdat al-wujud.'),
 ('ENT_SUF_IRAQI','taught_by','ENT_SUF_QUNAWI','medium','Drew his Lama''at from Qunawi''s expositions of Ibn al-Arabi.'),
 ('ENT_SUF_IRAQI','reception_of','ENT_SUF_IBN_ARABI','high','His Lama''at versifies Ibn al-Arabi''s metaphysics of love.'),
 ('ENT_SUF_SHABISTARI','reception_of','ENT_SUF_IBN_ARABI','high','Gulshan-i Raz is a verse summary of Ibn al-Arabi''s wahdat al-wujud.'),
 ('ENT_SUF_JILI','reception_of','ENT_SUF_IBN_ARABI','high','Al-Insan al-Kamil develops Ibn al-Arabi''s Perfect Man.'),
 ('ENT_SUF_NIMATULLAH','reception_of','ENT_SUF_IBN_ARABI','medium','Composed commentary on and verse in the wahdat al-wujud tradition.'),
 ('ENT_SUF_KIRMANI','aligned_with','ENT_SUF_IBN_ARABI','medium','Contemporary of Ibn al-Arabi''s circle sharing the contemplation of divine beauty in form.'),
 ('ENT_SUF_BAKHTIAR_KAKI','taught_by','ENT_SUF_CHISHTI_MUIN','high','Foremost disciple and successor of Mu''in al-Din Chishti.'),
 ('ENT_SUF_BABA_FARID','taught_by','ENT_SUF_BAKHTIAR_KAKI','high','Successor of Bakhtiar Kaki in the Delhi Chishti line.'),
 ('ENT_SUF_NIZAM_AWLIYA','taught_by','ENT_SUF_BABA_FARID','high','Khalifa and chief successor of Baba Farid.'),
 ('ENT_SUF_AMIR_KHUSROW','taught_by','ENT_SUF_NIZAM_AWLIYA','high','Devoted disciple of Nizam al-Din Awliya.'),
 ('ENT_SUF_KHWAJA_AHRAR','reception_of','ENT_SUF_NAQSHBAND','high','Carried forward the Naqshbandi path of Baha al-Din.'),
 ('ENT_SUF_JAMI','taught_by','ENT_SUF_KHWAJA_AHRAR','medium','Affiliated to the Naqshbandiyya through Khwaja Ahrar.'),
 ('ENT_SUF_MANERI','reception_of','ENT_SUF_SUHRAWARDI','medium','Of the Firdausiyya, a Suhrawardi branch in India.'),
 ('ENT_SUF_SAFI_ARDABILI','reception_of','ENT_SUF_SUHRAWARDI','low','His Safaviyya silsila descends through the broader Suhrawardi-Zahidi line.'),
 ('ENT_SUF_HAMADANI','reception_of','ENT_SUF_KUBRA','medium','Transmitted the Kubrawi visionary path founded by Najm al-Din Kubra.'),
 ('ENT_SUF_YUNUS_EMRE','aligned_with','ENT_SUF_RUMI','medium','Turkish saint-poet writing in the wake of Rumi''s Anatolian devotional milieu.'),
 ('ENT_SUF_HAFIZ','aligned_with','ENT_SUF_RUMI','low','Persian mystical poetry sharing Rumi''s idiom of divine love and longing.'),
 ('ENT_SUF_NURI','taught_by','ENT_SUF_LAL_DED','low','Kashmiri tradition links Nund Rishi''s path to the example of Lal Ded.'),
 ('ENT_SUF_LAL_DED','aligned_with','ENT_SUF_HAMADANI','low','Kashmiri contemporary devotion overlapping with the Hamadani Sufi presence.'),
 ('ENT_SUF_BADAWI','aligned_with','ENT_SUF_JILANI','low','Counted among the great popular saints venerated alongside Abd al-Qadir al-Jilani.'),
 ('ENT_SUF_DASUQI','aligned_with','ENT_SUF_BADAWI','medium','Counted among the four great qutbs of Egyptian Sufism with al-Badawi.'),
 ('ENT_SUF_KIRMANI','reception_of','ENT_SUF_GHAZALI','low','Heir to the sober contemplative tradition consolidated by al-Ghazali.'),
 ('ENT_SUF_CHISHTI_MUIN','member_of','ENT_SUF_KUBRAWI','low','Some silsilas link Mu''in al-Din''s early training to the Central Asian milieu of Kubra''s contemporaries.');

\echo '--- REJECTED edges (bad id/type, or subject lacks a source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
