-- build_p7_orisha.sql  (GENERATED by gen_roster.py p7_orisha) — v1.80.0
-- 15 entities, 33 edges, 2 new periods, 2 new sources. Idempotent + self-validating.
BEGIN;

INSERT INTO periods (period_id, period_name, start_year, end_year) VALUES
 ('PER_ORISHA_ROOT','Yoruba Orisha (West African root)',-800,1500),
 ('PER_ORISHA_DIASPORA','Orisha New-World Diaspora (Lucumi/Candomble)',1500,2025)
ON CONFLICT (period_id) DO NOTHING;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_BRANDON_SANTERIA','secondary scholarship','George Brandon, Santeria from Africa to the New World: The Dead Sell Memories (Indiana Univ. Press, 1993)','Yoruba orisha tradition and its Cuban Lucumi/Santeria diaspora, including the orisha-saint syncretism'),
 ('SRC_BASCOM_IFA','secondary scholarship','William Bascom, Ifa Divination: Communication between Gods and Men in West Africa (Indiana Univ. Press, 1969)','Yoruba religion, Orunmila/Ifa, and the orisha pantheon (public ethnographic description)')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,trad text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_ORI_PANTHEON','The Orisha (Yoruba pantheon)','collective','collective','Yoruba-Orisha','divinity; cosmos; nature; human affairs','B','Collective hub for the orisha, the Yoruba divinities. Publicly attested in West African ethnography and the Lucumi/Candomble diaspora; living tradition.'),
 ('ENT_ORI_SEVEN_POWERS','Siete Potencias Africanas (Seven African Powers)','collective','collective','Yoruba-Orisha','protection; popular devotion','B','Popular Cuban-diaspora grouping of seven leading orishas invoked together; widely attested in Santeria devotional practice and material culture.'),
 ('ENT_ORI_OLODUMARE','Olodumare (Olorun)','deity','deity','Yoruba-Orisha','supreme being; creation; destiny; the sky','B','The remote Yoruba supreme being and source of ashe; not the object of a sacrificial cult himself. Publicly attested; living tradition.'),
 ('ENT_ORI_ESHU','Eshu (Elegguá)','deity','deity','Yoruba-Orisha','crossroads; messages; thresholds; trickster mediation','B','Messenger-trickster who opens and closes the way between humans and orishas; in Cuba called Eleggua. Publicly attested; living tradition.'),
 ('ENT_ORI_OBATALA','Obatalá (Oxalá)','deity','deity','Yoruba-Orisha','creation of human bodies; purity; wisdom; peace','B','Senior orisha of creation and moral order, associated with white. Brazilian Candomble: Oxala. Publicly attested; living tradition.'),
 ('ENT_ORI_OGUN','Ogun (Ogum)','deity','deity','Yoruba-Orisha','iron; war; tools; labor; technology','B','Orisha of iron, smithing, war and clearing the path. Publicly attested across West Africa and the diaspora; living tradition.'),
 ('ENT_ORI_SHANGO','Shango (Xangô)','deity','deity','Yoruba-Orisha','thunder; lightning; justice; kingship; fire','B','Thunder-king orisha, remembered as a deified Oyo ruler; lord of lightning and justice. Publicly attested; living tradition.'),
 ('ENT_ORI_OSHUN','Oshun (Oxum)','deity','deity','Yoruba-Orisha','fresh water; rivers; love; fertility; wealth; beauty','B','Orisha of the river and of love and fertility, junior wife of Shango in oral tradition. Publicly attested; living tradition.'),
 ('ENT_ORI_YEMOJA','Yemoja (Yemayá)','deity','deity','Yoruba-Orisha','motherhood; the sea; salt water; protection','B','Great mother orisha, of the Ogun river in Nigeria and of the sea in the Cuban diaspora (Yemaya). Publicly attested; living tradition.'),
 ('ENT_ORI_OYA','Oya','deity','deity','Yoruba-Orisha','wind; storms; the Niger river; the dead; transformation','B','Orisha of storms, wind and the marketplace, guardian of the cemetery gate; wife of Shango in oral tradition. Publicly attested; living tradition.'),
 ('ENT_ORI_BABALU_AYE','Babalú-Ayé (Omolu)','deity','deity','Yoruba-Orisha','smallpox; epidemic disease; healing; the earth','B','Orisha of contagious disease and its cure, treated with great respect; Brazilian Candomble: Omolu/Obaluaye. Publicly attested; living tradition.'),
 ('ENT_ORI_ORUNMILA','Orunmila (Orúnla)','deity','deity','Yoruba-Orisha','wisdom; destiny; Ifa divination; knowledge','B','Orisha of wisdom and witness to destiny, the patron of Ifa divination. Figure only; the divination corpus/odu interiors are not modeled. Publicly attested; living tradition.'),
 ('ENT_ORI_OLOKUN','Olokun','deity','deity','Yoruba-Orisha','the deep sea; the ocean depths; wealth; mystery','C','Orisha of the bottom of the sea and its hidden wealth, paired with Yemoja in oral tradition. Publicly attested; living tradition.'),
 ('ENT_ORI_IBEJI','Ibeji (the sacred twins)','deity','deity','Yoruba-Orisha','twins; childhood; fortune; doubling','C','The deified twins, honored for the special status of twins among the Yoruba. Publicly attested; living tradition.'),
 ('ENT_ORI_AGANJU','Aganju','deity','deity','Yoruba-Orisha','volcanoes; wilderness; the desert; rivers'' depths','C','Orisha of volcanic fire and the untamed wilderness, linked in oral tradition to Shango. Publicly attested; living tradition.');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'devotional',conf,'candidate_verified_name','Roster build via gen_roster.py (see CHANGELOG/git for release)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,etype text,note text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_ORI_PANTHEON','SRC_BASCOM_IFA','scholarly attestation','attestation'),
 ('ENT_ORI_SEVEN_POWERS','SRC_BRANDON_SANTERIA','scholarly attestation','attestation'),
 ('ENT_ORI_OLODUMARE','SRC_BASCOM_IFA','scholarly attestation','attestation'),
 ('ENT_ORI_ESHU','SRC_BRANDON_SANTERIA','scholarly attestation','attestation'),
 ('ENT_ORI_OBATALA','SRC_BRANDON_SANTERIA','scholarly attestation','attestation'),
 ('ENT_ORI_OGUN','SRC_BASCOM_IFA','scholarly attestation','attestation'),
 ('ENT_ORI_SHANGO','SRC_BRANDON_SANTERIA','scholarly attestation','attestation'),
 ('ENT_ORI_OSHUN','SRC_BRANDON_SANTERIA','scholarly attestation','attestation'),
 ('ENT_ORI_YEMOJA','SRC_BRANDON_SANTERIA','scholarly attestation','attestation'),
 ('ENT_ORI_OYA','SRC_BRANDON_SANTERIA','scholarly attestation','attestation'),
 ('ENT_ORI_BABALU_AYE','SRC_BRANDON_SANTERIA','scholarly attestation','attestation'),
 ('ENT_ORI_ORUNMILA','SRC_BASCOM_IFA','scholarly attestation','attestation'),
 ('ENT_ORI_OLOKUN','SRC_BRANDON_SANTERIA','scholarly attestation','attestation'),
 ('ENT_ORI_IBEJI','SRC_BASCOM_IFA','scholarly attestation','attestation'),
 ('ENT_ORI_AGANJU','SRC_BRANDON_SANTERIA','scholarly attestation','attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_ORI_PANTHEON','PER_ORISHA_ROOT','Collective hub for the orisha, the Yoruba divinities. Publicly attested in West African ethnography and the Lucumi/Candomble diaspora; living tradition.'),
 ('ENT_ORI_SEVEN_POWERS','PER_ORISHA_DIASPORA','Popular Cuban-diaspora grouping of seven leading orishas invoked together; widely attested in Santeria devotional practice and material culture.'),
 ('ENT_ORI_OLODUMARE','PER_ORISHA_ROOT','The remote Yoruba supreme being and source of ashe; not the object of a sacrificial cult himself. Publicly attested; living tradition.'),
 ('ENT_ORI_ESHU','PER_ORISHA_ROOT','Messenger-trickster who opens and closes the way between humans and orishas; in Cuba called Eleggua. Publicly attested; living tradition.'),
 ('ENT_ORI_OBATALA','PER_ORISHA_ROOT','Senior orisha of creation and moral order, associated with white. Brazilian Candomble: Oxala. Publicly attested; living tradition.'),
 ('ENT_ORI_OGUN','PER_ORISHA_ROOT','Orisha of iron, smithing, war and clearing the path. Publicly attested across West Africa and the diaspora; living tradition.'),
 ('ENT_ORI_SHANGO','PER_ORISHA_ROOT','Thunder-king orisha, remembered as a deified Oyo ruler; lord of lightning and justice. Publicly attested; living tradition.'),
 ('ENT_ORI_OSHUN','PER_ORISHA_ROOT','Orisha of the river and of love and fertility, junior wife of Shango in oral tradition. Publicly attested; living tradition.'),
 ('ENT_ORI_YEMOJA','PER_ORISHA_ROOT','Great mother orisha, of the Ogun river in Nigeria and of the sea in the Cuban diaspora (Yemaya). Publicly attested; living tradition.'),
 ('ENT_ORI_OYA','PER_ORISHA_ROOT','Orisha of storms, wind and the marketplace, guardian of the cemetery gate; wife of Shango in oral tradition. Publicly attested; living tradition.'),
 ('ENT_ORI_BABALU_AYE','PER_ORISHA_ROOT','Orisha of contagious disease and its cure, treated with great respect; Brazilian Candomble: Omolu/Obaluaye. Publicly attested; living tradition.'),
 ('ENT_ORI_ORUNMILA','PER_ORISHA_ROOT','Orisha of wisdom and witness to destiny, the patron of Ifa divination. Figure only; the divination corpus/odu interiors are not modeled. Publicly attested; living tradition.'),
 ('ENT_ORI_OLOKUN','PER_ORISHA_ROOT','Orisha of the bottom of the sea and its hidden wealth, paired with Yemoja in oral tradition. Publicly attested; living tradition.'),
 ('ENT_ORI_IBEJI','PER_ORISHA_ROOT','The deified twins, honored for the special status of twins among the Yoruba. Publicly attested; living tradition.'),
 ('ENT_ORI_AGANJU','PER_ORISHA_ROOT','Orisha of volcanic fire and the untamed wilderness, linked in oral tradition to Shango. Publicly attested; living tradition.');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_ORI_OLODUMARE','member_of','ENT_ORI_PANTHEON','high','Olodumare is the supreme being at the head of the Yoruba orisha cosmos (Bascom).'),
 ('ENT_ORI_ESHU','member_of','ENT_ORI_PANTHEON','high','Eshu/Eleggua is a principal orisha (Brandon).'),
 ('ENT_ORI_OBATALA','member_of','ENT_ORI_PANTHEON','high','Obatala is a senior orisha (Brandon).'),
 ('ENT_ORI_OGUN','member_of','ENT_ORI_PANTHEON','high','Ogun is a principal orisha (Bascom).'),
 ('ENT_ORI_SHANGO','member_of','ENT_ORI_PANTHEON','high','Shango is a principal orisha (Brandon).'),
 ('ENT_ORI_OSHUN','member_of','ENT_ORI_PANTHEON','high','Oshun is a principal orisha (Brandon).'),
 ('ENT_ORI_YEMOJA','member_of','ENT_ORI_PANTHEON','high','Yemoja is a principal orisha (Brandon).'),
 ('ENT_ORI_OYA','member_of','ENT_ORI_PANTHEON','high','Oya is a principal orisha (Brandon).'),
 ('ENT_ORI_BABALU_AYE','member_of','ENT_ORI_PANTHEON','high','Babalu-Aye is a principal orisha (Brandon).'),
 ('ENT_ORI_ORUNMILA','member_of','ENT_ORI_PANTHEON','high','Orunmila is the orisha of Ifa wisdom (Bascom).'),
 ('ENT_ORI_OLOKUN','member_of','ENT_ORI_PANTHEON','high','Olokun is an orisha of the deep sea (Brandon).'),
 ('ENT_ORI_IBEJI','member_of','ENT_ORI_PANTHEON','high','The Ibeji twins are venerated among the orisha (Bascom).'),
 ('ENT_ORI_AGANJU','member_of','ENT_ORI_PANTHEON','medium','Aganju is counted among the orisha (Brandon).'),
 ('ENT_ORI_ESHU','member_of','ENT_ORI_SEVEN_POWERS','medium','Eleggua is one of the Siete Potencias Africanas in Cuban devotion (Brandon).'),
 ('ENT_ORI_OGUN','member_of','ENT_ORI_SEVEN_POWERS','medium','Ogun is one of the Seven African Powers (Brandon).'),
 ('ENT_ORI_SHANGO','member_of','ENT_ORI_SEVEN_POWERS','medium','Shango is one of the Seven African Powers (Brandon).'),
 ('ENT_ORI_OBATALA','member_of','ENT_ORI_SEVEN_POWERS','medium','Obatala is one of the Seven African Powers (Brandon).'),
 ('ENT_ORI_OSHUN','member_of','ENT_ORI_SEVEN_POWERS','medium','Oshun is one of the Seven African Powers (Brandon).'),
 ('ENT_ORI_YEMOJA','member_of','ENT_ORI_SEVEN_POWERS','medium','Yemaya is one of the Seven African Powers (Brandon).'),
 ('ENT_ORI_ORUNMILA','member_of','ENT_ORI_SEVEN_POWERS','medium','Orula is commonly counted among the Seven African Powers in Cuban devotion (Brandon).'),
 ('ENT_ORI_ESHU','mediates','ENT_ORI_PANTHEON','medium','Eshu carries the offerings and messages between humans and all the orishas, opening the way; he is the mediator, not the ruler, of the pantheon (Bascom).'),
 ('ENT_ORI_OSHUN','consort_of','ENT_ORI_SHANGO','medium','In Yoruba oral tradition Oshun is a wife of Shango (Brandon).'),
 ('ENT_ORI_OYA','consort_of','ENT_ORI_SHANGO','medium','In Yoruba oral tradition Oya is a wife of Shango (Brandon).'),
 ('ENT_ORI_AGANJU','sibling_of','ENT_ORI_SHANGO','low','Aganju is linked to Shango as kin in some oral traditions (Brandon).'),
 ('ENT_ORI_OLOKUN','paired_with','ENT_ORI_YEMOJA','medium','Olokun (deep sea) is paired with Yemoja (sea/motherhood) in oral tradition (Brandon).'),
 ('ENT_ORI_SHANGO','syncretized_with','ENT_CHR_BARBARA','high','In Cuban Lucumi/Santeria Shango is identified with Saint Barbara, sharing thunder/lightning imagery (Brandon).'),
 ('ENT_ORI_ESHU','syncretized_with','ENT_SAINT_ANTHONY_PADUA','high','In Santeria Eleggua is commonly identified with Saint Anthony of Padua (and the Holy Child of Atocha, not in DB) (Brandon).'),
 ('ENT_ORI_BABALU_AYE','syncretized_with','ENT_NT_LAZARUS_BETHANY','high','In Santeria Babalu-Aye is identified with Saint Lazarus (San Lazaro), patron against disease; ENT_NT_LAZARUS_BETHANY is the in-DB Lazarus target (Brandon).'),
 ('ENT_ORI_OBATALA','syncretized_with','ENT_MARY_MERCY','high','In Santeria Obatala is identified with Our Lady of Mercy (la Merced), sharing the color white (Brandon).'),
 ('ENT_ORI_OGUN','syncretized_with','ENT_SAINT_PETER','high','In Santeria Ogun is identified with Saint Peter, linked by iron keys/tools (Brandon).'),
 ('ENT_ORI_ORUNMILA','syncretized_with','ENT_SAINT_FRANCIS','high','In Santeria Orunmila/Orula is identified with Saint Francis of Assisi (Brandon).'),
 ('ENT_ORI_YEMOJA','syncretized_with','ENT_SAINT_MARY','medium','In Cuban Santeria Yemaya is identified with the Marian title Our Lady of Regla (a title not in DB); wired to Mary Theotokos as the underlying Marian devotion (Brandon).'),
 ('ENT_ORI_OSHUN','syncretized_with','ENT_SAINT_MARY','medium','In Cuban Santeria Oshun is identified with Our Lady of Charity of El Cobre, Cuba''s patroness (a title not in DB, verified absent); wired to Mary Theotokos as the underlying Marian devotion (Brandon).');

\echo '--- REJECTED edges (bad id/type, or subject lacks a source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
