-- build_p5_discordianism.sql  (GENERATED by gen_roster.py p5_discordianism) — v1.80.0
-- 6 entities, 10 edges, 1 new periods, 2 new sources. Idempotent + self-validating.
BEGIN;

INSERT INTO periods (period_id, period_name, start_year, end_year) VALUES
 ('PER_DISCORDIAN','Discordian Era (Principia Discordia to present)',1958,2025)
ON CONFLICT (period_id) DO NOTHING;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_PRINCIPIA_DISCORDIA','primary text','Malaclypse the Younger (Greg Hill) & Omar Khayyam Ravenhurst (Kerry Thornley), Principia Discordia, or How I Found Goddess and What I Did to Her When I Found Her (1965; 4th ed. 1970)','Discordianism'),
 ('SRC_CUSACK_INVENTED_RELIGIONS','secondary scholarship','Carole M. Cusack, Invented Religions: Imagination, Fiction and Faith (Ashgate, 2010)','Discordianism')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,trad text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_DIS_DISCORDIANISM','Discordianism','tradition_hub','Movement','Discordianism','chaos; absurdism; parody religion; individualism','B','Tradition-hub. Discordianism is an absurdist/parody religion founded 1958-63 by Greg Hill and Kerry Thornley and codified in the Principia Discordia; genuinely practiced worldwide (cabals, ordinations, the ''every man a Pope'' ethos) and influential on chaos magic. Attested in the Principia Discordia and treated as a sincerely-held invented religion in Cusack 2010.'),
 ('ENT_DIS_ERIS','Eris (Discordian Goddess of Chaos)','Goddess','Goddess','Discordianism','chaos; discord; creative disorder','B','The Discordian Eris/Discordia, central deity venerated by practicing Discordians as the benevolent Goddess of Chaos. An explicit modern reception of the ancient Greek Eris (ENT_ERIS); modeled neutrally as the sincerely-held object of Discordian devotion per the Principia Discordia. Homonym of, and reception_of, ENT_ERIS (Greek).'),
 ('ENT_DIS_SACRED_CHAO','The Sacred Chao','Sacred object','Symbol','Discordianism','cosmology; order and chaos; symbol','B','Core Discordian symbol (a yin-yang-like figure bearing the Apple of Discord and the Pentagon), used devotionally/ritually as the emblem of the interplay of order and disorder. Attested in the Principia Discordia.'),
 ('ENT_DIS_GOLDEN_APPLE','The Golden Apple of Discord (Discordian)','Sacred object','Relic','Discordianism','discord; chaos; relic','B','The golden apple inscribed ''kallisti'' (''to the prettiest one''), revered in Discordian practice as Eris''s defining relic and a sign of fruitful discord. A reception of the apple from the Greek Judgment of Paris myth, recontextualized in the Principia Discordia.'),
 ('ENT_DIS_GREYFACE','Greyface','Antagonist figure','Figure','Discordianism','order; seriousness; the curse of ''the Curse of Greyface''','C','The personified spirit of grim order and life-denying seriousness in Discordian myth; a man of c.1166 BC said to have taught that life is serious and play is wrong, originating ''the Curse of Greyface.'' The doctrinal antagonist of Eris/chaos; attested in the Principia Discordia.'),
 ('ENT_DIS_LAW_OF_FIVES','The Law of Fives','Doctrine','Doctrine','Discordianism','doctrine; numerology; hermeneutics','C','Core Discordian doctrine that all things happen in fives, or are divisible by or related to five (the ''Law of Fives is never wrong'' precisely because one can always find fives). Practiced as a half-serious interpretive/numerological lens; attested in the Principia Discordia.');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'devotional',conf,'candidate_verified_name','Roster build via gen_roster.py (see CHANGELOG/git for release)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,etype text,note text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_DIS_DISCORDIANISM','SRC_CUSACK_INVENTED_RELIGIONS','scholarly attestation','attestation'),
 ('ENT_DIS_ERIS','SRC_PRINCIPIA_DISCORDIA','primary text attestation','attestation'),
 ('ENT_DIS_SACRED_CHAO','SRC_PRINCIPIA_DISCORDIA','primary text attestation','attestation'),
 ('ENT_DIS_GOLDEN_APPLE','SRC_PRINCIPIA_DISCORDIA','primary text attestation','attestation'),
 ('ENT_DIS_GREYFACE','SRC_PRINCIPIA_DISCORDIA','primary text attestation','attestation'),
 ('ENT_DIS_LAW_OF_FIVES','SRC_PRINCIPIA_DISCORDIA','primary text attestation','attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_DIS_DISCORDIANISM','PER_DISCORDIAN','Tradition-hub. Discordianism is an absurdist/parody religion founded 1958-63 by Greg Hill and Kerry Thornley and codified in the Principia Discordia; genuinely practiced worldwide (cabals, ordinations, the ''every man a Pope'' ethos) and influential on chaos magic. Attested in the Principia Discordia and treated as a sincerely-held invented religion in Cusack 2010.'),
 ('ENT_DIS_ERIS','PER_DISCORDIAN','The Discordian Eris/Discordia, central deity venerated by practicing Discordians as the benevolent Goddess of Chaos. An explicit modern reception of the ancient Greek Eris (ENT_ERIS); modeled neutrally as the sincerely-held object of Discordian devotion per the Principia Discordia. Homonym of, and reception_of, ENT_ERIS (Greek).'),
 ('ENT_DIS_SACRED_CHAO','PER_DISCORDIAN','Core Discordian symbol (a yin-yang-like figure bearing the Apple of Discord and the Pentagon), used devotionally/ritually as the emblem of the interplay of order and disorder. Attested in the Principia Discordia.'),
 ('ENT_DIS_GOLDEN_APPLE','PER_DISCORDIAN','The golden apple inscribed ''kallisti'' (''to the prettiest one''), revered in Discordian practice as Eris''s defining relic and a sign of fruitful discord. A reception of the apple from the Greek Judgment of Paris myth, recontextualized in the Principia Discordia.'),
 ('ENT_DIS_GREYFACE','PER_DISCORDIAN','The personified spirit of grim order and life-denying seriousness in Discordian myth; a man of c.1166 BC said to have taught that life is serious and play is wrong, originating ''the Curse of Greyface.'' The doctrinal antagonist of Eris/chaos; attested in the Principia Discordia.'),
 ('ENT_DIS_LAW_OF_FIVES','PER_DISCORDIAN','Core Discordian doctrine that all things happen in fives, or are divisible by or related to five (the ''Law of Fives is never wrong'' precisely because one can always find fives). Practiced as a half-serious interpretive/numerological lens; attested in the Principia Discordia.');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_DIS_ERIS','member_of','ENT_DIS_DISCORDIANISM','high','The Discordian Eris is the central deity of the Discordianism tradition-hub.'),
 ('ENT_DIS_SACRED_CHAO','member_of','ENT_DIS_DISCORDIANISM','high','The Sacred Chao is a core Discordian symbol belonging to the tradition.'),
 ('ENT_DIS_GOLDEN_APPLE','member_of','ENT_DIS_DISCORDIANISM','high','The Golden Apple is a foundational Discordian relic belonging to the tradition.'),
 ('ENT_DIS_GREYFACE','member_of','ENT_DIS_DISCORDIANISM','high','Greyface is a Discordian mythic figure belonging to the tradition.'),
 ('ENT_DIS_LAW_OF_FIVES','member_of','ENT_DIS_DISCORDIANISM','high','The Law of Fives is a core doctrine belonging to the Discordian tradition.'),
 ('ENT_DIS_ERIS','reception_of','ENT_ERIS','high','The Discordian Goddess of Chaos is an explicit modern reception/re-imagining of the ancient Greek Eris (ENT_ERIS), the founding act of Discordian invention per the Principia Discordia and Cusack 2010.'),
 ('ENT_DIS_ERIS','presides_over','ENT_DIS_SACRED_CHAO','medium','In Discordian cosmology Eris reveals/governs the Sacred Chao as the emblem of her ordered-and-chaotic cosmos.'),
 ('ENT_DIS_SACRED_CHAO','symbolizes','ENT_DIS_ERIS','high','The Sacred Chao is the central emblem of the Discordian Eris and her doctrine of the chaos/order interplay.'),
 ('ENT_DIS_GOLDEN_APPLE','symbolizes','ENT_DIS_ERIS','high','The kallisti-inscribed Golden Apple is Eris''s defining emblem in both the Greek myth and Discordian practice.'),
 ('ENT_DIS_GREYFACE','opposes','ENT_DIS_ERIS','high','Greyface, the spirit of grim order, is the doctrinal antagonist of the chaos-goddess Eris in Discordian myth.');

\echo '--- REJECTED edges (bad id/type, or subject lacks a source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
