-- build_arthurian.sql  (GENERATED by gen_arthurian.py) — v1.78.0
-- The Arthurian legend / Matter of Britain (the Grail mythos).
-- 35 new entities, 75 edges. Idempotent + self-validating.
BEGIN;

INSERT INTO periods (period_id, period_name, start_year, end_year) VALUES
 ('PER_ARTHURIAN','Arthurian Literary Cycle (Matter of Britain)',1100,1500)
ON CONFLICT (period_id) DO NOTHING;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_GEOFFREY_MONMOUTH','primary text','Geoffrey of Monmouth, Historia Regum Britanniae (c. 1136)','Arthurian'),
 ('SRC_CHRETIEN_TROYES','primary text','Chrétien de Troyes, the Arthurian romances (c. 1170-1190)','Arthurian'),
 ('SRC_ROBERT_BORON','primary text','Robert de Boron, the Little Grail Cycle / Joseph d''Arimathie, Merlin (c. 1190-1210)','Arthurian'),
 ('SRC_VULGATE_CYCLE','primary text','The Vulgate Cycle (Lancelot-Grail) (c. 1210-1235)','Arthurian'),
 ('SRC_WOLFRAM_PARZIVAL','primary text','Wolfram von Eschenbach, Parzival (c. 1200-1210)','Arthurian'),
 ('SRC_MALORY_MORTE','primary text','Sir Thomas Malory, Le Morte d''Arthur (c. 1469-1485)','Arthurian')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_ART_ROUND_TABLE','The Knights of the Round Table','Collective','Order of chivalry','chivalry; fellowship; defense of the realm; the Grail quest','B','The fellowship of knights sworn to Arthur, gathered about the Round Table at Camelot.'),
 ('ENT_ART_ARTHUR','King Arthur','King','Legendary king','kingship; war; the Round Table; the once and future king','B','Legendary king of the Britons who founds the Round Table at Camelot and is borne to Avalon after Camlann.'),
 ('ENT_ART_GUINEVERE','Guinevere','Queen','Legendary queen','queenship; courtly love; the affair with Lancelot','B','Wife of Arthur whose love for Lancelot precipitates the fall of the realm.'),
 ('ENT_ART_UTHER_PENDRAGON','Uther Pendragon','King','Legendary king','kingship; war; the begetting of Arthur','B','King who, disguised by Merlin as Gorlois, begets Arthur upon Igraine at Tintagel.'),
 ('ENT_ART_IGRAINE','Igraine','Queen','Legendary noblewoman','noble lineage; the begetting of Arthur','B','Wife of Gorlois then Uther; mother of Arthur, Morgan, and Morgause.'),
 ('ENT_ART_MORDRED','Mordred','Knight','Legendary traitor','treachery; usurpation; the destruction of the realm','B','Begotten by Arthur upon Morgause; slays and is slain by Arthur at Camlann.'),
 ('ENT_ART_MORGAN_LE_FAY','Morgan le Fay','Enchantress','Sorceress','magic; healing; enmity toward the court','B','Magical half-sister of Arthur, both healer at Avalon and adversary of the court.'),
 ('ENT_ART_MORGAUSE','Morgause','Queen','Legendary noblewoman','queenship; the begetting of Mordred; the Orkney lineage','B','Half-sister of Arthur, wife of Lot, mother of the Orkney knights and of Mordred.'),
 ('ENT_ART_KING_LOT','King Lot','King','Legendary king','kingship; war; the Orkney lineage','B','King of Orkney, husband of Morgause and father of Gawain and his brothers.'),
 ('ENT_ART_MERLIN','Merlin','Sorcerer','Prophet-mage','magic; prophecy; counsel; the founding of the realm','B','Prophet-magician who engineers Arthur''s begetting and establishes the Round Table; in Robert de Boron, fathered by a devil and baptized.'),
 ('ENT_ART_LADY_OF_THE_LAKE','The Lady of the Lake','Enchantress','Otherworldly figure','magic; the otherworld; the giving of Excalibur','B','Otherworldly enchantress (Nimue/Viviane) who gives Excalibur, fosters Lancelot, and enchants Merlin.'),
 ('ENT_ART_LANCELOT','Lancelot','Knight','Knight of the Round Table','chivalry; prowess; courtly love; the adultery with Guinevere','B','The foremost knight, whose love for Guinevere brings the realm to ruin.'),
 ('ENT_ART_GALAHAD','Galahad','Knight','Knight of the Round Table','perfect chastity; the Grail quest; holiness','B','Son of Lancelot and Elaine of Corbenic, the sinless knight who achieves the Grail.'),
 ('ENT_ART_PERCEVAL','Perceval','Knight','Knight of the Round Table','the Grail quest; innocence; chivalric formation','B','The naive young knight (Parzival) who comes to the Grail castle; one of the Grail achievers.'),
 ('ENT_ART_GAWAIN','Gawain','Knight','Knight of the Round Table','chivalry; courtesy; kinship loyalty; the test of honor','B','Eldest son of Lot and Morgause and nephew of Arthur; tested by the Green Knight.'),
 ('ENT_ART_BORS','Bors','Knight','Knight of the Round Table','chivalry; piety; the Grail quest','B','Cousin of Lancelot and the only Grail achiever to return to Camelot.'),
 ('ENT_ART_TRISTAN','Tristan','Knight','Knight of the Round Table','chivalry; the tragic love for Isolde','B','Cornish knight whose love for Isolde parallels the Lancelot-Guinevere affair.'),
 ('ENT_ART_KAY','Kay','Knight','Knight of the Round Table','the seneschalship; blunt speech','B','Arthur''s foster-brother and seneschal, brusque but loyal.'),
 ('ENT_ART_BEDIVERE','Bedivere','Knight','Knight of the Round Table','loyalty; the return of Excalibur','B','Companion who casts Excalibur back into the lake at Arthur''s end.'),
 ('ENT_ART_GARETH','Gareth','Knight','Knight of the Round Table','chivalry; the proving of worth; kinship','B','Brother of Gawain who proves his knighthood; slain inadvertently by Lancelot.'),
 ('ENT_ART_GAHERIS','Gaheris','Knight','Knight of the Round Table','kinship; the Orkney feud; vengeance','B','Brother of Gawain who slays Morgause; later killed by Lancelot.'),
 ('ENT_ART_AGRAVAIN','Agravain','Knight','Knight of the Round Table','kinship; intrigue; the exposure of the adultery','B','Brother of Gawain who with Mordred exposes the affair, triggering the collapse.'),
 ('ENT_ART_LAMORAK','Lamorak','Knight','Knight of the Round Table','prowess; the Pellinore-Orkney feud; courtly love','B','Son of Pellinore; his affair with Morgause leads to murder by the Orkney brothers.'),
 ('ENT_ART_PELLINORE','Pellinore','King','Knight of the Round Table','kingship; the Questing Beast; the feud','B','King who pursues the Questing Beast, slays Lot, and fathers Lamorak.'),
 ('ENT_ART_GREEN_KNIGHT','The Green Knight','Legendary figure','Otherworldly challenger','the beheading game; the test of honor; the otherworld','B','Green otherworldly challenger (Bertilak enchanted) who tests Gawain''s honor in the beheading game.'),
 ('ENT_ART_FISHER_KING','The Fisher King','King','Grail guardian','guardianship of the Grail; the wasteland and its healing','B','Maimed guardian of the Grail (Pelles/Anfortas) whose wound mirrors the wasteland.'),
 ('ENT_ART_ELAINE_CORBENIC','Elaine of Corbenic','Legendary figure','Grail lineage','the Grail lineage; the conception of Galahad','B','Daughter of Pelles who conceives Galahad with Lancelot to fulfill prophecy.'),
 ('ENT_ART_ISOLDE','Isolde','Queen','Legendary lover','tragic love; the love potion; courtly devotion','B','Irish princess and queen of Cornwall, fated lover of Tristan.'),
 ('ENT_ART_ELAINE_ASTOLAT','Elaine of Astolat','Legendary figure','Legendary lover','unrequited love; tragic death','B','The lily maid of Astolat who dies of unrequited love for Lancelot.'),
 ('ENT_ART_GRAIL','The Holy Grail','Sacred object','Holy relic','divine grace; revelation; healing; the Eucharist','B','The vessel of the Last Supper brought to Britain by Joseph of Arimathea; object of the great quest.'),
 ('ENT_ART_EXCALIBUR','Excalibur','Relic','Legendary sword','kingship; war; sovereignty; the otherworld','B','Arthur''s sword (Geoffrey''s Caliburn), given by the Lady of the Lake and returned to her at his death.'),
 ('ENT_ART_ROUND_TABLE_OBJECT','The Round Table','Sacred object','Order of chivalry','fellowship; equality of the knights; the chivalric order','B','The round table made by Merlin so that no knight should sit above another.'),
 ('ENT_ART_AVALON','Avalon','cosmological realm','Otherworldly isle','the otherworld; healing; the resting place of Arthur','B','Otherworldly isle where Excalibur was forged and to which Arthur is borne to be healed.'),
 ('ENT_ART_CAMELOT','Camelot','cosmological realm','Royal seat','kingship; the chivalric court; the seat of the Round Table','B','The principal seat of Arthur''s court and of the Round Table.'),
 ('ENT_ART_SIEGE_PERILOUS','The Siege Perilous','Sacred object','Sacred seat','the Grail destiny; sanctity; predestination','B','The empty seat, fatal to the unworthy, reserved for the Grail knight Galahad.');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,'Arthurian',etype,cat,dom,'literary',conf,'candidate_verified_name','Arthurian legend / Matter of Britain (v1.78.0)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,note text,etype text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_ART_ROUND_TABLE','SRC_MALORY_MORTE','The fellowship of knights sworn to Arthur, gathered about the Round Table at Camelot.','primary text attestation'),
 ('ENT_ART_ARTHUR','SRC_GEOFFREY_MONMOUTH','Legendary king of the Britons who founds the Round Table at Camelot and is borne to Avalon after Camlann.','primary text attestation'),
 ('ENT_ART_GUINEVERE','SRC_MALORY_MORTE','Wife of Arthur whose love for Lancelot precipitates the fall of the realm.','primary text attestation'),
 ('ENT_ART_UTHER_PENDRAGON','SRC_GEOFFREY_MONMOUTH','King who, disguised by Merlin as Gorlois, begets Arthur upon Igraine at Tintagel.','primary text attestation'),
 ('ENT_ART_IGRAINE','SRC_GEOFFREY_MONMOUTH','Wife of Gorlois then Uther; mother of Arthur, Morgan, and Morgause.','primary text attestation'),
 ('ENT_ART_MORDRED','SRC_MALORY_MORTE','Begotten by Arthur upon Morgause; slays and is slain by Arthur at Camlann.','primary text attestation'),
 ('ENT_ART_MORGAN_LE_FAY','SRC_VULGATE_CYCLE','Magical half-sister of Arthur, both healer at Avalon and adversary of the court.','primary text attestation'),
 ('ENT_ART_MORGAUSE','SRC_MALORY_MORTE','Half-sister of Arthur, wife of Lot, mother of the Orkney knights and of Mordred.','primary text attestation'),
 ('ENT_ART_KING_LOT','SRC_MALORY_MORTE','King of Orkney, husband of Morgause and father of Gawain and his brothers.','primary text attestation'),
 ('ENT_ART_MERLIN','SRC_GEOFFREY_MONMOUTH','Prophet-magician who engineers Arthur''s begetting and establishes the Round Table; in Robert de Boron, fathered by a devil and baptized.','primary text attestation'),
 ('ENT_ART_LADY_OF_THE_LAKE','SRC_VULGATE_CYCLE','Otherworldly enchantress (Nimue/Viviane) who gives Excalibur, fosters Lancelot, and enchants Merlin.','primary text attestation'),
 ('ENT_ART_LANCELOT','SRC_CHRETIEN_TROYES','The foremost knight, whose love for Guinevere brings the realm to ruin.','primary text attestation'),
 ('ENT_ART_GALAHAD','SRC_VULGATE_CYCLE','Son of Lancelot and Elaine of Corbenic, the sinless knight who achieves the Grail.','primary text attestation'),
 ('ENT_ART_PERCEVAL','SRC_CHRETIEN_TROYES','The naive young knight (Parzival) who comes to the Grail castle; one of the Grail achievers.','primary text attestation'),
 ('ENT_ART_GAWAIN','SRC_GEOFFREY_MONMOUTH','Eldest son of Lot and Morgause and nephew of Arthur; tested by the Green Knight.','primary text attestation'),
 ('ENT_ART_BORS','SRC_VULGATE_CYCLE','Cousin of Lancelot and the only Grail achiever to return to Camelot.','primary text attestation'),
 ('ENT_ART_TRISTAN','SRC_MALORY_MORTE','Cornish knight whose love for Isolde parallels the Lancelot-Guinevere affair.','primary text attestation'),
 ('ENT_ART_KAY','SRC_GEOFFREY_MONMOUTH','Arthur''s foster-brother and seneschal, brusque but loyal.','primary text attestation'),
 ('ENT_ART_BEDIVERE','SRC_GEOFFREY_MONMOUTH','Companion who casts Excalibur back into the lake at Arthur''s end.','primary text attestation'),
 ('ENT_ART_GARETH','SRC_MALORY_MORTE','Brother of Gawain who proves his knighthood; slain inadvertently by Lancelot.','primary text attestation'),
 ('ENT_ART_GAHERIS','SRC_MALORY_MORTE','Brother of Gawain who slays Morgause; later killed by Lancelot.','primary text attestation'),
 ('ENT_ART_AGRAVAIN','SRC_MALORY_MORTE','Brother of Gawain who with Mordred exposes the affair, triggering the collapse.','primary text attestation'),
 ('ENT_ART_LAMORAK','SRC_MALORY_MORTE','Son of Pellinore; his affair with Morgause leads to murder by the Orkney brothers.','primary text attestation'),
 ('ENT_ART_PELLINORE','SRC_MALORY_MORTE','King who pursues the Questing Beast, slays Lot, and fathers Lamorak.','primary text attestation'),
 ('ENT_ART_GREEN_KNIGHT','SRC_MALORY_MORTE','Green otherworldly challenger (Bertilak enchanted) who tests Gawain''s honor in the beheading game.','primary text attestation'),
 ('ENT_ART_FISHER_KING','SRC_WOLFRAM_PARZIVAL','Maimed guardian of the Grail (Pelles/Anfortas) whose wound mirrors the wasteland.','primary text attestation'),
 ('ENT_ART_ELAINE_CORBENIC','SRC_VULGATE_CYCLE','Daughter of Pelles who conceives Galahad with Lancelot to fulfill prophecy.','primary text attestation'),
 ('ENT_ART_ISOLDE','SRC_MALORY_MORTE','Irish princess and queen of Cornwall, fated lover of Tristan.','primary text attestation'),
 ('ENT_ART_ELAINE_ASTOLAT','SRC_MALORY_MORTE','The lily maid of Astolat who dies of unrequited love for Lancelot.','primary text attestation'),
 ('ENT_ART_GRAIL','SRC_ROBERT_BORON','The vessel of the Last Supper brought to Britain by Joseph of Arimathea; object of the great quest.','primary text attestation'),
 ('ENT_ART_EXCALIBUR','SRC_MALORY_MORTE','Arthur''s sword (Geoffrey''s Caliburn), given by the Lady of the Lake and returned to her at his death.','primary text attestation'),
 ('ENT_ART_ROUND_TABLE_OBJECT','SRC_ROBERT_BORON','The round table made by Merlin so that no knight should sit above another.','primary text attestation'),
 ('ENT_ART_AVALON','SRC_GEOFFREY_MONMOUTH','Otherworldly isle where Excalibur was forged and to which Arthur is borne to be healed.','primary text attestation'),
 ('ENT_ART_CAMELOT','SRC_CHRETIEN_TROYES','The principal seat of Arthur''s court and of the Round Table.','primary text attestation'),
 ('ENT_ART_SIEGE_PERILOUS','SRC_VULGATE_CYCLE','The empty seat, fatal to the unworthy, reserved for the Grail knight Galahad.','primary text attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_ART_ROUND_TABLE','PER_ARTHURIAN','The fellowship of knights sworn to Arthur, gathered about the Round Table at Camelot.'),
 ('ENT_ART_ARTHUR','PER_ARTHURIAN','Legendary king of the Britons who founds the Round Table at Camelot and is borne to Avalon after Camlann.'),
 ('ENT_ART_GUINEVERE','PER_ARTHURIAN','Wife of Arthur whose love for Lancelot precipitates the fall of the realm.'),
 ('ENT_ART_UTHER_PENDRAGON','PER_ARTHURIAN','King who, disguised by Merlin as Gorlois, begets Arthur upon Igraine at Tintagel.'),
 ('ENT_ART_IGRAINE','PER_ARTHURIAN','Wife of Gorlois then Uther; mother of Arthur, Morgan, and Morgause.'),
 ('ENT_ART_MORDRED','PER_ARTHURIAN','Begotten by Arthur upon Morgause; slays and is slain by Arthur at Camlann.'),
 ('ENT_ART_MORGAN_LE_FAY','PER_ARTHURIAN','Magical half-sister of Arthur, both healer at Avalon and adversary of the court.'),
 ('ENT_ART_MORGAUSE','PER_ARTHURIAN','Half-sister of Arthur, wife of Lot, mother of the Orkney knights and of Mordred.'),
 ('ENT_ART_KING_LOT','PER_ARTHURIAN','King of Orkney, husband of Morgause and father of Gawain and his brothers.'),
 ('ENT_ART_MERLIN','PER_ARTHURIAN','Prophet-magician who engineers Arthur''s begetting and establishes the Round Table; in Robert de Boron, fathered by a devil and baptized.'),
 ('ENT_ART_LADY_OF_THE_LAKE','PER_ARTHURIAN','Otherworldly enchantress (Nimue/Viviane) who gives Excalibur, fosters Lancelot, and enchants Merlin.'),
 ('ENT_ART_LANCELOT','PER_ARTHURIAN','The foremost knight, whose love for Guinevere brings the realm to ruin.'),
 ('ENT_ART_GALAHAD','PER_ARTHURIAN','Son of Lancelot and Elaine of Corbenic, the sinless knight who achieves the Grail.'),
 ('ENT_ART_PERCEVAL','PER_ARTHURIAN','The naive young knight (Parzival) who comes to the Grail castle; one of the Grail achievers.'),
 ('ENT_ART_GAWAIN','PER_ARTHURIAN','Eldest son of Lot and Morgause and nephew of Arthur; tested by the Green Knight.'),
 ('ENT_ART_BORS','PER_ARTHURIAN','Cousin of Lancelot and the only Grail achiever to return to Camelot.'),
 ('ENT_ART_TRISTAN','PER_ARTHURIAN','Cornish knight whose love for Isolde parallels the Lancelot-Guinevere affair.'),
 ('ENT_ART_KAY','PER_ARTHURIAN','Arthur''s foster-brother and seneschal, brusque but loyal.'),
 ('ENT_ART_BEDIVERE','PER_ARTHURIAN','Companion who casts Excalibur back into the lake at Arthur''s end.'),
 ('ENT_ART_GARETH','PER_ARTHURIAN','Brother of Gawain who proves his knighthood; slain inadvertently by Lancelot.'),
 ('ENT_ART_GAHERIS','PER_ARTHURIAN','Brother of Gawain who slays Morgause; later killed by Lancelot.'),
 ('ENT_ART_AGRAVAIN','PER_ARTHURIAN','Brother of Gawain who with Mordred exposes the affair, triggering the collapse.'),
 ('ENT_ART_LAMORAK','PER_ARTHURIAN','Son of Pellinore; his affair with Morgause leads to murder by the Orkney brothers.'),
 ('ENT_ART_PELLINORE','PER_ARTHURIAN','King who pursues the Questing Beast, slays Lot, and fathers Lamorak.'),
 ('ENT_ART_GREEN_KNIGHT','PER_ARTHURIAN','Green otherworldly challenger (Bertilak enchanted) who tests Gawain''s honor in the beheading game.'),
 ('ENT_ART_FISHER_KING','PER_ARTHURIAN','Maimed guardian of the Grail (Pelles/Anfortas) whose wound mirrors the wasteland.'),
 ('ENT_ART_ELAINE_CORBENIC','PER_ARTHURIAN','Daughter of Pelles who conceives Galahad with Lancelot to fulfill prophecy.'),
 ('ENT_ART_ISOLDE','PER_ARTHURIAN','Irish princess and queen of Cornwall, fated lover of Tristan.'),
 ('ENT_ART_ELAINE_ASTOLAT','PER_ARTHURIAN','The lily maid of Astolat who dies of unrequited love for Lancelot.'),
 ('ENT_ART_GRAIL','PER_ARTHURIAN','The vessel of the Last Supper brought to Britain by Joseph of Arimathea; object of the great quest.'),
 ('ENT_ART_EXCALIBUR','PER_ARTHURIAN','Arthur''s sword (Geoffrey''s Caliburn), given by the Lady of the Lake and returned to her at his death.'),
 ('ENT_ART_ROUND_TABLE_OBJECT','PER_ARTHURIAN','The round table made by Merlin so that no knight should sit above another.'),
 ('ENT_ART_AVALON','PER_ARTHURIAN','Otherworldly isle where Excalibur was forged and to which Arthur is borne to be healed.'),
 ('ENT_ART_CAMELOT','PER_ARTHURIAN','The principal seat of Arthur''s court and of the Round Table.'),
 ('ENT_ART_SIEGE_PERILOUS','PER_ARTHURIAN','The empty seat, fatal to the unworthy, reserved for the Grail knight Galahad.');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_ART_LANCELOT','member_of','ENT_ART_ROUND_TABLE','high','Foremost knight of the Round Table.'),
 ('ENT_ART_GALAHAD','member_of','ENT_ART_ROUND_TABLE','high','Takes the Siege Perilous.'),
 ('ENT_ART_PERCEVAL','member_of','ENT_ART_ROUND_TABLE','high','Grail-questing knight.'),
 ('ENT_ART_GAWAIN','member_of','ENT_ART_ROUND_TABLE','high','Chief knight of the Round Table.'),
 ('ENT_ART_BORS','member_of','ENT_ART_ROUND_TABLE','high','Grail-achieving knight.'),
 ('ENT_ART_TRISTAN','member_of','ENT_ART_ROUND_TABLE','high','Admitted in the Prose Tristan and Malory.'),
 ('ENT_ART_KAY','member_of','ENT_ART_ROUND_TABLE','high','Seneschal-knight.'),
 ('ENT_ART_BEDIVERE','member_of','ENT_ART_ROUND_TABLE','high','Companion-knight.'),
 ('ENT_ART_GARETH','member_of','ENT_ART_ROUND_TABLE','high','Proves his worth and joins.'),
 ('ENT_ART_GAHERIS','member_of','ENT_ART_ROUND_TABLE','high','Orkney knight.'),
 ('ENT_ART_AGRAVAIN','member_of','ENT_ART_ROUND_TABLE','high','Orkney knight.'),
 ('ENT_ART_LAMORAK','member_of','ENT_ART_ROUND_TABLE','high','Among the mightiest knights.'),
 ('ENT_ART_PELLINORE','member_of','ENT_ART_ROUND_TABLE','high','King and knight of the Round Table.'),
 ('ENT_ART_MORDRED','member_of','ENT_ART_ROUND_TABLE','high','Seated before his treachery.'),
 ('ENT_ART_ARTHUR','member_of','ENT_ART_ROUND_TABLE','high','Head of the fellowship.'),
 ('ENT_ART_ARTHUR','child_of','ENT_ART_UTHER_PENDRAGON','high','Begotten by Uther at Tintagel.'),
 ('ENT_ART_ARTHUR','child_of','ENT_ART_IGRAINE','high','Son of Igraine.'),
 ('ENT_ART_ARTHUR','spouse_of','ENT_ART_GUINEVERE','high','Arthur marries Guinevere.'),
 ('ENT_ART_MORDRED','child_of','ENT_ART_ARTHUR','high','The incestuous begetting upon Morgause.'),
 ('ENT_ART_MORDRED','child_of','ENT_ART_MORGAUSE','high','Son of Morgause.'),
 ('ENT_ART_MORGAN_LE_FAY','sibling_of','ENT_ART_ARTHUR','high','Half-sister via Igraine.'),
 ('ENT_ART_MORGAUSE','sibling_of','ENT_ART_ARTHUR','high','Half-sister via Igraine.'),
 ('ENT_ART_MORGAN_LE_FAY','child_of','ENT_ART_IGRAINE','high','Daughter of Igraine by Gorlois.'),
 ('ENT_ART_MORGAUSE','child_of','ENT_ART_IGRAINE','high','Daughter of Igraine by Gorlois.'),
 ('ENT_ART_MORGAUSE','spouse_of','ENT_ART_KING_LOT','high','Wife of King Lot.'),
 ('ENT_ART_GAWAIN','child_of','ENT_ART_MORGAUSE','high','Son of Morgause and Lot.'),
 ('ENT_ART_GAWAIN','child_of','ENT_ART_KING_LOT','high','Son of Lot.'),
 ('ENT_ART_GARETH','child_of','ENT_ART_MORGAUSE','high','Son of Morgause and Lot.'),
 ('ENT_ART_GARETH','child_of','ENT_ART_KING_LOT','high','Son of Lot.'),
 ('ENT_ART_GAHERIS','child_of','ENT_ART_MORGAUSE','high','Son of Morgause and Lot.'),
 ('ENT_ART_GAHERIS','child_of','ENT_ART_KING_LOT','high','Son of Lot.'),
 ('ENT_ART_AGRAVAIN','child_of','ENT_ART_MORGAUSE','high','Son of Morgause and Lot.'),
 ('ENT_ART_AGRAVAIN','child_of','ENT_ART_KING_LOT','high','Son of Lot.'),
 ('ENT_ART_LAMORAK','child_of','ENT_ART_PELLINORE','high','Son of King Pellinore.'),
 ('ENT_ART_GALAHAD','child_of','ENT_ART_LANCELOT','high','Son of Lancelot.'),
 ('ENT_ART_GALAHAD','child_of','ENT_ART_ELAINE_CORBENIC','high','Son of Elaine of Corbenic.'),
 ('ENT_ART_ELAINE_CORBENIC','child_of','ENT_ART_FISHER_KING','high','Daughter of the Grail-king Pelles.'),
 ('ENT_ART_MORDRED','opposes','ENT_ART_ARTHUR','high','Usurps the throne; the final betrayal at Camlann.'),
 ('ENT_ART_MORDRED','slays','ENT_ART_ARTHUR','high','Mortally wounds Arthur at Camlann.'),
 ('ENT_ART_ARTHUR','slays','ENT_ART_MORDRED','high','Arthur slays Mordred at Camlann.'),
 ('ENT_ART_GREEN_KNIGHT','opposes','ENT_ART_GAWAIN','high','Tests Gawain through the beheading game.'),
 ('ENT_ART_LANCELOT','paired_with','ENT_ART_GUINEVERE','medium','The adulterous love of Lancelot and Guinevere.'),
 ('ENT_ART_PELLINORE','slays','ENT_ART_KING_LOT','high','Ignites the Pellinore-Orkney feud.'),
 ('ENT_ART_TRISTAN','paired_with','ENT_ART_ISOLDE','high','The great tragic lovers, bound by the love potion.'),
 ('ENT_ART_ELAINE_ASTOLAT','presides_over','ENT_LOVE','medium','The lily maid of Astolat embodies the motif of tragic, unrequited love for Lancelot.'),
 ('ENT_ART_GRAIL','mediated_by','ENT_NT_JOSEPH_ARIMATHEA','high','Joseph brings the Grail to Britain (Robert de Boron).'),
 ('ENT_ART_GRAIL','reception_of','ENT_JESUS_CHRIST','high','The cup of the Last Supper / vessel of Christ''s blood.'),
 ('ENT_ART_GALAHAD','guardian_of','ENT_ART_GRAIL','high','Supreme achiever of the Grail.'),
 ('ENT_ART_PERCEVAL','guardian_of','ENT_ART_GRAIL','high','One of the three Grail achievers.'),
 ('ENT_ART_BORS','guardian_of','ENT_ART_GRAIL','high','Grail achiever who returns to tell of it.'),
 ('ENT_ART_FISHER_KING','guardian_of','ENT_ART_GRAIL','high','Keeper of the Grail at the Grail castle.'),
 ('ENT_ART_GALAHAD','guardian_of','ENT_ART_SIEGE_PERILOUS','high','Alone may occupy the seat reserved for him.'),
 ('ENT_ART_MERLIN','transmits','ENT_ART_ROUND_TABLE_OBJECT','high','Merlin makes the Round Table.'),
 ('ENT_ART_MERLIN','transmits','ENT_ART_ROUND_TABLE','high','Merlin establishes the fellowship.'),
 ('ENT_ART_ARTHUR','rules','ENT_ART_CAMELOT','high','Reigns from Camelot.'),
 ('ENT_ART_ARTHUR','dwells_in','ENT_ART_AVALON','high','Borne to Avalon to be healed at his death.'),
 ('ENT_ART_ROUND_TABLE','dwells_in','ENT_ART_CAMELOT','high','The fellowship is seated at Camelot.'),
 ('ENT_ART_SIEGE_PERILOUS','member_of','ENT_ART_ROUND_TABLE_OBJECT','medium','The perilous seat belonging to the Round Table.'),
 ('ENT_ART_LADY_OF_THE_LAKE','guardian_of','ENT_ART_EXCALIBUR','high','Gives and reclaims Excalibur.'),
 ('ENT_ART_ARTHUR','guardian_of','ENT_ART_EXCALIBUR','high','Bears Excalibur as the sword of sovereignty.'),
 ('ENT_ART_LADY_OF_THE_LAKE','transmits','ENT_ART_LANCELOT','medium','Fosters Lancelot (Lancelot du Lac).'),
 ('ENT_ART_MERLIN','child_of','ENT_CHR_DEVIL','medium','In Robert de Boron, Merlin is fathered by a devil then baptized — a theological aetiology of his powers.'),
 ('ENT_ART_MERLIN','presides_over','ENT_MAGIC','high','Supreme magician of the cycle.'),
 ('ENT_ART_MERLIN','presides_over','ENT_PROPHECY','high','The great prophet (Prophetiae Merlini).'),
 ('ENT_ART_MORGAN_LE_FAY','presides_over','ENT_MAGIC','high','Chief sorceress of the cycle.'),
 ('ENT_ART_LADY_OF_THE_LAKE','presides_over','ENT_MAGIC','high','Otherworldly enchantress.'),
 ('ENT_ART_ARTHUR','presides_over','ENT_WAR','high','The great war-leader of the Britons.'),
 ('ENT_ART_LANCELOT','presides_over','ENT_WAR','medium','Foremost knight in arms.'),
 ('ENT_ART_GRAIL','presides_over','ENT_HEALING','high','Heals and sustains; its quest restores the wasteland.'),
 ('ENT_ART_GRAIL','presides_over','ENT_REVELATION','high','Vehicle of divine grace and revelation.'),
 ('ENT_ART_GRAIL','presides_over','ENT_FERTILITY','medium','Its quest restores the wasteland to fertility.'),
 ('ENT_ART_FISHER_KING','presides_over','ENT_FERTILITY','medium','His wound is bound to the barrenness of the wasteland.'),
 ('ENT_ART_AVALON','presides_over','ENT_HEALING','high','The isle of healing.'),
 ('ENT_ART_TRISTAN','presides_over','ENT_LOVE','medium','Embodies the great tragic love.'),
 ('ENT_ART_ISOLDE','presides_over','ENT_LOVE','medium','Embodies the great tragic love.');

\echo '--- REJECTED edges (bad id/type/source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
