-- build_yazidi.sql  (GENERATED by gen_roster.py yazidi) — v1.80.0
-- 15 entities, 20 edges, 1 new periods, 3 new sources. Idempotent + self-validating.
BEGIN;

INSERT INTO periods (period_id, period_name, start_year, end_year) VALUES
 ('PER_YAZIDI','Yazidi tradition (formative reform to present)',1100,2025)
ON CONFLICT (period_id) DO NOTHING;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_SPAT_YEZIDIS','secondary scholarship','Eszter Spat, The Yezidis (London: Saqi, 2005)','Yazidi religion, mythology, the Heptad, Tawusi Melek, Lalish, oral qewls'),
 ('SRC_KREYENBROEK_YEZIDISM','secondary scholarship','Philip G. Kreyenbroek, Yezidism: Its Background, Observances and Textual Tradition (Lewiston: Edwin Mellen Press, 1995)','Yazidi theology, the Seven Mysteries, Sheikh Adi, cosmology, hymn texts'),
 ('SRC_OMARKHALI_YEZIDI_TEXTUAL','secondary scholarship','Khanna Omarkhali, The Yezidi Religious Textual Tradition (Wiesbaden: Harrassowitz, 2017)','Yazidi sacred oral hymns (qewls and beyts), avatars of the Heptad, sheikhly and pir lineages')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,trad text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_YAZ_HEPTAD','The Heptad (Haft Sirr / Seven Mysteries)','Angelic collective','Angelic Collective','Yazidi','divine governance; emanation; cosmic administration','B','Attested in Spat and Kreyenbroek as the Seven Angels/Mysteries to whom Xwede entrusted the world; hub of Yazidi cosmology.'),
 ('ENT_YAZ_XWEDE','Xwede','Supreme deity','Supreme deity','Yazidi','creation; transcendence; the remote One God','B','The single remote creator God in Yazidi belief who delegates the cosmos to the Heptad; attested across Kreyenbroek and Spat.'),
 ('ENT_YAZ_TAWUSI_MELEK','Tawusi Melek (Melek Taus, the Peacock Angel)','Angel','Angelic Being','Yazidi','chief of the Heptad; divine vicegerent; mediator','B','Chief of the Seven; venerated as God''s foremost emanation and steward of the world. Yazidis REJECT the external misidentification with Shaytan/the devil; modeled here only as the Peacock Angel of the qewls (Spat, Kreyenbroek).'),
 ('ENT_YAZ_SHEIKH_ADI','Sheikh Adi ibn Musafir','Sufi saint','Sufi saint (wali)','Yazidi','reformer; manifestation of the divine; sheikhly lineage','B','Historical 12th-c. Sufi ascetic of Hakkari (d. c.1162) whose tomb is at Lalish; revered in Yazidism as a supreme manifestation and reorganizer of the faith (Kreyenbroek).'),
 ('ENT_YAZ_SULTAN_EZID','Sultan Ezid (Sultan Ezi)','Divine manifestation','Holy Figure','Yazidi','manifestation of the divine; eponymous holy figure','C','Revered manifestation/holy figure central to Yazidi devotion, often linked in name-tradition to the community''s self-designation; attested in the qewls (Spat, Kreyenbroek).'),
 ('ENT_YAZ_SHEIKH_HASAN','Sheikh Hasan (Sheikh Sin)','Angel','Holy Figure','Yazidi','member of the Heptad; sheikhly lineage; scribe/wisdom associations','C','One of the Seven Mysteries and an earthly avatar; eponym of a principal sheikhly lineage (Kreyenbroek, Omarkhali).'),
 ('ENT_YAZ_SHEIKH_SHAMS','Sheikh Shams (Shams al-Din)','Solar deity','Solar Deity','Yazidi','the sun; light; member of the Heptad','C','Member of the Seven associated with the sun and light; receives dawn veneration in Yazidi practice; eponym of a sheikhly lineage (Spat, Kreyenbroek).'),
 ('ENT_YAZ_FAKHR_AL_DIN','Sheikh Fakhr al-Din','Angel','Holy Figure','Yazidi','member of the Heptad; cosmogonic/creative role','C','One of the Seven Mysteries, with a creative/cosmogonic role in the qewls; eponym of a sheikhly lineage. Distinct from the Sufi poet Fakhr al-Din Iraqi (homonym) (Kreyenbroek, Omarkhali).'),
 ('ENT_YAZ_SAJADIN','Sheikh Sajadin (Sejadin)','Angel','Holy Figure','Yazidi','member of the Heptad; sheikhly lineage','C','One of the Seven Mysteries / Sons of Sheikh Adi''s companions in the qewls; eponym of a sheikhly lineage (Kreyenbroek, Omarkhali).'),
 ('ENT_YAZ_NASIRDIN','Sheikh Nasirdin (Nasr al-Din)','Angel','Holy Figure','Yazidi','member of the Heptad; sheikhly lineage','C','One of the Seven Mysteries and eponym of a sheikhly lineage in the Yazidi oral tradition (Kreyenbroek, Omarkhali).'),
 ('ENT_YAZ_SHEIKH_OBEKR','Sheikh Obekr (Abu Bakr)','Angel','Holy Figure','Yazidi','member of the Heptad; sheikhly lineage','C','Counted among the Seven Mysteries in several enumerations; eponym of a Yazidi sheikhly lineage (Kreyenbroek). Note: distinct from the Islamic caliph despite the shared name (homonym).'),
 ('ENT_YAZ_LALISH','Lalish','Sacred Place','Sacred Place','Yazidi','holy valley; pilgrimage center; cosmic axis','B','The sacred valley north of Mosul housing Sheikh Adi''s tomb; supreme Yazidi pilgrimage site and a sanctified cosmic realm in the qewls (Spat, Kreyenbroek).'),
 ('ENT_YAZ_PIR_LIBNAN','Pir Libnan (Pir Reshe / building master)','Holy figure','Holy Figure','Yazidi','sacred craft; building of Lalish; pir lineage','C','Holy figure of the pir caste associated in the qewls with the sacred construction at Lalish; eponym of a pir lineage (Kreyenbroek).'),
 ('ENT_YAZ_MEHMA_RESHAN','Pir Mehma Reshan','Holy figure','Holy Figure','Yazidi','weather/storm associations; pir lineage','C','Revered pir-lineage holy figure of the Yazidi oral tradition, with storm/weather associations in some qewls (Omarkhali, Kreyenbroek).'),
 ('ENT_YAZ_KHATUNA_FAKHRA','Khatuna Fakhra','Holy figure','Holy Figure','Yazidi','midwifery; protection of mothers and children; revered woman','C','Venerated female holy figure invoked as a patroness of childbirth and protection of infants in Yazidi devotion (Spat).');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'devotional',conf,'candidate_verified_name','Roster build via gen_roster.py (see CHANGELOG/git for release)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,etype text,note text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_YAZ_HEPTAD','SRC_KREYENBROEK_YEZIDISM','scholarly attestation','attestation'),
 ('ENT_YAZ_XWEDE','SRC_KREYENBROEK_YEZIDISM','scholarly attestation','attestation'),
 ('ENT_YAZ_TAWUSI_MELEK','SRC_SPAT_YEZIDIS','scholarly attestation','attestation'),
 ('ENT_YAZ_SHEIKH_ADI','SRC_KREYENBROEK_YEZIDISM','scholarly attestation','attestation'),
 ('ENT_YAZ_SULTAN_EZID','SRC_SPAT_YEZIDIS','scholarly attestation','attestation'),
 ('ENT_YAZ_SHEIKH_HASAN','SRC_OMARKHALI_YEZIDI_TEXTUAL','scholarly attestation','attestation'),
 ('ENT_YAZ_SHEIKH_SHAMS','SRC_SPAT_YEZIDIS','scholarly attestation','attestation'),
 ('ENT_YAZ_FAKHR_AL_DIN','SRC_OMARKHALI_YEZIDI_TEXTUAL','scholarly attestation','attestation'),
 ('ENT_YAZ_SAJADIN','SRC_OMARKHALI_YEZIDI_TEXTUAL','scholarly attestation','attestation'),
 ('ENT_YAZ_NASIRDIN','SRC_OMARKHALI_YEZIDI_TEXTUAL','scholarly attestation','attestation'),
 ('ENT_YAZ_SHEIKH_OBEKR','SRC_KREYENBROEK_YEZIDISM','scholarly attestation','attestation'),
 ('ENT_YAZ_LALISH','SRC_SPAT_YEZIDIS','scholarly attestation','attestation'),
 ('ENT_YAZ_PIR_LIBNAN','SRC_KREYENBROEK_YEZIDISM','scholarly attestation','attestation'),
 ('ENT_YAZ_MEHMA_RESHAN','SRC_OMARKHALI_YEZIDI_TEXTUAL','scholarly attestation','attestation'),
 ('ENT_YAZ_KHATUNA_FAKHRA','SRC_SPAT_YEZIDIS','scholarly attestation','attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_YAZ_HEPTAD','PER_YAZIDI','Attested in Spat and Kreyenbroek as the Seven Angels/Mysteries to whom Xwede entrusted the world; hub of Yazidi cosmology.'),
 ('ENT_YAZ_XWEDE','PER_YAZIDI','The single remote creator God in Yazidi belief who delegates the cosmos to the Heptad; attested across Kreyenbroek and Spat.'),
 ('ENT_YAZ_TAWUSI_MELEK','PER_YAZIDI','Chief of the Seven; venerated as God''s foremost emanation and steward of the world. Yazidis REJECT the external misidentification with Shaytan/the devil; modeled here only as the Peacock Angel of the qewls (Spat, Kreyenbroek).'),
 ('ENT_YAZ_SHEIKH_ADI','PER_YAZIDI','Historical 12th-c. Sufi ascetic of Hakkari (d. c.1162) whose tomb is at Lalish; revered in Yazidism as a supreme manifestation and reorganizer of the faith (Kreyenbroek).'),
 ('ENT_YAZ_SULTAN_EZID','PER_YAZIDI','Revered manifestation/holy figure central to Yazidi devotion, often linked in name-tradition to the community''s self-designation; attested in the qewls (Spat, Kreyenbroek).'),
 ('ENT_YAZ_SHEIKH_HASAN','PER_YAZIDI','One of the Seven Mysteries and an earthly avatar; eponym of a principal sheikhly lineage (Kreyenbroek, Omarkhali).'),
 ('ENT_YAZ_SHEIKH_SHAMS','PER_YAZIDI','Member of the Seven associated with the sun and light; receives dawn veneration in Yazidi practice; eponym of a sheikhly lineage (Spat, Kreyenbroek).'),
 ('ENT_YAZ_FAKHR_AL_DIN','PER_YAZIDI','One of the Seven Mysteries, with a creative/cosmogonic role in the qewls; eponym of a sheikhly lineage. Distinct from the Sufi poet Fakhr al-Din Iraqi (homonym) (Kreyenbroek, Omarkhali).'),
 ('ENT_YAZ_SAJADIN','PER_YAZIDI','One of the Seven Mysteries / Sons of Sheikh Adi''s companions in the qewls; eponym of a sheikhly lineage (Kreyenbroek, Omarkhali).'),
 ('ENT_YAZ_NASIRDIN','PER_YAZIDI','One of the Seven Mysteries and eponym of a sheikhly lineage in the Yazidi oral tradition (Kreyenbroek, Omarkhali).'),
 ('ENT_YAZ_SHEIKH_OBEKR','PER_YAZIDI','Counted among the Seven Mysteries in several enumerations; eponym of a Yazidi sheikhly lineage (Kreyenbroek). Note: distinct from the Islamic caliph despite the shared name (homonym).'),
 ('ENT_YAZ_LALISH','PER_YAZIDI','The sacred valley north of Mosul housing Sheikh Adi''s tomb; supreme Yazidi pilgrimage site and a sanctified cosmic realm in the qewls (Spat, Kreyenbroek).'),
 ('ENT_YAZ_PIR_LIBNAN','PER_YAZIDI','Holy figure of the pir caste associated in the qewls with the sacred construction at Lalish; eponym of a pir lineage (Kreyenbroek).'),
 ('ENT_YAZ_MEHMA_RESHAN','PER_YAZIDI','Revered pir-lineage holy figure of the Yazidi oral tradition, with storm/weather associations in some qewls (Omarkhali, Kreyenbroek).'),
 ('ENT_YAZ_KHATUNA_FAKHRA','PER_YAZIDI','Venerated female holy figure invoked as a patroness of childbirth and protection of infants in Yazidi devotion (Spat).');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_YAZ_TAWUSI_MELEK','member_of','ENT_YAZ_HEPTAD','high','Tawusi Melek is the chief of the Seven Mysteries/Heptad (Spat, Kreyenbroek).'),
 ('ENT_YAZ_SHEIKH_ADI','member_of','ENT_YAZ_HEPTAD','medium','Sheikh Adi is counted among the manifestations of the Heptad in the qewls (Kreyenbroek).'),
 ('ENT_YAZ_SHEIKH_HASAN','member_of','ENT_YAZ_HEPTAD','high','Sheikh Hasan (Sheikh Sin) is one of the Seven Mysteries (Kreyenbroek, Omarkhali).'),
 ('ENT_YAZ_SHEIKH_SHAMS','member_of','ENT_YAZ_HEPTAD','high','Sheikh Shams is one of the Seven, associated with the sun (Spat, Kreyenbroek).'),
 ('ENT_YAZ_FAKHR_AL_DIN','member_of','ENT_YAZ_HEPTAD','high','Sheikh Fakhr al-Din is one of the Seven Mysteries (Kreyenbroek, Omarkhali).'),
 ('ENT_YAZ_SAJADIN','member_of','ENT_YAZ_HEPTAD','medium','Sheikh Sajadin is enumerated among the Seven Mysteries in the qewls (Kreyenbroek, Omarkhali).'),
 ('ENT_YAZ_NASIRDIN','member_of','ENT_YAZ_HEPTAD','medium','Sheikh Nasirdin is enumerated among the Seven Mysteries in the qewls (Kreyenbroek, Omarkhali).'),
 ('ENT_YAZ_SHEIKH_OBEKR','member_of','ENT_YAZ_HEPTAD','medium','Sheikh Obekr appears among the Seven in several enumerations of the Heptad (Kreyenbroek).'),
 ('ENT_YAZ_HEPTAD','emanates_from','ENT_YAZ_XWEDE','high','Xwede, the remote creator, brings forth and delegates the world to the Heptad (Kreyenbroek).'),
 ('ENT_YAZ_TAWUSI_MELEK','emanates_from','ENT_YAZ_XWEDE','high','Tawusi Melek is the foremost emanation/vicegerent of Xwede (Spat, Kreyenbroek).'),
 ('ENT_YAZ_HEPTAD','rules','ENT_YAZ_LALISH','medium','The Heptad and especially Sheikh Adi govern the sanctified realm of Lalish in Yazidi cosmology (Spat).'),
 ('ENT_YAZ_SHEIKH_ADI','dwells_in','ENT_YAZ_LALISH','high','Sheikh Adi''s tomb is at Lalish, the supreme pilgrimage center (Spat, Kreyenbroek).'),
 ('ENT_YAZ_PIR_LIBNAN','associated_with','ENT_YAZ_LALISH','medium','Pir Libnan is associated in the qewls with the sacred building of Lalish (Kreyenbroek).'),
 ('ENT_YAZ_SULTAN_EZID','member_of','ENT_YAZ_HEPTAD','medium','Sultan Ezid is a divine manifestation closely woven into the Heptad theology of the qewls (Spat, Kreyenbroek).'),
 ('ENT_YAZ_MEHMA_RESHAN','associated_with','ENT_YAZ_HEPTAD','low','Pir Mehma Reshan figures among the holy pir lineages tied to the Heptad''s earthly manifestations (Omarkhali, Kreyenbroek).'),
 ('ENT_YAZ_KHATUNA_FAKHRA','associated_with','ENT_YAZ_SHEIKH_ADI','low','Khatuna Fakhra is a revered woman of the Adani holy circle in Yazidi devotion (Spat).'),
 ('ENT_YAZ_SHEIKH_ADI','reception_of','ENT_SUF_JILANI','medium','Sheikh Adi ibn Musafir was a historical Sufi ascetic of the Qadiri-adjacent Baghdad milieu of Abd al-Qadir al-Jilani; Yazidism received him as a supreme manifestation (Kreyenbroek).'),
 ('ENT_YAZ_TAWUSI_MELEK','aligned_with','ENT_SUF_HALLAJ','low','The Yazidi exaltation of the foremost angel echoes the Sufi (Hallajian) defense of Iblis''s refusal to bow as supreme love/obedience to God alone; a theological parallel, not an identification (Spat).'),
 ('ENT_YAZ_TAWUSI_MELEK','opposes','ENT_ISL_SHAYTAN','medium','Yazidis explicitly reject the external conflation of Tawusi Melek with Shaytan/the devil; modeled here to record that the misidentification is repudiated, not affirmed (Spat, Kreyenbroek).'),
 ('ENT_YAZ_SHEIKH_SHAMS','aligned_with','ENT_AST_SUN_SPIRIT','low','Sheikh Shams embodies solar veneration in Yazidism, functionally parallel to the sun-spirit of astral/planetary traditions (Kreyenbroek); cognate alignment, not identity.');

\echo '--- REJECTED edges (bad id/type, or subject lacks a source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
