-- build_p6_realms_greek.sql  (GENERATED by gen_roster.py p6_realms_greek) — v1.80.0
-- 7 entities, 15 edges, 0 new periods, 3 new sources. Idempotent + self-validating.
BEGIN;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_HOMER_ILIAD_ODYSSEY','primary text','Homer, Iliad and Odyssey (c. 750-675 BCE); Odyssey 11 (Nekyia)','reuse'),
 ('SRC_HESIOD_WORKS_DAYS','primary text','Hesiod, Works and Days (c. 700 BCE), trans. Evelyn-White','reuse'),
 ('SRC_VIRGIL_AENEID','primary text','Virgil, Aeneid (19 BCE); Book 6 (Aeneas in the underworld)','reuse')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,trad text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_GRR_UNDERWORLD','The Greek Underworld (House of Hades)','Cosmological realm','Cosmological realm','Greek','underworld; realm of the dead','B','Hub entity for the structured Greek realm of the dead, the domain of Hades and Persephone, divided into regions for the dead by their merit. Composite of Homer Odyssey 11, Hesiod, and Virgil Aeneid 6; the systematized topography (rivers, fields, judges) is fullest in Virgil.'),
 ('ENT_GRR_ELYSIUM','Elysium (Elysian Fields)','Cosmological realm','Cosmological realm','Greek','blessed afterlife for heroes and the virtuous','B','The Elysian Fields, paradisal abode of heroes and the righteous dead. First named at Homer Odyssey 4.563-569 (Elysian plain, where Menelaus is destined to go); elaborated as a region of the underworld in Virgil Aeneid 6.637-678.'),
 ('ENT_GRR_ASPHODEL','The Asphodel Meadows','Cosmological realm','Cosmological realm','Greek','afterlife abode of ordinary shades','B','The Asphodel Meadow (leimon asphodelos), where the shades of the unremarkable dead wander, named at Homer Odyssey 11.539 and 24.13. The intermediate region for those neither heroic nor wicked.'),
 ('ENT_GRR_ISLES_BLEST','The Isles of the Blest (Fortunate Isles)','Cosmological realm','Cosmological realm','Greek','blessed afterlife at the edge of the world','B','The Islands of the Blessed (makaron nesoi), at the ends of the earth by deep-swirling Ocean, where Hesiod''s fourth (heroic) race dwells in untroubled bliss; Hesiod, Works and Days 167-173. Often conflated with or adjacent to Elysium.'),
 ('ENT_GRR_MOURNING_FIELDS','The Mourning Fields (Lugentes Campi)','Cosmological realm','Cosmological realm','Greek','afterlife region for those who died of love','C','The Fields of Mourning (Lugentes Campi), region of the underworld for those consumed and killed by unhappy love (e.g. Dido, Phaedra), attested at Virgil, Aeneid 6.440-444. A Roman-poetic systematization of the Greek underworld.'),
 ('ENT_GRR_PLAIN_LETHE','The Plain of Lethe','Cosmological realm','Cosmological realm','Greek','place of forgetting before rebirth','C','The plain through which the river Lethe flows, where shades destined for reincarnation drink the water of forgetfulness; Virgil, Aeneid 6.703-715 (Anchises shows Aeneas the souls by Lethe). Plato Republic 10.621 places the Plain of Lethe (pediton tes Lethes) in the eschatology of Er.'),
 ('ENT_GRR_FIELDS_PUNISHMENT','The Fields of Punishment','Cosmological realm','Cosmological realm','Greek','place of torment for the wicked dead','B','The region where the wicked are punished, bounded by the flaming river Phlegethon and overseen by Rhadamanthus; the great prison-pit of Tartarus lies below it. Virgil, Aeneid 6.548-627 (Tartarus and the punishments). Distinct from but continuous with primordial Tartarus.');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'devotional',conf,'candidate_verified_name','Roster build via gen_roster.py (see CHANGELOG/git for release)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,etype text,note text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_GRR_UNDERWORLD','SRC_VIRGIL_AENEID','primary text attestation','attestation'),
 ('ENT_GRR_ELYSIUM','SRC_VIRGIL_AENEID','primary text attestation','attestation'),
 ('ENT_GRR_ASPHODEL','SRC_HOMER_ILIAD_ODYSSEY','primary text attestation','attestation'),
 ('ENT_GRR_ISLES_BLEST','SRC_HESIOD_WORKS_DAYS','primary text attestation','attestation'),
 ('ENT_GRR_MOURNING_FIELDS','SRC_VIRGIL_AENEID','primary text attestation','attestation'),
 ('ENT_GRR_PLAIN_LETHE','SRC_VIRGIL_AENEID','primary text attestation','attestation'),
 ('ENT_GRR_FIELDS_PUNISHMENT','SRC_VIRGIL_AENEID','primary text attestation','attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_GRR_UNDERWORLD','PER_GRK_CLASSICAL','Hub entity for the structured Greek realm of the dead, the domain of Hades and Persephone, divided into regions for the dead by their merit. Composite of Homer Odyssey 11, Hesiod, and Virgil Aeneid 6; the systematized topography (rivers, fields, judges) is fullest in Virgil.'),
 ('ENT_GRR_ELYSIUM','PER_GRK_CLASSICAL','The Elysian Fields, paradisal abode of heroes and the righteous dead. First named at Homer Odyssey 4.563-569 (Elysian plain, where Menelaus is destined to go); elaborated as a region of the underworld in Virgil Aeneid 6.637-678.'),
 ('ENT_GRR_ASPHODEL','PER_GRK_ARCHAIC','The Asphodel Meadow (leimon asphodelos), where the shades of the unremarkable dead wander, named at Homer Odyssey 11.539 and 24.13. The intermediate region for those neither heroic nor wicked.'),
 ('ENT_GRR_ISLES_BLEST','PER_GRK_ARCHAIC','The Islands of the Blessed (makaron nesoi), at the ends of the earth by deep-swirling Ocean, where Hesiod''s fourth (heroic) race dwells in untroubled bliss; Hesiod, Works and Days 167-173. Often conflated with or adjacent to Elysium.'),
 ('ENT_GRR_MOURNING_FIELDS','PER_GRK_ROMAN','The Fields of Mourning (Lugentes Campi), region of the underworld for those consumed and killed by unhappy love (e.g. Dido, Phaedra), attested at Virgil, Aeneid 6.440-444. A Roman-poetic systematization of the Greek underworld.'),
 ('ENT_GRR_PLAIN_LETHE','PER_GRK_ROMAN','The plain through which the river Lethe flows, where shades destined for reincarnation drink the water of forgetfulness; Virgil, Aeneid 6.703-715 (Anchises shows Aeneas the souls by Lethe). Plato Republic 10.621 places the Plain of Lethe (pediton tes Lethes) in the eschatology of Er.'),
 ('ENT_GRR_FIELDS_PUNISHMENT','PER_GRK_ROMAN','The region where the wicked are punished, bounded by the flaming river Phlegethon and overseen by Rhadamanthus; the great prison-pit of Tartarus lies below it. Virgil, Aeneid 6.548-627 (Tartarus and the punishments). Distinct from but continuous with primordial Tartarus.');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_HADES','rules','ENT_GRR_UNDERWORLD','high','Hades is the ruler of the underworld, the House of Hades that bears his name (Homer, passim).'),
 ('ENT_PERSEPHONE','rules','ENT_GRR_UNDERWORLD','high','Persephone reigns as queen of the underworld alongside Hades (Homer Odyssey 10-11; Homeric Hymn to Demeter).'),
 ('ENT_GRR_UNDERWORLD','ruled_by','ENT_HADES','high','The underworld is ruled by Hades, its eponymous lord.'),
 ('ENT_GRR_ELYSIUM','dwells_in','ENT_GRR_UNDERWORLD','medium','In the developed topography (Virgil Aeneid 6) Elysium is a region within the underworld.'),
 ('ENT_GRR_ASPHODEL','dwells_in','ENT_GRR_UNDERWORLD','high','The Asphodel Meadow is part of the House of Hades, where ordinary shades wander (Odyssey 11.539).'),
 ('ENT_GRR_MOURNING_FIELDS','dwells_in','ENT_GRR_UNDERWORLD','medium','The Lugentes Campi are a named region of the underworld (Aeneid 6.441).'),
 ('ENT_GRR_PLAIN_LETHE','dwells_in','ENT_GRR_UNDERWORLD','medium','The Plain of Lethe lies within the underworld, where souls prepare for rebirth (Aeneid 6.703ff).'),
 ('ENT_GRR_FIELDS_PUNISHMENT','dwells_in','ENT_GRR_UNDERWORLD','high','The Fields of Punishment are the penal region of the underworld (Aeneid 6.548ff).'),
 ('ENT_GRR_FIELDS_PUNISHMENT','dwells_in','ENT_TARTARUS','medium','The Fields of Punishment lie above and continuous with the abyss of Tartarus, where the deepest torments occur (Aeneid 6; Hesiod Theogony 717ff).'),
 ('ENT_GRR_FIELDS_PUNISHMENT','associated_with','ENT_PHLEGETHON','high','The Fields of Punishment are encircled by the flaming river Phlegethon (Aeneid 6.550-551).'),
 ('ENT_GRR_PLAIN_LETHE','associated_with','ENT_LETHE','high','The Plain of Lethe takes its name from and is watered by the river Lethe of forgetfulness (Aeneid 6.705, 714).'),
 ('ENT_GRR_UNDERWORLD','associated_with','ENT_EREBUS','medium','Erebus, primordial darkness, is the gloom of the underworld through which the dead pass (Hesiod Theogony 123; Homer).'),
 ('ENT_GRR_ISLES_BLEST','presided_over_by','ENT_CRONUS','medium','In Hesiod''s account (and Pindar Ol. 2), Cronus rules over the Isles of the Blest where the heroic dead dwell apart from Hades'' realm.'),
 ('ENT_GRR_FIELDS_PUNISHMENT','presided_over_by','ENT_RHADAMANTHUS','medium','Rhadamanthus presides over the punishment of the wicked in the penal region (Aeneid 6.566-569).'),
 ('ENT_GRR_ISLES_BLEST','associated_with','ENT_GRR_ELYSIUM','medium','The Isles of the Blest and Elysium are the two principal Greek paradise-abodes, frequently conflated in later sources as the destination of the blessed.');

\echo '--- REJECTED edges (bad id/type, or subject lacks a source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
