-- build_p6_realms_christian.sql  (GENERATED by gen_roster.py p6_realms_christian) — v1.80.0
-- 13 entities, 19 edges, 0 new periods, 2 new sources. Idempotent + self-validating.
BEGIN;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_DANTE_COMMEDIA','primary text','Dante Alighieri, La Divina Commedia (Inferno, Purgatorio, Paradiso, c. 1308–1321)','The structured Christian afterlife cosmos in Dante''s poem: the nine descending Circles of Hell, the seven Terraces of Mount Purgatory with ante-Purgatory and the Earthly Paradise at its summit, the nine revolving Celestial Spheres, and the Empyrean culminating in the Beatific Vision; principal medieval-poetic source for the literary topology of the Christian otherworld.'),
 ('SRC_CATECHISM_CC','reference work','Catechism of the Catholic Church (1992, rev. 1997)','Authoritative compendium of Catholic doctrine; articles on the Last Things (eschatology) defining Heaven and the Beatific Vision, Purgatory and final purification, Hell, and traditional teaching on the Limbo of the Fathers (Limbus Patrum) and the limbo of unbaptized infants.')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,trad text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_CHRR_COSMOS','The Christian Cosmos','Cosmological structure','Cosmological structure','Christian','Hub node for the structured Christian afterlife and eschatological cosmos: the threefold realm of Hell, Purgatory, and Heaven, with Limbo and intermediate states, as systematized in patristic theology, medieval scholasticism, the Catechism, and given its canonical poetic form in Dante''s Divina Commedia.','B','Structural hub entity grouping the Christian otherworld realms; attested as a coherent tripartite-plus cosmos in scholastic theology and Dante.'),
 ('ENT_CHRR_PURGATORY','Purgatory','Cosmological realm','Cosmological realm','Christian','The intermediate state/place of purification for the souls of the saved who die in grace but require cleansing of temporal punishment before entering Heaven; defined doctrinally by the Catechism and councils (Lyon, Florence, Trent) and depicted by Dante as Mount Purgatory.','B','Catholic doctrine of final purification (CCC 1030–1032); poetically the seven-terraced mountain of Purgatorio.'),
 ('ENT_CHRR_LIMBUS_PATRUM','Limbo of the Fathers (Limbus Patrum)','Cosmological realm','Cosmological realm','Christian','The abode where the righteous of the Old Covenant awaited the coming of Christ, harrowed and liberated at the Descent into Hell; identified by Dante with the first circle (Limbo) and associated with the Bosom of Abraham.','B','Traditional Catholic teaching on the Harrowing of Hell; emptied by Christ at the Resurrection.'),
 ('ENT_CHRR_LIMBUS_INFANTUM','Limbo of the Infants (Limbus Infantium)','Cosmological realm','Cosmological realm','Christian','The hypothesized state/place for the souls of unbaptized infants and others dying without personal sin but without baptism, free of suffering yet excluded from the Beatific Vision; a theological theory, never defined dogma.','C','Medieval-scholastic theory (Aquinas); the Catechism leaves the fate of unbaptized infants to God''s mercy. Attested as theological tradition, not dogma.'),
 ('ENT_CHRR_EMPYREAN','The Empyrean','Cosmological realm','Cosmological realm','Christian','The highest heaven, the dwelling of God, the angels, and the blessed beyond the nine moving celestial spheres; in Dante the motionless heaven of pure light where the Celestial Rose of the saints and the Beatific Vision are beheld.','B','Medieval cosmological term (caelum empyreum); the tenth, immobile heaven in Dante''s Paradiso.'),
 ('ENT_CHRR_BEATIFIC_VISION','The Beatific Vision','Eschatological category','Eschatological category','Christian','The direct, immediate, face-to-face vision of God enjoyed by the blessed in Heaven, the supreme end and beatitude of the saved; defined doctrinally (Benedictus Deus, 1336; CCC 1028) and the culminating experience of Dante''s Paradiso.','B','Catholic doctrine of the final blessedness; distinct from the Solomonic-magic ''operation'' homonym (ENT_SOL_BEATIFIC_VISION_OP, confirmed present in DB).'),
 ('ENT_CHRR_BOSOM_ABRAHAM','The Bosom of Abraham','Cosmological realm','Cosmological realm','Christian','The place of comfort and rest for the righteous dead before the redemption, named in the parable of the rich man and Lazarus (Luke 16:22); identified in Christian tradition with the Limbo of the Fathers prior to the Harrowing of Hell.','B','Lukan parable; patristic/medieval identification with Limbus Patrum.'),
 ('ENT_CHRR_NEW_JERUSALEM','The New Jerusalem','Cosmological realm','Cosmological realm','Christian','The heavenly city descending from God in the eschaton, the consummated dwelling of God with the redeemed (Revelation 21–22); Augustine''s Civitas Dei, the perfected community of the blessed.','B','Apocalyptic vision (Rev 21); developed as the City of God by Augustine.'),
 ('ENT_CHRR_HEAVEN','Heaven','Cosmological realm','Cosmological realm','Christian','The realm of God''s eternal presence and the final blessedness of the saved, the state of perfect communion with the Holy Trinity, the angels, and the saints; the destination of the elect after particular and final judgment.','B','Core Christian eschatology (CCC 1023–1029). No prior Christian-tradition Heaven realm existed in the DB.'),
 ('ENT_CHRR_HELL','Hell (Christian)','Cosmological realm','Cosmological realm','Christian','The state and place of definitive self-exclusion from communion with God, of eternal punishment for the damned who die in mortal sin; the abode of the Devil and his demons, depicted by Dante as the nine descending circles of the Inferno.','B','Christian eschatology (CCC 1033–1037). Distinct from Jewish Gehenna/Sheol (ENT_JM_GEHENNA, ENT_ISR_SHEOL), to which it is the conceptual heir.'),
 ('ENT_CHRR_NINE_CIRCLES','The Nine Circles of Hell','Cosmological structure','Cosmological structure','Christian','Dante''s descending structure of the Inferno: Limbo, Lust, Gluttony, Greed, Wrath, Heresy, Violence, Fraud, and Treachery, ordered by gravity of sin and culminating in the frozen pit where Satan is fixed at the earth''s center.','B','Literary-structural node from Dante''s Inferno; the canonical poetic topology of Christian Hell.'),
 ('ENT_CHRR_SEVEN_TERRACES','The Seven Terraces of Mount Purgatory','Cosmological structure','Cosmological structure','Christian','Dante''s ascending structure of Purgatorio: the seven terraces purging the capital vices (Pride, Envy, Wrath, Sloth, Avarice, Gluttony, Lust), preceded by ante-Purgatory and surmounted by the Earthly Paradise at the mountain''s summit.','B','Literary-structural node from Dante''s Purgatorio; the seven terraces correspond to the seven deadly sins.'),
 ('ENT_CHRR_CELESTIAL_SPHERES','The Celestial Spheres','Cosmological structure','Cosmological structure','Christian','Dante''s ascending structure of Paradiso: the nine revolving heavens (Moon, Mercury, Venus, Sun, Mars, Jupiter, Saturn, Fixed Stars, Primum Mobile), the moving spheres of Ptolemaic-Christian cosmology through which souls ascend toward the immobile Empyrean.','B','Literary-structural node from Dante''s Paradiso, fusing Ptolemaic astronomy with Christian theology.');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'devotional',conf,'candidate_verified_name','Roster build via gen_roster.py (see CHANGELOG/git for release)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,etype text,note text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_CHRR_COSMOS','SRC_DANTE_COMMEDIA','primary text attestation','attestation'),
 ('ENT_CHRR_PURGATORY','SRC_CATECHISM_CC','scholarly attestation','attestation'),
 ('ENT_CHRR_LIMBUS_PATRUM','SRC_CATECHISM_CC','scholarly attestation','attestation'),
 ('ENT_CHRR_LIMBUS_INFANTUM','SRC_CATECHISM_CC','scholarly attestation','attestation'),
 ('ENT_CHRR_EMPYREAN','SRC_DANTE_COMMEDIA','primary text attestation','attestation'),
 ('ENT_CHRR_BEATIFIC_VISION','SRC_CATECHISM_CC','scholarly attestation','attestation'),
 ('ENT_CHRR_BOSOM_ABRAHAM','SRC_CATECHISM_CC','scholarly attestation','attestation'),
 ('ENT_CHRR_NEW_JERUSALEM','SRC_AUGUSTINE_CITY_OF_GOD','scholarly attestation','attestation'),
 ('ENT_CHRR_HEAVEN','SRC_CATECHISM_CC','scholarly attestation','attestation'),
 ('ENT_CHRR_HELL','SRC_CATECHISM_CC','scholarly attestation','attestation'),
 ('ENT_CHRR_NINE_CIRCLES','SRC_DANTE_COMMEDIA','primary text attestation','attestation'),
 ('ENT_CHRR_SEVEN_TERRACES','SRC_DANTE_COMMEDIA','primary text attestation','attestation'),
 ('ENT_CHRR_CELESTIAL_SPHERES','SRC_DANTE_COMMEDIA','primary text attestation','attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_CHRR_COSMOS','PER_HIGH_MEDIEVAL_WEST','Structural hub entity grouping the Christian otherworld realms; attested as a coherent tripartite-plus cosmos in scholastic theology and Dante.'),
 ('ENT_CHRR_PURGATORY','PER_HIGH_MEDIEVAL_WEST','Catholic doctrine of final purification (CCC 1030–1032); poetically the seven-terraced mountain of Purgatorio.'),
 ('ENT_CHRR_LIMBUS_PATRUM','PER_HIGH_MEDIEVAL_WEST','Traditional Catholic teaching on the Harrowing of Hell; emptied by Christ at the Resurrection.'),
 ('ENT_CHRR_LIMBUS_INFANTUM','PER_HIGH_MEDIEVAL_WEST','Medieval-scholastic theory (Aquinas); the Catechism leaves the fate of unbaptized infants to God''s mercy. Attested as theological tradition, not dogma.'),
 ('ENT_CHRR_EMPYREAN','PER_HIGH_MEDIEVAL_WEST','Medieval cosmological term (caelum empyreum); the tenth, immobile heaven in Dante''s Paradiso.'),
 ('ENT_CHRR_BEATIFIC_VISION','PER_HIGH_MEDIEVAL_WEST','Catholic doctrine of the final blessedness; distinct from the Solomonic-magic ''operation'' homonym (ENT_SOL_BEATIFIC_VISION_OP, confirmed present in DB).'),
 ('ENT_CHRR_BOSOM_ABRAHAM','PER_PATRISTIC','Lukan parable; patristic/medieval identification with Limbus Patrum.'),
 ('ENT_CHRR_NEW_JERUSALEM','PER_PATRISTIC','Apocalyptic vision (Rev 21); developed as the City of God by Augustine.'),
 ('ENT_CHRR_HEAVEN','PER_PATRISTIC','Core Christian eschatology (CCC 1023–1029). No prior Christian-tradition Heaven realm existed in the DB.'),
 ('ENT_CHRR_HELL','PER_PATRISTIC','Christian eschatology (CCC 1033–1037). Distinct from Jewish Gehenna/Sheol (ENT_JM_GEHENNA, ENT_ISR_SHEOL), to which it is the conceptual heir.'),
 ('ENT_CHRR_NINE_CIRCLES','PER_HIGH_MEDIEVAL_WEST','Literary-structural node from Dante''s Inferno; the canonical poetic topology of Christian Hell.'),
 ('ENT_CHRR_SEVEN_TERRACES','PER_HIGH_MEDIEVAL_WEST','Literary-structural node from Dante''s Purgatorio; the seven terraces correspond to the seven deadly sins.'),
 ('ENT_CHRR_CELESTIAL_SPHERES','PER_HIGH_MEDIEVAL_WEST','Literary-structural node from Dante''s Paradiso, fusing Ptolemaic astronomy with Christian theology.');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_CHRR_HEAVEN','member_of','ENT_CHRR_COSMOS','high','Heaven is a principal realm of the structured Christian cosmos.'),
 ('ENT_CHRR_HELL','member_of','ENT_CHRR_COSMOS','high','Hell is a principal realm of the structured Christian cosmos.'),
 ('ENT_CHRR_PURGATORY','member_of','ENT_CHRR_COSMOS','high','Purgatory is the intermediate purifying realm of the Christian cosmos.'),
 ('ENT_CHRR_LIMBUS_PATRUM','member_of','ENT_CHRR_COSMOS','high','The Limbo of the Fathers is a region of the Christian otherworld cosmos.'),
 ('ENT_CHRR_LIMBUS_INFANTUM','member_of','ENT_CHRR_COSMOS','medium','The Limbo of the Infants is a theorized region of the Christian cosmos.'),
 ('ENT_CHRR_EMPYREAN','member_of','ENT_CHRR_HEAVEN','high','The Empyrean is the highest heaven, the innermost dwelling of God within Heaven.'),
 ('ENT_CHRR_NEW_JERUSALEM','member_of','ENT_CHRR_HEAVEN','high','The New Jerusalem is the consummated heavenly city, the perfected form of Heaven.'),
 ('ENT_CHRR_BOSOM_ABRAHAM','equated_with','ENT_CHRR_LIMBUS_PATRUM','high','Christian tradition identifies the Bosom of Abraham with the Limbo of the Fathers, the rest of the righteous dead before Christ.'),
 ('ENT_CHRR_BEATIFIC_VISION','dwells_in','ENT_CHRR_EMPYREAN','medium','The Beatific Vision is enjoyed by the blessed in the Empyrean, the highest heaven.'),
 ('ENT_CHRR_NINE_CIRCLES','member_of','ENT_CHRR_HELL','high','Dante''s nine descending circles are the structural articulation of Hell.'),
 ('ENT_CHRR_SEVEN_TERRACES','member_of','ENT_CHRR_PURGATORY','high','Dante''s seven terraces are the structural articulation of Mount Purgatory.'),
 ('ENT_CHRR_CELESTIAL_SPHERES','member_of','ENT_CHRR_HEAVEN','high','Dante''s nine revolving celestial spheres are the ascending structure of Heaven below the Empyrean.'),
 ('ENT_CHRR_LIMBUS_PATRUM','member_of','ENT_CHRR_NINE_CIRCLES','medium','Dante places Limbo as the first of the nine circles of Hell.'),
 ('ENT_CHR_DEVIL','dwells_in','ENT_CHRR_HELL','high','Hell is the abode of the Devil; Dante fixes Satan at the center of the Inferno.'),
 ('ENT_CHR_DEMONS','dwells_in','ENT_CHRR_HELL','high','The demons inhabit Hell with their prince the Devil.'),
 ('ENT_JESUS_CHRIST','rescues','ENT_CHRR_LIMBUS_PATRUM','high','In the Harrowing of Hell, Christ descends and liberates the righteous held in the Limbo of the Fathers.'),
 ('ENT_CHRR_HELL','reception_of','ENT_JM_GEHENNA','medium','The Christian conception of Hell as the place of eternal punishment develops from the Jewish Gehenna.'),
 ('ENT_CHRR_BOSOM_ABRAHAM','reception_of','ENT_ISR_SHEOL','low','The Bosom of Abraham as the rest of the righteous dead draws on the older Israelite Sheol as abode of the dead.'),
 ('ENT_PAT_AUGUSTINE','transmits','ENT_CHRR_NEW_JERUSALEM','medium','Augustine systematizes and transmits the heavenly Jerusalem as the City of God in De Civitate Dei.');

\echo '--- REJECTED edges (bad id/type, or subject lacks a source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
