-- build_p7_vodou.sql  (GENERATED by gen_roster.py p7_vodou) — v1.80.0
-- 18 entities, 31 edges, 1 new periods, 2 new sources. Idempotent + self-validating.
BEGIN;

INSERT INTO periods (period_id, period_name, start_year, end_year) VALUES
 ('PER_VODOU','Haitian Vodou (colonial Saint-Domingue formation to present)',1700,2025)
ON CONFLICT (period_id) DO NOTHING;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_MURPHY_WORKING_SPIRIT','secondary scholarship','Joseph M. Murphy, Working the Spirit: Ceremonies of the African Diaspora (Beacon Press, 1994)','Afro-diasporic religions incl. Haitian Vodou; ceremony, lwa, saint syncretism'),
 ('SRC_METRAUX_VOODOO_HAITI','secondary scholarship','Alfred Métraux, Voodoo in Haiti (trans. Hugo Charteris, Oxford UP, 1959)','Ethnography of Haitian Vodou; the lwa, nanchon, possession, and Catholic syncretism')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,trad text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_VOD_BONDYE','Bondye','deity','creator deity','Vodou','supreme creator; transcendence','B','The remote, supreme creator God of Haitian Vodou (from French ''Bon Dieu''); identified with the Christian God, served indirectly through the lwa. Living tradition; modern.'),
 ('ENT_VOD_LWA','The Lwa','collective','pantheon/collective','Vodou','served spirits; intermediaries','B','Collective hub for the lwa (mistè), the served spirits who mediate between Bondye and humanity, organized in nanchon (chiefly Rada and Petwo). Living tradition.'),
 ('ENT_VOD_RADA','Rada nanchon','collective','pantheon/collective','Vodou','cool, beneficent spirits; ancestral Dahomean rite','B','The Rada nanchon: ''cool'' (dou) lwa of largely Fon/Dahomean derivation, served in the Rada rite. Publicly documented organizing category. Living tradition.'),
 ('ENT_VOD_PETWO','Petwo nanchon','collective','pantheon/collective','Vodou','hot, forceful spirits; New-World/Kongo rite','B','The Petwo (Petro) nanchon: ''hot'' (cho) lwa of New-World and Kongo derivation, served in the Petwo rite. Publicly documented organizing category. Living tradition.'),
 ('ENT_VOD_LEGBA','Papa Legba','deity','lwa','Vodou','crossroads; gates; opener of the way','B','Rada lwa, the gatekeeper opening the way between worlds; saluted first in ceremony. Publicly identified in Vodou imagery with St Peter (keys) and St Lazarus. Living tradition.'),
 ('ENT_VOD_ERZULIE_FREDA','Erzulie Freda','deity','lwa','Vodou','love; beauty; luxury; feminine grace','B','Rada lwa of love and beauty; her chromolithograph is widely the Mater Dolorosa. Publicly attested. Living tradition.'),
 ('ENT_VOD_ERZULIE_DANTOR','Erzulie Dantor','deity','lwa','Vodou','fierce mother-protector; single mothers; defense','B','Petwo lwa, fierce protective mother; popularly imaged as the Black Madonna of Częstochowa (and St Barbara). Publicly attested. Living tradition.'),
 ('ENT_VOD_DAMBALLA','Damballa Wedo','deity','lwa','Vodou','serpent; creation; sky; purity; ancestral wisdom','B','Rada serpent lwa, ancient and benevolent creator-associated spirit, consort of Ayida-Wedo; popularly imaged as St Patrick (serpents). Publicly attested. Living tradition.'),
 ('ENT_VOD_AYIDA_WEDO','Ayida-Wedo','deity','lwa','Vodou','rainbow serpent; sky; fertility','B','Rada rainbow-serpent lwa, consort of Damballa; the serpent pair embodies cosmic balance. Publicly attested. Living tradition.'),
 ('ENT_VOD_BARON_SAMEDI','Baron Samedi','deity','lwa','Vodou','death; cemeteries; the dead; healing of the dying','B','Chief of the Gede; lord of cemeteries and the dead, associated with the cemetery cross. Publicly attested. Living tradition; not modeled here as a ''narco-saint'' or sensationalized figure.'),
 ('ENT_VOD_GEDE','The Gede','collective','lwa family/collective','Vodou','the dead; ancestors; fertility; ribald humor','B','Family (and Petwo-adjacent nanchon) of lwa of death and the ancestors, led by the Barons and Maman Brigitte. Publicly attested. Living tradition.'),
 ('ENT_VOD_MAMAN_BRIGITTE','Maman Brigitte','deity','lwa','Vodou','death; cemeteries; consort of Baron; protector of graves','B','Gede lwa, consort of Baron Samedi, mistress of the cemetery; her name reflects the Irish Brigid heritage of the diaspora. Publicly attested. Living tradition.'),
 ('ENT_VOD_OGOU','Ogou','deity','lwa','Vodou','iron; war; fire; soldiers; political power','B','Lwa of iron and war (Yoruba-derived Ogun), served across nanchon; popularly imaged as St James the Greater (Santiago Matamoros). Publicly attested. Living tradition.'),
 ('ENT_VOD_AGWE','Agwe','deity','lwa','Vodou','the sea; ships; sovereign of the waters','B','Rada lwa, sovereign of the sea and patron of sailors and fishermen, consort of La Sirène. Publicly attested. Living tradition.'),
 ('ENT_VOD_LASIRENE','La Sirène','deity','lwa','Vodou','the sea; wealth; music; mermaid spirit','B','Lwa of the sea, a mermaid spirit linked to Agwe and to the water-mother complex (Lasirèn/Labalèn). Publicly attested. Living tradition.'),
 ('ENT_VOD_MARASSA','The Marassa','deity','lwa','Vodou','divine twins; children; doubling; reciprocity','B','The sacred Marassa (divine twins), among the first lwa served; popularly imaged as Sts Cosmas and Damian. Publicly attested. Living tradition.'),
 ('ENT_VOD_LOKO','Loko','deity','lwa','Vodou','sacred trees; healing; patron of priests (oungan)','B','Rada lwa of vegetation and healing, patron of the priesthood and of the poto-mitan/sacred tree, consort of Ayizan. Publicly attested. Living tradition.'),
 ('ENT_VOD_SIMBI','Simbi','deity','lwa','Vodou','fresh water; springs; magic; messenger','B','Lwa (Kongo-derived, often Petwo) of fresh water, springs and rain, associated with magic and patronage of healers/sorcerers. Publicly attested. Living tradition.');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'devotional',conf,'candidate_verified_name','Roster build via gen_roster.py (see CHANGELOG/git for release)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,etype text,note text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_VOD_BONDYE','SRC_METRAUX_VOODOO_HAITI','scholarly attestation','attestation'),
 ('ENT_VOD_LWA','SRC_MURPHY_WORKING_SPIRIT','scholarly attestation','attestation'),
 ('ENT_VOD_RADA','SRC_METRAUX_VOODOO_HAITI','scholarly attestation','attestation'),
 ('ENT_VOD_PETWO','SRC_METRAUX_VOODOO_HAITI','scholarly attestation','attestation'),
 ('ENT_VOD_LEGBA','SRC_MURPHY_WORKING_SPIRIT','scholarly attestation','attestation'),
 ('ENT_VOD_ERZULIE_FREDA','SRC_MURPHY_WORKING_SPIRIT','scholarly attestation','attestation'),
 ('ENT_VOD_ERZULIE_DANTOR','SRC_MURPHY_WORKING_SPIRIT','scholarly attestation','attestation'),
 ('ENT_VOD_DAMBALLA','SRC_METRAUX_VOODOO_HAITI','scholarly attestation','attestation'),
 ('ENT_VOD_AYIDA_WEDO','SRC_METRAUX_VOODOO_HAITI','scholarly attestation','attestation'),
 ('ENT_VOD_BARON_SAMEDI','SRC_MURPHY_WORKING_SPIRIT','scholarly attestation','attestation'),
 ('ENT_VOD_GEDE','SRC_MURPHY_WORKING_SPIRIT','scholarly attestation','attestation'),
 ('ENT_VOD_MAMAN_BRIGITTE','SRC_MURPHY_WORKING_SPIRIT','scholarly attestation','attestation'),
 ('ENT_VOD_OGOU','SRC_MURPHY_WORKING_SPIRIT','scholarly attestation','attestation'),
 ('ENT_VOD_AGWE','SRC_METRAUX_VOODOO_HAITI','scholarly attestation','attestation'),
 ('ENT_VOD_LASIRENE','SRC_METRAUX_VOODOO_HAITI','scholarly attestation','attestation'),
 ('ENT_VOD_MARASSA','SRC_MURPHY_WORKING_SPIRIT','scholarly attestation','attestation'),
 ('ENT_VOD_LOKO','SRC_METRAUX_VOODOO_HAITI','scholarly attestation','attestation'),
 ('ENT_VOD_SIMBI','SRC_METRAUX_VOODOO_HAITI','scholarly attestation','attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_VOD_BONDYE','PER_VODOU','The remote, supreme creator God of Haitian Vodou (from French ''Bon Dieu''); identified with the Christian God, served indirectly through the lwa. Living tradition; modern.'),
 ('ENT_VOD_LWA','PER_VODOU','Collective hub for the lwa (mistè), the served spirits who mediate between Bondye and humanity, organized in nanchon (chiefly Rada and Petwo). Living tradition.'),
 ('ENT_VOD_RADA','PER_VODOU','The Rada nanchon: ''cool'' (dou) lwa of largely Fon/Dahomean derivation, served in the Rada rite. Publicly documented organizing category. Living tradition.'),
 ('ENT_VOD_PETWO','PER_VODOU','The Petwo (Petro) nanchon: ''hot'' (cho) lwa of New-World and Kongo derivation, served in the Petwo rite. Publicly documented organizing category. Living tradition.'),
 ('ENT_VOD_LEGBA','PER_VODOU','Rada lwa, the gatekeeper opening the way between worlds; saluted first in ceremony. Publicly identified in Vodou imagery with St Peter (keys) and St Lazarus. Living tradition.'),
 ('ENT_VOD_ERZULIE_FREDA','PER_VODOU','Rada lwa of love and beauty; her chromolithograph is widely the Mater Dolorosa. Publicly attested. Living tradition.'),
 ('ENT_VOD_ERZULIE_DANTOR','PER_VODOU','Petwo lwa, fierce protective mother; popularly imaged as the Black Madonna of Częstochowa (and St Barbara). Publicly attested. Living tradition.'),
 ('ENT_VOD_DAMBALLA','PER_VODOU','Rada serpent lwa, ancient and benevolent creator-associated spirit, consort of Ayida-Wedo; popularly imaged as St Patrick (serpents). Publicly attested. Living tradition.'),
 ('ENT_VOD_AYIDA_WEDO','PER_VODOU','Rada rainbow-serpent lwa, consort of Damballa; the serpent pair embodies cosmic balance. Publicly attested. Living tradition.'),
 ('ENT_VOD_BARON_SAMEDI','PER_VODOU','Chief of the Gede; lord of cemeteries and the dead, associated with the cemetery cross. Publicly attested. Living tradition; not modeled here as a ''narco-saint'' or sensationalized figure.'),
 ('ENT_VOD_GEDE','PER_VODOU','Family (and Petwo-adjacent nanchon) of lwa of death and the ancestors, led by the Barons and Maman Brigitte. Publicly attested. Living tradition.'),
 ('ENT_VOD_MAMAN_BRIGITTE','PER_VODOU','Gede lwa, consort of Baron Samedi, mistress of the cemetery; her name reflects the Irish Brigid heritage of the diaspora. Publicly attested. Living tradition.'),
 ('ENT_VOD_OGOU','PER_VODOU','Lwa of iron and war (Yoruba-derived Ogun), served across nanchon; popularly imaged as St James the Greater (Santiago Matamoros). Publicly attested. Living tradition.'),
 ('ENT_VOD_AGWE','PER_VODOU','Rada lwa, sovereign of the sea and patron of sailors and fishermen, consort of La Sirène. Publicly attested. Living tradition.'),
 ('ENT_VOD_LASIRENE','PER_VODOU','Lwa of the sea, a mermaid spirit linked to Agwe and to the water-mother complex (Lasirèn/Labalèn). Publicly attested. Living tradition.'),
 ('ENT_VOD_MARASSA','PER_VODOU','The sacred Marassa (divine twins), among the first lwa served; popularly imaged as Sts Cosmas and Damian. Publicly attested. Living tradition.'),
 ('ENT_VOD_LOKO','PER_VODOU','Rada lwa of vegetation and healing, patron of the priesthood and of the poto-mitan/sacred tree, consort of Ayizan. Publicly attested. Living tradition.'),
 ('ENT_VOD_SIMBI','PER_VODOU','Lwa (Kongo-derived, often Petwo) of fresh water, springs and rain, associated with magic and patronage of healers/sorcerers. Publicly attested. Living tradition.');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_VOD_LWA','emanates_from','ENT_VOD_BONDYE','high','The lwa serve and mediate the remote creator Bondye, who is their ultimate source (Métraux; Murphy).'),
 ('ENT_VOD_RADA','member_of','ENT_VOD_LWA','high','Rada is one of the principal nanchon (divisions) of the lwa.'),
 ('ENT_VOD_PETWO','member_of','ENT_VOD_LWA','high','Petwo is one of the principal nanchon (divisions) of the lwa.'),
 ('ENT_VOD_LEGBA','member_of','ENT_VOD_LWA','high','Papa Legba is a lwa.'),
 ('ENT_VOD_LEGBA','member_of','ENT_VOD_RADA','high','Legba is served as a Rada lwa, saluted first in ceremony (Métraux).'),
 ('ENT_VOD_ERZULIE_FREDA','member_of','ENT_VOD_RADA','high','Erzulie Freda Dahomey is a Rada lwa of love and beauty (Murphy).'),
 ('ENT_VOD_ERZULIE_DANTOR','member_of','ENT_VOD_PETWO','high','Erzulie Dantor is the fierce Petwo counterpart of Erzulie (Murphy).'),
 ('ENT_VOD_ERZULIE_DANTOR','opposes','ENT_VOD_ERZULIE_FREDA','medium','The Petwo Dantor and Rada Freda form the documented hot/cool polarity of the Erzulie complex (Murphy).'),
 ('ENT_VOD_DAMBALLA','member_of','ENT_VOD_RADA','high','Damballa Wedo is the senior Rada serpent lwa (Métraux).'),
 ('ENT_VOD_AYIDA_WEDO','member_of','ENT_VOD_RADA','high','Ayida-Wedo is a Rada serpent lwa (Métraux).'),
 ('ENT_VOD_AYIDA_WEDO','consort_of','ENT_VOD_DAMBALLA','high','Ayida-Wedo and Damballa are the paired rainbow/serpent consorts (Métraux).'),
 ('ENT_VOD_BARON_SAMEDI','member_of','ENT_VOD_GEDE','high','Baron Samedi heads the Gede family of death lwa (Murphy).'),
 ('ENT_VOD_GEDE','member_of','ENT_VOD_LWA','high','The Gede are a family/nanchon within the lwa.'),
 ('ENT_VOD_MAMAN_BRIGITTE','member_of','ENT_VOD_GEDE','high','Maman Brigitte is a Gede lwa of the cemetery (Murphy).'),
 ('ENT_VOD_MAMAN_BRIGITTE','consort_of','ENT_VOD_BARON_SAMEDI','high','Maman Brigitte is the documented consort of Baron Samedi (Murphy).'),
 ('ENT_VOD_OGOU','member_of','ENT_VOD_LWA','high','Ogou (Yoruba-derived Ogun) is a lwa of iron and war served across nanchon (Murphy).'),
 ('ENT_VOD_AGWE','member_of','ENT_VOD_RADA','high','Agwe, sovereign of the sea, is a Rada lwa (Métraux).'),
 ('ENT_VOD_LASIRENE','member_of','ENT_VOD_LWA','high','La Sirène, the mermaid sea spirit, is a lwa (Métraux).'),
 ('ENT_VOD_LASIRENE','consort_of','ENT_VOD_AGWE','medium','La Sirène is paired with Agwe in the marine complex of lwa (Métraux).'),
 ('ENT_VOD_MARASSA','member_of','ENT_VOD_LWA','high','The Marassa (divine twins) are among the lwa served (Murphy).'),
 ('ENT_VOD_LOKO','member_of','ENT_VOD_RADA','high','Loko is a Rada lwa, patron of the priesthood (Métraux).'),
 ('ENT_VOD_SIMBI','member_of','ENT_VOD_LWA','high','Simbi, the Kongo-derived water lwa, is a lwa often served in Petwo (Métraux).'),
 ('ENT_VOD_SIMBI','member_of','ENT_VOD_PETWO','medium','Simbi is frequently served within the Petwo nanchon (Métraux).'),
 ('ENT_VOD_LEGBA','syncretized_with','ENT_SAINT_PETER','high','Papa Legba, keeper of the gates, is popularly identified with St Peter (the keys) in Vodou chromolithography (Métraux; Murphy).'),
 ('ENT_VOD_LEGBA','syncretized_with','ENT_NT_LAZARUS_BETHANY','medium','In some lineages the aged, crutch-bearing Legba is imaged as St Lazarus (Métraux).'),
 ('ENT_VOD_LEGBA','aligned_with','ENT_SAINT_ANTHONY_PADUA','medium','St Anthony of Padua is also documented as a chromolithographic image for Legba in parts of Haiti (Métraux).'),
 ('ENT_VOD_ERZULIE_FREDA','syncretized_with','ENT_MARY_SORROWS','high','Erzulie Freda is popularly identified with the Mater Dolorosa / Our Lady of Sorrows (Murphy; Métraux).'),
 ('ENT_VOD_ERZULIE_DANTOR','syncretized_with','ENT_MARY_CZESTOCHOWA','high','Erzulie Dantor is popularly imaged as the Black Madonna of Częstochowa (Murphy).'),
 ('ENT_VOD_ERZULIE_DANTOR','aligned_with','ENT_CHR_BARBARA','medium','St Barbara also appears among the Catholic images associated with the fierce Erzulie Dantor in Vodou practice (Murphy).'),
 ('ENT_VOD_OGOU','syncretized_with','ENT_SAINT_JAMES_GREATER','high','Ogou is popularly identified with St James the Greater (Santiago, the mounted warrior) (Murphy; Métraux).'),
 ('ENT_VOD_MARASSA','syncretized_with','ENT_SAINT_COSMAS_DAMIAN','high','The divine twins Marassa are popularly imaged as Sts Cosmas and Damian, the holy twin physicians (Murphy; Métraux).');

\echo '--- REJECTED edges (bad id/type, or subject lacks a source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
