-- build_p6_realms_norse.sql  (GENERATED by gen_roster.py p6_realms_norse) — v1.80.0
-- 15 entities, 31 edges, 0 new periods, 2 new sources. Idempotent + self-validating.
BEGIN;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_PROSE_EDDA','primary text','Snorri Sturluson, Prose Edda (Gylfaginning)','Primary 13th-c. Old Norse prose mythography; Gylfaginning is the systematic source for the Nine Worlds, Yggdrasil, the wells, Bifröst and the cosmological realms. Reused, already in DB.'),
 ('SRC_POETIC_EDDA','primary text','Poetic Edda','Eddic poems (Völuspá, Grímnismál, Vafþrúðnismál) attesting Ginnungagap, the Well of Urðr, Mímisbrunnr, Múspell and the realms. Reused, already in DB.')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,trad text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_NORR_NINE_WORLDS','The Nine Worlds (Níu Heimar)','Cosmological category','realm-collective','Germanic/Norse','cosmology|cosmography','B','Hub collective for the nine cosmological worlds bound by Yggdrasil; Vafþrúðnismál 43 and Völuspá 2 attest ''nine worlds'' (níu heimar / níu íviðjur) though no single source enumerates them identically. Standard reconstruction (Asgard, Vanaheim, Alfheim, Midgard, Jotunheim, Svartalfheim/Nidavellir, Niflheim, Muspelheim, Hel) is modern-scholarly synthesis of Eddic material.'),
 ('ENT_NORR_ASGARD','Asgard (Ásgarðr)','Cosmological realm','divine-realm','Germanic/Norse','cosmology|divine abode','B','Stronghold of the Æsir, situated at the upper reaches of Yggdrasil and reached from Midgard by Bifröst; contains Valhalla. Gylfaginning attests its building and its halls.'),
 ('ENT_NORR_MIDGARD','Midgard (Miðgarðr)','Cosmological realm','human-realm','Germanic/Norse','cosmology|human world','B','The middle enclosure, the world of humankind, made by the sons of Borr from the brows of Ymir and encircled by Jörmungandr. Gylfaginning and Völuspá.'),
 ('ENT_NORR_VANAHEIM','Vanaheim (Vanaheimr)','Cosmological realm','divine-realm','Germanic/Norse','cosmology|divine abode','C','Home of the Vanir; named in Vafþrúðnismál 39 (Njörðr was reared in Vanaheim) and in Ynglinga saga. Sparsely described beyond its association with the Vanir.'),
 ('ENT_NORR_JOTUNHEIM','Jotunheim (Jötunheimr) / Útgarðr','Cosmological realm','giant-realm','Germanic/Norse','cosmology|giants','B','Land of the jötnar, lying outside Midgard across rivers and forests; its citadel Útgarðr features in Gylfaginning''s Útgarða-Loki episode. Jötunheimr and the outer Útgarðr are treated together here.'),
 ('ENT_NORR_NIFLHEIM','Niflheim (Niflheimr)','Cosmological realm','primordial-realm','Germanic/Norse','cosmology|primordial cold|underworld','B','World of mist and cold in the north, containing the spring Hvergelmir and the root gnawed by Níðhöggr; in Gylfaginning the primordial counterpart to fiery Múspell, and sometimes conflated with the realm of Hel.'),
 ('ENT_NORR_MUSPELHEIM','Muspelheim (Múspellsheimr)','Cosmological realm','primordial-realm','Germanic/Norse','cosmology|primordial fire','B','Realm of fire in the south, guarded by Surtr; its sparks helped form the cosmos and its hosts (Múspells synir) ride against the gods at Ragnarök. Gylfaginning; Völuspá names Múspell.'),
 ('ENT_NORR_ALFHEIM','Alfheim (Álfheimr)','Cosmological realm','elf-realm','Germanic/Norse','cosmology|elves','C','Home of the light-elves (ljósálfar), given to Freyr as a tooth-gift according to Grímnismál 5 and Gylfaginning. Lightly attested.'),
 ('ENT_NORR_SVARTALFHEIM','Svartalfheim (Svartálfaheimr) / Nidavellir','Cosmological realm','dwarf-realm','Germanic/Norse','cosmology|dwarves|smithcraft','C','Subterranean realm of the dark-elves/dwarves and their smithies; Gylfaginning sends Loki to Svartálfaheimr for the gods'' treasures. Often equated with Niðavellir (Völuspá 37), the ''dark fields'' of the dwarves; the equation is scholarly.'),
 ('ENT_NORR_VALHALLA','Valhalla (Valhöll)','Cosmological realm','afterlife-hall','Germanic/Norse','afterlife|battle-dead','B','Odin''s hall of the slain within Asgard, where the Einherjar feast and prepare for Ragnarök, served by Valkyries. Grímnismál and Gylfaginning describe its 540 doors and Sæhrímnir.'),
 ('ENT_NORR_FOLKVANGR','Folkvangr','Cosmological realm','afterlife-realm','Germanic/Norse','afterlife|battle-dead','C','Freyja''s field where she receives half of the battle-slain, the other half going to Odin; her hall there is Sessrúmnir. Grímnismál 14 and Gylfaginning.'),
 ('ENT_NORR_BIFROST','Bifröst (the rainbow bridge)','Cosmological realm','liminal-structure','Germanic/Norse','cosmology|liminal structure','B','The burning rainbow bridge (Bilröst/Bifröst) joining Midgard and Asgard, guarded by Heimdall, destined to break under the Múspell host at Ragnarök. Gylfaginning. Modeled as a locale within the realm set.'),
 ('ENT_NORR_GINNUNGAGAP','Ginnungagap','Cosmological realm','primordial-void','Germanic/Norse','cosmology|primordial void','B','The yawning primordial void between Niflheim and Muspelheim, where their rime and heat met to generate Ymir and the cosmos. Gylfaginning; Völuspá 3 (gap var ginnunga).'),
 ('ENT_NORR_URDARBRUNNR','Well of Urd (Urðarbrunnr)','Cosmological realm','sacred-well','Germanic/Norse','cosmology|fate|sacred water','B','The Well of Fate beneath a root of Yggdrasil where the gods hold court and the Norns water the tree; Völuspá 19-20 and Gylfaginning. Modeled as a sacred locale.'),
 ('ENT_NORR_MIMISBRUNNR','Well of Mimir (Mímisbrunnr)','Cosmological realm','sacred-well','Germanic/Norse','cosmology|wisdom|sacred water','B','The Well of Wisdom beneath a root of Yggdrasil, kept by Mímir; Odin pledged his eye there for a draught. Völuspá 28 and Gylfaginning. Modeled as a sacred locale.');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'devotional',conf,'candidate_verified_name','Roster build via gen_roster.py (see CHANGELOG/git for release)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,etype text,note text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_NORR_NINE_WORLDS','SRC_POETIC_EDDA','primary text attestation','attestation'),
 ('ENT_NORR_ASGARD','SRC_PROSE_EDDA','primary text attestation','attestation'),
 ('ENT_NORR_MIDGARD','SRC_PROSE_EDDA','primary text attestation','attestation'),
 ('ENT_NORR_VANAHEIM','SRC_POETIC_EDDA','primary text attestation','attestation'),
 ('ENT_NORR_JOTUNHEIM','SRC_PROSE_EDDA','primary text attestation','attestation'),
 ('ENT_NORR_NIFLHEIM','SRC_PROSE_EDDA','primary text attestation','attestation'),
 ('ENT_NORR_MUSPELHEIM','SRC_PROSE_EDDA','primary text attestation','attestation'),
 ('ENT_NORR_ALFHEIM','SRC_PROSE_EDDA','primary text attestation','attestation'),
 ('ENT_NORR_SVARTALFHEIM','SRC_PROSE_EDDA','primary text attestation','attestation'),
 ('ENT_NORR_VALHALLA','SRC_PROSE_EDDA','primary text attestation','attestation'),
 ('ENT_NORR_FOLKVANGR','SRC_PROSE_EDDA','primary text attestation','attestation'),
 ('ENT_NORR_BIFROST','SRC_PROSE_EDDA','primary text attestation','attestation'),
 ('ENT_NORR_GINNUNGAGAP','SRC_PROSE_EDDA','primary text attestation','attestation'),
 ('ENT_NORR_URDARBRUNNR','SRC_POETIC_EDDA','primary text attestation','attestation'),
 ('ENT_NORR_MIMISBRUNNR','SRC_POETIC_EDDA','primary text attestation','attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_NORR_NINE_WORLDS','PER_NOR_VIKING','Hub collective for the nine cosmological worlds bound by Yggdrasil; Vafþrúðnismál 43 and Völuspá 2 attest ''nine worlds'' (níu heimar / níu íviðjur) though no single source enumerates them identically. Standard reconstruction (Asgard, Vanaheim, Alfheim, Midgard, Jotunheim, Svartalfheim/Nidavellir, Niflheim, Muspelheim, Hel) is modern-scholarly synthesis of Eddic material.'),
 ('ENT_NORR_ASGARD','PER_NOR_VIKING','Stronghold of the Æsir, situated at the upper reaches of Yggdrasil and reached from Midgard by Bifröst; contains Valhalla. Gylfaginning attests its building and its halls.'),
 ('ENT_NORR_MIDGARD','PER_NOR_VIKING','The middle enclosure, the world of humankind, made by the sons of Borr from the brows of Ymir and encircled by Jörmungandr. Gylfaginning and Völuspá.'),
 ('ENT_NORR_VANAHEIM','PER_NOR_VIKING','Home of the Vanir; named in Vafþrúðnismál 39 (Njörðr was reared in Vanaheim) and in Ynglinga saga. Sparsely described beyond its association with the Vanir.'),
 ('ENT_NORR_JOTUNHEIM','PER_NOR_VIKING','Land of the jötnar, lying outside Midgard across rivers and forests; its citadel Útgarðr features in Gylfaginning''s Útgarða-Loki episode. Jötunheimr and the outer Útgarðr are treated together here.'),
 ('ENT_NORR_NIFLHEIM','PER_NOR_VIKING','World of mist and cold in the north, containing the spring Hvergelmir and the root gnawed by Níðhöggr; in Gylfaginning the primordial counterpart to fiery Múspell, and sometimes conflated with the realm of Hel.'),
 ('ENT_NORR_MUSPELHEIM','PER_NOR_VIKING','Realm of fire in the south, guarded by Surtr; its sparks helped form the cosmos and its hosts (Múspells synir) ride against the gods at Ragnarök. Gylfaginning; Völuspá names Múspell.'),
 ('ENT_NORR_ALFHEIM','PER_NOR_VIKING','Home of the light-elves (ljósálfar), given to Freyr as a tooth-gift according to Grímnismál 5 and Gylfaginning. Lightly attested.'),
 ('ENT_NORR_SVARTALFHEIM','PER_NOR_VIKING','Subterranean realm of the dark-elves/dwarves and their smithies; Gylfaginning sends Loki to Svartálfaheimr for the gods'' treasures. Often equated with Niðavellir (Völuspá 37), the ''dark fields'' of the dwarves; the equation is scholarly.'),
 ('ENT_NORR_VALHALLA','PER_NOR_VIKING','Odin''s hall of the slain within Asgard, where the Einherjar feast and prepare for Ragnarök, served by Valkyries. Grímnismál and Gylfaginning describe its 540 doors and Sæhrímnir.'),
 ('ENT_NORR_FOLKVANGR','PER_NOR_VIKING','Freyja''s field where she receives half of the battle-slain, the other half going to Odin; her hall there is Sessrúmnir. Grímnismál 14 and Gylfaginning.'),
 ('ENT_NORR_BIFROST','PER_NOR_VIKING','The burning rainbow bridge (Bilröst/Bifröst) joining Midgard and Asgard, guarded by Heimdall, destined to break under the Múspell host at Ragnarök. Gylfaginning. Modeled as a locale within the realm set.'),
 ('ENT_NORR_GINNUNGAGAP','PER_NOR_VIKING','The yawning primordial void between Niflheim and Muspelheim, where their rime and heat met to generate Ymir and the cosmos. Gylfaginning; Völuspá 3 (gap var ginnunga).'),
 ('ENT_NORR_URDARBRUNNR','PER_NOR_VIKING','The Well of Fate beneath a root of Yggdrasil where the gods hold court and the Norns water the tree; Völuspá 19-20 and Gylfaginning. Modeled as a sacred locale.'),
 ('ENT_NORR_MIMISBRUNNR','PER_NOR_VIKING','The Well of Wisdom beneath a root of Yggdrasil, kept by Mímir; Odin pledged his eye there for a draught. Völuspá 28 and Gylfaginning. Modeled as a sacred locale.');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_NORR_ASGARD','member_of','ENT_NORR_NINE_WORLDS','high','Asgard is one of the nine worlds in the standard reconstruction (Gylfaginning).'),
 ('ENT_NORR_MIDGARD','member_of','ENT_NORR_NINE_WORLDS','high','Midgard, the human world, is one of the nine worlds.'),
 ('ENT_NORR_VANAHEIM','member_of','ENT_NORR_NINE_WORLDS','medium','Vanaheim is counted among the nine worlds in the standard scholarly list.'),
 ('ENT_NORR_JOTUNHEIM','member_of','ENT_NORR_NINE_WORLDS','high','Jotunheim, land of the giants, is one of the nine worlds.'),
 ('ENT_NORR_NIFLHEIM','member_of','ENT_NORR_NINE_WORLDS','high','Niflheim is one of the nine worlds (Gylfaginning).'),
 ('ENT_NORR_MUSPELHEIM','member_of','ENT_NORR_NINE_WORLDS','high','Muspelheim is one of the nine worlds (Gylfaginning).'),
 ('ENT_NORR_ALFHEIM','member_of','ENT_NORR_NINE_WORLDS','medium','Alfheim, home of the light-elves, is one of the nine worlds.'),
 ('ENT_NORR_SVARTALFHEIM','member_of','ENT_NORR_NINE_WORLDS','medium','Svartalfheim/Nidavellir, realm of dwarves/dark-elves, is one of the nine worlds in the standard list.'),
 ('ENT_NOR_HEL','member_of','ENT_NORR_NINE_WORLDS','medium','Hel (the underworld) completes the standard nine-world enumeration; existing entity ENT_NOR_HEL conflates the ruler and her realm.'),
 ('ENT_NORR_ASGARD','dwelling_of','ENT_NOR_AESIR','high','Asgard is the stronghold of the Æsir (Gylfaginning).'),
 ('ENT_NOR_ODIN','dwells_in','ENT_NORR_ASGARD','high','Odin resides in Asgard, in his hall Valhalla.'),
 ('ENT_NORR_VANAHEIM','dwelling_of','ENT_NOR_VANIR','high','Vanaheim is the home of the Vanir (Vafþrúðnismál 39).'),
 ('ENT_NORR_JOTUNHEIM','dwelling_of','ENT_NOR_JOTNAR','high','Jotunheim/Utgard is the land of the jötnar (Gylfaginning).'),
 ('ENT_NORR_SVARTALFHEIM','dwelling_of','ENT_NOR_DWARVES','medium','Svartalfheim/Nidavellir is the subterranean realm of the dwarves and their smithies.'),
 ('ENT_NORR_VALHALLA','member_of','ENT_NORR_ASGARD','high','Valhalla is a hall situated within Asgard (Grímnismál; Gylfaginning).'),
 ('ENT_NORR_VALHALLA','dwelling_of','ENT_NOR_EINHERJAR','high','The Einherjar, the chosen slain, feast in Valhalla awaiting Ragnarök.'),
 ('ENT_NOR_ODIN','rules','ENT_NORR_VALHALLA','high','Valhalla is Odin''s hall of the slain.'),
 ('ENT_NOR_VALKYRIES','dwells_in','ENT_NORR_VALHALLA','medium','The Valkyries serve the Einherjar in Valhalla (Grímnismál; Gylfaginning).'),
 ('ENT_NORR_FOLKVANGR','ruled_by','ENT_NOR_FREYJA','high','Folkvangr is Freyja''s field where she receives half the battle-slain (Grímnismál 14).'),
 ('ENT_NORR_BIFROST','guarded_by','ENT_NOR_HEIMDALL','high','Heimdall guards Bifröst at the edge of heaven (Gylfaginning).'),
 ('ENT_NORR_GINNUNGAGAP','associated_with','ENT_NORR_NIFLHEIM','high','Ginnungagap lies between Niflheim and Muspelheim; Niflheim''s rime meets it from the north (Gylfaginning).'),
 ('ENT_NORR_GINNUNGAGAP','associated_with','ENT_NORR_MUSPELHEIM','high','Muspelheim''s heat meets Ginnungagap from the south, generating Ymir (Gylfaginning).'),
 ('ENT_NORR_MUSPELHEIM','guarded_by','ENT_NOR_SURTR','high','Surtr stands at the frontier of Muspelheim guarding it with a flaming sword (Gylfaginning).'),
 ('ENT_NORR_URDARBRUNNR','associated_with','ENT_NOR_YGGDRASIL','high','The Well of Urd lies beneath a root of Yggdrasil where the gods hold court (Völuspá; Gylfaginning).'),
 ('ENT_NORR_URDARBRUNNR','associated_with','ENT_NOR_NORNS','high','The Norns dwell by the Well of Urd and water Yggdrasil from it (Völuspá 20).'),
 ('ENT_NORR_MIMISBRUNNR','associated_with','ENT_NOR_YGGDRASIL','high','The Well of Mimir lies beneath a root of Yggdrasil (Gylfaginning).'),
 ('ENT_NORR_MIMISBRUNNR','associated_with','ENT_NOR_MIMIR','high','Mímir keeps the Well of Wisdom; Odin pledged his eye there (Völuspá 28; Gylfaginning).'),
 ('ENT_NORR_NIFLHEIM','associated_with','ENT_NOR_NIDHOGG','medium','Níðhöggr gnaws the root of Yggdrasil in Niflheim beside Hvergelmir (Gylfaginning; Grímnismál).'),
 ('ENT_NOR_JORMUNGANDR','dwells_in','ENT_NORR_MIDGARD','high','Jörmungandr the World Serpent encircles Midgard in the surrounding sea (Gylfaginning).'),
 ('ENT_NORR_BIFROST','associated_with','ENT_NORR_ASGARD','high','Bifröst connects Midgard to Asgard, the gods'' road into heaven (Gylfaginning).'),
 ('ENT_NORR_NINE_WORLDS','associated_with','ENT_NOR_YGGDRASIL','high','The nine worlds are bound together by the world-tree Yggdrasil, whose roots and branches reach into them.');

\echo '--- REJECTED edges (bad id/type, or subject lacks a source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
