-- build_p6_angels_finite.sql  (GENERATED by gen_roster.py p6_angels_finite) — v1.80.0
-- 13 entities, 23 edges, 0 new periods, 2 new sources. Idempotent + self-validating.
BEGIN;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_AGRIPPA_OCCULTA','primary text','Heinrich Cornelius Agrippa, De occulta philosophia libri tres (1533) — Bk II ch. 14, the Scale of Twelve (governance of the twelve zodiacal signs by twelve angels)','REUSE — primary source for the twelve zodiacal angels and the seven planetary scale'),
 ('SRC_DAVIDSON_ANGELS','secondary scholarship','Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (The Free Press / Macmillan, New York, 1967)','NEW — standard reference cross-attesting the names and zodiacal/planetary assignments of the zodiacal and planetary angels')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,trad text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_ANGF_ZODIAC_12','The Twelve Zodiacal Angels','Collective','Collective','Renaissance Esoteric','astrology; angelology; zodiac','B','Closed, enumerable set of twelve angels governing the twelve signs of the zodiac per Agrippa, De occulta philosophia II.14 (the Scale of Twelve). A structural collective; member angels attested in Agrippa and catalogued by Davidson.'),
 ('ENT_ANGF_MALCHIDAEL','Malchidael (Aries)','Angel','Angel','Renaissance Esoteric','zodiac: Aries; fire','B','Angel governing Aries in Agrippa''s Scale of Twelve (also spelled Malahidael/Machidiel). Attested Agrippa II.14; Davidson, Dictionary of Angels.'),
 ('ENT_ANGF_ASMODEL','Asmodel (Taurus)','Angel','Angel','Renaissance Esoteric','zodiac: Taurus; earth','B','Angel governing Taurus in Agrippa''s Scale of Twelve. Attested Agrippa II.14; Davidson. Not to be confused with the demon Asmodeus.'),
 ('ENT_ANGF_AMBRIEL','Ambriel (Gemini)','Angel','Angel','Renaissance Esoteric','zodiac: Gemini; air','B','Angel governing Gemini in Agrippa''s Scale of Twelve. Attested Agrippa II.14; Davidson.'),
 ('ENT_ANGF_MURIEL','Muriel (Cancer)','Angel','Angel','Renaissance Esoteric','zodiac: Cancer; water','B','Angel governing Cancer in Agrippa''s Scale of Twelve. Attested Agrippa II.14; Davidson.'),
 ('ENT_ANGF_VERCHIEL','Verchiel (Leo)','Angel','Angel','Renaissance Esoteric','zodiac: Leo; fire','B','Angel governing Leo in Agrippa''s Scale of Twelve (also Verachiel). Attested Agrippa II.14; Davidson.'),
 ('ENT_ANGF_HAMALIEL','Hamaliel (Virgo)','Angel','Angel','Renaissance Esoteric','zodiac: Virgo; earth','B','Angel governing Virgo in Agrippa''s Scale of Twelve. Attested Agrippa II.14; Davidson.'),
 ('ENT_ANGF_ZURIEL','Zuriel (Libra)','Angel','Angel','Renaissance Esoteric','zodiac: Libra; air','B','Angel governing Libra in Agrippa''s Scale of Twelve. Attested Agrippa II.14; Davidson.'),
 ('ENT_ANGF_BARBIEL','Barbiel (Scorpio)','Angel','Angel','Renaissance Esoteric','zodiac: Scorpio; water','B','Angel governing Scorpio in Agrippa''s Scale of Twelve (also a name among the planetary/lunar mansions in other lists). Attested Agrippa II.14; Davidson.'),
 ('ENT_ANGF_ADVACHIEL','Advachiel (Adnachiel, Sagittarius)','Angel','Angel','Renaissance Esoteric','zodiac: Sagittarius; fire','B','Angel governing Sagittarius in Agrippa''s Scale of Twelve; spelled Advachiel by Agrippa, commonly Adnachiel in later angelologies. Attested Agrippa II.14; Davidson.'),
 ('ENT_ANGF_HANAEL','Hanael (Capricorn)','Angel','Angel','Renaissance Esoteric','zodiac: Capricorn; earth','C','Angel governing Capricorn in Agrippa''s Scale of Twelve. HOMONYM: distinct from the archangel Haniel of Venus/Netzach (ENT_JM_HANIEL); the same name-stem is reused for a zodiacal governor here. Attested Agrippa II.14; Davidson.'),
 ('ENT_ANGF_CAMBIEL','Cambiel (Aquarius)','Angel','Angel','Renaissance Esoteric','zodiac: Aquarius; air','B','Angel governing Aquarius in Agrippa''s Scale of Twelve (also Cambriel). Attested Agrippa II.14; Davidson.'),
 ('ENT_ANGF_BARCHIEL','Barchiel (Pisces)','Angel','Angel','Renaissance Esoteric','zodiac: Pisces; water','B','Angel governing Pisces in Agrippa''s Scale of Twelve (also Barakiel/Barchiel). Attested Agrippa II.14; Davidson.');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'devotional',conf,'candidate_verified_name','Roster build via gen_roster.py (see CHANGELOG/git for release)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,etype text,note text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_ANGF_ZODIAC_12','SRC_AGRIPPA_OCCULTA','primary text attestation','attestation'),
 ('ENT_ANGF_MALCHIDAEL','SRC_AGRIPPA_OCCULTA','primary text attestation','attestation'),
 ('ENT_ANGF_ASMODEL','SRC_AGRIPPA_OCCULTA','primary text attestation','attestation'),
 ('ENT_ANGF_AMBRIEL','SRC_AGRIPPA_OCCULTA','primary text attestation','attestation'),
 ('ENT_ANGF_MURIEL','SRC_AGRIPPA_OCCULTA','primary text attestation','attestation'),
 ('ENT_ANGF_VERCHIEL','SRC_AGRIPPA_OCCULTA','primary text attestation','attestation'),
 ('ENT_ANGF_HAMALIEL','SRC_AGRIPPA_OCCULTA','primary text attestation','attestation'),
 ('ENT_ANGF_ZURIEL','SRC_AGRIPPA_OCCULTA','primary text attestation','attestation'),
 ('ENT_ANGF_BARBIEL','SRC_AGRIPPA_OCCULTA','primary text attestation','attestation'),
 ('ENT_ANGF_ADVACHIEL','SRC_AGRIPPA_OCCULTA','primary text attestation','attestation'),
 ('ENT_ANGF_HANAEL','SRC_AGRIPPA_OCCULTA','primary text attestation','attestation'),
 ('ENT_ANGF_CAMBIEL','SRC_AGRIPPA_OCCULTA','primary text attestation','attestation'),
 ('ENT_ANGF_BARCHIEL','SRC_AGRIPPA_OCCULTA','primary text attestation','attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_ANGF_ZODIAC_12','PER_RENAISSANCE','Closed, enumerable set of twelve angels governing the twelve signs of the zodiac per Agrippa, De occulta philosophia II.14 (the Scale of Twelve). A structural collective; member angels attested in Agrippa and catalogued by Davidson.'),
 ('ENT_ANGF_MALCHIDAEL','PER_RENAISSANCE','Angel governing Aries in Agrippa''s Scale of Twelve (also spelled Malahidael/Machidiel). Attested Agrippa II.14; Davidson, Dictionary of Angels.'),
 ('ENT_ANGF_ASMODEL','PER_RENAISSANCE','Angel governing Taurus in Agrippa''s Scale of Twelve. Attested Agrippa II.14; Davidson. Not to be confused with the demon Asmodeus.'),
 ('ENT_ANGF_AMBRIEL','PER_RENAISSANCE','Angel governing Gemini in Agrippa''s Scale of Twelve. Attested Agrippa II.14; Davidson.'),
 ('ENT_ANGF_MURIEL','PER_RENAISSANCE','Angel governing Cancer in Agrippa''s Scale of Twelve. Attested Agrippa II.14; Davidson.'),
 ('ENT_ANGF_VERCHIEL','PER_RENAISSANCE','Angel governing Leo in Agrippa''s Scale of Twelve (also Verachiel). Attested Agrippa II.14; Davidson.'),
 ('ENT_ANGF_HAMALIEL','PER_RENAISSANCE','Angel governing Virgo in Agrippa''s Scale of Twelve. Attested Agrippa II.14; Davidson.'),
 ('ENT_ANGF_ZURIEL','PER_RENAISSANCE','Angel governing Libra in Agrippa''s Scale of Twelve. Attested Agrippa II.14; Davidson.'),
 ('ENT_ANGF_BARBIEL','PER_RENAISSANCE','Angel governing Scorpio in Agrippa''s Scale of Twelve (also a name among the planetary/lunar mansions in other lists). Attested Agrippa II.14; Davidson.'),
 ('ENT_ANGF_ADVACHIEL','PER_RENAISSANCE','Angel governing Sagittarius in Agrippa''s Scale of Twelve; spelled Advachiel by Agrippa, commonly Adnachiel in later angelologies. Attested Agrippa II.14; Davidson.'),
 ('ENT_ANGF_HANAEL','PER_RENAISSANCE','Angel governing Capricorn in Agrippa''s Scale of Twelve. HOMONYM: distinct from the archangel Haniel of Venus/Netzach (ENT_JM_HANIEL); the same name-stem is reused for a zodiacal governor here. Attested Agrippa II.14; Davidson.'),
 ('ENT_ANGF_CAMBIEL','PER_RENAISSANCE','Angel governing Aquarius in Agrippa''s Scale of Twelve (also Cambriel). Attested Agrippa II.14; Davidson.'),
 ('ENT_ANGF_BARCHIEL','PER_RENAISSANCE','Angel governing Pisces in Agrippa''s Scale of Twelve (also Barakiel/Barchiel). Attested Agrippa II.14; Davidson.');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_ANGF_MALCHIDAEL','member_of','ENT_ANGF_ZODIAC_12','high','Malchidael is the Aries governor in Agrippa''s Scale of Twelve.'),
 ('ENT_ANGF_ASMODEL','member_of','ENT_ANGF_ZODIAC_12','high','Asmodel is the Taurus governor in Agrippa''s Scale of Twelve.'),
 ('ENT_ANGF_AMBRIEL','member_of','ENT_ANGF_ZODIAC_12','high','Ambriel is the Gemini governor in Agrippa''s Scale of Twelve.'),
 ('ENT_ANGF_MURIEL','member_of','ENT_ANGF_ZODIAC_12','high','Muriel is the Cancer governor in Agrippa''s Scale of Twelve.'),
 ('ENT_ANGF_VERCHIEL','member_of','ENT_ANGF_ZODIAC_12','high','Verchiel is the Leo governor in Agrippa''s Scale of Twelve.'),
 ('ENT_ANGF_HAMALIEL','member_of','ENT_ANGF_ZODIAC_12','high','Hamaliel is the Virgo governor in Agrippa''s Scale of Twelve.'),
 ('ENT_ANGF_ZURIEL','member_of','ENT_ANGF_ZODIAC_12','high','Zuriel is the Libra governor in Agrippa''s Scale of Twelve.'),
 ('ENT_ANGF_BARBIEL','member_of','ENT_ANGF_ZODIAC_12','high','Barbiel is the Scorpio governor in Agrippa''s Scale of Twelve.'),
 ('ENT_ANGF_ADVACHIEL','member_of','ENT_ANGF_ZODIAC_12','high','Advachiel/Adnachiel is the Sagittarius governor in Agrippa''s Scale of Twelve.'),
 ('ENT_ANGF_HANAEL','member_of','ENT_ANGF_ZODIAC_12','high','Hanael is the Capricorn governor in Agrippa''s Scale of Twelve.'),
 ('ENT_ANGF_CAMBIEL','member_of','ENT_ANGF_ZODIAC_12','high','Cambiel is the Aquarius governor in Agrippa''s Scale of Twelve.'),
 ('ENT_ANGF_BARCHIEL','member_of','ENT_ANGF_ZODIAC_12','high','Barchiel is the Pisces governor in Agrippa''s Scale of Twelve.'),
 ('ENT_ANGF_ZODIAC_12','aligned_with','ENT_AST_DECANS','medium','The twelve zodiacal angels (one per sign) parallel and subdivide into the thirty-six decans (three per sign); functional alignment of the two zodiacal angelic schemes.'),
 ('ENT_SAINT_MICHAEL_CHR','member_of','ENT_SOL_PLANETARY_ANGELS','high','Michael is the Sun angel in the seven-planet grimoire scheme; wires the existing archangel into the existing (previously member-less) Seven Planetary Angels collective.'),
 ('ENT_SAINT_GABRIEL_CHR','member_of','ENT_SOL_PLANETARY_ANGELS','high','Gabriel is the Moon angel in the seven-planet grimoire scheme; wires the existing archangel into the collective.'),
 ('ENT_SAINT_RAPHAEL_CHR','member_of','ENT_SOL_PLANETARY_ANGELS','high','Raphael is the Mercury angel in the seven-planet grimoire scheme; wires the existing archangel into the collective.'),
 ('ENT_SOL_ANAEL','member_of','ENT_SOL_PLANETARY_ANGELS','high','Anael is the Venus angel; completes membership of the previously empty Seven Planetary Angels collective.'),
 ('ENT_SOL_SAMAEL_MARS','member_of','ENT_SOL_PLANETARY_ANGELS','high','Samael is the Mars angel; completes membership of the collective.'),
 ('ENT_SOL_SACHIEL','member_of','ENT_SOL_PLANETARY_ANGELS','high','Sachiel is the Jupiter angel; completes membership of the collective.'),
 ('ENT_SOL_CASSIEL','member_of','ENT_SOL_PLANETARY_ANGELS','high','Cassiel is the Saturn angel; completes membership of the collective.'),
 ('ENT_SAINT_MICHAEL_CHR','presides_over','ENT_SUN','high','Adds the missing solar rulership: Michael governs the Sun in the planetary-angel scheme (Agrippa, Scale of Seven).'),
 ('ENT_SAINT_GABRIEL_CHR','presides_over','ENT_MOON','high','Adds the missing lunar rulership: Gabriel governs the Moon in the planetary-angel scheme (Agrippa, Scale of Seven).'),
 ('ENT_SOL_ANAEL','presides_over','ENT_VENUS','high','Anael governs Venus in the planetary-angel scheme; wires the existing Venus angel to the existing Venus planet-category entity.');

\echo '--- REJECTED edges (bad id/type, or subject lacks a source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
