-- build_bahai.sql  (GENERATED by gen_roster.py bahai) — v1.80.0
-- 13 entities, 28 edges, 1 new periods, 4 new sources. Idempotent + self-validating.
BEGIN;

INSERT INTO periods (period_id, period_name, start_year, end_year) VALUES
 ('PER_BAHAI','Bahá''í Era (Badí'')',1844,2025)
ON CONFLICT (period_id) DO NOTHING;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_SMITH_BAHAI','secondary scholarship','Peter Smith, An Introduction to the Bahá''í Faith (Cambridge University Press, 2008)','Authoritative scholarly survey of Bahá''í history, central figures, theology of progressive revelation, and administrative institutions.'),
 ('SRC_BAHAI_KITAB_AQDAS','primary text','Bahá''u''lláh, Kitáb-i-Aqdas (The Most Holy Book), Bahá''í World Centre edition','Central book of Bahá''í laws and covenant, including provisions establishing the Universal House of Justice.'),
 ('SRC_BAHAI_KITAB_IQAN','primary text','Bahá''u''lláh, Kitáb-i-Íqán (The Book of Certitude), Bahá''í World Centre edition','Doctrinal exposition of progressive revelation and the station of the Manifestations of God in relation to prior prophets.'),
 ('SRC_SHOGHI_GPB','primary text','Shoghi Effendi, God Passes By (Bahá''í Publishing Trust, 1944)','Authoritative Bahá''í history of the first Bahá''í century covering the Báb, Bahá''u''lláh, Abdu''l-Bahá and institutional development.')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,trad text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_BAH_MANIFESTATIONS','Manifestations of God (collective)','Collective/divine category','Collective','Bahá''í','progressive revelation; prophethood; divine mediation','B','Bahá''í doctrinal category (Mazhar-i-Iláhí) for the succession of supreme Messengers; serves as the cohort hub. Attested across Bahá''u''lláh''s Kitáb-i-Íqán and Smith (2008).'),
 ('ENT_BAH_MAZHAR','Manifestation of God (Mazhar)','Theological concept','Theological concept','Bahá''í','prophetology; divine mediation; revelation','B','Core Bahá''í concept: a perfect mirror reflecting divine attributes who founds a religious dispensation. Attested in Kitáb-i-Íqán; Smith (2008) ch. on theology.'),
 ('ENT_BAH_BAB','The Báb (Siyyid Alí-Muhammad Shírází)','Manifestation/Prophet-founder','Manifestation/Prophet-founder','Bahá''í','revelation; herald; martyrdom','B','1819-1850; herald-Manifestation who declared his mission in 1844 (start of the Bahá''í era) and prophesied ''Him Whom God shall make manifest.'' Historically attested; Smith (2008); Shoghi Effendi, God Passes By.'),
 ('ENT_BAH_BAHAULLAH','Bahá''u''lláh (Mírzá Husayn-Alí Núrí)','Manifestation/Prophet-founder','Manifestation/Prophet-founder','Bahá''í','revelation; covenant; central authority','B','1817-1892; central figure and founder of the Bahá''í Faith, ''Him Whom God shall make manifest,'' author of the Kitáb-i-Aqdas and Kitáb-i-Íqán. Historically attested; Smith (2008).'),
 ('ENT_BAH_ABDULBAHA','Abdu''l-Bahá (Abbás Effendi)','Authoritative interpreter/exemplar','Authoritative interpreter/exemplar','Bahá''í','interpretation; exemplar; covenant','B','1844-1921; eldest son of Bahá''u''lláh, appointed Centre of the Covenant and authorized interpreter; not regarded as a Manifestation. Historically attested; Smith (2008).'),
 ('ENT_BAH_SHOGHI','Shoghi Effendi (Shoghi Rabbání)','Guardian/authoritative interpreter','Guardian/authoritative interpreter','Bahá''í','guardianship; interpretation; administration','B','1897-1957; great-grandson of Bahá''u''lláh, Guardian of the Cause and authorized interpreter who built the administrative order. Historically attested; author of God Passes By.'),
 ('ENT_BAH_UHJ','Universal House of Justice','Institution','Institution','Bahá''í','governance; legislation; covenant','B','Supreme elected governing body of the Bahá''í Faith, ordained in the Kitáb-i-Aqdas and first elected 1963; seated in Haifa. Attested in primary scripture and Smith (2008).'),
 ('ENT_BAH_COVENANT','Covenant (Bahá''í)','Theological concept','Theological concept','Bahá''í','succession; authority; unity','B','Bahá''í concept of the binding chain of authority from Bahá''u''lláh through Abdu''l-Bahá, the Guardianship and the Universal House of Justice. Attested in Kitáb-i-Aqdas and Smith (2008).'),
 ('ENT_BAH_QUDDUS','Quddús (Mullá Muhammad-Alí Bárfurúshí)','Disciple/saint','Disciple/saint','Bahá''í','discipleship; martyrdom','C','d. 1849; foremost of the Báb''s Letters of the Living and leading figure at the Shaykh Tabarsí upheaval. Historically attested; Shoghi Effendi, God Passes By.'),
 ('ENT_BAH_TAHIRIH','Táhirih (Fátimih Baraghání, Qurratu''l-Ayn)','Disciple/saint','Disciple/saint','Bahá''í','discipleship; poetry; martyrdom; women''s emancipation','C','1817-1852; only woman among the Báb''s Letters of the Living, poet and reformer martyred for the Bábí cause. Historically attested; Smith (2008).'),
 ('ENT_BAH_LETTERS_LIVING','Letters of the Living (Hurúf-i-Hayy)','Collective/disciple body','Collective','Bahá''í','discipleship; early Bábí community','C','The eighteen first disciples who independently recognized the Báb, forming with him the first ''Unity.'' Attested in Shoghi Effendi, God Passes By.'),
 ('ENT_BAH_HANDS_CAUSE','Hands of the Cause of God','Institution/office','Institution/office','Bahá''í','propagation; protection of the Faith','C','Distinguished believers appointed to propagate and protect the Faith; functioned especially under Shoghi Effendi and after his passing. Attested in Smith (2008).'),
 ('ENT_BAH_BAYAN','Bayán (Báb''s revelation)','Scripture/concept','Scripture/concept','Bahá''í','scripture; messianic prophecy','C','Principal scriptural work of the Báb (Persian and Arabic Bayán) which abrogated Islamic law and foretold the coming Manifestation. Attested in Smith (2008).');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'devotional',conf,'candidate_verified_name','Roster build via gen_roster.py (see CHANGELOG/git for release)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,etype text,note text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_BAH_MANIFESTATIONS','SRC_SMITH_BAHAI','scholarly attestation','attestation'),
 ('ENT_BAH_MAZHAR','SRC_BAHAI_KITAB_IQAN','primary text attestation','attestation'),
 ('ENT_BAH_BAB','SRC_SMITH_BAHAI','scholarly attestation','attestation'),
 ('ENT_BAH_BAHAULLAH','SRC_SMITH_BAHAI','scholarly attestation','attestation'),
 ('ENT_BAH_ABDULBAHA','SRC_SMITH_BAHAI','scholarly attestation','attestation'),
 ('ENT_BAH_SHOGHI','SRC_SMITH_BAHAI','scholarly attestation','attestation'),
 ('ENT_BAH_UHJ','SRC_BAHAI_KITAB_AQDAS','primary text attestation','attestation'),
 ('ENT_BAH_COVENANT','SRC_BAHAI_KITAB_AQDAS','primary text attestation','attestation'),
 ('ENT_BAH_QUDDUS','SRC_SHOGHI_GPB','primary text attestation','attestation'),
 ('ENT_BAH_TAHIRIH','SRC_SMITH_BAHAI','scholarly attestation','attestation'),
 ('ENT_BAH_LETTERS_LIVING','SRC_SHOGHI_GPB','primary text attestation','attestation'),
 ('ENT_BAH_HANDS_CAUSE','SRC_SMITH_BAHAI','scholarly attestation','attestation'),
 ('ENT_BAH_BAYAN','SRC_SMITH_BAHAI','scholarly attestation','attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_BAH_MANIFESTATIONS','PER_BAHAI','Bahá''í doctrinal category (Mazhar-i-Iláhí) for the succession of supreme Messengers; serves as the cohort hub. Attested across Bahá''u''lláh''s Kitáb-i-Íqán and Smith (2008).'),
 ('ENT_BAH_MAZHAR','PER_BAHAI','Core Bahá''í concept: a perfect mirror reflecting divine attributes who founds a religious dispensation. Attested in Kitáb-i-Íqán; Smith (2008) ch. on theology.'),
 ('ENT_BAH_BAB','PER_BAHAI','1819-1850; herald-Manifestation who declared his mission in 1844 (start of the Bahá''í era) and prophesied ''Him Whom God shall make manifest.'' Historically attested; Smith (2008); Shoghi Effendi, God Passes By.'),
 ('ENT_BAH_BAHAULLAH','PER_BAHAI','1817-1892; central figure and founder of the Bahá''í Faith, ''Him Whom God shall make manifest,'' author of the Kitáb-i-Aqdas and Kitáb-i-Íqán. Historically attested; Smith (2008).'),
 ('ENT_BAH_ABDULBAHA','PER_BAHAI','1844-1921; eldest son of Bahá''u''lláh, appointed Centre of the Covenant and authorized interpreter; not regarded as a Manifestation. Historically attested; Smith (2008).'),
 ('ENT_BAH_SHOGHI','PER_BAHAI','1897-1957; great-grandson of Bahá''u''lláh, Guardian of the Cause and authorized interpreter who built the administrative order. Historically attested; author of God Passes By.'),
 ('ENT_BAH_UHJ','PER_BAHAI','Supreme elected governing body of the Bahá''í Faith, ordained in the Kitáb-i-Aqdas and first elected 1963; seated in Haifa. Attested in primary scripture and Smith (2008).'),
 ('ENT_BAH_COVENANT','PER_BAHAI','Bahá''í concept of the binding chain of authority from Bahá''u''lláh through Abdu''l-Bahá, the Guardianship and the Universal House of Justice. Attested in Kitáb-i-Aqdas and Smith (2008).'),
 ('ENT_BAH_QUDDUS','PER_BAHAI','d. 1849; foremost of the Báb''s Letters of the Living and leading figure at the Shaykh Tabarsí upheaval. Historically attested; Shoghi Effendi, God Passes By.'),
 ('ENT_BAH_TAHIRIH','PER_BAHAI','1817-1852; only woman among the Báb''s Letters of the Living, poet and reformer martyred for the Bábí cause. Historically attested; Smith (2008).'),
 ('ENT_BAH_LETTERS_LIVING','PER_BAHAI','The eighteen first disciples who independently recognized the Báb, forming with him the first ''Unity.'' Attested in Shoghi Effendi, God Passes By.'),
 ('ENT_BAH_HANDS_CAUSE','PER_BAHAI','Distinguished believers appointed to propagate and protect the Faith; functioned especially under Shoghi Effendi and after his passing. Attested in Smith (2008).'),
 ('ENT_BAH_BAYAN','PER_BAHAI','Principal scriptural work of the Báb (Persian and Arabic Bayán) which abrogated Islamic law and foretold the coming Manifestation. Attested in Smith (2008).');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_BAH_MAZHAR','member_of','ENT_BAH_MANIFESTATIONS','high','The concept of the Manifestation of God defines the membership category that the collective hub gathers.'),
 ('ENT_BAH_BAB','member_of','ENT_BAH_MANIFESTATIONS','high','The Báb is regarded in Bahá''í doctrine as an independent Manifestation of God.'),
 ('ENT_BAH_BAHAULLAH','member_of','ENT_BAH_MANIFESTATIONS','high','Bahá''u''lláh is the central Manifestation of God of the present dispensation.'),
 ('ENT_BAH_BAB','embodies','ENT_BAH_MAZHAR','high','The Báb is an instance of the Mazhar (Manifestation of God) category in Bahá''í prophetology.'),
 ('ENT_BAH_BAHAULLAH','embodies','ENT_BAH_MAZHAR','high','Bahá''u''lláh is the supreme exemplar of the Mazhar category for this age.'),
 ('ENT_BAH_BAB','reveals','ENT_BAH_BAYAN','high','The Báb is the author/revealer of the Bayán.'),
 ('ENT_BAH_BAYAN','revealed_by','ENT_BAH_BAB','high','The Bayán is the scriptural corpus revealed through the Báb (inverse of the reveals edge; replaces an incorrect reception_of).'),
 ('ENT_BAH_QUDDUS','member_of','ENT_BAH_LETTERS_LIVING','high','Quddús was the eighteenth and foremost of the Letters of the Living.'),
 ('ENT_BAH_TAHIRIH','member_of','ENT_BAH_LETTERS_LIVING','high','Táhirih was the only woman among the Letters of the Living.'),
 ('ENT_BAH_QUDDUS','associated_with','ENT_BAH_BAB','high','Quddús was a leading disciple of the Báb.'),
 ('ENT_BAH_TAHIRIH','associated_with','ENT_BAH_BAB','high','Táhirih was an early recognizer and disciple of the Báb.'),
 ('ENT_BAH_ABDULBAHA','child_of','ENT_BAH_BAHAULLAH','high','Abdu''l-Bahá was the eldest son of Bahá''u''lláh.'),
 ('ENT_BAH_BAHAULLAH','parent_of','ENT_BAH_ABDULBAHA','high','Bahá''u''lláh was the father of Abdu''l-Bahá.'),
 ('ENT_BAH_ABDULBAHA','associated_with','ENT_BAH_COVENANT','high','Abdu''l-Bahá was appointed Centre of the Covenant by Bahá''u''lláh.'),
 ('ENT_BAH_SHOGHI','associated_with','ENT_BAH_COVENANT','high','Shoghi Effendi was appointed Guardian and authorized interpreter within the line of the Covenant.'),
 ('ENT_BAH_SHOGHI','associated_with','ENT_BAH_ABDULBAHA','high','Shoghi Effendi was appointed Guardian by Abdu''l-Bahá''s Will and Testament.'),
 ('ENT_BAH_COVENANT','emanates_from','ENT_BAH_BAHAULLAH','high','The Bahá''í Covenant derives its authority from Bahá''u''lláh''s appointment of successors (replaces an incorrect reception_of).'),
 ('ENT_BAH_UHJ','associated_with','ENT_BAH_BAHAULLAH','high','The Universal House of Justice was ordained by Bahá''u''lláh in the Kitáb-i-Aqdas (replaces an incorrect reception_of).'),
 ('ENT_BAH_UHJ','associated_with','ENT_BAH_COVENANT','high','The Universal House of Justice is the institution charged with the Covenant after the Guardianship.'),
 ('ENT_BAH_HANDS_CAUSE','associated_with','ENT_BAH_SHOGHI','medium','The Hands of the Cause functioned prominently under Shoghi Effendi''s guidance.'),
 ('ENT_BAH_BAHAULLAH','reception_of','ENT_BAH_BAB','high','Bahá''u''lláh is identified by Bahá''ís as the fulfillment of the Báb''s prophecy of ''Him Whom God shall make manifest.'''),
 ('ENT_BAH_BAHAULLAH','reception_of','ENT_ISR_ABRAHAM','high','Bahá''í progressive revelation regards Bahá''u''lláh''s dispensation as renewing the religion of prior Manifestations including Abraham.'),
 ('ENT_BAH_BAHAULLAH','reception_of','ENT_ISR_MOSES','high','Bahá''í doctrine treats Moses as a prior Manifestation whose revelation is fulfilled in Bahá''u''lláh''s.'),
 ('ENT_BAH_BAHAULLAH','reception_of','ENT_JESUS_CHRIST','high','Bahá''ís regard Jesus as a Manifestation of God whose return is realized spiritually in Bahá''u''lláh''s revelation.'),
 ('ENT_BAH_BAHAULLAH','reception_of','ENT_ISL_MUHAMMAD','high','Bahá''í teaching honors Muhammad as a Manifestation of God preceding Bahá''u''lláh in the prophetic chain.'),
 ('ENT_BAH_BAHAULLAH','reception_of','ENT_ZOR_ZARATHUSTRA','high','Bahá''í progressive revelation counts Zoroaster among the prior Manifestations of God.'),
 ('ENT_BAH_BAB','aligned_with','ENT_ISL_MAHDI','medium','Bahá''ís hold the Báb fulfilled Shi''i expectation of the return of the Hidden Imam (Mahdi); functional/eschatological alignment, not identity.'),
 ('ENT_BAH_MANIFESTATIONS','associated_with','ENT_BAH_MAZHAR','high','The collective of Manifestations is constituted by the Mazhar prophetological concept.');

\echo '--- REJECTED edges (bad id/type, or subject lacks a source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
