-- build_p7_folk_catholic.sql  (GENERATED by gen_roster.py p7_folk_catholic) — v1.80.0
-- 9 entities, 18 edges, 1 new periods, 2 new sources. Idempotent + self-validating.
BEGIN;

INSERT INTO periods (period_id, period_name, start_year, end_year) VALUES
 ('PER_FOLK_CATHOLIC','Modern Latin American Folk Catholicism',1900,2025)
ON CONFLICT (period_id) DO NOTHING;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_CHESNUT_DEVOTED_DEATH','secondary scholarship','R. Andrew Chesnut, Devoted to Death: Santa Muerte, the Skeleton Saint (Oxford University Press, 2012; rev. 2017)','Santa Muerte and the comparative cult of personified Death; Latin American folk sanctity'),
 ('SRC_GRAZIANO_CULTURES_DEVOTION','secondary scholarship','Frank Graziano, Cultures of Devotion: Folk Saints of Spanish America (Oxford University Press, 2007)','Unofficial folk saints of Spanish America: Difunta Correa, San La Muerte, Niño Fidencio, Sarita Colonia, and others')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,trad text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_FCS_FOLK_SAINTS','Latin American Folk Saints','Saint collective','collective','Folk Catholic','Vernacular sanctity, popular canonization, miraculous intercession','B','Hub for the folk-canonized (popular, Rome-unrecognized) intercessory figures of modern Latin American vernacular Catholicism; well attested ethnographically.'),
 ('ENT_FCS_SANTA_MUERTE','Santa Muerte','Folk saint','folk_saint','Folk Catholic','Death personified, protection, healing, justice, love, devotion of the marginalized','B','Mexican folk ''saint'' (Holy Death), a skeletal female personification of death venerated since at least the mid-20th c. with mass public shrines (Tepito); not recognized by Rome; imagery descends from the personified Grim Reaper / Death.'),
 ('ENT_FCS_SAN_LA_MUERTE','San La Muerte','Folk saint','folk_saint','Folk Catholic','Death personified, protection, oaths, sudden help','B','Argentine/Paraguayan/Guaraní-zone male folk saint of personified Death (skeletal figure); publicly venerated in the Litoral region; Rome-unrecognized; cognate of the broader Death-saint devotion.'),
 ('ENT_FCS_MAXIMON','Maximón (San Simón)','Folk saint','folk_saint','Folk Catholic','Fortune, fertility, protection, intercession, bargains and vows, Maya-Catholic intercession','B','Guatemalan Maya-Catholic syncretic figure of the highlands (esp. Santiago Atitlán, San Andrés Itzapa), publicly identified with St. Simon and an Indigenous Maya ancestral/Mam figure; an effigy receives offerings of tobacco and liquor. Only the public devotion is modeled.'),
 ('ENT_FCS_JESUS_MALVERDE','Jesús Malverde','Folk saint','folk_saint','Folk Catholic','Protection of the poor and travelers, intercession, popular justice','C','Sinaloan (Mexico) folk saint, said to be an early-20th-c. bandit-benefactor executed c.1909; venerated at a Culiacán chapel; not recognized by Rome. Modeled neutrally as a publicly attested devotion.'),
 ('ENT_FCS_NINO_FIDENCIO','Niño Fidencio','Folk saint','folk_saint','Folk Catholic','Healing, spirit mediumship, popular intercession','B','José Fidencio Constantino Síntora (1898–1938), a celebrated curandero of Espinazo, Nuevo León (Mexico); posthumously venerated as a folk healer-saint with a living devotional movement (fidencistas); Rome-unrecognized.'),
 ('ENT_FCS_SARITA_COLONIA','Sarita Colonia','Folk saint','folk_saint','Folk Catholic','Protection of migrants, the poor and the marginalized, intercession','B','Sara Colonia Zambrano (1914–1940), a poor migrant woman in Callao, Peru; posthumously venerated as a folk saint of the urban marginalized; Rome-unrecognized.'),
 ('ENT_FCS_DIFUNTA_CORREA','Difunta Correa','Folk saint','folk_saint','Folk Catholic','Protection of travelers and the desperate, miraculous nourishment, intercession','B','Argentine folk saint (Deolinda Correa), a 19th-c. woman said to have died of thirst in the San Juan desert while her nursing infant survived; major roadside shrine at Vallecito; Rome-unrecognized.'),
 ('ENT_FCS_SAN_PASCUALITO','San Pascualito','Folk saint','folk_saint','Folk Catholic','Death personified, healing, protection from epidemic, intercession','C','Guatemalan/Chiapas Maya-Catholic skeletal folk saint of Death, publicly associated by name with the canonical St. Paschal Baylón but venerated as a personified-Death figure; centered at Olintepeque and Chiapas; Rome-unrecognized in this form.');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'devotional',conf,'candidate_verified_name','Roster build via gen_roster.py (see CHANGELOG/git for release)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,etype text,note text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_FCS_FOLK_SAINTS','SRC_GRAZIANO_CULTURES_DEVOTION','scholarly attestation','attestation'),
 ('ENT_FCS_SANTA_MUERTE','SRC_CHESNUT_DEVOTED_DEATH','scholarly attestation','attestation'),
 ('ENT_FCS_SAN_LA_MUERTE','SRC_GRAZIANO_CULTURES_DEVOTION','scholarly attestation','attestation'),
 ('ENT_FCS_MAXIMON','SRC_GRAZIANO_CULTURES_DEVOTION','scholarly attestation','attestation'),
 ('ENT_FCS_JESUS_MALVERDE','SRC_GRAZIANO_CULTURES_DEVOTION','scholarly attestation','attestation'),
 ('ENT_FCS_NINO_FIDENCIO','SRC_GRAZIANO_CULTURES_DEVOTION','scholarly attestation','attestation'),
 ('ENT_FCS_SARITA_COLONIA','SRC_GRAZIANO_CULTURES_DEVOTION','scholarly attestation','attestation'),
 ('ENT_FCS_DIFUNTA_CORREA','SRC_GRAZIANO_CULTURES_DEVOTION','scholarly attestation','attestation'),
 ('ENT_FCS_SAN_PASCUALITO','SRC_GRAZIANO_CULTURES_DEVOTION','scholarly attestation','attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_FCS_FOLK_SAINTS','PER_FOLK_CATHOLIC','Hub for the folk-canonized (popular, Rome-unrecognized) intercessory figures of modern Latin American vernacular Catholicism; well attested ethnographically.'),
 ('ENT_FCS_SANTA_MUERTE','PER_FOLK_CATHOLIC','Mexican folk ''saint'' (Holy Death), a skeletal female personification of death venerated since at least the mid-20th c. with mass public shrines (Tepito); not recognized by Rome; imagery descends from the personified Grim Reaper / Death.'),
 ('ENT_FCS_SAN_LA_MUERTE','PER_FOLK_CATHOLIC','Argentine/Paraguayan/Guaraní-zone male folk saint of personified Death (skeletal figure); publicly venerated in the Litoral region; Rome-unrecognized; cognate of the broader Death-saint devotion.'),
 ('ENT_FCS_MAXIMON','PER_FOLK_CATHOLIC','Guatemalan Maya-Catholic syncretic figure of the highlands (esp. Santiago Atitlán, San Andrés Itzapa), publicly identified with St. Simon and an Indigenous Maya ancestral/Mam figure; an effigy receives offerings of tobacco and liquor. Only the public devotion is modeled.'),
 ('ENT_FCS_JESUS_MALVERDE','PER_FOLK_CATHOLIC','Sinaloan (Mexico) folk saint, said to be an early-20th-c. bandit-benefactor executed c.1909; venerated at a Culiacán chapel; not recognized by Rome. Modeled neutrally as a publicly attested devotion.'),
 ('ENT_FCS_NINO_FIDENCIO','PER_FOLK_CATHOLIC','José Fidencio Constantino Síntora (1898–1938), a celebrated curandero of Espinazo, Nuevo León (Mexico); posthumously venerated as a folk healer-saint with a living devotional movement (fidencistas); Rome-unrecognized.'),
 ('ENT_FCS_SARITA_COLONIA','PER_FOLK_CATHOLIC','Sara Colonia Zambrano (1914–1940), a poor migrant woman in Callao, Peru; posthumously venerated as a folk saint of the urban marginalized; Rome-unrecognized.'),
 ('ENT_FCS_DIFUNTA_CORREA','PER_FOLK_CATHOLIC','Argentine folk saint (Deolinda Correa), a 19th-c. woman said to have died of thirst in the San Juan desert while her nursing infant survived; major roadside shrine at Vallecito; Rome-unrecognized.'),
 ('ENT_FCS_SAN_PASCUALITO','PER_FOLK_CATHOLIC','Guatemalan/Chiapas Maya-Catholic skeletal folk saint of Death, publicly associated by name with the canonical St. Paschal Baylón but venerated as a personified-Death figure; centered at Olintepeque and Chiapas; Rome-unrecognized in this form.');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_FCS_SANTA_MUERTE','member_of','ENT_FCS_FOLK_SAINTS','high','Santa Muerte is the most widely venerated of the Latin American folk saints (Chesnut).'),
 ('ENT_FCS_SAN_LA_MUERTE','member_of','ENT_FCS_FOLK_SAINTS','high','San La Muerte is a folk-canonized intercessory figure of the Litoral region (Graziano).'),
 ('ENT_FCS_MAXIMON','member_of','ENT_FCS_FOLK_SAINTS','high','Maximón/San Simón is a publicly venerated Guatemalan folk saint.'),
 ('ENT_FCS_JESUS_MALVERDE','member_of','ENT_FCS_FOLK_SAINTS','high','Jesús Malverde is a Sinaloan folk saint (Graziano).'),
 ('ENT_FCS_NINO_FIDENCIO','member_of','ENT_FCS_FOLK_SAINTS','high','Niño Fidencio heads a living folk-saint devotion (fidencismo).'),
 ('ENT_FCS_SARITA_COLONIA','member_of','ENT_FCS_FOLK_SAINTS','high','Sarita Colonia is a Peruvian folk saint of the marginalized (Graziano).'),
 ('ENT_FCS_DIFUNTA_CORREA','member_of','ENT_FCS_FOLK_SAINTS','high','Difunta Correa is a major Argentine folk saint (Graziano).'),
 ('ENT_FCS_SAN_PASCUALITO','member_of','ENT_FCS_FOLK_SAINTS','high','San Pascualito is a Guatemalan/Chiapas folk saint of Death.'),
 ('ENT_FCS_SANTA_MUERTE','reception_of','ENT_DEATH','high','Santa Muerte''s skeletal scythe-bearing iconography is a devotional reception of personified Death / the Grim Reaper (Chesnut, Devoted to Death).'),
 ('ENT_FCS_SAN_LA_MUERTE','reception_of','ENT_DEATH','high','San La Muerte is likewise a personification of Death received as a folk saint (Graziano).'),
 ('ENT_FCS_SAN_PASCUALITO','reception_of','ENT_DEATH','medium','San Pascualito is venerated as a skeletal personification of Death in Maya-Catholic devotion.'),
 ('ENT_FCS_SAN_LA_MUERTE','aligned_with','ENT_FCS_SANTA_MUERTE','medium','San La Muerte (Southern Cone) and Santa Muerte (Mexico) are cognate folk personifications of Death venerated as saints (Chesnut).'),
 ('ENT_FCS_MAXIMON','syncretized_with','ENT_NT_SIMON_ZEALOT','medium','Maximón is publicly identified as ''San Simón,'' overlaying the apostle Simon onto a Maya ancestral figure (Graziano); only the public identification is modeled.'),
 ('ENT_FCS_JESUS_MALVERDE','aligned_with','ENT_JESUS_CHRIST','low','Devotees liken Malverde''s protective benefaction to a Christ-like ''generous bandit'' figure; the popular name evokes Jesus, though no formal identification exists (Graziano).'),
 ('ENT_FCS_NINO_FIDENCIO','aligned_with','ENT_JESUS_CHRIST','low','Fidencista devotion publicly frames Niño Fidencio''s healing ministry in imitatio Christi terms (Graziano).'),
 ('ENT_FCS_SARITA_COLONIA','aligned_with','ENT_SAINT_MARY','low','Sarita Colonia''s public cult casts her as a compassionate maternal intercessor for the marginalized, modeled on Marian devotion (Graziano).'),
 ('ENT_FCS_DIFUNTA_CORREA','aligned_with','ENT_SAINT_MARY','low','The Difunta Correa devotion centers on the miraculously nursing mother, drawing on Marian maternal-intercessor imagery (Graziano).'),
 ('ENT_FCS_FOLK_SAINTS','reception_of','ENT_SAINT_MARY','medium','Latin American folk sanctity adapts the Catholic cult of the saints and Marian intercession into vernacular, locally canonized figures (Graziano).');

\echo '--- REJECTED edges (bad id/type, or subject lacks a source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
