-- build_p5_masonic_rosicrucian.sql  (GENERATED by gen_roster.py p5_masonic_rosicrucian) — v1.80.0
-- 9 entities, 14 edges, 1 new periods, 2 new sources. Idempotent + self-validating.
BEGIN;

INSERT INTO periods (period_id, period_name, start_year, end_year) VALUES
 ('PER_MASONIC','Masonic / Rosicrucian Era (manifestos and speculative lodges to present)',1600,2025)
ON CONFLICT (period_id) DO NOTHING;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_YATES_ROSICRUCIAN','secondary scholarship','Frances A. Yates, The Rosicrucian Enlightenment (1972)','Rosicrucian manifestos, Christian Rosenkreutz legend, the Invisible College, and early-modern Hermetic-esoteric reform.'),
 ('SRC_MACKEY_FREEMASONRY','secondary scholarship','Albert G. Mackey, An Encyclopaedia of Freemasonry and Its Kindred Sciences (1874; rev. eds.)','Masonic symbolism, ritual, and legend: G.A.O.T.U., Hiram Abiff, the pillars Jachin and Boaz, and the Royal Arch word Jahbulon.')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,trad text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_MAS_LODGE','The Masonic Lodge (Craft Freemasonry)','tradition_hub','Institution','Masonic/Rosicrucian','fraternity; initiation; moral allegory','B','Hub for organized speculative Freemasonry, a globally practiced fraternal-initiatic system (Grand Lodge of England 1717 onward) whose ritual symbolism is the attestation base for these entities.'),
 ('ENT_MAS_ROSICRUCIAN','The Brotherhood of the Rosy Cross (Rosicrucianism)','tradition_hub','Institution','Masonic/Rosicrucian','Hermetic-Christian esotericism; reform; healing','B','Hub for Rosicrucianism, an esoteric current launched by the early-17th-c. manifestos and continued by practicing modern orders (AMORC, SRIA, Rosicrucian Fellowship).'),
 ('ENT_MAS_GAOTU','The Great Architect of the Universe (G.A.O.T.U.)','Cosmic builder','Deity','Masonic/Rosicrucian','creation; divine craftsmanship; cosmic order','B','Non-sectarian name of God required of Masonic candidates and invoked in lodge ritual; a deity sincerely affirmed (in varied confessional terms) by practicing Freemasons worldwide.'),
 ('ENT_MAS_HIRAM_ABIFF','Hiram Abiff','Legendary figure','Legendary figure','Masonic/Rosicrucian','master-craft; fidelity; death and raising','B','The murdered master-builder of Solomon''s Temple in the Masonic Hiramic legend, ritually personified by the candidate in the Third Degree of practiced Craft Masonry.'),
 ('ENT_MAS_JACHIN','Jachin (the pillar)','Cult object','Sacred object','Masonic/Rosicrucian','establishment; threshold; temple symbolism','B','Personified right-hand pillar of Solomon''s porch in Masonic ritual symbolism (lecture of the Fellow Craft); a working ritual symbol, not the biblical priest. Homonym/parallel to scriptural pillar named in 1 Kings 7.'),
 ('ENT_MAS_BOAZ','Boaz (the pillar)','Cult object','Sacred object','Masonic/Rosicrucian','strength; threshold; temple symbolism','B','Personified left-hand pillar of Solomon''s porch in Masonic ritual symbolism. HOMONYM: distinct from the biblical Boaz (ancestor of David), entity ENT_ISR_BOAZ; this is the Temple pillar of 1 Kings 7 as used in lodge symbolism.'),
 ('ENT_MAS_JAHBULON','Jahbulon','Divine name/principle','Divine name/principle','Masonic/Rosicrucian','ineffable name; Royal Arch mystery','C','Composite sacred word disclosed in older Royal Arch Masonic ritual, traditionally parsed as conjoined divine names; a ritually-used (and controversy-attended) name within practiced Royal Arch Masonry, modeled neutrally.'),
 ('ENT_MAS_CHRISTIAN_ROSENKREUTZ','Christian Rosenkreutz','Legendary figure','Legendary figure','Masonic/Rosicrucian','founder-sage; Hermetic wisdom; hidden adeptship','B','Legendary founder of the Rosicrucian brotherhood narrated in the Fama and Chymical Wedding; revered as an archetypal adept within practicing Rosicrucian orders.'),
 ('ENT_MAS_INVISIBLE_COLLEGE','The Invisible College','Initiate order','Collective','Masonic/Rosicrucian','hidden fellowship of adepts; reform; healing','B','The unseen confraternity of Rosicrucian adepts proclaimed in the manifestos; a believed-in body of hidden masters within Rosicrucian practice and a template for later occult orders. Distinct from the Rosicrucian tradition-hub (ENT_MAS_ROSICRUCIAN) — this is the body of adepts itself.');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'devotional',conf,'candidate_verified_name','Roster build via gen_roster.py (see CHANGELOG/git for release)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,etype text,note text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_MAS_LODGE','SRC_MACKEY_FREEMASONRY','scholarly attestation','attestation'),
 ('ENT_MAS_ROSICRUCIAN','SRC_YATES_ROSICRUCIAN','scholarly attestation','attestation'),
 ('ENT_MAS_GAOTU','SRC_MACKEY_FREEMASONRY','scholarly attestation','attestation'),
 ('ENT_MAS_HIRAM_ABIFF','SRC_MACKEY_FREEMASONRY','scholarly attestation','attestation'),
 ('ENT_MAS_JACHIN','SRC_MACKEY_FREEMASONRY','scholarly attestation','attestation'),
 ('ENT_MAS_BOAZ','SRC_MACKEY_FREEMASONRY','scholarly attestation','attestation'),
 ('ENT_MAS_JAHBULON','SRC_MACKEY_FREEMASONRY','scholarly attestation','attestation'),
 ('ENT_MAS_CHRISTIAN_ROSENKREUTZ','SRC_YATES_ROSICRUCIAN','scholarly attestation','attestation'),
 ('ENT_MAS_INVISIBLE_COLLEGE','SRC_YATES_ROSICRUCIAN','scholarly attestation','attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_MAS_LODGE','PER_MASONIC','Hub for organized speculative Freemasonry, a globally practiced fraternal-initiatic system (Grand Lodge of England 1717 onward) whose ritual symbolism is the attestation base for these entities.'),
 ('ENT_MAS_ROSICRUCIAN','PER_MASONIC','Hub for Rosicrucianism, an esoteric current launched by the early-17th-c. manifestos and continued by practicing modern orders (AMORC, SRIA, Rosicrucian Fellowship).'),
 ('ENT_MAS_GAOTU','PER_MASONIC','Non-sectarian name of God required of Masonic candidates and invoked in lodge ritual; a deity sincerely affirmed (in varied confessional terms) by practicing Freemasons worldwide.'),
 ('ENT_MAS_HIRAM_ABIFF','PER_MASONIC','The murdered master-builder of Solomon''s Temple in the Masonic Hiramic legend, ritually personified by the candidate in the Third Degree of practiced Craft Masonry.'),
 ('ENT_MAS_JACHIN','PER_MASONIC','Personified right-hand pillar of Solomon''s porch in Masonic ritual symbolism (lecture of the Fellow Craft); a working ritual symbol, not the biblical priest. Homonym/parallel to scriptural pillar named in 1 Kings 7.'),
 ('ENT_MAS_BOAZ','PER_MASONIC','Personified left-hand pillar of Solomon''s porch in Masonic ritual symbolism. HOMONYM: distinct from the biblical Boaz (ancestor of David), entity ENT_ISR_BOAZ; this is the Temple pillar of 1 Kings 7 as used in lodge symbolism.'),
 ('ENT_MAS_JAHBULON','PER_MASONIC','Composite sacred word disclosed in older Royal Arch Masonic ritual, traditionally parsed as conjoined divine names; a ritually-used (and controversy-attended) name within practiced Royal Arch Masonry, modeled neutrally.'),
 ('ENT_MAS_CHRISTIAN_ROSENKREUTZ','PER_MASONIC','Legendary founder of the Rosicrucian brotherhood narrated in the Fama and Chymical Wedding; revered as an archetypal adept within practicing Rosicrucian orders.'),
 ('ENT_MAS_INVISIBLE_COLLEGE','PER_MASONIC','The unseen confraternity of Rosicrucian adepts proclaimed in the manifestos; a believed-in body of hidden masters within Rosicrucian practice and a template for later occult orders. Distinct from the Rosicrucian tradition-hub (ENT_MAS_ROSICRUCIAN) — this is the body of adepts itself.');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_MAS_GAOTU','member_of','ENT_MAS_LODGE','high','G.A.O.T.U. is the deity invoked in Craft Masonic ritual; anchors to the lodge hub.'),
 ('ENT_MAS_HIRAM_ABIFF','member_of','ENT_MAS_LODGE','high','Hiram Abiff is the central legendary figure of Craft Masonry''s Third Degree.'),
 ('ENT_MAS_JACHIN','member_of','ENT_MAS_LODGE','high','The pillar Jachin is a core symbolic object of the Masonic lodge.'),
 ('ENT_MAS_BOAZ','member_of','ENT_MAS_LODGE','high','The pillar Boaz is a core symbolic object of the Masonic lodge.'),
 ('ENT_MAS_JAHBULON','member_of','ENT_MAS_LODGE','medium','Jahbulon belongs to Royal Arch Masonry, a continuation of the Craft lodge system.'),
 ('ENT_MAS_CHRISTIAN_ROSENKREUTZ','member_of','ENT_MAS_ROSICRUCIAN','high','Christian Rosenkreutz is the legendary founder of the Rosicrucian brotherhood hub.'),
 ('ENT_MAS_INVISIBLE_COLLEGE','member_of','ENT_MAS_ROSICRUCIAN','high','The Invisible College is the brotherhood organ of the Rosicrucian current.'),
 ('ENT_MAS_INVISIBLE_COLLEGE','associated_with','ENT_MAS_CHRISTIAN_ROSENKREUTZ','high','The manifestos present the Brotherhood of the Rosy Cross as founded by and centered on Christian Rosenkreutz.'),
 ('ENT_MAS_JACHIN','paired_with','ENT_MAS_BOAZ','high','Jachin and Boaz are the inseparable twin pillars of Solomon''s porch in Masonic symbolism.'),
 ('ENT_MAS_HIRAM_ABIFF','associated_with','ENT_ISR_SOLOMON','high','The Hiramic legend casts Hiram Abiff as master-builder of King Solomon''s Temple.'),
 ('ENT_MAS_JACHIN','associated_with','ENT_ISR_SOLOMON','medium','The pillars Jachin and Boaz stood at the porch of Solomon''s Temple in the legend the lodge draws on.'),
 ('ENT_MAS_GAOTU','reception_of','ENT_HER_DEMIURGE','medium','The Masonic image of God as cosmic Architect/Craftsman receives the Hermetic-Platonic demiurgic-craftsman conception of the divine maker.'),
 ('ENT_MAS_ROSICRUCIAN','reception_of','ENT_HER_TRISMEGISTUS','high','Rosicrucianism is heavily Hermetic, taking up the prisca theologia of Hermes Trismegistus as a wisdom source.'),
 ('ENT_MAS_INVISIBLE_COLLEGE','aligned_with','ENT_MOD_SECRET_CHIEFS','medium','The Rosicrucian hidden brotherhood of adepts is the prototype later occult orders developed into the doctrine of unseen Secret Chiefs.');

\echo '--- REJECTED edges (bad id/type, or subject lacks a source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
