-- build_modern_orthodox.sql  (GENERATED by gen_roster.py modern_orthodox) — v1.80.0
-- 22 entities, 38 edges, 1 new periods, 0 new sources. Idempotent + self-validating.
BEGIN;

INSERT INTO periods (period_id, period_name, start_year, end_year) VALUES
 ('PER_MODERN_ORTHODOX','Modern Eastern Orthodoxy (19th-21st c.)',1800,2025)
ON CONFLICT (period_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,trad text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_ORTH_ATHONITE_ELDERS','The Modern Athonite Elders','Collective','Elder (Geron) hub','Christian/Orthodox','Hesychasm; monastic eldership; the Jesus Prayer','A','Hub for the modern Athonite startsy / gerontes (Mount Athos): Silouan, Joseph the Hesychast, Paisios, Porphyrios, who renewed hesychast prayer and spiritual fatherhood in the 20th c.'),
 ('ENT_ORTH_ROYAL_MARTYRS','The Royal Martyrs (Romanov Passion-Bearers)','Collective','New Martyr / passion-bearer hub','Christian/Orthodox','Passion-bearing; new-martyrdom of the Russian Revolution','A','Collective hub for Tsar Nicholas II and his family, glorified in 2000 by the Moscow Patriarchate as passion-bearers (strastoterptsy) following their 1918 execution at Yekaterinburg.'),
 ('ENT_ORTH_NIKODEMOS_HAGIORITE','Nikodemos the Hagiorite','Saint','Hesychast / compiler','Christian/Orthodox','Hesychasm; spiritual anthology; canon law','A','Athonite monk (1749-1809), co-compiler of the Philokalia with Macarius of Corinth; foundational figure of the modern hesychast revival. Glorified 1955.'),
 ('ENT_ORTH_IGNATIUS_BRIANCHANINOV','Ignatius Brianchaninov','Saint','Hierarch / ascetic writer','Christian/Orthodox','Asceticism; the Jesus Prayer; patristic spirituality','A','Russian bishop (1807-1867), author of The Arena and On the Prayer of Jesus; major modern systematizer of patristic ascetic teaching. Glorified 1988.'),
 ('ENT_ORTH_THEOPHAN_RECLUSE','Theophan the Recluse','Saint','Hierarch / spiritual writer','Christian/Orthodox','Prayer of the heart; spiritual direction; Philokalic translation','A','Russian bishop (1815-1894) who retired into reclusion; translated the Philokalia into Russian (Dobrotolyubie) and wrote extensively on unceasing prayer. Glorified 1988.'),
 ('ENT_ORTH_JOHN_KRONSTADT','John of Kronstadt','Saint','Wonderworker / pastor','Christian/Orthodox','Pastoral ministry; the Eucharist; healing; charity','A','Russian parish priest (1829-1908), famed wonderworker and author of My Life in Christ; renowned for frequent communion and miracles of healing. Glorified 1990.'),
 ('ENT_ORTH_NECTARIOS_AEGINA','Nektarios of Aegina','Saint','Hierarch / wonderworker','Christian/Orthodox','Healing; humility under slander; monastic founding','A','Greek bishop (1846-1920), Metropolitan of Pentapolis, founder of the convent on Aegina; one of the most popular modern Greek wonderworkers and healers. Glorified 1961.'),
 ('ENT_ORTH_SILOUAN_ATHONITE','Silouan the Athonite','Saint','Hesychast / Elder (Geron)','Christian/Orthodox','Hesychasm; the Jesus Prayer; love of enemies; ''Keep your mind in hell''','A','Russian monk of St Panteleimon''s Monastery on Athos (1866-1938); his life and teaching were transmitted by his disciple Sophrony. Glorified 1987.'),
 ('ENT_ORTH_JOSEPH_HESYCHAST','Joseph the Hesychast','Saint','Hesychast / Elder (Geron)','Christian/Orthodox','Hesychasm; noetic prayer; Athonite monastic renewal','A','Athonite elder (1897-1959) whose disciples repopulated many Athonite monasteries; key figure in the 20th-c. hesychast revival. Glorified 2020.'),
 ('ENT_ORTH_LUKE_SIMFEROPOL','Luke of Simferopol (Voino-Yasenetsky)','Saint','New Confessor / hierarch','Christian/Orthodox','Healing; medicine; confession under persecution','A','Russian archbishop and surgeon (1877-1961), Valentin Voino-Yasenetsky, confessor who suffered Soviet imprisonment and exile while practicing surgery. Glorified 1995/2000.'),
 ('ENT_ORTH_MATRONA_MOSCOW','Matrona of Moscow','Saint','Blessed wonderworker','Christian/Orthodox','Healing; clairvoyance; consolation under persecution','A','Blind Russian laywoman (1881-1952), Matrona Nikonova, venerated for healing and spiritual sight during the Soviet era; one of the most popular Russian saints. Glorified 1999/2004.'),
 ('ENT_ORTH_ELIZABETH_FEODOROVNA','Elizabeth Feodorovna','Saint','New Martyr / Grand Duchess','Christian/Orthodox','Charity; monastic foundation; new-martyrdom','A','Grand Duchess Elizabeth (1864-1918), founder of the Martha and Mary Convent; murdered by the Bolsheviks at Alapayevsk. New-martyr glorified 1981 (ROCOR) / 1992 (Moscow).'),
 ('ENT_ORTH_NICHOLAS_II','Tsar Nicholas II','Saint','Passion-bearer / Royal Martyr','Christian/Orthodox','Passion-bearing; Christian rulership','A','Last Russian emperor (1868-1918), executed with his family at Yekaterinburg; glorified as a passion-bearer (strastoterpets) in 2000.'),
 ('ENT_ORTH_ALEXANDRA_FEODOROVNA','Empress Alexandra Feodorovna','Saint','Passion-bearer / Royal Martyr','Christian/Orthodox','Passion-bearing','A','Last Russian empress (1872-1918), wife of Nicholas II; executed at Yekaterinburg and glorified as a passion-bearer in 2000.'),
 ('ENT_ORTH_ALEXEI_TSAREVICH','Tsarevich Alexei','Saint','Passion-bearer / Royal Martyr','Christian/Orthodox','Passion-bearing','A','Heir to the Russian throne (1904-1918), son of Nicholas II; executed at Yekaterinburg and glorified with his family as a passion-bearer in 2000.'),
 ('ENT_ORTH_JOHN_MAXIMOVITCH','John Maximovitch (of Shanghai and San Francisco)','Saint','Hierarch / wonderworker','Christian/Orthodox','Healing; ascetic episcopate; diaspora mission','A','Russian Orthodox bishop (1896-1966) of the diaspora (Shanghai, Western Europe, San Francisco); ascetic wonderworker. Glorified 1994 (ROCOR).'),
 ('ENT_ORTH_MARIA_SKOBTSOVA','Maria Skobtsova (Maria of Paris)','Saint','New Martyr / monastic','Christian/Orthodox','Social charity; new-martyrdom; ministry to the persecuted','A','Russian emigre nun in Paris (1891-1945) who sheltered Jews and others under Nazi occupation; died at Ravensbruck. Glorified 2004 (Ecumenical Patriarchate).'),
 ('ENT_ORTH_NIKOLAI_VELIMIROVIC','Nikolai Velimirovic','Saint','Hierarch / theologian','Christian/Orthodox','Preaching; theology; spiritual writing','A','Serbian bishop (1880-1956), ''the Serbian Chrysostom'', author of the Prologue of Ohrid; imprisoned at Dachau. Glorified 2003 (Serbian Orthodox Church).'),
 ('ENT_ORTH_JUSTIN_POPOVIC','Justin Popovic','Saint','Theologian / confessor','Christian/Orthodox','Dogmatic theology; patristic revival; christocentric spirituality','A','Serbian theologian and archimandrite (1894-1979), author of the Dogmatics of the Orthodox Church and Lives of the Saints; disciple of patristic tradition. Glorified 2010.'),
 ('ENT_ORTH_PAISIOS_ATHONITE','Paisios of Mount Athos','Saint','Elder (Geron) / hesychast','Christian/Orthodox','Spiritual counsel; the Jesus Prayer; discernment','A','Greek Athonite elder (1924-1994), among the most beloved modern startsy; renowned for counsel and discernment. Glorified 2015 (Ecumenical Patriarchate).'),
 ('ENT_ORTH_PORPHYRIOS_KAVSOKALYVIA','Porphyrios of Kavsokalyvia','Saint','Elder (Geron) / hesychast','Christian/Orthodox','Clairvoyance; healing; spiritual counsel','A','Greek elder (1906-1991) of Kavsokalyvia on Athos and later Athens; famed for charismatic gifts of insight and healing. Glorified 2013 (Ecumenical Patriarchate).'),
 ('ENT_ORTH_SOPHRONY_ESSEX','Sophrony of Essex','Saint','Elder (Geron) / hesychast','Christian/Orthodox','Hesychasm; the Jesus Prayer; monastic founding','A','Russian-born archimandrite (1896-1993), disciple and biographer of Silouan the Athonite; founder of the Monastery of St John the Baptist, Essex. Glorified 2019 (Ecumenical Patriarchate).');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'devotional',conf,'candidate_verified_name','Roster build via gen_roster.py (see CHANGELOG/git for release)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,etype text,note text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_ORTH_ATHONITE_ELDERS','SRC_PHILOKALIA','scholarly attestation','attestation'),
 ('ENT_ORTH_ROYAL_MARTYRS','SRC_SYNAXARION','scholarly attestation','attestation'),
 ('ENT_ORTH_NIKODEMOS_HAGIORITE','SRC_PHILOKALIA','scholarly attestation','attestation'),
 ('ENT_ORTH_IGNATIUS_BRIANCHANINOV','SRC_SYNAXARION','scholarly attestation','attestation'),
 ('ENT_ORTH_THEOPHAN_RECLUSE','SRC_PHILOKALIA','scholarly attestation','attestation'),
 ('ENT_ORTH_JOHN_KRONSTADT','SRC_SYNAXARION','scholarly attestation','attestation'),
 ('ENT_ORTH_NECTARIOS_AEGINA','SRC_SYNAXARION','scholarly attestation','attestation'),
 ('ENT_ORTH_SILOUAN_ATHONITE','SRC_PHILOKALIA','scholarly attestation','attestation'),
 ('ENT_ORTH_JOSEPH_HESYCHAST','SRC_PHILOKALIA','scholarly attestation','attestation'),
 ('ENT_ORTH_LUKE_SIMFEROPOL','SRC_SYNAXARION','scholarly attestation','attestation'),
 ('ENT_ORTH_MATRONA_MOSCOW','SRC_SYNAXARION','scholarly attestation','attestation'),
 ('ENT_ORTH_ELIZABETH_FEODOROVNA','SRC_SYNAXARION','scholarly attestation','attestation'),
 ('ENT_ORTH_NICHOLAS_II','SRC_SYNAXARION','scholarly attestation','attestation'),
 ('ENT_ORTH_ALEXANDRA_FEODOROVNA','SRC_SYNAXARION','scholarly attestation','attestation'),
 ('ENT_ORTH_ALEXEI_TSAREVICH','SRC_SYNAXARION','scholarly attestation','attestation'),
 ('ENT_ORTH_JOHN_MAXIMOVITCH','SRC_SYNAXARION','scholarly attestation','attestation'),
 ('ENT_ORTH_MARIA_SKOBTSOVA','SRC_SYNAXARION','scholarly attestation','attestation'),
 ('ENT_ORTH_NIKOLAI_VELIMIROVIC','SRC_SYNAXARION','scholarly attestation','attestation'),
 ('ENT_ORTH_JUSTIN_POPOVIC','SRC_SYNAXARION','scholarly attestation','attestation'),
 ('ENT_ORTH_PAISIOS_ATHONITE','SRC_PHILOKALIA','scholarly attestation','attestation'),
 ('ENT_ORTH_PORPHYRIOS_KAVSOKALYVIA','SRC_PHILOKALIA','scholarly attestation','attestation'),
 ('ENT_ORTH_SOPHRONY_ESSEX','SRC_PHILOKALIA','scholarly attestation','attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_ORTH_ATHONITE_ELDERS','PER_MODERN_ORTHODOX','Hub for the modern Athonite startsy / gerontes (Mount Athos): Silouan, Joseph the Hesychast, Paisios, Porphyrios, who renewed hesychast prayer and spiritual fatherhood in the 20th c.'),
 ('ENT_ORTH_ROYAL_MARTYRS','PER_MODERN_ORTHODOX','Collective hub for Tsar Nicholas II and his family, glorified in 2000 by the Moscow Patriarchate as passion-bearers (strastoterptsy) following their 1918 execution at Yekaterinburg.'),
 ('ENT_ORTH_NIKODEMOS_HAGIORITE','PER_MODERN_ORTHODOX','Athonite monk (1749-1809), co-compiler of the Philokalia with Macarius of Corinth; foundational figure of the modern hesychast revival. Glorified 1955.'),
 ('ENT_ORTH_IGNATIUS_BRIANCHANINOV','PER_MODERN_ORTHODOX','Russian bishop (1807-1867), author of The Arena and On the Prayer of Jesus; major modern systematizer of patristic ascetic teaching. Glorified 1988.'),
 ('ENT_ORTH_THEOPHAN_RECLUSE','PER_MODERN_ORTHODOX','Russian bishop (1815-1894) who retired into reclusion; translated the Philokalia into Russian (Dobrotolyubie) and wrote extensively on unceasing prayer. Glorified 1988.'),
 ('ENT_ORTH_JOHN_KRONSTADT','PER_MODERN_ORTHODOX','Russian parish priest (1829-1908), famed wonderworker and author of My Life in Christ; renowned for frequent communion and miracles of healing. Glorified 1990.'),
 ('ENT_ORTH_NECTARIOS_AEGINA','PER_MODERN_ORTHODOX','Greek bishop (1846-1920), Metropolitan of Pentapolis, founder of the convent on Aegina; one of the most popular modern Greek wonderworkers and healers. Glorified 1961.'),
 ('ENT_ORTH_SILOUAN_ATHONITE','PER_MODERN_ORTHODOX','Russian monk of St Panteleimon''s Monastery on Athos (1866-1938); his life and teaching were transmitted by his disciple Sophrony. Glorified 1987.'),
 ('ENT_ORTH_JOSEPH_HESYCHAST','PER_MODERN_ORTHODOX','Athonite elder (1897-1959) whose disciples repopulated many Athonite monasteries; key figure in the 20th-c. hesychast revival. Glorified 2020.'),
 ('ENT_ORTH_LUKE_SIMFEROPOL','PER_MODERN_ORTHODOX','Russian archbishop and surgeon (1877-1961), Valentin Voino-Yasenetsky, confessor who suffered Soviet imprisonment and exile while practicing surgery. Glorified 1995/2000.'),
 ('ENT_ORTH_MATRONA_MOSCOW','PER_MODERN_ORTHODOX','Blind Russian laywoman (1881-1952), Matrona Nikonova, venerated for healing and spiritual sight during the Soviet era; one of the most popular Russian saints. Glorified 1999/2004.'),
 ('ENT_ORTH_ELIZABETH_FEODOROVNA','PER_MODERN_ORTHODOX','Grand Duchess Elizabeth (1864-1918), founder of the Martha and Mary Convent; murdered by the Bolsheviks at Alapayevsk. New-martyr glorified 1981 (ROCOR) / 1992 (Moscow).'),
 ('ENT_ORTH_NICHOLAS_II','PER_MODERN_ORTHODOX','Last Russian emperor (1868-1918), executed with his family at Yekaterinburg; glorified as a passion-bearer (strastoterpets) in 2000.'),
 ('ENT_ORTH_ALEXANDRA_FEODOROVNA','PER_MODERN_ORTHODOX','Last Russian empress (1872-1918), wife of Nicholas II; executed at Yekaterinburg and glorified as a passion-bearer in 2000.'),
 ('ENT_ORTH_ALEXEI_TSAREVICH','PER_MODERN_ORTHODOX','Heir to the Russian throne (1904-1918), son of Nicholas II; executed at Yekaterinburg and glorified with his family as a passion-bearer in 2000.'),
 ('ENT_ORTH_JOHN_MAXIMOVITCH','PER_MODERN_ORTHODOX','Russian Orthodox bishop (1896-1966) of the diaspora (Shanghai, Western Europe, San Francisco); ascetic wonderworker. Glorified 1994 (ROCOR).'),
 ('ENT_ORTH_MARIA_SKOBTSOVA','PER_MODERN_ORTHODOX','Russian emigre nun in Paris (1891-1945) who sheltered Jews and others under Nazi occupation; died at Ravensbruck. Glorified 2004 (Ecumenical Patriarchate).'),
 ('ENT_ORTH_NIKOLAI_VELIMIROVIC','PER_MODERN_ORTHODOX','Serbian bishop (1880-1956), ''the Serbian Chrysostom'', author of the Prologue of Ohrid; imprisoned at Dachau. Glorified 2003 (Serbian Orthodox Church).'),
 ('ENT_ORTH_JUSTIN_POPOVIC','PER_MODERN_ORTHODOX','Serbian theologian and archimandrite (1894-1979), author of the Dogmatics of the Orthodox Church and Lives of the Saints; disciple of patristic tradition. Glorified 2010.'),
 ('ENT_ORTH_PAISIOS_ATHONITE','PER_MODERN_ORTHODOX','Greek Athonite elder (1924-1994), among the most beloved modern startsy; renowned for counsel and discernment. Glorified 2015 (Ecumenical Patriarchate).'),
 ('ENT_ORTH_PORPHYRIOS_KAVSOKALYVIA','PER_MODERN_ORTHODOX','Greek elder (1906-1991) of Kavsokalyvia on Athos and later Athens; famed for charismatic gifts of insight and healing. Glorified 2013 (Ecumenical Patriarchate).'),
 ('ENT_ORTH_SOPHRONY_ESSEX','PER_MODERN_ORTHODOX','Russian-born archimandrite (1896-1993), disciple and biographer of Silouan the Athonite; founder of the Monastery of St John the Baptist, Essex. Glorified 2019 (Ecumenical Patriarchate).');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_ORTH_SILOUAN_ATHONITE','member_of','ENT_ORTH_ATHONITE_ELDERS','high','Silouan was an Athonite monk of St Panteleimon''s; charter member of the modern Athonite eldership.'),
 ('ENT_ORTH_JOSEPH_HESYCHAST','member_of','ENT_ORTH_ATHONITE_ELDERS','high','Joseph the Hesychast was a foundational 20th-c. Athonite elder whose disciples renewed Athos.'),
 ('ENT_ORTH_PAISIOS_ATHONITE','member_of','ENT_ORTH_ATHONITE_ELDERS','high','Paisios was among the most prominent modern Athonite elders.'),
 ('ENT_ORTH_PORPHYRIOS_KAVSOKALYVIA','member_of','ENT_ORTH_ATHONITE_ELDERS','high','Porphyrios was an Athonite elder of Kavsokalyvia.'),
 ('ENT_ORTH_SOPHRONY_ESSEX','member_of','ENT_ORTH_ATHONITE_ELDERS','high','Sophrony lived on Athos as a hesychast disciple of Silouan before founding his Essex monastery.'),
 ('ENT_ORTH_NICHOLAS_II','member_of','ENT_ORTH_ROYAL_MARTYRS','high','Nicholas II is the principal of the Romanov passion-bearers glorified in 2000.'),
 ('ENT_ORTH_ALEXANDRA_FEODOROVNA','member_of','ENT_ORTH_ROYAL_MARTYRS','high','Empress Alexandra was glorified among the Royal Martyrs in 2000.'),
 ('ENT_ORTH_ALEXEI_TSAREVICH','member_of','ENT_ORTH_ROYAL_MARTYRS','high','Tsarevich Alexei was glorified among the Royal Martyrs in 2000.'),
 ('ENT_ORTH_ROYAL_MARTYRS','reception_of','ENT_JESUS_CHRIST','high','As passion-bearers (strastoterptsy) the Romanovs are venerated for accepting death in imitation of Christ''s passion; passion-bearing is explicitly a reception of Christ''s Passion, not deification.'),
 ('ENT_ORTH_SOPHRONY_ESSEX','taught_by','ENT_ORTH_SILOUAN_ATHONITE','high','Sophrony was the personal disciple and biographer of Silouan the Athonite, whose teaching he transmitted.'),
 ('ENT_ORTH_NIKODEMOS_HAGIORITE','embodies','ENT_MONASTICISM','high','Nikodemos was an Athonite monk whose life embodied hesychast monasticism.'),
 ('ENT_ORTH_NIKODEMOS_HAGIORITE','transmits','ENT_ORTH_UNCREATED_LIGHT','high','As co-compiler of the Philokalia he transmitted the hesychast doctrine of the uncreated light/noetic prayer.'),
 ('ENT_ORTH_THEOPHAN_RECLUSE','transmits','ENT_ORTH_UNCREATED_LIGHT','high','Theophan translated the Philokalia into Russian, transmitting the hesychast tradition of inner light and the prayer of the heart.'),
 ('ENT_ORTH_THEOPHAN_RECLUSE','teaches','ENT_PRAYER','high','Theophan''s principal teaching concerned unceasing prayer and the prayer of the heart.'),
 ('ENT_ORTH_IGNATIUS_BRIANCHANINOV','teaches','ENT_PRAYER','high','Ignatius''s central work, On the Prayer of Jesus, teaches the practice of the Jesus Prayer.'),
 ('ENT_ORTH_IGNATIUS_BRIANCHANINOV','embodies','ENT_MONASTICISM','high','Ignatius was a monastic reformer whose Arena systematizes patristic ascetic life.'),
 ('ENT_ORTH_SILOUAN_ATHONITE','aligned_with','ENT_ORTH_UNCREATED_LIGHT','high','Silouan''s teaching is firmly within the hesychast experience of grace and the uncreated light.'),
 ('ENT_ORTH_SILOUAN_ATHONITE','teaches','ENT_PRAYER','high','Silouan taught the practice of the Jesus Prayer and prayer for the whole world.'),
 ('ENT_ORTH_JOSEPH_HESYCHAST','aligned_with','ENT_ORTH_UNCREATED_LIGHT','high','Joseph the Hesychast taught noetic prayer and the experience of divine grace in the hesychast tradition.'),
 ('ENT_ORTH_PAISIOS_ATHONITE','teaches','ENT_PRAYER','high','Paisios taught the Jesus Prayer and was a renowned counselor on the spiritual life.'),
 ('ENT_ORTH_PORPHYRIOS_KAVSOKALYVIA','patron_of','ENT_HEALING','medium','Porphyrios was widely venerated for charismatic gifts of healing and spiritual insight.'),
 ('ENT_ORTH_SOPHRONY_ESSEX','aligned_with','ENT_ORTH_UNCREATED_LIGHT','high','Sophrony''s theology of personhood and the vision of the uncreated light continues the Palamite hesychast tradition.'),
 ('ENT_ORTH_JOHN_KRONSTADT','patron_of','ENT_HEALING','high','John of Kronstadt was venerated in his lifetime for numerous miracles of healing.'),
 ('ENT_ORTH_JOHN_KRONSTADT','aligned_with','ENT_ORTH_SERAPHIM','medium','John of Kronstadt belongs to the same Russian wonderworker tradition as Seraphim of Sarov.'),
 ('ENT_ORTH_NECTARIOS_AEGINA','patron_of','ENT_HEALING','high','Nektarios of Aegina is one of the most popular modern Greek healing wonderworkers.'),
 ('ENT_ORTH_LUKE_SIMFEROPOL','patron_of','ENT_HEALING','high','Luke (Voino-Yasenetsky) was both a surgeon and venerated healer; patron of physicians and the sick.'),
 ('ENT_ORTH_LUKE_SIMFEROPOL','aligned_with','ENT_ORTH_PANTELEIMON','medium','As a physician-saint Luke continues the tradition of the unmercenary healers such as Panteleimon.'),
 ('ENT_ORTH_MATRONA_MOSCOW','patron_of','ENT_HEALING','high','Matrona of Moscow is venerated principally for healing and consolation.'),
 ('ENT_ORTH_MATRONA_MOSCOW','aligned_with','ENT_ORTH_SERAPHIM','medium','Matrona stands in the Russian wonderworker lineage exemplified by Seraphim of Sarov.'),
 ('ENT_ORTH_JOHN_MAXIMOVITCH','patron_of','ENT_HEALING','medium','John of Shanghai and San Francisco was venerated as an ascetic wonderworker and healer in the diaspora.'),
 ('ENT_ORTH_JOHN_MAXIMOVITCH','embodies','ENT_MONASTICISM','high','John lived a strict ascetic-monastic episcopate.'),
 ('ENT_ORTH_ELIZABETH_FEODOROVNA','embodies','ENT_MONASTICISM','high','Elizabeth founded and led the Martha and Mary Convent, embodying the monastic-diaconal life.'),
 ('ENT_ORTH_ELIZABETH_FEODOROVNA','reception_of','ENT_JESUS_CHRIST','high','As a new-martyr she is venerated for accepting death in imitation of Christ; martyrdom as reception of Christ''s Passion, not deification.'),
 ('ENT_ORTH_MARIA_SKOBTSOVA','reception_of','ENT_JESUS_CHRIST','high','Maria of Paris is venerated as a new-martyr who died at Ravensbruck serving Christ in the persecuted; martyrdom as reception of Christ''s Passion.'),
 ('ENT_ORTH_MARIA_SKOBTSOVA','embodies','ENT_MONASTICISM','medium','Maria was a professed nun who reconceived monasticism as active social charity.'),
 ('ENT_ORTH_NIKOLAI_VELIMIROVIC','teaches','ENT_WISDOM','high','Nikolai Velimirovic, ''the Serbian Chrysostom'', was a major preacher and theological writer.'),
 ('ENT_ORTH_JUSTIN_POPOVIC','teaches','ENT_WISDOM','high','Justin Popovic was a leading 20th-c. dogmatic theologian of the Orthodox Church.'),
 ('ENT_ORTH_JUSTIN_POPOVIC','taught_by','ENT_ORTH_NIKOLAI_VELIMIROVIC','medium','Justin Popovic was a younger associate and spiritual heir of Nikolai Velimirovic within the Serbian Orthodox revival.');

\echo '--- REJECTED edges (bad id/type, or subject lacks a source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
