-- build_p3_lydian.sql  (GENERATED by gen_roster.py p3_lydian) — v1.80.0
-- 8 entities, 17 edges, 1 new periods, 1 new sources. Idempotent + self-validating.
BEGIN;

INSERT INTO periods (period_id, period_name, start_year, end_year) VALUES
 ('PER_LYDIAN','Lydian Kingdom (Iron Age western Anatolia)',-1200,-540)
ON CONFLICT (period_id) DO NOTHING;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_MUNN_MOTHER_GODS','secondary scholarship','Munn, Mark. The Mother of the Gods, Athens, and the Tyranny of Asia: A Study of Sovereignty in Ancient Religion (University of California Press, 2006)','Lydian and Anatolian sovereignty religion; Kuvava/Kybebe, Santas, and the transmission of the Mother of the Gods into Greek and Roman cult.')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,trad text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_LYD_PANTHEON','Lydian Pantheon','collective','collective','Lydian','civic polytheism','B','Collective hub for the deities of the Iron Age Lydian kingdom (Sardis, c. 1200-540 BCE), attested in Lydian-language inscriptions, theophoric names, and Greek sources (Herodotus, Hipponax). Munn (2006).'),
 ('ENT_LYD_KUVAVA','Kuvava (Kybebe)','deity','deity','Lydian','mother goddess, sovereignty, mountains','B','The Lydian mother-goddess, attested in Lydian inscriptions as Kuvava and in Greek as Kybebe (Herodotus 5.102; Hipponax names her at Sardis). Descended from the Luwian/Neo-Hittite Kubaba of Carchemish and ancestral to the Phrygian/Greek Cybele; central to Munn''s account of Anatolian divine sovereignty. Distinct local form, not the Phrygian Matar.'),
 ('ENT_LYD_SANTAS','Santas (Sandon)','deity','deity','Lydian','war, plague, kingship, club-bearing hero-god','B','Lydian war- and plague-god, the Anatolian Sandon/Sandas figure interpreted by Greeks as a Heracles. Munn connects him to Lydian dynastic ancestry (the Tylonid/Heraclid line at Sardis); continuous with the Luwian Santa and Cilician Sandas. Attested via theophoric onomastics and the Greek Herakles-equation.'),
 ('ENT_LYD_ARTIMUS','Artimus','deity','deity','Lydian','wild nature, protection, the dead','B','Lydian goddess attested in Lydian inscriptions (frequently paired with Pldans), regularly equated with Greek Artemis; her cult is prominent at Sardis and Ephesus'' Anatolian background. Munn (2006); Lydian epigraphic corpus.'),
 ('ENT_LYD_PLDANS','Pldans','deity','deity','Lydian','divine guardianship, oracular/solar associations','C','Lydian god named in inscriptions (paired with Artimus in protective formulae), conventionally identified with Greek Apollo on phonetic and functional grounds. Attestation is epigraphic and partly conjectural. Munn (2006).'),
 ('ENT_LYD_LAMETRUS','Lametrus','deity','deity','Lydian','grain, fertility, earth','C','Lydian goddess attested in inscriptions, identified with Greek Demeter through both name and agrarian function. Reflects the shared Anatolian-Greek grain-mother substrate. Munn (2006); Lydian epigraphy.'),
 ('ENT_LYD_BAKIVALIS','Bakivalis','deity','deity','Lydian','wine, ecstatic cult, vegetation','C','Lydian theonym/theophoric element (Baki-) reflecting a Dionysus-type wine and ecstatic-cult deity; the Lydian-Phrygian Bakkhos sphere from which the Greek epithet Bakchos is partly drawn. Attestation chiefly onomastic. Munn (2006).'),
 ('ENT_LYD_KANDAULES','Kandaules','deity','deity','Lydian','dog-throttling, gateways, chthonic protection','C','Lydian divine epithet ''Kandaules'' (the ''dog-throttler''), reported by Hipponax as a Lydian title of Hermes; also the throne-name of the last Heraclid king of Sardis (Herodotus 1.7ff). A Hermes-type guardian/psychopomp figure. Munn (2006).');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'devotional',conf,'candidate_verified_name','Roster build via gen_roster.py (see CHANGELOG/git for release)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,etype text,note text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_LYD_PANTHEON','SRC_MUNN_MOTHER_GODS','scholarly attestation','attestation'),
 ('ENT_LYD_KUVAVA','SRC_MUNN_MOTHER_GODS','scholarly attestation','attestation'),
 ('ENT_LYD_SANTAS','SRC_MUNN_MOTHER_GODS','scholarly attestation','attestation'),
 ('ENT_LYD_ARTIMUS','SRC_MUNN_MOTHER_GODS','scholarly attestation','attestation'),
 ('ENT_LYD_PLDANS','SRC_MUNN_MOTHER_GODS','scholarly attestation','attestation'),
 ('ENT_LYD_LAMETRUS','SRC_MUNN_MOTHER_GODS','scholarly attestation','attestation'),
 ('ENT_LYD_BAKIVALIS','SRC_MUNN_MOTHER_GODS','scholarly attestation','attestation'),
 ('ENT_LYD_KANDAULES','SRC_MUNN_MOTHER_GODS','scholarly attestation','attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_LYD_PANTHEON','PER_LYDIAN','Collective hub for the deities of the Iron Age Lydian kingdom (Sardis, c. 1200-540 BCE), attested in Lydian-language inscriptions, theophoric names, and Greek sources (Herodotus, Hipponax). Munn (2006).'),
 ('ENT_LYD_KUVAVA','PER_LYDIAN','The Lydian mother-goddess, attested in Lydian inscriptions as Kuvava and in Greek as Kybebe (Herodotus 5.102; Hipponax names her at Sardis). Descended from the Luwian/Neo-Hittite Kubaba of Carchemish and ancestral to the Phrygian/Greek Cybele; central to Munn''s account of Anatolian divine sovereignty. Distinct local form, not the Phrygian Matar.'),
 ('ENT_LYD_SANTAS','PER_LYDIAN','Lydian war- and plague-god, the Anatolian Sandon/Sandas figure interpreted by Greeks as a Heracles. Munn connects him to Lydian dynastic ancestry (the Tylonid/Heraclid line at Sardis); continuous with the Luwian Santa and Cilician Sandas. Attested via theophoric onomastics and the Greek Herakles-equation.'),
 ('ENT_LYD_ARTIMUS','PER_LYDIAN','Lydian goddess attested in Lydian inscriptions (frequently paired with Pldans), regularly equated with Greek Artemis; her cult is prominent at Sardis and Ephesus'' Anatolian background. Munn (2006); Lydian epigraphic corpus.'),
 ('ENT_LYD_PLDANS','PER_LYDIAN','Lydian god named in inscriptions (paired with Artimus in protective formulae), conventionally identified with Greek Apollo on phonetic and functional grounds. Attestation is epigraphic and partly conjectural. Munn (2006).'),
 ('ENT_LYD_LAMETRUS','PER_LYDIAN','Lydian goddess attested in inscriptions, identified with Greek Demeter through both name and agrarian function. Reflects the shared Anatolian-Greek grain-mother substrate. Munn (2006); Lydian epigraphy.'),
 ('ENT_LYD_BAKIVALIS','PER_LYDIAN','Lydian theonym/theophoric element (Baki-) reflecting a Dionysus-type wine and ecstatic-cult deity; the Lydian-Phrygian Bakkhos sphere from which the Greek epithet Bakchos is partly drawn. Attestation chiefly onomastic. Munn (2006).'),
 ('ENT_LYD_KANDAULES','PER_LYDIAN','Lydian divine epithet ''Kandaules'' (the ''dog-throttler''), reported by Hipponax as a Lydian title of Hermes; also the throne-name of the last Heraclid king of Sardis (Herodotus 1.7ff). A Hermes-type guardian/psychopomp figure. Munn (2006).');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_LYD_KUVAVA','member_of','ENT_LYD_PANTHEON','high','Kuvava/Kybebe is the chief mother-goddess of the Lydian pantheon at Sardis (Munn 2006).'),
 ('ENT_LYD_SANTAS','member_of','ENT_LYD_PANTHEON','high','Santas/Sandon is a principal Lydian war/kingship god (Munn 2006).'),
 ('ENT_LYD_ARTIMUS','member_of','ENT_LYD_PANTHEON','high','Artimus is attested across the Lydian inscriptional pantheon (Munn 2006).'),
 ('ENT_LYD_PLDANS','member_of','ENT_LYD_PANTHEON','medium','Pldans appears in Lydian inscriptions, often paired with Artimus.'),
 ('ENT_LYD_LAMETRUS','member_of','ENT_LYD_PANTHEON','medium','Lametrus is an attested Lydian grain-goddess theonym.'),
 ('ENT_LYD_BAKIVALIS','member_of','ENT_LYD_PANTHEON','medium','Bakivalis reflects the Lydian Dionysiac/wine-cult sphere.'),
 ('ENT_LYD_KANDAULES','member_of','ENT_LYD_PANTHEON','medium','Kandaules is a Lydian divine epithet (Hermes-type guardian) within Sardian cult.'),
 ('ENT_LYD_ARTIMUS','paired_with','ENT_LYD_PLDANS','medium','Artimus and Pldans recur together in Lydian protective inscription formulae, mirroring the Greek Artemis-Apollo pairing.'),
 ('ENT_LYD_KUVAVA','received_as','ENT_CYBELE','high','The Lydian Kuvava/Kybebe is a key link in the reception chain (Kubaba > Kuvava/Kybebe > Cybele) producing the Greek Cybele/Magna Mater (Munn 2006).'),
 ('ENT_LYD_KUVAVA','equated_with','ENT_LUW_KUBABA','high','Lydian Kuvava continues the name and figure of the Luwian/Neo-Hittite Kubaba of Carchemish.'),
 ('ENT_LYD_SANTAS','equated_with','ENT_LUW_SANTA','high','Lydian Santas is the western-Anatolian continuation of the Luwian war/plague god Santa (ancestor of Cilician Sandas).'),
 ('ENT_LYD_SANTAS','equated_with','ENT_HERACLES','high','Greeks interpreted the club-bearing Lydian Santas/Sandon as Heracles, grounding the Heraclid dynasty of Sardis (interpretatio Graeca; Munn 2006).'),
 ('ENT_LYD_ARTIMUS','equated_with','ENT_ARTEMIS','high','Lydian Artimus is the local form regularly equated with Greek Artemis on phonetic and functional grounds.'),
 ('ENT_LYD_PLDANS','equated_with','ENT_APOLLO','medium','Pldans is conventionally identified with Greek Apollo by name and protective/oracular function.'),
 ('ENT_LYD_LAMETRUS','equated_with','ENT_DEMETER','medium','Lydian Lametrus is identified with Greek Demeter by name and agrarian grain function.'),
 ('ENT_LYD_BAKIVALIS','syncretized_with','ENT_DIONYSUS','medium','The Lydian Baki- wine/ecstatic cult is syncretized with Dionysus, who carries the Lydian-derived epithet Bakchos.'),
 ('ENT_LYD_KANDAULES','equated_with','ENT_HERMES','medium','Hipponax reports Kandaules (''dog-throttler'') as a Lydian title of Hermes, a guardian/psychopomp figure.');

\echo '--- REJECTED edges (bad id/type, or subject lacks a source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
