-- build_p3_commagene.sql  (GENERATED by gen_roster.py p3_commagene) — v1.80.0
-- 6 entities, 18 edges, 1 new periods, 1 new sources. Idempotent + self-validating.
BEGIN;

INSERT INTO periods (period_id, period_name, start_year, end_year) VALUES
 ('PER_COMMAGENE','Commagenian Kingdom',-100,-31)
ON CONFLICT (period_id) DO NOTHING;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_VERSLUYS_COMMAGENE','secondary scholarship','Versluys, M.J. — Visual Style and Constructing Identity in the Hellenistic World: Nemrud Dag and Commagene under Antiochos I (Cambridge, 2017)','Royal dynastic cult, syncretic pantheon, hierothesion program, and Greco-Iranian theonyms of Commagene')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,trad text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_COMM_PANTHEON','Pantheon of Commagene','collective','Deity collective','Commagene','dynastic cult, syncretism, royal ancestor cult','B','Hub for the syncretic Greco-Iranian dynastic pantheon established by Antiochus I Theos; attested in the Nomos inscriptions and the colossal seated divine statues of the Nemrud Dag hierothesion.'),
 ('ENT_COMM_ZEUS_OROMASDES','Zeus-Oromasdes','deity','Syncretic deity','Commagene','sky sovereignty, supreme god','B','Supreme deity of the Commagenian pantheon, an explicit fusion of Greek Zeus with Iranian Ahura Mazda (Oromasdes); attested in the Nemrud Dag cult inscriptions and colossal statuary of Antiochus I.'),
 ('ENT_COMM_APOLLO_MITHRAS_HELIOS_HERMES','Apollo-Mithras-Helios-Hermes','deity','Syncretic deity','Commagene','sun, light, mediation, messenger','B','Composite solar/mediating deity of Commagene fusing Apollo, Iranian Mithra(s), Helios and Hermes; named in the Nomos inscriptions and depicted among the Nemrud Dag seated colossi.'),
 ('ENT_COMM_ARTAGNES_HERACLES_ARES','Artagnes-Heracles-Ares','deity','Syncretic deity','Commagene','war, victory, heroic strength','B','Composite warrior deity of Commagene fusing Iranian Verethragna (Artagnes) with Greek Heracles and Ares; attested at Nemrud Dag and in the dexiosis reliefs where Antiochus I clasps his hand.'),
 ('ENT_COMM_TYCHE','Tyche of Commagene','deity','Goddess/personification','Commagene','fortune, territorial personification','B','Personified fortune of the kingdom of Commagene, seated among the divine colossi at Nemrud Dag as the patroness of the land; a regional cult form of Greek Tyche.'),
 ('ENT_COMM_ANTIOCHUS_I_THEOS','Antiochus I Theos of Commagene','deity','Deified human','Commagene','deified king, dynastic ancestor cult','B','King of Commagene (r. c.70-31 BCE) who established and was deified within the royal pantheon; enthroned among the gods at Nemrud Dag and shown in dexiosis with each deity. A deified historical mortal.');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'devotional',conf,'candidate_verified_name','Roster build via gen_roster.py (see CHANGELOG/git for release)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,etype text,note text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_COMM_PANTHEON','SRC_VERSLUYS_COMMAGENE','scholarly attestation','attestation'),
 ('ENT_COMM_ZEUS_OROMASDES','SRC_VERSLUYS_COMMAGENE','scholarly attestation','attestation'),
 ('ENT_COMM_APOLLO_MITHRAS_HELIOS_HERMES','SRC_VERSLUYS_COMMAGENE','scholarly attestation','attestation'),
 ('ENT_COMM_ARTAGNES_HERACLES_ARES','SRC_VERSLUYS_COMMAGENE','scholarly attestation','attestation'),
 ('ENT_COMM_TYCHE','SRC_VERSLUYS_COMMAGENE','scholarly attestation','attestation'),
 ('ENT_COMM_ANTIOCHUS_I_THEOS','SRC_VERSLUYS_COMMAGENE','scholarly attestation','attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_COMM_PANTHEON','PER_COMMAGENE','Hub for the syncretic Greco-Iranian dynastic pantheon established by Antiochus I Theos; attested in the Nomos inscriptions and the colossal seated divine statues of the Nemrud Dag hierothesion.'),
 ('ENT_COMM_ZEUS_OROMASDES','PER_COMMAGENE','Supreme deity of the Commagenian pantheon, an explicit fusion of Greek Zeus with Iranian Ahura Mazda (Oromasdes); attested in the Nemrud Dag cult inscriptions and colossal statuary of Antiochus I.'),
 ('ENT_COMM_APOLLO_MITHRAS_HELIOS_HERMES','PER_COMMAGENE','Composite solar/mediating deity of Commagene fusing Apollo, Iranian Mithra(s), Helios and Hermes; named in the Nomos inscriptions and depicted among the Nemrud Dag seated colossi.'),
 ('ENT_COMM_ARTAGNES_HERACLES_ARES','PER_COMMAGENE','Composite warrior deity of Commagene fusing Iranian Verethragna (Artagnes) with Greek Heracles and Ares; attested at Nemrud Dag and in the dexiosis reliefs where Antiochus I clasps his hand.'),
 ('ENT_COMM_TYCHE','PER_COMMAGENE','Personified fortune of the kingdom of Commagene, seated among the divine colossi at Nemrud Dag as the patroness of the land; a regional cult form of Greek Tyche.'),
 ('ENT_COMM_ANTIOCHUS_I_THEOS','PER_COMMAGENE','King of Commagene (r. c.70-31 BCE) who established and was deified within the royal pantheon; enthroned among the gods at Nemrud Dag and shown in dexiosis with each deity. A deified historical mortal.');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_COMM_ZEUS_OROMASDES','member_of','ENT_COMM_PANTHEON','high','Zeus-Oromasdes is the supreme deity of the Commagenian dynastic pantheon at Nemrud Dag.'),
 ('ENT_COMM_APOLLO_MITHRAS_HELIOS_HERMES','member_of','ENT_COMM_PANTHEON','high','Apollo-Mithras-Helios-Hermes is one of the seated colossal deities of the Commagenian pantheon.'),
 ('ENT_COMM_ARTAGNES_HERACLES_ARES','member_of','ENT_COMM_PANTHEON','high','Artagnes-Heracles-Ares is one of the seated colossal deities of the Commagenian pantheon.'),
 ('ENT_COMM_TYCHE','member_of','ENT_COMM_PANTHEON','high','The Tyche of Commagene is seated among the divine colossi of the pantheon at Nemrud Dag.'),
 ('ENT_COMM_ANTIOCHUS_I_THEOS','member_of','ENT_COMM_PANTHEON','high','Antiochus I Theos enthroned himself as a deified king among the gods of his own dynastic pantheon.'),
 ('ENT_COMM_ZEUS_OROMASDES','equated_with','ENT_ZEUS','high','Ancient interpretatio: the theonym Zeus-Oromasdes explicitly equates the Commagenian supreme god with Greek Zeus.'),
 ('ENT_COMM_ZEUS_OROMASDES','equated_with','ENT_ZOR_AHURA_MAZDA','high','Ancient interpretatio: Oromasdes is the Hellenized form of Iranian Ahura Mazda, fused with Zeus in the Commagenian theonym.'),
 ('ENT_COMM_APOLLO_MITHRAS_HELIOS_HERMES','equated_with','ENT_APOLLO','high','Ancient interpretatio: the composite theonym explicitly identifies the Commagenian solar god with Greek Apollo.'),
 ('ENT_COMM_APOLLO_MITHRAS_HELIOS_HERMES','equated_with','ENT_ZOR_MITHRA','high','Ancient interpretatio: the Mithras element of the composite theonym derives from Iranian Mithra of the Zoroastrian tradition.'),
 ('ENT_COMM_APOLLO_MITHRAS_HELIOS_HERMES','syncretized_with','ENT_SYN_MITHRAS','medium','The Commagenian Apollo-Mithras-Helios-Hermes is a key early attestation of the Mithras whose cult later developed in the Roman world.'),
 ('ENT_COMM_APOLLO_MITHRAS_HELIOS_HERMES','equated_with','ENT_HELIOS','high','Ancient interpretatio: the Helios element of the composite theonym identifies the god with the Greek sun god.'),
 ('ENT_COMM_APOLLO_MITHRAS_HELIOS_HERMES','equated_with','ENT_HERMES','high','Ancient interpretatio: the Hermes element of the composite theonym identifies the god with the Greek messenger god.'),
 ('ENT_COMM_ARTAGNES_HERACLES_ARES','equated_with','ENT_ZOR_VERETHRAGNA','high','Ancient interpretatio: Artagnes is the Hellenized form of Iranian Verethragna, the Zoroastrian yazata of victory.'),
 ('ENT_COMM_ARTAGNES_HERACLES_ARES','equated_with','ENT_HERACLES','high','Ancient interpretatio: the composite theonym explicitly identifies the Commagenian warrior god with Greek Heracles.'),
 ('ENT_COMM_ARTAGNES_HERACLES_ARES','equated_with','ENT_ARES','high','Ancient interpretatio: the Ares element of the composite theonym identifies the god with the Greek war god.'),
 ('ENT_COMM_TYCHE','cult_form_of','ENT_TYCHE','high','The Tyche of Commagene is a regional civic/territorial cult form of the Greek goddess Tyche (Fortune).'),
 ('ENT_COMM_ANTIOCHUS_I_THEOS','associated_with','ENT_COMM_ZEUS_OROMASDES','medium','The Nemrud Dag dexiosis reliefs depict Antiochus I clasping the hand of Zeus-Oromasdes, asserting his divine legitimacy.'),
 ('ENT_COMM_ANTIOCHUS_I_THEOS','associated_with','ENT_COMM_ARTAGNES_HERACLES_ARES','medium','A Nemrud Dag dexiosis relief shows Antiochus I clasping the hand of Artagnes-Heracles-Ares.');

\echo '--- REJECTED edges (bad id/type, or subject lacks a source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
