-- build_p2_coptic.sql  (GENERATED by gen_roster.py p2_coptic) — v1.80.0
-- 9 entities, 16 edges, 0 new periods, 1 new sources. Idempotent + self-validating.
BEGIN;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_DAVIS_EARLY_COPTIC_PAPACY','secondary scholarship','Stephen J. Davis, The Early Coptic Papacy: The Egyptian Church and Its Leadership in Late Antiquity (American University in Cairo Press, 2004)','Standard scholarly history of the Alexandrian patriarchate and the formation of the Coptic (miaphysite) Church from its origins through late antiquity; covers the papal succession, the monastic movement (Anthony, Pachomius, the Kellia/Scetis fathers, Shenoute and the White Monastery), the post-Chalcedonian schism, the major Coptic martyrs of the Diocletianic persecution, and the leadership culture that shaped figures down to the modern Coptic papacy.')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,trad text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_COP_FATHERS','Coptic Fathers and Saints','Collective','Collective hub','Coptic Christian','monasticism, martyrdom, ecclesiastical leadership','B','Hub collective for the venerated abbots, patriarchs, and martyrs of the Egyptian (Coptic) Church; a grouping node, not a cultic figure.'),
 ('ENT_COP_SHENOUTE','Shenoute the Great','Saint','Abbot / Church Father','Coptic Christian','monasticism, Coptic literature, abbacy','B','Archimandrite of the White Monastery near Sohag (d. c.465); the towering author of classical Sahidic Coptic literature, attested by his vast surviving corpus of sermons and letters and by Besa''s Life of Shenoute. Venerated human, not deified.'),
 ('ENT_COP_BESA','Besa of Atripe','Saint','Abbot / disciple','Coptic Christian','monasticism, hagiography','C','Disciple and successor of Shenoute as head of the White Monastery; author of the Life of Shenoute and of monastic letters, attested by that surviving corpus.'),
 ('ENT_COP_PACHOMIUS','Pachomius the Great','Saint','Abbot / founder','Coptic Christian','cenobitic monasticism','B','Founder of cenobitic (communal) monasticism at Tabennesi (d. 348); attested by the Coptic and Greek Lives of Pachomius and his surviving Rule. Verified absent from DB. Venerated human.'),
 ('ENT_COP_MACARIUS','Macarius of Egypt','Saint','Abbot / desert father','Coptic Christian','desert monasticism','B','Founder of the monastic settlement of Scetis (Wadi al-Natrun) in the Nitrian desert (d. c.391); attested in the Apophthegmata Patrum and the Lausiac History. Distinct from Macaria (ENT_MACARIA, a Greek goddess - homonym verified in DB) and Macarius of Alexandria. Verified absent from DB. Venerated human.'),
 ('ENT_COP_MOSES_BLACK','Moses the Black','Saint','Monk / martyr','Coptic Christian','desert monasticism, conversion, martyrdom','C','Former brigand turned ascetic of Scetis under Macarius (d. c.405), martyred by raiding Berbers; attested in the Apophthegmata Patrum. Venerated human.'),
 ('ENT_COP_SAMUEL_CONFESSOR','Samuel the Confessor','Saint','Abbot / confessor','Coptic Christian','monasticism, confession of faith under persecution','C','Seventh-century Coptic abbot of the Monastery of al-Qalamun (the Monastery of St Samuel) in the Fayyum, confessor under Chalcedonian and early Muslim-era pressure; attested by his Coptic Life. Distinct from the prophet Samuel (ENT_ISR_SAMUEL, verified in DB) - homonym noted. Venerated human.'),
 ('ENT_COP_KYRILLOS_VI','Pope Kyrillos VI','Saint','Patriarch / pope','Coptic Christian','Coptic papacy, monastic revival','C','116th Pope of Alexandria (reigned 1959-1971), monastic-revival reformer, canonized by the Coptic Orthodox Church in 2013; placed in the modern period (re-pointed from the proposed late-antique Coptic period, which ends c.1000, to PER_MODERN_ORTHODOX). A 20th-century figure standing in the continuous Alexandrian papal tradition. Venerated human, not deified.'),
 ('ENT_COP_MENA_MARTYR','Mena the Wonderworker (Abu Mina)','Saint','Martyr / wonderworker','Coptic Christian','martyrdom, healing cult, pilgrimage','C','Egyptian (Coptic) reception of the soldier-martyr Menas, centre of the great healing-pilgrimage shrine of Abu Mina west of Alexandria. Cross-links to the existing pan-Orthodox Menas (ENT_ORTH_MENAS, verified in DB) as the same figure venerated in the Coptic tradition; flagged as a homonym/overlap in review.');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'devotional',conf,'candidate_verified_name','Roster build via gen_roster.py (see CHANGELOG/git for release)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,etype text,note text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_COP_FATHERS','SRC_DAVIS_EARLY_COPTIC_PAPACY','scholarly attestation','attestation'),
 ('ENT_COP_SHENOUTE','SRC_DAVIS_EARLY_COPTIC_PAPACY','scholarly attestation','attestation'),
 ('ENT_COP_BESA','SRC_DAVIS_EARLY_COPTIC_PAPACY','scholarly attestation','attestation'),
 ('ENT_COP_PACHOMIUS','SRC_DAVIS_EARLY_COPTIC_PAPACY','scholarly attestation','attestation'),
 ('ENT_COP_MACARIUS','SRC_DAVIS_EARLY_COPTIC_PAPACY','scholarly attestation','attestation'),
 ('ENT_COP_MOSES_BLACK','SRC_DAVIS_EARLY_COPTIC_PAPACY','scholarly attestation','attestation'),
 ('ENT_COP_SAMUEL_CONFESSOR','SRC_DAVIS_EARLY_COPTIC_PAPACY','scholarly attestation','attestation'),
 ('ENT_COP_KYRILLOS_VI','SRC_DAVIS_EARLY_COPTIC_PAPACY','scholarly attestation','attestation'),
 ('ENT_COP_MENA_MARTYR','SRC_DAVIS_EARLY_COPTIC_PAPACY','scholarly attestation','attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_COP_FATHERS','PER_EGY_COPTIC','Hub collective for the venerated abbots, patriarchs, and martyrs of the Egyptian (Coptic) Church; a grouping node, not a cultic figure.'),
 ('ENT_COP_SHENOUTE','PER_EGY_COPTIC','Archimandrite of the White Monastery near Sohag (d. c.465); the towering author of classical Sahidic Coptic literature, attested by his vast surviving corpus of sermons and letters and by Besa''s Life of Shenoute. Venerated human, not deified.'),
 ('ENT_COP_BESA','PER_EGY_COPTIC','Disciple and successor of Shenoute as head of the White Monastery; author of the Life of Shenoute and of monastic letters, attested by that surviving corpus.'),
 ('ENT_COP_PACHOMIUS','PER_EGY_COPTIC','Founder of cenobitic (communal) monasticism at Tabennesi (d. 348); attested by the Coptic and Greek Lives of Pachomius and his surviving Rule. Verified absent from DB. Venerated human.'),
 ('ENT_COP_MACARIUS','PER_EGY_COPTIC','Founder of the monastic settlement of Scetis (Wadi al-Natrun) in the Nitrian desert (d. c.391); attested in the Apophthegmata Patrum and the Lausiac History. Distinct from Macaria (ENT_MACARIA, a Greek goddess - homonym verified in DB) and Macarius of Alexandria. Verified absent from DB. Venerated human.'),
 ('ENT_COP_MOSES_BLACK','PER_EGY_COPTIC','Former brigand turned ascetic of Scetis under Macarius (d. c.405), martyred by raiding Berbers; attested in the Apophthegmata Patrum. Venerated human.'),
 ('ENT_COP_SAMUEL_CONFESSOR','PER_EGY_COPTIC','Seventh-century Coptic abbot of the Monastery of al-Qalamun (the Monastery of St Samuel) in the Fayyum, confessor under Chalcedonian and early Muslim-era pressure; attested by his Coptic Life. Distinct from the prophet Samuel (ENT_ISR_SAMUEL, verified in DB) - homonym noted. Venerated human.'),
 ('ENT_COP_KYRILLOS_VI','PER_MODERN_ORTHODOX','116th Pope of Alexandria (reigned 1959-1971), monastic-revival reformer, canonized by the Coptic Orthodox Church in 2013; placed in the modern period (re-pointed from the proposed late-antique Coptic period, which ends c.1000, to PER_MODERN_ORTHODOX). A 20th-century figure standing in the continuous Alexandrian papal tradition. Venerated human, not deified.'),
 ('ENT_COP_MENA_MARTYR','PER_EGY_COPTIC','Egyptian (Coptic) reception of the soldier-martyr Menas, centre of the great healing-pilgrimage shrine of Abu Mina west of Alexandria. Cross-links to the existing pan-Orthodox Menas (ENT_ORTH_MENAS, verified in DB) as the same figure venerated in the Coptic tradition; flagged as a homonym/overlap in review.');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_COP_SHENOUTE','member_of','ENT_COP_FATHERS','high','Shenoute is a venerated Coptic abbot-saint, a member of the Coptic Fathers hub (Davis).'),
 ('ENT_COP_BESA','member_of','ENT_COP_FATHERS','high','Besa, Shenoute''s successor at the White Monastery, is a venerated Coptic father.'),
 ('ENT_COP_PACHOMIUS','member_of','ENT_COP_FATHERS','high','Pachomius, founder of cenobitic monasticism in Egypt, is a foundational Coptic father.'),
 ('ENT_COP_MACARIUS','member_of','ENT_COP_FATHERS','high','Macarius of Egypt, founder of Scetis, is a foundational Coptic desert father.'),
 ('ENT_COP_MOSES_BLACK','member_of','ENT_COP_FATHERS','high','Moses the Black, monk-martyr of Scetis, is a venerated Coptic father.'),
 ('ENT_COP_SAMUEL_CONFESSOR','member_of','ENT_COP_FATHERS','high','Samuel the Confessor, abbot of al-Qalamun, is a venerated Coptic father.'),
 ('ENT_COP_KYRILLOS_VI','member_of','ENT_COP_FATHERS','high','Pope Kyrillos VI, canonized Coptic patriarch, belongs to the Coptic Fathers and Saints hub.'),
 ('ENT_COP_MENA_MARTYR','member_of','ENT_COP_FATHERS','high','Mena/Abu Mina, the great Coptic healing-martyr, is a venerated Coptic saint.'),
 ('ENT_COP_BESA','taught_by','ENT_COP_SHENOUTE','high','Besa was the disciple of Shenoute and succeeded him as archimandrite of the White Monastery (Davis; Besa''s own Life of Shenoute).'),
 ('ENT_COP_MOSES_BLACK','taught_by','ENT_COP_MACARIUS','medium','Moses the Black became a monk of Scetis under the spiritual direction of Macarius of Egypt (Apophthegmata Patrum).'),
 ('ENT_SAINT_ANTHONY_ABBOT','member_of','ENT_COP_FATHERS','high','Anthony the Great (existing ENT_SAINT_ANTHONY_ABBOT, verified in DB), the Egyptian father of monasticism, is venerated as the foremost Coptic father; wiring the existing entity into the Coptic hub.'),
 ('ENT_COP_PACHOMIUS','reception_of','ENT_SAINT_ANTHONY_ABBOT','medium','Pachomian cenobitism develops the Egyptian eremitic ideal pioneered by Anthony the Great, the model anchorite (Davis); object verified to exist in DB.'),
 ('ENT_COP_MACARIUS','reception_of','ENT_SAINT_ANTHONY_ABBOT','medium','Macarius of Egypt is portrayed in the Apophthegmata as carrying forward the desert ascetic tradition founded by Anthony the Great; object verified to exist in DB.'),
 ('ENT_ORTH_ATHANASIUS','member_of','ENT_COP_FATHERS','high','Athanasius of Alexandria (existing ENT_ORTH_ATHANASIUS, verified in DB), the Coptic patriarch and biographer of Anthony, is a foundational Coptic father; wiring the existing entity into the Coptic hub.'),
 ('ENT_COP_KYRILLOS_VI','reception_of','ENT_ORTH_ATHANASIUS','medium','As a successor Pope of Alexandria, Kyrillos VI stands in the continuous Alexandrian patriarchal line whose great early model is Athanasius (Davis, on the papal succession); object verified to exist in DB.'),
 ('ENT_COP_MENA_MARTYR','received_as','ENT_ORTH_MENAS','high','The Coptic wonderworker Mena (Abu Mina) is the Egyptian/Coptic reception of the same soldier-martyr venerated pan-Orthodox as Menas (existing ENT_ORTH_MENAS, verified in DB); same figure, flagged as a homonym/overlap.');

\echo '--- REJECTED edges (bad id/type, or subject lacks a source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
