-- build_p6_realms_iranian_meso_jewish.sql  (GENERATED by gen_roster.py p6_realms_iranian_meso_jewish) — v1.80.0
-- 9 entities, 27 edges, 0 new periods, 3 new sources. Idempotent + self-validating.
BEGIN;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_VENDIDAD','primary text','Vendidad (Videvdad, ''Law against the Demons''), Younger Avesta, ed./trans. J. Darmesteter, SBE 4','Zoroastrian law, eschatology, and cosmography incl. the Chinvat Bridge and post-mortem realms'),
 ('SRC_DESCENT_ISHTAR','primary text','The Descent of Ishtar to the Netherworld (Akkadian), trans. S. Dalley, Myths from Mesopotamia (Oxford University Press, 2000)','Mesopotamian netherworld (Irkalla/Kur), its gates, and Ereshkigal''s rule'),
 ('SRC_HEKHALOT_RABBATI','primary text','Hekhalot Rabbati (''The Greater Palaces''), Merkavah text, ed. in P. Schafer, Synopse zur Hekhalot-Literatur','The seven heavenly palaces (hekhalot) and the ascent of the descender to the chariot')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,trad text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_RLMX_CHINVAT','Chinvat Bridge','Cosmological realm','Cosmological realm','Zoroastrian','Eschatology / judgement of the soul','B','The Cinvat (Chinvat) Bridge, the ''bridge of the separator/accountant'' which every soul must cross after death; attested in the Gathas (Y. 46.10, 51.13) and the Vendidad (19), where Rashnu, Mithra and Sraosha judge and the Daena meets the soul. Widens for the righteous, narrows to a blade for the wicked.'),
 ('ENT_RLMX_GAROTHMAN','Garothman (House of Song)','Cosmological realm','Cosmological realm','Zoroastrian','Paradise / best existence','B','Garothman / Garodman, the ''House of Song'' (Avestan Garo-demana), the highest paradise and abode of Ahura Mazda and the blessed (the ''Best Existence'', vahishta ahu). Attested in the Avesta and elaborated in the Bundahishn and Menog-i Khrad.'),
 ('ENT_RLMX_DRUJO_DEMANA','Drujo Demana (House of Lies)','Cosmological realm','Cosmological realm','Zoroastrian','Hell / worst existence','B','Drujo Demana, the ''House of the Lie'' (Avestan druj-demana), the Zoroastrian hell and abode of Angra Mainyu and the damned (the ''Worst Existence''). Antithesis of the House of Song; attested in the Gathas (Y. 46.11, 49.11) and Pahlavi eschatology.'),
 ('ENT_RLMX_HAMISTAGAN','Hamistagan','Cosmological realm','Cosmological realm','Zoroastrian','Limbo / neutral intermediate state','B','Hamistagan (Pahlavi hammistagan), the neutral ''place of the mixed'', an intermediate state for souls whose good and evil deeds are exactly balanced; they remain there, untormented but joyless, until the final renovation (Frashokereti). Attested in the Bundahishn and Menog-i Khrad.'),
 ('ENT_RLMX_IRKALLA','Irkalla (Kur)','Cosmological realm','Cosmological realm','Mesopotamian','Netherworld / land of the dead','B','Irkalla (Sumerian Kur, the ''land of no return''), the Mesopotamian underworld ruled by Ereshkigal (and Nergal), a dark dust-filled realm where the dead eat clay. Attested in the Descent of Ishtar and the Descent of Inanna. NOTE: distinct from the being Apsu (ENT_MES_APSU); this is the place.'),
 ('ENT_RLMX_GANZIR','Ganzir','Cosmological realm','Cosmological realm','Mesopotamian','Gate of the netherworld','C','Ganzir, the gate / threshold (the ''face'') of the netherworld Irkalla/Kur, sometimes used as a name for the underworld''s entrance through which the dead pass the seven gates. Attested in the Descent of Inanna/Ishtar tradition.'),
 ('ENT_RLMX_DILMUN','Dilmun','Cosmological realm','Cosmological realm','Mesopotamian','Pure land / paradise','B','Dilmun, the ''pure, clean, bright'' land where there is no death or sickness, watered with fresh water by Enki; the Sumerian paradise (and a real geographical region, Bahrain). Attested in the myth Enki and Ninhursag.'),
 ('ENT_RLMX_SEVEN_HEAVENS','The Seven Heavens (Vilon, Raqia, Shehaqim, Zebul, Maon, Makhon, Araboth)','Cosmological structure','Cosmological structure','Jewish Mystical','Vertical celestial cosmography','B','The seven heavens of rabbinic/Merkavah cosmology, named in b. Hagigah 12b: Vilon, Raqia, Shehaqim, Zebul, Maon, Makhon, and Araboth (the highest, housing the Throne of Glory). Distinct from the seven firmaments of Sefer ha-Razim.'),
 ('ENT_RLMX_SEVEN_HEKHALOT','The Seven Hekhalot (Heavenly Palaces)','Cosmological structure','Cosmological structure','Jewish Mystical','Merkavah ascent / celestial palaces','B','The seven hekhalot (''palaces''/''halls'') nested within the highest heaven (Araboth), each guarded by angelic gatekeepers, through which the yored merkavah (''descender to the chariot'') ascends to the Throne. Attested in Hekhalot Rabbati.');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'devotional',conf,'candidate_verified_name','Roster build via gen_roster.py (see CHANGELOG/git for release)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,etype text,note text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_RLMX_CHINVAT','SRC_VENDIDAD','primary text attestation','attestation'),
 ('ENT_RLMX_GAROTHMAN','SRC_BUNDAHISHN','scholarly attestation','attestation'),
 ('ENT_RLMX_DRUJO_DEMANA','SRC_MENOG_I_KHRAD','scholarly attestation','attestation'),
 ('ENT_RLMX_HAMISTAGAN','SRC_MENOG_I_KHRAD','scholarly attestation','attestation'),
 ('ENT_RLMX_IRKALLA','SRC_DESCENT_ISHTAR','primary text attestation','attestation'),
 ('ENT_RLMX_GANZIR','SRC_DESCENT_ISHTAR','primary text attestation','attestation'),
 ('ENT_RLMX_DILMUN','SRC_DESCENT_ISHTAR','primary text attestation','attestation'),
 ('ENT_RLMX_SEVEN_HEAVENS','SRC_3_ENOCH','scholarly attestation','attestation'),
 ('ENT_RLMX_SEVEN_HEKHALOT','SRC_HEKHALOT_RABBATI','primary text attestation','attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_RLMX_CHINVAT','PER_ZOR_ACHAEMENID','The Cinvat (Chinvat) Bridge, the ''bridge of the separator/accountant'' which every soul must cross after death; attested in the Gathas (Y. 46.10, 51.13) and the Vendidad (19), where Rashnu, Mithra and Sraosha judge and the Daena meets the soul. Widens for the righteous, narrows to a blade for the wicked.'),
 ('ENT_RLMX_GAROTHMAN','PER_ZOR_SASANIAN','Garothman / Garodman, the ''House of Song'' (Avestan Garo-demana), the highest paradise and abode of Ahura Mazda and the blessed (the ''Best Existence'', vahishta ahu). Attested in the Avesta and elaborated in the Bundahishn and Menog-i Khrad.'),
 ('ENT_RLMX_DRUJO_DEMANA','PER_ZOR_SASANIAN','Drujo Demana, the ''House of the Lie'' (Avestan druj-demana), the Zoroastrian hell and abode of Angra Mainyu and the damned (the ''Worst Existence''). Antithesis of the House of Song; attested in the Gathas (Y. 46.11, 49.11) and Pahlavi eschatology.'),
 ('ENT_RLMX_HAMISTAGAN','PER_ZOR_SASANIAN','Hamistagan (Pahlavi hammistagan), the neutral ''place of the mixed'', an intermediate state for souls whose good and evil deeds are exactly balanced; they remain there, untormented but joyless, until the final renovation (Frashokereti). Attested in the Bundahishn and Menog-i Khrad.'),
 ('ENT_RLMX_IRKALLA','PER_MES_OLD_BAB','Irkalla (Sumerian Kur, the ''land of no return''), the Mesopotamian underworld ruled by Ereshkigal (and Nergal), a dark dust-filled realm where the dead eat clay. Attested in the Descent of Ishtar and the Descent of Inanna. NOTE: distinct from the being Apsu (ENT_MES_APSU); this is the place.'),
 ('ENT_RLMX_GANZIR','PER_MES_OLD_BAB','Ganzir, the gate / threshold (the ''face'') of the netherworld Irkalla/Kur, sometimes used as a name for the underworld''s entrance through which the dead pass the seven gates. Attested in the Descent of Inanna/Ishtar tradition.'),
 ('ENT_RLMX_DILMUN','PER_MES_EARLY','Dilmun, the ''pure, clean, bright'' land where there is no death or sickness, watered with fresh water by Enki; the Sumerian paradise (and a real geographical region, Bahrain). Attested in the myth Enki and Ninhursag.'),
 ('ENT_RLMX_SEVEN_HEAVENS','PER_JM_HEKHALOT','The seven heavens of rabbinic/Merkavah cosmology, named in b. Hagigah 12b: Vilon, Raqia, Shehaqim, Zebul, Maon, Makhon, and Araboth (the highest, housing the Throne of Glory). Distinct from the seven firmaments of Sefer ha-Razim.'),
 ('ENT_RLMX_SEVEN_HEKHALOT','PER_JM_HEKHALOT','The seven hekhalot (''palaces''/''halls'') nested within the highest heaven (Araboth), each guarded by angelic gatekeepers, through which the yored merkavah (''descender to the chariot'') ascends to the Throne. Attested in Hekhalot Rabbati.');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_RLMX_CHINVAT','guarded_by','ENT_ZOR_RASHNU','high','Rashnu the Just is the yazata who weighs souls'' deeds at the Chinvat Bridge (Vendidad 19).'),
 ('ENT_ZOR_RASHNU','presides_over','ENT_RLMX_CHINVAT','high','Rashnu presides over the judgement of the soul at the Chinvat Bridge (was ''judges''; corrected to presides_over since judges takes a being/Dead object in house convention).'),
 ('ENT_ZOR_MITHRA','presides_over','ENT_RLMX_CHINVAT','medium','Mithra is one of the three judging yazatas at the Chinvat Bridge in Zoroastrian eschatology.'),
 ('ENT_ZOR_SRAOSHA','associated_with','ENT_RLMX_CHINVAT','medium','Sraosha conducts and protects the soul on its passage across the bridge (was ''guides''; corrected since guides takes a being/Dead object).'),
 ('ENT_ZOR_DAENA','associated_with','ENT_RLMX_CHINVAT','high','The Daena, the personified conscience, meets the soul at the Chinvat Bridge and leads the righteous onward.'),
 ('ENT_RLMX_GAROTHMAN','dwelling_of','ENT_ZOR_AHURA_MAZDA','high','Garothman, the House of Song, is the abode of Ahura Mazda and the blessed.'),
 ('ENT_RLMX_DRUJO_DEMANA','dwelling_of','ENT_ZOR_ANGRA_MAINYU','high','Drujo Demana, the House of Lies, is the abode of Angra Mainyu and the damned.'),
 ('ENT_RLMX_DRUJO_DEMANA','opposes','ENT_RLMX_GAROTHMAN','high','The House of Lies is the structural antithesis of the House of Song in Zoroastrian eschatology.'),
 ('ENT_RLMX_GAROTHMAN','associated_with','ENT_RLMX_CHINVAT','high','The righteous soul reaches Garothman by crossing the Chinvat Bridge.'),
 ('ENT_RLMX_DRUJO_DEMANA','associated_with','ENT_RLMX_CHINVAT','high','The wicked soul falls from the Chinvat Bridge into the House of Lies.'),
 ('ENT_RLMX_HAMISTAGAN','opposes','ENT_RLMX_GAROTHMAN','medium','Hamistagan is the neutral middle state distinct from both paradise (Garothman) and hell.'),
 ('ENT_RLMX_HAMISTAGAN','associated_with','ENT_ZOR_SAOSHYANT','medium','Souls in Hamistagan await release at the final renovation brought by the Saoshyant (Frashokereti).'),
 ('ENT_RLMX_IRKALLA','ruled_by','ENT_MES_ERESHKIGAL','high','Ereshkigal is queen of Irkalla/Kur, the Mesopotamian netherworld (Descent of Ishtar).'),
 ('ENT_MES_ERESHKIGAL','rules','ENT_RLMX_IRKALLA','high','Ereshkigal rules the land of no return.'),
 ('ENT_MES_NERGAL','rules','ENT_RLMX_IRKALLA','high','Nergal becomes consort and co-ruler of the netherworld with Ereshkigal.'),
 ('ENT_RLMX_GANZIR','belongs_to_realm','ENT_RLMX_IRKALLA','high','Ganzir is the gate/threshold belonging to the netherworld Irkalla (was ''part_of'', which is not a valid relationship_type; belongs_to_realm is attested for place-within-realm).'),
 ('ENT_MES_INANNA_ISHTAR','associated_with','ENT_RLMX_IRKALLA','high','Ishtar descends into Irkalla and is detained there in the Descent of Ishtar.'),
 ('ENT_RLMX_DILMUN','associated_with','ENT_MES_ENKI_EA','high','Enki provides fresh water to Dilmun in the myth Enki and Ninhursag, making it the pure land.'),
 ('ENT_RLMX_DILMUN','opposes','ENT_RLMX_IRKALLA','medium','Dilmun, the deathless pure land, stands in mythic contrast to the netherworld of death.'),
 ('ENT_RLMX_SEVEN_HEAVENS','associated_with','ENT_RLMX_SEVEN_HEKHALOT','high','The seven hekhalot are situated within Araboth, the seventh of the seven heavens.'),
 ('ENT_RLMX_SEVEN_HEKHALOT','belongs_to_realm','ENT_RLMX_SEVEN_HEAVENS','high','The seven palaces are contained within the highest heaven of the sevenfold cosmos (was ''part_of'', invalid; belongs_to_realm is the attested place-within-realm type).'),
 ('ENT_RLMX_SEVEN_HEKHALOT','guarded_by','ENT_JM_HEAVENLY_HOST','medium','Angelic gatekeepers of the Heavenly Host guard the entrances to each of the seven palaces in Hekhalot Rabbati.'),
 ('ENT_RLMX_SEVEN_HEKHALOT','associated_with','ENT_JM_METATRON','medium','Metatron, the heavenly prince/scribe, presides over the upper palaces and the Throne in Merkavah literature.'),
 ('ENT_RLMX_SEVEN_HEAVENS','associated_with','ENT_THRONE','high','Araboth, the seventh heaven, houses the Throne of Glory.'),
 ('ENT_RLMX_SEVEN_HEAVENS','associated_with','ENT_JM_SEVEN_FIRMAMENTS','medium','The rabbinic/Merkavah seven heavens parallel but are distinct from the seven firmaments of Sefer ha-Razim.'),
 ('ENT_RLMX_SEVEN_HEAVENS','aligned_with','ENT_JM_ATZILUTH','low','Both are vertical hierarchies of the Jewish-mystical cosmos; the four Kabbalistic worlds are a later systematization overlapping the heavens schema.'),
 ('ENT_RLMX_SEVEN_HEAVENS','opposes','ENT_JM_GEHENNA','medium','The ascending heavens stand opposite Gehenna, the lower realm of punishment, in Jewish cosmology.');

\echo '--- REJECTED edges (bad id/type, or subject lacks a source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
