-- v2.1.85  Dictionary-format SECONDARY citations from the 2026-09 library expansion
-- Netton, A Popular Dictionary of Islam (1992); Davidson, A Dictionary of Angels (1967); Piwowarczyk Lexicon (2023);
-- Evans (2015) and Widengren (1946) pointers. In-copyright: quotes are brief attributed headword excerpts (Renard precedent)
-- or NULL pointers; every excerpt gated as a contiguous substring of the extraction. Existing citations PRESERVED (INSERT only).
BEGIN;

INSERT INTO sources (source_id, title, url, source_type, scope) VALUES ('SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', '', 'secondary scholarship (dictionary)', 'NEW - concise headword dictionary; used for the Islamic eschatological/angelic residue and the Twelver Imams') ON CONFLICT (source_id) DO NOTHING;
INSERT INTO sources (source_id, title, url, source_type, scope) VALUES ('SRC_LIB_EVANS_BOOKS_OF_JEU', 'Erin Evans, The Books of Jeu and the Pistis Sophia as Handbooks to Eternity (Brill, 2015)', '', 'secondary scholarship', 'NEW - monograph on the Bruce and Askew codices; pointers only') ON CONFLICT (source_id) DO NOTHING;
INSERT INTO sources (source_id, title, url, source_type, scope) VALUES ('SRC_LIB_WIDENGREN_KING_SAVIOUR_II', 'Geo Widengren, Mesopotamian Elements in Manichaeism (King and Saviour II) (Uppsala, 1946)', '', 'secondary scholarship', 'NEW - Manichaean/Mandaean comparative study; pointers only') ON CONFLICT (source_id) DO NOTHING;

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISL_AZRAIL_NETTON', 'ENT_ISL_AZRAIL', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "‘Izrā’īl"', 'Izrā’īl (Ar.) Azrael. He is the principal Islamic angel of death with a reputation in tradition for toughness and ruthlessness.', 'secondary', 'Dictionary entry on the angel of death; notes he is unnamed in the Qur''an (Malak al-Mawt, 32:11).', DATE '2026-09-18', 'full-text extraction (EPUB); headword entry located by accent-insensitive search (the diacritics defeat plain search), entry read to confirm it treats THIS figure; brief attributed excerpt limited to the entry''s opening definition (in-copyright dictionary, cf. the Renard precedent); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISL_AZRAIL_NETTON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISL_MIKAIL_NETTON', 'ENT_ISL_MIKAIL', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "Mīkā’īl"', 'Mīkā’īl (Ar.) Michael, one of the great Islamic angels. He is mentioned once in the Qur''ān in the company of Jibrīl (q.v.).', 'secondary', 'Dictionary entry on Mika''il.', DATE '2026-09-18', 'full-text extraction (EPUB); headword entry located by accent-insensitive search (the diacritics defeat plain search), entry read to confirm it treats THIS figure; brief attributed excerpt limited to the entry''s opening definition (in-copyright dictionary, cf. the Renard precedent); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISL_MIKAIL_NETTON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISL_MUNKAR_NETTON', 'ENT_ISL_MUNKAR', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "Munkar and Nakīr"', 'Munkar and Nakīr The Angels of the Grave. These two angels, who play a significant role in the afterlife of man, are described principally in the tradition literature and do not appear in the Qur''ān by name', 'secondary', 'Dictionary entry on the two interrogating angels of the grave.', DATE '2026-09-18', 'full-text extraction (EPUB); headword entry located by accent-insensitive search (the diacritics defeat plain search), entry read to confirm it treats THIS figure; brief attributed excerpt limited to the entry''s opening definition (in-copyright dictionary, cf. the Renard precedent); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISL_MUNKAR_NETTON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISL_NAKIR_NETTON', 'ENT_ISL_NAKIR', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "Munkar and Nakīr"', 'Munkar and Nakīr The Angels of the Grave. These two angels, who play a significant role in the afterlife of man, are described principally in the tradition literature and do not appear in the Qur''ān by name', 'secondary', 'Dictionary entry on the two interrogating angels of the grave.', DATE '2026-09-18', 'full-text extraction (EPUB); headword entry located by accent-insensitive search (the diacritics defeat plain search), entry read to confirm it treats THIS figure; brief attributed excerpt limited to the entry''s opening definition (in-copyright dictionary, cf. the Renard precedent); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISL_NAKIR_NETTON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISL_ISRAFIL_NETTON', 'ENT_ISL_ISRAFIL', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "Isrāfīl"', NULL, 'secondary', 'Netton''s ''Angel'' entry refers the reader to a dedicated entry ''Isrāfīl''; pointer only (entry not machine-located in the extraction).', DATE '2026-09-18', 'headword entry confirmed in the pdftotext/EPUB extraction (or by the dictionary''s own cross-reference); NO text reproduced - pointer only', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISL_ISRAFIL_NETTON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISL_DAJJAL_NETTON', 'ENT_ISL_DAJJAL', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "al-Dajjāl"', 'al-Dajjāl (Ar.) The word derives from Syriac and means ‘the Cheat’ or ‘the Charlatan’. It is often translated to signify an Islamic ‘anti-Christ’.', 'secondary', 'Dictionary entry on the eschatological Dajjal.', DATE '2026-09-18', 'full-text extraction (EPUB); headword entry located by accent-insensitive search (the diacritics defeat plain search), entry read to confirm it treats THIS figure; brief attributed excerpt limited to the entry''s opening definition (in-copyright dictionary, cf. the Renard precedent); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISL_DAJJAL_NETTON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISLR_JAHANNAM_NETTON', 'ENT_ISLR_JAHANNAM', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "Jahannam"', 'Jahannam (Ar.) Gehenna. This is one of the seven ranks of Hell.', 'secondary', 'Dictionary entry; notes the word occurs 77 times in the Qur''an.', DATE '2026-09-18', 'full-text extraction (EPUB); headword entry located by accent-insensitive search (the diacritics defeat plain search), entry read to confirm it treats THIS figure; brief attributed excerpt limited to the entry''s opening definition (in-copyright dictionary, cf. the Renard precedent); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISLR_JAHANNAM_NETTON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISLR_SAQAR_NETTON', 'ENT_ISLR_SAQAR', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "Saqar"', 'Saqar (Ar.) One of the seven ranks of Hell (q.v.). Saqar is the scorching fire to which tradition assigns the Zoroastrians.', 'secondary', 'Dictionary entry on Saqar.', DATE '2026-09-18', 'full-text extraction (EPUB); headword entry located by accent-insensitive search (the diacritics defeat plain search), entry read to confirm it treats THIS figure; brief attributed excerpt limited to the entry''s opening definition (in-copyright dictionary, cf. the Renard precedent); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISLR_SAQAR_NETTON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISLR_SAIR_NETTON', 'ENT_ISLR_SAIR', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "Sa‘īr"', 'Sa‘īr (Ar.) One of the seven ranks of Hell. According to tradition Sa’īr is the blazing inferno in which Sabaeans (q.v.) will burn.', 'secondary', 'Dictionary entry on Sa''ir.', DATE '2026-09-18', 'full-text extraction (EPUB); headword entry located by accent-insensitive search (the diacritics defeat plain search), entry read to confirm it treats THIS figure; brief attributed excerpt limited to the entry''s opening definition (in-copyright dictionary, cf. the Renard precedent); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISLR_SAIR_NETTON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISLR_HUTAMAH_NETTON', 'ENT_ISLR_HUTAMAH', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "al-Ḥuṭama"', 'al-Ḥuṭama (Ar.) Literally, ‘that which shatters, wrecks or smashes’. Al-Hutama is one of the seven ranks of Hell to which tradition later assigned the Jews.', 'secondary', 'Dictionary entry on al-Hutama (Qur''an 104:4-6).', DATE '2026-09-18', 'full-text extraction (EPUB); headword entry located by accent-insensitive search (the diacritics defeat plain search), entry read to confirm it treats THIS figure; brief attributed excerpt limited to the entry''s opening definition (in-copyright dictionary, cf. the Renard precedent); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISLR_HUTAMAH_NETTON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISLR_JAHIM_NETTON', 'ENT_ISLR_JAHIM', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "al-Jaḥīm"', 'al-Jaḥīm (Ar.) One of the seven ranks of Hell. The word appears 25 times in the Qur''ān and is the region of Hell to which tradition consigns idolaters.', 'secondary', 'Dictionary entry on al-Jahim.', DATE '2026-09-18', 'full-text extraction (EPUB); headword entry located by accent-insensitive search (the diacritics defeat plain search), entry read to confirm it treats THIS figure; brief attributed excerpt limited to the entry''s opening definition (in-copyright dictionary, cf. the Renard precedent); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISLR_JAHIM_NETTON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISLR_ARAF_NETTON', 'ENT_ISLR_ARAF', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "al-A‘rāf"', 'The title refers to an apparently intermediate place or state (see vv.46-48), not in Paradise or Hell, inhabited by those whose good and bad deeds are equal.', 'secondary', 'Dictionary entry on Surat al-A''raf, defining al-A''raf as the intermediate place of Qur''an 7:46-48.', DATE '2026-09-18', 'full-text extraction (EPUB); headword entry located by accent-insensitive search (the diacritics defeat plain search), entry read to confirm it treats THIS figure; brief attributed excerpt limited to the entry''s opening definition (in-copyright dictionary, cf. the Renard precedent); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISLR_ARAF_NETTON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISL_KHADIJAH_NETTON', 'ENT_ISL_KHADIJAH', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "Khadīja bint Khuwaylid"', 'Khadīja bint Khuwaylid (c. AD 554-AD 619) First wife of the Prophet Muḥammad and also revered as the first Muslim after him.', 'secondary', 'Dictionary entry on Khadija.', DATE '2026-09-18', 'full-text extraction (EPUB); headword entry located by accent-insensitive search (the diacritics defeat plain search), entry read to confirm it treats THIS figure; brief attributed excerpt limited to the entry''s opening definition (in-copyright dictionary, cf. the Renard precedent); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISL_KHADIJAH_NETTON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISL_SAFIYYA_NETTON', 'ENT_ISL_SAFIYYA', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "Ṣafiyya bint Ḥuyayy"', 'Ṣafiyya bint ḥuyayy One of the wives of the Prophet Muḥammad. She was a Jewess, captured at Khaybar (q.v.), but was freed on conversion to Islam.', 'secondary', 'Dictionary entry on Safiyya.', DATE '2026-09-18', 'full-text extraction (EPUB); headword entry located by accent-insensitive search (the diacritics defeat plain search), entry read to confirm it treats THIS figure; brief attributed excerpt limited to the entry''s opening definition (in-copyright dictionary, cf. the Renard precedent); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISL_SAFIYYA_NETTON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISL_SAWDA_NETTON', 'ENT_ISL_SAWDA', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "Sawda bint Zam‘a"', 'Sawda bint Zam‘a A wife of the Prophet Muḥammad and a member of the tribe of Quraysh (q.v.).', 'secondary', 'Dictionary entry on Sawda.', DATE '2026-09-18', 'full-text extraction (EPUB); headword entry located by accent-insensitive search (the diacritics defeat plain search), entry read to confirm it treats THIS figure; brief attributed excerpt limited to the entry''s opening definition (in-copyright dictionary, cf. the Renard precedent); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISL_SAWDA_NETTON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISL_ABU_HURAYRA_NETTON', 'ENT_ISL_ABU_HURAYRA', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "Abū Hurayra"', 'Abū Hurayra (died c. 58/678) Name of one of Muḥammad’s companions. His reputation is mainly based, however, on the huge number of traditions which he is said to have narrated.', 'secondary', 'Dictionary entry on Abu Hurayra.', DATE '2026-09-18', 'full-text extraction (EPUB); headword entry located by accent-insensitive search (the diacritics defeat plain search), entry read to confirm it treats THIS figure; brief attributed excerpt limited to the entry''s opening definition (in-copyright dictionary, cf. the Renard precedent); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISL_ABU_HURAYRA_NETTON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_SUF_IBN_ARABI_NETTON', 'ENT_SUF_IBN_ARABI', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "Ibn al-‘Arabī"', 'Ibn al-‘Arabī (560/1165-638/1240) One of the great ṣūfī (q.v.) masters of all time, deservedly referred to as ‘The Greatest Shaykh’ (al-Shaykh al-Akbar).', 'secondary', 'Dictionary entry on Ibn al-Arabi.', DATE '2026-09-18', 'full-text extraction (EPUB); headword entry located by accent-insensitive search (the diacritics defeat plain search), entry read to confirm it treats THIS figure; brief attributed excerpt limited to the entry''s opening definition (in-copyright dictionary, cf. the Renard precedent); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_SUF_IBN_ARABI_NETTON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISL_QUTB_NETTON', 'ENT_ISL_QUTB', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "Quṭb"', 'Quṭb (Ar.) [pl. aqṭāb] In the technical terminology of taṣawwuf (q.v.) this word means ‘pole’, ‘pivot’ or ‘axis’ and designates the Head of the saints (awliyā’), although other saints have been honoured by the title as well.', 'secondary', 'Dictionary entry on the Sufi qutb.', DATE '2026-09-18', 'full-text extraction (EPUB); headword entry located by accent-insensitive search (the diacritics defeat plain search), entry read to confirm it treats THIS figure; brief attributed excerpt limited to the entry''s opening definition (in-copyright dictionary, cf. the Renard precedent); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISL_QUTB_NETTON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISL_ZAYN_ABIDIN_NETTON', 'ENT_ISL_ZAYN_ABIDIN', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "‘Alī Zayn ’l-‘Ābidīn"', 'Alī Zayn ’l-‘Ābidīn (36/658-94/712 or 95/713) Fourth Shī‘ite Imam. His full name was Abū Muḥammad ‘Alī b. al-Ḥusayn.', 'secondary', 'Dictionary entry on the fourth Imam.', DATE '2026-09-18', 'full-text extraction (EPUB); headword entry located by accent-insensitive search (the diacritics defeat plain search), entry read to confirm it treats THIS figure; brief attributed excerpt limited to the entry''s opening definition (in-copyright dictionary, cf. the Renard precedent); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISL_ZAYN_ABIDIN_NETTON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISL_BAQIR_NETTON', 'ENT_ISL_BAQIR', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "Muḥammad al-Bāqir"', 'Muḥammad al-Bāqir (57/676- died between 114/732 and 126/743) Fifth Shī‘ite Imām. He was the grandson of the Second Shī‘ite Imām, al-Ḥasan b. ‘Alī (q.v.).', 'secondary', 'Dictionary entry on the fifth Imam.', DATE '2026-09-18', 'full-text extraction (EPUB); headword entry located by accent-insensitive search (the diacritics defeat plain search), entry read to confirm it treats THIS figure; brief attributed excerpt limited to the entry''s opening definition (in-copyright dictionary, cf. the Renard precedent); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISL_BAQIR_NETTON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISL_KAZIM_NETTON', 'ENT_ISL_KAZIM', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "Mūsā al-Kāẓim"', 'Mūsā al-Kāẓim (c. 128/745-183/799) Seventh Imām for the Ithnā ‘Asharīs (q.v.), and a younger son of Ja‘far al-Ṣādiq (q.v.).', 'secondary', 'Dictionary entry on the seventh Imam.', DATE '2026-09-18', 'full-text extraction (EPUB); headword entry located by accent-insensitive search (the diacritics defeat plain search), entry read to confirm it treats THIS figure; brief attributed excerpt limited to the entry''s opening definition (in-copyright dictionary, cf. the Renard precedent); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISL_KAZIM_NETTON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISL_RIDA_NETTON', 'ENT_ISL_RIDA', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "‘Alī al-Riḍā"', 'Alī al-Riḍā (c. 148/765-203/818) Eighth Shī‘ite Imām. His full name was Abū ’l-Ḥasan ‘Alī b. Mūsā.', 'secondary', 'Dictionary entry on the eighth Imam.', DATE '2026-09-18', 'full-text extraction (EPUB); headword entry located by accent-insensitive search (the diacritics defeat plain search), entry read to confirm it treats THIS figure; brief attributed excerpt limited to the entry''s opening definition (in-copyright dictionary, cf. the Renard precedent); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISL_RIDA_NETTON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISL_JAWAD_NETTON', 'ENT_ISL_JAWAD', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "Muḥammad al-Taqī"', 'Muḥammad al-Taqī (195/810-220/835) Ninth Shī‘ite Imām of the Ithnā ‘Asharīs (q.v.). He was the son of ‘Alī al-Riḍā (q.v.).', 'secondary', 'Dictionary entry on the ninth Imam under his other epithet al-Taqi (= Muhammad al-Jawad).', DATE '2026-09-18', 'full-text extraction (EPUB); headword entry located by accent-insensitive search (the diacritics defeat plain search), entry read to confirm it treats THIS figure; brief attributed excerpt limited to the entry''s opening definition (in-copyright dictionary, cf. the Renard precedent); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISL_JAWAD_NETTON');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_ISL_JAWAD', 'Muhammad al-Taqi', 'transliteration variant (Netton 1992)', 'SRC_NETTON_DICT_ISLAM', 'high', 'needs_review', 'Netton, A Popular Dictionary of Islam'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_ISL_JAWAD' AND alias_name='Muhammad al-Taqi');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISL_HADI_NETTON', 'ENT_ISL_HADI', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "‘Alī al-Hādī"', 'Alī al-Hādī (c. 212/827-214/829-254/868) Tenth Shī‘ite Imām. His full name was Abū ’l-Ḥasan ‘Alī b. Muḥammad.', 'secondary', 'Dictionary entry on the tenth Imam.', DATE '2026-09-18', 'full-text extraction (EPUB); headword entry located by accent-insensitive search (the diacritics defeat plain search), entry read to confirm it treats THIS figure; brief attributed excerpt limited to the entry''s opening definition (in-copyright dictionary, cf. the Renard precedent); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISL_HADI_NETTON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISL_ASKARI_NETTON', 'ENT_ISL_ASKARI', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "Ḥasan al-‘Askarī"', 'Ḥasan al-‘Askarī (230/844-260/874) Eleventh Shi‘ite Imām.', 'secondary', 'Dictionary entry on the eleventh Imam.', DATE '2026-09-18', 'full-text extraction (EPUB); headword entry located by accent-insensitive search (the diacritics defeat plain search), entry read to confirm it treats THIS figure; brief attributed excerpt limited to the entry''s opening definition (in-copyright dictionary, cf. the Renard precedent); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISL_ASKARI_NETTON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISL_HASAN_NETTON', 'ENT_ISL_HASAN', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "al-Ḥasan b. ‘Alī"', 'al-Ḥasan b. ‘Alī (3/624-5-c. 49/669-70) Son of ‘Alī b. Abī Ṭālib (q.v.) and Fāṭima (q.v.), grandson and favourite, with his brother al-Ḥusayn b. ‘Alī (q.v.), of the Prophet Muḥammad, and Second Shī‘ite Imām.', 'secondary', 'Dictionary entry on the second Imam.', DATE '2026-09-18', 'full-text extraction (EPUB); headword entry located by accent-insensitive search (the diacritics defeat plain search), entry read to confirm it treats THIS figure; brief attributed excerpt limited to the entry''s opening definition (in-copyright dictionary, cf. the Renard precedent); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISL_HASAN_NETTON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_ISL_MAHDI_NETTON', 'ENT_ISL_MAHDI', 'SRC_NETTON_DICT_ISLAM', 'Ian Richard Netton, A Popular Dictionary of Islam (London: Curzon Press, 1992)', 's.v. "Muḥammad al-Qā’im"', NULL, 'secondary', 'Netton''s cross-reference ''Hidden Imām See Muḥammad al-Qā’im'' confirms a dedicated entry on the twelfth Imam under the epithet al-Qa''im; pointer only.', DATE '2026-09-18', 'headword entry confirmed in the pdftotext/EPUB extraction (or by the dictionary''s own cross-reference); NO text reproduced - pointer only', 3, TRUE, 'secondary dictionary entry; confirm the entry and page in the printed dictionary', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_ISL_MAHDI_NETTON');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_ISL_MAHDI', 'Muhammad al-Qa''im', 'transliteration variant (Netton 1992)', 'SRC_NETTON_DICT_ISLAM', 'high', 'needs_review', 'Netton, A Popular Dictionary of Islam'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_ISL_MAHDI' AND alias_name='Muhammad al-Qa''im');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_REN_AGIEL_DAVIDSON', 'ENT_REN_AGIEL', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Agiel"', 'Agiel-an angel''s name found inscribed on the 1st pentacle of the planet Mercury. According to Paracelsus'' doctrine of Talismans, Agiel is the presiding intelligence (i.e., spirit, angel) of the planet Saturn, acting in concert with the spirit Zazel.', 'secondary', 'Davidson''s entry on the intelligence of Saturn (Agrippa''s Agiel).', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_REN_AGIEL_DAVIDSON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_REN_ZAZEL_DAVIDSON', 'ENT_REN_ZAZEL', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Agiel"', 'According to Paracelsus'' doctrine of Talismans, Agiel is the presiding intelligence (i.e., spirit, angel) of the planet Saturn, acting in concert with the spirit Zazel.', 'secondary', 'Zazel named as the spirit of Saturn paired with the intelligence Agiel (Davidson''s Agiel entry).', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_REN_ZAZEL_DAVIDSON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_REN_GRAPHIEL_DAVIDSON', 'ENT_REN_GRAPHIEL', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Graphiel"', 'the intelligence (angel) of the planet Mars when this luminary enters the signs of the Ram and Scorpio.', 'secondary', 'Davidson''s entry on Graphiel (headword itself OCR-damaged, so only the definition is quoted).', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_REN_GRAPHIEL_DAVIDSON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_REN_BARTZABEL_DAVIDSON', 'ENT_REN_BARTZABEL', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Bartyabel"', 'Bartyabel-according to Paracelsus in his doctrine of Talismans, Bartyabel is a spirit of Mars, serving the angel Graphiel, who is the presiding intelligence of the planet.', 'secondary', 'Davidson (following Paul Christian) spells the spirit of Mars ''Bartyabel''; it is Agrippa''s Bartzabel.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_REN_BARTZABEL_DAVIDSON');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_REN_BARTZABEL', 'Bartyabel', 'spelling variant (Davidson 1967)', 'SRC_DAVIDSON_ANGELS', 'high', 'needs_review', 'Davidson, A Dictionary of Angels'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_REN_BARTZABEL' AND alias_name='Bartyabel');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_REN_NAKHIEL_DAVIDSON', 'ENT_REN_NAKHIEL', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Nachiel"', 'Nachiel (Nakiel, Nakhiel)-in the cabala, the intelligence of the sun, when the sun enters the sign of Leo.', 'secondary', 'Davidson''s entry on the intelligence of the Sun.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_REN_NAKHIEL_DAVIDSON');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_REN_NAKHIEL', 'Nachiel', 'spelling variant (Davidson 1967)', 'SRC_DAVIDSON_ANGELS', 'high', 'needs_review', 'Davidson, A Dictionary of Angels'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_REN_NAKHIEL' AND alias_name='Nachiel');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_REN_SORATH_DAVIDSON', 'ENT_REN_SORATH', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Sorath"', 'In talismanic magic, Sorath is the spirit of the sun.', 'secondary', 'Davidson''s entry on Sorath (only the OCR-clean clause quoted; the entry is column-bled in the scan).', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_REN_SORATH_DAVIDSON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_REN_HAGIEL_DAVIDSON', 'ENT_REN_HAGIEL', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Hagiel"', 'Hagiel-the intelligence of Venus when that planet enters the signs of Taurus and Libra.', 'secondary', 'Davidson''s entry on the intelligence of Venus.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_REN_HAGIEL_DAVIDSON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_REN_KEDEMEL_DAVIDSON', 'ENT_REN_KEDEMEL', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Kedemel"', 'Kedemel-in talismanic magic, the spirit of the planet Venus.', 'secondary', 'Davidson''s entry on the spirit of Venus.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_REN_KEDEMEL_DAVIDSON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_REN_TIRIEL_DAVIDSON', 'ENT_REN_TIRIEL', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Tiriel"', 'Tiriel-an archangel, the intelligence of the planet Mercury, with the cabalistic number 260.', 'secondary', 'Davidson''s entry on the intelligence of Mercury.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_REN_TIRIEL_DAVIDSON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_REN_HISMAEL_DAVIDSON', 'ENT_REN_HISMAEL', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Hismael"', 'Hismael-the spirit of the planet Jupiter.', 'secondary', 'Davidson''s entry on the spirit of Jupiter.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_REN_HISMAEL_DAVIDSON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_REN_CHASHMODAI_DAVIDSON', 'ENT_REN_CHASHMODAI', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Chasmodai"', 'Chasmodai-according to Paracelsus in his doctrine of Talismans, Chasmodai is the spirit of the moon', 'secondary', 'Davidson''s entry on the spirit of the Moon.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_REN_CHASHMODAI_DAVIDSON');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_REN_CHASHMODAI', 'Chasmodai', 'spelling variant (Davidson 1967)', 'SRC_DAVIDSON_ANGELS', 'high', 'needs_review', 'Davidson, A Dictionary of Angels'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_REN_CHASHMODAI' AND alias_name='Chasmodai');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_REN_ARATRON_DAVIDSON', 'ENT_REN_ARATRON', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Arathron"', 'Arathron (Aratron)-1st of the Olympian spirits governing the planet Saturn; he rules 49 of the 196 Olympic Provinces.', 'secondary', 'Davidson''s entry on the Olympic spirit of Saturn.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_REN_ARATRON_DAVIDSON');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_REN_ARATRON', 'Arathron', 'spelling variant (Davidson 1967)', 'SRC_DAVIDSON_ANGELS', 'high', 'needs_review', 'Davidson, A Dictionary of Angels'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_REN_ARATRON' AND alias_name='Arathron');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_REN_BETHOR_DAVIDSON', 'ENT_REN_BETHOR', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Bethor"', 'Bethor-one of the 7 supreme angels ruling the 196 provinces in which Heaven is divided. Bethor rules 42 Olympic regions and commands kings, princes, dukes, etc.', 'secondary', 'Davidson''s entry on the Olympic spirit of Jupiter.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_REN_BETHOR_DAVIDSON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_REN_PHALEG_DAVIDSON', 'ENT_REN_PHALEG', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Phalec (Phaleg)"', 'Phalec is also the governing spirit of the planet Mars (and hence often referred to, as he is by Cornelius Agrippa, as the war lord). Of the 106 Olympic Provinces, Phalec has dominion over 35.', 'secondary', 'Davidson''s entry on the Olympic spirit of Mars (headword spelled Phalec).', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_REN_PHALEG_DAVIDSON');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_REN_PHALEG', 'Phalec', 'spelling variant (Davidson 1967)', 'SRC_DAVIDSON_ANGELS', 'high', 'needs_review', 'Davidson, A Dictionary of Angels'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_REN_PHALEG' AND alias_name='Phalec');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_REN_OCH_DAVIDSON', 'ENT_REN_OCH', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Och"', 'Och gives 600 years of perfect health (if, that is, the invocant lives that long). Och is also ruler of 28 of the 196 Olympian provinces in which Heaven is divided.', 'secondary', 'Davidson''s entry on the Olympic spirit of the Sun.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_REN_OCH_DAVIDSON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_REN_HAGITH_DAVIDSON', 'ENT_REN_HAGITH', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Hagith"', 'Hagith-ruler of the planet Venus and one of the 7 Olympian spirits.', 'secondary', 'Davidson''s entry on the Olympic spirit of Venus.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_REN_HAGITH_DAVIDSON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_REN_OPHIEL_DAVIDSON', 'ENT_REN_OPHIEL', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Ophiel"', 'Ophiel--one of the 7 Olympian spirits (or one of 14 such spirits). Ophiel rules the planet Mercury.', 'secondary', 'Davidson''s entry on the Olympic spirit of Mercury.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_REN_OPHIEL_DAVIDSON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_REN_PHUL_DAVIDSON', 'ENT_REN_PHUL', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Phul"', 'Phul (Phuel)-lord of the moon and ruler of 7 of the Olympian Provinces.', 'secondary', 'Davidson''s entry on the Olympic spirit of the Moon.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_REN_PHUL_DAVIDSON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_SOL_CASSIEL_DAVIDSON', 'ENT_SOL_CASSIEL', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Cassiel"', 'Cassiel is one of the rulers of the planet Saturn, also a ruling prince of the 7th Heaven and one of the sarim (princes) of the order of powers.', 'secondary', 'Davidson''s entry on Cassiel (angel of Saturn/Saturday).', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_SOL_CASSIEL_DAVIDSON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_JM_BOEL_DAVIDSON', 'ENT_JM_BOEL', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Boel"', 'Boel ("God is in him"-Boul, Booel, Bohel, Dohel)--one of 7 exalted throne angels resident in the 1st Heaven.', 'secondary', 'Davidson''s entry (Rf. Zohar); the DB entity is the Boel of Sefer ha-Razim''s first firmament - same name-tradition, confirm identity.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_JM_BOEL_DAVIDSON');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_JM_BOEL', 'Bual', 'spelling variant (Davidson 1967)', 'SRC_DAVIDSON_ANGELS', 'high', 'needs_review', 'Davidson, A Dictionary of Angels'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_JM_BOEL' AND alias_name='Bual');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_JM_HAYLIEL_DAVIDSON', 'ENT_JM_HAYLIEL', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Hayyel"', 'Hayyel (Hashmal, Chayyiel, Hayyliel, Johiel, Yayael)-chief angel of the hayyoth (q.v.). He has dominion over wild beasts, according to 3 Enoch', 'secondary', 'Davidson''s entry on the 3 Enoch angel of the hayyoth (Hayliel).', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_JM_HAYLIEL_DAVIDSON');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_JM_HAYLIEL', 'Hayyliel', 'spelling variant (Davidson 1967)', 'SRC_DAVIDSON_ANGELS', 'high', 'needs_review', 'Davidson, A Dictionary of Angels'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_JM_HAYLIEL' AND alias_name='Hayyliel');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_JM_HAYLIEL', 'Hayyel', 'spelling variant (Davidson 1967)', 'SRC_DAVIDSON_ANGELS', 'high', 'needs_review', 'Davidson, A Dictionary of Angels'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_JM_HAYLIEL' AND alias_name='Hayyel');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_JM_SOPERIEL_MEMETH_DAVIDSON', 'ENT_JM_SOPERIEL_MEMETH', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Sofriel (Sopher, Sopheriel)"', 'an angelic bookkeeper appointed over the records of the living and the dead. There are two Sofriels: Sofriel Memith and Sofriel Mehayye.', 'secondary', 'Davidson''s entry on the two Sofriels of 3 Enoch (headword OCR-damaged, definition quoted).', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_JM_SOPERIEL_MEMETH_DAVIDSON');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_JM_SOPERIEL_MEMETH', 'Sofriel Memith', 'spelling variant (Davidson 1967)', 'SRC_DAVIDSON_ANGELS', 'high', 'needs_review', 'Davidson, A Dictionary of Angels'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_JM_SOPERIEL_MEMETH' AND alias_name='Sofriel Memith');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_JM_ZIIEL_DAVIDSON', 'ENT_JM_ZIIEL', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Zi''iel"', 'Zi''iel-in 3 Enoch, the angel "appointed over commotion."', 'secondary', 'Davidson''s entry on the 3 Enoch angel Ziiel.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_JM_ZIIEL_DAVIDSON');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_JM_ZIIEL', 'Zi''iel', 'spelling variant (Davidson 1967)', 'SRC_DAVIDSON_ANGELS', 'high', 'needs_review', 'Davidson, A Dictionary of Angels'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_JM_ZIIEL' AND alias_name='Zi''iel');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_JM_TOTRISI_DAVIDSON', 'ENT_JM_TOTRISI', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Trotrosi X (Totrisi)"', 'Trotrosi X (Totrisi)-an invocation spirit who communicated to Moses the divine name.', 'secondary', 'Davidson''s entry (Rf. Gaster, The Sword of Moses).', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_JM_TOTRISI_DAVIDSON');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_JM_TOTRISI', 'Trotrosi', 'spelling variant (Davidson 1967)', 'SRC_DAVIDSON_ANGELS', 'high', 'needs_review', 'Davidson, A Dictionary of Angels'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_JM_TOTRISI' AND alias_name='Trotrosi');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_JM_SOQEDHOZI_DAVIDSON', 'ENT_JM_SOQEDHOZI', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Angel of the Balances"', 'Angel of the Balances [Soqed Hozi, Dokiel, Michael, Zehanpuryu''h]', 'secondary', 'Davidson lists Soqed Hozi first among the angels of the balances (weighing of souls).', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_JM_SOQEDHOZI_DAVIDSON');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_JM_SOQEDHOZI', 'Soqed Hozi', 'spelling variant (Davidson 1967)', 'SRC_DAVIDSON_ANGELS', 'high', 'needs_review', 'Davidson, A Dictionary of Angels'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_JM_SOQEDHOZI' AND alias_name='Soqed Hozi');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_JM_LILIN_DAVIDSON', 'ENT_JM_LILIN', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Shaitans"', 'In rabbinic lore, the shaitans are male demons, the female being known as lilin.', 'secondary', 'Davidson names the lilin as the female counterpart of the shaitans (Rf. Talmud Berachoth).', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_JM_LILIN_DAVIDSON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_LAT_IAX_DAVIDSON', 'ENT_LAT_IAX', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Iax"', 'Iax-an angel capable of thwarting the demon Roeled (who causes stomach trouble) and the demon Envy.', 'secondary', 'Davidson''s entry (Rf. Conybeare, The Testament of Solomon).', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_LAT_IAX_DAVIDSON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_MAN_ABATHUR_DAVIDSON', 'ENT_MAN_ABATHUR', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Abathur Mazania"', 'Abathur Mazania (Abyatur)-in Mandaean cosmology, the uthra (angel) of the North Star. He presides over the scales in which the human soul is weighed at the death of the body.', 'secondary', 'Davidson''s entry on Abathur (Rf. Drower).', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_MAN_ABATHUR_DAVIDSON');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_MAN_ABATHUR', 'Abathur Muzania', 'spelling variant (Davidson 1967)', 'SRC_DAVIDSON_ANGELS', 'high', 'needs_review', 'Davidson, A Dictionary of Angels'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_MAN_ABATHUR' AND alias_name='Abathur Muzania');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_MAN_ABATHUR', 'Abyatur', 'spelling variant (Davidson 1967)', 'SRC_DAVIDSON_ANGELS', 'high', 'needs_review', 'Davidson, A Dictionary of Angels'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_MAN_ABATHUR' AND alias_name='Abyatur');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_MAN_SAURIEL_DAVIDSON', 'ENT_MAN_SAURIEL', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Sauriel"', 'Sauriel (Sauriil, Suriel, Sowrill)-an angel of death, so designated in Drower, The Canonical Prayerbook of the Mandaeans, where Sauriel is referred to as "Sauriel the Releaser."', 'secondary', 'Davidson''s entry on the Mandaean angel of death.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_MAN_SAURIEL_DAVIDSON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_MAN_HIBIL_ZIWA_DAVIDSON', 'ENT_MAN_HIBIL_ZIWA', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Hiwel-Ziwa"', 'Hiwel-Ziwa (Hibel-Ziwa)-in Mandaean lore, one of the 360 divine beings, created by Alaha, the Supreme Being. Hiwel in turn is said to have created this world.', 'secondary', 'Davidson''s entry on Hibil Ziwa (spelled Hiwel-Ziwa).', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_MAN_HIBIL_ZIWA_DAVIDSON');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_MAN_HIBIL_ZIWA', 'Hiwel-Ziwa', 'spelling variant (Davidson 1967)', 'SRC_DAVIDSON_ANGELS', 'high', 'needs_review', 'Davidson, A Dictionary of Angels'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_MAN_HIBIL_ZIWA' AND alias_name='Hiwel-Ziwa');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_MAN_HIBIL_ZIWA', 'Hibel-Ziwa', 'spelling variant (Davidson 1967)', 'SRC_DAVIDSON_ANGELS', 'high', 'needs_review', 'Davidson, A Dictionary of Angels'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_MAN_HIBIL_ZIWA' AND alias_name='Hibel-Ziwa');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_MAN_YUSHAMIN_DAVIDSON', 'ENT_MAN_YUSHAMIN', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Yus(h)amin"', 'Mandaean lore, Yusamin or Yushamin is a spirit of fertility dwelling in the wellsprings o f light; he is one of the 3 supreme uthri (angels).', 'secondary', 'Davidson''s entry on Yushamin (headword hyphenation OCR-broken; definition quoted).', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_MAN_YUSHAMIN_DAVIDSON');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_MAN_YUSHAMIN', 'Yusamin', 'spelling variant (Davidson 1967)', 'SRC_DAVIDSON_ANGELS', 'high', 'needs_review', 'Davidson, A Dictionary of Angels'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_MAN_YUSHAMIN' AND alias_name='Yusamin');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_MAN_NIDBAI_DAVIDSON', 'ENT_MAN_NIDBAI', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Nidbai"', 'Nidbai-in Mandaean mythology, one of 2 guardian uthri (angels) of the River Jordan', 'secondary', 'Davidson''s entry on Nidbai (the continuation is column-bled and omitted); the other guardian is Shilmai.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_MAN_NIDBAI_DAVIDSON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_MAN_SHILMAI_DAVIDSON', 'ENT_MAN_SHILMAI', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Nidbai"', NULL, 'secondary', 'Davidson''s Nidbai entry names Silmai/Shilmai as the other guardian uthra of the Jordan; that clause is column-bled in the scan, so pointer only.', DATE '2026-09-18', 'headword entry located in the pdftotext extraction but its text is column-bled/OCR-garbled; NO text reproduced - pointer only', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_MAN_SHILMAI_DAVIDSON');
INSERT INTO entity_aliases (entity_id, alias_name, alias_type, source_id, confidence, review_status, notes)
SELECT 'ENT_MAN_SHILMAI', 'Silmai', 'spelling variant (Davidson 1967)', 'SRC_DAVIDSON_ANGELS', 'high', 'needs_review', 'Davidson, A Dictionary of Angels'
WHERE NOT EXISTS (SELECT 1 FROM entity_aliases WHERE entity_id='ENT_MAN_SHILMAI' AND alias_name='Silmai');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_MAN_UTHRAS_DAVIDSON', 'ENT_MAN_UTHRAS', 'SRC_DAVIDSON_ANGELS', 'Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (New York: Free Press, 1967)', 's.v. "Uthra"', 'Uthra (pl. uthri)-in Mandaean mythology, an angel or spirit of life, one of 10, that accompany the sun on its daily course.', 'secondary', 'Davidson''s entry on the uthras.', DATE '2026-09-18', 'full-text extraction (pdftotext, two-column scan); headword entry located and read; only OCR-clean, non-column-bled spans accepted; brief attributed excerpt of the entry''s definition (in-copyright dictionary, house precedent SRC_DAVIDSON_ANGELS); contiguous-substring gate passed', 3, TRUE, 'secondary dictionary entry; confirm the entry in the printed Davidson', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_MAN_UTHRAS_DAVIDSON');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_SET_PLESITHEA_PIWO', 'ENT_SET_PLESITHEA', 'SRC_PIWOWARCZYK_LEXICON', 'Przemysław Piwowarczyk, A Lexicon of Spiritual Powers in the Nag Hammadi "Library" in the Light of the Texts of Ritual Power (Leiden: Brill, 2023)', 's.v. ⲡⲗⲏⲥⲓⲑⲉⲁ (plêsithea), entry 254', NULL, 'secondary', 'Lexicon entry: Plesithea, ''the great power of the great light'', NHC III 56,6 (Gos. Eg.).', DATE '2026-09-18', 'lexicon entry located in the pdftotext extraction by its Coptic/Greek headword and read (entry lists the NHC loci); in-copyright scholarly lexicon, NO text reproduced - pointer only', 3, TRUE, 'secondary lexicon pointer; confirm entry number', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_SET_PLESITHEA_PIWO');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_SET_HORMOS_PIWO', 'ENT_SET_HORMOS', 'SRC_PIWOWARCZYK_LEXICON', 'Przemysław Piwowarczyk, A Lexicon of Spiritual Powers in the Nag Hammadi "Library" in the Light of the Texts of Ritual Power (Leiden: Brill, 2023)', 's.v. ϩⲟⲣⲙⲟⲥ (hormos), entry 343', NULL, 'secondary', 'Lexicon entry: Hormos, ''the great angel'' who prepared the seed, NHC III 60,3 = IV 71,12 (Gos. Eg.).', DATE '2026-09-18', 'lexicon entry located in the pdftotext extraction by its Coptic/Greek headword and read (entry lists the NHC loci); in-copyright scholarly lexicon, NO text reproduced - pointer only', 3, TRUE, 'secondary lexicon pointer; confirm entry number', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_SET_HORMOS_PIWO');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_SET_NEBRUEL_PIWO', 'ENT_SET_NEBRUEL', 'SRC_PIWOWARCZYK_LEXICON', 'Przemysław Piwowarczyk, A Lexicon of Spiritual Powers in the Nag Hammadi "Library" in the Light of the Texts of Ritual Power (Leiden: Brill, 2023)', 's.v. ⲛⲉⲃⲣⲟⲩⲏⲗ (nebrouêl), entry 231', NULL, 'secondary', 'Lexicon entry: Nebruel, ''the great demon'' who with Sakla begets the spirit of earth, NHC III 57,18 = IV 69,2 (Gos. Eg.); also CT 51 (Gos. Jud.).', DATE '2026-09-18', 'lexicon entry located in the pdftotext extraction by its Coptic/Greek headword and read (entry lists the NHC loci); in-copyright scholarly lexicon, NO text reproduced - pointer only', 3, TRUE, 'secondary lexicon pointer; confirm entry number', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_SET_NEBRUEL_PIWO');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_JEU_FIRE_BAPTISM_EVANS', 'ENT_JEU_FIRE_BAPTISM', 'SRC_LIB_EVANS_BOOKS_OF_JEU', 'Erin Evans, The Books of Jeu and the Pistis Sophia as Handbooks to Eternity: Exploring Mysteries of the Codex Brucianus and the Askew Codex (Leiden: Brill, 2015)', 'passim', NULL, 'secondary', 'Entity discussed in this work (7 word-boundary occurrences); context verified. Discussed as the rite of 2 Jeu (2 Jeu 63-64).', DATE '2026-09-18', 'full-text extraction (pdftotext); entity located by word-boundary search and the surrounding context read to confirm the reference is to THIS Jeuian figure; in-copyright monograph, NO text reproduced - pointer only', 4, TRUE, 'secondary pointer - confirm the work treats this figure substantively', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_JEU_FIRE_BAPTISM_EVANS');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_PS_RECEIVERS_EVANS', 'ENT_PS_RECEIVERS', 'SRC_LIB_EVANS_BOOKS_OF_JEU', 'Erin Evans, The Books of Jeu and the Pistis Sophia as Handbooks to Eternity: Exploring Mysteries of the Codex Brucianus and the Askew Codex (Leiden: Brill, 2015)', 'passim', NULL, 'secondary', 'Entity discussed in this work (17 word-boundary occurrences); context verified. Discussed as the receivers (paralemptai) of the Treasury of Light in Pistis Sophia.', DATE '2026-09-18', 'full-text extraction (pdftotext); entity located by word-boundary search and the surrounding context read to confirm the reference is to THIS Jeuian figure; in-copyright monograph, NO text reproduced - pointer only', 4, TRUE, 'secondary pointer - confirm the work treats this figure substantively', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_PS_RECEIVERS_EVANS');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_JEU_SEALS_EVANS', 'ENT_JEU_SEALS', 'SRC_LIB_EVANS_BOOKS_OF_JEU', 'Erin Evans, The Books of Jeu and the Pistis Sophia as Handbooks to Eternity: Exploring Mysteries of the Codex Brucianus and the Askew Codex (Leiden: Brill, 2015)', 'passim', NULL, 'secondary', 'Entity discussed in this work (108 word-boundary occurrences); context verified. The seals of the Books of Jeu are treated in ch. 3 (''Diagrams in the Books of Jeu'').', DATE '2026-09-18', 'full-text extraction (pdftotext); entity located by word-boundary search and the surrounding context read to confirm the reference is to THIS Jeuian figure; in-copyright monograph, NO text reproduced - pointer only', 4, TRUE, 'secondary pointer - confirm the work treats this figure substantively', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_JEU_SEALS_EVANS');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_MAN_HIBIL_ZIWA_WIDENGREN', 'ENT_MAN_HIBIL_ZIWA', 'SRC_LIB_WIDENGREN_KING_SAVIOUR_II', 'Geo Widengren, Mesopotamian Elements in Manichaeism (King and Saviour II): Studies in Manichaean, Mandaean, and Syrian-Gnostic Religion (Uppsala, 1946)', 'passim', NULL, 'secondary', 'Hibil''s descent to the nether world discussed with Ginza references (Lidzbarski, Ginza p. 502).', DATE '2026-09-18', 'full-text extraction (pdftotext); entity located by word-boundary search and the surrounding context (with Widengren''s Ginza/Liturgies references) read to confirm the referent; NO text reproduced - pointer only', 4, TRUE, 'secondary pointer - confirm the work treats this figure substantively', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_MAN_HIBIL_ZIWA_WIDENGREN');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_MAN_KUSHTA_WIDENGREN', 'ENT_MAN_KUSHTA', 'SRC_LIB_WIDENGREN_KING_SAVIOUR_II', 'Geo Widengren, Mesopotamian Elements in Manichaeism (King and Saviour II): Studies in Manichaean, Mandaean, and Syrian-Gnostic Religion (Uppsala, 1946)', 'passim', NULL, 'secondary', '''The keys of Kushta'' in a translated Mandaean hymn (Shilmai the treasurer).', DATE '2026-09-18', 'full-text extraction (pdftotext); entity located by word-boundary search and the surrounding context (with Widengren''s Ginza/Liturgies references) read to confirm the referent; NO text reproduced - pointer only', 4, TRUE, 'secondary pointer - confirm the work treats this figure substantively', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_MAN_KUSHTA_WIDENGREN');

INSERT INTO entity_citations (citation_id, entity_id, source_id, work_title, locus, quote,
  evidence_grade, evidence_note, verified_on, verify_method, display_order, needs_review, review_reason, translator, translation_year, source_url)
SELECT 'CIT_MAN_HAYYI_RABBI_WIDENGREN', 'ENT_MAN_HAYYI_RABBI', 'SRC_LIB_WIDENGREN_KING_SAVIOUR_II', 'Geo Widengren, Mesopotamian Elements in Manichaeism (King and Saviour II): Studies in Manichaean, Mandaean, and Syrian-Gnostic Religion (Uppsala, 1946)', 'passim', NULL, 'secondary', 'The Great Life as sender of the Saviour/Messenger, with Mandaean Liturgies references.', DATE '2026-09-18', 'full-text extraction (pdftotext); entity located by word-boundary search and the surrounding context (with Widengren''s Ginza/Liturgies references) read to confirm the referent; NO text reproduced - pointer only', 4, TRUE, 'secondary pointer - confirm the work treats this figure substantively', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM entity_citations WHERE citation_id='CIT_MAN_HAYYI_RABBI_WIDENGREN');

COMMIT;
