-- build_p6_monsters_brood.sql  (GENERATED by gen_roster.py p6_monsters_brood) — v1.80.0
-- 10 entities, 18 edges, 0 new periods, 1 new sources. Idempotent + self-validating.
BEGIN;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_GANTZ_EARLY_GREEK_MYTH','secondary scholarship','Timothy Gantz, Early Greek Myth: A Guide to Literary and Artistic Sources (Johns Hopkins University Press, 1993)','Comparative source-critical treatment of the Typhon/Echidna monster genealogy and its variants across early Greek poetry and art')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,trad text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_MON_ECHIDNA','Echidna','Monster','Chthonic monster','Greek','Monsters; chthonic generation','B','The half-woman, half-serpent ''mother of monsters''; mate of Typhon and dam of the Greek monster brood. Attested Hesiod, Theogony 295-332 (esp. 304-305 description); Apollodorus 2.1.2. Genealogical hub previously missing from the DB.'),
 ('ENT_MON_ORTHRUS','Orthrus','Monster','Guardian beast','Greek','Monsters; guardian beasts','B','Two-headed hound of Geryon, son of Typhon and Echidna, slain by Heracles; sire (with the Chimera) of the Sphinx and Nemean Lion in Hesiod''s construal. Attested Hesiod, Theogony 309-327; Apollodorus 2.5.10.'),
 ('ENT_MON_SPHINX','Sphinx','Monster','Chthonic monster','Greek','Monsters; riddle/death','B','The Theban Sphinx (Phix), winged lion-bodied woman who posed the riddle; child of Orthrus and the Chimera (Hesiod) or of Typhon/Echidna. Attested Hesiod, Theogony 326-329; Apollodorus 3.5.8. Distinct from the Egyptian sphinx.'),
 ('ENT_MON_HARPIES','Harpies','Monster','Monster collective','Greek','Monsters; storm-winds; snatching','B','Collective of winged storm-spirits (Aello, Ocypete, Celaeno), daughters of Thaumas and Electra, ''snatchers'' who tormented Phineus. Attested Hesiod, Theogony 265-269; Apollodorus 1.9.21. Collective entity.'),
 ('ENT_MON_SIRENS','Sirens','Monster','Monster collective','Greek','Monsters; deadly song','B','Collective of bird-bodied singing maidens whose song lured sailors to death; encountered by Odysseus. Attested Homer, Odyssey 12.39-54, 165-200; Apollodorus E7.18-19. Collective entity.'),
 ('ENT_MON_STYMPHALIAN_BIRDS','Stymphalian Birds','Monster','Monster collective','Greek','Monsters; man-eating birds','B','Man-eating bronze-beaked birds of Lake Stymphalia driven off by Heracles in his sixth labour. Attested Apollodorus 2.5.6; Pausanias 8.22.4. Collective entity.'),
 ('ENT_MON_GRAEAE','Graeae','Monster','Monster collective','Greek','Monsters; old age; prophecy','B','Grey-haired sisters (Deino, Enyo, Pemphredo) sharing one eye and one tooth, daughters of Phorcys and Ceto; coerced by Perseus. Attested Hesiod, Theogony 270-273; Apollodorus 2.4.2. Collective entity.'),
 ('ENT_MON_HECATONCHEIRES','Hecatoncheires','Monster','Primordial monster collective','Greek','Monsters; primordial force','B','The hundred-handed, fifty-headed giants Cottus, Briareus and Gyges, sons of Ouranos and Gaia; allies of Zeus against the Titans and jailers of the imprisoned Titans. Attested Hesiod, Theogony 147-153, 617-735. Collective entity.'),
 ('ENT_MON_GIGANTES','Gigantes','Monster','Primordial monster collective','Greek','Monsters; Gigantomachy','B','Earth-born giants sprung from Gaia (from the blood of Ouranos) who warred on the Olympians in the Gigantomachy. Attested Hesiod, Theogony 183-186; Apollodorus 1.6.1-2. Collective entity.'),
 ('ENT_MON_NIDHOGGR','Níðhöggr','Monster','Chthonic serpent','Germanic/Norse','Monsters; corpse-serpent; world-tree','B','Corpse-devouring dragon-serpent that gnaws the root of Yggdrasil from below in Niflheim/Náströnd. Attested Poetic Edda, Völuspá 39, 66 and Grímnismál 32, 35; Snorri, Prose Edda (Gylfaginning). Norse functional cognate of the Greek chthonic monster-serpent.');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'devotional',conf,'candidate_verified_name','Roster build via gen_roster.py (see CHANGELOG/git for release)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,etype text,note text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_MON_ECHIDNA','SRC_HESIOD_THEOGONY','scholarly attestation','attestation'),
 ('ENT_MON_ORTHRUS','SRC_HESIOD_THEOGONY','scholarly attestation','attestation'),
 ('ENT_MON_SPHINX','SRC_HESIOD_THEOGONY','scholarly attestation','attestation'),
 ('ENT_MON_HARPIES','SRC_HESIOD_THEOGONY','scholarly attestation','attestation'),
 ('ENT_MON_SIRENS','SRC_GANTZ_EARLY_GREEK_MYTH','scholarly attestation','attestation'),
 ('ENT_MON_STYMPHALIAN_BIRDS','SRC_GANTZ_EARLY_GREEK_MYTH','scholarly attestation','attestation'),
 ('ENT_MON_GRAEAE','SRC_HESIOD_THEOGONY','scholarly attestation','attestation'),
 ('ENT_MON_HECATONCHEIRES','SRC_HESIOD_THEOGONY','scholarly attestation','attestation'),
 ('ENT_MON_GIGANTES','SRC_HESIOD_THEOGONY','scholarly attestation','attestation'),
 ('ENT_MON_NIDHOGGR','SRC_POETIC_EDDA','scholarly attestation','attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_MON_ECHIDNA','PER_GRK_ARCHAIC','The half-woman, half-serpent ''mother of monsters''; mate of Typhon and dam of the Greek monster brood. Attested Hesiod, Theogony 295-332 (esp. 304-305 description); Apollodorus 2.1.2. Genealogical hub previously missing from the DB.'),
 ('ENT_MON_ORTHRUS','PER_GRK_ARCHAIC','Two-headed hound of Geryon, son of Typhon and Echidna, slain by Heracles; sire (with the Chimera) of the Sphinx and Nemean Lion in Hesiod''s construal. Attested Hesiod, Theogony 309-327; Apollodorus 2.5.10.'),
 ('ENT_MON_SPHINX','PER_GRK_ARCHAIC','The Theban Sphinx (Phix), winged lion-bodied woman who posed the riddle; child of Orthrus and the Chimera (Hesiod) or of Typhon/Echidna. Attested Hesiod, Theogony 326-329; Apollodorus 3.5.8. Distinct from the Egyptian sphinx.'),
 ('ENT_MON_HARPIES','PER_GRK_ARCHAIC','Collective of winged storm-spirits (Aello, Ocypete, Celaeno), daughters of Thaumas and Electra, ''snatchers'' who tormented Phineus. Attested Hesiod, Theogony 265-269; Apollodorus 1.9.21. Collective entity.'),
 ('ENT_MON_SIRENS','PER_GRK_ARCHAIC','Collective of bird-bodied singing maidens whose song lured sailors to death; encountered by Odysseus. Attested Homer, Odyssey 12.39-54, 165-200; Apollodorus E7.18-19. Collective entity.'),
 ('ENT_MON_STYMPHALIAN_BIRDS','PER_GRK_ARCHAIC','Man-eating bronze-beaked birds of Lake Stymphalia driven off by Heracles in his sixth labour. Attested Apollodorus 2.5.6; Pausanias 8.22.4. Collective entity.'),
 ('ENT_MON_GRAEAE','PER_GRK_ARCHAIC','Grey-haired sisters (Deino, Enyo, Pemphredo) sharing one eye and one tooth, daughters of Phorcys and Ceto; coerced by Perseus. Attested Hesiod, Theogony 270-273; Apollodorus 2.4.2. Collective entity.'),
 ('ENT_MON_HECATONCHEIRES','PER_GRK_ARCHAIC','The hundred-handed, fifty-headed giants Cottus, Briareus and Gyges, sons of Ouranos and Gaia; allies of Zeus against the Titans and jailers of the imprisoned Titans. Attested Hesiod, Theogony 147-153, 617-735. Collective entity.'),
 ('ENT_MON_GIGANTES','PER_GRK_ARCHAIC','Earth-born giants sprung from Gaia (from the blood of Ouranos) who warred on the Olympians in the Gigantomachy. Attested Hesiod, Theogony 183-186; Apollodorus 1.6.1-2. Collective entity.'),
 ('ENT_MON_NIDHOGGR','PER_NOR_VIKING','Corpse-devouring dragon-serpent that gnaws the root of Yggdrasil from below in Niflheim/Náströnd. Attested Poetic Edda, Völuspá 39, 66 and Grímnismál 32, 35; Snorri, Prose Edda (Gylfaginning). Norse functional cognate of the Greek chthonic monster-serpent.');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_MON_ECHIDNA','paired_with','ENT_TYPHON','high','Hesiod, Theog. 306-308: Echidna couples with Typhon (Typhaon) to bear the monster brood. paired_with (not consort_of, which is not a valid type).'),
 ('ENT_MON_ECHIDNA','parent_of','ENT_MON_ORTHRUS','high','Hesiod, Theog. 309-310: Echidna bore Orthrus the hound of Geryon.'),
 ('ENT_MON_ECHIDNA','parent_of','ENT_CERBERUS','high','Hesiod, Theog. 310-312: Echidna bore Cerberus, the brazen-voiced hound of Hades (existing entity).'),
 ('ENT_MON_ECHIDNA','parent_of','ENT_HYDRA','high','Hesiod, Theog. 313-315: Echidna bore the Lernaean Hydra (existing entity).'),
 ('ENT_MON_ECHIDNA','parent_of','ENT_CHIMERA','medium','Hesiod, Theog. 319-325: the Chimera in the prevailing reading belongs to the Echidna/Typhon line (variant: of Echidna and Orthrus). Existing entity.'),
 ('ENT_TYPHON','parent_of','ENT_MON_ORTHRUS','high','Hesiod, Theog. 306-310: Typhon father of Echidna''s brood, including Orthrus.'),
 ('ENT_TYPHON','parent_of','ENT_CERBERUS','high','Hesiod, Theog. 306-312: Typhon father of Cerberus by Echidna (existing entity).'),
 ('ENT_TYPHON','parent_of','ENT_HYDRA','high','Hesiod, Theog. 306-315: Typhon father of the Hydra by Echidna (existing entity).'),
 ('ENT_MON_ORTHRUS','sibling_of','ENT_CERBERUS','high','Hesiod, Theog. 309-312: Orthrus and Cerberus both born of Typhon and Echidna (existing entity).'),
 ('ENT_MON_ORTHRUS','guardian_of','ENT_GERYON','high','Hesiod, Theog. 309-311; Apollodorus 2.5.10: Orthrus guarded the cattle of Geryon and was slain by Heracles (existing entity).'),
 ('ENT_MON_SPHINX','child_of','ENT_MON_ORTHRUS','medium','Hesiod, Theog. 326-327: the Sphinx (Phix) born of Orthrus (contested maternal line).'),
 ('ENT_MON_SPHINX','child_of','ENT_CHIMERA','medium','Hesiod, Theog. 326-329: the Sphinx and Nemean Lion born of the Chimera (by Orthrus) per one construal. Existing entity.'),
 ('ENT_NEMEAN_LION','child_of','ENT_CHIMERA','medium','Hesiod, Theog. 327-329: the Nemean Lion in the same brood-line, connected to the Chimera/Orthrus. Both existing entities.'),
 ('ENT_MON_NIDHOGGR','dwells_in','ENT_NOR_YGGDRASIL','high','Poetic Edda, Grímnismál 32, 35 and Völuspá 66: Níðhöggr gnaws the root of Yggdrasil from below (existing entity).'),
 ('ENT_MON_NIDHOGGR','aligned_with','ENT_MON_ECHIDNA','low','Modern comparative cross-tradition pairing: Níðhöggr as the Norse functional cognate of the Greek chthonic monster-serpent of the Echidna brood (aligned_with = modern functional analogue, not ancient identification).'),
 ('ENT_MON_GRAEAE','aligned_with','ENT_MON_SIRENS','low','Structural grouping within the wider chthonic Phorcys/Ceto and sea-monster cohort of early Greek myth (Gantz, Early Greek Myth); cohort linkage, NOT attested kinship (changed from sibling_of, which would falsely assert shared parentage).'),
 ('ENT_MON_HECATONCHEIRES','opposes','ENT_MON_GIGANTES','low','Structural contrast among Gaia''s primordial earth-born hosts: the Hundred-Handers fight for Zeus, while the Gigantes war against the Olympians (Hesiod, Theog.; Apollodorus 1.6).'),
 ('ENT_MON_STYMPHALIAN_BIRDS','aligned_with','ENT_MON_HARPIES','low','Comparative grouping of monstrous bird-collectives of Greek myth (Stymphalian Birds, Harpies, Sirens); cohort linkage for graph connectivity, not genealogical kinship.');

\echo '--- REJECTED edges (bad id/type, or subject lacks a source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
