-- build_p4_anglosaxon.sql  (GENERATED by gen_roster.py p4_anglosaxon) — v1.80.0
-- 11 entities, 17 edges, 1 new periods, 2 new sources. Idempotent + self-validating.
BEGIN;

INSERT INTO periods (period_id, period_name, start_year, end_year) VALUES
 ('PER_ANGLO_SAXON','Anglo-Saxon period',400,1000)
ON CONFLICT (period_id) DO NOTHING;

INSERT INTO sources (source_id, source_type, title, scope) VALUES
 ('SRC_POLLINGTON_ELDER_GODS','secondary scholarship','Stephen Pollington, The Elder Gods: The Otherworld of Early England (2011)','Anglo-Saxon paganism, deities, cosmology and ritual'),
 ('SRC_BEDE_DTR','primary text','Bede, De temporum ratione (The Reckoning of Time), c. 725 CE','Old English month-names; sole attestation of Eostre and Hreda')
ON CONFLICT (source_id) DO NOTHING;

CREATE TEMP TABLE _e(id text,name text,etype text,cat text,trad text,dom text,conf text,note text) ON COMMIT DROP;
INSERT INTO _e VALUES
 ('ENT_ASX_PANTHEON','Anglo-Saxon Pantheon','collective','collective','Anglo-Saxon','pantheon','B','Hub collective for the pre-Christian Old English gods reconstructed from royal genealogies, place-names, charms, Bede and Norse cognates.'),
 ('ENT_ASX_WODEN','Woden','deity','sky/sovereign deity','Anglo-Saxon','war, wisdom, kingship, the dead','B','Chief god; head of most Anglo-Saxon royal genealogies (West Saxon, Mercian lines) and named in the Nine Herbs Charm. Old English cognate of Norse Odin.'),
 ('ENT_ASX_THUNOR','Thunor','deity','thunder deity','Anglo-Saxon','thunder, sky, protection','B','Thunder-god attested in place-names (Thunderfield, Thundersley) and the weekday Thunresdaeg. Old English cognate of Norse Thor.'),
 ('ENT_ASX_TIW','Tiw','deity','war/sky deity','Anglo-Saxon','war, law, the sky','B','War-god attested in place-names (Tysoe, Tuesley) and the weekday Tiwesdaeg. Old English cognate of Norse Tyr.'),
 ('ENT_ASX_FRIGE','Frige','deity','mother/sovereign goddess','Anglo-Saxon','marriage, household, fertility','B','Goddess attested in the weekday Frigedaeg (Friday). Old English cognate of Norse Frigg.'),
 ('ENT_ASX_EOSTRE','Eostre','deity','dawn/spring goddess','Anglo-Saxon','dawn, spring, renewal','C','Dawn/spring goddess named by Bede as eponym of the month Eosturmonath, from which English Easter derives; sole near-contemporary attestation.'),
 ('ENT_ASX_HREDA','Hreda','deity','goddess','Anglo-Saxon','victory, glory, the early-spring month','C','Goddess named by Bede as eponym of the month Hredmonath (roughly March); known only from that passage.'),
 ('ENT_ASX_SEAXNEAT','Seaxneat','deity','ancestral/tribal deity','Anglo-Saxon','kingship, tribal ancestry','C','Divine ancestor heading the East Saxon royal genealogy; cognate of Continental Saxon Saxnot in the Old Saxon Baptismal Vow.'),
 ('ENT_ASX_ING','Ing','deity','fertility deity','Anglo-Saxon','fertility, peace, ancestry','C','Ing/Ingui, eponym of the Ingaevones, named in the Old English Rune Poem; cognate of Norse Freyr (Yngvi-Freyr).'),
 ('ENT_ASX_WULDOR','Wuldor','deity','deity','Anglo-Saxon','glory, splendour','C','Glory-god inferred from the noun wuldor and place-names; Old English cognate of Norse Ullr.'),
 ('ENT_ASX_ERCE','Erce','deity','earth-mother goddess','Anglo-Saxon','earth, fertility of the fields','C','Earth-mother addressed as ''Erce, eorthan modor'' in the Old English Aecerbot (field-remedy) charm.');

INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'devotional',conf,'candidate_verified_name','Roster build via gen_roster.py (see CHANGELOG/git for release)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;

CREATE TEMP TABLE _s(id text,src text,etype text,note text) ON COMMIT DROP;
INSERT INTO _s VALUES
 ('ENT_ASX_PANTHEON','SRC_POLLINGTON_ELDER_GODS','scholarly attestation','attestation'),
 ('ENT_ASX_WODEN','SRC_POLLINGTON_ELDER_GODS','scholarly attestation','attestation'),
 ('ENT_ASX_THUNOR','SRC_POLLINGTON_ELDER_GODS','scholarly attestation','attestation'),
 ('ENT_ASX_TIW','SRC_POLLINGTON_ELDER_GODS','scholarly attestation','attestation'),
 ('ENT_ASX_FRIGE','SRC_POLLINGTON_ELDER_GODS','scholarly attestation','attestation'),
 ('ENT_ASX_EOSTRE','SRC_BEDE_DTR','primary text attestation','attestation'),
 ('ENT_ASX_HREDA','SRC_BEDE_DTR','primary text attestation','attestation'),
 ('ENT_ASX_SEAXNEAT','SRC_POLLINGTON_ELDER_GODS','scholarly attestation','attestation'),
 ('ENT_ASX_ING','SRC_POLLINGTON_ELDER_GODS','scholarly attestation','attestation'),
 ('ENT_ASX_WULDOR','SRC_POLLINGTON_ELDER_GODS','scholarly attestation','attestation'),
 ('ENT_ASX_ERCE','SRC_POLLINGTON_ELDER_GODS','scholarly attestation','attestation');

INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;
INSERT INTO _p VALUES
 ('ENT_ASX_PANTHEON','PER_ANGLO_SAXON','Hub collective for the pre-Christian Old English gods reconstructed from royal genealogies, place-names, charms, Bede and Norse cognates.'),
 ('ENT_ASX_WODEN','PER_ANGLO_SAXON','Chief god; head of most Anglo-Saxon royal genealogies (West Saxon, Mercian lines) and named in the Nine Herbs Charm. Old English cognate of Norse Odin.'),
 ('ENT_ASX_THUNOR','PER_ANGLO_SAXON','Thunder-god attested in place-names (Thunderfield, Thundersley) and the weekday Thunresdaeg. Old English cognate of Norse Thor.'),
 ('ENT_ASX_TIW','PER_ANGLO_SAXON','War-god attested in place-names (Tysoe, Tuesley) and the weekday Tiwesdaeg. Old English cognate of Norse Tyr.'),
 ('ENT_ASX_FRIGE','PER_ANGLO_SAXON','Goddess attested in the weekday Frigedaeg (Friday). Old English cognate of Norse Frigg.'),
 ('ENT_ASX_EOSTRE','PER_ANGLO_SAXON','Dawn/spring goddess named by Bede as eponym of the month Eosturmonath, from which English Easter derives; sole near-contemporary attestation.'),
 ('ENT_ASX_HREDA','PER_ANGLO_SAXON','Goddess named by Bede as eponym of the month Hredmonath (roughly March); known only from that passage.'),
 ('ENT_ASX_SEAXNEAT','PER_ANGLO_SAXON','Divine ancestor heading the East Saxon royal genealogy; cognate of Continental Saxon Saxnot in the Old Saxon Baptismal Vow.'),
 ('ENT_ASX_ING','PER_ANGLO_SAXON','Ing/Ingui, eponym of the Ingaevones, named in the Old English Rune Poem; cognate of Norse Freyr (Yngvi-Freyr).'),
 ('ENT_ASX_WULDOR','PER_ANGLO_SAXON','Glory-god inferred from the noun wuldor and place-names; Old English cognate of Norse Ullr.'),
 ('ENT_ASX_ERCE','PER_ANGLO_SAXON','Earth-mother addressed as ''Erce, eorthan modor'' in the Old English Aecerbot (field-remedy) charm.');

INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;
INSERT INTO _r VALUES
 ('ENT_ASX_WODEN','member_of','ENT_ASX_PANTHEON','high','Woden is the chief deity of the reconstructed Anglo-Saxon pantheon (Pollington).'),
 ('ENT_ASX_THUNOR','member_of','ENT_ASX_PANTHEON','high','Thunor is a core Anglo-Saxon god attested in place-names and the weekday.'),
 ('ENT_ASX_TIW','member_of','ENT_ASX_PANTHEON','high','Tiw is a core Anglo-Saxon god attested in place-names and the weekday.'),
 ('ENT_ASX_FRIGE','member_of','ENT_ASX_PANTHEON','high','Frige is the principal Anglo-Saxon goddess, attested in the weekday Friday.'),
 ('ENT_ASX_EOSTRE','member_of','ENT_ASX_PANTHEON','medium','Eostre is attested by Bede as an Anglo-Saxon goddess (month Eosturmonath).'),
 ('ENT_ASX_HREDA','member_of','ENT_ASX_PANTHEON','medium','Hreda is attested by Bede as an Anglo-Saxon goddess (month Hredmonath).'),
 ('ENT_ASX_SEAXNEAT','member_of','ENT_ASX_PANTHEON','medium','Seaxneat heads the East Saxon royal genealogy as a divine ancestor.'),
 ('ENT_ASX_ING','member_of','ENT_ASX_PANTHEON','medium','Ing is named in the Old English Rune Poem as an Anglo-Saxon deity.'),
 ('ENT_ASX_WULDOR','member_of','ENT_ASX_PANTHEON','low','Wuldor is a glory-god inferred for the Anglo-Saxon pantheon from lexis and place-names.'),
 ('ENT_ASX_ERCE','member_of','ENT_ASX_PANTHEON','medium','Erce is the earth-mother invoked in the Anglo-Saxon Aecerbot charm.'),
 ('ENT_ASX_WODEN','aligned_with','ENT_NOR_ODIN','high','Woden is the Old English reflex of the same Germanic deity as Norse Odin (Wodanaz).'),
 ('ENT_ASX_THUNOR','aligned_with','ENT_NOR_THOR','high','Thunor is the Old English cognate of Norse Thor (Thunraz).'),
 ('ENT_ASX_TIW','aligned_with','ENT_NOR_TYR','high','Tiw is the Old English cognate of Norse Tyr (Tiwaz).'),
 ('ENT_ASX_FRIGE','aligned_with','ENT_NOR_FRIGG','high','Frige is the Old English cognate of Norse Frigg (Frijjo).'),
 ('ENT_ASX_ING','aligned_with','ENT_NOR_FREYR','medium','Ing/Ingui corresponds to Norse Yngvi-Freyr, the Ingaevonic ancestor-deity.'),
 ('ENT_ASX_WULDOR','aligned_with','ENT_NOR_ULLR','medium','Wuldor is the Old English lexical and divine cognate of Norse Ullr.'),
 ('ENT_ASX_ERCE','aligned_with','ENT_NOR_NERTHUS','low','Erce the Old English earth-mother is functionally aligned with the Germanic earth-goddess Nerthus described by Tacitus.');

\echo '--- REJECTED edges (bad id/type, or subject lacks a source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
