-- scripts/cleanup_zoroastrian_citations.sql
-- Citation-quality cleanup: re-anchor Zoroastrian citations that were anchored on
-- translator apparatus (footnotes/index/commentary) onto real primary text, or
-- honestly re-grade those not yet replaceable. No fabrication.

BEGIN;
UPDATE entity_citations SET quote='Ohrmazd performed the spiritual Yazishn ceremony with the archangels (amahraspand) in the Rapithwin Gah, and in the Yazishn he supplied every means necessary for overcoming the adversary. 10.', source_id='SRC_BUNDAHISHN', work_title='Bundahishn', locus='Bundahishn', source_url='https://www.sacred-texts.com/zor/sbe05/index.htm', translator='E. W. West (SBE 5)', translation_year=1880, evidence_grade='primary-verbatim', verify_method='re-anchored to primary text (substring-gated); cleanup of apparatus-anchored citation', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ZOR_AMESHA_SPENTAS_BUNDAH';
UPDATE entity_citations SET quote='And before his coming to Gayomard, Ohrmazd brought forth a sweat upon Gayomard, so long as he might recite a prayer (vaj) of one stanza (vichast); moreover, Ohrmazd formed that sweat into the youthful body of a man of fifteen years, radiant and tall. 20.', source_id='SRC_BUNDAHISHN', work_title='Bundahishn', locus='Bundahishn', source_url='https://www.sacred-texts.com/zor/sbe05/index.htm', translator='E. W. West (SBE 5)', translation_year=1880, evidence_grade='primary-verbatim', verify_method='re-anchored to primary text (substring-gated); cleanup of apparatus-anchored citation', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ZOR_GAYOMARD_BUNDAH';
UPDATE entity_citations SET quote='Unto Mithra, the lord of wide pastures, who has a thousand ears, ten thousand eyes, a Yazata invoked by his own name, and unto Rama Hvastra, 1 Be propitiation, with sacrifice, prayer, propitiation, and glorification. Yatha ahu vairyo: The will of the Lord is the law of holiness.... 1.', source_id='SRC_AVESTA', work_title='The Zend-Avesta (Darmesteter, SBE)', locus='Mihr Yasht (Yt 10)', source_url='https://www.avesta.org/ka/yt10sbe.htm', translator='James Darmesteter', translation_year=1883, evidence_grade='primary-verbatim', verify_method='re-anchored to primary text (substring-gated); cleanup of apparatus-anchored citation', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ZOR_MITHRA_BUNDAH';
UPDATE entity_citations SET quote='Unto the holy, strong Sraosha, who is the incarnate Word, a mighty-speared and lordly god, Be propitiation, with sacrifice, prayer, propitiation, and glorification. Yatha ahu vairyo: The will of the Lord is the law of holiness.... I. 1.', source_id='SRC_AVESTA', work_title='The Zend-Avesta (Darmesteter, SBE)', locus='Srosh Yasht (Yt 11)', source_url='https://www.avesta.org/ka/yt11sbe.htm', translator='James Darmesteter', translation_year=1883, evidence_grade='primary-verbatim', verify_method='re-anchored to primary text (substring-gated); cleanup of apparatus-anchored citation', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ZOR_SRAOSHA_BUNDAH';
UPDATE entity_citations SET quote='We sacrifice unto the holy, tall-formed, fiend-smiting Sraosha, who makes the world increase, the holy and master of holiness; Whom the holy Ahura Mazda has created to withstand Aeshma, the fiend of the wounding spear; we sacrifice unto Peace, whose breath is friendly, and unto the two withstanders', source_id='SRC_AVESTA', work_title='The Zend-Avesta (Darmesteter, SBE)', locus='Srosh Yasht (Yt 11)', source_url='https://www.avesta.org/ka/yt11sbe.htm', translator='James Darmesteter', translation_year=1883, evidence_grade='primary-verbatim', verify_method='re-anchored to primary text (substring-gated); cleanup of apparatus-anchored citation', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ZOR_AESHMA_DAEVA_BUNDAH';
UPDATE entity_citations SET quote='We worship the Fravashi of the holy Keresaspa, the Sama, the club-bearer with plaited hair; to withstand the dreadful arm and the hordes with the wide battle array, with the many spears, with the straight spears, with the spears uplifted, bearing the spears of havoc; to withstand the dreadful brigan', source_id='SRC_AVESTA', work_title='The Zend-Avesta (Darmesteter, SBE)', locus='Farvardin Yasht (Yt 13)', source_url='https://www.avesta.org/ka/yt13sbe.htm', translator='James Darmesteter', translation_year=1883, evidence_grade='primary-verbatim', verify_method='re-anchored to primary text (substring-gated); cleanup of apparatus-anchored citation', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ZOR_KERESASPA_AVESTA';
UPDATE entity_citations SET evidence_grade='secondary', evidence_note='Translator''s scholarly description (Avesta/Bundahishn commentary), not a primary-text quotation.', review_reason='Re-graded from primary-verbatim: quote is West/Darmesteter commentary; primary-text upgrade pending.', verify_method='quality-cleanup re-grade' WHERE citation_id='CIT_ZOR_ANGRA_MAINYU_BUNDAH';
UPDATE entity_citations SET evidence_grade='secondary', evidence_note='Translator''s scholarly description (Avesta/Bundahishn commentary), not a primary-text quotation.', review_reason='Re-graded from primary-verbatim: quote is West/Darmesteter commentary; primary-text upgrade pending.', verify_method='quality-cleanup re-grade' WHERE citation_id='CIT_ZOR_KHSHATHRA_BUNDAH';
UPDATE entity_citations SET evidence_grade='secondary', evidence_note='Translator''s scholarly description (Avesta/Bundahishn commentary), not a primary-text quotation.', review_reason='Re-graded from primary-verbatim: quote is West/Darmesteter commentary; primary-text upgrade pending.', verify_method='quality-cleanup re-grade' WHERE citation_id='CIT_ZOR_SPENTA_ARMATI_BUNDAH';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared mis-anchored/apparatus quote; primary source identified, verbatim quote pending.', verify_method='quality-cleanup re-point' WHERE citation_id='CIT_ZOR_INDRA_DAEVA_AVESTA';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared mis-anchored/apparatus quote; primary source identified, verbatim quote pending.', verify_method='quality-cleanup re-point' WHERE citation_id='CIT_ZOR_DAENA_AVESTA';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared mis-anchored/apparatus quote; primary source identified, verbatim quote pending.', verify_method='quality-cleanup re-point' WHERE citation_id='CIT_ZOR_SPENTA_MAINYU_AVESTA';
UPDATE entity_citations SET quote='Revelation is the explanation of both spirits together; one is he who is independent of unlimited time, because Ohrmazd and the region, religion, and time of Ohrmazd were and are and ever will be; while Ahriman in darkness, with backward un', evidence_grade='primary-verbatim', evidence_note='', source_url='https://www.sacred-texts.com/zor/sbe05/index.htm', review_reason=NULL, verify_method='re-anchored to Bundahishn primary text (substring-gated); Ahriman = West''s rendering of Angra Mainyu', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ZOR_ANGRA_MAINYU_BUNDAH';
UPDATE entity_citations SET quote='''"I praise, I invoke, I meditate upon, and we sacrifice unto the good, strong, beneficent Fravashis of the faithful.', source_id='SRC_AVESTA', work_title='The Zend-Avesta (Darmesteter, SBE)', locus='Farvardin Yasht (Yt 13)', source_url='https://www.avesta.org/ka/yt13sbe.htm', translator='James Darmesteter', translation_year=1883, evidence_grade='primary-verbatim', evidence_note='', review_reason=NULL, verify_method='re-anchored to Farvardin Yasht primary text (substring-gated); cleanup of apparatus/index citation', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ZOR_FRAVASHIS_BUNDAH';
COMMIT;
