-- scripts/cleanup_apparatus_citations.sql
-- Database-wide apparatus-citation cleanup: 48 citations graded primary-verbatim
-- but whose 'quote' is actually a table-of-contents, index, title page, bibliographic
-- footnote, or HTML/file-path bleed (not primary text). Blanked + re-graded to
-- primary-uncited pointers (source still identified). Real name-catalogues (e.g. the
-- Voluspa Dvergatal) were excluded. No fabrication. Detection: scripts (concrete
-- garbage signals only). These are now verbatim-quote upgrade targets.

BEGIN;
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_CHARON_APOLLO';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_EGY_MONTU_PYRAMI';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ANANKE_ORPHIC';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_THO_THOMAS_PISTIS';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_LAT_DECAN_MARMARETH_TESTSO';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ISR_URIEL_ENOCH1';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_GNO_MONAD_NHC';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ADONIS_HERO_APOLLO';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ISL_ISRAFIL_QURAN';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_MANICH_COLUMN_GLORY_MANICH';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_CASSANDRA_APOLLO';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_JM_RAHATIEL_ENOCH3';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_GNO_CHRIST_PISTIS';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_CROSS_PISTIS';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_FINN_LOUHI_KALEVA';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_MANICH_FIVE_DARK_WORLDS_MANICH';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_REN_TIRIEL_AGRIPP';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_REN_TAPHTHARTHARATH_AGRIPP';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_HTT_KUMARBI_HITTIT';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ISR_SARIEL_ENOCH1';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_SET_HEIMARMENE_NHC_ME';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_REN_AGIEL_AGRIPP';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_REN_ZAZEL_AGRIPP';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_REN_HISMAEL_AGRIPP';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_REN_GRAPHIEL_AGRIPP';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_REN_SORATH_AGRIPP';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_REN_HAGIEL_AGRIPP';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_REN_KEDEMEL_AGRIPP';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_JEU_SEALS_JEU';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ISR_PENEMUE_ENOCH1';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_CHR_LAWRENCE_GOLDEN';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ORTH_CHRYSOSTOM_SYNAX';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_HTT_KAMRUSEPA_HITTIT';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_DIO_CELESTIAL_HIERARCHY_DIONYS';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_DIO_FIRST_TRIAD_DIONYS';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_DIO_SECOND_TRIAD_DIONYS';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_DIO_THIRD_TRIAD_DIONYS';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_DIO_ECCLESIASTICAL_HIERARCHY_DIONYS';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_NOR_GEIRROD_GIANT_PROSE_';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_NOR_HUGINN_POETIC';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_NOR_GERI_POETIC';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_JM_SEFER_HARAZIM_ANGELS_HARAZI';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_AST_PERFECT_NATURE_PICATR';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_HER_TRISMEGISTUS_HERMET';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_GSAGA_VOLSUNG_VOLSUN';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_GSAGA_VOLSUNG_CYCLE_VOLSUN';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_NORR_MIMISBRUNNR_POETIC';
UPDATE entity_citations SET quote='', evidence_grade='primary-uncited', evidence_note='', review_reason='Cleared non-primary quote (TOC/index/footnote/title-page bleed); primary source identified, verbatim quote pending.', verify_method='apparatus-cleanup re-point', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_NORR_URDARBRUNNR_POETIC';
COMMIT;
