#!/usr/bin/env python3
# Generates build_fringe.sql from scripts/_fringe/{entities,relationships}.json — the
# early-antiquity fringe completion: Nabataean, Pre-Islamic Arabian, South Arabian,
# Aksumite, Aramean, Urartian, Iberian, Mycenaean, Thracian, Meroitic, Elamite. v1.67.0.
# Prefix-driven tradition/period/source. Idempotent + self-validating.
import json, os
HERE = os.path.dirname(os.path.abspath(__file__)); F = os.path.join(HERE, "_fringe")

NEW_PERIODS = [
 ("PER_NABATAEAN","Nabataean Kingdom",-312,106),
 ("PER_DMT_AKSUM","Dʿmt and Pre-Christian Aksum",-800,400),
]
NEW_SOURCES = [
 ("SRC_MUNRO_HAY_AKSUM","secondary scholarship","Stuart Munro-Hay, Aksum: An African Civilisation of Late Antiquity","Aksumite"),
 ("SRC_VENTRIS_CHADWICK","secondary scholarship","Michael Ventris & John Chadwick, Documents in Mycenaean Greek","Mycenaean"),
 ("SRC_HODDINOTT_THRACIANS","secondary scholarship","R. F. Hoddinott, The Thracians","Thracian"),
 ("SRC_TEIXIDOR_PALMYRA","secondary scholarship","Javier Teixidor, The Pantheon of Palmyra","Aramean"),
]
TRAD = {"NAB":"Nabataean","ARAB":"Pre-Islamic Arabian","SAB":"South Arabian","AKS":"Aksumite",
        "ARA":"Aramean","URA":"Urartian","IB":"Iberian/Lusitanian","MYC":"Mycenaean",
        "THRA":"Thracian","MER":"Meroitic","ELAM":"Elamite"}
PERIOD = {"NAB":"PER_NABATAEAN","ARAB":"PER_ARA_PRE_ISLAMIC","SAB":"PER_SABAEAN","AKS":"PER_DMT_AKSUM",
          "ARA":"PER_ARA_IRON_AGE","URA":"PER_URA_IRON_AGE","IB":"PER_IB_IRON_AGE","MYC":"PER_GRK_MYCENAEAN",
          "THRA":"PER_THRA_IRON_AGE","MER":"PER_MER_NAPATAN_MEROITIC","ELAM":"PER_ELAM_CLASSICAL"}
def pfx(eid):  # ENT_NAB_X -> NAB ; ENT_ARAB_X -> ARAB
    p = eid.split("_")[1]
    return p
def src_for(eid, note):
    p = pfx(eid)
    if p == "NAB": return "SRC_HEALEY_NABATAEAN_RELIGION"
    if p in ("ARAB","SAB"): return "SRC_QURAN" if "Qurʾan" in note else "SRC_HOYLAND_ARABIA"
    if p == "AKS": return "SRC_MUNRO_HAY_AKSUM"
    if p == "ARA": return "SRC_TEIXIDOR_PALMYRA" if "Palmyr" in note else "SRC_LIPINSKI_ARAMEANS"
    if p == "URA": return "SRC_PIOTROVSKY_URARTU"
    if p == "IB": return "SRC_OLIVARES_IBERIAN"
    if p == "MYC": return "SRC_VENTRIS_CHADWICK"
    if p == "THRA": return "SRC_HODDINOTT_THRACIANS"
    if p == "MER": return "SRC_TÖRÖK_MEROE"
    if p == "ELAM": return "SRC_HENKELMAN_ELAM" if "Henkelman" in note else "SRC_POTTS_ELAM"
    return "SRC_HOYLAND_ARABIA"
def q(x): return "'" + str(x).replace("'","''") + "'"

ents = json.load(open(os.path.join(F,"entities.json")))
rels = json.load(open(os.path.join(F,"relationships.json")))
new_ids = {e["id"] for e in ents}

out=["-- build_fringe.sql  (GENERATED by gen_fringe.py) — v1.67.0",
     "-- Early-antiquity fringe completion: Nabataean, Pre-Islamic Arabian, South Arabian,",
     "-- Aksumite, Aramean, Urartian, Iberian, Mycenaean, Thracian, Meroitic, Elamite.",
     "-- %d new entities, %d edges. Idempotent + self-validating." % (len(ents), len(rels)),
     "BEGIN;",""]
out.append("INSERT INTO periods (period_id, period_name, start_year, end_year) VALUES")
out.append(",\n".join(" (%s,%s,%d,%d)"%(q(a),q(b),c,d) for (a,b,c,d) in NEW_PERIODS)+"\nON CONFLICT (period_id) DO NOTHING;")
out.append("")
out.append("INSERT INTO sources (source_id, source_type, title, scope) VALUES")
out.append(",\n".join(" (%s,%s,%s,%s)"%(q(a),q(b),q(c),q(dd)) for (a,b,c,dd) in NEW_SOURCES)+"\nON CONFLICT (source_id) DO NOTHING;")
out.append("")
# entities
out.append("CREATE TEMP TABLE _e(id text,name text,trad text,etype text,cat text,dom text,conf text,note text) ON COMMIT DROP;")
out.append("INSERT INTO _e VALUES")
out.append(",\n".join(" (%s,%s,%s,%s,%s,%s,%s,%s)"%(q(e["id"]),q(e["name"]),q(TRAD[pfx(e["id"])]),q(e["type"]),q(e["cat"]),q(e["dom"]),q(e["conf"]),q(e["note"])) for e in ents)+";")
out.append("""
INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'regional',conf,'candidate_verified_name','Early-antiquity fringe completion (v1.67.0)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;
""")
# sources per entity
out.append("CREATE TEMP TABLE _s(id text,src text,note text,etype text) ON COMMIT DROP;")
out.append("INSERT INTO _s VALUES")
srows=[]
for e in ents:
    s=src_for(e["id"], e["note"]); et = "direct attestation" if s=="SRC_QURAN" else "scholarly attestation"
    srows.append(" (%s,%s,%s,%s)"%(q(e["id"]),q(s),q(e["note"]),q(et)))
out.append(",\n".join(srows)+";")
out.append("""
INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;
""")
# periods per entity
out.append("CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;")
out.append("INSERT INTO _p VALUES")
out.append(",\n".join(" (%s,%s,%s)"%(q(e["id"]),q(PERIOD[pfx(e["id"])]),q(e["note"])) for e in ents)+";")
out.append("""
INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;
""")
# relationships
out.append("CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text,src text) ON COMMIT DROP;")
out.append("INSERT INTO _r VALUES")
rrows=[]
for r in rels:
    src = r.get("src","")
    rrows.append(" (%s,%s,%s,%s,%s,%s)"%(q(r["s"]),q(r["t"]),q(r["o"]),q(r["c"]),q(r["ra"]),q(src)))
out.append(",\n".join(rrows)+";")
out.append("""
\\echo '--- REJECTED edges (bad id/type/source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  COALESCE(NULLIF(r.src,''),(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1)),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
""")
open(os.path.join(HERE,"build_fringe.sql"),"w").write("\n".join(out))
print("wrote build_fringe.sql: %d entities, %d edges, %d new periods, %d new sources" % (len(ents),len(rels),len(NEW_PERIODS),len(NEW_SOURCES)))
