#!/usr/bin/env python3
# Generates build_occult.sql from scripts/_occult/*.json — late-antique & early-medieval
# occult clusters (PGM, Jewish magical, Picatrix astral, Latin Solomonic). v1.66.0.
# Idempotent + self-validating. PGM wires EXISTING gods into its collective (no duplicates);
# edges whose subject is a pre-existing entity are sourced to the cluster's own text.
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
OC = os.path.join(HERE, "_occult")
FILES = ["pgm.json", "jewish.json", "astral.json", "solomonic.json"]

NEW_SOURCES = [
 ("SRC_SEFER_HARAZIM","primary text","Sefer ha-Razim (The Book of the Mysteries), ed. Margalioth; trans. M. A. Morgan","Jewish Mystical"),
 ("SRC_SWORD_OF_MOSES","primary text","Harba de-Moshe (The Sword of Moses), ed. Gaster; trans. Harari","Jewish Mystical"),
 ("SRC_SEFER_RAZIEL","primary text","Sefer Raziel ha-Malakh (The Book of Raziel the Angel)","Jewish Mystical"),
 ("SRC_PICATRIX","primary text","Picatrix (Ghayat al-Hakim), trans. Greer & Warnock; ed. Pingree","Astral Magic"),
 ("SRC_LIBER_JURATUS","primary text","Liber Juratus Honorii (The Sworn Book of Honorius), ed. Hedegard","Solomonic Magic"),
 ("SRC_ARS_NOTORIA","primary text","Ars Notoria, ed./trans. Veronese","Solomonic Magic"),
 ("SRC_LIBER_RAZIELIS","primary text","Liber Razielis (Latin, compiled for Alfonso X)","Solomonic Magic"),
]

CONF = {"A":"high","B":"medium","C":"low","high":"high","medium":"medium","low":"low"}

def src_for(fname, citation):
    if fname == "pgm.json": return "SRC_GREEK_MAGICAL_PAPYRI"
    if fname == "astral.json": return "SRC_PICATRIX"
    if fname == "jewish.json":
        if "Sword of Moses" in citation: return "SRC_SWORD_OF_MOSES"
        if "Raziel" in citation: return "SRC_SEFER_RAZIEL"
        return "SRC_SEFER_HARAZIM"
    if fname == "solomonic.json":
        if "Juratus" in citation: return "SRC_LIBER_JURATUS"
        if "Ars Notoria" in citation: return "SRC_ARS_NOTORIA"
        return "SRC_LIBER_RAZIELIS"
    return "SRC_GREEK_MAGICAL_PAPYRI"

def remap(rt, obj):
    if rt == "governs": return "presides_over"
    if rt == "subclass_of": return "aligned_with"
    if rt == "associated_with":
        if obj == "ENT_MAGIC": return "mediated_by"
        if obj == "ENT_PLANETARY_SPHERES": return "aligned_with"
        return "presides_over"
    return rt

def dom(x):
    return "; ".join(x) if isinstance(x, list) else x

def q(x):
    return "'" + str(x).replace("'", "''") + "'"

# first pass: collect all NEW entity ids
new_ids = set()
data = {}
for f in FILES:
    d = json.load(open(os.path.join(OC, f)))
    data[f] = d
    for e in d["entities"]:
        new_ids.add(e["suggested_id"])

ents, srcs, pers, edges = [], [], [], []
for f in FILES:
    d = data[f]
    trad = d["tradition"]; basis = d["basis"]; pdef = d["period"]; csrc = d["cluster_src"]
    for e in d["entities"]:
        eid = e["suggested_id"]; s = src_for(f, e["source"])
        ents.append((eid, e["name"], trad, e["entity_type"], e["category"], dom(e["primary_domains"]),
                     e.get("evidence_confidence","B"), basis, e["note"]))
        srcs.append((eid, s, e["source"]))
        pers.append((eid, e.get("period", pdef), e["note"]))
    for r in d["relationships"]:
        rt = remap(r["relationship_type"], r["object_id"])
        # edge source: subject's own first source if subject is one we're creating; else the cluster text
        esrc = "" if r["subject_id"] in new_ids else csrc
        edges.append((r["subject_id"], rt, r["object_id"], CONF.get(r["confidence"],"medium"), r["rationale"], esrc))

# de-dup edges
seen=set(); ded=[]
for row in edges:
    k=(row[0],row[1],row[2])
    if k in seen: continue
    seen.add(k); ded.append(row)
edges=ded

out=[]
out.append("-- build_occult.sql  (GENERATED by gen_occult.py) — v1.66.0")
out.append("-- Late-antique & early-medieval occult clusters: PGM (Greco-Egyptian Magical),")
out.append("-- Jewish magical (Sefer ha-Razim/Sword of Moses/Raziel), Picatrix (Astral Magic),")
out.append("-- early Latin Solomonic (Ars Notoria/Liber Juratus/Liber Razielis).")
out.append("-- %d new entities, %d edges. Idempotent + self-validating." % (len(ents), len(edges)))
out.append("BEGIN;")
out.append("")
out.append("INSERT INTO sources (source_id, source_type, title, scope) VALUES")
out.append(",\n".join(" (%s,%s,%s,%s)"%(q(a),q(b),q(c),q(dd)) for (a,b,c,dd) in NEW_SOURCES))
out.append("ON CONFLICT (source_id) DO NOTHING;")
out.append("")
out.append("CREATE TEMP TABLE _e(id text,name text,trad text,etype text,cat text,domains text,conf text,basis text,note text) ON COMMIT DROP;")
out.append("INSERT INTO _e VALUES")
out.append(",\n".join(" (%s,%s,%s,%s,%s,%s,%s,%s,%s)"%(q(a),q(b),q(c),q(dd),q(e),q(f),q(g),q(h),q(i)) for (a,b,c,dd,e,f,g,h,i) in ents)+";")
out.append("""
INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,domains,'regional',conf,'candidate_verified_name',basis,0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;
""")
out.append("CREATE TEMP TABLE _s(id text,src text,note text) ON COMMIT DROP;")
out.append("INSERT INTO _s VALUES")
out.append(",\n".join(" (%s,%s,%s)"%(q(a),q(b),q(c)) for (a,b,c) in srcs)+";")
out.append("""
INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,'direct attestation',s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;
""")
out.append("CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;")
out.append("INSERT INTO _p VALUES")
out.append(",\n".join(" (%s,%s,%s)"%(q(a),q(b),q(c)) for (a,b,c) in pers)+";")
out.append("""
INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;
""")
out.append("CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text,src text) ON COMMIT DROP;")
out.append("INSERT INTO _r VALUES")
out.append(",\n".join(" (%s,%s,%s,%s,%s,%s)"%(q(a),q(b),q(c),q(dd),q(e),q(f)) for (a,b,c,dd,e,f) in edges)+";")
out.append("""
\\echo '--- REJECTED edges (bad id/type/source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  COALESCE(NULLIF(r.src,''),(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1)),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
""")
open(os.path.join(HERE,"build_occult.sql"),"w").write("\n".join(out))
print("wrote build_occult.sql: %d entities, %d sources(new), %d periods, %d edges" % (len(ents),len(NEW_SOURCES),len(pers),len(edges)))
print("new entity ids:", len(new_ids))
