#!/usr/bin/env python3
# Generates build_arthurian.sql from scripts/_arthurian/{entities,relationships}.json — the Arthurian
# legend / Matter of Britain (the Grail mythos). v1.78.0. NEW tradition 'Arthurian', NEW period
# PER_ARTHURIAN (the high/late-medieval literary flourishing), 6 new primary-text sources.
# Idempotent + self-validating. (Rebuild of an off-process agent write that lacked periods and used the
# wrong confidence vocab; this is the canonical reproducible artifact.)
import json, os
HERE = os.path.dirname(os.path.abspath(__file__)); F = os.path.join(HERE, "_arthurian")
TRAD = "Arthurian"
PERIOD_ID = "PER_ARTHURIAN"
NEW_PERIODS = [("PER_ARTHURIAN","Arthurian Literary Cycle (Matter of Britain)",1100,1500)]
NEW_SOURCES = [
 ("SRC_GEOFFREY_MONMOUTH","primary text","Geoffrey of Monmouth, Historia Regum Britanniae (c. 1136)","Arthurian"),
 ("SRC_CHRETIEN_TROYES","primary text","Chrétien de Troyes, the Arthurian romances (c. 1170-1190)","Arthurian"),
 ("SRC_ROBERT_BORON","primary text","Robert de Boron, the Little Grail Cycle / Joseph d'Arimathie, Merlin (c. 1190-1210)","Arthurian"),
 ("SRC_VULGATE_CYCLE","primary text","The Vulgate Cycle (Lancelot-Grail) (c. 1210-1235)","Arthurian"),
 ("SRC_WOLFRAM_PARZIVAL","primary text","Wolfram von Eschenbach, Parzival (c. 1200-1210)","Arthurian"),
 ("SRC_MALORY_MORTE","primary text","Sir Thomas Malory, Le Morte d'Arthur (c. 1469-1485)","Arthurian"),
]
PRIMARY_SRCS = {a for (a,*_) in NEW_SOURCES}
def conf_norm(c):
    c=(c or "").lower()
    return c if c in ("high","medium","low") else {"a":"high","b":"medium","c":"low","d":"low"}.get(c,"medium")
from sqlgen import sql_str as q, sql_int  # robust literals (None->NULL, int validation); see scripts/sqlgen.py

ents = json.load(open(os.path.join(F,"entities.json")))
rels = json.load(open(os.path.join(F,"relationships.json")))

out=["-- build_arthurian.sql  (GENERATED by gen_arthurian.py) — v1.78.0",
     "-- The Arthurian legend / Matter of Britain (the Grail mythos).",
     "-- %d new entities, %d edges. Idempotent + self-validating." % (len(ents), len(rels)),
     "BEGIN;",""]
out.append("INSERT INTO periods (period_id, period_name, start_year, end_year) VALUES")
out.append(",\n".join(" (%s,%s,%s,%s)"%(q(a),q(b),sql_int(c),sql_int(d)) for (a,b,c,d) in NEW_PERIODS)+"\nON CONFLICT (period_id) DO NOTHING;")
out.append("")
out.append("INSERT INTO sources (source_id, source_type, title, scope) VALUES")
out.append(",\n".join(" (%s,%s,%s,%s)"%(q(a),q(b),q(c),q(dd)) for (a,b,c,dd) in NEW_SOURCES)+"\nON CONFLICT (source_id) DO NOTHING;")
out.append("")
out.append("CREATE TEMP TABLE _e(id text,name text,etype text,cat text,dom text,conf text,note text) ON COMMIT DROP;")
out.append("INSERT INTO _e VALUES")
out.append(",\n".join(" (%s,%s,%s,%s,%s,%s,%s)"%(q(e["id"]),q(e["name"]),q(e["type"]),q(e["cat"]),q(e["dom"]),q(e["conf"]),q(e["note"])) for e in ents)+";")
out.append("""
INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,%s,etype,cat,dom,'literary',conf,'candidate_verified_name','Arthurian legend / Matter of Britain (v1.78.0)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;
""" % q(TRAD))
out.append("CREATE TEMP TABLE _s(id text,src text,note text,etype text) ON COMMIT DROP;")
out.append("INSERT INTO _s VALUES")
out.append(",\n".join(" (%s,%s,%s,%s)"%(q(e["id"]),q(e["src"]),q(e["note"]),q("primary text attestation" if e["src"] in PRIMARY_SRCS else "scholarly attestation")) for e in ents)+";")
out.append("""
INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;
""")
out.append("CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;")
out.append("INSERT INTO _p VALUES")
out.append(",\n".join(" (%s,%s,%s)"%(q(e["id"]),q(PERIOD_ID),q(e["note"])) for e in ents)+";")
out.append("""
INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;
""")
out.append("CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;")
out.append("INSERT INTO _r VALUES")
out.append(",\n".join(" (%s,%s,%s,%s,%s)"%(q(r["s"]),q(r["t"]),q(r["o"]),q(conf_norm(r.get("c"))),q(r["ra"])) for r in rels)+";")
out.append("""
\\echo '--- REJECTED edges (bad id/type/source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
""")
open(os.path.join(HERE,"build_arthurian.sql"),"w").write("\n".join(out))
print("wrote build_arthurian.sql: %d entities, %d edges, %d period, %d sources" % (len(ents),len(rels),len(NEW_PERIODS),len(NEW_SOURCES)))
