#!/usr/bin/env python3
# General roster generator: scripts/gen_roster.py <cohort_dir>
# Reads scripts/_<cohort>/{periods,sources,entities,relationships}.json and emits build_<cohort>.sql.
# Per-entity tradition/period/source (roster may span several tradition tags). Creates any NEW periods
# and sources listed. Idempotent (ON CONFLICT) + self-validating (REJECTED edges printed). v1.80.0.
# entities.json: {id,name,type,cat,trad,dom,conf(A/B/C/D),note,src,per}
# sources.json:  [[source_id, source_type, title, scope], ...]   (primary if 'primary' in source_type)
# periods.json:  [[period_id, period_name, start_year, end_year], ...]
# relationships.json: {s,t,o,c(high/medium/low),ra}
import json, os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
COHORT = sys.argv[1] if len(sys.argv) > 1 else "medieval_christian"
F = os.path.join(HERE, "_" + COHORT)
def conf_norm(c):
    c=(c or "").lower()
    return c if c in ("high","medium","low") else {"a":"high","b":"medium","c":"low","d":"low"}.get(c,"medium")
def econf(c):  # entities.evidence_confidence uses A/B/C/D
    c=(c or "").upper()
    return c if c in ("A","B","C","D") else {"HIGH":"A","MEDIUM":"B","LOW":"C"}.get(c,"B")
def q(x): return "'" + str(x).replace("'","''") + "'"
def load(n):
    p=os.path.join(F,n)
    return json.load(open(p)) if os.path.exists(p) else []

periods=load("periods.json"); sources=load("sources.json")
ents=load("entities.json"); rels=load("relationships.json")
PRIMARY={s[0] for s in sources if "primary" in s[1].lower()}

out=["-- build_%s.sql  (GENERATED by gen_roster.py %s) — v1.80.0" % (COHORT,COHORT),
     "-- %d entities, %d edges, %d new periods, %d new sources. Idempotent + self-validating." % (len(ents),len(rels),len(periods),len(sources)),
     "BEGIN;",""]
if periods:
    out.append("INSERT INTO periods (period_id, period_name, start_year, end_year) VALUES")
    out.append(",\n".join(" (%s,%s,%d,%d)"%(q(a),q(b),c,d) for (a,b,c,d) in periods)+"\nON CONFLICT (period_id) DO NOTHING;")
    out.append("")
if sources:
    out.append("INSERT INTO sources (source_id, source_type, title, scope) VALUES")
    out.append(",\n".join(" (%s,%s,%s,%s)"%(q(a),q(b),q(c),q(d)) for (a,b,c,d) in sources)+"\nON CONFLICT (source_id) DO NOTHING;")
    out.append("")
out.append("CREATE TEMP TABLE _e(id text,name text,etype text,cat text,trad text,dom text,conf text,note text) ON COMMIT DROP;")
out.append("INSERT INTO _e VALUES")
out.append(",\n".join(" (%s,%s,%s,%s,%s,%s,%s,%s)"%(q(e["id"]),q(e["name"]),q(e["type"]),q(e["cat"]),q(e["trad"]),q(e["dom"]),q(econf(e["conf"])),q(e["note"])) for e in ents)+";")
out.append("""
INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'devotional',conf,'candidate_verified_name','High/late-medieval depth build (v1.80.0)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;
""")
out.append("CREATE TEMP TABLE _s(id text,src text,etype text,note text) ON COMMIT DROP;")
out.append("INSERT INTO _s VALUES")
out.append(",\n".join(" (%s,%s,%s,%s)"%(q(e["id"]),q(e["src"]),q("primary text attestation" if e["src"] in PRIMARY else "scholarly attestation"),q("attestation")) for e in ents)+";")
out.append("""
INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;
""")
out.append("CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;")
out.append("INSERT INTO _p VALUES")
out.append(",\n".join(" (%s,%s,%s)"%(q(e["id"]),q(e["per"]),q(e["note"])) for e in ents)+";")
out.append("""
INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;
""")
out.append("CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;")
out.append("INSERT INTO _r VALUES")
out.append(",\n".join(" (%s,%s,%s,%s,%s)"%(q(r["s"]),q(r["t"]),q(r["o"]),q(conf_norm(r.get("c"))),q(r["ra"])) for r in rels)+";")
out.append("""
\\echo '--- REJECTED edges (bad id/type, or subject lacks a source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
""")
open(os.path.join(HERE,"build_%s.sql"%COHORT),"w").write("\n".join(out))
print("wrote build_%s.sql: %d entities, %d edges, %d periods, %d sources" % (COHORT,len(ents),len(rels),len(periods),len(sources)))
