#!/usr/bin/env python3
# Generates build_enochian.sql from scripts/_enochian/{entities,relationships}.json — the
# Enochian angelic system of John Dee & Edward Kelley (Heptarchia kings/princes, the Four
# Watchtowers, the Thirty Aethyrs). v1.71.0. Tradition 'Renaissance Esoteric', reuses period
# PER_EARLY_MODERN_OCCULT, one new source SRC_DEE_ENOCHIAN. Idempotent + self-validating.
import json, os
HERE = os.path.dirname(os.path.abspath(__file__)); F = os.path.join(HERE, "_enochian")
TRAD = "Renaissance Esoteric"
PERIOD_ID = "PER_EARLY_MODERN_OCCULT"
NEW_SOURCES = [
 ("SRC_DEE_ENOCHIAN","primary text","John Dee & Edward Kelley, the Enochian diaries (Heptarchia Mystica; Liber Loagaeth; Liber Scientiae / the Aethyrs), Sloane MSS","Renaissance Esoteric"),
]
PRIMARY_SRCS = {"SRC_DEE_ENOCHIAN"}
def conf_norm(c):
    c=(c or "").lower()
    return c if c in ("high","medium","low") else {"a":"high","b":"medium","c":"low"}.get(c,"medium")
def q(x): return "'" + str(x).replace("'","''") + "'"

ents = json.load(open(os.path.join(F,"entities.json")))
rels = json.load(open(os.path.join(F,"relationships.json")))

out=["-- build_enochian.sql  (GENERATED by gen_enochian.py) — v1.71.0",
     "-- The Enochian system of John Dee: Heptarchia kings/princes, the Four Watchtowers, the Thirty Aethyrs.",
     "-- %d new entities, %d edges. Idempotent + self-validating." % (len(ents), len(rels)),
     "BEGIN;",""]
out.append("INSERT INTO sources (source_id, source_type, title, scope) VALUES")
out.append(",\n".join(" (%s,%s,%s,%s)"%(q(a),q(b),q(c),q(dd)) for (a,b,c,dd) in NEW_SOURCES)+"\nON CONFLICT (source_id) DO NOTHING;")
out.append("")
out.append("CREATE TEMP TABLE _e(id text,name text,etype text,cat text,dom text,conf text,note text) ON COMMIT DROP;")
out.append("INSERT INTO _e VALUES")
out.append(",\n".join(" (%s,%s,%s,%s,%s,%s,%s)"%(q(e["id"]),q(e["name"]),q(e["type"]),q(e["cat"]),q(e["dom"]),q(e["conf"]),q(e["note"])) for e in ents)+";")
out.append("""
INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,%s,etype,cat,dom,'literary',conf,'candidate_verified_name','Enochian system of John Dee (v1.71.0)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;
""" % q(TRAD))
out.append("CREATE TEMP TABLE _s(id text,src text,note text,etype text) ON COMMIT DROP;")
out.append("INSERT INTO _s VALUES")
out.append(",\n".join(" (%s,%s,%s,%s)"%(q(e["id"]),q(e["src"]),q(e["note"]),q("primary text attestation")) for e in ents)+";")
out.append("""
INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;
""")
out.append("CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;")
out.append("INSERT INTO _p VALUES")
out.append(",\n".join(" (%s,%s,%s)"%(q(e["id"]),q(PERIOD_ID),q(e["note"])) for e in ents)+";")
out.append("""
INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;
""")
out.append("CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;")
out.append("INSERT INTO _r VALUES")
out.append(",\n".join(" (%s,%s,%s,%s,%s)"%(q(r["s"]),q(r["t"]),q(r["o"]),q(conf_norm(r.get("c"))),q(r["ra"])) for r in rels)+";")
out.append("""
\\echo '--- REJECTED edges (bad id/type/source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
""")
open(os.path.join(HERE,"build_enochian.sql"),"w").write("\n".join(out))
print("wrote build_enochian.sql: %d entities, %d edges, %d new sources" % (len(ents),len(rels),len(NEW_SOURCES)))
