#!/usr/bin/env python3
# Generates build_abrahamic.sql from scripts/_abrahamic/{entities,relationships}.json — the
# mainstream Abrahamic scriptural backbone: Hebrew Bible patriarchs/leaders/kings + prophets
# (Israelite/Second Temple), the NT apostles & evangelists (Christian/Biblical), and the 25
# Qur'anic prophets (Islamic), heavily cross-linked by reception_of. v1.70.0.
# Prefix-driven tradition/source/period. Idempotent + self-validating; confidence coerced to high/medium/low.
import json, os
HERE = os.path.dirname(os.path.abspath(__file__)); F = os.path.join(HERE, "_abrahamic")

NEW_PERIODS = [
 ("PER_APOSTOLIC","Apostolic Age",1,100),
]
NEW_SOURCES = []  # SRC_HEBREW_BIBLE, SRC_NEW_TESTAMENT, SRC_QURAN all already exist
TRAD = {"ISR":"Israelite/Second Temple","NT":"Christian/Biblical","ISL":"Islamic"}
SRC  = {"ISR":"SRC_HEBREW_BIBLE","NT":"SRC_NEW_TESTAMENT","ISL":"SRC_QURAN"}
PERIOD = {"NT":"PER_APOSTOLIC","ISL":"PER_ISL_EARLY","ISR":"PER_ISR_IRON_AGE"}
# Israelite figures whose floruit is exilic/post-exilic rather than Iron Age:
ISR_EXILIC = {"ENT_ISR_JEREMIAH","ENT_ISR_EZEKIEL","ENT_ISR_DANIEL_PROPHET","ENT_ISR_OBADIAH",
 "ENT_ISR_HAGGAI","ENT_ISR_ZECHARIAH","ENT_ISR_MALACHI","ENT_ISR_EZRA","ENT_ISR_NEHEMIAH",
 "ENT_ISR_ESTHER","ENT_ISR_MORDECAI"}
PRIMARY_SRCS = {"SRC_HEBREW_BIBLE","SRC_NEW_TESTAMENT","SRC_QURAN"}
def pfx(eid): return eid.split("_")[1]   # ENT_ISR_X->ISR, ENT_NT_X->NT, ENT_ISL_X->ISL
def per_for(eid):
    p = pfx(eid)
    if p == "ISR": return "PER_ISR_EXILIC" if eid in ISR_EXILIC else "PER_ISR_IRON_AGE"
    return PERIOD[p]
def conf_norm(c):
    c = (c or "").lower()
    if c in ("high","medium","low"): return c
    return {"a":"high","b":"medium","c":"low","d":"low"}.get(c,"medium")
from sqlgen import sql_str as q, sql_int  # robust literals (None->NULL, int validation); see scripts/sqlgen.py

ents = json.load(open(os.path.join(F,"entities.json")))
rels = json.load(open(os.path.join(F,"relationships.json")))

out=["-- build_abrahamic.sql  (GENERATED by gen_abrahamic.py) — v1.70.0",
     "-- Mainstream Abrahamic scriptural backbone: Hebrew Bible patriarchs/leaders/kings & prophets,",
     "-- NT apostles & evangelists, and the 25 Qur'anic prophets — cross-linked by reception_of.",
     "-- %d new entities, %d edges. Idempotent + self-validating." % (len(ents), len(rels)),
     "BEGIN;",""]
out.append("INSERT INTO periods (period_id, period_name, start_year, end_year) VALUES")
out.append(",\n".join(" (%s,%s,%s,%s)"%(q(a),q(b),sql_int(c),sql_int(d)) for (a,b,c,d) in NEW_PERIODS)+"\nON CONFLICT (period_id) DO NOTHING;")
out.append("")
# entities
out.append("CREATE TEMP TABLE _e(id text,name text,trad text,etype text,cat text,dom text,conf text,note text) ON COMMIT DROP;")
out.append("INSERT INTO _e VALUES")
out.append(",\n".join(" (%s,%s,%s,%s,%s,%s,%s,%s)"%(q(e["id"]),q(e["name"]),q(TRAD[pfx(e["id"])]),q(e["type"]),q(e["cat"]),q(e["dom"]),q(e["conf"]),q(e["note"])) for e in ents)+";")
out.append("""
INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'regional',conf,'candidate_verified_name','Mainstream Abrahamic scriptural figures (v1.70.0)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;
""")
# sources per entity
out.append("CREATE TEMP TABLE _s(id text,src text,note text,etype text) ON COMMIT DROP;")
out.append("INSERT INTO _s VALUES")
out.append(",\n".join(" (%s,%s,%s,%s)"%(q(e["id"]),q(SRC[pfx(e["id"])]),q(e["note"]),q("primary text attestation")) for e in ents)+";")
out.append("""
INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;
""")
# periods per entity
out.append("CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;")
out.append("INSERT INTO _p VALUES")
out.append(",\n".join(" (%s,%s,%s)"%(q(e["id"]),q(per_for(e["id"])),q(e["note"])) for e in ents)+";")
out.append("""
INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;
""")
# relationships
out.append("CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;")
out.append("INSERT INTO _r VALUES")
out.append(",\n".join(" (%s,%s,%s,%s,%s)"%(q(r["s"]),q(r["t"]),q(r["o"]),q(conf_norm(r.get("c"))),q(r["ra"])) for r in rels)+";")
out.append("""
\\echo '--- REJECTED edges (bad id/type/source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
""")
open(os.path.join(HERE,"build_abrahamic.sql"),"w").write("\n".join(out))
print("wrote build_abrahamic.sql: %d entities, %d edges, %d new periods" % (len(ents),len(rels),len(NEW_PERIODS)))
