#!/usr/bin/env python3
# Generates build_goetia.sql from scripts/_goetia/{entities,relationships}.json — the
# Grimoire Demonology cohort: the 72 spirits of the Ars Goetia (Lemegeton/Weyer) plus the
# infernal hierarchy / princes of Hell (Binsfeld's seven deadly-sin demons, de Plancy). v1.68.0.
# Single tradition 'Goetic/Solomonic', one early-modern period. Idempotent + self-validating.
# Models demons as catalogued entities (rank/legions/office/cross-links) — NOT ritual seals (CLAUDE.md boundary).
import json, os
HERE = os.path.dirname(os.path.abspath(__file__)); F = os.path.join(HERE, "_goetia")
TRAD = "Goetic/Solomonic"
PERIOD_ID = "PER_EARLY_MODERN_OCCULT"

NEW_PERIODS = [
 ("PER_EARLY_MODERN_OCCULT","Early-Modern Western Esoteric / Grimoire Era",1450,1900),
]
NEW_SOURCES = [
 ("SRC_LEMEGETON","primary text","The Lesser Key of Solomon (Lemegeton), Book I: Ars Goetia; ed. S. L. MacGregor Mathers & Aleister Crowley (1904)","Goetic/Solomonic"),
 ("SRC_WEYER_PSEUDOMONARCHIA","primary text","Johann Weyer, Pseudomonarchia Daemonum (appendix to De praestigiis daemonum, 1577)","Goetic/Solomonic"),
 ("SRC_DEPLANCY_INFERNAL","secondary scholarship","J. A. S. Collin de Plancy, Dictionnaire Infernal (1818; 6th ed. 1863)","Goetic/Solomonic"),
]
PRIMARY_SRCS = {"SRC_LEMEGETON","SRC_WEYER_PSEUDOMONARCHIA"}
from sqlgen import sql_str as q, sql_int  # robust literals (None->NULL, int validation); see scripts/sqlgen.py

ents = json.load(open(os.path.join(F,"entities.json")))
rels = json.load(open(os.path.join(F,"relationships.json")))

out=["-- build_goetia.sql  (GENERATED by gen_goetia.py) — v1.68.0",
     "-- Grimoire Demonology: the 72 spirits of the Ars Goetia (Lemegeton/Weyer) + the infernal",
     "-- hierarchy / princes of Hell (Binsfeld's seven deadly-sin demons, de Plancy's Dictionnaire Infernal).",
     "-- %d new entities, %d edges. Idempotent + self-validating." % (len(ents), len(rels)),
     "BEGIN;",""]
out.append("INSERT INTO periods (period_id, period_name, start_year, end_year) VALUES")
out.append(",\n".join(" (%s,%s,%s,%s)"%(q(a),q(b),sql_int(c),sql_int(d)) for (a,b,c,d) in NEW_PERIODS)+"\nON CONFLICT (period_id) DO NOTHING;")
out.append("")
out.append("INSERT INTO sources (source_id, source_type, title, scope) VALUES")
out.append(",\n".join(" (%s,%s,%s,%s)"%(q(a),q(b),q(c),q(dd)) for (a,b,c,dd) in NEW_SOURCES)+"\nON CONFLICT (source_id) DO NOTHING;")
out.append("")
# entities
out.append("CREATE TEMP TABLE _e(id text,name text,etype text,cat text,dom text,conf text,note text) ON COMMIT DROP;")
out.append("INSERT INTO _e VALUES")
out.append(",\n".join(" (%s,%s,%s,%s,%s,%s,%s)"%(q(e["id"]),q(e["name"]),q(e["type"]),q(e["cat"]),q(e["dom"]),q(e["conf"]),q(e["note"])) for e in ents)+";")
out.append("""
INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,%s,etype,cat,dom,'literary',conf,'candidate_verified_name','Grimoire demonology completion (v1.68.0)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;
""" % q(TRAD))
# sources per entity (from each entity's src field)
out.append("CREATE TEMP TABLE _s(id text,src text,note text,etype text) ON COMMIT DROP;")
out.append("INSERT INTO _s VALUES")
srows=[]
for e in ents:
    s=e["src"]; et = "primary text attestation" if s in PRIMARY_SRCS else "scholarly attestation"
    srows.append(" (%s,%s,%s,%s)"%(q(e["id"]),q(s),q(e["note"]),q(et)))
out.append(",\n".join(srows)+";")
out.append("""
INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;
""")
# periods per entity (all new entities -> the early-modern occult band)
out.append("CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;")
out.append("INSERT INTO _p VALUES")
out.append(",\n".join(" (%s,%s,%s)"%(q(e["id"]),q(PERIOD_ID),q(e["note"])) for e in ents)+";")
out.append("""
INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;
""")
# relationships (per-edge src override for existing-subject edges; else subject's own source)
out.append("CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text,src text) ON COMMIT DROP;")
out.append("INSERT INTO _r VALUES")
rrows=[]
for r in rels:
    src = r.get("src","")
    rrows.append(" (%s,%s,%s,%s,%s,%s)"%(q(r["s"]),q(r["t"]),q(r["o"]),q(r["c"]),q(r["ra"]),q(src)))
out.append(",\n".join(rrows)+";")
out.append("""
\\echo '--- REJECTED edges (bad id/type/source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  COALESCE(NULLIF(r.src,''),(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1)),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
""")
open(os.path.join(HERE,"build_goetia.sql"),"w").write("\n".join(out))
print("wrote build_goetia.sql: %d entities, %d edges, %d new periods, %d new sources" % (len(ents),len(rels),len(NEW_PERIODS),len(NEW_SOURCES)))
