#!/usr/bin/env python3
# Generates build_deep_past.sql from the three _deeppast/*.json research payloads.
# Deep-past enrichment (v1.65.0): archaic Sumerian + predynastic/Old-Kingdom Egyptian
# + Elamite strata. Idempotent + self-validating: every row checks ids/type/source via
# EXISTS and skips conflicts; edge source = each subject's own attesting source.
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
DP = os.path.join(HERE, "_deeppast")

# Map each tradition's default source_id (real existing rows; actual citation kept in source_note).
def meso_src(s):
    return "SRC_ORACC" if "ORACC" in s else "SRC_BLACK_GREEN_MESO"
def egy_src(s):
    return "SRC_WILKINSON_EGYPTIAN_GODS"
def elam_src(s):
    if "Henkelman" in s: return "SRC_HENKELMAN_ELAM"
    if "Carter" in s: return "SRC_CARTER_STOLPER_ELAM"
    return "SRC_POTTS_ELAM"

CONF = {"A":"high","B":"medium","C":"low","high":"high","medium":"medium","low":"low"}

CLUSTERS = [
    ("sumerian.json", "Mesopotamian", meso_src, "Archaic Sumerian / Early Dynastic deity (earliest god-lists: Fara, Abu Salabikh, Zame Hymns)"),
    ("egyptian.json", "Egyptian", egy_src, "Predynastic / Early Dynastic / Old Kingdom Egyptian deity"),
    ("elamite.json", "Elamite", elam_src, "Elamite deity (Susa / Anshan / Tchoga Zanbil)"),
]

from sqlgen import sql_str as q  # robust literals (None->NULL, int validation); see scripts/sqlgen.py

ents, srcs, pers, edges = [], [], [], []
for fname, tradition, srcfn, basis in CLUSTERS:
    data = json.load(open(os.path.join(DP, fname)))
    for e in data["entities"]:
        eid = e["suggested_id"]
        src = srcfn(e["source"])
        ents.append((eid, e["name"], tradition, e["entity_type"], e["category"],
                     e["primary_domains"], e.get("evidence_confidence","B"), basis, e["note"]))
        srcs.append((eid, src, e["source"]))
        pers.append((eid, e["period"], e["note"]))
    for r in data["relationships"]:
        # drop the one flagged-bad Egyptian edge (Dunanwi presides_over Horus)
        if r["subject_id"] == "ENT_EGY_DUNANWI" and r["relationship_type"] == "presides_over":
            continue
        edges.append((r["subject_id"], r["relationship_type"], r["object_id"],
                      CONF.get(r["confidence"],"medium"), r["rationale"]))

# de-dup edges on (subject,type,object)
seen=set(); ded=[]
for s,t,o,c,ra in edges:
    k=(s,t,o)
    if k in seen: continue
    seen.add(k); ded.append((s,t,o,c,ra))
edges=ded

out=[]
out.append("-- build_deep_past.sql  (GENERATED by gen_deep_past.py) — v1.65.0")
out.append("-- Deep-past enrichment: archaic Sumerian + predynastic/OK Egyptian + Elamite strata.")
out.append("-- %d new entities, %d edges. Idempotent + self-validating." % (len(ents), len(edges)))
out.append("BEGIN;")
out.append("")
out.append("-- New source: the standard reference for Elamite religion (used for the Pinikir/Simut equations).")
out.append("INSERT INTO sources (source_id, source_type, title, scope) VALUES")
out.append("  ('SRC_HENKELMAN_ELAM','secondary scholarship','Wouter F. M. Henkelman, The Other Gods Who Are: Studies in Elamite-Iranian Acculturation (Achaemenid History XIV, NINO 2008)','Elamite')")
out.append("ON CONFLICT (source_id) DO NOTHING;")
out.append("")

# entities
out.append("CREATE TEMP TABLE _e(id text,name text,trad text,etype text,cat text,domains text,conf text,basis text,note text) ON COMMIT DROP;")
out.append("INSERT INTO _e VALUES")
rows=[]
for (eid,name,trad,etype,cat,dom,conf,basis,note) in ents:
    rows.append(" (%s,%s,%s,%s,%s,%s,%s,%s,%s)" % (q(eid),q(name),q(trad),q(etype),q(cat),q(dom),q(conf),q(basis),q(note)))
out.append(",\n".join(rows)+";")
out.append("""
INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,domains,'regional',conf,'candidate_verified_name',basis,0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;
""")

# sources
out.append("CREATE TEMP TABLE _s(id text,src text,note text) ON COMMIT DROP;")
out.append("INSERT INTO _s VALUES")
rows=[" (%s,%s,%s)"%(q(a),q(b),q(c)) for (a,b,c) in srcs]
out.append(",\n".join(rows)+";")
out.append("""
INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,'scholarly attestation',s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id)
  AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;
""")

# periods
out.append("CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;")
out.append("INSERT INTO _p VALUES")
rows=[" (%s,%s,%s)"%(q(a),q(b),q(c)) for (a,b,c) in pers]
out.append(",\n".join(rows)+";")
out.append("""
INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id)
  AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;
""")

# edges
out.append("CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;")
out.append("INSERT INTO _r VALUES")
rows=[" (%s,%s,%s,%s,%s)"%(q(a),q(b),q(c),q(d),q(e)) for (a,b,c,d,e) in edges]
out.append(",\n".join(rows)+";")
out.append("""
\\echo '--- REJECTED edges (bad id/type/source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
""")

open(os.path.join(HERE,"build_deep_past.sql"),"w").write("\n".join(out))
print("wrote build_deep_past.sql: %d entities, %d sources, %d periods, %d edges" % (len(ents),len(srcs),len(pers),len(edges)))
