#!/usr/bin/env python3
# Generates build_abrahamic_deep.sql from scripts/_abrahamic_deep/{entities,relationships}.json —
# v1.72.0 deepening of the mainstream Abrahamic scriptural backbone: the divided-monarchy kings &
# later Tanakh figures (ENT_ISR_), more NT apostolic-age figures (ENT_NT_, Christian/Biblical), and
# the early-Islamic Rashidun caliphs + companions (ENT_ISL_, sira/hadith-sourced).
# Prefix-driven tradition/period; per-entity source override; confidence coerced. Idempotent + self-validating.
import json, os
HERE = os.path.dirname(os.path.abspath(__file__)); F = os.path.join(HERE, "_abrahamic_deep")

NEW_PERIODS = []   # PER_ISR_IRON_AGE / PER_ISR_EXILIC / PER_APOSTOLIC / PER_ISL_EARLY all exist
NEW_SOURCES = []   # SRC_HEBREW_BIBLE / SRC_NEW_TESTAMENT / SRC_IBN_ISHAQ_SIRA / SRC_SAHIH_BUKHARI all exist
TRAD = {"ISR":"Israelite/Second Temple","NT":"Christian/Biblical","ISL":"Islamic"}
SRC  = {"ISR":"SRC_HEBREW_BIBLE","NT":"SRC_NEW_TESTAMENT","ISL":"SRC_IBN_ISHAQ_SIRA"}
PERIOD = {"NT":"PER_APOSTOLIC","ISL":"PER_ISL_EARLY","ISR":"PER_ISR_IRON_AGE"}
ISR_EXILIC = {"ENT_ISR_ZEDEKIAH","ENT_ISR_NEBUCHADNEZZAR","ENT_ISR_CYRUS"}
PRIMARY_SRCS = {"SRC_HEBREW_BIBLE","SRC_NEW_TESTAMENT","SRC_QURAN"}  # sira/hadith -> scholarly attestation
def pfx(eid): return eid.split("_")[1]
def per_for(eid):
    p=pfx(eid)
    if p=="ISR": return "PER_ISR_EXILIC" if eid in ISR_EXILIC else "PER_ISR_IRON_AGE"
    return PERIOD[p]
def src_for(e):
    return e.get("src") or SRC[pfx(e["id"])]
def conf_norm(c):
    c=(c or "").lower()
    return c if c in ("high","medium","low") else {"a":"high","b":"medium","c":"low","d":"low"}.get(c,"medium")
def q(x): return "'" + str(x).replace("'","''") + "'"

ents = json.load(open(os.path.join(F,"entities.json")))
rels = json.load(open(os.path.join(F,"relationships.json")))

out=["-- build_abrahamic_deep.sql  (GENERATED by gen_abrahamic_deep.py) — v1.72.0",
     "-- Mainstream Abrahamic backbone deepening: divided-monarchy kings & later Tanakh figures,",
     "-- more NT apostolic-age figures, and the early-Islamic Rashidun caliphs + companions.",
     "-- %d new entities, %d edges. Idempotent + self-validating." % (len(ents), len(rels)),
     "BEGIN;",""]
out.append("CREATE TEMP TABLE _e(id text,name text,trad text,etype text,cat text,dom text,conf text,note text) ON COMMIT DROP;")
out.append("INSERT INTO _e VALUES")
out.append(",\n".join(" (%s,%s,%s,%s,%s,%s,%s,%s)"%(q(e["id"]),q(e["name"]),q(TRAD[pfx(e["id"])]),q(e["type"]),q(e["cat"]),q(e["dom"]),q(e["conf"]),q(e["note"])) for e in ents)+";")
out.append("""
INSERT INTO entities (entity_id,canonical_name,tradition,entity_type,category,primary_domains,cult_scope,evidence_confidence,review_status,inclusion_basis,earth_association_score,chthonic_flag,serpent_flag,short_note)
SELECT id,name,trad,etype,cat,dom,'regional',conf,'candidate_verified_name','Mainstream Abrahamic backbone deepening (v1.72.0)',0,false,false,note FROM _e
ON CONFLICT (entity_id) DO NOTHING;
""")
out.append("CREATE TEMP TABLE _s(id text,src text,note text,etype text) ON COMMIT DROP;")
out.append("INSERT INTO _s VALUES")
srows=[]
for e in ents:
    s=src_for(e); et="primary text attestation" if s in PRIMARY_SRCS else "scholarly attestation"
    srows.append(" (%s,%s,%s,%s)"%(q(e["id"]),q(s),q(e["note"]),q(et)))
out.append(",\n".join(srows)+";")
out.append("""
INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
SELECT s.id,s.src,s.etype,s.note FROM _s s
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=s.id) AND EXISTS(SELECT 1 FROM sources x WHERE x.source_id=s.src)
ON CONFLICT DO NOTHING;
""")
out.append("CREATE TEMP TABLE _p(id text,per text,note text) ON COMMIT DROP;")
out.append("INSERT INTO _p VALUES")
out.append(",\n".join(" (%s,%s,%s)"%(q(e["id"]),q(per_for(e["id"])),q(e["note"])) for e in ents)+";")
out.append("""
INSERT INTO entity_periods (entity_id,period_id,confidence,rationale,source_id,review_status)
SELECT p.id,p.per,'high',p.note,(SELECT es.source_id FROM entity_sources es WHERE es.entity_id=p.id ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _p p
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=p.id) AND EXISTS(SELECT 1 FROM periods x WHERE x.period_id=p.per)
ON CONFLICT DO NOTHING;
""")
out.append("CREATE TEMP TABLE _r(s text,t text,o text,c text,ra text) ON COMMIT DROP;")
out.append("INSERT INTO _r VALUES")
out.append(",\n".join(" (%s,%s,%s,%s,%s)"%(q(r["s"]),q(r["t"]),q(r["o"]),q(conf_norm(r.get("c"))),q(r["ra"])) for r in rels)+";")
out.append("""
\\echo '--- REJECTED edges (bad id/type/source) — review these ---'
SELECT r.s,r.t,r.o FROM _r r
WHERE NOT (EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s));

INSERT INTO entity_relationships(subject_entity_id,relationship_type,object_entity_id,confidence,rationale,source_id,review_status)
SELECT r.s,r.t,r.o,r.c,r.ra,
  (SELECT es.source_id FROM entity_sources es WHERE es.entity_id=r.s ORDER BY es.source_id LIMIT 1),'reviewed'
FROM _r r
WHERE EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.s)
  AND EXISTS(SELECT 1 FROM entities e WHERE e.entity_id=r.o)
  AND EXISTS(SELECT 1 FROM relationship_types y WHERE y.relationship_type=r.t)
  AND EXISTS(SELECT 1 FROM entity_sources es WHERE es.entity_id=r.s)
ON CONFLICT (subject_entity_id,relationship_type,object_entity_id) DO NOTHING;

COMMIT;
""")
open(os.path.join(HERE,"build_abrahamic_deep.sql"),"w").write("\n".join(out))
print("wrote build_abrahamic_deep.sql: %d entities, %d edges" % (len(ents),len(rels)))
