BEGIN;
UPDATE entities SET entity_type='National deity' WHERE entity_type='national deity';
UPDATE entities SET entity_type='Revealer' WHERE entity_type='revealer';
UPDATE entities SET entity_type='Cosmological realm' WHERE entity_type='cosmological realm';
UPDATE entities SET entity_type='Fate goddess' WHERE entity_type='fate goddess';
UPDATE entities SET entity_type='Prophet' WHERE entity_type='prophet';
UPDATE entities SET entity_type='Moon deity' WHERE entity_type='moon deity';
UPDATE entities SET entity_type='Sun deity' WHERE entity_type='sun deity';
UPDATE entities SET entity_type='Giant' WHERE entity_type='giant';
UPDATE entities SET entity_type='Goddess' WHERE entity_type='goddess';
UPDATE entities SET entity_type='Dragon' WHERE entity_type='dragon';
UPDATE entities SET entity_type='High god' WHERE entity_type='High God';
UPDATE entities SET entity_type='Solar deity' WHERE entity_type='solar deity';
UPDATE entities SET entity_type='Sun goddess' WHERE entity_type='sun goddess';
UPDATE entities SET entity_type='Deity' WHERE entity_type='deity';
UPDATE entities SET entity_type='Spirit' WHERE entity_type='spirit';
UPDATE entities SET entity_type='Chthonic deity' WHERE entity_type='chthonic deity';
UPDATE entities SET entity_type='Daimon' WHERE entity_type='daimon';
UPDATE entities SET entity_type='Demon' WHERE entity_type='demon';
UPDATE entities SET entity_type='Monster' WHERE entity_type='monster';
UPDATE entities SET entity_type='Hero' WHERE entity_type='hero';
UPDATE entities SET entity_type='Nymph' WHERE entity_type='nymph';
UPDATE entities SET entity_type='God' WHERE entity_type='god';
UPDATE entities SET entity_type='Personified abstraction' WHERE entity_type='personified abstraction';
COMMIT;
