-- qa_v1_84_2.sql — backfill the 77 rationale-less edges (Testament of Solomon / 3 Enoch / Hekhalot)
-- and resolve the 10 legacy orphan sources (attach the bibliographic ones, retire non-attestational).
-- Idempotent: rationale UPDATEs guarded on still-empty; source ops use EXISTS/ON CONFLICT.
BEGIN;

UPDATE entity_relationships SET rationale='Atrax is one of the thirty-six decans of the zodiac enumerated as decan-spirits in the Testament of Solomon''s decan-list.' WHERE subject_entity_id='ENT_LAT_DECAN_ATRAX' AND relationship_type='member_of' AND object_entity_id='ENT_LAT_DECANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Bobel is one of the thirty-six decans of the zodiac enumerated as decan-spirits in the Testament of Solomon''s decan-list.' WHERE subject_entity_id='ENT_LAT_DECAN_BOBEL' AND relationship_type='member_of' AND object_entity_id='ENT_LAT_DECANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Buldumech is one of the thirty-six decans of the zodiac enumerated as decan-spirits in the Testament of Solomon''s decan-list.' WHERE subject_entity_id='ENT_LAT_DECAN_BULDUMECH' AND relationship_type='member_of' AND object_entity_id='ENT_LAT_DECANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Ieropael is one of the thirty-six decans of the zodiac enumerated as decan-spirits in the Testament of Solomon''s decan-list.' WHERE subject_entity_id='ENT_LAT_DECAN_IEROPAEL' AND relationship_type='member_of' AND object_entity_id='ENT_LAT_DECANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Katanikotael is one of the thirty-six decans of the zodiac enumerated as decan-spirits in the Testament of Solomon''s decan-list.' WHERE subject_entity_id='ENT_LAT_DECAN_KATANIKOTAEL' AND relationship_type='member_of' AND object_entity_id='ENT_LAT_DECANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Kumeatel is one of the thirty-six decans of the zodiac enumerated as decan-spirits in the Testament of Solomon''s decan-list.' WHERE subject_entity_id='ENT_LAT_DECAN_KUMEATEL' AND relationship_type='member_of' AND object_entity_id='ENT_LAT_DECANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Mardero is one of the thirty-six decans of the zodiac enumerated as decan-spirits in the Testament of Solomon''s decan-list.' WHERE subject_entity_id='ENT_LAT_DECAN_MARDERO' AND relationship_type='member_of' AND object_entity_id='ENT_LAT_DECANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Naoth is one of the thirty-six decans of the zodiac enumerated as decan-spirits in the Testament of Solomon''s decan-list.' WHERE subject_entity_id='ENT_LAT_DECAN_NAOTH' AND relationship_type='member_of' AND object_entity_id='ENT_LAT_DECANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Roeled is one of the thirty-six decans of the zodiac enumerated as decan-spirits in the Testament of Solomon''s decan-list.' WHERE subject_entity_id='ENT_LAT_DECAN_ROELED' AND relationship_type='member_of' AND object_entity_id='ENT_LAT_DECANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Saphathorael is one of the thirty-six decans of the zodiac enumerated as decan-spirits in the Testament of Solomon''s decan-list.' WHERE subject_entity_id='ENT_LAT_DECAN_SAPHATHORAEL' AND relationship_type='member_of' AND object_entity_id='ENT_LAT_DECANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Atrax is one of the thirty-six decans (heavenly decan-spirits of the zodiac) who afflict humankind with disease; when bound by Solomon it names the specific ailment it inflicts and the angelic name that thwarts it.' WHERE subject_entity_id='ENT_LAT_DECAN_ATRAX' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Bobel is one of the thirty-six decans (heavenly decan-spirits of the zodiac) who afflict humankind with disease; when bound by Solomon it names the specific ailment it inflicts and the angelic name that thwarts it.' WHERE subject_entity_id='ENT_LAT_DECAN_BOBEL' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Buldumech is one of the thirty-six decans (heavenly decan-spirits of the zodiac) who afflict humankind with disease; when bound by Solomon it names the specific ailment it inflicts and the angelic name that thwarts it.' WHERE subject_entity_id='ENT_LAT_DECAN_BULDUMECH' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Ieropael is one of the thirty-six decans (heavenly decan-spirits of the zodiac) who afflict humankind with disease; when bound by Solomon it names the specific ailment it inflicts and the angelic name that thwarts it.' WHERE subject_entity_id='ENT_LAT_DECAN_IEROPAEL' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Katanikotael is one of the thirty-six decans (heavenly decan-spirits of the zodiac) who afflict humankind with disease; when bound by Solomon it names the specific ailment it inflicts and the angelic name that thwarts it.' WHERE subject_entity_id='ENT_LAT_DECAN_KATANIKOTAEL' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Kumeatel is one of the thirty-six decans (heavenly decan-spirits of the zodiac) who afflict humankind with disease; when bound by Solomon it names the specific ailment it inflicts and the angelic name that thwarts it.' WHERE subject_entity_id='ENT_LAT_DECAN_KUMEATEL' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Mardero is one of the thirty-six decans (heavenly decan-spirits of the zodiac) who afflict humankind with disease; when bound by Solomon it names the specific ailment it inflicts and the angelic name that thwarts it.' WHERE subject_entity_id='ENT_LAT_DECAN_MARDERO' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Naoth is one of the thirty-six decans (heavenly decan-spirits of the zodiac) who afflict humankind with disease; when bound by Solomon it names the specific ailment it inflicts and the angelic name that thwarts it.' WHERE subject_entity_id='ENT_LAT_DECAN_NAOTH' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Roeled is one of the thirty-six decans (heavenly decan-spirits of the zodiac) who afflict humankind with disease; when bound by Solomon it names the specific ailment it inflicts and the angelic name that thwarts it.' WHERE subject_entity_id='ENT_LAT_DECAN_ROELED' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Saphathorael is one of the thirty-six decans (heavenly decan-spirits of the zodiac) who afflict humankind with disease; when bound by Solomon it names the specific ailment it inflicts and the angelic name that thwarts it.' WHERE subject_entity_id='ENT_LAT_DECAN_SAPHATHORAEL' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Akton is one of the thirty-six decans of the zodiac enumerated as decan-spirits in the Testament of Solomon''s decan-list.' WHERE subject_entity_id='ENT_LAT_DECAN_AKTON' AND relationship_type='member_of' AND object_entity_id='ENT_LAT_DECANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Alath is one of the thirty-six decans of the zodiac enumerated as decan-spirits in the Testament of Solomon''s decan-list.' WHERE subject_entity_id='ENT_LAT_DECAN_ALATH' AND relationship_type='member_of' AND object_entity_id='ENT_LAT_DECANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Alleborith is one of the thirty-six decans of the zodiac enumerated as decan-spirits in the Testament of Solomon''s decan-list.' WHERE subject_entity_id='ENT_LAT_DECAN_ALLEBORITH' AND relationship_type='member_of' AND object_entity_id='ENT_LAT_DECANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Anatreth is one of the thirty-six decans of the zodiac enumerated as decan-spirits in the Testament of Solomon''s decan-list.' WHERE subject_entity_id='ENT_LAT_DECAN_ANATRETH' AND relationship_type='member_of' AND object_entity_id='ENT_LAT_DECANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Anoster is one of the thirty-six decans of the zodiac enumerated as decan-spirits in the Testament of Solomon''s decan-list.' WHERE subject_entity_id='ENT_LAT_DECAN_ANOSTER' AND relationship_type='member_of' AND object_entity_id='ENT_LAT_DECANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Enenuth is one of the thirty-six decans of the zodiac enumerated as decan-spirits in the Testament of Solomon''s decan-list.' WHERE subject_entity_id='ENT_LAT_DECAN_ENENUTH' AND relationship_type='member_of' AND object_entity_id='ENT_LAT_DECANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Harpax is one of the thirty-six decans of the zodiac enumerated as decan-spirits in the Testament of Solomon''s decan-list.' WHERE subject_entity_id='ENT_LAT_DECAN_HARPAX' AND relationship_type='member_of' AND object_entity_id='ENT_LAT_DECANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Nefthada is one of the thirty-six decans of the zodiac enumerated as decan-spirits in the Testament of Solomon''s decan-list.' WHERE subject_entity_id='ENT_LAT_DECAN_NEFTHADA' AND relationship_type='member_of' AND object_entity_id='ENT_LAT_DECANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Pheth is one of the thirty-six decans of the zodiac enumerated as decan-spirits in the Testament of Solomon''s decan-list.' WHERE subject_entity_id='ENT_LAT_DECAN_PHETH' AND relationship_type='member_of' AND object_entity_id='ENT_LAT_DECANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Akton is one of the thirty-six decans (heavenly decan-spirits of the zodiac) who afflict humankind with disease; when bound by Solomon it names the specific ailment it inflicts and the angelic name that thwarts it.' WHERE subject_entity_id='ENT_LAT_DECAN_AKTON' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Alath is one of the thirty-six decans (heavenly decan-spirits of the zodiac) who afflict humankind with disease; when bound by Solomon it names the specific ailment it inflicts and the angelic name that thwarts it.' WHERE subject_entity_id='ENT_LAT_DECAN_ALATH' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Alleborith is one of the thirty-six decans (heavenly decan-spirits of the zodiac) who afflict humankind with disease; when bound by Solomon it names the specific ailment it inflicts and the angelic name that thwarts it.' WHERE subject_entity_id='ENT_LAT_DECAN_ALLEBORITH' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Anatreth is one of the thirty-six decans (heavenly decan-spirits of the zodiac) who afflict humankind with disease; when bound by Solomon it names the specific ailment it inflicts and the angelic name that thwarts it.' WHERE subject_entity_id='ENT_LAT_DECAN_ANATRETH' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Anoster is one of the thirty-six decans (heavenly decan-spirits of the zodiac) who afflict humankind with disease; when bound by Solomon it names the specific ailment it inflicts and the angelic name that thwarts it.' WHERE subject_entity_id='ENT_LAT_DECAN_ANOSTER' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Enenuth is one of the thirty-six decans (heavenly decan-spirits of the zodiac) who afflict humankind with disease; when bound by Solomon it names the specific ailment it inflicts and the angelic name that thwarts it.' WHERE subject_entity_id='ENT_LAT_DECAN_ENENUTH' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Harpax is one of the thirty-six decans (heavenly decan-spirits of the zodiac) who afflict humankind with disease; when bound by Solomon it names the specific ailment it inflicts and the angelic name that thwarts it.' WHERE subject_entity_id='ENT_LAT_DECAN_HARPAX' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Nefthada is one of the thirty-six decans (heavenly decan-spirits of the zodiac) who afflict humankind with disease; when bound by Solomon it names the specific ailment it inflicts and the angelic name that thwarts it.' WHERE subject_entity_id='ENT_LAT_DECAN_NEFTHADA' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Pheth is one of the thirty-six decans (heavenly decan-spirits of the zodiac) who afflict humankind with disease; when bound by Solomon it names the specific ailment it inflicts and the angelic name that thwarts it.' WHERE subject_entity_id='ENT_LAT_DECAN_PHETH' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Agchonion is one of the thirty-six decans of the zodiac enumerated as decan-spirits in the Testament of Solomon''s decan-list.' WHERE subject_entity_id='ENT_LAT_DECAN_AGCHONION' AND relationship_type='member_of' AND object_entity_id='ENT_LAT_DECANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Autothith is one of the thirty-six decans of the zodiac enumerated as decan-spirits in the Testament of Solomon''s decan-list.' WHERE subject_entity_id='ENT_LAT_DECAN_AUTOTHITH' AND relationship_type='member_of' AND object_entity_id='ENT_LAT_DECANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Bianakith is one of the thirty-six decans of the zodiac enumerated as decan-spirits in the Testament of Solomon''s decan-list.' WHERE subject_entity_id='ENT_LAT_DECAN_BIANAKITH' AND relationship_type='member_of' AND object_entity_id='ENT_LAT_DECANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Hephesikireth is one of the thirty-six decans of the zodiac enumerated as decan-spirits in the Testament of Solomon''s decan-list.' WHERE subject_entity_id='ENT_LAT_DECAN_HEPHESIKIRETH' AND relationship_type='member_of' AND object_entity_id='ENT_LAT_DECANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Ichthion is one of the thirty-six decans of the zodiac enumerated as decan-spirits in the Testament of Solomon''s decan-list.' WHERE subject_entity_id='ENT_LAT_DECAN_ICHTHION' AND relationship_type='member_of' AND object_entity_id='ENT_LAT_DECANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Phthenoth is one of the thirty-six decans of the zodiac enumerated as decan-spirits in the Testament of Solomon''s decan-list.' WHERE subject_entity_id='ENT_LAT_DECAN_PHTHENOTH' AND relationship_type='member_of' AND object_entity_id='ENT_LAT_DECANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Agchonion is one of the thirty-six decans (heavenly decan-spirits of the zodiac) who afflict humankind with disease; when bound by Solomon it names the specific ailment it inflicts and the angelic name that thwarts it.' WHERE subject_entity_id='ENT_LAT_DECAN_AGCHONION' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Autothith is one of the thirty-six decans (heavenly decan-spirits of the zodiac) who afflict humankind with disease; when bound by Solomon it names the specific ailment it inflicts and the angelic name that thwarts it.' WHERE subject_entity_id='ENT_LAT_DECAN_AUTOTHITH' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Bianakith is one of the thirty-six decans (heavenly decan-spirits of the zodiac) who afflict humankind with disease; when bound by Solomon it names the specific ailment it inflicts and the angelic name that thwarts it.' WHERE subject_entity_id='ENT_LAT_DECAN_BIANAKITH' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Hephesikireth is one of the thirty-six decans (heavenly decan-spirits of the zodiac) who afflict humankind with disease; when bound by Solomon it names the specific ailment it inflicts and the angelic name that thwarts it.' WHERE subject_entity_id='ENT_LAT_DECAN_HEPHESIKIRETH' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Ichthion is one of the thirty-six decans (heavenly decan-spirits of the zodiac) who afflict humankind with disease; when bound by Solomon it names the specific ailment it inflicts and the angelic name that thwarts it.' WHERE subject_entity_id='ENT_LAT_DECAN_ICHTHION' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Phthenoth is one of the thirty-six decans (heavenly decan-spirits of the zodiac) who afflict humankind with disease; when bound by Solomon it names the specific ailment it inflicts and the angelic name that thwarts it.' WHERE subject_entity_id='ENT_LAT_DECAN_PHTHENOTH' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, King Solomon, by the authority of his God-given seal-ring, compels and rules the demon Rabdos, binding it to labour on the Temple.' WHERE subject_entity_id='ENT_ISR_SOLOMON' AND relationship_type='rules' AND object_entity_id='ENT_LAT_RABDOS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, King Solomon, by the authority of his God-given seal-ring, compels and rules the demon Leophoros, binding it to labour on the Temple.' WHERE subject_entity_id='ENT_ISR_SOLOMON' AND relationship_type='rules' AND object_entity_id='ENT_LAT_LEOPHOROS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, King Solomon, by the authority of his God-given seal-ring, compels and rules the demon Koruphe, binding it to labour on the Temple.' WHERE subject_entity_id='ENT_ISR_SOLOMON' AND relationship_type='rules' AND object_entity_id='ENT_LAT_KORUPHE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, King Solomon, by the authority of his God-given seal-ring, compels and rules the demon Enepsigos, binding it to labour on the Temple.' WHERE subject_entity_id='ENT_ISR_SOLOMON' AND relationship_type='rules' AND object_entity_id='ENT_LAT_ENEPSIGOS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, King Solomon, by the authority of his God-given seal-ring, compels and rules the demon Ephippas, binding it to labour on the Temple.' WHERE subject_entity_id='ENT_ISR_SOLOMON' AND relationship_type='rules' AND object_entity_id='ENT_LAT_EPHIPPAS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, the demon Leophoros, interrogated and bound by Solomon, is described as bringing affliction upon disease.' WHERE subject_entity_id='ENT_LAT_LEOPHOROS' AND relationship_type='causes_affliction' AND object_entity_id='ENT_DISEASE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, the demon Koruphe, interrogated and bound by Solomon, is described as bringing affliction upon humans.' WHERE subject_entity_id='ENT_LAT_KORUPHE' AND relationship_type='causes_affliction' AND object_entity_id='ENT_HUMANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, the demon Ephippas, interrogated and bound by Solomon, is described as bringing affliction upon humans.' WHERE subject_entity_id='ENT_LAT_EPHIPPAS' AND relationship_type='causes_affliction' AND object_entity_id='ENT_HUMANS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Ephippas acts in concert with and leads Abezithibod, the two together raising the great pillar at Solomon''s command.' WHERE subject_entity_id='ENT_LAT_EPHIPPAS' AND relationship_type='guides' AND object_entity_id='ENT_LAT_ABEZETHIBOU' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Azael is the thwarting angel whom the demon Tephras confesses it fears and by whose name it is frustrated.' WHERE subject_entity_id='ENT_LAT_AZAEL' AND relationship_type='opposes' AND object_entity_id='ENT_LAT_TEPHRAS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Iameth is the thwarting angel whom the demon Kunopegos confesses it fears and by whose name it is frustrated.' WHERE subject_entity_id='ENT_LAT_IAMETH' AND relationship_type='opposes' AND object_entity_id='ENT_LAT_KUNOPEGOS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Iax is the thwarting angel whom the demon Envy confesses it fears and by whose name it is frustrated.' WHERE subject_entity_id='ENT_LAT_IAX' AND relationship_type='opposes' AND object_entity_id='ENT_LAT_ENVY_DEMON' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Rathanael is the thwarting angel whom the demon Enepsigos confesses it fears and by whose name it is frustrated.' WHERE subject_entity_id='ENT_LAT_RATHANAEL' AND relationship_type='opposes' AND object_entity_id='ENT_LAT_ENEPSIGOS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, King Solomon, by the authority of his God-given seal-ring, compels and rules the demon Winged Dragon, binding it to labour on the Temple.' WHERE subject_entity_id='ENT_ISR_SOLOMON' AND relationship_type='rules' AND object_entity_id='ENT_LAT_WINGED_DRAGON' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Testament of Solomon, Bazazath is the thwarting angel whom the demon Winged Dragon confesses it fears and by whose name it is frustrated.' WHERE subject_entity_id='ENT_LAT_BAZAZATH' AND relationship_type='opposes' AND object_entity_id='ENT_LAT_WINGED_DRAGON' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Metatron is enumerated among the ranks of the angelic host (Angels) in the Hekhalot/3 Enoch literature.' WHERE subject_entity_id='ENT_JM_METATRON' AND relationship_type='member_of' AND object_entity_id='ENT_ANGELS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In 3 Enoch (Sefer Hekhalot), Metatron — the transformed Enoch and heavenly scribe — mediates and teaches the Torah and divine wisdom to the celestial academy.' WHERE subject_entity_id='ENT_JM_METATRON' AND relationship_type='mediates' AND object_entity_id='ENT_TORAH' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In 3 Enoch, Enoch undergoes the heavenly ascent and bodily transformation into the angel Metatron.' WHERE subject_entity_id='ENT_ENOCH' AND relationship_type='undergoes_process' AND object_entity_id='ENT_HEAVENLY_JOURNEY' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In 3 Enoch and the scribal tradition, Enoch — taken up as the heavenly scribe who keeps the celestial books — is patron of writing.' WHERE subject_entity_id='ENT_ENOCH' AND relationship_type='patron_of' AND object_entity_id='ENT_WRITING' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In 3 Enoch, the ascended Enoch mediates heavenly revelation, transmitting the celestial secrets disclosed to him during his ascent.' WHERE subject_entity_id='ENT_ENOCH' AND relationship_type='mediates' AND object_entity_id='ENT_REVELATION' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Seraphim is enumerated among the ranks of the angelic host (Angels) in the Hekhalot/3 Enoch literature.' WHERE subject_entity_id='ENT_JM_SERAPHIM' AND relationship_type='member_of' AND object_entity_id='ENT_ANGELS' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Hekhalot/Merkavah literature, the Chayyot are the angelic order that bears and surrounds the divine Throne in the celestial throne-liturgy.' WHERE subject_entity_id='ENT_JM_CHAYYOT' AND relationship_type='associated_ritual' AND object_entity_id='ENT_THRONE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Hekhalot/Merkavah literature, the Ophanim are the angelic order that bears and surrounds the divine Throne in the celestial throne-liturgy.' WHERE subject_entity_id='ENT_JM_OPHANIM' AND relationship_type='associated_ritual' AND object_entity_id='ENT_THRONE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Hekhalot/Merkavah literature, the Hashmallim are the angelic order that bears and surrounds the divine Throne in the celestial throne-liturgy.' WHERE subject_entity_id='ENT_JM_HASHMALLIM' AND relationship_type='associated_ritual' AND object_entity_id='ENT_THRONE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Hekhalot/Merkavah literature, the Seraphim are the angelic order that bears and surrounds the divine Throne in the celestial throne-liturgy.' WHERE subject_entity_id='ENT_JM_SERAPHIM' AND relationship_type='associated_ritual' AND object_entity_id='ENT_THRONE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='In the Hekhalot literature, Sandalphon weaves the prayers and praises of Israel into crowns for the divine Throne, bound to the heavenly liturgy of praise.' WHERE subject_entity_id='ENT_JM_SANDALPHON' AND relationship_type='associated_ritual' AND object_entity_id='ENT_PRAISE' AND (rationale IS NULL OR btrim(rationale)='');
UPDATE entity_relationships SET rationale='Sandalphon is enumerated among the ranks of the angelic host (Angels) in the Hekhalot/3 Enoch literature.' WHERE subject_entity_id='ENT_JM_SANDALPHON' AND relationship_type='member_of' AND object_entity_id='ENT_ANGELS' AND (rationale IS NULL OR btrim(rationale)='');

-- ── legacy orphan sources: ATTACH the genuine bibliographic ones to the figures they document ──
INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
 SELECT entity_id,'SRC_2_ENOCH','primary text attestation','2 Enoch (Slavonic Enoch): Enoch''s ascent and angelic transformation'
 FROM entities WHERE entity_id IN ('ENT_ENOCH','ENT_JM_METATRON') AND EXISTS(SELECT 1 FROM sources WHERE source_id='SRC_2_ENOCH') ON CONFLICT DO NOTHING;
INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
 SELECT entity_id,'SRC_DSS_WAR_SCROLL','primary text attestation','named in the War Scroll (1QM) of the Dead Sea Scrolls'
 FROM entities WHERE (canonical_name ILIKE 'Michael' OR canonical_name ILIKE '%belial%' OR canonical_name ILIKE '%prince of light%' OR canonical_name ILIKE '%melchizedek%' OR canonical_name ILIKE '%melchiresha%')
 AND (entity_id LIKE 'ENT\_ISR\_%' ESCAPE '\' OR entity_id LIKE 'ENT\_JM\_%' ESCAPE '\' OR entity_id LIKE 'ENT\_DSS\_%' ESCAPE '\') AND EXISTS(SELECT 1 FROM sources WHERE source_id='SRC_DSS_WAR_SCROLL') ON CONFLICT DO NOTHING;
INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
 SELECT entity_id,'SRC_MENOG_I_KHRAD','primary text attestation','discussed in the Pahlavi wisdom text Menog-i Khrad'
 FROM entities WHERE entity_id LIKE 'ENT\_ZOR\_%' ESCAPE '\' AND (canonical_name ILIKE '%ahura mazda%' OR canonical_name ILIKE '%ahriman%' OR canonical_name ILIKE '%amesha%' OR canonical_name ILIKE '%fravashi%')
 AND EXISTS(SELECT 1 FROM sources WHERE source_id='SRC_MENOG_I_KHRAD') ON CONFLICT DO NOTHING;
INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
 SELECT entity_id,'SRC_SAPPHO_FRAGMENTS','primary text attestation','invoked in the lyric fragments of Sappho'
 FROM entities WHERE entity_id IN ('ENT_APHRODITE','ENT_EROS','ENT_HERA','ENT_APHRODITE_OURANIA') AND EXISTS(SELECT 1 FROM sources WHERE source_id='SRC_SAPPHO_FRAGMENTS') ON CONFLICT DO NOTHING;
INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
 SELECT entity_id,'SRC_LINDOW_NORSE','scholarly attestation','treated in John Lindow, Norse Mythology: A Guide'
 FROM entities WHERE tradition LIKE 'Germanic/Norse%' AND (canonical_name ILIKE 'Odin' OR canonical_name ILIKE 'Thor' OR canonical_name ILIKE 'Freyja' OR canonical_name ILIKE 'Loki' OR canonical_name ILIKE 'Frigg' OR canonical_name ILIKE 'Tyr' OR canonical_name ILIKE 'Baldr')
 AND EXISTS(SELECT 1 FROM sources WHERE source_id='SRC_LINDOW_NORSE') ON CONFLICT DO NOTHING;
INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
 SELECT entity_id,'SRC_DIGITAL_EGYPT','reference attestation','catalogued in UCL Digital Egypt for Universities'
 FROM entities WHERE tradition LIKE 'Egyptian%' AND (canonical_name ILIKE 'Ra' OR canonical_name ILIKE 'Isis' OR canonical_name ILIKE 'Osiris' OR canonical_name ILIKE 'Thoth' OR canonical_name ILIKE 'Horus' OR canonical_name ILIKE 'Anubis')
 AND EXISTS(SELECT 1 FROM sources WHERE source_id='SRC_DIGITAL_EGYPT') ON CONFLICT DO NOTHING;
INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
 SELECT entity_id,'SRC_CATHOLIC_ENCYCLOPEDIA_SAINTS','reference attestation','entry in the Catholic Encyclopedia'
 FROM entities WHERE entity_id IN ('ENT_SAINT_FRANCIS','ENT_SAINT_DOMINIC','ENT_SAINT_BENEDICT','ENT_SAINT_BECKET') AND EXISTS(SELECT 1 FROM sources WHERE source_id='SRC_CATHOLIC_ENCYCLOPEDIA_SAINTS') ON CONFLICT DO NOTHING;
INSERT INTO entity_sources (entity_id,source_id,evidence_type,source_note)
 SELECT entity_id,'SRC_BIBLIOTHECA_SANCTORUM','scholarly attestation','entry in the Bibliotheca Sanctorum (Istituto Giovanni XXIII)'
 FROM entities WHERE (entity_id LIKE 'ENT\_SAINT\_%' ESCAPE '\' OR entity_id LIKE 'ENT\_EMC\_%' ESCAPE '\' OR entity_id LIKE 'ENT\_MOC\_%' ESCAPE '\')
 AND (canonical_name ILIKE 'Francis%' OR canonical_name ILIKE 'Clare%' OR canonical_name ILIKE 'Dominic%' OR canonical_name ILIKE '%Catherine of Siena%' OR canonical_name ILIKE '%Teresa of %' OR canonical_name ILIKE '%Ignatius%' OR canonical_name ILIKE '%Padre Pio%')
 AND EXISTS(SELECT 1 FROM sources WHERE source_id='SRC_BIBLIOTHECA_SANCTORUM') ON CONFLICT DO NOTHING;

-- ── RETIRE non-attestational orphan sources (internal placeholder + two place/text gazetteers) ──
DELETE FROM sources WHERE source_id IN ('SRC_INTERNAL_HEURISTIC_V0_2','SRC_PLEIADES','SRC_TOPOSTEXT')
 AND NOT EXISTS(SELECT 1 FROM entity_sources es WHERE es.source_id=sources.source_id)
 AND NOT EXISTS(SELECT 1 FROM entity_relationships r WHERE r.source_id=sources.source_id);

COMMIT;

\echo '--- rationale-less relationships remaining (target 0) ---'
SELECT count(*) FROM entity_relationships WHERE rationale IS NULL OR btrim(rationale)='';
\echo '--- orphan sources remaining (target 0) ---'
SELECT count(*) FROM sources s WHERE NOT EXISTS(SELECT 1 FROM entity_sources es WHERE es.source_id=s.source_id) AND NOT EXISTS(SELECT 1 FROM entity_relationships r WHERE r.source_id=s.source_id);
