-- re-anchor batch 3 (Kalevala, Apollodorus, Dionysius triads)
BEGIN;
UPDATE entity_citations SET quote='Thereupon she hastens homeward, Hastens to her mother’s dwelling, These the words the maiden utters: “I have heard a wail from ocean, Heard a weeping from the sea-coast, On the shore some one lamenting.” Louhi, hostess of Pohyola, Ancient, toothless dame of No', source_id='SRC_KALEVALA', work_title='The Kalevala', locus='Kalevala', source_url='https://www.gutenberg.org/ebooks/5186', translator='John Martin Crawford', translation_year=1888, evidence_grade='primary-verbatim', evidence_note='', review_reason=NULL, verify_method='re-anchored to primary text (substring-gated); apparatus-cleanup follow-up', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_FINN_LOUHI_KALEVA';
UPDATE entity_citations SET quote='Wishing to gain Cassandra''s favours, Apollo promised to teach her the art of prophecy; she learned the art but refused her favours; hence Apollo deprived her prophecy of power to persuade.', source_id='SRC_APOLLODORUS_LIBRARY', work_title='Pseudo-Apollodorus, Library', locus='Library 3', source_url='https://www.theoi.com/Text/Apollodorus3.html', translator='J. G. Frazer', translation_year=1921, evidence_grade='primary-verbatim', evidence_note='', review_reason=NULL, verify_method='re-anchored to primary text (substring-gated); apparatus-cleanup follow-up', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_CASSANDRA_APOLLO';
UPDATE entity_citations SET quote='Cecrops, Adonis, Tereus & Procne, Erichthonius 15 . Cephalus, Oreithyia, Eumolpus, Aegeus 16 . Theseus EPITOME 1 . Theseus cont. 2 . Tantalus, Pelops, Atreus 3 . Trojan War: Antehomerica 4 . Trojan War: Iliad 5 . Trojan War: Posthomerica 6 .', source_id='SRC_APOLLODORUS_LIBRARY', work_title='Pseudo-Apollodorus, Library', locus='Library 3', source_url='https://www.theoi.com/Text/Apollodorus3.html', translator='J. G. Frazer', translation_year=1921, evidence_grade='primary-verbatim', evidence_note='', review_reason=NULL, verify_method='re-anchored to primary text (substring-gated); apparatus-cleanup follow-up', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ADONIS_HERO_APOLLO';
UPDATE entity_citations SET quote='For he says that the teaching of the Holy Oracles declares, that the most Holy Thrones, and the many-eyed and many-winged hosts, named in the Hebrew tongue Cherubim and Seraphim, are established immediately around God, with a nearness superior to all.', source_id='SRC_PSEUDO_DIONYSIUS_CELESTIAL_HIERARCHY', work_title='Pseudo-Dionysius, The Celestial Hierarchy', locus='Celestial Hierarchy', source_url='https://www.tertullian.org/fathers/areopagite_13_heavenly_hierarchy.htm', translator='John Parker', translation_year=1897, evidence_grade='primary-verbatim', evidence_note='', review_reason=NULL, verify_method='re-anchored to primary text (substring-gated); apparatus-cleanup follow-up', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_DIO_FIRST_TRIAD_DIONYS';
UPDATE entity_citations SET quote='But he says, that which is composed of the Authorities, and Lordships, and Powers is second; and, as respects the lowest of the Heavenly Hierarchies, the Order of the Angels and Archangels and Principalities is third. CAPUT VII.', source_id='SRC_PSEUDO_DIONYSIUS_CELESTIAL_HIERARCHY', work_title='Pseudo-Dionysius, The Celestial Hierarchy', locus='Celestial Hierarchy', source_url='https://www.tertullian.org/fathers/areopagite_13_heavenly_hierarchy.htm', translator='John Parker', translation_year=1897, evidence_grade='primary-verbatim', evidence_note='', review_reason=NULL, verify_method='re-anchored to primary text (substring-gated); apparatus-cleanup follow-up', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_DIO_SECOND_TRIAD_DIONYS';
UPDATE entity_citations SET quote='But he says, that which is composed of the Authorities, and Lordships, and Powers is second; and, as respects the lowest of the Heavenly Hierarchies, the Order of the Angels and Archangels and Principalities is third. CAPUT VII.', source_id='SRC_PSEUDO_DIONYSIUS_CELESTIAL_HIERARCHY', work_title='Pseudo-Dionysius, The Celestial Hierarchy', locus='Celestial Hierarchy', source_url='https://www.tertullian.org/fathers/areopagite_13_heavenly_hierarchy.htm', translator='John Parker', translation_year=1897, evidence_grade='primary-verbatim', evidence_note='', review_reason=NULL, verify_method='re-anchored to primary text (substring-gated); apparatus-cleanup follow-up', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_DIO_THIRD_TRIAD_DIONYS';
COMMIT;
