-- re-anchor apparatus-cleanup pointers to primary text (batch 1: in-hand sources)
BEGIN;
UPDATE entity_citations SET quote='Geri and Freki the war-wont sates, the triumphant sire of hosts; but on wine only the famed in arms, Odin, ever lives.', source_id='SRC_POETIC_EDDA', work_title='The Poetic Edda (Grimnismal)', locus='Grimnismal', source_url='https://www.gutenberg.org/ebooks/14726', translator='Benjamin Thorpe', translation_year=1866, evidence_grade='primary-verbatim', evidence_note='', review_reason=NULL, verify_method='re-anchored to primary text (substring-gated); apparatus-cleanup follow-up', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_NOR_GERI_POETIC';
UPDATE entity_citations SET quote='Hugin and Munin fly each day over the spacious earth. I fear for Hugin, that he come not back, yet more anxious am I for Munin.', source_id='SRC_POETIC_EDDA', work_title='The Poetic Edda (Grimnismal)', locus='Grimnismal', source_url='https://www.gutenberg.org/ebooks/14726', translator='Benjamin Thorpe', translation_year=1866, evidence_grade='primary-verbatim', evidence_note='', review_reason=NULL, verify_method='re-anchored to primary text (substring-gated); apparatus-cleanup follow-up', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_NOR_HUGINN_POETIC';
UPDATE entity_citations SET quote='I know all, where thou thine eye didst sink in the pure well of Mim.', source_id='SRC_POETIC_EDDA', work_title='The Poetic Edda (Voluspa)', locus='Voluspa', source_url='https://www.gutenberg.org/ebooks/14726', translator='Benjamin Thorpe', translation_year=1866, evidence_grade='primary-verbatim', evidence_note='', review_reason=NULL, verify_method='re-anchored to primary text (substring-gated); apparatus-cleanup follow-up', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_NORR_MIMISBRUNNR_POETIC';
UPDATE entity_citations SET quote='I know an ash standing Yggdrasil hight, a lofty tree, laved with limpid water: thence come the dews into the dales that fall; ever stands it green over Urd', source_id='SRC_POETIC_EDDA', work_title='The Poetic Edda (Voluspa)', locus='Voluspa', source_url='https://www.gutenberg.org/ebooks/14726', translator='Benjamin Thorpe', translation_year=1866, evidence_grade='primary-verbatim', evidence_note='', review_reason=NULL, verify_method='re-anchored to primary text (substring-gated); apparatus-cleanup follow-up', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_NORR_URDARBRUNNR_POETIC';
UPDATE entity_citations SET quote='It is worth giving a full account of how Thor made a journey to Geirrodsgard.', source_id='SRC_PROSE_EDDA', work_title='Snorri Sturluson, Prose Edda', locus='Skaldskaparmal', source_url='https://www.gutenberg.org/ebooks/18947', translator='Rasmus B. Anderson', translation_year=1880, evidence_grade='primary-verbatim', evidence_note='', review_reason=NULL, verify_method='re-anchored to primary text (substring-gated); apparatus-cleanup follow-up', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_NOR_GEIRROD_GIANT_PROSE_';
UPDATE entity_citations SET quote='Rahatiel who is appointed over the constellations.', source_id='SRC_3_ENOCH', work_title='3 Enoch (The Hebrew Book of Enoch)', locus='3 Enoch 14', source_url='https://archive.org/details/HebrewBookOfEnochenoch3', translator='Hugo Odeberg', translation_year=1928, evidence_grade='primary-verbatim', evidence_note='', review_reason=NULL, verify_method='re-anchored to primary text (substring-gated); apparatus-cleanup follow-up', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_JM_RAHATIEL_ENOCH3';
UPDATE entity_citations SET quote='And why do I say so much? I have an angel that frustrates me: "Marmarath."', source_id='SRC_TESTAMENT_SOLOMON', work_title='The Testament of Solomon', locus='Testament of Solomon', source_url='https://www.esotericarchives.com/solomon/testamen.htm', translator='F. C. Conybeare', translation_year=1898, evidence_grade='primary-verbatim', evidence_note='', review_reason=NULL, verify_method='re-anchored to primary text (substring-gated); apparatus-cleanup follow-up', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_LAT_DECAN_MARMARETH_TESTSO';
COMMIT;
