-- scripts/source_greek_long_tail.sql
-- Sourcing rigor VII (v1.42.0): the Greek long tail. The last ~154 ref-only Greek
-- entities (sourced only to the Theoi index) brought to verified PRIMARY-TEXT
-- attestation, each matched to its correct ancient locus. Additive: the Theoi
-- reference is kept; this adds the cited primary passage. All entities are currently
-- ref-only, so there is no dedupe risk. Loci verified against Theoi/Perseus by
-- research pass (UNVERIFIED figures deliberately left: Lampades, Mormolykeia,
-- Eleutheria, Soter, Soteria, Kakodaimon — no clean primary locus survives).

BEGIN;

-- ── New public-domain primary texts (+ two ancient compilations) ──────────────
INSERT INTO sources (source_id, title, url, source_type, scope) VALUES
('SRC_OVID_METAMORPHOSES','Ovid, Metamorphoses, c. 8 CE','','primary text','The great Latin epic of transformation; the canonical locus for many nymph and metamorphosis myths'),
('SRC_NONNUS_DIONYSIACA','Nonnus of Panopolis, Dionysiaca, c. 5th c. CE','','primary text','The vast late-antique Greek epic of Dionysus; Zagreus, Beroe'),
('SRC_LUCIAN_ALEXANDER','Lucian of Samosata, Alexander the False Prophet (Alexandros), c. 180 CE','','primary text','Lucian''s expose of the oracle-cult of the snake-god Glycon'),
('SRC_STRABO_GEOGRAPHY','Strabo, Geographica (Geography), c. 7 BCE-23 CE','','primary text','The major Greek geography; cult topography, the Kabeiroi/Korybantes, Anatolian Men'),
('SRC_DIODORUS_SICULUS','Diodorus Siculus, Bibliotheca Historica (Library of History), c. 60-30 BCE','','primary text','The universal history; Rhodian Telchines, the Kouretes and Korybantes, Libyan Lamia'),
('SRC_CALLIMACHUS_HYMNS','Callimachus, Hymns, c. 270 BCE','','primary text','The six Hellenistic hymns; Amaltheia (Hymn to Zeus), the Nesoi (Hymn to Delos)'),
('SRC_THEOCRITUS_IDYLLS','Theocritus, Idylls, c. 270 BCE','','primary text','The Hellenistic bucolic poems; the child-bogey Mormo (Idyll 15)'),
('SRC_APULEIUS_GOLDEN_ASS','Apuleius, Metamorphoses (The Golden Ass), c. 160 CE','','primary text','The Latin novel containing the tale of Cupid and Psyche'),
('SRC_VIRGIL_GEORGICS','Virgil, Georgics, 29 BCE','','primary text','The didactic poem on farming; the Aristaeus epyllion and the bugonia'),
('SRC_OVID_HEROIDES','Ovid, Heroides, c. 15 BCE','','primary text','The verse epistles of mythic heroines; Phyllis (Heroides 2)'),
('SRC_APOLLONIUS_ARGONAUTICA','Apollonius of Rhodes, Argonautica, 3rd c. BCE','','primary text','The Hellenistic Argonaut epic; the Samothracian Great Gods, Ophion and Eurynome, Brimo'),
('SRC_DAMASCIUS_PRINCIPLES','Damascius, De Principiis (Problems and Solutions Concerning First Principles), c. 520 CE','','primary text','The last Neoplatonist''s work, preserving the Orphic Rhapsodic theogony (Hydros, Thesis)'),
('SRC_AESCHYLUS_ORESTEIA','Aeschylus, Oresteia trilogy (Agamemnon, Choephoroi, Eumenides), 458 BCE','','primary text','The tragic trilogy; Alastor, Poine, Thrasos, Hermes Chthonios, the Eumenides, Themis at Delphi'),
('SRC_AESCHYLUS_SUPPLIANTS','Aeschylus, Suppliants (Hiketides), c. 463 BCE','','primary text','The tragedy of the Danaids; Pothos in Aphrodite''s retinue'),
('SRC_EURIPIDES_BACCHAE','Euripides, Bacchae, 405 BCE','','primary text','The tragedy of Dionysus at Thebes; the Maenads'),
('SRC_EURIPIDES_HERACLES','Euripides, Heracles (Herakles Mainomenos), c. 416 BCE','','primary text','The tragedy of Heracles'' madness; Lyssa'),
('SRC_EURIPIDES_HERACLEIDAE','Euripides, Heracleidae (Children of Heracles), c. 430 BCE','','primary text','The tragedy of the Heraclid suppliants; the self-sacrifice of Macaria'),
('SRC_PINDAR_ODES','Pindar, Odes and Fragments (Snell-Maehler), c. 498-446 BCE','','primary text','The victory odes and fragments; Tyche, Nomos, Hymenaios, Alala'),
('SRC_ARISTOPHANES_THESMOPHORIAZUSAE','Aristophanes, Thesmophoriazusae, 411 BCE','','primary text','The comedy of the women''s festival; Kalligeneia'),
('SRC_ARISTOPHANES_FROGS','Aristophanes, Frogs (Batrachoi), 405 BCE','','primary text','The comedy of Dionysus'' descent; the phantom Empusa'),
('SRC_ARISTOPHANES_BIRDS','Aristophanes, Birds (Ornithes), 414 BCE','','primary text','The comedy of Cloudcuckooland; Basileia (Sovereignty)'),
('SRC_ARISTOPHANES_KNIGHTS','Aristophanes, Knights (Hippeis), 424 BCE','','primary text','The political comedy; the libation to the Agathos Daimon'),
('SRC_SAPPHO_FRAGMENTS','Sappho, Fragments (Lobel-Page/Voigt), c. 600 BCE','','primary text','The lyric fragments of Sappho of Lesbos'),
('SRC_ALCAEUS_FRAGMENTS','Alcaeus of Mytilene, Fragments (Lobel-Page), c. 600 BCE','','primary text','The lyric fragments of Alcaeus; Amechania, sister of Penia (fr. 364)'),
('SRC_THEOGNIS_ELEGIES','Theognis of Megara, Elegies, c. 6th c. BCE','','primary text','The elegiac corpus; Sophrosyne fled to Olympus'),
('SRC_POSIDIPPUS_EPIGRAMS','Posidippus of Pella, Epigrams (incl. Greek Anthology 16.275), c. 270 BCE','','primary text','The Hellenistic epigrams; the dialogue on Lysippos'' statue of Kairos'),
('SRC_HYGINUS_FABULAE','Hyginus, Fabulae, c. 1st-2nd c. CE','','primary text','The Latin mythographic handbook; the genealogy of personifications (Praefatio)'),
('SRC_MNASEAS_FRAGMENTS','Mnaseas of Patrae, Fragments (incl. On Europe), c. 3rd c. BCE','','primary text','The fragmentary periegete; Homonoia, daughter of Soter and Praxidike'),
('SRC_PHILOSTRATUS_VA','Philostratus, Life of Apollonius of Tyana, c. 220 CE','','primary text','The biography of the Neopythagorean sage; altars of Techne at Gadeira'),
('SRC_ZENOBIUS_PROVERBS','Zenobius, Epitome of Proverbs (transmitting Sappho fr. 178), 2nd c. CE','','primary text','The paroemiographic collection preserving the Sapphic attestation of Gello'),
('SRC_SERVIUS_COMMENTARY','Servius, In Vergilii Carmina Commentarii (Commentary on Virgil), c. 400 CE','','secondary scholarship','The late-antique grammarian''s commentary preserving the metamorphoses of Leuce and Chelone'),
('SRC_SUDA','Suda (Souda), Byzantine Greek encyclopedic lexicon, c. 10th c. CE','','reference work','The great Byzantine lexicon preserving otherwise-lost ancient attestations')
ON CONFLICT (source_id) DO NOTHING;

-- ── Attach each ref-only Greek entity to its verified primary locus ───────────
INSERT INTO entity_sources (entity_id, source_id, evidence_type, source_note)
SELECT e.entity_id, t.src, 'Direct attestation', t.note
FROM (VALUES
 -- healing / Eleusinian / underworld
 ('Aceso','SRC_SUDA','Suda (s.v. Epione): Akeso, a healing daughter of Asclepius and Epione.'),
 ('Iaso','SRC_PAUSANIAS_DESCRIPTION','Pausanias 1.34.3: named on the altar at the Amphiareion at Oropus with Hygieia and Panacea.'),
 ('Hygieia','SRC_PAUSANIAS_DESCRIPTION','Pausanias 1.34.3 (Amphiareion altar at Oropus); cf. dedicated Orphic Hymn 68.'),
 ('Panacea','SRC_PAUSANIAS_DESCRIPTION','Pausanias 1.34.3: "to Aphrodite and Panakeia, and to Iaso, Hygieia and Athena Paionia."'),
 ('Epione','SRC_PAUSANIAS_DESCRIPTION','Pausanias 2.29.1: the wife of Asclepius, her image in the precinct at Epidaurus.'),
 ('Eubouleus','SRC_ORPHIC_HYMNS','Orphic Hymn 30.6-7 (to Dionysus); invoked also at OH 29 and 41 as an Eleusinian chthonic figure.'),
 ('Iacchus','SRC_HERODOTUS_HISTORIES','Herodotus 8.65: the Eleusinian "Iakchos" procession-cry; cf. Orphic Hymn 42.'),
 ('Triptolemus','SRC_HOMERIC_HYMNS','Homeric Hymn to Demeter (2) 153, 474: the Eleusinian prince who receives Demeter''s rites.'),
 ('Kalligeneia','SRC_ARISTOPHANES_THESMOPHORIAZUSAE','Aristophanes, Thesmophoriazusae 298-300: invoked in the women''s prayer; a nurse-figure of Demeter.'),
 ('Acheron','SRC_HOMER_ILIAD_ODYSSEY','Odyssey 10.513: the underworld river into which Cocytus and Pyriphlegethon flow.'),
 ('Cocytus','SRC_HOMER_ILIAD_ODYSSEY','Odyssey 10.513-514: the river of wailing, a branch of the Styx.'),
 ('Phlegethon','SRC_HOMER_ILIAD_ODYSSEY','Odyssey 10.513: the fiery Pyriphlegethon of the underworld.'),
 ('Lethe','SRC_PLATO_REPUBLIC','Plato, Republic 10.621a-c: the river/plain of Lethe in the Myth of Er; cf. Virgil Aeneid 6.705.'),
 ('Orphne','SRC_OVID_METAMORPHOSES','Ovid, Metamorphoses 5.539-541: the underworld nymph, mother of Ascalaphus by Acheron.'),
 ('Gorgyra','SRC_APOLLODORUS_LIBRARY','Apollodorus 1.5.3: mother of Ascalaphus by Acheron (a variant of Orphne).'),
 ('Eurynomos','SRC_PAUSANIAS_DESCRIPTION','Pausanias 10.28.7: the corpse-devouring underworld daimon in Polygnotus'' Nekyia at Delphi.'),
 ('Ascalaphus','SRC_APOLLODORUS_LIBRARY','Apollodorus 1.5.3: reveals that Persephone ate the pomegranate; cf. Ovid Met. 5.534-550.'),
 ('Empousa','SRC_ARISTOPHANES_FROGS','Aristophanes, Frogs 293-295: the shape-shifting phantom of the underworld road.'),
 ('Empusa','SRC_ARISTOPHANES_FROGS','Aristophanes, Frogs 293-295: the shape-shifting phantom of the underworld road.'),
 ('Melinoe','SRC_ORPHIC_HYMNS','Orphic Hymn 71: the chthonic goddess, daughter of Persephone.'),
 ('Plouton','SRC_HOMERIC_HYMNS','Homeric Hymn to Demeter (2) 9, 17-18 (Polydegmon/Plouton, the abductor); cf. dedicated Orphic Hymn 18.'),
 ('Hades Klymenos','SRC_PAUSANIAS_DESCRIPTION','Pausanias 2.35.9: Hades worshipped as Klymenos at Hermione.'),
 ('Macaria','SRC_EURIPIDES_HERACLEIDAE','Euripides, Heracleidae 500-534: the self-sacrificing daughter of Heracles, identified with Makaria, goddess of blessed death.'),
 ('Macaria','SRC_SUDA','Suda (s.v. Makaria): Makaria, daughter of Hades, the goddess of a blessed death.'),
 ('Brimo','SRC_APOLLONIUS_ARGONAUTICA','Apollonius, Argonautica 3.861-862: Hecate/Persephone invoked under the name Brimo.'),
 ('Enodia','SRC_ORPHIC_HYMNS','Orphic Hymn 1.1: "Einodian Hekaten" - Hecate of the crossroads.'),
 ('Hermes Chthonios','SRC_AESCHYLUS_ORESTEIA','Aeschylus, Choephoroi 1: the opening invocation of "Hermes chthonios."'),
 ('Zeus Chthonios','SRC_HESIOD_WORKS_DAYS','Hesiod, Works and Days 465: "pray to Zeus Chthonios and to pure Demeter" at the first ploughing.'),
 ('Zeus Meilichios','SRC_PAUSANIAS_DESCRIPTION','Pausanias 1.37.4: the altar of Zeus Meilichios on the Sacred Way, where Theseus was purified.'),
 ('Zeus Ktesios','SRC_PAUSANIAS_DESCRIPTION','Pausanias 1.31.4: the household property-protector cult form; cf. Antoninus Liberalis 19.'),
 -- personified abstractions / daimones
 ('Adikia','SRC_PAUSANIAS_DESCRIPTION','Pausanias 5.18.2: on the Chest of Cypselus, Dike throttles the ugly Adikia (Injustice).'),
 ('Alastor','SRC_AESCHYLUS_ORESTEIA','Aeschylus, Agamemnon 1501: Clytemnestra invokes the Alastor (avenging spirit) of the house of Atreus.'),
 ('Alala','SRC_PINDAR_ODES','Pindar fr. 78 (Snell-Maehler): "Alala, daughter of Polemos (War)," the battle-cry personified.'),
 ('Amechania','SRC_ALCAEUS_FRAGMENTS','Alcaeus fr. 364 (Lobel-Page): Amechania (Helplessness), sister of Penia, lays a great people low.'),
 ('Basileia','SRC_ARISTOPHANES_BIRDS','Aristophanes, Birds 1536-1537: Basileia (Sovereignty) keeps Zeus''s thunderbolt; to win her is to win kingship.'),
 ('Caerus','SRC_PAUSANIAS_DESCRIPTION','Pausanias 5.14.9: the altar of Kairos (Opportunity) near the stadium entrance at Olympia.'),
 ('Kairos','SRC_POSIDIPPUS_EPIGRAMS','Posidippus, epigram on Lysippos'' statue of Kairos (Greek Anthology 16.275): tiptoe, winged, with forelock and razor.'),
 ('Dikaiosyne','SRC_ORPHIC_HYMNS','Orphic Hymn 63: to Dikaiosyne (Righteousness).'),
 ('Dike','SRC_HESIOD_THEOGONY','Hesiod, Theogony 901-906: one of the Horai, daughter of Zeus and Themis; cf. Works and Days 256.'),
 ('Eleos','SRC_PAUSANIAS_DESCRIPTION','Pausanias 1.17.1: the Athenians alone honour an altar of Eleos (Mercy) in the agora.'),
 ('Epiphron','SRC_HYGINUS_FABULAE','Hyginus, Fabulae Praefatio: Epiphron (Prudence) among the offspring of Nox and Erebus.'),
 ('Eusebeia','SRC_ORPHIC_HYMNS','Orphic Hymns, Proem (to Mousaios): Eusebeia (Piety) named among the invoked deities.'),
 ('Hedone','SRC_XENOPHON_MEMORABILIA','Xenophon, Memorabilia 2.1.21-34: in Prodicus'' Choice of Heracles, Vice is called Hedone (Pleasure) by her foes.'),
 ('Homonoia','SRC_MNASEAS_FRAGMENTS','Mnaseas, On Europe (fr.): Homonoia (Concord), daughter of Soter and Praxidike.'),
 ('Hybris','SRC_HESIOD_WORKS_DAYS','Hesiod, Works and Days 213-218: the warning that Dike prevails over Hybris (Insolence).'),
 ('Lyssa','SRC_EURIPIDES_HERACLES','Euripides, Heracles 815ff: Iris brings Lyssa (Madness), daughter of Nyx, to drive Heracles mad.'),
 ('Mania','SRC_PAUSANIAS_DESCRIPTION','Pausanias 8.34.1-3: the sanctuary of the Maniai near Megalopolis, where Orestes went mad.'),
 ('Nomos','SRC_PINDAR_ODES','Pindar fr. 169a (Snell-Maehler): "Nomos, king of all" (transmitted via Plato, Gorgias 484b).'),
 ('Nike','SRC_HESIOD_THEOGONY','Hesiod, Theogony 383-384: daughter of Styx and Pallas, with Zelos, Kratos and Bia.'),
 ('Peitho','SRC_HESIOD_WORKS_DAYS','Hesiod, Works and Days 73: "queenly Peitho" (Persuasion) adorns Pandora.'),
 ('Poine','SRC_AESCHYLUS_ORESTEIA','Aeschylus, Choephoroi 935-937: Poine (Retribution) comes upon the house of Atreus.'),
 ('Poinai','SRC_AESCHYLUS_ORESTEIA','Aeschylus, Choephoroi 935-937: the Poinai, spirits of retribution upon the house of Atreus.'),
 ('Pothos','SRC_AESCHYLUS_SUPPLIANTS','Aeschylus, Suppliants 1038-1041: Pothos (Yearning) in Aphrodite''s retinue beside Peitho.'),
 ('Praxis','SRC_PAUSANIAS_DESCRIPTION','Pausanias 1.43.6: the ivory Aphrodite "surnamed Praxis" at Megara.'),
 ('Sophrosyne','SRC_THEOGNIS_ELEGIES','Theognis 1135-1136: Sophrosyne (Moderation) has fled men to Olympus.'),
 ('Techne','SRC_PHILOSTRATUS_VA','Philostratus, Life of Apollonius 5.4: altars to Techne (Skill) at Gadeira.'),
 ('Thrasos','SRC_AESCHYLUS_ORESTEIA','Aeschylus, Agamemnon 763-766: the unholy daimon Thrasos (Audacity) bred by old Hybris.'),
 ('Tychon','SRC_STRABO_GEOGRAPHY','Strabo, Geography 13.1.12: Tychon among Priapus''s fertility daimones with Konisalos and Orthanes.'),
 ('Tyche','SRC_PINDAR_ODES','Pindar, Olympian 12.1-2: "Saviour Tyche, daughter of Zeus Eleutherios"; cf. Hesiod Theog. 360.'),
 ('Eirene','SRC_HESIOD_THEOGONY','Hesiod, Theogony 901-902: one of the Horai, "blooming Eirene" (Peace); dramatised in Aristophanes'' Peace.'),
 ('Eunomia','SRC_HESIOD_THEOGONY','Hesiod, Theogony 902: daughter of Zeus and Themis, one of the Horai.'),
 ('Phosphorus','SRC_HESIOD_THEOGONY','Hesiod, Theogony 378-382: Eos bears Eosphoros (the Morning Star) to Astraios.'),
 ('Hymenaios','SRC_PINDAR_ODES','Pindar fr. 128c.7-8 (Snell-Maehler): the wedding-god Hymenaios, lamented with Linos and Ialemos.'),
 ('Agathos Daimon','SRC_ARISTOPHANES_KNIGHTS','Aristophanes, Knights 85: the libation of unmixed wine to the Agathos Daimon (Good Spirit).'),
 ('Plutus','SRC_HESIOD_THEOGONY','Hesiod, Theogony 969-974: Demeter bears Ploutos (Wealth) to Iasion in Crete; dramatised in Aristophanes'' Plutus.'),
 -- nymphs / metamorphosis / monsters / heroes & deified mortals
 ('Aganippe','SRC_PAUSANIAS_DESCRIPTION','Pausanias 9.29.5: the spring Aganippe on Helicon, by the grove of the Muses.'),
 ('Arethusa','SRC_OVID_METAMORPHOSES','Ovid, Metamorphoses 5.572-641: the nymph''s flight from Alpheus, transformed into a spring.'),
 ('Daphne','SRC_OVID_METAMORPHOSES','Ovid, Metamorphoses 1.452-567: pursued by Apollo, she becomes the laurel.'),
 ('Echo','SRC_OVID_METAMORPHOSES','Ovid, Metamorphoses 3.339-401: the nymph wasted to a voice in the Narcissus episode.'),
 ('Syrinx','SRC_OVID_METAMORPHOSES','Ovid, Metamorphoses 1.689-712: flees Pan and becomes the reeds of the panpipe.'),
 ('Salmacis','SRC_OVID_METAMORPHOSES','Ovid, Metamorphoses 4.285-388: the spring-nymph who merges with Hermaphroditus.'),
 ('Minthe','SRC_STRABO_GEOGRAPHY','Strabo, Geography 8.3.14: Hades''s concubine, trampled by Persephone and changed into mint.'),
 ('Leuce','SRC_SERVIUS_COMMENTARY','Servius on Eclogues 7.61: the Oceanid carried off by Pluto, made the white poplar.'),
 ('Beroe','SRC_NONNUS_DIONYSIACA','Nonnus, Dionysiaca 41-42: the contest of Poseidon and Dionysus for the nymph Beroe.'),
 ('Ephyra','SRC_PAUSANIAS_DESCRIPTION','Pausanias 2.1.1: the Oceanid Ephyra, first to dwell in the land later called Corinth.'),
 ('Chelone','SRC_SERVIUS_COMMENTARY','Servius on Aeneid 1.505: the nymph turned to a tortoise for scorning Zeus''s wedding.'),
 ('Cyllene','SRC_APOLLODORUS_LIBRARY','Apollodorus 3.8.1: the nymph Kyllene, wife of Pelasgus.'),
 ('Maia','SRC_HESIOD_THEOGONY','Hesiod, Theogony 938-939: the Pleiad daughter of Atlas who bore Hermes to Zeus; cf. Homeric Hymn to Hermes 1-9.'),
 ('Melia','SRC_APOLLODORUS_LIBRARY','Apollodorus 2.1.1: the Oceanid Melia, consort of Inachus.'),
 ('Amaltheia','SRC_CALLIMACHUS_HYMNS','Callimachus, Hymn to Zeus (1) 48-49: the she-goat Amaltheia who suckled the infant Zeus.'),
 ('Phyllis','SRC_OVID_HEROIDES','Ovid, Heroides 2: the Thracian princess Phyllis, abandoned by Demophon.'),
 ('Doris','SRC_HESIOD_THEOGONY','Hesiod, Theogony 240-241: the Oceanid wife of Nereus, mother of the Nereids.'),
 ('Tyche Oceanid','SRC_HESIOD_THEOGONY','Hesiod, Theogony 360: Tyche in the catalogue of Oceanids, daughter of Oceanus and Tethys.'),
 ('Hydra','SRC_APOLLODORUS_LIBRARY','Apollodorus 2.5.2: the Lernaean Hydra, slain in the second labour of Heracles.'),
 ('Geryon','SRC_APOLLODORUS_LIBRARY','Apollodorus 2.5.10: the three-bodied Geryon, slain in the tenth labour.'),
 ('Scylla','SRC_HOMER_ILIAD_ODYSSEY','Odyssey 12.85-100: Circe''s description of the six-headed Scylla.'),
 ('Charybdis','SRC_HOMER_ILIAD_ODYSSEY','Odyssey 12.101-110: the thrice-daily whirlpool beneath the fig tree.'),
 ('Minotaur','SRC_APOLLODORUS_LIBRARY','Apollodorus 3.1.4: born of Pasiphae and the bull (Asterius, "the Minotaur"); slain by Theseus, Epitome 1.8.'),
 ('Lamia','SRC_DIODORUS_SICULUS','Diodorus Siculus 20.41: the Libyan queen Lamia who devoured others'' children.'),
 ('Gello','SRC_ZENOBIUS_PROVERBS','Zenobius, Proverbs 3.3, preserving Sappho fr. 178: Gello, the ghost of one dead young, who carries off children.'),
 ('Mormo','SRC_THEOCRITUS_IDYLLS','Theocritus, Idyll 15.40: "Mormo, the horse bites" - the child-frightening bogey.'),
 ('Glycon','SRC_LUCIAN_ALEXANDER','Lucian, Alexander the False Prophet 12-18: the snake-puppet oracle "Glycon, grandson of Zeus."'),
 ('Daedalus','SRC_OVID_METAMORPHOSES','Ovid, Metamorphoses 8.183ff: the craftsman''s wings and the flight from Crete; cf. Apollodorus Epitome 1.12.'),
 ('Palamedes','SRC_APOLLODORUS_LIBRARY','Apollodorus, Epitome 3.8: the hero framed and killed by Odysseus at Troy.'),
 ('Melampus','SRC_APOLLODORUS_LIBRARY','Apollodorus 1.9.11: serpents lick his ears, granting him prophecy.'),
 ('Calchas','SRC_HOMER_ILIAD_ODYSSEY','Iliad 1.68-72: "far the best of bird-diviners," seer of the Achaeans.'),
 ('Cassandra','SRC_APOLLODORUS_LIBRARY','Apollodorus 3.12.5: Apollo''s gift of prophecy, made unpersuasive when she refused him.'),
 ('Manto','SRC_PAUSANIAS_DESCRIPTION','Pausanias 9.33.2: the prophetic daughter of Tiresias, sent to Colophon.'),
 ('Amphiaraus','SRC_PAUSANIAS_DESCRIPTION','Pausanias 1.34: the dream-oracle of the seer-hero Amphiaraus at Oropus.'),
 ('Trophonius','SRC_PAUSANIAS_DESCRIPTION','Pausanias 9.39: the oracle of Trophonios at Lebadeia and its descent ritual.'),
 ('Glaucus','SRC_OVID_METAMORPHOSES','Ovid, Metamorphoses 13.898ff: the Anthedon fisherman made a sea-god by a magic herb.'),
 ('Aristaeus','SRC_VIRGIL_GEORGICS','Virgil, Georgics 4.315-558: the rustic god of beekeeping, the loss of his bees and the bugonia.'),
 ('Linus','SRC_PAUSANIAS_DESCRIPTION','Pausanias 9.29.6-9: the musician Linos, son of Urania, killed by Apollo.'),
 ('Ariadne','SRC_HESIOD_THEOGONY','Hesiod, Theogony 947-949: Dionysus makes Ariadne deathless; cf. Odyssey 11.321-325.'),
 ('Psyche','SRC_APULEIUS_GOLDEN_ASS','Apuleius, Metamorphoses (Golden Ass) 4.28-6.24: Cupid and Psyche; she is made immortal at 6.24.'),
 ('Ino','SRC_HOMER_ILIAD_ODYSSEY','Odyssey 5.333-335: the mortal daughter of Cadmus, now the sea-goddess Leucothea.'),
 ('Melicertes-Palaemon','SRC_OVID_METAMORPHOSES','Ovid, Metamorphoses 4.519-542: Ino''s leap with the infant Melicertes, deified as Palaemon/Leucothea.'),
 ('Palaemon','SRC_PAUSANIAS_DESCRIPTION','Pausanias 2.1.3: the Isthmian cult of Palaemon, with the dolphin and the founding of the games.'),
 ('Tithonus','SRC_HOMERIC_HYMNS','Homeric Hymn 5 (to Aphrodite) 218-238: granted immortality without eternal youth.'),
 ('Hermaphroditus','SRC_OVID_METAMORPHOSES','Ovid, Metamorphoses 4.285-388: merged with the nymph Salmacis into one two-sexed body.'),
 ('Despoina','SRC_PAUSANIAS_DESCRIPTION','Pausanias 8.37: the mysteries of Despoina at Lykosoura; daughter of Poseidon and Demeter.'),
 ('Dioscuri','SRC_HOMERIC_HYMNS','Homeric Hymn 33 (to the Dioscuri): the saviour twins Castor and Polydeuces; cf. Odyssey 11.298-304.'),
 ('Hesperides','SRC_HESIOD_THEOGONY','Hesiod, Theogony 215-216: the daughters of Nyx who guard the golden apples beyond Ocean.'),
 -- collectives / mystery cults / Orphic primordials / cult forms / rustic gods
 ('Cabeiri','SRC_STRABO_GEOGRAPHY','Strabo, Geography 10.3.21: the Kabeiroi and their mystery rites, linked to Samothrace and Lemnos.'),
 ('Great Gods of Samothrace','SRC_APOLLONIUS_ARGONAUTICA','Apollonius, Argonautica 1.915-921: the Argonauts initiated into the rites of the Great Gods of Samothrace.'),
 ('Corybantes','SRC_DIODORUS_SICULUS','Diodorus Siculus 5.49: the Korybantes, celebrants of the Mother''s ecstatic rites.'),
 ('Korybantes','SRC_STRABO_GEOGRAPHY','Strabo, Geography 10.3.19: the Korybantes, armed dancers of the Phrygian Mother, linked with the Kouretes and Kabeiroi.'),
 ('Kouretes','SRC_DIODORUS_SICULUS','Diodorus Siculus 5.65: the Idaean Kouretes who reared the infant Zeus, drowning his cries with their war-dance.'),
 ('Curetes','SRC_HOMER_ILIAD_ODYSSEY','Homer, Iliad 9.529ff: the Aetolian Kouretes who besieged Calydon.'),
 ('Anytus','SRC_PAUSANIAS_DESCRIPTION','Pausanias 8.37.5: Anytos, one of the Titans, who reared Despoina at Lykosoura.'),
 ('Cyclopes Craftsmen','SRC_HESIOD_THEOGONY','Hesiod, Theogony 139-146: Brontes, Steropes and Arges, the smith-Cyclopes who forged Zeus''s thunderbolt.'),
 ('Satyrs','SRC_STRABO_GEOGRAPHY','Hesiod fr. 10a (Merkelbach-West), transmitted by Strabo 10.3.19: the Satyrs born with the Nymphs and Kouretes.'),
 ('Silenus','SRC_HOMERIC_HYMNS','Homeric Hymn 5 (to Aphrodite) 262: the Sileni who mate with nymphs in the depths of caves.'),
 ('Maenads','SRC_EURIPIDES_BACCHAE','Euripides, Bacchae 55: the thiasos of bacchant women of Dionysus.'),
 ('Thyiads','SRC_PAUSANIAS_DESCRIPTION','Pausanias 10.4.3: the Thyiades, women who dance the biennial Dionysiac rites on Parnassus.'),
 ('Nosoi','SRC_HESIOD_WORKS_DAYS','Hesiod, Works and Days 102-104: the countless Nosoi (Diseases) that escaped Pandora''s jar.'),
 ('Oneiroi','SRC_HESIOD_THEOGONY','Hesiod, Theogony 211-212: Nyx bears the tribe of Dreams (Oneiroi).'),
 ('Morpheus','SRC_OVID_METAMORPHOSES','Ovid, Metamorphoses 11.635: Morpheus, shaper of human forms, son of Somnus.'),
 ('Phantasos','SRC_OVID_METAMORPHOSES','Ovid, Metamorphoses 11.642: Phantasos, who takes the form of earth, rock, water and wood.'),
 ('Phobetor','SRC_OVID_METAMORPHOSES','Ovid, Metamorphoses 11.640: "Icelos to the gods, Phobetor to mortals," who takes beast-forms.'),
 ('Zagreus','SRC_NONNUS_DIONYSIACA','Nonnus, Dionysiaca 6.155-205: the horned infant Zagreus, dismembered by the Titans.'),
 ('Pallas','SRC_HESIOD_THEOGONY','Hesiod, Theogony 376, 383-385: the Titan Pallas, father of Zelos, Nike, Kratos and Bia by Styx.'),
 ('Eurynome Primordial','SRC_APOLLONIUS_ARGONAUTICA','Apollonius, Argonautica 1.503-506: Eurynome and Ophion ruled Olympus before Cronus and Rhea.'),
 ('Hydros','SRC_DAMASCIUS_PRINCIPLES','Damascius, De Principiis 123: Hydros (Water), with Mud, the first principle of the Orphic Rhapsodic theogony.'),
 ('Ophion','SRC_APOLLONIUS_ARGONAUTICA','Apollonius, Argonautica 1.503-506: the primordial serpent Ophion who ruled Olympus with Eurynome.'),
 ('Thesis','SRC_DAMASCIUS_PRINCIPLES','Damascius, De Principiis 123: Thesis (Disposition), an ineffable first principle of the Orphic theogony.'),
 ('Nesoi','SRC_CALLIMACHUS_HYMNS','Callimachus, Hymn 4 (to Delos) 300: the islands form a choir around Delos.'),
 ('Priapus','SRC_PAUSANIAS_DESCRIPTION','Pausanias 9.31.2: Priapos, most revered at Lampsacus, son of Dionysus and Aphrodite.'),
 ('Mên','SRC_STRABO_GEOGRAPHY','Strabo, Geography 12.3.31: the Anatolian lunar god Men Pharnakou, worshipped at Ameria in Pontus.'),
 ('Kourotrophos','SRC_HOMERIC_HYMNS','Homeric Hymn 30 (to Gaia) 1-3: Gaia the all-nurturing mother of all (the Kourotrophos function).'),
 ('Themis at Delphi','SRC_AESCHYLUS_ORESTEIA','Aeschylus, Eumenides 1-8: Themis held the Delphic oracular seat, second after Gaia, before Apollo.'),
 ('Charites','SRC_HESIOD_THEOGONY','Hesiod, Theogony 907-911: the three Graces Aglaia, Euphrosyne and Thalia, borne by Eurynome to Zeus.'),
 ('Muses','SRC_HESIOD_THEOGONY','Hesiod, Theogony 75-79: the nine daughters of Zeus and Mnemosyne.'),
 ('Muses Heliconian','SRC_HESIOD_THEOGONY','Hesiod, Theogony 1-2: the opening invocation of "the Heliconian Muses."'),
 ('Nereids','SRC_HESIOD_THEOGONY','Hesiod, Theogony 240-264: the fifty daughters of Nereus and Doris.'),
 ('Oceanids','SRC_HESIOD_THEOGONY','Hesiod, Theogony 346-366: the three thousand daughters of Oceanus and Tethys.'),
 ('Erinyes','SRC_HESIOD_THEOGONY','Hesiod, Theogony 183-185: born from the blood of the castrated Ouranos.'),
 ('Eumenides','SRC_AESCHYLUS_ORESTEIA','Aeschylus, Eumenides 1021-1047: the Erinyes transformed into the kindly Semnai/Eumenides.'),
 ('Horae','SRC_HESIOD_THEOGONY','Hesiod, Theogony 901-906: Eunomia, Dike and Eirene, daughters of Zeus and Themis.'),
 ('Eileithyia','SRC_HESIOD_THEOGONY','Hesiod, Theogony 922: daughter of Zeus and Hera, goddess of childbirth.'),
 ('Telchines','SRC_DIODORUS_SICULUS','Diodorus Siculus 5.55: the Telchines, first inhabitants of Rhodes, smiths and weather-magicians who reared Poseidon.')
) AS t(name, src, note)
JOIN entities e ON e.tradition LIKE 'Greek%' AND e.canonical_name = t.name
ON CONFLICT DO NOTHING;

-- ── Verify ───────────────────────────────────────────────────────────────────
SELECT round(100.0*count(*) FILTER (WHERE ok)/count(*),1) AS pct_rigorous_overall,
       count(*) FILTER (WHERE NOT ok) AS ref_only_total
FROM (SELECT e.entity_id,
  bool_or(s.source_type IN ('primary text','primary inscription/artifact','heresiological source','secondary scholarship')) ok
  FROM entities e LEFT JOIN entity_sources es ON es.entity_id=e.entity_id LEFT JOIN sources s ON s.source_id=es.source_id
  GROUP BY e.entity_id) g;
SELECT 'Greek ref-only remaining' AS label, count(*) FROM (
  SELECT e.entity_id, bool_or(s.source_type IN ('primary text','primary inscription/artifact','heresiological source','secondary scholarship')) ok
  FROM entities e LEFT JOIN entity_sources es ON es.entity_id=e.entity_id LEFT JOIN sources s ON s.source_id=es.source_id
  WHERE e.tradition LIKE 'Greek%' GROUP BY e.entity_id) g WHERE NOT ok;
SELECT count(*) AS dup_pairs FROM (SELECT entity_id, source_id FROM entity_sources GROUP BY 1,2 HAVING count(*)>1) d;
SELECT count(*) AS unsourced FROM entities e WHERE NOT EXISTS (SELECT 1 FROM entity_sources s WHERE s.entity_id=e.entity_id);
SELECT * FROM v_release_metrics;

COMMIT;
