-- MacKillop (1998) Celtic secondary excerpts.
BEGIN;
UPDATE entity_citations SET quote='The bear-goddess of the Continental Celts as represented in a small bronze found at Berne.', work_title='James MacKillop, Dictionary of Celtic Mythology (Oxford University Press, 1998), s.v. Artio', verify_method='secondary-scholarship excerpt; substring-gated against MacKillop (1998) OCR; cross-reference asterisks removed', needs_review=true, review_reason='In-copyright peer-reviewed reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_CEL_ARTIO_SEC';
UPDATE entity_citations SET quote='An ancestor deity who established several royal lines in Wales.', work_title='James MacKillop, Dictionary of Celtic Mythology (Oxford University Press, 1998), s.v. Beli Mawr', verify_method='secondary-scholarship excerpt; substring-gated against MacKillop (1998) OCR; cross-reference asterisks removed', needs_review=true, review_reason='In-copyright peer-reviewed reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_WEL_BELI_MAWR_SEC';
UPDATE entity_citations SET quote='British goddess at the time of the Roman occupation, a personification of the hegemony of the Brigantes.', work_title='James MacKillop, Dictionary of Celtic Mythology (Oxford University Press, 1998), s.v. Brigantia', verify_method='secondary-scholarship excerpt; substring-gated against MacKillop (1998) OCR; cross-reference asterisks removed', needs_review=true, review_reason='In-copyright peer-reviewed reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_BRI_BRIGANTIA_SEC';
UPDATE entity_citations SET quote='Malevolent female figure in early Irish tradition, perhaps a divinity.', work_title='James MacKillop, Dictionary of Celtic Mythology (Oxford University Press, 1998), s.v. Carman', verify_method='secondary-scholarship excerpt; substring-gated against MacKillop (1998) OCR; cross-reference asterisks removed', needs_review=true, review_reason='In-copyright peer-reviewed reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_IRH_CARMAN_SEC';
UPDATE entity_citations SET quote='Gaulish goddess known only from an inscription in Haute Savoie in eastern France.', work_title='James MacKillop, Dictionary of Celtic Mythology (Oxford University Press, 1998), s.v. Cathubodua', verify_method='secondary-scholarship excerpt; substring-gated against MacKillop (1998) OCR; cross-reference asterisks removed', needs_review=true, review_reason='In-copyright peer-reviewed reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_CEL_CATHUBODUA_SEC';
UPDATE entity_citations SET quote='A god worshipped in early Britain, especially in the north and west, whom the Romans compared with Mars.', work_title='James MacKillop, Dictionary of Celtic Mythology (Oxford University Press, 1998), s.v. Cocidius', verify_method='secondary-scholarship excerpt; substring-gated against MacKillop (1998) OCR; cross-reference asterisks removed', needs_review=true, review_reason='In-copyright peer-reviewed reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_BRI_COCIDIUS_SEC';
UPDATE entity_citations SET quote='Name for a British goddess worshipped during the Roman occupation.', work_title='James MacKillop, Dictionary of Celtic Mythology (Oxford University Press, 1998), s.v. Coventina', verify_method='secondary-scholarship excerpt; substring-gated against MacKillop (1998) OCR; cross-reference asterisks removed', needs_review=true, review_reason='In-copyright peer-reviewed reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_BRI_COVENTINA_SEC';
UPDATE entity_citations SET quote='Speculative name for the mother goddess of the Continental Celts based on the evidence of place.', work_title='James MacKillop, Dictionary of Celtic Mythology (Oxford University Press, 1998), s.v. Danu', verify_method='secondary-scholarship excerpt; substring-gated against MacKillop (1998) OCR; cross-reference asterisks removed', needs_review=true, review_reason='In-copyright peer-reviewed reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_CEL_DANU_SEC';
UPDATE entity_citations SET quote='Important god of ancient Gaul, known both from Latin commentaries and from archaeological evidence.', work_title='James MacKillop, Dictionary of Celtic Mythology (Oxford University Press, 1998), s.v. Esus', verify_method='secondary-scholarship excerpt; substring-gated against MacKillop (1998) OCR; cross-reference asterisks removed', needs_review=true, review_reason='In-copyright peer-reviewed reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_CEL_ESUS_SEC';
UPDATE entity_citations SET quote='Celtic god of Roman-occupied Britain and Gaul often linked to Apollo.', work_title='James MacKillop, Dictionary of Celtic Mythology (Oxford University Press, 1998), s.v. Maponos', verify_method='secondary-scholarship excerpt; substring-gated against MacKillop (1998) OCR; cross-reference asterisks removed', needs_review=true, review_reason='In-copyright peer-reviewed reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_CEL_MAPONOS_SEC';
UPDATE entity_citations SET quote='Gaulish raven-goddess whose worship is recorded in several locations.', work_title='James MacKillop, Dictionary of Celtic Mythology (Oxford University Press, 1998), s.v. Nantosuelta', verify_method='secondary-scholarship excerpt; substring-gated against MacKillop (1998) OCR; cross-reference asterisks removed', needs_review=true, review_reason='In-copyright peer-reviewed reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_CEL_NANTOSUELTA_SEC';
UPDATE entity_citations SET quote='Gaulish god of eloquence and letters known primarily froma single 2nd-century ap text.', work_title='James MacKillop, Dictionary of Celtic Mythology (Oxford University Press, 1998), s.v. Ogmios', verify_method='secondary-scholarship excerpt; substring-gated against MacKillop (1998) OCR; cross-reference asterisks removed', needs_review=true, review_reason='In-copyright peer-reviewed reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_CEL_OGMIOS_SEC';
UPDATE entity_citations SET quote='Ritona was a Continental Celtic goddess of fords worshipped at Trier, in what is now Germany.', work_title='James MacKillop, Dictionary of Celtic Mythology (Oxford University Press, 1998), s.v. Ritona', verify_method='secondary-scholarship excerpt; substring-gated against MacKillop (1998) OCR; cross-reference asterisks removed', needs_review=true, review_reason='In-copyright peer-reviewed reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_CEL_RITONA_SEC';
UPDATE entity_citations SET quote='Gaulish goddess of healing springs whose cult has been recorded at sites from Hungary to Brittany.', work_title='James MacKillop, Dictionary of Celtic Mythology (Oxford University Press, 1998), s.v. Sirona', verify_method='secondary-scholarship excerpt; substring-gated against MacKillop (1998) OCR; cross-reference asterisks removed', needs_review=true, review_reason='In-copyright peer-reviewed reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_CEL_SIRONA_SEC';
UPDATE entity_citations SET quote='Gaulish god, personification of the Vosges mountains and forest of eastern France.', work_title='James MacKillop, Dictionary of Celtic Mythology (Oxford University Press, 1998), s.v. Vosegus', verify_method='secondary-scholarship excerpt; substring-gated against MacKillop (1998) OCR; cross-reference asterisks removed', needs_review=true, review_reason='In-copyright peer-reviewed reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_CEL_VOSEGUS_SEC';
UPDATE entity_citations SET quote='Name for one of the three great fairs of early Ireland and the Fir Bolg queen there commemorated.', work_title='James MacKillop, Dictionary of Celtic Mythology (Oxford University Press, 1998), s.v. Tailtiu', verify_method='secondary-scholarship excerpt; substring-gated against MacKillop (1998) OCR; cross-reference asterisks removed', needs_review=true, review_reason='In-copyright peer-reviewed reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_IRH_TAILTIU_SEC';
COMMIT;
