-- Upgrade pointer-only Ovid Fasti citations to verbatim (Riley prose, Bohn).
BEGIN;
UPDATE entity_citations SET quote='And do ye take heed that the birds, a nuisance to the tilled fields, do not in mischievous flocks lay waste the gifts of Ceres.', evidence_grade='primary-verbatim', work_title='Ovid, Fasti (Riley, Bohn Classical Library)', translator='Henry T. Riley', translation_year=1851, source_url='https://archive.org/details/fastitristiapon00ovid', original_text_url='https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.02.0547', verify_method='pointer→verbatim upgrade; substring-gated against Riley prose Fasti (OCR; footnote/Latin/argument windows excluded)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ROM_CERES_SEC';
UPDATE entity_citations SET quote='I will cause, too, that with thee there shall be a memorial of thy crown, which Vulcan gave to Venus, she to thee.', evidence_grade='primary-verbatim', work_title='Ovid, Fasti (Riley, Bohn Classical Library)', translator='Henry T. Riley', translation_year=1851, source_url='https://archive.org/details/fastitristiapon00ovid', original_text_url='https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.02.0547', verify_method='pointer→verbatim upgrade; substring-gated against Riley prose Fasti (OCR; footnote/Latin/argument windows excluded)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ROM_VENUS_SEC';
UPDATE entity_citations SET quote='Hercules had been sold by Mercury, to serve as a slave for three years, to Omphale, queen of Lydia or Maeonia.', evidence_grade='primary-verbatim', work_title='Ovid, Fasti (Riley, Bohn Classical Library)', translator='Henry T. Riley', translation_year=1851, source_url='https://archive.org/details/fastitristiapon00ovid', original_text_url='https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.02.0547', verify_method='pointer→verbatim upgrade; substring-gated against Riley prose Fasti (OCR; footnote/Latin/argument windows excluded)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ROM_MERCURY_SEC';
UPDATE entity_citations SET quote='but the one after it has been consecrated to Quirinus.', evidence_grade='primary-verbatim', work_title='Ovid, Fasti (Riley, Bohn Classical Library)', translator='Henry T. Riley', translation_year=1851, source_url='https://archive.org/details/fastitristiapon00ovid', original_text_url='https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.02.0547', verify_method='pointer→verbatim upgrade; substring-gated against Riley prose Fasti (OCR; footnote/Latin/argument windows excluded)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ROM_QUIRINUS_SEC';
UPDATE entity_citations SET quote='These shrines are worthy of the trophies won from the giants ; it becomes Gradivus from this spot to give an impulse to the cruel warfare.', evidence_grade='primary-verbatim', work_title='Ovid, Fasti (Riley, Bohn Classical Library)', translator='Henry T. Riley', translation_year=1851, source_url='https://archive.org/details/fastitristiapon00ovid', original_text_url='https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.02.0547', verify_method='pointer→verbatim upgrade; substring-gated against Riley prose Fasti (OCR; footnote/Latin/argument windows excluded)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ROM_MARS_SEC';
UPDATE entity_citations SET quote='Bacchus gave the wine ; each had brought a chaplet for himself ; a rivulet rolled by its waters, to be but sparingly mixed.', evidence_grade='primary-verbatim', work_title='Ovid, Fasti (Riley, Bohn Classical Library)', translator='Henry T. Riley', translation_year=1851, source_url='https://archive.org/details/fastitristiapon00ovid', original_text_url='https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.02.0547', verify_method='pointer→verbatim upgrade; substring-gated against Riley prose Fasti (OCR; footnote/Latin/argument windows excluded)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ROM_BACCHUS_SEC';
UPDATE entity_citations SET quote='He used to offer the annual gifts to the Genius of his father.', evidence_grade='primary-verbatim', work_title='Ovid, Fasti (Riley, Bohn Classical Library)', translator='Henry T. Riley', translation_year=1851, source_url='https://archive.org/details/fastitristiapon00ovid', original_text_url='https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.02.0547', verify_method='pointer→verbatim upgrade; substring-gated against Riley prose Fasti (OCR; footnote/Latin/argument windows excluded)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ROM_GENIUS_SEC';
UPDATE entity_citations SET quote='She is carried in perfect safety over the waters of her son Neptune.', evidence_grade='primary-verbatim', work_title='Ovid, Fasti (Riley, Bohn Classical Library)', translator='Henry T. Riley', translation_year=1851, source_url='https://archive.org/details/fastitristiapon00ovid', original_text_url='https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.02.0547', verify_method='pointer→verbatim upgrade; substring-gated against Riley prose Fasti (OCR; footnote/Latin/argument windows excluded)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ROM_NEPTUNE_SEC';
UPDATE entity_citations SET quote='and Saturn afterwards reigned on the Latian side of the Tiber.', evidence_grade='primary-verbatim', work_title='Ovid, Fasti (Riley, Bohn Classical Library)', translator='Henry T. Riley', translation_year=1851, source_url='https://archive.org/details/fastitristiapon00ovid', original_text_url='https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.02.0547', verify_method='pointer→verbatim upgrade; substring-gated against Riley prose Fasti (OCR; footnote/Latin/argument windows excluded)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ROM_SATURN_SEC';
UPDATE entity_citations SET quote='that fierce battles are waged by the hand of Minerva ; has she on that account less leisure for the liberal arts.', evidence_grade='primary-verbatim', work_title='Ovid, Fasti (Riley, Bohn Classical Library)', translator='Henry T. Riley', translation_year=1851, source_url='https://archive.org/details/fastitristiapon00ovid', original_text_url='https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.02.0547', verify_method='pointer→verbatim upgrade; substring-gated against Riley prose Fasti (OCR; footnote/Latin/argument windows excluded)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ROM_MINERVA_SEC';
UPDATE entity_citations SET quote='Genial Pales, do thou favour the poet.', evidence_grade='primary-verbatim', work_title='Ovid, Fasti (Riley, Bohn Classical Library)', translator='Henry T. Riley', translation_year=1851, source_url='https://archive.org/details/fastitristiapon00ovid', original_text_url='https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.02.0547', verify_method='pointer→verbatim upgrade; substring-gated against Riley prose Fasti (OCR; footnote/Latin/argument windows excluded)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ROM_PALES_SEC';
COMMIT;
