-- Upgrade pointer-only ETCSL (Sumerian) citations to verbatim.
BEGIN;
UPDATE entity_citations SET quote='Neti, the chief doorman of the underworld, answered holy Inana.', evidence_grade='primary-verbatim', work_title='Electronic Text Corpus of Sumerian Literature (ETCSL)', translator='Black, Cunningham, Robson, Zólyomi et al.', translation_year=2006, source_url='https://etcsl.orinst.ox.ac.uk/', verify_method='pointer→verbatim upgrade; substring-gated against ETCSL translation (ASCII translit; line-labels/apparatus stripped)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_MES_NETI_SEC';
UPDATE entity_citations SET quote='Ninjiczida, who brings together giant snakes and dragons.', evidence_grade='primary-verbatim', work_title='Electronic Text Corpus of Sumerian Literature (ETCSL)', translator='Black, Cunningham, Robson, Zólyomi et al.', translation_year=2006, source_url='https://etcsl.orinst.ox.ac.uk/', verify_method='pointer→verbatim upgrade; substring-gated against ETCSL translation (ASCII translit; line-labels/apparatus stripped)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_MES_NINGISHZIDA_SEC';
UPDATE entity_citations SET quote='Bau was pleading petitions in a prayer for the king.', evidence_grade='primary-verbatim', work_title='Electronic Text Corpus of Sumerian Literature (ETCSL)', translator='Black, Cunningham, Robson, Zólyomi et al.', translation_year=2006, source_url='https://etcsl.orinst.ox.ac.uk/', verify_method='pointer→verbatim upgrade; substring-gated against ETCSL translation (ASCII translit; line-labels/apparatus stripped)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_MES_BAU_SEC';
UPDATE entity_citations SET quote='She has made perfect the divine powers of medicine, and hands them over to her son, the king of Jirsi, the kindly Damu.', evidence_grade='primary-verbatim', work_title='Electronic Text Corpus of Sumerian Literature (ETCSL)', translator='Black, Cunningham, Robson, Zólyomi et al.', translation_year=2006, source_url='https://etcsl.orinst.ox.ac.uk/', verify_method='pointer→verbatim upgrade; substring-gated against ETCSL translation (ASCII translit; line-labels/apparatus stripped)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_MES_DAMU_SEC';
UPDATE entity_citations SET quote='the Asag, a child who sucked the power of milk without ever staying with a wet-nurse.', evidence_grade='primary-verbatim', work_title='Electronic Text Corpus of Sumerian Literature (ETCSL)', translator='Black, Cunningham, Robson, Zólyomi et al.', translation_year=2006, source_url='https://etcsl.orinst.ox.ac.uk/', verify_method='pointer→verbatim upgrade; substring-gated against ETCSL translation (ASCII translit; line-labels/apparatus stripped)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_MES_ASAG_SEC';
UPDATE entity_citations SET quote='Namma, the primeval mother who gave birth to the senior gods.', evidence_grade='primary-verbatim', work_title='Electronic Text Corpus of Sumerian Literature (ETCSL)', translator='Black, Cunningham, Robson, Zólyomi et al.', translation_year=2006, source_url='https://etcsl.orinst.ox.ac.uk/', verify_method='pointer→verbatim upgrade; substring-gated against ETCSL translation (ASCII translit; line-labels/apparatus stripped)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_MES_NAMMU_SEC';
UPDATE entity_citations SET quote='I am named with a good name by Ninhursaja. I am the leader of the Anuna gods.', evidence_grade='primary-verbatim', work_title='Electronic Text Corpus of Sumerian Literature (ETCSL)', translator='Black, Cunningham, Robson, Zólyomi et al.', translation_year=2006, source_url='https://etcsl.orinst.ox.ac.uk/', verify_method='pointer→verbatim upgrade; substring-gated against ETCSL translation (ASCII translit; line-labels/apparatus stripped)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_MES_NINHURSAG_SEC';
UPDATE entity_citations SET quote='He brought forth the Anzud bird from the halub-haran tree.', evidence_grade='primary-verbatim', work_title='Electronic Text Corpus of Sumerian Literature (ETCSL)', translator='Black, Cunningham, Robson, Zólyomi et al.', translation_year=2006, source_url='https://etcsl.orinst.ox.ac.uk/', verify_method='pointer→verbatim upgrade; substring-gated against ETCSL translation (ASCII translit; line-labels/apparatus stripped)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_MES_ANZU_SEC';
UPDATE entity_citations SET quote='Bring my Jectin-ana, bring my sister.', evidence_grade='primary-verbatim', work_title='Electronic Text Corpus of Sumerian Literature (ETCSL)', translator='Black, Cunningham, Robson, Zólyomi et al.', translation_year=2006, source_url='https://etcsl.orinst.ox.ac.uk/', verify_method='pointer→verbatim upgrade; substring-gated against ETCSL translation (ASCII translit; line-labels/apparatus stripped)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_MES_GESHTINANNA_SEC';
UPDATE entity_citations SET quote='Nance, the august lady, who rests her feet on the holy pelican, is to be the fisheries inspector of the sea.', evidence_grade='primary-verbatim', work_title='Electronic Text Corpus of Sumerian Literature (ETCSL)', translator='Black, Cunningham, Robson, Zólyomi et al.', translation_year=2006, source_url='https://etcsl.orinst.ox.ac.uk/', verify_method='pointer→verbatim upgrade; substring-gated against ETCSL translation (ASCII translit; line-labels/apparatus stripped)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_MES_NANSHE_SEC';
UPDATE entity_citations SET quote='For the Anuna gods, Enki situated dwellings in cities and disposed agricultural land into fields.', evidence_grade='primary-verbatim', work_title='Electronic Text Corpus of Sumerian Literature (ETCSL)', translator='Black, Cunningham, Robson, Zólyomi et al.', translation_year=2006, source_url='https://etcsl.orinst.ox.ac.uk/', verify_method='pointer→verbatim upgrade; substring-gated against ETCSL translation (ASCII translit; line-labels/apparatus stripped)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_MES_ANUNNAKI_SEC';
UPDATE entity_citations SET quote='Utu turned Dumuzid''s hands into snake.', evidence_grade='primary-verbatim', work_title='Electronic Text Corpus of Sumerian Literature (ETCSL)', translator='Black, Cunningham, Robson, Zólyomi et al.', translation_year=2006, source_url='https://etcsl.orinst.ox.ac.uk/', verify_method='pointer→verbatim upgrade; substring-gated against ETCSL translation (ASCII translit; line-labels/apparatus stripped)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_MES_UTU_SHAMASH_SEC';
COMMIT;
