-- Davidson Dictionary of Angels secondary excerpts (Jewish).
BEGIN;
UPDATE entity_citations SET quote='In cabalistic cosmology, one of the lowest of the 4 worlds.', work_title='Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (The Free Press, 1967), s.v. Assiah', source_url='https://archive.org/details/dictionaryofange0000davi', verify_method='secondary-scholarship excerpt; substring-gated against Davidson Dictionary of Angels OCR; 2-column bleed eyeballed out', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_JM_ASSIAH_SEC';
UPDATE entity_citations SET quote='Angel of the wheel of the sun.', work_title='Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (The Free Press, 1967), s.v. Galgaliel', source_url='https://archive.org/details/dictionaryofange0000davi', verify_method='secondary-scholarship excerpt; substring-gated against Davidson Dictionary of Angels OCR; 2-column bleed eyeballed out', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_JM_GALGALIEL_SEC';
UPDATE entity_citations SET quote='Angel of hailstorms in Jewish legend.', work_title='Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (The Free Press, 1967), s.v. Nuriel', source_url='https://archive.org/details/dictionaryofange0000davi', verify_method='secondary-scholarship excerpt; substring-gated against Davidson Dictionary of Angels OCR; 2-column bleed eyeballed out', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_JM_NURIEL_SEC';
UPDATE entity_citations SET quote='An angel with dominion over thunder.', work_title='Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (The Free Press, 1967), s.v. Raamiel', source_url='https://archive.org/details/dictionaryofange0000davi', verify_method='secondary-scholarship excerpt; substring-gated against Davidson Dictionary of Angels OCR; 2-column bleed eyeballed out', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_JM_RAAMIEL_SEC';
UPDATE entity_citations SET quote='"chief of the Supreme Mysteries," and "author" of the famous.', work_title='Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (The Free Press, 1967), s.v. Raziel', source_url='https://archive.org/details/dictionaryofange0000davi', verify_method='secondary-scholarship excerpt; substring-gated against Davidson Dictionary of Angels OCR; 2-column bleed eyeballed out', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_JM_RAZIEL_SEC';
UPDATE entity_citations SET quote='Has been described as "the left-hand cherub of the Ark.', work_title='Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (The Free Press, 1967), s.v. Sandalphon', source_url='https://archive.org/details/dictionaryofange0000davi', verify_method='secondary-scholarship excerpt; substring-gated against Davidson Dictionary of Angels OCR; 2-column bleed eyeballed out', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_JM_SANDALPHON_SEC';
UPDATE entity_citations SET quote='"prince of the face.', work_title='Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (The Free Press, 1967), s.v. Sar ha-Panim', source_url='https://archive.org/details/dictionaryofange0000davi', verify_method='secondary-scholarship excerpt; substring-gated against Davidson Dictionary of Angels OCR; 2-column bleed eyeballed out', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_JM_SAR_HAPANIM_SEC';
UPDATE entity_citations SET quote='An angel equated with Metatron.', work_title='Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (The Free Press, 1967), s.v. Yahoel', source_url='https://archive.org/details/dictionaryofange0000davi', verify_method='secondary-scholarship excerpt; substring-gated against Davidson Dictionary of Angels OCR; 2-column bleed eyeballed out', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_JM_YAHOEL_SEC';
UPDATE entity_citations SET quote='A ruler of the order of cherubim, and prince of the planet Saturn.', work_title='Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (The Free Press, 1967), s.v. Zaphiel', source_url='https://archive.org/details/dictionaryofange0000davi', verify_method='secondary-scholarship excerpt; substring-gated against Davidson Dictionary of Angels OCR; 2-column bleed eyeballed out', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_JM_ZAPHIEL_SEC';
UPDATE entity_citations SET quote='As Zophiel, is the ruler of the order of cherubim (the rabbinic ophanim.', work_title='Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (The Free Press, 1967), s.v. Zaphkiel', source_url='https://archive.org/details/dictionaryofange0000davi', verify_method='secondary-scholarship excerpt; substring-gated against Davidson Dictionary of Angels OCR; 2-column bleed eyeballed out', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_JM_ZAPHKIEL_SEC';
UPDATE entity_citations SET quote='The patriarch Enoch, on his translation to Heaven (Genesis 5 :24), became Metatron.', work_title='Gustav Davidson, A Dictionary of Angels, Including the Fallen Angels (The Free Press, 1967), s.v. Metatron', source_url='https://archive.org/details/dictionaryofange0000davi', verify_method='secondary-scholarship excerpt; substring-gated against Davidson Dictionary of Angels OCR; 2-column bleed eyeballed out', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_JM_METATRON_SEC';
COMMIT;
