-- Upgrade pointer-only Testament of Solomon citations to verbatim (Conybeare).
BEGIN;
UPDATE entity_citations SET quote='I am the first decans of the zodiacal circle, and I am called the ram, and with me are these two.', evidence_grade='primary-verbatim', work_title='The Testament of Solomon (Conybeare)', translator='F. C. Conybeare', translation_year=1898, source_url='https://www.esotericarchives.com/solomon/testamen.htm', verify_method='pointer→verbatim upgrade; substring-gated against Conybeare Testament of Solomon (genuine substring; footnote markers excluded)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_LAT_DECANS_SEC';
UPDATE entity_citations SET quote='I, O Lord, am called Ruax, and I cause the heads of men to be idle, and I pillage their brows. But let me only hear the words, ''Michael, imprison Ruax,'' and at once I retreat.', evidence_grade='primary-verbatim', work_title='The Testament of Solomon (Conybeare)', translator='F. C. Conybeare', translation_year=1898, source_url='https://www.esotericarchives.com/solomon/testamen.htm', verify_method='pointer→verbatim upgrade; substring-gated against Conybeare Testament of Solomon (genuine substring; footnote markers excluded)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_LAT_DECAN_RUAX_SEC';
UPDATE entity_citations SET quote='I am called Barsafael, and I cause those who are subject to my hour to feel the pain of migraine. If only I hear the words, ''Gabriel, imprison Barsafael,'' at once I retreat.', evidence_grade='primary-verbatim', work_title='The Testament of Solomon (Conybeare)', translator='F. C. Conybeare', translation_year=1898, source_url='https://www.esotericarchives.com/solomon/testamen.htm', verify_method='pointer→verbatim upgrade; substring-gated against Conybeare Testament of Solomon (genuine substring; footnote markers excluded)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_LAT_DECAN_BARSAPHAEL_SEC';
UPDATE entity_citations SET quote='I am called Arotosael. I do harm to eyes, and grievously injure them. Only let me hear the words, ''Uriel, imprison Aratosael'' (sic), at once I retreat.', evidence_grade='primary-verbatim', work_title='The Testament of Solomon (Conybeare)', translator='F. C. Conybeare', translation_year=1898, source_url='https://www.esotericarchives.com/solomon/testamen.htm', verify_method='pointer→verbatim upgrade; substring-gated against Conybeare Testament of Solomon (genuine substring; footnote markers excluded)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_LAT_DECAN_ARTOSAEL_SEC';
UPDATE entity_citations SET quote='I am called Sphendonael. I cause tumours of the parotid gland, and inflammations of the tonsils, and tetanic recurvation.', evidence_grade='primary-verbatim', work_title='The Testament of Solomon (Conybeare)', translator='F. C. Conybeare', translation_year=1898, source_url='https://www.esotericarchives.com/solomon/testamen.htm', verify_method='pointer→verbatim upgrade; substring-gated against Conybeare Testament of Solomon (genuine substring; footnote markers excluded)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_LAT_DECAN_SPHENDONAEL_SEC';
UPDATE entity_citations SET quote='I am called Envy. For I delight to devour heads, being desirous to secure for myself a head; but I do not eat enough, but am anxious to have such a head as thou hast.', evidence_grade='primary-verbatim', work_title='The Testament of Solomon (Conybeare)', translator='F. C. Conybeare', translation_year=1898, source_url='https://www.esotericarchives.com/solomon/testamen.htm', verify_method='pointer→verbatim upgrade; substring-gated against Conybeare Testament of Solomon (genuine substring; footnote markers excluded)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_LAT_ENVY_DEMON_SEC';
UPDATE entity_citations SET quote='I am called Hephesimireth, and cause lingering disease. If you throw salt, rubbed in the hand, into oil and smear it on the patient, saying: ''Seraphim, Cherubim, help me!'' I at once retire.', evidence_grade='primary-verbatim', work_title='The Testament of Solomon (Conybeare)', translator='F. C. Conybeare', translation_year=1898, source_url='https://www.esotericarchives.com/solomon/testamen.htm', verify_method='pointer→verbatim upgrade; substring-gated against Conybeare Testament of Solomon (genuine substring; footnote markers excluded)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_LAT_DECAN_HEPHESIKIRETH_SEC';
UPDATE entity_citations SET quote='I am a spirit made into a god among men, but now brought to naught by the ring and wisdom vouchsafed to thee by God. Now I am the so-called winged dragon.', evidence_grade='primary-verbatim', work_title='The Testament of Solomon (Conybeare)', translator='F. C. Conybeare', translation_year=1898, source_url='https://www.esotericarchives.com/solomon/testamen.htm', verify_method='pointer→verbatim upgrade; substring-gated against Conybeare Testament of Solomon (genuine substring; footnote markers excluded)', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_LAT_WINGED_DRAGON_SEC';
COMMIT;
