-- Dixon-Kennedy Slavic secondary excerpts.
BEGIN;
UPDATE entity_citations SET quote='The spirit of the bathhouse (banya), described as a wizened little man.', work_title='Mike Dixon-Kennedy, Encyclopedia of Russian and Slavic Myth and Legend (ABC-CLIO, 1998), s.v. Bannik', source_url='https://archive.org/details/encyclopediaofru0000dixo', verify_method='secondary-scholarship excerpt; substring-gated against Dixon-Kennedy (1998) OCR; figure verified against entry', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_SLAV_BANNIK_SEC';
UPDATE entity_citations SET quote='The Black God, whose name is a compound of the words chernyi (black) and bog.', work_title='Mike Dixon-Kennedy, Encyclopedia of Russian and Slavic Myth and Legend (ABC-CLIO, 1998), s.v. Chernobog', source_url='https://archive.org/details/encyclopediaofru0000dixo', verify_method='secondary-scholarship excerpt; substring-gated against Dixon-Kennedy (1998) OCR; figure verified against entry', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_SLAV_CHERNOBOG_SEC';
UPDATE entity_citations SET quote='Khor, or Khors, a sun god, was the offspring of Perun and Mokosh.', work_title='Mike Dixon-Kennedy, Encyclopedia of Russian and Slavic Myth and Legend (ABC-CLIO, 1998), s.v. Khors', source_url='https://archive.org/details/encyclopediaofru0000dixo', verify_method='secondary-scholarship excerpt; substring-gated against Dixon-Kennedy (1998) OCR; figure verified against entry', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_SLAV_KHORS_SEC';
UPDATE entity_citations SET quote='A female domestic spirit sometimes described as the wife of the domovoi.', work_title='Mike Dixon-Kennedy, Encyclopedia of Russian and Slavic Myth and Legend (ABC-CLIO, 1998), s.v. Kikimora', source_url='https://archive.org/details/encyclopediaofru0000dixo', verify_method='secondary-scholarship excerpt; substring-gated against Dixon-Kennedy (1998) OCR; figure verified against entry', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_SLAV_KIKIMORA_SEC';
UPDATE entity_citations SET quote='The goddess of peace, water, magic, and herbs.', work_title='Mike Dixon-Kennedy, Encyclopedia of Russian and Slavic Myth and Legend (ABC-CLIO, 1998), s.v. Kupala', source_url='https://archive.org/details/encyclopediaofru0000dixo', verify_method='secondary-scholarship excerpt; substring-gated against Dixon-Kennedy (1998) OCR; figure verified against entry', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_SLAV_KUPALA_SEC';
UPDATE entity_citations SET quote='The goddess of beauty, female counterpart of Lado.', work_title='Mike Dixon-Kennedy, Encyclopedia of Russian and Slavic Myth and Legend (ABC-CLIO, 1998), s.v. Lada', source_url='https://archive.org/details/encyclopediaofru0000dixo', verify_method='secondary-scholarship excerpt; substring-gated against Dixon-Kennedy (1998) OCR; figure verified against entry', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_SLAV_LADA_SEC';
UPDATE entity_citations SET quote='A fertility goddess widely worshiped.', work_title='Mike Dixon-Kennedy, Encyclopedia of Russian and Slavic Myth and Legend (ABC-CLIO, 1998), s.v. Mokosh', source_url='https://archive.org/details/encyclopediaofru0000dixo', verify_method='secondary-scholarship excerpt; substring-gated against Dixon-Kennedy (1998) OCR; figure verified against entry', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_SLAV_MOKOSH_SEC';
UPDATE entity_citations SET quote='An ancient rain and fertility god.', work_title='Mike Dixon-Kennedy, Encyclopedia of Russian and Slavic Myth and Legend (ABC-CLIO, 1998), s.v. Rod', source_url='https://archive.org/details/encyclopediaofru0000dixo', verify_method='secondary-scholarship excerpt; substring-gated against Dixon-Kennedy (1998) OCR; figure verified against entry', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_SLAV_ROD_SEC';
UPDATE entity_citations SET quote='"Wind Lord," the god of air.', work_title='Mike Dixon-Kennedy, Encyclopedia of Russian and Slavic Myth and Legend (ABC-CLIO, 1998), s.v. Stribog', source_url='https://archive.org/details/encyclopediaofru0000dixo', verify_method='secondary-scholarship excerpt; substring-gated against Dixon-Kennedy (1998) OCR; figure verified against entry', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_SLAV_STRIBOG_SEC';
UPDATE entity_citations SET quote='"Very Hot," god of the sky.', work_title='Mike Dixon-Kennedy, Encyclopedia of Russian and Slavic Myth and Legend (ABC-CLIO, 1998), s.v. Svarog', source_url='https://archive.org/details/encyclopediaofru0000dixo', verify_method='secondary-scholarship excerpt; substring-gated against Dixon-Kennedy (1998) OCR; figure verified against entry', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_SLAV_SVAROG_SEC';
UPDATE entity_citations SET quote='The god of fire and prophecy, the son of Svarog.', work_title='Mike Dixon-Kennedy, Encyclopedia of Russian and Slavic Myth and Legend (ABC-CLIO, 1998), s.v. Svarozhich', source_url='https://archive.org/details/encyclopediaofru0000dixo', verify_method='secondary-scholarship excerpt; substring-gated against Dixon-Kennedy (1998) OCR; figure verified against entry', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_SLAV_SVAROZHICH_SEC';
UPDATE entity_citations SET quote='A nature deity who was regarded as the patron of cattle and of merchants.', work_title='Mike Dixon-Kennedy, Encyclopedia of Russian and Slavic Myth and Legend (ABC-CLIO, 1998), s.v. Veles', source_url='https://archive.org/details/encyclopediaofru0000dixo', verify_method='secondary-scholarship excerpt; substring-gated against Dixon-Kennedy (1998) OCR; figure verified against entry', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_SLAV_VELES_SEC';
UPDATE entity_citations SET quote='The god of thunder and rain.', work_title='Mike Dixon-Kennedy, Encyclopedia of Russian and Slavic Myth and Legend (ABC-CLIO, 1998), s.v. Perun', source_url='https://archive.org/details/encyclopediaofru0000dixo', verify_method='secondary-scholarship excerpt; substring-gated against Dixon-Kennedy (1998) OCR; figure verified against entry', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_SLAV_PERUN_SEC';
UPDATE entity_citations SET quote='Goddess of the hunt, paralleling the Roman Diana.', work_title='Mike Dixon-Kennedy, Encyclopedia of Russian and Slavic Myth and Legend (ABC-CLIO, 1998), s.v. Devana', source_url='https://archive.org/details/encyclopediaofru0000dixo', verify_method='secondary-scholarship excerpt; substring-gated against Dixon-Kennedy (1998) OCR; figure verified against entry', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_SLAV_DEVANA_SEC';
UPDATE entity_citations SET quote='Goddess of fertility and of the dead.', work_title='Mike Dixon-Kennedy, Encyclopedia of Russian and Slavic Myth and Legend (ABC-CLIO, 1998), s.v. Zhiva', source_url='https://archive.org/details/encyclopediaofru0000dixo', verify_method='secondary-scholarship excerpt; substring-gated against Dixon-Kennedy (1998) OCR; figure verified against entry', needs_review=true, review_reason='In-copyright reference work — brief attributed excerpt for scholarly identification; verify against the print edition.', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_SLAV_ZHIVA_SEC';
COMMIT;
