-- Norse primary verbatim from Eddas + Germania.
BEGIN;
UPDATE entity_citations SET quote='Loud bays Garm before the Gnupa-cave, his bonds he rends asunder; and the wolf runs.', evidence_grade='primary-verbatim', source_id='SRC_POETIC_EDDA', work_title='Poetic Edda', translator='Benjamin Thorpe', translation_year=1866, source_url='https://www.gutenberg.org/ebooks/14726', verify_method='pointer→verbatim upgrade; substring-gated against Poetic Edda', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_NOR_GARM_POE_PTR';
UPDATE entity_citations SET quote='Sol among men ''tis called, but with the gods sunna, the dwarfs call it Dvalinn''s leika.', evidence_grade='primary-verbatim', source_id='SRC_POETIC_EDDA', work_title='Poetic Edda', translator='Benjamin Thorpe', translation_year=1866, source_url='https://www.gutenberg.org/ebooks/14726', verify_method='pointer→verbatim upgrade; substring-gated against Poetic Edda', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_NOR_SOL_SEC';
UPDATE entity_citations SET quote='Skoll the wolf is named, that the fair-faced goddess to the ocean chases.', evidence_grade='primary-verbatim', source_id='SRC_POETIC_EDDA', work_title='Poetic Edda', translator='Benjamin Thorpe', translation_year=1866, source_url='https://www.gutenberg.org/ebooks/14726', verify_method='pointer→verbatim upgrade; substring-gated against Poetic Edda', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_NOR_SKOLL_SEC';
UPDATE entity_citations SET quote='Heimdal is the name of one. He is also called the white-asa.', evidence_grade='primary-verbatim', source_id='SRC_PROSE_EDDA', work_title='Snorri Sturluson, Prose Edda (Anderson)', translator='Rasmus B. Anderson', translation_year=1880, source_url='https://www.gutenberg.org/ebooks/18947', verify_method='pointer→verbatim upgrade; substring-gated against Snorri Sturluson, Prose Edda (Anderson)', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_NOR_HEIMDALL_SEC';
UPDATE entity_citations SET quote='Then the asas became aware that Ran had a net in which she caught all men who perish at sea.', evidence_grade='primary-verbatim', source_id='SRC_PROSE_EDDA', work_title='Snorri Sturluson, Prose Edda (Anderson)', translator='Rasmus B. Anderson', translation_year=1880, source_url='https://www.gutenberg.org/ebooks/18947', verify_method='pointer→verbatim upgrade; substring-gated against Snorri Sturluson, Prose Edda (Anderson)', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_NOR_RAN_SEC';
UPDATE entity_citations SET quote='Hoder hight one of the asas, who is blind, but exceedingly strong.', evidence_grade='primary-verbatim', source_id='SRC_PROSE_EDDA', work_title='Snorri Sturluson, Prose Edda (Anderson)', translator='Rasmus B. Anderson', translation_year=1880, source_url='https://www.gutenberg.org/ebooks/18947', verify_method='pointer→verbatim upgrade; substring-gated against Snorri Sturluson, Prose Edda (Anderson)', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_NOR_HODR_SEC';
UPDATE entity_citations SET quote='Uller is the name of one, who is a son of Sif, and a step-son of Thor.', evidence_grade='primary-verbatim', source_id='SRC_PROSE_EDDA', work_title='Snorri Sturluson, Prose Edda (Anderson)', translator='Rasmus B. Anderson', translation_year=1880, source_url='https://www.gutenberg.org/ebooks/18947', verify_method='pointer→verbatim upgrade; substring-gated against Snorri Sturluson, Prose Edda (Anderson)', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_NOR_ULLR_SEC';
UPDATE entity_citations SET quote='Eir, who is the best leech.', evidence_grade='primary-verbatim', source_id='SRC_PROSE_EDDA', work_title='Snorri Sturluson, Prose Edda (Anderson)', translator='Rasmus B. Anderson', translation_year=1880, source_url='https://www.gutenberg.org/ebooks/18947', verify_method='pointer→verbatim upgrade; substring-gated against Snorri Sturluson, Prose Edda (Anderson)', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_NOR_EIR_SEC';
UPDATE entity_citations SET quote='She keeps in a box those apples of which the gods eat when they grow old, and then they become young again.', evidence_grade='primary-verbatim', source_id='SRC_PROSE_EDDA', work_title='Snorri Sturluson, Prose Edda (Anderson)', translator='Rasmus B. Anderson', translation_year=1880, source_url='https://www.gutenberg.org/ebooks/18947', verify_method='pointer→verbatim upgrade; substring-gated against Snorri Sturluson, Prose Edda (Anderson)', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_NOR_IDUN_SEC';
UPDATE entity_citations SET quote='She was the fairest of all women, her hair was like gold.', evidence_grade='primary-verbatim', source_id='SRC_PROSE_EDDA', work_title='Snorri Sturluson, Prose Edda (Anderson)', translator='Rasmus B. Anderson', translation_year=1880, source_url='https://www.gutenberg.org/ebooks/18947', verify_method='pointer→verbatim upgrade; substring-gated against Snorri Sturluson, Prose Edda (Anderson)', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_NOR_SIF_SEC';
UPDATE entity_citations SET quote='There is yet an asa, whose name is Tyr. He is very daring and stout-hearted.', evidence_grade='primary-verbatim', source_id='SRC_PROSE_EDDA', work_title='Snorri Sturluson, Prose Edda (Anderson)', translator='Rasmus B. Anderson', translation_year=1880, source_url='https://www.gutenberg.org/ebooks/18947', verify_method='pointer→verbatim upgrade; substring-gated against Snorri Sturluson, Prose Edda (Anderson)', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_NOR_TYR_SEC';
UPDATE entity_citations SET quote='Hel he cast into Niflheim, and gave her power over nine worlds.', evidence_grade='primary-verbatim', source_id='SRC_PROSE_EDDA', work_title='Snorri Sturluson, Prose Edda (Anderson)', translator='Rasmus B. Anderson', translation_year=1880, source_url='https://www.gutenberg.org/ebooks/18947', verify_method='pointer→verbatim upgrade; substring-gated against Snorri Sturluson, Prose Edda (Anderson)', verified_on=DATE '2026-06-27' WHERE citation_id='CIT_NOR_HEL_SEC';
COMMIT;
