-- Upgrade pointer-only Lebor Gabála citations to verbatim (Macalister Vol. IV).
BEGIN;
UPDATE entity_citations SET quote='Fotla was wife of Mac Cecht, Banba of Mac Cuill, Eriu of Mac Greine. Those were the three daughters of Fiachna son of Delbaeth. Emmas daughter of Etarlam s.', evidence_grade='primary-verbatim', work_title='Lebor Gabála Érenn (Macalister, Vol. IV)', translator='R. A. S. Macalister', translation_year=1941, source_url='https://archive.org/details/leborgablare04macauoft', verify_method='pointer→verbatim upgrade; substring-gated against Macalister Vol. IV OCR (English-translation regions); eyeballed for Irish/apparatus/OCR-column bleed', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_CEL_BANBA_SEC';
UPDATE entity_citations SET quote='Fotla was wife of Mac Cecht, Banba was the wife of Mac Cuill, Eriu was wife of Mac Greine : those were the three daughters of Fiachna s. Delbaeth. Ernmas daughter of Etarlam s.', evidence_grade='primary-verbatim', work_title='Lebor Gabála Érenn (Macalister, Vol. IV)', translator='R. A. S. Macalister', translation_year=1941, source_url='https://archive.org/details/leborgablare04macauoft', verify_method='pointer→verbatim upgrade; substring-gated against Macalister Vol. IV OCR (English-translation regions); eyeballed for Irish/apparatus/OCR-column bleed', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_CEL_FODLA_SEC';
UPDATE entity_citations SET quote='Fotla was wife of Mac Cecht, Banba was the wife of Mac Cuill, Eriu was wife of Mac Greine : those were the three daughters of Fiachna s. Delbaeth. Ernmas daughter of Etarlam s.', evidence_grade='primary-verbatim', work_title='Lebor Gabála Érenn (Macalister, Vol. IV)', translator='R. A. S. Macalister', translation_year=1941, source_url='https://archive.org/details/leborgablare04macauoft', verify_method='pointer→verbatim upgrade; substring-gated against Macalister Vol. IV OCR (English-translation regions); eyeballed for Irish/apparatus/OCR-column bleed', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_CEL_ERIU_SEC';
UPDATE entity_citations SET quote='Brigid the poetess, daughter of The Dagda, had certain supernatural animals, and, "after rapine," three demoniac shouts were heard among them. Each of these four paragraphs has a certain individuality.', evidence_grade='primary-verbatim', work_title='Lebor Gabála Érenn (Macalister, Vol. IV)', translator='R. A. S. Macalister', translation_year=1941, source_url='https://archive.org/details/leborgablare04macauoft', verify_method='pointer→verbatim upgrade; substring-gated against Macalister Vol. IV OCR (English-translation regions); eyeballed for Irish/apparatus/OCR-column bleed', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_CEL_BRIGID_SEC';
UPDATE entity_citations SET quote='Ernmas d. Etarlam was mother of those women : and she was mother of Fiachna and Ollom. Ernmas had three other daughters, Badb, Macha, Morrigu : and Ana, of whom are called the Paps of Ana in Urluachair, was her seventh daughter. Badb and Neman were the two wives of Net s.', evidence_grade='primary-verbatim', work_title='Lebor Gabála Érenn (Macalister, Vol. IV)', translator='R. A. S. Macalister', translation_year=1941, source_url='https://archive.org/details/leborgablare04macauoft', verify_method='pointer→verbatim upgrade; substring-gated against Macalister Vol. IV OCR (English-translation regions); eyeballed for Irish/apparatus/OCR-column bleed', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_CEL_ERNMAS_SEC';
UPDATE entity_citations SET quote='The three sons of Cermad son of The Dagda were Mac Civill, Mac Cecht, Mac Greine : Sethor and Tethor and Cethor were their names. Fotla and Banba and Eriu were their three wives.', evidence_grade='primary-verbatim', work_title='Lebor Gabála Érenn (Macalister, Vol. IV)', translator='R. A. S. Macalister', translation_year=1941, source_url='https://archive.org/details/leborgablare04macauoft', verify_method='pointer→verbatim upgrade; substring-gated against Macalister Vol. IV OCR (English-translation regions); eyeballed for Irish/apparatus/OCR-column bleed', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_CEL_DAGDA_SEC';
UPDATE entity_citations SET quote='Lug was forty years in the kingship of Ireland after the last battle of Mag Tuired, and fortnight after Lugnasad.', evidence_grade='primary-verbatim', work_title='Lebor Gabála Érenn (Macalister, Vol. IV)', translator='R. A. S. Macalister', translation_year=1941, source_url='https://archive.org/details/leborgablare04macauoft', verify_method='pointer→verbatim upgrade; substring-gated against Macalister Vol. IV OCR (English-translation regions); eyeballed for Irish/apparatus/OCR-column bleed', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_CEL_LUGH_SEC';
UPDATE entity_citations SET quote='He had an arm of silver with the full activity of any arm in each finger and in each joint, which Dian Cecht the leech put upon him, Creidne the wright giving him help.', evidence_grade='primary-verbatim', work_title='Lebor Gabála Érenn (Macalister, Vol. IV)', translator='R. A. S. Macalister', translation_year=1941, source_url='https://archive.org/details/leborgablare04macauoft', verify_method='pointer→verbatim upgrade; substring-gated against Macalister Vol. IV OCR (English-translation regions); eyeballed for Irish/apparatus/OCR-column bleed', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_CEL_DIANCECHT_SEC';
UPDATE entity_citations SET quote='Though some say that the Tuatha De Danann were demons, seeing that they came unperceived [and they them- selves said that it was in dark clouds that t', evidence_grade='primary-verbatim', work_title='Lebor Gabála Érenn (Macalister, Vol. IV)', translator='R. A. S. Macalister', translation_year=1941, source_url='https://archive.org/details/leborgablare04macauoft', verify_method='pointer→verbatim upgrade; substring-gated against Macalister Vol. IV OCR (English-translation regions); eyeballed for Irish/apparatus/OCR-column bleed', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_CEL_TUATHA_SEC';
UPDATE entity_citations SET quote='And it is they who broke the battle of Mag Tuired against the Fomoraig, and the previous battle against the FirBolg.', evidence_grade='primary-verbatim', work_title='Lebor Gabála Érenn (Macalister, Vol. IV)', translator='R. A. S. Macalister', translation_year=1941, source_url='https://archive.org/details/leborgablare04macauoft', verify_method='pointer→verbatim upgrade; substring-gated against Macalister Vol. IV OCR (English-translation regions); eyeballed for Irish/apparatus/OCR-column bleed', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_CEL_FOMORIANS_SEC';
COMMIT;
