-- Bunson Encyclopedia of Ancient Rome secondary excerpts.
BEGIN;
UPDATE entity_citations SET quote='Roman divinity who, as her name would suggest (caro, flesh), was the protectoress of health and wellbeing.', work_title='Matthew Bunson, Encyclopedia of Ancient Rome (Facts on File, 1994), s.v. Carna', verify_method='secondary-scholarship excerpt; substring-gated against Bunson Encyclopedia of Ancient Rome OCR', needs_review=true, review_reason='Reference encyclopedia (general reference publisher, not academic press) — brief attributed excerpt; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ROM_CARNA_SEC';
UPDATE entity_citations SET quote='An Italian god of several identities whose festival, CONSUALIA, was held on the days of August 19 or 21 and December 15.', work_title='Matthew Bunson, Encyclopedia of Ancient Rome (Facts on File, 1994), s.v. Consus', verify_method='secondary-scholarship excerpt; substring-gated against Bunson Encyclopedia of Ancient Rome OCR', needs_review=true, review_reason='Reference encyclopedia (general reference publisher, not academic press) — brief attributed excerpt; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ROM_CONSUS_SEC';
UPDATE entity_citations SET quote='Ancient Roman goddess whose special area of divine concern was the fertility of the annual crops.', work_title='Matthew Bunson, Encyclopedia of Ancient Rome (Facts on File, 1994), s.v. Dea Dia', verify_method='secondary-scholarship excerpt; substring-gated against Bunson Encyclopedia of Ancient Rome OCR', needs_review=true, review_reason='Reference encyclopedia (general reference publisher, not academic press) — brief attributed excerpt; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ROM_DEA_DIA_SEC';
UPDATE entity_citations SET quote='Roman goddess of faith, especially good faith.', work_title='Matthew Bunson, Encyclopedia of Ancient Rome (Facts on File, 1994), s.v. Fides', verify_method='secondary-scholarship excerpt; substring-gated against Bunson Encyclopedia of Ancient Rome OCR', needs_review=true, review_reason='Reference encyclopedia (general reference publisher, not academic press) — brief attributed excerpt; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ROM_FIDES_SEC';
UPDATE entity_citations SET quote='The Roman god of doorways, beginnings, the past, and the future.', work_title='Matthew Bunson, Encyclopedia of Ancient Rome (Facts on File, 1994), s.v. Janus', verify_method='secondary-scholarship excerpt; substring-gated against Bunson Encyclopedia of Ancient Rome OCR', needs_review=true, review_reason='Reference encyclopedia (general reference publisher, not academic press) — brief attributed excerpt; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ROM_JANUS_SEC';
UPDATE entity_citations SET quote='Roman goddess of the fruit trees.', work_title='Matthew Bunson, Encyclopedia of Ancient Rome (Facts on File, 1994), s.v. Pomona', verify_method='secondary-scholarship excerpt; substring-gated against Bunson Encyclopedia of Ancient Rome OCR', needs_review=true, review_reason='Reference encyclopedia (general reference publisher, not academic press) — brief attributed excerpt; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ROM_POMONA_SEC';
UPDATE entity_citations SET quote='A Roman deity of nature whose main attributes were destructive powers through rust or blight.', work_title='Matthew Bunson, Encyclopedia of Ancient Rome (Facts on File, 1994), s.v. Robigus', verify_method='secondary-scholarship excerpt; substring-gated against Bunson Encyclopedia of Ancient Rome OCR', needs_review=true, review_reason='Reference encyclopedia (general reference publisher, not academic press) — brief attributed excerpt; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ROM_ROBIGUS_SEC';
UPDATE entity_citations SET quote='The divine personification of the city of Rome, a means of expressing in religious terms the greatness of the Eternal City, of the empire and the Republic.', work_title='Matthew Bunson, Encyclopedia of Ancient Rome (Facts on File, 1994), s.v. Roma', verify_method='secondary-scholarship excerpt; substring-gated against Bunson Encyclopedia of Ancient Rome OCR', needs_review=true, review_reason='Reference encyclopedia (general reference publisher, not academic press) — brief attributed excerpt; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ROM_ROMA_SEC';
UPDATE entity_citations SET quote='Roman god of the sun, called by the Greeks Helios.', work_title='Matthew Bunson, Encyclopedia of Ancient Rome (Facts on File, 1994), s.v. Sol Invictus', verify_method='secondary-scholarship excerpt; substring-gated against Bunson Encyclopedia of Ancient Rome OCR', needs_review=true, review_reason='Reference encyclopedia (general reference publisher, not academic press) — brief attributed excerpt; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ROM_SOL_INVICTUS_SEC';
UPDATE entity_citations SET quote='A Roman god, probably of the changing seasons; his name was based on the Latin verto, or change.', work_title='Matthew Bunson, Encyclopedia of Ancient Rome (Facts on File, 1994), s.v. Vertumnus', verify_method='secondary-scholarship excerpt; substring-gated against Bunson Encyclopedia of Ancient Rome OCR', needs_review=true, review_reason='Reference encyclopedia (general reference publisher, not academic press) — brief attributed excerpt; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ROM_VERTUMNUS_SEC';
UPDATE entity_citations SET quote='Also Volcanus, and to the Greeks, Hephaestus; the great fire god of the Romans, whose power was always on display at the volcanos of Etna or VESUVIUS.', work_title='Matthew Bunson, Encyclopedia of Ancient Rome (Facts on File, 1994), s.v. Vulcan', verify_method='secondary-scholarship excerpt; substring-gated against Bunson Encyclopedia of Ancient Rome OCR', needs_review=true, review_reason='Reference encyclopedia (general reference publisher, not academic press) — brief attributed excerpt; verify against the print edition.', verified_on=DATE '2026-06-26' WHERE citation_id='CIT_ROM_VULCAN_SEC';
COMMIT;
